- .travis.yml
This pr adds the initial travis manifest that allows a new PR to trigger `go test ./...`.
The manifest file should be changed to run tests and build inside an container.
cc/ @hasbro17 @spahl @Verolop
> ci: add travis yaml

- commands/operator-sdk/cmd/generate.go
- commands/operator-sdk/cmd/generate/olm_catalog.go
- pkg/generator/gen_olm_catalog.go
- pkg/generator/generator.go
- pkg/generator/olm_catalog_tmpl.go
ALM is now OLM: https://github.com/operator-framework/operator-lifecycle-manager
This PR renames all references in the code.
> Rename alm to olm

- pkg/k8sclient/client.go
I like to be able to test locally before I deploy to the cluster. This PR allows this through an environment variable.
```
$ KUBERNETES_CONFIG=~/.kube/config go run cmd/app-operator/main.go
```
> Add support for running the operator out of cluster 

- README.md
- doc/user-guide.md
The README and user-guide will now expect the SDK to be installed from the master branch for all commands to work as expected.
> *: use master branch for docs

- Gopkg.lock
- commands/operator-sdk/cmd/build.go
- commands/operator-sdk/cmd/cmdutil/util.go
- commands/operator-sdk/cmd/root.go
- commands/operator-sdk/cmd/up.go
- commands/operator-sdk/cmd/up/local.go
- pkg/k8sclient/client.go
- pkg/util/k8sutil/constants.go
This pr adds a new command call `up` and its subcommand `local`.
When`operator-sdk up local` is called, the operator is run locally on developer's machine with the access to a kubernetes cluster via the `--kubeconfig` flag.
ref: https://github.com/operator-framework/operator-sdk/issues/142
cc/ @hasbro17 @spahl
> operator-sdk/cmd: add up command

- commands/operator-sdk/cmd/new.go
Looks like this was missed in #28
> Fixing usage syntax s/api-group/api-version/

- commands/operator-sdk/cmd/completion.go
- commands/operator-sdk/cmd/completion/bash.go
- commands/operator-sdk/cmd/completion/zsh.go
Bash completions can be set up in your shell by running:
```bash
. <(operator-sdk completion bash)
```
`operator-sdk completion zsh` will generate zsh completions too!
> commands/opreator-sdk: command to autogenerate shell completions

- pkg/generator/generator.go
- pkg/generator/gitignore_tmpls.go
The top level ignore golang, vim, and emacs files
The tmp/.gitignore ignores tmp/_output
> pkg:generator: Generate .gitignore at top and for tmp/_output

- pkg/generator/deploy_tmpl.go
- pkg/generator/gen_deploy_test.go
- pkg/generator/gen_main.go
- pkg/generator/generator_test.go
- pkg/generator/handler_tmpl.go
- pkg/generator/main_tmpl.go
- pkg/util/k8sutil/constants.go
- pkg/util/k8sutil/k8sutil.go
This will make it, by default, watch for CRs in the same namespace as the
operator and it will create the busybox pods in that namespace as well.
Resolves #187
> pkg/generator: Work in my namespace, not default

- example/memcached-operator/handler.go.tmpl
- pkg/generator/generator_test.go
- pkg/generator/handler_tmpl.go
- pkg/sdk/handler.go
- pkg/sdk/informer-sync.go
- pkg/sdk/types.go
Addressing #161 
This PR removes the custom Context type defined in `pkg/sdk/types.go`. Its better to use the default golang context type.
> pkg: remove custom Context type

- pkg/generator/gen_api_register_test.go
- pkg/generator/gen_api_types_test.go
- pkg/generator/gen_build_test.go
- pkg/generator/gen_codegen_test.go
- pkg/generator/gen_config_test.go
- pkg/generator/gen_deploy_test.go
- pkg/generator/gen_deps_test.go
- pkg/generator/gen_handler_test.go
- pkg/generator/gen_main_test.go
- pkg/generator/test_constants.go
Refer to #252 
This PR change test failure output format for more lisibility. Newline have been add in output
New output now like:
```shell
$ make test
./hack/test
?   	github.com/operator-framework/operator-sdk/commands/operator-sdk	[no test files]
?   	github.com/operator-framework/operator-sdk/commands/operator-sdk/cmd	[no test files]
?   	github.com/operator-framework/operator-sdk/commands/operator-sdk/cmd/cmdutil	[no test files]
?   	github.com/operator-framework/operator-sdk/commands/operator-sdk/cmd/completion	[no test files]
?   	github.com/operator-framework/operator-sdk/commands/operator-sdk/cmd/generate	[no test files]
?   	github.com/operator-framework/operator-sdk/commands/operator-sdk/cmd/up	[no test files]
?   	github.com/operator-framework/operator-sdk/commands/operator-sdk …
```
> pkg/generator: Change test failure output format + TestGenTypes use const

- commands/operator-sdk/cmd/up/local.go
operator-flags gives the ability to pass flags to the local operator.
Fixes #255
> up local command: add flag operator-flags

- commands/operator-sdk/cmd/new.go
- doc/user-guide.md
I love that `cargo new` from the rust project initializes git after it creates
the stock files. I don't have to run that command myself. Make `operator-sdk new`
just call git init.
> commands/operator-sdk/cmd/new: initialize git on `new`

- doc/user-guide.md
Refers to #253 
@fanminshi Should we document `operator-sdk up local` in `README` ?
Feedbacks are welcome for `user-guide.md` proposal 😄
> doc/user-guide: Document operator-sdk up local

- CHANGELOG.md
- commands/operator-sdk/cmd/up/local.go
ref: #273 
This adds the `--namespace` flag to the up local command and the default value is the "default" namespace.
Example:
```sh
operator-sdk up local --namespace operator
```
Help output
```
$ operator-sdk up local --help
The operator-sdk up local command launches the operator on the local machine
by building the operator binary with the ability to access a
kubernetes cluster using a kubeconfig file.
Usage:
operator-sdk up local [flags]
Flags:
-h, --help                    help for local
--kubeconfig string       The file path to kubernetes configuration file; defaults to $HOME/.kube/config
--namespace string        The namespace where the operator watches for changes. (default "default")
--operator-flags string   The flags that the operator needs. Example: "--flag1 value1 …
```
> commands/operator-sdk/cmd/local: add namespace flag

- doc/user-guide.md
cc/ @etiennecoutaud @jhernandezb
> doc: modify user_guide with watched namespace fixed

- CHANGELOG.md
- pkg/k8sclient/client.go
This sets up a go routine to reset the restMapper at a 1 minute
interval so that new resources can be found in the cluster.
fixes #272
> pkg/k8sclient: add cache reset on 1 minute interval

- doc/sdk-cli-reference.md
started documentation for operator-sdk and added docs for build cmd
Refers #266
Is this a good place for the CLI documentation? @fanminshi
> doc/user-guide.md: add docs for cli cmd build

- doc/sdk-cli-reference.md
adds details and more examples for `operator-sdk up local` flags
Fixes #266
> doc/sdk-cli-reference: Adding details for up/local command.

- commands/operator-sdk/cmd/new.go
>  commands/operator-sdk: Add better error message when dep is not installed or not in path

- CHANGELOG.md
- pkg/k8sclient/client.go
Exposing the underlying kubernetes client will provide the flexibility of
allowing the user to perform more advanced actions that the SDK does not
provide out of the box. Often, more advanced actions are located in
subresources of the resource, like Pods().Evict and Pods().GetLogs. The SDK
does not provide access to these, and restricts the user to create, get,
update, delete and list.
Some examples:
```go
kubeClient := k8sclient.GetKubeClient()
// Evict pod
kubeClient.CoreV1().Pods("default").Evict(&v1beta1.Eviction{})
// Get pod logs
kubeClient.CoreV1().Pods("default").GetLogs("example", &v1.PodLogOptions{})
```
Resolves #190
> pkg/k8sclient: expose the kubernetes client

- pkg/generator/gen_handler_test.go
- pkg/generator/handler_tmpl.go
aliasing core/v1 to corev1 to avoid conflicts with generated code
Fixes: Issue #288
> generator: added alias for core/v1 to avoid conflicts

- pkg/generator/generator.go
> pkg/generator: final cleanup of generator.go

- pkg/sdk/informer-sync.go
- pkg/sdk/informer.go
Logs generated by the informer were not in the appropriate logging level.
The user can then change the log level for the sdk with the following:
```
logrus.SetLevel(logrus.DebugLevel)
```
Resolves #307
> pkg/sdk: update informer logging levels

- CHANGELOG.md
- pkg/generator/gen_deps.go
- pkg/generator/gen_deps_test.go
- pkg/generator/generator.go
- pkg/generator/generator_test.go
- pkg/generator/templates.go
- pkg/generator/test_constants.go
Fixes #226 
The k8s code-generators are now vendored for every project so they can be used locally instead of relying on `gcr.io/coreos-k8s-scale-testing/codegen:1.9.3`.
`k8s.io/code-generator` and `k8s.io/gengo` are not imports of an operator project so they need the [required](https://golang.github.io/dep/docs/Gopkg.toml.html#required) rule.
Secondly the generator should not generate `Gopkg.lock` just to ensure that the k8s.io dependencies are pinned at the respective revisions for a particular tag. That can be done in the `Gopkg.toml` file by specifying `revision = "xyz"`. I've kept the `version` field as a comment to indicate the tag for each revision.
With that change `tmp/codegen/update-generated.sh` can simply call the vendored code-generator.
/cc @fanminshi
> pkg/generator: vendor the code-generators, remove Gopkg.lock template

- Gopkg.lock
- Gopkg.toml
- pkg/generator/generator_test.go
Addressing Issue #318 
Now a failing generator test will print a pretty diff where red text is missing form the actual result and green text is extra in the actual result when compared to the expected output string. (These were tested by creating some garbage data, which was not committed as to not pollute the test cases.)
> pkg/generator: Add diff to test failures

- .travis.yml
we need to delete the existing vendored sdk pkg as the ln tool will not create the expected symlink over an existing directory.
> travis: Add rm of existing pkg dir

- Gopkg.lock
- pkg/generator/generator.go
- pkg/generator/generator_test.go
- pkg/generator/templates.go
- pkg/sdk/metrics.go
- pkg/util/k8sutil/constants.go
- pkg/util/k8sutil/k8sutil.go
- pkg/util/k8sutil/k8sutil_test.go
related to #222 discuss
This PR is similar to #241
\cc @hasbro17
> pkg/{sdk,generator} Expose Prometheus metrics port

- Gopkg.lock
- pkg/k8sclient/client.go
ref: #292 
k8sclient.client: refactored to create singleton pattern, remove `init`
At this time it is possible to abstract away the api for unit testing, the `init` 
method blocks the ability to do the unit tests because it tries to connect to 
the cluster. This refactor though not fully the direction you guys are going, is a temporary fix to allow unit testing of downstream code in operators using the sdk. In addition, this does not break the existing API and allows for no other code to change.
> k8sclient.client: refactored to create singleton pattern, remove init

- Gopkg.lock
The lock file is out of date for a fresh run of `dep ensure -update`.
Tested out the update with a manual build and run of the user-guide.
/cc @fanminshi
> Gopkg.lock: update dependencies

- README.md
- doc/user-guide.md
if copy-pasted or typed verbatim the clone would fail.
> readme: add protocol to URL

- CHANGELOG.md
- Gopkg.lock
- pkg/sdk/api.go
- pkg/sdk/informer-sync.go
- pkg/sdk/informer.go
- pkg/sdk/internal/metrics/metrics.go
this sets up the sdk to expose metrics by registering metrics with
prometheus.
it also adds the metrics as a type to be used by clients to update the
metrics.
> pkg/{sdk,sdk/metrics}: Adding default metrics

- test/e2e/e2eutil/check_util.go
- test/e2e/e2eutil/create_util.go
- test/e2e/memcached_test.go
This renames many variables in the e2e test to make the naming more
consistent and thus make the code more readable. It also makes a
small change to writing the new cr.yaml file to make it simpler and
changes the delete options for the cr's deletion to make them the
same as the rest of the deletion process.
This is one of the parts of PR #355 that is being split off for easier review.
> test/e2e: general cleanup and renaming of variables

- pkg/sdk/metrics.go
ref: #356 
/cc @fanminshi 
Setting up the operator metrics service was supposed to be best effort and not fail. With this `operator-sdk up local` should be fixed:
```sh
$ operator-sdk up local --namespace=haseeb
INFO[0000] Go Version: go1.10.2
INFO[0000] Go OS/Arch: darwin/amd64
INFO[0000] operator-sdk Version: 0.0.5+git
ERRO[0000] Failed to initialize service object for operator metrics: OPERATOR_NAME must be set
INFO[0000] Watching app.example.com/v1alpha1, App, haseeb, 5
```
> pkg/sdk: don't exit on failure to create metrics service

- test/e2e/framework/framework.go
- test/e2e/framework/main_entry.go
- test/e2e/main_test.go
- test/e2e/memcached_test.go
This will allow us to add more tests in the future without
duplicating code and will also allow us to parse command line options
more easily.
This is one of the parts of PR #355 that is being split off for easier review.
> test/e2e: add framework for e2e tests

- test/e2e/memcached_test.go
Currently, if the test fails, the teardown does not occur, which
may cause problems for future tests or local tests. It is also
cleaner to defer the teardown after creation of a resource instead
of lumping all the teardown together at the end of the function.
This is one of the parts of PR #355 that is being split off for easier review.
> test/e2e/memcached_test.go: defer teardown

- test/e2e/framework/framework.go
- test/e2e/memcached_test.go
These commits add the ability to run E2E tests on a local machine using an external repository for the image and using the GOPATH instead of TRAVIS_BUILD_DIR for the pkg symlink.
This is the last part of PR #355 that was split up for easier review.
> Allow running of E2E tests locally

- pkg/util/k8sutil/k8sutil.go
Creates a typed function for getting the decoder from the scheme
Adds method to set decoder func
Adds package var for the decoder fun
fixes #352
> util/k8sutil: add ability to configure decoder

- commands/operator-sdk/cmd/up/local.go
This commit fixes issue #366 and kills the `go run` command spawned
by `up local` when a `SIGINT` or `SIGTERM` signal is sent.
> commands/.../up/local.go: handle sigint and sigterm

- pkg/util/k8sutil/k8sutil.go
Perhaps the default should be changed in `operator-sdk up local`, but I didn't include in this PR.
> Allow empty namespace to watch all namespaces.

- commands/operator-sdk/cmd/test.go
This allows users of the `operator-sdk test` command to pass arguments to `go test`. For instance, `operator-sdk -t ./test/e2e/ args -v -parallel=2`.
Part of issue #387.
> commands/.../test.go: allow passing of flags to `go test`

- pkg/tlsutil/tls.go
Add interface and config definition for the tls util.
ref design: https://github.com/operator-framework/operator-sdk/pull/371
> pkg/util: add interface for tls util

- doc/sdk-cli-reference.md
- doc/testing/travis-build.md
This adds some documentation for the new e2e tests as well as for the `operator-sdk test` command
> docs: add test command documentation

- Makefile
- hack/test
The make test is old and not valid anymore. We will add instructions
for running the tests locally in a future PR.
> Makefile: remove make test

- Gopkg.lock
- README.md
- doc/user-guide.md
This adds changes to Gopkg.lock generated by running `dep ensure` with
dep version 0.5.0. Mostly, the changes are addition of extra information
for vendor verification.
Fixes #397
> Update Gopkg.lock for dep 0.5.0

- pkg/test/framework.go
If more than 1 test concurrently ran AddToFrameworkScheme,
there would be concurrent map read/write errors. By using a mutex,
we can ensure that there is not more than 1 function modifying the
scheme at the same time.
> pkg/test/framework.go: protect AddToFrameworkScheme with mutex

- pkg/tlsutil/primitives.go
- pkg/tlsutil/tls.go
add tls primitives that generate the private key, the ca cert, and the signed cert for the private key.
> pkg/util/tlsutil: add tls primitives functions

- doc/testing/end-to-end.md
> doc/testing/end-to-end.md: add end-to-end.md doc

- doc/test-framework/writing-e2e-tests.md
This PR provides documentation on the SDK's test framework
and a waltkthrough on how to create a simple e2e test for the
example memcached-operator.
> doc/test-framework: add test framework documentation

- commands/operator-sdk/cmd/test.go
- doc/sdk-cli-reference.md
- doc/test-framework/writing-e2e-tests.md
- pkg/test/framework.go
- pkg/test/main_entry.go
- pkg/test/resource_creator.go
To increase the flexibility of the framework and better describe
how we're using user provided YAML files, this commit removes the
specific crd, rbac, and operator yamls and replaces them with
a global init yaml (for things like CRDs) and a namespaced
init yaml (for things like rbac and operators).
> Change handling of YAML resources in test framework

- pkg/generator/templates.go
The code that gets vendored by dep by default is huge. We can
leverage the functionality given by dep viz. prune. This will remove
all the non-go code and unused packages.
It makes an exception to the k8s.io/code-generator repository. Since
we use the scripts from this repository to generate code.
Ref: https://golang.github.io/dep/docs/Gopkg.toml.html#prune
> pkg/generator: Add prune to Gopkg.toml template

- doc/user-guide.md
The instructions to create the `example-inc` project are missing a step to create the directory first.
> Missing step to create the example directory

- pkg/tlsutil/primitives.go
- pkg/tlsutil/tls.go
Implement the case where the CA and encryption key and cert are in the cluster.
When both are in the cluster, we simply retrieve them and return them to the user.
> pkg/tlsutil: implement the case ca and key are in the cluster

- pkg/generator/generator_test.go
- pkg/generator/templates.go
- pkg/sdk/api.go
- pkg/sdk/informer.go
> Switch ints to time.Duration

- doc/user-guide.md
- pkg/sdk/api.go
- pkg/sdk/informer.go
- pkg/sdk/watch-opt.go
pkg/sdk: adding label selector to sdk.Watch()
This is being made because as of right now there is no way to watch a specific
sub-set of a resource based on labels. This makes implementing finalizer 
controllers difficult.
> pkg/sdk: Add label selector for sdk.Watch()

- pkg/tlsutil/tls.go
- test/e2e/tls_util_test.go
Test the case when both app and ca tls assets exist in the cluster, the GenerateCert should just return those k8s assets to the user.
Also change SDKCertGenerator to use `kubernetes.Interface` instead of the sdk's dynamic client.
> *: test the case when both app and CA TLS assets exist 

- pkg/tlsutil/error.go
- pkg/tlsutil/tls.go
- test/e2e/tls_util_test.go
Test TLS Util for the case where only the application TLS asset exists in cluster and its corresponding CA doesn't. In this situation, the CertGenerator can't proceed because it can't generate a new CA as the new CA can't be used to verify the existing application TLS asset. Therefore, CertGenerator returns an error to the caller.
cc/ @hasbro17
> *: test the case where only the application TLS asset exists

- pkg/test/context.go
- test/test-framework/memcached_test.go
See https://github.com/operator-framework/operator-sdk-samples/pull/31#discussion_r214433233
> pkg/test/context.go: make NewTestCtx return ptr

- pkg/tlsutil/tls.go
- test/e2e/tls_util_test.go
Implement and test the case where none of the CA and application TLS assets are found. In this case, GenerateCert should simply generate both and put them into the k8s cluster.
> pkg/tlsutil: impl none of the CA and App TLS assets are found

- commands/operator-sdk/cmd/new.go
`fatal: write failure on 'stdout': Bad file descriptor` error is encountered by some users because the call to `git commit` uses a nil output fd. This commit allows `git commit` to print to stdout but quietly, fixing the error.
Fixes #363
> commands/operator-sdk/cmd: quiet initial git commit

- doc/proposals/ansible-operator.md
* Describes how the library packages of ansible operator
will be layed out
* New commands to manage ansible operators.
> doc/proposal: Ansible Operator proposal

- test/e2e/memcached_test.go
TestCustomCA needs the current directory to be rooted at projectPath to resolve `e2e/testdata ` correctly. Since TestMemcached changes the current directory to `/src/github.com/example-inc`, it causes TestCustomCA to unable to find `e2e/testdata `. 
This pr changes TestMemcached current directory to the default one once test is done.
cc/ @AlexNPavel
> test/e2e: change current dir to root in TestMemcached

- pkg/tlsutil/error.go
- pkg/tlsutil/tls.go
- test/e2e/tls_util_test.go
this PR adds support for users to provide a custom CA Key and Cert to generate other TLS assets. A unit test has also been added to test the functionality.
> pkg/tlsutil: add support for custom CA

- .travis.yml
- Gopkg.lock
This check makes sure repo is in a clean state after tests are run,
especially after dep ensure.
git diff --exit-code produces a 0 when there are not git differences.
See #492
> travis.yml: Add git diff check

- pkg/generator/generator.go
- pkg/generator/generator_test.go
If olm-catalog/ is removed from deploy/ dir, olm-catalog generation
fails. This change creates deploy/olm-catalog/ dir if it doesn't exist
and avoids failure.
Fixes #495
> Create olmCatalogDir if doesn't exists in deploy/

- pkg/generator/templates.go
The latest OLM has csv kind as `ClusterServiceVersion` under the group
`operators.coreos.com`.
Refer: https://github.com/operator-framework/getting-started/issues/21
> Update csv template's apiVersion and kind

- commands/operator-sdk/cmd/add/api.go
- pkg/scaffold/cr.go
- pkg/scaffold/crd.go
- pkg/scaffold/resource.go
[skip ci]
The `operator-sdk add api --kind --api-version` command can now add a new Kind for an existing api-version.
It also scaffolds the crd.yaml and cr.yaml for a new (apiversion,kind) under deploy/crds/.
> add api: add new type, generate crd and example cr

- MAINTAINERS
This updates the maintainer info
> MAINTAINERS: update MAINTAINERS file

- README.md
- commands/operator-sdk/cmd/test.go
- doc/user-guide.md
- pkg/generator/generator.go
- pkg/generator/generator_test.go
- pkg/generator/templates.go
- test/e2e/memcached_test.go
- test/test-framework/deploy/namespace-init.yaml
- test/test-framework/deploy/operator.yaml
- test/test-framework/deploy/rbac.yaml
- test/test-framework/deploy/sa.yaml
> Create SA for the operator

- commands/operator-sdk/cmd/add.go
- commands/operator-sdk/cmd/add/api.go
- commands/operator-sdk/cmd/add/controller.go
- commands/operator-sdk/cmd/generate/k8s.go
- commands/operator-sdk/cmd/new.go
- pkg/scaffold/add_controller.go
- pkg/scaffold/controller_kind.go
Added `operator-sdk add controller --kind=<Kind> --api-version=<APIversion>` command.
The default controller reconcile code is similar to our existing busy-box pod operator example. 
Later on we could add a flag to skip generating the example code.
Also made some typo fixes in the code-generator and `add api` cmd.
/cc @fanminshi
> *: add controller command and templates

- test/e2e/memcached_test.go
This should fix dependency issues that we occasionally experience in travis.
This should make PR #522 pass testing successfully
> test/e2e/memcached_test.go: fix dep issues in travis

- .travis.yml
- Gopkg.lock
- Gopkg.toml
- pkg/generator/templates.go
- pkg/k8sclient/client.go
- pkg/test/framework.go
- test/e2e/framework/framework.go
this continues https://github.com/operator-framework/operator-sdk/pull/391 @hasbro17 PTAL
> Gopkg.*,pkg/generator/templates.go: update to kubernetes 1.11.2

- test/e2e/memcached_test.go
On master, `TRAVIS_PULL_REQUEST_SLUG` is still set, but to `""`. This
breaks dep if it is run after a dependency change occurs, which
happens once we add the test directory. To fix this, we check
if `TRAVIS_PULL_REQUEST_SLUG` is `""` and we also only run `dep ensure`
once after all the files are up to date instead of once before
and once after.
/cc hasbro17
> test/e2e/memcached_test.go: fix travis on master

- commands/operator-sdk/cmd/up/local.go
Due to incoporating the controller runtime into the sdk, the operator entry point `main.go` is no long under `cmd/<project-name>/` but is under `cmd/manager`. Hence, `operator-sdk up local` needs to run the operator at the path `cmd/manager/main.go` instead of `cmd/<project-name>/main.go` . This pr reflects that change.
cc/ @hasbro17
> commands: update up local command to run cmd/manager/main.go

- commands/operator-sdk/cmd/test/cluster.go
- doc/sdk-cli-reference.md
- doc/test-framework/writing-e2e-tests.md
Updates docs to match changes made in #469
> Update Docs With Incluster Testing Support

- README.md
- commands/operator-sdk/cmd/add/api.go
- commands/operator-sdk/cmd/build.go
- commands/operator-sdk/cmd/new.go
- pkg/scaffold/cmd.go
- pkg/scaffold/controller_kind.go
- pkg/scaffold/gopkgtoml.go
- pkg/scaffold/operator.go
Updated the README example for the controller-runtime.
Update the `build` command to work with the new project layout. Fixed some template typos and the `new` cmd to get the full example working correctly.
We also can't prune unused pkgs because when we generate new files with `add api` and `add controller` they introduce dependencies on pkgs that were previously pruned. 
Meaning we would have to run dep ensure after both commands separately if we pruned.
/cc @fanminshi
> *: update README and fix templates and commands

- .travis.yml
- commands/operator-sdk/cmd/test/local.go
- doc/sdk-cli-reference.md
- doc/test-framework/writing-e2e-tests.md
- hack/ci/setup-openshift.sh
- pkg/test/framework.go
- pkg/test/main_entry.go
- pkg/test/resource_creator.go
This commit brings support for running the tests in a single
namespace when using `test local`, which was previously only used
by `test cluster` (where it was a requirement to properly function)
/cc @hasbro17 @fanminshi
> commands,pkg/test: support single namespace mode for local test

- test/e2e/memcached_test.go
PR #525 changed the way that dep worked to fix dependency issues
when doing e2e tests on travis. The PR breaks e2e testing on local
machines though, as the tests will just use the master branch
instead of a local branch. This commit symlinks the local sdk
into vendor on non-travis tests. The tests will still fail on local
machines if there is a dependency change, but we are unable to fix
this on local machines unless `dep` adds local repo support.
/cc @hasbro17 @fanminshi
> test/e2e/memcached_test.go: fix e2e testing on local machines

- .travis.yml
- Gopkg.lock
- commands/operator-sdk/cmd/build.go
- commands/operator-sdk/cmd/generate.go
- commands/operator-sdk/cmd/generate/crd.go
- commands/operator-sdk/cmd/new.go
- commands/operator-sdk/cmd/test/local.go
- doc/sdk-cli-reference.md
- doc/test-framework/writing-e2e-tests.md
- hack/ci/setup-openshift.sh
- pkg/ansible/controller/controller.go
- pkg/ansible/controller/reconcile.go
- pkg/ansible/controller/source.go
- pkg/ansible/controller/types.go
- pkg/ansible/events/log_events.go
- pkg/generator/generator.go
- pkg/generator/generator_test.go
- pkg/generator/templates.go
- pkg/test/framework.go
- pkg/test/main_entry.go
- pkg/test/resource_creator.go
- test/e2e/memcached_test.go
- ~~[ ] `operator-sdk up local` support.~~ Going to break this out to a separate PR
> commands/operator-sdk: Add CLI support for Ansible Operator

- commands/operator-sdk/cmd/build.go
- commands/operator-sdk/cmd/cmdutil/util.go
- pkg/generator/generator.go
- pkg/generator/generator_test.go
- pkg/generator/templates.go
This commit moves all functionality of build.sh into the build.go
file to embed the functionality into the binary. It also allows the
binary to generate the files needed when making tests (Dockerfile
and go-test.sh) in case someone tries to build testing enabled
images using a project made before that functionality was added.
See #541
> commands/{build,cmdutil},pkg/generator: remove build.sh

- commands/operator-sdk/cmd/cmdutil/util.go
- pkg/generator/generator.go
- pkg/generator/generator_test.go
- pkg/generator/templates.go
This fixes a regression introduced in: https://github.com/operator-framework/operator-sdk/pull/561
To determine if we are in the project root I've changed it to look for `tmp/build/Dockerfile`.
I also changed the rbac files to have Jinja templating for required differences in Ansible Operator RBAC. It sounds like the Jinja can go away when master is rebased on controller-runtime but I could be wrong on that.
> commands/operator-sdk,pkg/generator: Fix project root function and rbac updates for Ansible Operator

- Gopkg.lock
- doc/test-framework/writing-e2e-tests.md
- pkg/test/client.go
- pkg/test/context.go
- pkg/test/framework.go
- pkg/test/main_entry.go
- pkg/test/resource_creator.go
- test/e2e/incluster-test-code/memcached_test.go.tmpl
- test/test-framework/memcached_test.go
This commit create a new FrameworkClient type accesible as
Global.Client. It is a simple wrapper of the controller-runtime's
client with the exception of Create, which now adds cleanup
functions. This also changes "Finalizer" to "Cleanup" and trims
the Framework struct to only include variables that are useful
to the user. All other variables required in the framework are
now separate, unexported variables.
/cc @hasbro17 @shawn-hurley
> pkg/test: create new frameworkClient

- Gopkg.lock
- pkg/ansible/controller/controller.go
- pkg/ansible/controller/reconcile.go
- pkg/ansible/controller/source.go
- pkg/ansible/controller/types.go
- pkg/ansible/events/log_events.go
- pkg/ansible/paramconv/paramconv.go
- pkg/ansible/proxy/kubeconfig/kubeconfig.go
- pkg/ansible/proxy/kubectl.go
- pkg/ansible/proxy/proxy.go
- pkg/ansible/runner/eventapi/eventapi.go
- pkg/ansible/runner/eventapi/types.go
- pkg/ansible/runner/internal/inputdir/inputdir.go
- pkg/ansible/runner/runner.go
Cherry picking the commits in from the master branch for the ansible pkgs.
This is needed to bring in all extra changes for the ansible-operator into the refactor branch and have them work with the CLI changes in the refactor branch.
> pkg/ansible: cherry pick from master into refactor branch

- doc/ansible/project_layout.md
- doc/ansible/user-guide.md
- doc/sdk-cli-reference.md
- doc/user-guide.md
> docs: Add a user guide for using an Ansible Operator

- example/memcached-operator/handler.go.tmpl
- pkg/generator/generator_test.go
- pkg/generator/templates.go
- This PR primarily introduces a metric example in the generated operator. As an example it registers the `operatorErrors` operator specific metric. 
- Fixes https://github.com/operator-framework/operator-sdk/issues/462 when running locally the metrics `Service` was not created as the project/operator name was never known when running locally as the env. variable was not set. This passes the name of the project directly to the `ExposeMetricsPort`, if it's empty it still takes the env variable. This way it is us to the user which method they would prefer to take.
Closes https://github.com/operator-framework/operator-sdk/issues/479
> Add metrics example to the generated operator

- Gopkg.lock
- Gopkg.toml
- commands/operator-sdk/cmd/cmdutil/util.go
- commands/operator-sdk/cmd/up/local.go
- pkg/ansible/controller/controller.go
- pkg/ansible/controller/source.go
- pkg/ansible/operator/operator.go
This PR includes a bump in `controller-runtime` to `0.1.4`. Without it I was seeing an error:
```
2018/10/03 15:00:26 no kind "MemcachedList" is registered for version "cache.example.com/v1alpha1"
```
> commands/up/local; pkg/ansible; Add support for `up local` to Ansible Operator

- test/e2e/memcached_test.go
Small fix to make errors cleaner instead of resulting in unhelpful panics.
> test/e2e/memcached_test.go: check error for all ioutil.ReadFile

- doc/user-guide.md
otherwise `operator-sdk up local` fails.
> add OPERATOR_NAME env var

- pkg/scaffold/build_dockerfile.go
- pkg/scaffold/build_dockerfile_test.go
- pkg/util/file_util.go
The e2e tests were passing in travis due to the travis user and the container user being the same, but if the user building the image is different from the in-image uid, there will be permission errors. This changes to default exec file mode to `0755` and the in-image user to `nobody`
> pkg/{scaffold,util}: fix execute mode and container user

- pkg/leader/doc.go
- pkg/leader/leader.go
See doc/proposals/leader-for-life.md
> Added leader election.

- release.sh
Backport of change made in `refactor/controller-runtime` branch. See [this PR comment](https://github.com/operator-framework/operator-sdk/pull/604#discussion_r224573690) for details.
> release.sh: compare file versions against new version

- .travis.yml
We are hitting a bottleneck in travis jobs (at ~10 jobs) since
each PR/commit results in 4 jobs being started to testing. New
versions of minikube do not work properly on travis anymore due
to travis not yet supporting systemd, so we would be stuck on
an old version of minikube anyway. This commit means that all
tests will run on openshift (currently 3.11), which should be the
same as vanilla kubernetes (1.11), but with a bit more restrictions.
> .travis.yml: remove minikube tests

- Makefile
The `build/%.asc` target conditional `git` operand was being evaluated after the conditional itself, so the conditional was not evaluating correctly. Now `make build/%.asc`'s conditional evaluates correctly and normalizes alphabetical case.
> Makefile: build signature target performs correct comparison

- test/e2e/memcached_test.go
This PR enables the e2e tests to substitute any branch fixed in the SDK-generated `Gopkg.toml`.
Test: https://play.golang.org/p/eY5PQj-ulxt
> test/e2e/memcached_test.go: regexp branch substitution

- .github/ISSUE_TEMPLATE.md
- .github/ISSUE_TEMPLATE/Bug_report.md
- .github/ISSUE_TEMPLATE/Feature_request.md
- .github/ISSUE_TEMPLATE/Question.md
- .github/PULL_REQUEST_TEMPLATE.md
As per the suggestion in the issue #585 I opened, we went with using the `.github` directory to store all the issue and PR templates. Inspired by https://github.com/babel/babel.
Suggestions are very welcome, especially for the PR template.
Closes #585
> Add Issue and PR templates to the project

- commands/operator-sdk/cmd/up/local.go
- pkg/ansible/operator/operator.go
- pkg/ansible/proxy/proxy.go
- test/ansible-operator/cmd/ansible-operator/main.go
main.go should be as minimal as is reasonable, so this moves startup logic to a
more appropriate place. It also slightly changes the proxy startup code to
better match controller startup.
The new error handling avoids a race between the proxy being available and
ansible trying to use it.
> moves controller creation and startup out of ansible's main.go

- .gitignore
**Description of the change:** The ansible-operator binary was unintentionally committed in a
previous PR. This commit removes the binary and adds its path to
the gitignore.
**Motivation for the change:** We shouldn't have binaries in our repo
> test/ansible-operator: remove binary

- pkg/scaffold/gopkgtoml.go
- pkg/scaffold/gopkgtoml_test.go
**Description of the change:** Make scaffolded Gopkg.toml point to master
**Motivation for the change:** The master branch version of the sdk should point to master
/cc @hasbro17 @shawn-hurley @estroz
> pkg/scaffold/gopkgtoml: point to master branch

- .travis.yml
- test/e2e/memcached_test.go
This PR moves `$GOPATH/src/github.com/example-inc` creation logic from `.travis.yml` into the test itself so devs can re-run tests without having to create the dir manually.
> test/e2e: make running e2e tests locally easier

- test/test-framework/memcached_test.go
**Description of the change:** Bump `up local` subcommand test deployment check timeout from 30 seconds to 60 seconds.
**Motivation for the change:** The `up local` test is very flaky on travis. It seems to be mostly
a timeout issue, so we should be able to just bump it to fix the
flakes.
> test/test-framework/memcached_test.go: bump timeout

- commands/operator-sdk/cmd/cmdutil/util.go
- commands/operator-sdk/cmd/new.go
**Description of the change:** as per #627, operator type checking should be refactored into the `cmdutil` package.
**Motivation for the change:** two sets of operator type indicators is unnecessary.
> commands/operator-sdk: consolidate operator types into cmdutil package

- commands/operator-sdk/cmd/generate/k8s.go
- pkg/scaffold/resource.go
**Description of the change:** `K8sCodegen()` requires groups and versions of operator API's when generating `deepcopy` functions and types. This change ensures only specific directories are used when parsing groups and versions for generating `deepcopy` code. Furthermore, resource fields such as API versions should be validated on creation.
**Motivation for the change:** currently, `deepcopy` generation looks at all files and directories in `pkg/api` in a brute-force manner. We need filtering to produce better user-facing output. Resources with invalid field names cannot be understood by the Kubernetes API and should be validated before they are created by the SDK
> cmd: initial resource validation

- doc/design/milestone-0.1.0/client-api.md
- doc/user-guide.md
- doc/user/client.md
- pkg/scaffold/controller_kind.go
- pkg/scaffold/controller_kind_test.go
The refactor from SDK-specific k8s API calls to `kubernetes-sigs/controller-runtime` was
a large undertaking that changed project structure and how generated projects interact
with a k8s cluster. This document attempts to explain these changes to both new users
and developers of existing operators generated with SDK `<= v0.7.0`.
> doc/user: document refactor to controller-runtime

- commands/operator-sdk/cmd/add/api.go
- commands/operator-sdk/cmd/add/crd.go
- commands/operator-sdk/cmd/cmdutil/util.go
- commands/operator-sdk/cmd/new.go
**Description of the change:** This moves updateRoleForResource to cmdutil so all of the command libraries can use it and also adds support for ClusterRoles in said function.
**Motivation for the change:** Deduplication of code and supporting users who want to use ClusterRole
> commands/.../cmdutil: deduplicate updateRoleForResource and support ClusterRole

- Gopkg.lock
- pkg/scaffold/role.go
- pkg/scaffold/role_test.go
- pkg/sdk/metrics.go
- pkg/sdk/service-monitor.go
[ServiceMonitor](https://github.com/coreos/prometheus-operator/blob/7b837c1a06b1252efec85e6f04a9ff54889b519b/Documentation/design.md#servicemonitor) is a CRD of the prometheus-operator, it discovers the `Endpoints` in `Service` objects and configures Prometheus to monitor those Pods. The `GenerateServiceMonitor` takes a `Service` object and generates a `ServiceMonitor` resources based on it. 
Note: I think some docs would be good to add here to explain what `ServiceMonitor` are point to requirments, but wasn't sure where to add it, let me know if you have any ideas?
As for the addition of `ExposeMetricsPort` to return the `Service` object, I think that makes it clean for the user to use these helper functions, this is what I had in mind:
```
s := ExposeMetricsPort() …
```
> Add helper function for generating ServiceMonitor objects

- pkg/leader/doc.go
- pkg/leader/leader.go
- pkg/scaffold/operator.go
- pkg/scaffold/operator_test.go
This is useful for pods running in hostNetwork, where the hostname is not the pod name.
> pkg/leader: allow setting the pod name explicitly.

- version/version.go
**Description of the change:** Set version in `version/version.go` to v0.0.7-git
**Motivation for the change:** v0.0.7 was released, so the git version on master needed to be bumped
> version: set to v0.0.7-git

- Makefile
**Description of the change:** `make release` target code is now fully a bash script rather than a mix of bash and Makefile syntax.
**Motivation for the change:** the script to sign release binaries is relatively complicated and doesn't play nice with Makefile bash interpretation. Uses were also seeing errors when they did not have `gpgconf` installed regardless of what target they were running.
Closes: #651
> Makefile: convert release signing target to full bash

- doc/ansible/user-guide.md
Added documentation around the handling of variable names by the ansible operator. Previously the only way to know how this works was to read the code.
> Document snake_case conversion by ansible operator

- commands/operator-sdk/cmd/up/local.go
- pkg/ansible/operator/operator.go
- pkg/ansible/runner/runner.go
- pkg/ansible/runner/runner_test.go
- pkg/ansible/runner/testdata/duplicate_gvk.yaml
- pkg/ansible/runner/testdata/invalid.yaml
- pkg/ansible/runner/testdata/invalid_duration.yaml
- pkg/ansible/runner/testdata/invalid_finalizer_playbook_path.yaml
- pkg/ansible/runner/testdata/invalid_finalizer_role_path.yaml
- pkg/ansible/runner/testdata/invalid_playbook_path.yaml
- pkg/ansible/runner/testdata/invalid_role_path.yaml
- pkg/ansible/runner/testdata/valid.yaml
- test/ansible-operator/cmd/ansible-operator/main.go
Adding ability to specify GVK specific re-queue times via the watches file
* Not every GVK should be handled the same
* wanted to add some test cases.
> pkg/ansible,*: Adding ability to specify re-queue period per GVK via watches file.

- doc/migration/v0.1.0-migration-guide.md
- doc/user-guide.md
[skip ci]
- Added a migration guide to migrate a Go operator project to use SDK `v0.1.0` with the new controller-runtime changes.
-  Update the user-guide for adding 3rd party resources.
- The `v0.1.0-changes.md` doc referenced in the migration guide will be added in a followup PR. But even without that the migration guide should be sufficient to understand the changes.
- Need a migration guide before making the `v0.1.0` release.
/cc @shawn-hurley @joelanford @LiliC @AlexNPavel @estroz
> doc: add migration guide

- doc/test-framework/writing-e2e-tests.md
**Description of the change:** Add service account flag to cluster test command example
**Motivation for the change:** The command will fail due to permissions if the service account is not specified
> doc/test-framework: add service account flag to cluster test cmd

- README.md
- doc/user-guide.md
README:
- Change pre-alpha to alpha 
- Updated the workflow
- Linked to ansible operator user-guide
user-guide:
- Cleaned up some sections and added links to controller-runtime go-docs in the user-guide
> doc: clean up README and user-guide

- .gitignore
- pkg/ansible/runner/runner.go
- pkg/ansible/runner/runner_test.go
- pkg/ansible/runner/testdata/valid.yaml.tmpl
Check that the absolute path to the playbook or role does exist.
Not exposing errors to the user when we are unable to find the playbook or role makes it hard to figure out there is a problem when running.
> pkg/ansible: fail early if we are unable to find role or playbook

- doc/sdk-cli-reference.md
- Added the CLI reference description and examples for `add api` and `add controller`
- Cleaned up the section for `new` by making the flags `--api-version` and `--kind` only specific to `--type=ansible`. Also added the example cmd for ansible.
- Made the description for `generate k8s` more specific. The example output was outdated as well.
- The doc for `generate crd` was wrong. It's actually `add crd` so I moved it down to the correct section. The example was outdated too since the filenames changed after the refactor.
- Removed the section for `generate olm-catalog` since we no longer have that in our CLI.
The diff below is confusing to review since I had to reshuffle and remove some sections. It will be easier to just view the whole file and directly review the following sections:
- …
> doc/sdk-cli-reference: update for [api,controller], cleanup for [new, generate]

- .travis.yml
**Description of the change:** skip any files containing:
`.md | .MD | .png | .pdf | docs | MAINTAINERS | LICENSE`
**Motivation for the change:** running CI on these files is unnecessary.
> .travisl.yml: skip CI on change to docs or untestable project files

- hack/lib/test_lib.sh
- internal/util/projutil/project_util.go
<!--
Before making a PR, please read our contributing guidelines https://github.com/operator-framework/operator-sdk/blob/master/CONTRIBUTING.MD
Note: Make sure your branch is rebased to the latest upstream master.
--!>
Allow operator-sdk to run with composed GOPATH
Currently it fails.
<!--
Note: If this PR is fixing an issue make sure to add a note saying:
Closes #<ISSUE_NUMBER>
--!>
> allow operator-sdk to run with composed GOPATH

- pkg/scaffold/cmd.go
- pkg/scaffold/cmd_test.go
Remove the commented out TODO for exposing the metrics port in `main.go` template.
We're still waiting for an upstream PR on the runtime before the controller metrics will be exposed. So for the purposes of the v0.1.0 release we can remove that from the template until the upstream PR is merged.
> pkg/scaffold: remove TODO for metrics port

- doc/release-versioning.md
- release.sh
**Description of the change:** Fix the `release.sh` file and improve the versioning documentation.
**Motivation for the change:** We need the `release.sh` to be correct to make new releases and we need working documentation for maintainers who have not done releases in the past.
> Release versioning

- doc/migration/v0.1.0-migration-guide.md
We have to copy and overwrite the `.git` directory from the old project into the new project, so we can skip it for the new project.
> doc/migration: skip git for new project

- pkg/scaffold/crd.go
Use requested version in CRD example.
Examples could mismatch on versions.
Closes #689
> pkg/scaffold: fix hardcoded crd version

- README.md
Adding workflow for the ansible operator in the README.
Making the workflow just as obvious as golang
/cc @hasbro17
> Adding ansible operator workflow to the README

- Makefile
- doc/release-versioning.md
All binary releases should be signed using a single, well-known PGP key or any of the [maintainers'](https://github.com/operator-framework/operator-sdk/tree/master/MAINTAINERS).
/cc @AlexNPavel @hasbro17
> Release signing process

- test/e2e/memcached_test.go
**Description of the change:** Comment out version during tests
**Motivation for the change:** Release PRs would always fail, requiring us to disable branch protection temporarily to merge the PR before creating a matching tag. This should fix that
> test/e2e/memcached_test.go: comment out gopkg version during tests

- commands/operator-sdk/cmd/build.go
Changing build output so that exec'ed build subprocesses use the main process stdout and stderr.
Currently `operator-sdk build` prints subprocess output only after the subprocess has finished. This can be a poor user experience for long running subprocesses that output progress along the way (e.g. `docker build`).
> commands/.../build.go: set exec command output to stdout, stderr

- CHANGELOG.md
- pkg/scaffold/gopkgtoml.go
- pkg/scaffold/gopkgtoml_test.go
- version/version.go
**Description of the change:** Release v0.1.1
**Motivation for the change:** Bug fixes
NOTE: This will not pass CI due to pointing to a non-existant tag and will require an override to merge
> pkg/scaffold,version,changelog: bump to v0.1.1

- pkg/scaffold/build_dockerfile.go
- pkg/scaffold/build_dockerfile_test.go
**Description of the change:** Update base image used by generated dockerfile and run `apk update` to make sure bug and security fixes are applied to image.
**Motivation for the change:** Alpine 3.6 is an old image and may contains security vulnerabilities or otherwise be out of date. For our default generated dockerfile, we should try to remain up to date and also update the image's packages in case a vulnerability was fixed in the repos, but not the image
> pkg/scaffold/build_dockerfile: update base image

- pkg/ansible/controller/reconcile.go
- pkg/ansible/events/log_events.go
- pkg/ansible/runner/eventapi/eventapi.go
- pkg/ansible/runner/internal/inputdir/inputdir.go
- pkg/ansible/runner/runner.go
* When a specific task fails, the path and line number are logged.
* When ansible fails to run any tasks, such as if a syntax error exists in a role, ansible's stdout gets logged.
* log messages from the reconciler now include the job ID.
* The message "dropping event that is not a JobEvent" is now logged at debug level instead of info, since it isn't normally helpful.
Example log output when a task fails:
```
INFO[0001] [playbook task]: Gathering Facts              component=logging_event_handler event_type=playbook_on_task_start gvk="cache.example.com/v1alpha1, Kind=Memcached" name=example-memcached namespace=default
INFO[0002] [playbook task]: dymurray.memcached_operator_role : foo  component=logging_event_handler event_type=playbook_on_task_start gvk="cache.example.com/v1alpha1, …
```
> Improves output available for troubleshooting ansible

- commands/operator-sdk/cmd/add/api.go
- commands/operator-sdk/cmd/add/controller.go
- commands/operator-sdk/cmd/generate/k8s.go
- internal/util/projutil/project_util.go
**Description of the change:** add `MustGoProject` function to exit if the current operator project is not a Go project.
**Motivation for the change:** see #670
> Exit if not a Go project

- doc/test-framework/writing-e2e-tests.md
Improve the example code for e2e test by importing `AddToScheme` from the `pkg/apis` package.
> doc/test-framework: improve example code

- pkg/scaffold/resource.go
**Description of the change:** updates to `Resource` field regexps.
**Motivation for the change:** `Kind`'s must start with a capital letter, and can contain digits. `Group`'s can contain digits.
> better Resource field pattern matching

- README.md
- doc/ansible/dev/developer_guide.md
- doc/ansible/user-guide.md
- doc/user-guide.md
On OSX `sed` throws an error if you do not specify a file extension when
`-i` is given. Fixing the docs to address this on OSX.
Error:
`sed: 1: "deploy/operator.yaml": extra characters at the end of d command`
From `man sed` on OSX:
```
-i extension
Edit files in-place, saving backups with the specified
extension.  If a zero-length extension is given, no backup
will be saved.  It is not recommended to give a
zero-length extension when in-place editing
files, as you risk corruption or partial
content in situations where disk space is
exhausted, etc.
```
> Fix sed issue on OSX

- hack/tests/e2e-ansible.sh
- test/ansible-operator/Dockerfile
**Description of the change:** make a temporary directory in the current directory for Ansible test files and unset Golang environmental variables within script process.
**Motivation for the change:** we should test Ansible operators outside of a Golang environment. Brought up by @shawn-hurley when re-assessing #712.
> tests/e2e-ansible: ansible tests should not run in Golang environment

- commands/operator-sdk/cmd/add/api.go
- commands/operator-sdk/cmd/add/controller.go
- commands/operator-sdk/cmd/build.go
- commands/operator-sdk/cmd/generate/k8s.go
- commands/operator-sdk/cmd/new.go
- internal/util/projutil/project_util.go
- test/e2e/memcached_test.go
**Description of the change:** see #712 for main change. Also changed `CheckAndGetCurrPkg()` to `CheckAndGetProjectGoPkg()`, and removed local constants in favor of `projutil` contstants.
**Motivation for the change:** see #712, and make function name more obvious. We had to revert #712 in #721 so Ansible operator users don't see errors when they shouldn't. Now the `GOPATH` check only occurs when calling `CheckAndGetProjectGoPkg()`. 
@nrobert13
> commands/operator-sdk/cmd: set composed GOPATH for Go projects (fix #712)

- Gopkg.lock
- commands/operator-sdk/cmd/test/cluster.go
- commands/operator-sdk/cmd/test/local.go
- internal/util/k8sutil/k8sutil.go
- pkg/test/framework.go
**Description of the change:** The clientcmd package provides utilities to retrieve `ClientConfig` objects using sane defaults (checking the environment variable first, which we didn't do, then falling back to `$HOME/.kube/config`). `ClientConfig`s contain the `*rest.Config` (kubeconfig) and other useful information like the active default namespace, which is useful for the `test cluster` subcommand, as we previously just assumed `default` was the default.
**Motivation for the change:** Using kubernetes utils will likely be more reliable in the long term and require less maintenance from us. Also, this allows the cluster test to correctly identify the default namespace.
> commands/.../test,internal/util: use clientcmd's kubeconfig getter

- doc/migration/v0.1.0-migration-guide.md
- internal/util/projutil/project_util.go
**Description of the change:** state `main.go` must be present for Go operators, and better error message.
**Motivation for the change:** see #726 
Closes #726
> *: better docs and error reporting for project type issue

- pkg/scaffold/add_controller_test.go
- pkg/scaffold/addtoscheme_test.go
- pkg/scaffold/apis_test.go
- pkg/scaffold/build_dockerfile_test.go
- pkg/scaffold/cmd_test.go
- pkg/scaffold/controller_kind_test.go
- pkg/scaffold/controller_test.go
- pkg/scaffold/cr_test.go
- pkg/scaffold/crd_test.go
- pkg/scaffold/doc_test.go
- pkg/scaffold/gitignore_test.go
- pkg/scaffold/go_test_script_test.go
- pkg/scaffold/gopkgtoml_test.go
- pkg/scaffold/internal/testutil/test_util.go
- pkg/scaffold/operator_test.go
- pkg/scaffold/register_test.go
- pkg/scaffold/role_test.go
- pkg/scaffold/rolebinding_test.go
- pkg/scaffold/service_account_test.go
- pkg/scaffold/test_framework_dockerfile_test.go
- pkg/scaffold/test_pod_test.go
- pkg/scaffold/types_test.go
- pkg/scaffold/version_test.go
**Description of the change:** move `pkg/scaffold/util.go` to `pkg/scaffold/internal/testutil/test_util.go` and update deps.
**Motivation for the change:** sub-packages of `pkg/scaffold` need to access unit test helpers.
> pkg/scaffold/internal/testutil/test_util.go: scaffold unit test utilities

- doc/dev/developer_guide.md
**Description of the change:** update dev docs.
**Motivation for the change:** were out of date.
> doc/dev/developer_guide.md: update dev guide

- pkg/scaffold/cmd.go
- pkg/scaffold/cmd_test.go
Modifying the `cmd/manager/main.go` template so that the call to `printVersion()` occurs after the logger has been set.
`printVersion()` does not currently print the version information.
If we're concerned that moving `printVersion()` beyond the very first call in `main()` will cause problems, we can also just use `fmt.Printf()` in `printVersion()` instead of using the logger.
> pkg/scaffold: fixing main printVersion

- .travis.yml
- test/e2e/memcached_test.go
This enables a developer to activate travis-ci on their own namespace and have
branches tested upon push. It's an effective way to test the CI before making a
pull request to operator-sdk.
> Adds travis support for push builds

- .travis.yml
In the https://github.com/operator-framework/operator-sdk/pull/764 PR `pkg/sdk` directory was removed and when that was merged it [broke the markdown check](https://travis-ci.org/operator-framework/operator-sdk/jobs/459670676#L358), as we have some links in CHANGELOG that point to that directory. I decided against changing the CHANGELOG and instead added so we now run the `marker` only on doc.
The https://github.com/crawford/marker does not support excluding certain files, so here we introduce the check in `doc` directory only, until the support for the `--exclude` flag is added. Opened issue https://github.com/crawford/marker/issues/18
> .travis.yml: Only run markdown checker on doc dir

- Gopkg.lock
- commands/operator-sdk/cmd/print_deps.go
- commands/operator-sdk/cmd/root.go
- doc/sdk-cli-reference.md
- pkg/scaffold/gopkgtoml.go
- pkg/scaffold/gopkgtoml_test.go
**Description of the change:** add an `operator-sdk print-deps` sub-command to print the most recent operator dependencies and versions. The sub-command will print pretty (below) by default, or the full `Gopkg.toml` when passed the `--as-file` flag.
**Motivation for the change:** updating operator versions when upgrading to new binary versions requires looking at SDK source code. This command prints all version information for packages pre-defined by the SDK that can be copy and pasted into an operators' `Gopkg.toml`, or written over directly with the `--as-file` flag.
Sample of output:
```
NAME						VERSION		BRANCH		REVISION
github.com/operator-framework/operator-sdk			master
k8s.io/code-generator								6702109cc68eb6fe6350b83e14407c8d7309fd1a
k8s.io/api …
```
> 'operator-sdk print-deps' command

- doc/user/unit-testing.md
**Description of the change:** doc on using `controller-runtime`'s fake client library to mock API calls in unit tests.
**Motivation for the change:** users should be writing unit tests for custom operator code. The fake client is useful for doing so.
> doc/user/unit-testing.md: explain fake client and unit test example

- doc/user/event-filtering.md
**Description of the change:** document predicate usage in SDK controllers.
**Motivation for the change:** improves documentation of controller features.
> doc/user/event-filtering.md: event filtering with Predicates

- hack/tests/e2e-ansible.sh
- test/ansible-operator/Dockerfile
There is an issue in the latest ansible/ansible-runner image
that causes the ansible-operator proxy not to be used to add
owner references as expected. This commit ensures the latest
versions of ansible and ansible-runner are installed.
Aligning ansible-operator e2e Dockerfile with the Dockerfile in `water-hole/ansible-operator` and ensure that latest ansible version is installed.
1. Consistency.
2. The current Dockerfile results in a broken image. In e2e tests, the memcached deployment does not have an owner ref, which causes it not be be garbage collected. I think this is caused by a [bug in ansible 2.7.0](https://github.com/ansible/ansible/issues/47149), which is what currently exists in the `ansible/ansible-runner` image.
> test/ansible-operator/Dockerfile: fix e2e ownerref issue

- hack/tests/test-subcommand.sh
- pkg/test/main_entry.go
Dereference kubeconfig pointer instead of using it directly.
As of now, go test local won't work if we are passing kubeconfig.
> Fix kubeconfig pointer override

- CHANGELOG.md
- pkg/scaffold/gopkgtoml.go
- pkg/scaffold/gopkgtoml_test.go
- version/version.go
Due to a CI issue, we had to revert the previous release PR and the PR that was causing problems. This creates the release after those results (and hopefully will allow CI to pass)
> pkg/scaffold,version,changelog: bump to v0.2.0 (again)

- .travis.yml
- When tests fail we want to see the output of the cluster state to more easily see the problem, so adding events and displaying the resources helps with that.
- Single quotes output the variable name, double quotes outputs the value. See https://bash.cyberciti.biz/guide/Quoting
> Minor travis improvments

- pkg/scaffold/resource.go
In the current validation code for api version, it causes go panic
when the version was missed. This patch changes to check the length of
splitted API by "/". Then, use the value and output produce error
message if version was missed.
- Before:
~~~
$ operator-sdk add api --api-version=foo  --kind=AppService
INFO[0000] Generating api version foo for kind AppService. 
panic: runtime error: index out of range
goroutine 1 [running]:
github.com/operator-framework/operator-sdk/pkg/scaffold.(*Resource).checkAndSetVersion(0xc000436380, 0x0, 0x0)
/Users/knakayam/.go/src/github.com/operator-framework/operator-sdk/pkg/scaffold/resource.go:132 +0x183
github.com/operator-framework/operator-sdk/pkg/scaffold.(*Resource).Validate(0xc000436380, 0xc000436380, 0x2) …
> Fix validation check for when API version is missed

- Gopkg.lock
- commands/operator-sdk/cmd/up/local.go
- pkg/ansible/proxy/proxy.go
- pkg/ansible/proxy/proxy_test.go
- pkg/ansible/proxy/requestfactory/requestinfo.go
- test/ansible-operator/cmd/ansible-operator/main.go
This change passes in the manager's cache into the proxy to prevent spamming APIserver with GET requests.
Performance enhancements
**Metrics**
1000 sequential requests against a resource.
Before changes:
```
1m1.615s
```
After changes:
```
0m15.547s
```
Overall this is a ~75% reduction in the time it takes to GET resources from the cluster.
**TODO**
* Add prometheus metrics
* Update proxy tests once https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/controller/controllertest/util.go#L44 is implemented to allow us to use a fake cache
> pkg/ansible/proxy; Integrate caching to AO proxy

- test/ansible-operator/Dockerfile
Locks python idna package to 2.7
Fixes broken ansible-operator base image, which installs incompatible idna version 2.8
> test/ansible-operator/Dockerfile: lock idna to 2.7

- pkg/scaffold/resource.go
**Description of the change:** bounds and length checking in resource version validators.
**Motivation for the change:** robust validation and to avoid panics.
> pkg/scaffold/resource.go: robust validators and avoid panics

- doc/proposals/metering-operator-metrics.md
**Motivation:**
See https://github.com/operator-framework/operator-sdk/issues/616 for background and initial discussion.
This is a working PR, with two proposals for us to decide on. I looked over all the options and I believe there are both valid and have their own drawbacks. Once we agree on an option, either kube-state-metrics or client_golang, I will reflect that in the PR by leaving the agreed upon option.
I have created a working POC operator https://github.com/LiliC/operator-sdk-metric-example, it takes the kube-state-metrics as an example implemtation.
For a in depth explanation of kube-state-metrics I found this blog post useful. https://brancz.com/2017/11/13/kube-state-metrics-the-past-the-present-and-the-future/
> doc/proposals: Add operator specific metrics proposal

- hack/tests/e2e-ansible.sh
- pkg/ansible/controller/reconcile.go
- pkg/ansible/controller/reconcile_test.go
- pkg/ansible/events/log_events.go
- pkg/ansible/proxy/proxy.go
- test/ansible-memcached/memfin/tasks/main.yml
- test/ansible-operator/cmd/ansible-operator/main.go
- Fixes bug where reconcile attempted to update status after running finalizer
- Stops depending on grepping for a log statement for a test to pass
- Disables debug log mode by default
- logs cache miss at INFO instead of ERROR
- adds commented-out check for errors in logs in e2e tests, which will be enabled after #818 gets fixed
> fixes several ansible test failures and flaws

- pkg/scaffold/gopkgtoml.go
- pkg/scaffold/gopkgtoml_test.go
When you specify a version without an operator, dep automatically uses
the ^ operator by default. That means it will take the major range.
That broke building of generated operators due to missing dependencies
in controller-runtime latest release.
operator-sdk master is currently broken. See https://github.com/operator-framework/operator-sdk/issues/827#issuecomment-445199222
> Pin controller-runtime to v0.1.4

- commands/operator-sdk/cmd/test/local.go
- pkg/scaffold/gopkgtoml.go
- pkg/scaffold/gopkgtoml_test.go
- pkg/test/framework.go
- test/e2e/memcached_test.go
- test/test-framework/test/e2e/memcached_test.go
**Description of the change:** clean up and fix tests.
**Motivation for the change:** the following error has been seen in several PR's with the CI command
```sh
$ operator-sdk test local ./test/e2e --up-local --namespace=test-memcached
```
```
{
"level":"error",
"ts":1543959163.0456057,
"logger":"controller_memcached",
"caller":"memcached/memcached_controller.go:127",
"msg":"failed to create new Deployment.",
"Request.Namespace":"test-memcached",
"Request.Name":"example-memcached",
"Deployment.Namespace":"test-memcached",
"Deployment.Name":"example-memcached",
"error":"deployments.apps \"example-memcached\" is forbidden: cannot set blockOwnerDeletion in this case because cannot find RESTMapping for APIVersion cache.example.com/v1alpha1 Kind Memcached: no matches for kind \"Memcached\" in …
```
> test local: fix reconcile 'cannot find RESTMapping' error

- pkg/ansible/runner/runner.go
- pkg/scaffold/gopkgtoml.go
- pkg/scaffold/gopkgtoml_test.go
- test/ansible-operator/Dockerfile
operator-sdk branch v0.2.x currently broken due to recent controller-runtime bump to v0.1.8. See #828. Backport @LiliC's master fix to v0.2.x.
> Backport Pin controller-runtime to v0.1.4 #828 to v0.2.x

- CHANGELOG.md
- doc/ansible/dev/developer_guide.md
- doc/user-guide.md
- doc/user/client.md
- example/memcached-operator/memcached_controller.go.tmpl
- pkg/ansible/controller/reconcile.go
- pkg/ansible/controller/status/types.go
- pkg/helm/controller/reconcile.go
- pkg/scaffold/crd.go
- pkg/scaffold/crd_test.go
- test/test-framework/pkg/controller/memcached/memcached_controller.go
Enable use of status subresource by default in operator-sdk.
*Ansible:*
Adds support for hybrid managed status between AO and user's Ansible. Get's latest version of resource to ensure that we are updating the latest version of the resource.
In Kubernetes v1.11.0 the status subresource is enabled by default and so this PR enables the status subresource by default in operator-sdk.
*Ansible:*
Hybrid use case panics when user updates status from Ansible task.
Closes #809
> pkg/ansible/controller,pkg/helm/controller; Enable status subresource by default

- Makefile
Added `-update` flag to sync the `Gopkg.toml` to`Gopkg.lock`. 
The `Gopkg.toml` does NOT sync to `Gopkg.lock` automatically. Correct me if I'm wrong.
But, it will take more time to run if we add this `-update` flag.
Any comments are welcome！
Closes #827
> fixed #827

- pkg/ansible/runner/runner.go
This change ensures that the `K8S_AUTH_KUBECONFIG` and `KUBECONFIG` variables are set for both the outer ansible-runner context (for lookup plugins) and the context that runner sets when executing tasks (for modules etc). This should make the `k8s` lookup plugin respect the kubeconfig created by the operator.
the Ansible `k8s` lookup plugin was connecting directly to the cluster instead of using the Operator's proxy.
> Set KUBECONFIG and K8S_AUTH_KUBECONFIG environment variables for ansible-runner

- CHANGELOG.md
- pkg/scaffold/gopkgtoml.go
- pkg/scaffold/gopkgtoml_test.go
- version/version.go
> release 0.3.0

- CHANGELOG.md
**Description of the change:** Move the status subresource change note in the changelog to the correct location.
> changelog: move the subresource note to correct section

- CHANGELOG.md
The link to updating the status subresource was broken.
> changelog: fix typo in link

- doc/dev/testing/end-to-end.md
- doc/dev/testing/travis-build.md
Our requirements in the testing docs were no longer up to date, instead of having to keep it up to date I think linking to the CI script might be a better option.
> doc/dev/testing: Update documentation

- Gopkg.lock
- pkg/k8sutil/k8sutil.go
- pkg/metrics/service-monitor.go
- pkg/scaffold/gopkgtoml.go
- pkg/scaffold/gopkgtoml_test.go
This PR adds a helper function to create [ServiceMonitor](https://github.com/coreos/prometheus-operator/blob/3288dbd9cf9a9b667d16e48d7c113753635654ef/Documentation/design.md#servicemonitor) objects by passing a metrics Service objects that already exist. The function does a check to makes sure the ServiceMonitor is registered within the cluster before creating the ServiceMonitor object. 
*Note:* As this is just a helper function, I am not sure if we should add an end-to-end test as for that we need to deploy prometheus-operator as well. Let me know your thoughts.
Closes https://github.com/operator-framework/operator-sdk/issues/789
> ServiceMonitors

- Gopkg.lock
- commands/operator-sdk/cmd/up/local.go
- hack/tests/e2e-ansible.sh
- pkg/ansible/flags/flag.go
- pkg/ansible/operator/operator.go
- test/ansible-operator/bin/entrypoint
- test/ansible-operator/cmd/ansible-operator/main.go
* Add the ability add flags to your binary
* Change to `operator.Run` to take the flags
* Adding ability to pass in the watches file location
Adding the ability to add the ansible operator flags to the command line. An example is for `operator-sdk up local`. If we sense that this is an ansible operator, then we will add the ansible operator flags so that the same testing can happen locally as it can in a container image.
Adding some infrastructure to make adding flags/options easier.
> pkg/ansible,cmd/up/local: Add ansible operator flags to your CLI

- doc/proposals/ansible-operator-testing.md
Signed-off-by: Fabian von Feilitzsch <fabian@fabianism.us>
Adds a proposal to support e2e testing on Ansible Operators
Currently only Golang-based operators have any e2e testing integration. This proposal would bring Ansible Operators to parity.
> Add proposal for Ansible Operator e2e test integration

- pkg/scaffold/customrender.go
- pkg/scaffold/scaffold.go
**Description of the change:** added the `CustomRenderer` interface. `scaffold.Execute()` will execute `CustomRender()` if an `input.File` implements the interface, otherwise defaulting to `template.Execute()`.
**Motivation for the change:** complex scaffold files that might not want use a template, ex. CSV's, and should be able to write arbitrary bytes to a scaffold file.
> CustomRenderer interface for non-templated scaffolds

- README.md
Adds a link to the README to the SDK CLI Reference
Make the SDK CLI Reference document more prominent to help users clarify questions
Closes #415
> README.md: Adding link to SDK CLI Reference doc

- pkg/scaffold/input/input.go
- pkg/scaffold/scaffold.go
**Description of the change:** add a `TemplateFuncs` field to `input.Input` for functions to be applied to a scaffold template, and add these funcs to the template in `newTemplate`.
**Motivation for the change:** complex templates may require Go functions defined in a scaffold source file.
> pkg/scaffold/*: allow Inputs to specify template functions

- commands/operator-sdk/cmd/test/cluster.go
- pkg/test/framework.go
Signed-off-by: Serge Catudal <serge.catudal@gmail.com>
Fix gcp authentication for the test frameworkd when running the commands:
*  `operator-sdk test local`
* `operator-sdk test cluster`
on a kubernetes cluster deployed on Google Cloud Platform.
> **NOTE:** tested successfully on a GKE cluster.
Closes #865
> Fix gcp authentication for the test framework

- .travis.yml
- test/e2e/memcached_test.go
**Description of the change:** This PR makes travis builds work correctly on forks of the sdk repo
**Motivation for the change:** This allows developers to test their changes in their own forks before making a PR. This was previously implemented in #766, but it caused the Gopkg.lock replacement to also occur on this repo's branches, which could mask typos in the generated Gopkg.lock. This PR includes a check to make sure it does not run for branches in this repo.
Closes #805
> test/e2e/memcached_test.go: make tests work on forks

- commands/operator-sdk/cmd/new.go
Especially when running end-to-end tests locally if something fails it
might be confusing to the user where the operator is located.
> commands/../new.go: Output the operator filepath

- internal/util/projutil/project_util.go
- test/e2e/memcached_test.go
**Description of the change:** symlink both `pkg` and `internal` dirs to the test project's `vendor` when running e2e tests locally, and some cleanup.
**Motivation for the change:** the e2e tests symlink `internal` so any future changes are picked up by local e2e tests.
> Symlink internal dir in e2e

- commands/operator-sdk/cmd/up/local.go
- pkg/ansible/controller/controller.go
- pkg/ansible/operator/operator.go
- pkg/ansible/proxy/proxy.go
- pkg/ansible/proxy/proxy_test.go
- pkg/ansible/runner/fake/runner.go
- pkg/ansible/runner/runner.go
- test/ansible-operator/cmd/ansible-operator/main.go
Adding support for the Ansible Operator to keep track of resources that are created by adding them for the controller to watch if we have already created a controller object for the specific GVK.
Performance Enhancement.
> pkg/ansible; Add watching of dependent resources

- pkg/ansible/runner/runner.go
Append current environment vars to Ansible Runner invocation.
Without doing this $PATH is completely screwed up and I cannot shell out to executables in my PATH.
> pkg/ansible; Append current environment vars to runner

- Gopkg.lock
- pkg/helm/release/manager.go
Updates the Helm reconciler to only apply patches when there are changes to be made to dependent resources
The Helm reconciler currently patches every dependent resource of a Helm chart during reconciliation even when the dependent resource does not require any changes, which results in unnecessary chatter with the API server.
> pkg/helm/release/manager.go: only apply patch if resources change

- .travis.yml
- Makefile
- hack/image/build-ansible-image.sh
1. Ensure `operator-sdk` binary is available during deploy stages
2. Explicitly build and use `x86_64-linux` binary in base image
Fixes the ansible deploy stage
> hack/image/build-ansible-image.sh,Makefile,.travis.yml: fix ansible deploy stage

- pkg/ansible/operator/operator.go
- pkg/ansible/proxy/proxy.go
- pkg/ansible/runner/runner.go
Prior to this the `watchDependentResources` field in watches.yaml was not being passed along to the runner. We were also setting the wrong values when re-queuing for the owner.
Fixes watching of dependent resources for Ansible Operator
In a follow-up PR I will address the corner-case of a namespaced operator trying to watch cluster-scoped resources.
> pkg/ansible; Fix implementation of watching dependent resources

- doc/sdk-cli-reference.md
**Description of the change:** Clean up SDK CLI reference doc
**Motivation for the change:** The sdk cli doc was not following certain best practices for markdown files and was also using the `bash` type for code blocks where `console` would be more appropriate and more readable.
> doc/sdk-cli-reference.md: clean up cli ref doc

- commands/operator-sdk/cmd/new.go
Adds all available operator types to shown in the "new" help message for the `--type`param
This way a user is aware of all available operator types by reading the help message.
> cmd: adds all possible types for --type arg in "new" sub-command

- pkg/scaffold/cmd.go
- pkg/scaffold/cmd_test.go
This PR is adding missings errors handling in the operator generated code from `pkg/scaffold`.
"errcheck" tool detects 2 errors on the operator generated code:
- cmd/manager/main.go:70:15:warning: error return value not checked
(leader.Become(context.TODO(), "memcached-operator-lock")) (errcheck)
- cmd/manager/main.go:78:9:warning: error return value not checked (r.Unset())
(errcheck)
Closes #893
> pkg/schaffold: Add missing errors handeling in main.go

- commands/operator-sdk/cmd/test/local.go
**Description of the change:** Use manifest generation helper functions for the `test local` subcommand.
**Motivation for the change:** The helper functions were created to simplify the code in the `test local` subcommand, but it seems that either we forgot to actually use the functions or those changes were mistakenly reverted in a different PR.
> commands/.../test/local.go: use manifest gen helpers

- Gopkg.lock
- Gopkg.toml
Add prune options to operator-sdk `Gopkg.toml`.
https://golang.github.io/dep/docs/Gopkg.toml.html#prune
Making use of the different prune options saves time and space when vendoring and removes the unused pkgs.
> Add different prune options to Gopkg.toml

- pkg/helm/run.go
Use set watch namespace to `metav1.NamespaceAll` to explicitly watch all namespaces.
We should use the Kubernetes defined value for all namespaces instead of relying on the empty string.
> pkg/helm/run.go: explicitly set metav1.NamespaceAll to watch all namespaces

- doc/ansible/dev/advanced_options.md
- pkg/ansible/runner/runner.go
Allow runner to manage the artifacts it creates. Setting to 20 at the moment, as a random guess on the first time. Could see the eventual need to make this configurable. Open to doing it in this PR if others feel it is necessary. 
/cc @mhrivnak
> ansible/runner: Adding ability to rotate artifacts via runner

- pkg/scaffold/ansible/gopkgtoml.go
- pkg/scaffold/helm/gopkgtoml.go
Adds additional overrides to the Gopkg.toml scaffolds for Ansible and Helm migrated operators, which are necessary for `dep ensure` to succeed, and therefore also necessary to build the resulting migrated operator.
The Ansible and Helm projects that result from calling `operator-sdk migrate` are broken.
> pkg/scaffold/(ansible|helm)/gopkgtoml.go: fix dep ensure errors

- pkg/ansible/proxy/proxy.go
* Adds a `Content-Type` header to our cache.
* Checks if a subresource is present on the request before injecting owner reference
Kubectl exec now works from within Ansible Operator tasks
Closes #911
> pkg/ansible/proxy; Do not inject owner references on subresource requests

- CHANGELOG.md
- pkg/scaffold/cmd.go
- pkg/scaffold/cmd_test.go
- pkg/scaffold/operator.go
- pkg/scaffold/operator_test.go
- test/e2e/memcached_test.go
Removes the readiness check that prevented non-leader operator pods from becoming ready. This issue causes operator deployment updates to fail to deploy.
Closes #920
> pkg/scaffold: fixing deadlock caused by readiness probe

- pkg/scaffold/ansible/playbook.go
Use `.yml` for playbook scaffolding
Breaks scaffolding currently.
Closes #933
> pkg/scaffold/ansible; Use yml as playbook extension

- commands/operator-sdk/cmd/migrate.go
- doc/ansible/dev/developer_guide.md
- doc/ansible/user-guide.md
- doc/sdk-cli-reference.md
- hack/tests/e2e-ansible-molecule.sh
- pkg/scaffold/ansible/dockerfilehybrid.go
> Make migrate command look for playbook.yml instead of .yaml

- Gopkg.lock
- pkg/scaffold/resource.go
Currently operator-sdk does not allow to use `-` for api groups as:
```
$ operator-sdk add api --api-version=node-problem-detector.operator.k8s.io/v1alpha1 --kind=NodeProblemDetector
INFO[0000] Generating api version node-problem-detector.operator.k8s.io/v1alpha1 for kind NodeProblemDetector.
FATA[0000] group should consist of lowercase alphabetical characters
```
This validation is different from upstream's validation, and
operator-sdk cannot work if api groups uses `-`.
This patch changes to calls `IsDNS1123Subdomain()` which is same
validation for api groups with kubernetes's.
> Use same validation with k8s's for API resource group

- CHANGELOG.md
- pkg/scaffold/ansible/gopkgtoml.go
- pkg/scaffold/gopkgtoml.go
- pkg/scaffold/gopkgtoml_test.go
- pkg/scaffold/helm/gopkgtoml.go
- version/version.go
**Description of the change:** Release v0.4.0
> *: release v0.4.0

- hack/tests/e2e-ansible-molecule.sh
- test/ansible-memcached/prepare-test-image.yml
Fixes #958 
Unblocks #946 
Copies the :dev image into the Kubernetes-in-Docker container and uses that as the base instead of the versioned base image that is generated by default.
> hack/test,test: Use the :dev image as the base for testing Ansible Operator

- doc/helm/user-guide.md
Correct versions in Helm user guide (required for status subresource and correct CRD pluralization)
So users know that Kubernetes 1.11.3+ is required for the current version of the Helm operator.
> doc/helm/user-guide.md: update required kubernetes versions

- commands/operator-sdk/cmd/migrate.go
- hack/image/ansible/scaffold-ansible-image.go
- hack/tests/e2e-ansible-molecule.sh
- pkg/scaffold/ansible/dockerfilehybrid.go
- pkg/scaffold/ansible/k8s_status.go
- pkg/scaffold/ansible/molecule_test_local_playbook.go
- test/ansible-memcached/asserts.yml
- test/ansible-memcached/prepare-test-image.yml
- test/ansible-memcached/tasks.yml
Move k8s_status rendering all inside of scaffold
Add tests for k8s status
Adds k8s_status module into Ansible Operator scaffolding
k8s_status module is missing in 0.4.0 release.
> pkg/scaffold/ansible; Add k8s_status module

- hack/tests/e2e-ansible.sh
- pkg/ansible/controller/controller.go
- test/ansible-memcached/watches-foo-kind.yaml
Remove erroneous check to see if GV is already registered with Manager
Bug Fix
Closes #962
> pkg/ansible/controller; Remove IsVersionRegistered check

- doc/user-guide.md
**Description of the change:** `v1apha1` -> `v1alpha1`
**Motivation for the change:** Typos are bad
> Fix typo in user guide

- pkg/scaffold/ansible/molecule_test_cluster_playbook.go
- pkg/scaffold/ansible/molecule_test_local_playbook.go
- test/ansible-memcached/asserts.yml
Updates Travis CI Molecule tasks to prevent transient errors. Also updates CI to dump operator logs if reconciliation fails.
Fail CI less often for transient errors and make CI more robust.
> test/ansible, pkg/scaffold; Update Ansible Operator CI to prevent failures

- hack/tests/e2e-ansible.sh
- pkg/ansible/controller/controller.go
- test/ansible-memcached/watches-foo-kind.yaml
There is no need to skip adding the controller if the version is already registered.
This currently breaks the ability to watch multiple kinds in the same operator.
Closes #962
> pkg/ansible/controller; Remove IsAlreadyRegistered() check in controller

- hack/ci/check-doc-only-update.sh
In cases when PRs were force pushed and the commit range was not
valid, the PR job would still pass as we did catch the error. This adds
a check and exits in case of an invalid commit range.
Ran into a weird error when running tests, where the commit didn't exist anymore(I think), as it exited the `check-doc-only-update.sh` with `true` which in turn was passing my tests.
https://api.travis-ci.org/v3/job/479857827/log.txt
```bash
[0K$ source hack/ci/check-doc-only-update.sh
fatal: ambiguous argument '99b2197f26fa...3493d93a7547': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
Only doc files were updated, not running the CI. …
```
> hack/ci: Add check for valid commit range

- CHANGELOG.md
- commands/operator-sdk/cmd/up/local.go
**Description of the change:** Cherry pick commit from #983
**Motivation for the change:** It is a bug fix that applies to `v0.4.0`
> commands/.../up/local: fix kubeconfig and namespace handling (#983)

- README.md
Remove alpha status label from our README
To stop giving users the perception that the SDK is not ready for production.
> README.md: remove alpha label

- CHANGELOG.md
- pkg/helm/run.go
- pkg/scaffold/helm/operator.go
Adds leader election to the helm operator
To prevent contention between multiple running replicas of an operator.
> pkg/helm,pkg/scaffold/helm: add leader election

- Gopkg.lock
- Gopkg.toml
- commands/operator-sdk/cmd/scorecard/olm_tests.go
- commands/operator-sdk/cmd/scorecard/scorecard.go
- pkg/scaffold/olm-catalog/csv.go
- pkg/scaffold/olm-catalog/csv_test.go
- pkg/scaffold/olm-catalog/csv_updaters.go
**Description of the change:** update OLM version to latest non-breaking commit so the SDK has the newest CSV fields available. Also [standardized](https://golang.org/doc/effective_go.html#names) OLM import identifiers.
**Motivation for the change:** users should have access to the latest CSV fields. Updating OLM version is not a breaking change.
> OLM version update

- pkg/scaffold/cr.go
- pkg/scaffold/crd.go
`operator-sdk add crd` commands overwrites
`deploy/crds/app_v1alpha1_example_{crd,cr}.yaml` even if files exist.
This patch changes to skip overwrites if the file exists.
Fixes https://github.com/operator-framework/operator-sdk/issues/1006
> Do not let operator-sdk add crd overwrite exsiting file

- commands/operator-sdk/cmd/scorecard/scorecard.go
Executing `operator-sdk scorecard` without setting `kubeconfig` fails with
following error:
BEFORE:
```
$ operator-sdk scorecard --cr-manifest deploy/crds/app_v1alpha1_appservice_cr.yaml --olm-tests=false
Error: invalid configuration: no configuration has been provided
```
It is difficult to realize what config file was invalid by reading the message
`Error: invalid configuration: no configuration has been provided`.
This patch adds clear message when kubeconfig is missing or failed to
parse.
AFTER:
```
$ operator-sdk scorecard --cr-manifest deploy/crds/cache_v1alpha1_memcached_cr.yaml --olm-tests=false
Error: failed to build the kubeconfig: invalid configuration: no configuration has been provided
```
> Add clear error message when kubeconfig is missing for `operator-sdk scorecard`

- commands/operator-sdk/cmd/up/local.go
Changes `operator-sdk up local` for Go projects to stop using `go run` and instead use `go build` followed by executing the binary directly.
e2e tests that use `operator-sdk up local` are not properly cleaned up because [`go run` does not forward signals to its child process](https://github.com/golang/go/issues/15553#issuecomment-217162874).
As a result, there is a leftover process listening on port `8383` (for metrics exporting) that causes future runs of the e2e test to fail due to not being able to listen on port `8383`
> commands/operator-sdk/cmd/up/local.go: build and run binary directly

- commands/operator-sdk/cmd/add/crd.go
- pkg/scaffold/cr.go
- pkg/scaffold/crd.go
**Description of the change:** see #1007, but moved to `CRD` and `CR` instantiations.
**Motivation for the change:** some commands need to overwrite CRD manifests.
> add crd: only skip overwriting CRD's/CR's when explicitly adding them

- hack/tests/e2e-ansible-molecule.sh
- hack/tests/e2e-ansible.sh
- pkg/ansible/controller/controller.go
- test/ansible-memcached/asserts.yml
- test/ansible-memcached/secret/tasks/main.yml
- test/ansible-memcached/tasks.yml
- test/ansible-memcached/watches-v1-kind.yaml
Fixes controller.Add so that we aren't double-registering GVKs. We check if the GVK is already registered before we attempt to register it again.
Currently Ansible Operator is unable to watch any resources that exist in the core API groups.
> pkg/ansible/controller; Check if GVK is already registered

- test/test-framework/deploy/crds/cache_v1alpha1_memcached_crd.yaml
- test/test-framework/deploy/operator.yaml
**Description of the change:** The sdk's subcommand tests rely on a very old memcached example that has not been updated in 4 months. I've pushed up a new memcached operator image based on sdk `v0.4.0`. The old operator image did not support the status resource, so the new operator and manifests have been updated to work with subresources. This also adds validation for the CRD, which will be useful for #979.
**Motivation for the change:** Make tests work with subresources.
> test/test-framework/deploy/operator.yaml: update image

- .travis.yml
**Description of the change:** Make the `dep ensure` part of the `before_install` step verbose
**Motivation for the change:** `dep ensure` is currently stalling on many PRs, and it would be useful to see what's causing problems when situations like this arise.
> .travis.yml: make dep ensure verbose

- Gopkg.lock
- Gopkg.toml
- pkg/scaffold/ansible/gopkgtoml.go
- pkg/scaffold/cmd_test.go
- pkg/scaffold/controller_kind.go
- pkg/scaffold/controller_kind_test.go
- pkg/scaffold/gopkgtoml.go
- pkg/scaffold/gopkgtoml_test.go
- pkg/scaffold/helm/gopkgtoml.go
Update the dep constraints for the controller-runtime version to `v0.1.10` and the k8s.io deps to `kubernetes-1.13.1`.
Also removed the requirement for the `k8s.io/code-generator/cmd/openapi-gen` pkg since that has been moved to the repo `k8s.io/kube-openapi`.
Lagging behind the latest controller-runtime updates.
> pkg/scaffold: update to controller-runtime v0.1.10 and k8s 1.13.1

- commands/operator-sdk/cmd/scorecard/scorecard.go
- doc/test-framework/scorecard.md
- hack/tests/scorecard-subcommand.sh
**Description of the change:** Disable "Operator actions are reflected in status" test
**Motivation for the change:** This test is quite poor and very likely to fail on more complicated operators. It is too unreliable for the score to be meaningful, so it should be disabled and eventually replaced by more operator specific, user configured tests.
> commands/.../scorecard: disable inconsistent test

- Makefile
- commands/operator-sdk/cmd/build.go
- hack/image/build-scorecard-proxy-image.sh
**Description of the change:** Trim the GOPATH from binaries built with `install` or `build`.
**Motivation for the change:** Remove the home directory of the builder from the panic path.
Example of current panic output:
```
/home/apavel/go/src/github.com/operator-framework/operator-sdk/vendor/github.com/spf13/cobra/command.go:852 +0x30a
github.com/operator-framework/operator-sdk/vendor/github.com/spf13/cobra.(*Command).Execute(0xc4200f1180, 0xc4207d5f78, 0xc4200b6058)
/home/apavel/go/src/github.com/operator-framework/operator-sdk/vendor/github.com/spf13/cobra/command.go:800 +0x2b
main.main()
/home/apavel/go/src/github.com/operator-framework/operator-sdk/commands/operator-sdk/main.go:24 +0x27
```
Example of new panic output:
```
... …
```
> Makefile: trim gopath from panic logs

- pkg/leader/leader.go
Switch to using controller-runtime helper to get config.
See -> https://github.com/operator-framework/operator-sdk/pull/1037#discussion_r252663270
> pkg/leader: Switch to controller-runtime config pkg

- pkg/ansible/controller/controller.go
- pkg/helm/controller/controller.go
Set the reconciler to use the cache for a Reader.
The delegating reader will proxy unstructured calls to the API and not use the cache.
This is specifically for 0.4.0, there is a better mechanism when using controller-runtime v0.1.10
> ansible/controller,helm/controller: reconcile controller to use cache

- commands/operator-sdk/cmd/generate/k8s.go
Adds support for defaulter-gen in the code generation system.
Closes #1038
> commands/.../generate: add defaulter-gen support

- Makefile
- commands/operator-sdk/cmd/build.go
- hack/image/build-scorecard-proxy-image.sh
**Description of the change:** Trim the GOPATH from binaries built with `install` or `build`.
**Motivation for the change:** Remove the home directory of the builder from the panic path.
> Makefile: trim gopath from panic logs (#1042)

- commands/operator-sdk/cmd/new.go
The --api-version and --kind flags are only supported for the
ansible and helm type projects. 
This PR clarifies this, there is already an error msg is you try to set those flags, but should prevent the user setting them in the first place.
Welcoming suggestions for better wording!
Closes https://github.com/operator-framework/operator-sdk/issues/856
> commands/../new.go: Clarify flags use cases

- pkg/ansible/proxy/proxy.go
- test/ansible-memcached/asserts.yml
This will allow ansible operator to re-watch dependent resources on an operator pod restart or on the loss of leader status. 
Operator pods are expected to be restarted or to lose leader status
> pkg/ansible/proxy: adding ability for dependent watches to be recovered

- pkg/ansible/controller/reconcile.go
* will alert the user to when reconcile is happening
* will show the user the last results from ansible
* handles the case when the operator is failing.
Better messaging to users when things are happening.
> pkg/ansible: Update the running condition when reconcile happens

- .travis.yml
**Description of the change:** Cache the $HOME/.cache/go-build
**Motivation for the change:** Significantly improve build speed for CI. In tests on my branch, the go and ansible CI tests increased in performance by ~4 minutes
Initial Build (before cache was created): https://travis-ci.org/AlexNPavel/operator-sdk/builds/489678685
Cached Build: https://travis-ci.org/AlexNPavel/operator-sdk/builds/489690596
The way that cache works:
CI checks if the current PR has a cache. If yes, use that.
CI checks if target branch has cache. If yes, use that.
CI checks if default branch (master) has cache. If yes, use that.
This should improve build times for most builds, as all of our dependencies will now be precompiled and only sdk changes and linking will need to be done by CI.
> .travis.yml: cache $HOME/.cache/go-build

- pkg/scaffold/crd.go
- pkg/scaffold/crd_test.go
**Description of the change:** populate a CRD's `Versions` field. `Version` is kept for backwards compatibility.
**Motivation for the change:** `Version` is deprecated in newer k8s api versions.
Closes #1012
> pkg/scaffold/crd*.go: support crd.Versions

- hack/tests/e2e-ansible-molecule.sh
- pkg/ansible/runner/internal/inputdir/inputdir.go
- test/ansible-inventory/ansible.cfg
- test/ansible-inventory/build/Dockerfile
- test/ansible-inventory/deploy/crds/inventory_v1alpha1_inventory_cr.yaml
- test/ansible-inventory/deploy/crds/inventory_v1alpha1_inventory_crd.yaml
- test/ansible-inventory/deploy/operator.yaml
- test/ansible-inventory/deploy/role.yaml
- test/ansible-inventory/deploy/role_binding.yaml
- test/ansible-inventory/deploy/service_account.yaml
- test/ansible-inventory/inventory/group_vars/test.yml
- test/ansible-inventory/inventory/hosts
- test/ansible-inventory/molecule/test-local/asserts.yml
- test/ansible-inventory/molecule/test-local/molecule.yml
- test/ansible-inventory/molecule/test-local/playbook.yml
- test/ansible-inventory/molecule/test-local/prepare.yml
- test/ansible-inventory/playbooks/playbook.yml
- test/ansible-inventory/plugins/filter/test.py
- test/ansible-inventory/roles/inventory/tasks/main.yml
- test/ansible-inventory/watches.yaml
If the `ANSIBLE_INVENTORY` environment variable is set, the Ansible Operator will copy it into the runner artifacts directory. This is a placeholder until the `--inventory` option to runner supports directories, or until it respects the `ansible.cfg`.
Allows users to specify more complex inventories, should at least partially unblock #954
> pkg/ansible/runner: Add ability to specify ANSIBLE_INVENTORY env variable

- doc/ansible/user-guide.md
documentation: fix typo in ansible user-guide
s/Memached/Memcached/
> documentation: fix typo in ansible user-guide

- hack/ci/check-doc-only-update.sh
**Description of the change:** Removes `-x` set option in check-doc-only-update
**Motivation for the change:** The `set -x` option was persisting throughout the entire test since we were sourcing the script, and this was causing the travis logs to become much more difficult to understand. We don't need the `-x` option for this script, so we can remove it to improve the travis logs.
> hack/ci/check-doc-only-update: don't set -x

- commands/operator-sdk/cmd/generate/openapi.go
- commands/operator-sdk/cmd/olm-catalog/gen-csv.go
- commands/operator-sdk/cmd/scorecard/olm_tests.go
- commands/operator-sdk/cmd/scorecard/resource_handler.go
- internal/util/k8sutil/crd.go
**Description of the change:** move getCRDs to `internal/util/k8sutil/crd.go` as an exported function, and add a helper to get CRD files.
**Motivation for the change:** getting CRD's or their manifests occurs in at least one other place in the SDK. These two helpers will be useful in `generate openapi` and other commands. For example, PR #1016 will use them.
> commands/.../scorecard: move getCRDs to k8sutil

- CHANGELOG.md
- pkg/test/main_entry.go
**Description of the change:** Build the test local binary instead of using `go run`. Essentially runs `--up-local` in the same way that #1010 changed the `up local` subcommand to work.
**Motivation for the change:** This allows us to kill the process on exit correctly, which wouldn't always work correctly when using `go run`
Closes #1088
> pkg/test/main_entry.go: build local binary instead of `go run`

- internal/util/fileutil/file_util.go
- pkg/scaffold/ansible/k8s_status.go
- pkg/scaffold/crd.go
- pkg/scaffold/customrender.go
- pkg/scaffold/olm-catalog/concat_crd.go
- pkg/scaffold/olm-catalog/csv.go
- pkg/scaffold/scaffold.go
**Description of the change:** add an `afero.Fs` field to Scaffold and use it in place of directly calling functions from the `os` package. `CustomRenderer`s must now implement `SetFS()`.
**Motivation for the change:** more versatile, enhances our ability to test complex scaffolds. `SetFS()` injects a `Scaffold`'s fs at runtime so we don't have unnecessarily disconnected fs'.
> pkg/scaffold: use afero.Fs instead of os package directly

- pkg/scaffold/addtoscheme.go
- pkg/scaffold/controller_kind.go
- pkg/scaffold/doc.go
- pkg/scaffold/register.go
- pkg/scaffold/resource.go
- pkg/scaffold/scaffold.go
- pkg/scaffold/types.go
Currently, if API group contains hyphen(`-`), `operator-sdk add controller` 
fails to execute because Go does not allow us to use
hyphone for import package alias.
Since API group accepts hyphen in Kubernetes, openshift-sdk should
handle hyphen in API group as well.
This patch replaces `-` with `_` in generated code.
Fixes https://github.com/operator-framework/operator-sdk/issues/997
> Remove hyphen from controller generated code

- doc/dev/release.md
**Description of the change:** Remove `pool.sks-keyservers.net` hyperlink (and change 1 URL to relative path).
**Motivation for the change:** The `pool.sks-keyservers.net` URL occasionally results in a 502 or 404 error
> doc/dev/release.md: remove flaky hyperlink

- doc/user-guide.md
Added a brief overview of the two leader election implementations that can be used along with their respective tradeoffs and example code snippets on how to use them. 
Fixes #665 #784 
I'm aiming to keep the explanations as concise as possible without being too vague and referring to the pkg godocs for more details on the implementations themselves.
I also need a second opinion on whether this is bloating the user-guide, and if we would rather keep this in a separate doc and just link it from the user-guide.
> doc/user-guide: show how to enable both leader election options

- commands/operator-sdk/cmd/test/local.go
- pkg/test/main_entry.go
**Description of the change:** Disable creation of namespaced resources when running `test local --up-local` and fix running of local command in `test local --up-local`.
**Motivation for the change:** `test local --up-local` was broken. Fixes #1105
> commands/.../test,pkg/test: fix test local --up-local

- commands/operator-sdk/cmd/test/local.go
**Description of the change:** Move error check to correct location
**Motivation for the change:** Check error correctly
/cc @hasbro17
> commands/.../test/local: move an error check to correct location

- CHANGELOG.md
- commands/operator-sdk/cmd/test/local.go
**Description of the change:** Disable creation of namespaced resources when running `test local --up-local` and fix running of local command in `test local --up-local`.
**Motivation for the change:** `test local --up-local` was broken. Fixes #1105
This is a cherry pick based on PR #1109
> commands/.../test,pkg/test: fix test local --up-local (#1109)

- Gopkg.lock
- commands/operator-sdk/cmd/test/cluster.go
- pkg/k8sutil/constants.go
- pkg/k8sutil/k8sutil.go
- pkg/leader/leader.go
- pkg/metrics/metrics.go
Add Deployment ownerReference to metrics Service object, by getting the Pod the operator is currently running in and via ReplicaSet getting the Deployment Object.
When operator Deployment is deleted currently the metrics Service operator creates was not deleted.
Closes https://github.com/operator-framework/operator-sdk/issues/459
> pkg/metrics: Add Deployment ownerReference to metrics Service object

- doc/dev/developer_guide.md
- doc/dev/release.md
- doc/versioning.md
Looks like github added a language path segment before `articles`.
> doc/*: fix broken links

- doc/helm/dev/developer_guide.md
- doc/helm/project_layout.md
- doc/helm/user-guide.md
More link issues, this time with helm docs. Not sure why `marker` isn't catching the redirect like my browser is.
> doc/helm/*: fix helm docs links

- pkg/scaffold/helm/operator.go
> pkg/scaffold/helm/operator.go: Remove metrics port

- pkg/scaffold/ansible/molecule_default_molecule.go
- pkg/scaffold/ansible/molecule_test_local_molecule.go
- test/ansible-inventory/molecule/test-local/molecule.yml
- test/ansible-memcached/molecule.yml
Molecule now requires you to set the `override_command` option to `false` in order to prevent it from overriding the `CMD` directive on a docker image you're using. This PR brings the generated molecule.yml files up to date. See https://github.com/ansible/molecule/pull/1771
We're going to break without it.
> Molecule override cmd

- pkg/scaffold/olm-catalog/csv.go
- pkg/scaffold/olm-catalog/testdata/deploy/olm-catalog/app-operator/0.1.0/app-operator.v0.1.0.clusterserviceversion.yaml
**Description of the change:** add `spec.installModes` to CSV's that don't have them.
**Motivation for the change:** SDK operators must specify that the `MultiNamespace` install mode is not supported.
> pkg/scaffold/olm-catalog: add InstallModes to CSV's

- pkg/helm/run.go
Fixes logging about which namespaces are watched.
Addressing [this comment](https://github.com/operator-framework/operator-sdk/pull/917#discussion_r252010384) since #917 will likely be closed in favor of #1102.
> pkg/helm/run.go: fix logging when WATCH_NAMESPACE=""

- pkg/scaffold/olm-catalog/testdata/deploy/olm-catalog/app-operator/0.1.0/app-operator.v0.1.0.clusterserviceversion.yaml
- pkg/scaffold/olm-catalog/testdata/deploy/operator.yaml
- test/ansible-inventory/deploy/operator.yaml
- test/test-framework/deploy/namespace-init.yaml
- test/test-framework/deploy/olm-catalog/memcached-operator/0.0.2/memcached-operator.v0.0.2.clusterserviceversion.yaml
- test/test-framework/deploy/operator.yaml
metrics: Cleanup unused container port
Code cleanup for removing containerPort:60000. It is deprecated.
Closes #1130
> Code cleanup for removing unused container port:60000

- CHANGELOG.md
- doc/sdk-cli-reference.md
- images/scorecard-proxy/Dockerfile
- pkg/scaffold/build_dockerfile.go
- pkg/scaffold/build_dockerfile_test.go
- pkg/scaffold/helm/dockerfilehybrid.go
Update Go, Helm, and Scorecard base images to use `registry.access.redhat.com/ubi7/ubi-minimal:7.6`
To make simplify the process for making operators available in OCP.
Question: should we make this configurable via a flag or force this change on all users? Note that even if we force it on all users, they can always change their Dockerfile to use whatever base image they want.
/cc @dmesser @robszumski
> Use RHEL UBI for go, helm, and scorecard base images

- pkg/scaffold/olm-catalog/csv_updaters.go
- pkg/scaffold/olm-catalog/testdata/deploy/crds/app_v1alpha1_app_crd.yaml
- pkg/scaffold/olm-catalog/testdata/deploy/crds/app_v1alpha2_app_crd.yaml
- pkg/scaffold/olm-catalog/testdata/deploy/olm-catalog/app-operator/0.1.0/app-operator.v0.1.0.clusterserviceversion.yaml
* pkg/scaffold/olm-catalog: remove required `CRDDescription` update and test preservation of required `CRDDescription`s
**Motivation for the change:** [required `CRDDescription`s](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/Documentation/design/building-your-csv.md#required-crds) are user-defined fields since their CRD manifests will not be present in an operator package or project.
> pkg/scaffold/olm-catalog: remove required CRDDescription updater

- CHANGELOG.md
- doc/sdk-cli-reference.md
- images/scorecard-proxy/Dockerfile
- pkg/scaffold/build_dockerfile.go
- pkg/scaffold/build_dockerfile_test.go
- pkg/scaffold/helm/dockerfilehybrid.go
Changing base image for go, helm, and scorecard to `registry.access.redhat.com/ubi7-dev-preview/ubi-minimal:7.6`
To use the correct base image
/cc @robszumski
> Use registry.access.redhat.com/ubi7-dev-preview/ubi-minimal:7.6 for UBI

- OWNERS
**Description of the change:** Add OWNERS file. Currently, all reviewers are also approvers.
**Motivation for the change:** To start integrating with Openshift Prow automation, we need an OWNERS file. For now, this won't change the way we approve of merge PRs, but we may start to use prow for those features in the future.
> OWNERS: add file

- pkg/test/e2eutil/wait_util.go
- test/e2e/incluster-test-code/memcached_test.go.tmpl
- test/e2e/memcached_test.go
* Re-enables and fixes leader election tests
* Adds `e2eutil.WaitForDeletion()` to help avoid test flakes 
Closes #934
> test/e2e,pkg/test/e2eutil: re-enable and fix leader election e2e test

- Makefile
While working on operator-sdk, I lost a lot of time running `make build/operator-sdk` thinking it was rebuilding my changes only to find out it was only looking at the executable and never taking into account the changed sources. By making `build/%` dependent on the sources anytime you changed the source.
> Makefile: add SOURCES to build

- OWNERS
- doc/ansible/OWNERS
- pkg/ansible/OWNERS
- pkg/scaffold/ansible/OWNERS
- test/ansible-inventory/OWNERS
- test/ansible-memcached/OWNERS
**Description of the change:** This commit adds fabianvf and jmrodri to OWNERS files for ansible related directories. This prevents them from automatically being added as reviewers by the ci-robot for non-ansible related SDK PRs.
**Motivation for the change:** Prevent the ci-robot from automatically requesting reviews from people working specifically on the ansible operator on non-ansible related PRs.
/cc @jmrodri @fabianvf @shawn-hurley
> OWNERS,*/OWNERS: add fabianvf and jmrodri to OWNERS for ansible

- pkg/scaffold/ansible/molecule_default_molecule.go
- pkg/scaffold/ansible/molecule_test_local_molecule.go
- test/ansible-memcached/molecule.yml
* use new override_command option
* Update tests
(cherry picked from commit 9afbe83d410e73b2e70bd5794bd87e5440a2329c)
> Molecule override cmd (#1131)

- test/e2e/memcached_test.go
Add wait polling for getting leader lock configmap in e2e test.
The e2e test sometimes flakes trying to fetch the leader lock config map before it is present.
Closes #1152
> test/e2e/memcached_test.go: poll for leader lock configmap

- pkg/ansible/runner/runner.go
- test/ansible-memcached/asserts.yml
Creates a directory called "latest" in the artifacts directory, which is linked to the most recent ansible run
This will greatly ease the debugging experience, as there will be a single copy-pasteable command that can be run to view a human readable log.
> [pkg/ansible/runner] link latest artifacts directory to 'latest'  ident

- doc/ansible/dev/advanced_options.md
- doc/ansible/dev/dependent_watches.md
Add documentation for watching dependent resources.
> doc/ansible/dev/*: add documentation for dependent watches option

- pkg/scaffold/olm-catalog/testdata/deploy/olm-catalog/app-operator/0.1.0/app-operator.v0.1.0.clusterserviceversion.yaml
- pkg/scaffold/olm-catalog/testdata/deploy/role.yaml
- pkg/scaffold/role.go
- pkg/scaffold/role_test.go
- test/test-framework/deploy/namespace-init.yaml
- test/test-framework/deploy/olm-catalog/memcached-operator/0.0.2/memcached-operator.v0.0.2.clusterserviceversion.yaml
- test/test-framework/deploy/role.yaml
Because the Service now adds an OwnerReference wherever
OwnerReferencesPermissionEnforcement is enabled this role is needed
to be able to create an OwnerReference in the Service that points to the
Deployment.
Because we determine the owner of the Service dynamically, this role
would need to be adjusted by the user to fit whatever type of deployment
resource they use.
> pkg,test: Add deployments/finalizers to roles

- .travis.yml
- Makefile
**Description of the change:** Only run the unit, sanity, and markdown checks on post-merge or non-master PRs
**Motivation for the change:** Prow currently runs the unit, sanity, and markdown tests on all PRs targeting master and has now been set as a require status check in the master branch protection rules
> .travis.yml,Makefile: disable travis tests that run in prow

- doc/user-guide.md
- doc/user/metrics/README.md
- doc/user/metrics/service-monitor.md
- doc/user/metrics/service_monitor.md
Basic documentation for monitoring.
> doc/user: Add metrics and service-monitor docs

- doc/ansible/dev/testing_guide.md
Adds documentation for ansible e2e testing. Followup to #861 
> Add Ansible Operator testing guide

- Gopkg.lock
- test/e2e/memcached_test.go
- vendor/github.com/prometheus/prometheus/LICENSE
- vendor/github.com/prometheus/prometheus/NOTICE
- vendor/github.com/prometheus/prometheus/util/promlint/promlint.go
The test gets the metrics data via the proxy and checks the metrics
are present. It also checks the lint of metrics using the prometheus
linter.
Note: There is an invalid metric in upstream Kubernetes, which is fixed
in 1.14 release. We choose to ignore that one, until we migrate to 1.14
release.
To ensure we always have working metrics in generated operators.
>  test/e2e/memcached_test.go: Add metrics test

- commands/operator-sdk/cmd/scorecard/olm_tests.go
- hack/tests/scorecard-subcommand.sh
**Description of the change:** Set maximum points for AnnotationsContiansExamples test to 1.
**Motivation for the change:** I forgot to set the maximum points for this test to 1 in the refactor, so now this was resulting in a score of 1/0 on pass instead of 1/1, and a fail was resulting in 0/0 instead of 0/1.
> commands/.../scorecard: set annotation example test max points to 1

- pkg/ansible/operator/operator.go
add default workers value to the string of the message
remove log panic logs from ansible operators when setting this option
Thanks @matihost for the report
> Adding max workers to the string of the message instead of a logr field

- pkg/test/context.go
- pkg/test/main_entry.go
**Description of the change:** This commit removes `Cleanup`'s dependence on `t`.
**Motivation for the change:** The test library has functions that are useful outside of `go test`, such as `createFromYAML`, `ctx` resource deletion, and auto setting of resource cleanup when using the framework's client. The only function that required `t` and would fail if it did not exist was `Cleanup`, as other function could handle if it was nil.
> pkg/test: remove dependence on ctx.t

- .github/ISSUE_TEMPLATE/bug-report.md
Don't ask for Gopkg.lock info in bug report template
That info isn't useful in most cases and makes the issue message long enough to be unreadable.
> .github: don't ask for Gopkg.lock

- commands/operator-sdk/cmd/migrate.go
- doc/ansible/dev/developer_guide.md
- doc/ansible/user-guide.md
- hack/image/ansible/scaffold-ansible-image.go
- hack/tests/e2e-ansible.sh
- pkg/scaffold/ansible/ao_logs.go
- pkg/scaffold/ansible/deploy_operator.go
- pkg/scaffold/ansible/dockerfilehybrid.go
- test/ansible-memcached/asserts.yml
Adds a sidecar container to Ansible Operator deployments that aggregates the stdout of the ansible logs.
Currently looking at the ansible stdout log (what people are generally accustomed to seeing with Ansible) is a huge pain (you need to exec into a pod, and look at the stdout file in a very specific directory, `/tmp/ansible-operator/runner/{group}/{version}/{kind}/{namespace}/{name}/artifacts/{job id}/stdout`). This PR allows you to see the aggregated stdout without interfering with the machine readability of the standard operator logs.
- https://github.com/openshift/ocp-release-operator-sdk/pull/4
> Add log aggregator sidecar for Ansible Operator

- doc/helm/user-guide.md
doc/helm: Fix minor typos in helm/user-guide.md
> doc/helm: Fix minor typos in helm/user-guide.md

- doc/user-guide.md
When using ` cluster-scoped` flag, in the file `deploy/role_binding.yaml` CluserRole is used instead of Role
Making the docs more accurate
> updated description when using cluster-scoped flag

- doc/ansible/user-guide.md
- doc/helm/user-guide.md
When using cluster-scoped flag, in the file deploy/role_binding.yaml CluserRole is used instead of Role. Keeping in sync ansible and helm cause of pull request #1190
Making the docs more accurate
> updated description when using cluster-scoped flag (ansible & helm)

- doc/user/logging.md
- pkg/log/zap/flags.go
- pkg/log/zap/flags_test.go
- pkg/log/zap/logger.go
- pkg/log/zap/logger_test.go
With this feature we can use --zap-level 10 and this will allow
log.V(10).Info("hello world") to be seen in the logs. Prior to this
change debug (log.V(1)) was the lowest value attainable.
We also disable sampling when using an integer less than -1
(i.e. beyond debug). The zap sampling code assumes the lowest number for
sampling is DebugLevel (-1) which isn't the case in this scenario.
Disabling sampling makes sense at this point because sampling is used
for better performing logs which isn't required for trace level type
logs.
We also handle negative values being passed in.
> log: allow different log levels

- CHANGELOG.md
- pkg/scaffold/ansible/gopkgtoml.go
- pkg/scaffold/gopkgtoml.go
- pkg/scaffold/gopkgtoml_test.go
- pkg/scaffold/helm/gopkgtoml.go
- version/version.go
Create new release
Create new release
> v0.6.0 release version

- doc/user/metrics/README.md
Explain how to replace the default `deployments/finalizers` role in case
user is using another way of creating the operator pod(s).
Leftover from https://github.com/operator-framework/operator-sdk/pull/1157#discussion_r262022655
> doc/user/metrics/README.md: Add garbage collection

- doc/ansible/user-guide.md
- doc/helm/user-guide.md
- doc/user-guide.md
This change modifies the user guides (Go, Helm, and Ansible) first meaningful reference to quay.io so that the text links to the quay.io website.
In the off chance that someone hasn't has only heard of a single
container registry (eg Docker Hub), provide a hyperlink to quay.io on
its first mention. Plus, having the link provides for a little less
typing for people to get to the site.
> docs: Make first ref to quay.io link to https://quay.io

- CHANGELOG.md
- commands/operator-sdk/cmd/root.go
- commands/operator-sdk/cmd/version.go
> Version command

- CHANGELOG.md
- Gopkg.lock
- Gopkg.toml
- pkg/scaffold/helm/gopkgtoml.go
- vendor/k8s.io/helm/pkg/chartutil/save.go
Bumps helm version to 2.13.1
Helm 2.13.1 fixes an issue in `chartutil.SaveDir()` that causes `operator-sdk new mychart-operator --type=helm --helm-chart=./my-chart` to fail if `./mychart` contains files in subdirectories of `./mychart/templates` (e.g. `./mychart/templates/hooks/myhook.yaml`)
> Gopkg.toml,pkg/scaffold/helm/gopkgtoml.go: bump to helm 2.13.1

- README.md
- doc/ansible/user-guide.md
- doc/helm/user-guide.md
- doc/user-guide.md
Adds details to the README and user-guide about installing the `operator-sdk` tool via the Homebrew formula.
This adds instructions to install the operator-sdk tool via a Homebrew formula. This is a common package manager for those running macOS, and ensures that the tool (and `go`/`dep`) are installed properly in one step.
ref https://github.com/Homebrew/homebrew-core/pull/37826
> docs: add instructions to install via Homebrew

- Gopkg.toml
- pkg/scaffold/gopkgtoml.go
- pkg/scaffold/gopkgtoml_test.go
**Description of the change:** removed pin of `github.com/census-instrumentation/opencensus-proto`.
**Motivation for the change:** `v0.2.0` was previously broken, now fixed.
> *: remove github.com/census-instrumentation/opencensus-proto pin

- CHANGELOG.md
- pkg/scaffold/ansible/gopkgtoml.go
- pkg/scaffold/gopkgtoml.go
- pkg/scaffold/gopkgtoml_test.go
- pkg/scaffold/helm/gopkgtoml.go
- version/version.go
**Description of the change:** Bump v0.6.x branch to track the branch instead of v0.6.0 tag
**Motivation for the change:** Version bump for release branch
> pkg/scaffold,version: bump to track v0.6.x branch

- commands/operator-sdk/cmd/add/api.go
- commands/operator-sdk/cmd/generate/internal/genutil.go
- commands/operator-sdk/cmd/generate/k8s.go
- commands/operator-sdk/cmd/generate/openapi.go
**Description of the change:** allow users to pass in a header file for `generate k8s`, or use a temp file if one is not supplied.
**Motivation for the change:** `deepcopy-gen` and `defaulter-gen` now require header files, and will fail if not provided. I noticed this when testing the SDK with go modules; `go mod vendor` removes default header files from the gengo repo.
> commands/.../generate/*: set generator header file if not supplied

- test/ansible-inventory/plugins/filter/test.py
Remove GPL license from test filter plugin stub
One of the files used for testing had a GPL license header that should not have been added, and the person named was not actually the author of the file.
I am the author of the test plugin stub in question.
closes #1213
> Remove invalid GPL license from test file

- doc/dev/release.md
**Description of the change:** Add a new section to create a new release branch for minor releases. This PR also includes some minor formatting fixes.
**Motivation for the change:** We did not make release branches for `v0.5.x` and `v0.6.x` since we did not have this in the release doc.
> doc/dev/release.md: add new branch release

- CHANGELOG.md
- doc/dev/developer_guide.md
- doc/dev/release.md
- doc/versioning.md
- pkg/scaffold/ansible/gopkgtoml.go
- pkg/scaffold/ansible/molecule_default_molecule.go
- pkg/scaffold/ansible/molecule_test_local_molecule.go
- pkg/scaffold/gopkgtoml.go
- pkg/scaffold/gopkgtoml_test.go
- pkg/scaffold/helm/gopkgtoml.go
- test/ansible-inventory/molecule/test-local/molecule.yml
- test/ansible-memcached/molecule.yml
- version/version.go
**Description of the change:** Bump v0.5.x branch to track the branch instead of v0.5.0 tag
**Motivation for the change:** Version bump for release branch
> pkg/scaffold,version: bump to track v0.5.x branch

- pkg/scaffold/ansible/build_dockerfile.go
- pkg/scaffold/ansible/dockerfilehybrid.go
- pkg/scaffold/helm/dockerfile.go
- pkg/scaffold/helm/dockerfilehybrid.go
Minor change to reorder the Helm operator Dockerfile template to copy the `watches.yaml` file _before_ the `helm-charts` directory.
It is very unlikely that you will make a change to watches.yaml and create a new Docker image without a corresponding change to the helm-charts directory. However, it's very plausible that you may make a change to the helm-charts directory to modify an existing template without touching the watches file. Previously, this would cause the creation of additional layer for the watches file, since the file addition layer happens after the helm-charts directory is added. With this change, the watches.yaml image layer can be reused for multiple operator images until the file itself actually changes.
> fix(helm dockerfile): reduce extraneous layers

- internal/util/yamlutil/scan.go
**Description of the change:** Check length of yaml token after trimming spaces
**Motivation for the change:** Fix #1225
> internal/util/yamlutil: fix empty yaml bug

- CHANGELOG.md
- cmd/operator-sdk/scorecard/scorecard.go
**Description of the change:** Change `namespace-manifest` flag in scorecard to `namespaced-manifest` flag.
**Motivation for the change:** Match other commands like `test local` and `build`. Closes #1243
> cmd/.../scorecard: change namespaced-manifest flag

- CHANGELOG.md
- commands/operator-sdk/cmd/generate/internal/genutil.go
- commands/operator-sdk/cmd/generate/k8s.go
- commands/operator-sdk/cmd/generate/openapi.go
- test/e2e/memcached_test.go
> Backport: commands/.../generate: verbose codegen by default (#1271)

- internal/pkg/scaffold/gopkgtoml.go
- internal/pkg/scaffold/gopkgtoml_test.go
Bumps up prometheus-operator to 0.29.0 release.
> internal/pkg/scaffold/gopkgtoml*: Update prometheus-operator

- Gopkg.lock
- cmd/operator-sdk/build/cmd.go
- cmd/operator-sdk/new/cmd.go
- cmd/operator-sdk/test/cluster.go
- cmd/operator-sdk/test/local.go
- cmd/operator-sdk/up/local.go
- internal/util/projutil/project_util.go
* internal/util/projutil/project_util.go: functions for detecting operator type
* internal/util/projutil/project_util.go: remove scaffold dependency
* cmd/operator-sdk: return `projutil.ErrUnknownOperatorType` if no valid operator type found
**Motivation for the change:** new functions in `projutil` will help type checking projects for `print-deps` in #1001. Code that checks operator type should return a standard error.
> internal/util/projutil: standardize operator type checks

- doc/ansible/user-guide.md
fixed the `sed` command for `REPLACE_IMAGE`
added a step to properly define the `imagePullPolicy` in the deployment
Closes #1264
> update sed commands for image name and pull policy

- CHANGELOG.md
- Gopkg.lock
- doc/user/logging.md
- pkg/log/zap/flags.go
Adding the ability to set the log level for klog if the zap-level is for enough verbosity.
Allowing users to get more debug level logs with help when diagnosing problems.
> pkg/log/zap: Adding ability to get client-go and trace level logs

- CHANGELOG.md
- internal/pkg/scaffold/resource.go
**Description of the change:** only check if `group` in `group/version` is empty, not if it has a specific number of sub-domains.
**Motivation for the change:** From #1191 on adding new API's:
>But I guess that only makes sense for defining new apis. If you're adding a controller to watch a k8s resource(with a single word group) as the primary resource then that'll be a problem.
Closes #1191
> internal/pkg/scaffold/resource.go: relax group format check

- CHANGELOG.md
- cmd/operator-sdk/build/cmd.go
- doc/sdk-cli-reference.md
This PR adds buildah support.
operator-sdk should support building image by using buildah. 
There is an existing discussion for motivation in https://github.com/operator-framework/operator-sdk/pull/563 .
> cmd/build: Add buildah support

- Gopkg.lock
- pkg/ansible/proxy/kubectl.go
- vendor/k8s.io/kubernetes/pkg/kubectl/util/pod_port.go
- vendor/k8s.io/kubernetes/pkg/kubectl/util/service_port.go
- vendor/k8s.io/kubernetes/pkg/kubectl/util/umask.go
- vendor/k8s.io/kubernetes/pkg/kubectl/util/umask_windows.go
- vendor/k8s.io/kubernetes/pkg/kubectl/util/util.go
Replaces unix-specific `syscall.Umask` with `util.Umask` so that windows builds of operator-sdk work.
See: https://github.com/kubernetes/kubernetes/blob/204d994aca210e1ef20ea947ae0555df7b70a994/pkg/kubectl/proxy/proxy_server.go#L242-L244
Closes #1298
> pkg/ansible/proxy/kubectl.go: support windows build

- CHANGELOG.md
- pkg/helm/controller/reconcile.go
Remove `ReleaseFailed` condition when reconciling an existing deployed release.
If a change is made to the CR spec that causes a release failure, a `ReleaseFailed` condition is added to the status conditions. If that change is then reverted to its previous state, the operator will stop attempting the release and will resume reconciling.
In this case, we need to remove the `ReleaseFailed` condition because the failing release is no longer being attempted.
> pkg/helm/controller/reconcile.go: fix conditions logic

- CHANGELOG.md
- Gopkg.lock
- internal/pkg/scaffold/cmd.go
- internal/pkg/scaffold/cmd_test.go
- pkg/restmapper/dynamicrestmapper.go
This addresses a controller-runtime bug which can affect operators
that create CRD's and then CR's that refer to them, as the default
mapper never "sees" the new CRD's.
Fixes #1328 (originally from @danwinship)
> pkg/restmapper,scaffold/cmd.go: override default restmapper

- hack/tests/e2e-ansible.sh
- internal/pkg/scaffold/ansible/build_test_framework_dockerfile.go
- internal/pkg/scaffold/ansible/dockerfilehybrid.go
**Description of the change:** pin python library versions in `internal/pkg/scaffold/ansible/dockerfilehybrid.go` and `internal/pkg/scaffold/ansible/build_test_framework_dockerfile.go`.
- `urllib3` version conflict between [`kubernetes`](https://travis-ci.org/operator-framework/operator-sdk/jobs/524268811#L916-L917) and [`requests`](https://travis-ci.org/operator-framework/operator-sdk/jobs/524268811#L1178)
- `six` version conflict between [`molecule`](https://travis-ci.org/operator-framework/operator-sdk/jobs/524286120#L1444) and [`ansible-runner`](https://travis-ci.org/operator-framework/operator-sdk/jobs/524286120#L3159)
> fix ansible e2e

- CHANGELOG.md
- hack/tests/e2e-helm.sh
- pkg/helm/controller/reconcile.go
- pkg/helm/internal/types/types.go
- pkg/helm/internal/types/types_test.go
- pkg/helm/release/manager.go
This PR removes the full release status from the status condition and adds a new `deployedRelease` field on the top level status that contains just the release name and manifest.
This PR also removes code that syncs the release state from the status condition to the storage backend, which was leftover from when the Helm operator used the in-memory backend. Now that the CR status does not contain the full release state, there is nothing to sync.
With the Helm storage backend moved to in-cluster secrets, it is no longer necessary to store the full release state on the CR status. This change will de-clutter the CR status to make it easier for users to find what they're looking for.
> pkg/helm,hack/tests: slim down release information in Helm CR status

- Gopkg.lock
- cmd/operator-sdk/build/cmd.go
- cmd/operator-sdk/test/local.go
- cmd/operator-sdk/up/local.go
- internal/util/projutil/exec.go
- internal/util/projutil/project_util.go
- pkg/test/main_entry.go
- test/e2e/memcached_test.go
- vendor/github.com/mitchellh/go-homedir/LICENSE
- vendor/github.com/mitchellh/go-homedir/homedir.go
* internal/util/projutil/exec.go: move commands executing external binaries to exec.go, add `GoBuild()` and `GoTest()` functions to run `go build`/`go test`, and `GoBuildOptions` to configure both
* cmd/operator-sdk/{build/cmd.go,up/local.go}: use `GoBuild()` and `GoTest()`
* pkg/test/main_entry.go: use GoBuild() to run go build
**Motivation for the change:** The SDK calls `go build` and `go test` in several places. These functions provide convenient wrappers that sets up args based on the users' environment.
This code was split out and enhanced from #1001
> internal/util/projutil: add Go{Build,Test{() functions to run go build/test

- pkg/k8sutil/k8sutil.go
Set `APIVersion ` and `Kind` of the `Pod` before returning the object
We were seeing problems when the metrics Service tries to create an `OwnerRef`, because the fields were empty the Service creation failed.
cc @shawn-hurley @jmrodri
> pkg/k8sutil/k8sutil.go: Set kind and APIVersion

- CHANGELOG.md
- internal/pkg/scaffold/ansible/build_test_framework_dockerfile.go
- internal/pkg/scaffold/ansible/dockerfilehybrid.go
**Description of the change:** backport of #1348 to `v0.7.x`.
**Motivation for the change:** `v0.7.0` images are broken as they pull latest versions of ansible dependencies, which have a conflict.
> V0.7.x backport: pin ansible version (#1348)

- pkg/k8sutil/k8sutil.go
Backport  of https://github.com/operator-framework/operator-sdk/pull/1353 into the `v0.7.x` branch.
> backport: pkg/k8sutil/k8sutil.go: Set kind and APIVersion

- cmd/operator-sdk/up/local.go
Description of the change: The current sdk up local only build main.go. It would be better to build by cmd/manager/ pacakge.
> cmd/operator-sdk/up/local.go: sdk up local build by package than only the main file

- internal/pkg/scorecard/olm_tests.go
- Adds new valid URI formats in scorecardProxy log parser
- Improves suggestion text to include missing resources
- Some valid URI formats are not parsed correctly, resulting in tests that erroneously fail
- Give users better feedback about why their CRDsHaveResourcesTest failed.
> internal/pkg/scorecard/olm_tests.go: improve CRDsHaveResourcesTest

- CHANGELOG.md
- pkg/helm/controller/reconcile.go
Backport #1321 into `v0.7.x`
We backport bug fixes to previous release.
> Backport: pkg/helm/controller/reconcile.go: fix conditions logic (#1321)

- cmd/operator-sdk/scorecard/cmd.go
**Description of the change:** Increase default value for `--init-timeout` flag to 60.
**Motivation for the change:** Many (probably most) operators take longer than 10 seconds to initialize and update a new CR. 60 seconds is a more reasonable default timeout for the initialization timeout.
> cmd/.../scorecard: increase init-timeout default to 60s

- internal/pkg/scaffold/cr.go
- internal/pkg/scaffold/crd.go
**Description of the change:** use `Resource.GoImportGroup` in CRD and CR file names.
**Motivation for the change:** the `controller-tools` CRD generator uses API import path in CRD file names, causing a "cache miss" in the SDK's CRD generator wrapper. See #1368 for more details.
Closes #1368
> internal/pkg/scaffold: use `Resource.GoImportGroup` in CRD/CR file names

- doc/ansible/user-guide.md
The last step of the clean up process should be delete the custom resource *definition*, not the custom resource itself.
The custom resource is already deleted by line 440, the first step of the clean up process.
Improve the documentation.
> fix a typo in doc

- doc/ansible/dev/testing_guide.md
- doc/ansible/project_layout.md
- doc/design/long-term/testing-operators.md
- doc/design/milestone-0.0.2/action-api.md
- doc/design/milestone-0.0.2/query-api.md
- doc/dev/reporting_bugs.md
- doc/helm/user-guide.md
- doc/proposals/TEMPLATE.md
- doc/proposals/ansible-operator-testing.md
- doc/proposals/ansible-operator.md
- doc/proposals/tls-utilities.md
- doc/sdk-cli-reference.md
- doc/user-guide.md
- doc/user/client.md
- doc/user/metrics/README.md
- doc/user/metrics/service-monitor.md
- doc/user/olm-catalog/generating-a-csv.md
Remove the trailing white space from all of the docs. I purposely ignored the developer-guide because that was fixed with a different PR since I also edited it: https://github.com/operator-framework/operator-sdk/pull/1381
> remove trailing whitespaces

- internal/pkg/scaffold/crd_test.go
- internal/pkg/scaffold/types.go
- internal/pkg/scaffold/types_test.go
- test/test-framework/pkg/apis/cache/v1alpha1/memcached_types.go
- test/test-framework/pkg/apis/cache/v1alpha1/memcachedrs_types.go
**Description of the change:** add the `// +kubebuilder:subresource:status` annotation to all `Kind` types in generated API `*_types.go` files.
**Motivation for the change:** now that we [overwrite CRD's](https://github.com/operator-framework/operator-sdk/pull/1278/files) when regenerating them, `spec.subresources.status` is removed unless the above annotation exists for a `Kind` type.
> *types.go: set kubebuilder subresource status annotation in go source

- test/e2e/memcached_test.go
- Refactors memcached e2e `go.mod` replace logic for easier readability
- Adds support for non-PR branch builds in forks.
To make it easier to understand and maintain this section of code for future changes and support developers using travis on their forks.
> test/e2e/memcached_test.go: refactor and support forks for go.mod replace

- hack/tests/e2e-ansible.sh
- hack/tests/e2e-helm.sh
- internal/pkg/scaffold/ansible/go_mod.go
- internal/pkg/scaffold/go_mod.go
- internal/pkg/scaffold/go_mod_test.go
- internal/pkg/scaffold/helm/go_mod.go
- Removes hardcoded SDK reference in templated `go.mod` files, and replaces it to reference `master` which will be resolved by the go toolchain on first run of `go mod tidy`, `go mod vendor`, `go build`, etc.
- Updates ansible and helm e2e tests to use the same `go mod` replace method as the go e2e test
- Non-release SDK versions should use the SDK master branch in `go.mod`, which is [the same thing we do when using `dep`](https://github.com/operator-framework/operator-sdk/blob/d4a98bc5d2694f65ad6060db5c735163dd28714c/internal/pkg/scaffold/gopkgtoml.go#L98).
> internal/pkg/scaffold/*,hack/tests/: use osdk master when not on tagged commit

- internal/pkg/scaffold/ansible/go_mod.go
Pins a migrated ansible operator to use `github.com/coreos/prometheus-operator` at `v0.29.0`
Fixes the currently broken master branch. The latest  prometheus-operator release (`v0.30.0`) bumped its Kubernetes dependencies and code generation to `v1.14`, which breaks SDK's usage.
Build errors that are resolved by this PR:
```
vendor/github.com/coreos/prometheus-operator/pkg/apis/monitoring/v1/openapi_generated.go:13056:31: "github.com/operator-framework/operators/memcached-operator/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".Duration literal.OpenAPISchemaType undefined (type "github.com/operator-framework/operators/memcached-operator/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".Duration has no field or method OpenAPISchemaType) …
```
> internal/pkg/scaffold/ansible/go_mod.go: pin to prometheus-operator v0.29.0

- test/e2e/memcached_test.go
Use a unique temporary directory for the go e2e test, and cleanup temp files created during the test.
Running the go e2e tests repeatedly locally fails when a previous run was killed because the `$GOPATH/src/example-inc` still exists.
This change puts the test directory in a more obvious temporary location (`$GOPATH/src/tmp.XXXXXXX`) and it makes it easier to re-run tests without old temporary directories getting in the way.
Lastly, this PR adds a couple of extra cleanup functions for temporary global and namespaced manifest files created during the test.
> test/e2e/memcached_test.go: improve test isolation, cleanup temp files

- cmd/operator-sdk/build/cmd.go
stop overriding `CGO_ENABLED` on build
Fixes #1404
> cmd: allow CGO_ENABLED=1

- README.md
- doc/user-guide.md
Added a note to the user guide on running the docker client without sudo
Minimize surprise for users running "operator-sdk build" and seeing the following two errors:
[foo@localhost memcached-operator]$ operator-sdk build quay.io/example/memcached-operator:v0.0.1
INFO[0018] Building OCI image quay.io/example/memcached-operator:v0.0.1 
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Error: failed to output build image quay.io/example/memcached-operator:v0.0.1: (failed to exec []string{"docker", "build", "-f", "build/Dockerfile", "-t", "quay.io/example/memcached-operator:v0.0.1", "."}: exit status 1)
and
[foo@localhost memcached-operator]$ operator-sdk build …
> Added a note to the user guide on running the docker client without sudo

- internal/util/projutil/project_util.go
Fixes logic that extracts repo portion of path from $GOPATH when CWD is $GOPATH/src
Closes #1423
> internal/util/projutil/project_util.go: fix repo lookup when CWD is $GOPATH/src

- .travis.yml
Adds `$GOPATH/pkg/mod` to travis cache
This directory contains cached go modules, which take significant time to re-download during each build. Adding this to the travis cache should speed up builds.
> .travis.yaml: Add $GOPATH/pkg/mod to travis cache

- doc/user/install-operator-sdk.md
Currently users are being redirected when using curl to download the operator sdk.
By adding the `-L` flag to the curl command, it will be forced to follow them and get to the correct download
> docs: update curl to follow redirects

- Makefile
- cmd/operator-sdk/version/cmd.go
- release.sh
- version/version.go
- Adds `version.GitVersion` and `version.GitCommit`
- Updates `operator-sdk version` command to print them
- Updates Makefile to set them at compile-time.
Many users seem to be using non-release versions of `operator-sdk`, so lots of issues typically only report the version as something like `v0.7.0+git`.
To make it easier to troubleshoot issues, it would be nice to have the `operator-sdk version` command print the git version and commit strings.
> Makefile,version,cmd/operator-sdk/version: add git compile-time variables

- CHANGELOG.md
- cmd/operator-sdk/new/cmd.go
- doc/ansible/user-guide.md
- doc/helm/user-guide.md
- doc/operator-scope.md
- doc/sdk-cli-reference.md
- doc/user-guide.md
- internal/pkg/scaffold/ansible/deploy_operator.go
- internal/pkg/scaffold/helm/operator.go
- internal/pkg/scaffold/helm/role.go
- internal/pkg/scaffold/operator.go
- internal/pkg/scaffold/operator_test.go
Removal of `--cluster-scoped` flag and consolidation of docs on how to run cluster-scoped operators.
Also documents how to enable cluster-scoped CRDs.
The Helm operator will automatically scaffold a ClusterRole/ClusterRoleBinding and inform the user of this if it detects a cluster-scoped resource in the source chart when creating a new project.
There is a general consensus that the `--cluster-scoped` flag does not cover all the use cases of running operators watching different namespaces and expanding it would complicate the CLI and behavior. 
It's much easier to instruct users to make the small number of changes needed to enable cluster-scoped operators and cluster-scoped CRDs.
With this the default is now namespace-scoped …
> Remove cluster-scoped flag

- CHANGELOG.md
- cmd/operator-sdk/main.go
Removing `--version` flag.
We currently have two implementations of printing the version. This and `operator-sdk version`, which prints more information. Removing this is easier than continuing to maintain both.
> cmd/operator-sdk/main.go: remove --version flag

- CHANGELOG.md
- doc/user/install-operator-sdk.md
- internal/pkg/scaffold/ansible/go_mod.go
- internal/pkg/scaffold/ansible/gopkgtoml.go
- internal/pkg/scaffold/go_mod.go
- internal/pkg/scaffold/go_mod_test.go
- internal/pkg/scaffold/gopkgtoml.go
- internal/pkg/scaffold/gopkgtoml_test.go
- internal/pkg/scaffold/helm/go_mod.go
- internal/pkg/scaffold/helm/gopkgtoml.go
- version/version.go
**Description of the change:** Update to `v0.8.0`
**Motivation for the change:** Release `v0.8.0`
> *: release v0.8.0

- doc/user/install-operator-sdk.md
If one hasn't been configured yet, the user will need to specify a keyserver when running gpg(1).
Thanks for the quick review on the previous PR, I didn't find an existing one for this :-)
> Specify --keyserver to gpg(1) call if needed

- internal/pkg/scaffold/helm/role.go
Always add custom roles when generating Helm role rules, regardless of whether the operator is cluster-scoped or not.
This is a regression that should be fixed. We didn't catch it in reviews and CI somehow passed for #1434.
> internal/pkg/scaffold/helm/role.go: add custom rules for namespaced scope

- CHANGELOG.md
- hack/tests/e2e-helm.sh
- internal/pkg/scaffold/helm/role.go
- Fail e2e test if RBAC generation fails
- Fix RBAC version parsing to handle OCP versions
- Return role scaffold immediately upon rule generation failure
This is a follow-on to #1456, which fixed a regression in the Helm RBAC rule generation.
In CI, the RBAC rule generation is currently failing and falling back to the default rule set when using the OCP cluster in Travis. In OCP, the kubernetes version number is reported as `1.11+` (in minikube and upstream kubernetes, it is reported as `1.11`). Helm's libraries to generate manifests fail to parse the kubernetes version when it contains the plus sign, so Helm e2e testing has fallen back to the default non-generated rules ever since RBAC generation was added.
The reason that …
> Helm: RBAC generation fixes 

- internal/pkg/scaffold/helm/role.go
Backports #1456 to `v0.8.x` branch.
To fix this bug in the latest release.
> (backport to v0.8.x) internal/pkg/scaffold/helm/role.go: add custom rules for namespaced scope

- CHANGELOG.md
- hack/tests/e2e-helm.sh
- internal/pkg/scaffold/helm/role.go
Backports #1461 to `v0.8.x` branch
To fix this bug in the latest release
> (backport to v0.8.x)  Helm: RBAC generation fixes

- internal/pkg/scaffold/internal/testutil/test_util.go
- internal/util/k8sutil/crd.go
- internal/util/k8sutil/object.go
**Description of the change:** add missing license headers to SDK package files
**Motivation for the change:** must have them
> internal/{pkg,util}: add missing license headers

- CHANGELOG.md
- doc/test-framework/writing-e2e-tests.md
- doc/user/client.md
- example/memcached-operator/memcached_controller.go.tmpl
- internal/pkg/scorecard/helpers.go
- pkg/leader/leader.go
- pkg/metrics/metrics.go
- pkg/metrics/service-monitor.go
- pkg/test/framework.go
- test/e2e/incluster-test-code/memcached_test.go.tmpl
- test/test-framework/pkg/controller/memcachedrs/memcachedrs_controller.go
- test/test-framework/test/e2e/memcached_test.go
* Remove TypeMeta declaration from the implementation of the objects
Note that the TypeMeta struct and its values are automatically filled when an object is initialized in this way is unnecessary to add this values and indeed shows a not good practice at all since the dev can add wrong values which will cause issues as for example not allow the client GET the object. 
Following an example which could cause error just to example this scenario. 
```go
...
route := &routev1.Route{
TypeMeta: v1.TypeMeta{  // TODO (user): Remove the TypeMeta declared
APIVersion: "v1",   // the correct value should be `"route.openshift.io/v1"`
Kind:       "Route",
},
ObjectMeta: v1.ObjectMeta{
Name:      name,
Namespace: namespace,
Labels:    ls,
},
}
...
```
Following an example …
> Remove TypeMeta declaration from the implementation of the objects

- CHANGELOG.md
- README.md
- cmd/operator-sdk/build/cmd.go
- doc/sdk-cli-reference.md
Adds support for running `podman` during `operator-sdk build`
See #1207
> cmd/operator-sdk/build/cmd.go: support podman

- internal/pkg/scaffold/types.go
- internal/pkg/scaffold/types_test.go
validation documentation deep link to book.kubebuilder.io in generated CR types was invalid.
> internal/pkg/scaffold/types.go: remove broken kubebuilder book link

- cmd/operator-sdk/build/cmd.go
- cmd/operator-sdk/new/cmd.go
- cmd/operator-sdk/up/local.go
- internal/pkg/scaffold/test_setup.go
- internal/util/projutil/project_util.go
- test/e2e/memcached_test.go
**Description of the change:** ensure all import/package paths use `/` and file/dir paths use `filepath.Separator`.
**Motivation for the change:** Even though we do not officially support windows, we should still use proper path separators in all cases.
> *: use "/" for Go package paths and filepath.Separator for on-disk paths

- CHANGELOG.md
- README.md
- cmd/operator-sdk/up/local.go
- doc/sdk-cli-reference.md
Add a debug flag for operator-sdk up local, which wraps the built binary into the dlv command to attach a remote debugger
To simplify the process to attach a debugger when developing an operator locally
> Add run local in debug

- cmd/operator-sdk/test/local.go
- doc/sdk-cli-reference.md
- pkg/test/main_entry.go
**operator-sdk test** : add `--local-operator-flags` to `operator-sdk test local --up-local` command
**why this change was made**: without this flag, we cannot write tests to test operator code that uses command line flags. A flag like this is already there in `operator-sdk up local` command (`--operator-flags`). 
Fixes https://github.com/operator-framework/operator-sdk/issues/1476
This patch adds `--local-operator-flags` to
`operator-sdk test local --up-local` command
It is provides the functionality provided by
`--operator-flags` flag in `operator-sdk up local --operator-flags` command.
At present there is no way to pass command line flags to an operator
while testing using `operator-sdk test local --up-local` command.
There …
> Add --local-operator-flags for testing with --up-local

- README.md
- doc/user/install-operator-sdk.md
The old steps are overcoming the benefits provided by "go get <repo>" command, which automatically clones the repo in "$GOPATH/src/" . Hence, with this commit, I trying to leverage-up those benefits by introducing in "go get <repo>" in README.md .
> Added changes in README.md

- internal/pkg/scaffold/helm/chart_test.go
- Adds unit tests for scaffolding charts from various sources for helm operators.
Minimize future regressions.
> pkg/scaffold/helm/chart_test.go: add chart scaffolding tests

- CHANGELOG.md
- cmd/operator-sdk/build/cmd.go
- internal/util/projutil/exec.go
**Description of the change:** expand environment variables in `operator-sdk build`'s `go build` process, and always append os.Environ() to `go` commands.
**Motivation for the change:** `exec.Cmd`'s are not run in a shell, so env variables are not expanded.
Closes #1530
> cmd/operator-sdk/build: expand env in go build

- CHANGELOG.md
- cmd/operator-sdk/internal/genutil/genutil.go
**Description of the change:** remove requirement that the API dir structure `pkg/apis/<group>/<version>` have `<version>` match something like `v1alpha1`, and instead check if `<version>` is a dir (or dir hierarchy) that contains files.
**Motivation for the change:** having a API dir shared by multiple versions, ex `pkg/apis/operators/shared`, is valid and should be considered when running a code generator.
> cmd/operator-sdk/internal/genutil: relax version dir check in `parseGroupVersions()`

- pkg/helm/controller/reconcile.go
- pkg/helm/release/manager.go
Improves handling of errors that can occur when rolling back failed releases.
See #1505
> pkg/helm/release/manager.go: improve error handling with failed releases

- hack/lib/test_lib.sh
- internal/pkg/scaffold/olm-catalog/csv_updaters.go
- internal/util/projutil/project_util.go
**Description of the change:** `listPkgDirs` gets `internal` package, and all other packages, by dir using a `go list` pipeline. `listFiles` is now GOPATH-agnostic because `go list` considers modules.
**Motivation for the change:** we should be getting `internal` package dirs because they need to be tested by e2e. See #1475 for more details on why the GOPATH requirement was removed from `listFiles`.
> hack/lib/test_lib.sh: `listFiles` is GOPATH-agnostic

- hack/tests/e2e-ansible-molecule.sh
- hack/tests/e2e-ansible.sh
- pkg/ansible/proxy/cache_response.go
- pkg/ansible/proxy/inject_owner.go
- pkg/ansible/proxy/proxy.go
- pkg/ansible/runner/eventapi/eventapi.go
- test/ansible-memcached/asserts.yml
- test/ansible-memcached/tasks.yml
* Defining virtual resources as any resource that does not have the
ability to "get", "list", and "watch" as all are needed for the cache.
* creating a new struct to handle the caching of the cluster APIResources
Using a virtual resource in the cache will cause issues because the informer is unable to be started.
> pkg/ansible: pass along requests for virtual resources to cluster

- internal/annotations/prefix.go
- internal/annotations/prefix_test.go
**Description of the change:** implementation of code annotation parser helpers described in #1324 
**Motivation for the change:** #1324 added a spec for SDK code annotations. These constants and helper functions are primitives for reading and writing general SDK annotations. They are to be used by parsers for specific implementations of annotations.
> internal/annotations/prefix.go: define annotation separators, join and split functions

- internal/pkg/scaffold/boilerplate_go_txt_test.go
- internal/pkg/scaffold/scaffold.go
Go permits multiline, block-style comments. It's common for boilerplates to utilize these for licences (e.g. Apache-2.0's standard boilerplate).
This PR removes the line-by-line stripping of whitespace, and adds a test for it.
Allow existing projects with compliant, multiline boilerplates to use them.
> Fix multiline boilerplates

- CHANGELOG.md
- Gopkg.lock
- Gopkg.toml
- internal/pkg/scaffold/cmd.go
- internal/pkg/scaffold/cmd_test.go
- internal/pkg/scaffold/go_mod.go
- internal/pkg/scaffold/go_mod_test.go
- internal/pkg/scaffold/gopkgtoml.go
- internal/pkg/scaffold/gopkgtoml_test.go
- pkg/k8sutil/k8sutil.go
- pkg/kube-metrics/collector.go
- pkg/kube-metrics/metrics.go
- pkg/kube-metrics/server.go
- pkg/kube-metrics/uclient.go
- test/e2e/memcached_test.go
- vendor/k8s.io/kube-state-metrics/LICENSE
- vendor/k8s.io/kube-state-metrics/pkg/collector/collector.go
- vendor/k8s.io/kube-state-metrics/pkg/metric/family.go
- vendor/k8s.io/kube-state-metrics/pkg/metric/generator.go
- vendor/k8s.io/kube-state-metrics/pkg/metric/metric.go
- vendor/k8s.io/kube-state-metrics/pkg/metrics_store/metrics_store.go
Operator specific metrics are generated based on the api/kind given
deployed in the given namespace(s).
See https://github.com/operator-framework/operator-sdk/blob/master/doc/proposals/metering-operator-metrics.md for the full background on this work.
Things to be done:
Closes https://github.com/operator-framework/operator-sdk/issues/616
> pkg/kube-metrics: Add initial operator specific metrics

- cmd/operator-sdk/new/cmd.go
- doc/sdk-cli-reference.md
Move project validation to only check new go projects 
Ansible and Helm projects don't use dependency managers, and don't have go code, so there's nothing to validate.
> cmd/operator-sdk/new/cmd.go: only validate new go projects

- README.md
- doc/faq.md
It would be helpful to have a variety of commonly asked operator-sdk questions, starting with `The resourceVersion for the provided watch is too old`. This question appears in a variety of blogs and Github issues but is not posted anywhere in our docs - many people think this is a bug.
> faq + explanation fo resourceVersion too old

- doc/user/unit-testing.md
- Fix indentation to use 4 spaces which shows the standard
- Add var with the link used in the doc on top of it
- Add explanation and examples over how to use third-party resources
- Add troubleshooting section with tips and common issues
- Add a table of context
- https://github.com/operator-framework/operator-sdk/issues/1427
- https://github.com/operator-framework/operator-sdk/issues/1421
NOTE: The questions and issues faced when we were trying to create unit testing by following the docs.
To review see: https://github.com/operator-framework/operator-sdk/blob/cf27131e8cac7d6ec2302b4f0d20de74a939ff51/doc/user/unit-testing.md
> doc(unit-testing): Improvements, add example/explanation over how to use third-party resources and common issues

- CHANGELOG.md
- doc/ansible/dev/developer_guide.md
- pkg/ansible/runner/runner.go
Necessary to allow accessing the CR unmodified `spec` without also
accessing a variable containing the CR `status`. If the CR status is
managed by ansible-operator directly, then it's possible the status can
contain invalid jinja expressions which will be evaluated if you
access a variable containing the `status`. See #1471 for more details.
Closes #1471
> ansible-operator: Add extra var containing watched resource spec

- pkg/metrics/service-monitor.go
Whenever there are multiple ports in the Service object we take all of
them to map to the Endpoints of the ServiceMonitor object. 
This way we can have one ServiceMonitor per Service with multiple ports exposed.
I cam across this while working and testing https://github.com/operator-framework/operator-sdk/pull/1560 but they don't depend on each other, so can be merged separately.
> pkg/metrics/service-monitor.go: Populate all ports

- .travis.yml
- hack/ci/setup-build-dependencies.sh
Adds a setup script that can be used in OpenShift CI
We currently [hard-code the `dep` setup commands](https://github.com/openshift/release/blob/master/ci-operator/config/operator-framework/operator-sdk/operator-framework-operator-sdk-master.yaml#L8) in the openshift/release repo.
Once this script is merged into master, we can update the OpenShift CI configuration to use it, which then gives us the flexibility to change the test setup from the SDK repo, rather than having to make coordinating changes in openshift/release.
This will be helpful in migrating the SDK from using `dep` to go modules (see #1566)
/cc @AlexNPavel
> hack/ci/setup-build-dependencies.sh: add setup script in SDK repo

- CHANGELOG.md
- internal/pkg/scorecard/scorecard.go
**Description of the change:** use `viper.GetStringSlice()` for getting and use `[]string` when setting `CRManifestOpt` with `--olm-deployed`.
**Motivation for the change:** `CRManifestOpt` is not accessed correctly when `--olm-deployed` is set.
> internal/pkg/scorecard: access `CRManifestOpt` correctly with `--olm-deployed`

- doc/user/metrics/README.md
These are user specific docs so they do not go in depth of what happens
in the kube-metrics package.
> doc/user/metrics/README.md: Add Custom Resource docs

- internal/pkg/scaffold/ansible/molecule_test_cluster_playbook.go
- internal/pkg/scaffold/ansible/molecule_test_local_playbook.go
Increase ansible molecule test waits from 40s to 60s
The 40s waits are sometimes to short, causing the ansible CI test runs to be flaky.
> internal/pkg/scaffold/ansible: bump molecule retries to wait 60s

- doc/user/metrics/README.md
If we were to write the metrics here, we would need to update on every change in controller-runtime, linking to their docs makes more sense.
Closes https://github.com/operator-framework/operator-sdk/issues/1168
> doc/user/metrics/README.md: Link to details about metrics

- doc/ansible/user-guide.md
- doc/dev/developer_guide.md
- doc/helm/user-guide.md
PRs have been having failing marker tests for no reason. Network is working inside the pods, I could resolve URLs that are failing in the tests. Changing as per the suggestion in https://github.com/operator-framework/operator-sdk/blob/a87a07686fba330b18611daf67f1b972f14fe3be/doc/dev/testing/travis-build.md#markdown
> doc/*: Change underscore links for marker tool to work

- Gopkg.lock
- test/e2e/memcached_test.go
- test/test-framework/test/e2e/memcached_test.go
Adds retry logic when conflicts occur in the memcached e2e tests for updating the CR.
More fixes for flaky tests:
https://travis-ci.org/operator-framework/operator-sdk/jobs/548776852#L1424
> test/test-framework,test/e2e: retry conflict updates

- doc/test-framework/scorecard.md
**Description of the change:** add docs detailing how to use `operator-sdk scorecard` with only a CSV.
**Motivation for the change:** no docs exist for this functionality.
> doc/test-framework/scorecard.md: document using the scorecard with a CSV

- doc/operator-scope.md
Adds an example section to outline the changes in the operator manifests for cluster-scoped operators. 
Closes #1490
> doc/operator-scope: add example manifests

- doc/proposals/improved-scorecard-config.md
**Description of the change:** Make proposal for removing most command line arguments for the `scorecard` subcommand and replacing them with a new, comprehensive config file format
**Motivation for the change:** Reduce the excessive amount of command line flags in the scorecard and replace it with a cleaner config file format that also allows for more extensive configuration of external plugins.
> doc/proposals/improved-scorecard-config.md: make proposal

- README.md
it was not clear that to avoid issues in the quick start, that
one should use the specific version of the operator-sdk that matches
the version of the quick start they are following.
Adds line to README about using the same version of operator-sdk as the version of the quick start one is following.
Failure to use the exact version of the sdk (in this case, viewing the master branch readme, and installing operator-sdk 0.8.1) can lead to build errors and frustration.
> documentation: add note operator-sdk version

- CHANGELOG.md
- doc/user/metrics/README.md
- hack/tests/e2e-helm.sh
- internal/pkg/scaffold/cmd.go
- internal/pkg/scaffold/cmd_test.go
- pkg/ansible/run.go
- pkg/helm/run.go
- pkg/metrics/metrics.go
- test/e2e/memcached_test.go
With the recent addition of Custom Resource metrics we need to expose the port in the metrics Service. This also helps users who want to expose their own metrics ports in a Service as they can just pass in another port.
Note: We also changed the name of the Service that is being created by appending `-metrics` to the operator name, this makes it self descriptive as we did have questions what is this service for.
**TODO:**
> pkg/metrics: Allow multi port metrics Service creation

- doc/migration/v0.1.0-migration-guide.md
- doc/proposals/ansible-operator-status.md
- doc/proposals/metering-operator-metrics.md
The links have moved to subdirectories, this PR adjusts to point to the
current commit so we don't have to adjust this in the future.
Currently CI marker test is failing, due to the following errors, this PR fixes them.
```
./hack/ci/marker --root=doc
Found broken url       (Kubernetes API conventions -> https://github.com/kubernetes/community/blob/master/contributors/devel/api-conventions.md#typical-status-properties) at doc/proposals/ansible-operator-status.md:23 : 404 Not Found
Found broken url       (guide -> https://github.com/kubernetes/community/blob/master/contributors/devel/instrumentation.md) at doc/proposals/metering-operator-metrics.md:9 : 404 Not Found
Found broken url       (controller conventions -> …
```
> doc/*: Fix links

- test/e2e/memcached_test.go
- test/test-framework/test/e2e/memcached_test.go
Fixes a flake that happens sometimes during the Go e2e test, related to CR updates failing with conflic errors during the scale test.
The original PR that attempted to fix this is here: #1585 
The original PR to fix this issue didn't actually fix the issue because it didn't re-fetch the latest version of the resource.
> test/test-framework,test/e2e: get latest resource during RetryOnConflict

- doc/ansible/user-guide.md
- doc/helm/user-guide.md
- doc/user-guide.md
Removes references to the recently removed `--cluster-scoped` flag in the Go, Ansible, and Helm user guides
Keep docs up-to-date
> doc: remove obsolete references to --cluster-scoped flag

- doc/faq.md
This question has been asked a few times, and those users with existing
operators when trying to use the metrics Service creation, do not update
the role.yaml file.
> doc/faq.md: Add metrics Service creation error question

- internal/pkg/scaffold/crd.go
This sets domain as empty string when we can't extract it from FullGroup.
In turn this defaults to extracting the domain from project root file
in controller-tools.
Closes https://github.com/operator-framework/operator-sdk/issues/1579
cc @estroz 
I was not sure if we should error out early if we cannot extract the domain, but I noticed in controller-tools there is an option to leave the domain empty.  https://github.com/operator-framework/operator-sdk/blob/6aac3b6efddd6824ea8578b5187eb360c42b1e63//vendor/sigs.k8s.io/controller-tools/pkg/crd/generator/generator.go#L85-L89
I find the error msg there a bit confusing if domain is not empty and the project cannot be found from the path, so not sure if we should warn the user or not?
> internal/../crd.go: Add check to prevent index panic

- cmd/operator-sdk/build/cmd.go
#1595 
Make `operator-sdk build` support other architectures.
I do not change the original behavior, since I have no idea the reason `GOARCH=amd64` there.
We try to use `operator-sdk build` for other architectures.
> support multi-arch for "operator-sdk build"

- hack/tests/e2e-helm.sh
- pkg/helm/run.go
This PR enables custom resource metrics in helm. As part of this issue https://github.com/operator-framework/operator-sdk/issues/1554
For background see PR https://github.com/operator-framework/operator-sdk/pull/1277
cc @joelanford
> pkg/helm/run.go: Enable custom resource metrics

- doc/dev/testing/running-the-tests.md
**Description of the change:** add section to the SDK dev testing doc about Go e2e flags.
**Motivation for the change:** see https://github.com/operator-framework/operator-sdk/pull/1450#issuecomment-501052719
> doc/dev/testing/running-the-tests.md: add Go e2e test flag section

- cmd/operator-sdk/olmcatalog/gen-csv.go
- internal/pkg/scaffold/olm-catalog/csv.go
- internal/pkg/scaffold/olm-catalog/csv_test.go
This patch adds a flag `--operator-name` to specify the operator name
while generating CSV using `operator-sdk gen-csv` command
The default value (when flag is absent) is base directory name as before
At present operator-sdk  assumes project-directory-name (ProjectName) is the operator name.
The operator-name and the project-directory-name can be different.
(because of change in source control, project home, organizational policies etc)
Without an --operator-name flag we will have to rename, copy-paste generated CSVs
Signed-off-by: Nikhil Thomas <nikthoma@redhat.com>
> Add --operator-name flag to olm-catalog gen-csv

- CHANGELOG.md
- cmd/operator-sdk/new/cmd.go
- doc/sdk-cli-reference.md
Changed the flag `--skip-git-init` to `--git-init` to make `git init` opt-in instead of opt-out.
Also `operator-sdk new` will no longer create the initial commit.
Creating the initial commit is unexpected behavior and can fail certain scenarios as described in #1198 .
~~Having `git init` as opt-out via `--skip-git-init` instead of opt-in is debatable, and so is unchanged at the moment.~~
~~I am leaning towards making `git init` opt-in but can address that in a follow up PR after we discuss it on the issue.~~
Changed `git init` to opt-in per the consensus from the community and maintainers.
Closes: #1198
> cmd/operator-sdk/new: make git init opt-in with --git-init flag

- .travis.yml
**Description of the change:** Don't run travis on branches `release-4.2` and `release-4.3`.
**Motivation for the change:** These are currently just mirroring master and slow down CI as it causes us to hit the job limit quickly. Currently just limiting the branches directly without a regex, as we might need to re-enable travis testing if we haven't fully migrated to openshift-ci by the 4.2 final freeze.
> .travis.yml: don't run travis on release branches

- doc/test-framework/writing-e2e-tests.md
The link https://github.com/operator-framework/operator-sdk/blob/master/pkg/test/framework.go#L45 may be inaccurate because of the file changes. 
Thus I think it is better to remove the line number in the link just like https://github.com/operator-framework/operator-sdk/pull/1617/files#diff-59ad6a5ff59239f33497d6206b778c43L329 does.
Please take a look, thanks for your time :smile:
Signed-off-by: Ce Gao <gaoce@caicloud.io>
<!--
Before making a PR, please read our contributing guidelines https://github.com/operator-framework/operator-sdk/blob/master/CONTRIBUTING.MD
Note: Make sure your branch is rebase
> fix: Fix a link in README

- CHANGELOG.md
- doc/dev/release.md
- Adds 0.7.1 and 0.8.1 sections on CHANGELOG
- Adds line to developer release document to clarify that post-patch release PRs should be created and merged into both `master` and the release branch.
Bring CHANGELOG up-to-date, and clarify release doc to improve our patch release process.
> CHANGELOG.md,doc/dev/release.md: fix CHANGELOG, clarify release doc

- Makefile
- doc/dev/testing/running-the-tests.md
- doc/dev/testing/travis-build.md
**Description of the change:** Remove `test/ansible` target from the `ci-ansible` make target used by travis
**Motivation for the change:** The main ansible test is currently being tested in Openshift-CI
> Makefile: remove test/ansible from ci-ansible

- CHANGELOG.md
- internal/pkg/scaffold/crd.go
**Description of the change:** remove CRD cache so manifests are generated with the correct [domain](https://github.com/operator-framework/operator-sdk/blob/db3a453bde93dc4bba13e5ace6dde08758b6dca0/internal/pkg/scaffold/crd.go#L122).
**Motivation for the change:** Fixes #1608. The cache didn't provide a big performance benefit anyway unless quite a few API's require parsing. This is also not an issue in controller-tools v0.2.0 CRD generator.
Closes #1608
> internal/pkg/scaffold/crd.go: remove CRD cache

- internal/pkg/scaffold/cmd.go
- internal/pkg/scaffold/cmd_test.go
- pkg/helm/run.go
Without this change, I get an error about "odd number of arguments
passed as key-value pairs for logging" in the case where this code is
invoked (I hit it when running the operator with `operator-sdk up local`).
I only hit it in the cmd.go for my Go operator, but I presume the same
thing is needed for the cmd_test.go and helm/run.go.
I'm also not sure if this is absolutely the best solution (I'm not
that experienced with Go), but it fixed the issue for me.
I think the previous behaviour was unintentional.
> Fix log message so it doesn't cause an error

- doc/test-framework/writing-e2e-tests.md
**Description of the change:** Update old manifest structure used in part of the writing tests doc (was using the pre-v0.1.0 manifest structure)
**Motivation for the change:** Keep docs up to date
> doc/test-framework: use correct manifest structure in docs

- hack/check_error_log_msg_format.sh
**Description of the change:** correctly check functions with the form `errors.Function(...)`.
**Motivation for the change:** functions like `github.com/pkg/errors.Errorf()` should not be assessed as log messages.
> hack/check_error_log_msg_format.sh: correctly check "errors." functions

- doc/operator-scope.md
- doc/user-guide.md
Document the tag `// +genclient:nonNamespaced` for generating CRDs as cluster-scoped in the operator scope document.
Also add a line clarifying the default usage of the `WATCH_NAMESPACE` env in the user guide. 
Closes: #1650
> doc/operator-scope: add scope tag for CRD generation

- internal/pkg/scaffold/crd.go
- internal/pkg/scaffold/olm-catalog/csv.go
- internal/pkg/scaffold/olm-catalog/csv_test.go
- internal/pkg/scaffold/olm-catalog/csv_updaters.go
- internal/pkg/scaffold/olm-catalog/package_manifest.go
- internal/pkg/scaffold/olm-catalog/package_manifest_test.go
- internal/util/k8sutil/k8sutil.go
- internal/util/k8sutil/k8sutil_test.go
- internal/util/k8sutil/object.go
- internal/util/operator-registry/package_manifest.go
- internal/util/operator-registry/package_manifest_test.go
**Description of the change:** export `getDisplayName()`, `getKindFromYAML()`, and `validatePackageManifest()` and move to `internal/util/k8sutil`.
**Motivation for the change:** these functions are useful elsewhere when dealing with k8s and OLM resources. See #1552 for an example.
> internal/pkg/scaffold: move some utility functions to internal/util/k8sutil

- hack/tests/scaffolding/scaffold-memcached.go
**Description of the change:** remove code that creates `go.mod` in a local SDK repo if one does not exist.
**Motivation for the change:** no longer needed now that #1566 is merged (I believe this was removed then accidentally added back on a rebase).
> hack/tests/scaffolding/scaffold-memcached.go: remove go.mod in SDK repo hack

- pkg/ansible/run.go
- pkg/ansible/watches/watches_test.go
This makes it possible for ansible based operators to interact with CRDs
that didn't exist when the operator started.
fixes #1330
>  ansible: Use operator-sdk's dynamic restmapper

- hack/lib/test_lib.sh
- hack/tests/scaffolding/scaffold-memcached.go
**Description of the change:** remove existing replace lines in go.mod for the SDK repo before appending one in e2e tests
**Motivation for the change:** e2e code will not pass release PR's otherwise.
> hack/: remove existing replace lines in go.mod for the SDK repo first

- CHANGELOG.md
- doc/user/install-operator-sdk.md
- internal/pkg/scaffold/ansible/go_mod.go
- internal/pkg/scaffold/ansible/gopkgtoml.go
- internal/pkg/scaffold/go_mod.go
- internal/pkg/scaffold/go_mod_test.go
- internal/pkg/scaffold/gopkgtoml.go
- internal/pkg/scaffold/gopkgtoml_test.go
- internal/pkg/scaffold/helm/go_mod.go
- internal/pkg/scaffold/helm/gopkgtoml.go
- version/version.go
**Description of the change:** change versions to `v0.9.0`.
**Motivation for the change:** release `v0.9.0`.
> *: release v0.9.0

- CHANGELOG.md
- README.md
- doc/user-guide.md
**Description of the change:** document new mercurial compile-time dependency for new operators.
**Motivation for the change:** new operators require mercurial be installed as of v0.9.0.
Closes #1681
> *: document mercurial dependency for v0.9+ operators

- CHANGELOG.md
- README.md
- doc/user-guide.md
**Description of the change:** cherry pick from #1683.
**Motivation for the change:** required dependency for all operators using SDK v0.9+.
> v0.9.x: document mercurial dependency for operators (#1683)

- doc/user/metrics/README.md
- doc/user/metrics/service-monitor.md
- internal/pkg/scaffold/cmd.go
- internal/pkg/scaffold/cmd_test.go
- internal/pkg/scaffold/role.go
- internal/pkg/scaffold/role_test.go
- pkg/metrics/service-monitor.go
- Adds creation of ServiceMonitor objects in every users generated main.go file. We already have a check in place that logs and does not create the objects if they are not registered - so when prometheus-operator is not running in the cluster.
- Adds owner reference to the ServiceMonitor and sets Service as the owner, so when the Service is deleted it will clean up any ServiceMonitor objects as well.
Closes https://github.com/operator-framework/operator-sdk/issues/1576
**Question:** Should we add an e2e test to check if the ServiceMonitor was created? For that we need to install prometheus-operator in the cluster which might take a while.
> Enable ServiceMonitor creation by default

- doc/user-guide.md
The generated YAML CRD created when running `operator-sdk add api ...`
includes an OpenAPI v3.0 validation section. E.g.
```YAML
validation:
openAPIV3Schema:
properties:
apiVersion:
description: 'APIVersion defines the versioned schema of this representation
of an object. Servers should convert recognized schemas to the latest
internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
type: string
kind:
description: 'Kind is a string value representing the REST resource this
object represents. Servers may infer this from the endpoint the client
submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#type …
```
> doc: add OpenAPI validation info to user guide

- ci/tests/e2e-go.sh
- test/e2e/_incluster-test-code/memcached_test.go
**Description of the change:** Print out operator logs if local operator fails
**Motivation for the change:** It is difficult to identify what caused an error if we don't have proper logs
> ci/tests,test/e2e: log up local errors better

- internal/pkg/scaffold/test_setup.go
**Description of the change:** hardcode repo path in setupTestFrameworkConfig to avoid panic outside of `$GOPATH/src`
**Motivation for the change:** fix panic caused by incorrect repo path.
> internal/pkg/scaffold: hardcode repo path in setupTestFrameworkConfig

- ci/dockerfiles/ansible-e2e-hybrid.Dockerfile
- ci/dockerfiles/ansible.Dockerfile
- ci/tests/e2e-ansible.sh
- internal/pkg/scaffold/ansible/dockerfilehybrid.go
- internal/pkg/scaffold/ansible/molecule_default_molecule.go
- internal/pkg/scaffold/ansible/molecule_default_prepare.go
- internal/pkg/scaffold/ansible/molecule_test_local_molecule.go
- test/ansible-inventory/molecule/test-local/molecule.yml
- test/ansible-inventory/molecule/test-local/prepare.yml
- test/ansible-memcached/asserts.yml
- test/ansible-memcached/molecule.yml
Replaces `ansible-runner` base image with `ubi7/ubi`.
Also installs and uses `tini` to reap zombie Ansible processes.
Currently python dependencies are installed via pip, but should move to using RPMs as soon as we determine what the proper practice for that on ubi is.
Partners need a ubi-based image for certification, 
**Note**
Both this and https://github.com/openshift/release/pull/4302 will need to be merged for tests to pass
closes #1551
> Move to ubi-based base image for Ansible Operator

- CHANGELOG.md
- cmd/operator-sdk/build/cmd.go
- internal/util/projutil/exec.go
**Description of the change:** see #1535
**Motivation for the change:** cherry-pick for v0.8.2
> cmd/operator-sdk/build: expand env in go build (#1535)

- CHANGELOG.md
- internal/pkg/scorecard/scorecard.go
**Description of the change:** see #1565 
**Motivation for the change:** cherry-pick for v0.8.2
> internal/pkg/scorecard: access `CRManifestOpt` correctly with `--olm-deployed` (#1565)

- hack/lib/test_lib.sh
- hack/tests/e2e-ansible.sh
- hack/tests/e2e-helm.sh
- test/e2e/memcached_test.go
**Description of the change:** see #1574
**Motivation for the change:** necessary to pass CI on release PR's.
> e2e: better method of adding SDK repo replace directive to operator's go.mod (#1574)

- ci/dockerfiles/ansible-e2e-hybrid.Dockerfile
- ci/dockerfiles/ansible.Dockerfile
Ansible is now explicitly installed in the CI images, which should allow https://github.com/openshift/release/pull/4302 to pass
The CI images when based on UBI don't actually have ansible installed, just ansible-runner.
> Ensure Ansible is installed in CI images

- doc/user/install-operator-sdk.md
Adding "&& sudo mkdir -p /usr/local/bin/operator-sdk"" to the installation guide
Fixes an error when the path doesn't exist already.
> adding /usr/local/bin/operator-sdk path

- doc/user/install-operator-sdk.md
Adds some links to the top of the install guide.
I didn't realize there was a homebrew option until really late.
> docs: add links in install doc

- doc/user/install-operator-sdk.md
operator-sdk installation documentation update.
Moved `brew install operator-sdk` to the top since it's the simplest installation method.
Visitors only see `brew install operator-sdk` after downloading from Github method.
> Display simple installation first

- README.md
In 757f7a0b9 the `--repo` flag was added to the `operator-sdk new` command, which is required when running with `--dep-manager modules`. This breaks the Go quickstart since `--repo` isn't mentioned there.
Closes https://github.com/operator-framework/operator-sdk/issues/1688.
Include the `--repo` flag in the Go quickstart.
Docs should be accurate.
> README.md: Add missing --repo flag in quickstart

- doc/operator-scope.md
Documents limitation of Helm operator, which only supports namespace-scoped CRDs
Closes #1666
> doc/operator-scope.md: Helm operator supports only namespace-scoped CRDs

- internal/olm/client.go
- internal/olm/client/client.go
- internal/olm/client/status.go
**Description of the change:** move functions that use `sigs.k8s.io/controller-runtime/pkg/client.Client` directly to `internal/olm/client`.
**Motivation for the change:** future packages that use OLM API's should be able to share a client.
**Note:** this PR mostly refactors code as-is except for `Do{Create,Delete}`.
> internal/olm/client{,.go}: refactor Client to its own package

- OWNERS
As I am no longer working on operator-sdk project I am not in a position
to review or approve any changes.
I kept getting assigned to new PRs, this prevents that from happening. :)
> OWNERS: Remove lilic

- doc/user-guide.md
**Description of the change:** add `--repo` to user guide example.
**Motivation for the change:** see #1713
> doc/user-guide.md: operator-sdk new requires --repo if outside of $GOPATH/src

- doc/ansible/dev/apb_migration_guide.md
Adds a migration guide so that users can take their existing APBs and convert them to operators.
> Add APB migration guide

- cmd/operator-sdk/main.go
- cmd/operator-sdk/new/cmd.go
Just improve msg by adding a link with a further explanation in order to help the users. 
https://github.com/operator-framework/operator-sdk/issues/1732 - Just improve the msg in order to by adding the link for the docs in order to help the users with.
> feat(msg error over ) : Improve error msg GO111MODULE=on

- CHANGELOG.md
- pkg/ready/ready.go
- pkg/ready/ready_test.go
Closes #1760
Make the ready package idempotent.
As a user, I would expect the cases where I set the operator as ready or unset the operator's readiness to be a no-op in the cases that the operator is already in said state.
> pkg/ready: Make set/unset idempotent

- CHANGELOG.md
- internal/pkg/scorecard/plugins/plugin_runner.go
**Description of the change:** check if CRs are present when parsing `metadata.annotations['alm-examples']`.
**Motivation for the change:** see #1780 
Closes #1780
> internal/pkg/scorecard/plugins: return an error if no CRs exist in alm-examples w/o cr-manifest set

- CHANGELOG.md
- internal/pkg/scaffold/ansible/go_mod.go
- internal/pkg/scaffold/ansible/gopkgtoml.go
- internal/pkg/scaffold/go_mod.go
- internal/pkg/scaffold/gopkgtoml.go
- internal/pkg/scaffold/helm/go_mod.go
- internal/pkg/scaffold/helm/gopkgtoml.go
- version/version.go
**Description of the change**: Post-release branch bump for v0.10.x
**Motivation for the change**: Versioning
> *: bump to v0.10.0+git for v0.10.x

- doc/user-guide.md
Address the TODOs in the user-guide on the more common advanced controller configurations.
Fixes #1028 
The upstream godocs for the [Controller](https://godoc.org/sigs.k8s.io/controller-runtime/pkg/controller) and [EventHandler](https://godoc.org/sigs.k8s.io/controller-runtime/pkg/handler) types are already detailed enough with examples so we can mostly point and defer to those docs.
The one example that can be improved is for the EnqueueRequestFromMapFunc handler. That should be worked on upstream.
The [Predicate godocs](https://godoc.org/sigs.k8s.io/controller-runtime/pkg/predicate) are a little sparse and since we already have an in depth example for that we can just point to that.
> doc/user-guide: add docs for advanced controller configurations

- CHANGELOG.md
- internal/pkg/scaffold/olm-catalog/csv_updaters.go
- test/test-framework/deploy/olm-catalog/memcached-operator/0.0.3/memcached-operator.v0.0.3.clusterserviceversion.yaml
Generated `alm-examples` for olm in a pretty format. 
* To improve the Maintenace ability and understatement.
* https://github.com/operator-framework/operator-sdk/issues/1708
**Tests performed locally:**
> feat(olm-catalog) : Generated alm-examples in a pretty format

- CHANGELOG.md
**Description of the change:** Add the addition of a new flag to the `v0.9.0` CHANGELOG
**Motivation for the change:** We should mention all new features so users know when features where added and thus what version of the SDK they need to use for the features to work. This is an important addition that was missed in the `v0.9.0` changelog
> CHANGELOG.md: add important addition to v0.9.0 that was missed

- CHANGELOG.md
- pkg/helm/engine/ownerref.go
- pkg/helm/engine/ownerref_test.go
- pkg/helm/release/manager_factory.go
Update helm-operator's custom rendering engine to skip owner reference injection for resources that are cluster-scoped.
#1815
> pkg/helm: only inject ownerrefs into namespace-scoped resources

- cmd/operator-sdk/internal/genutil/genutil.go
Fix typo in the `generateWithHeaderFile` comment.
"arguemnt" isn't a valid English word.
> cmd/.../genutil: fix typo in comment

- CHANGELOG.md
- pkg/helm/release/manager.go
- pkg/helm/release/manager_factory.go
This changes the release name for new CRs to be the CR name. Releases for existing CRs will continue to use the legacy name. If a CR is created, and a release already exists with the same name from a CR of a different kind, an error is returned, indicating a duplicate name.
The reason for this change is based on an interaction between the Kubernetes constraint that limits label values to 63 characters and the Helm convention of including the release name as a label on release resources.
Since the legacy release name includes a 25-character value based on the parent CR's UID, it leaves little extra space for the CR name and any other identifying names or characters added by templates.
Also including a random string in the …
> pkg/helm: deprecate UID-based release name, use CR name instead

- ci/dockerfiles/ansible-e2e-hybrid.Dockerfile
- ci/dockerfiles/ansible.Dockerfile
- internal/pkg/scaffold/ansible/build_test_framework_dockerfile.go
- internal/pkg/scaffold/ansible/dockerfilehybrid.go
**Description of the change:** add `yum clean all && rm -rf /var/cache/yum/*` to ansible dockerfiles.
**Motivation for the change:** yum repos can become stale and cause errors like:
```console
$ yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
...
https://mirror.steadfastnet.com/epel/7/x86_64/repodata/59cd2d904711571ac63cfec0fec0641233dc027173c6667914bbcc2e10ea11dd-primary.sqlite.bz2: [Errno 14] HTTPS Error 404 - Not Found
Trying other mirror.
http://mirror.math.princeton.edu/pub/epel/7/x86_64/repodata/59cd2d904711571ac63cfec0fec0641233dc027173c6667914bbcc2e10ea11dd-primary.sqlite.bz2: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
...
```
The accepted fix is to clean the yum cache on each build. See [this …
> ansible Dockerfiles: ensure clean yum cache before installing packages

- internal/pkg/scaffold/ansible/deploy_operator.go
Defaults fact gathering to explicit, which means you need to add `gather_facts: yes` or run the setup task to make ansible gather facts about your hosts.
This should help us avoid a class of error related to certain facts not necessarily being discoverable on any arbitrary image.
closes #1677
> Default ansible fact gathering to explicit

- internal/pkg/scaffold/ansible/k8s_status.go
when old condition is on index 0, new condition with same type was always appended, instead of replaced.
This PR fixes issue when old condition is on index 0 and new condition with the same type should replace old condition, but instead it is appended.
/cc @fabianvf @MarSik
> k8s_status module: fix append issue, when condition was on 0 index

- CHANGELOG.md
- ci/tests/e2e-ansible.sh
- hack/tests/e2e-ansible.sh
- pkg/ansible/run.go
This PR enables custom resource metrics for ansible based operators.
Closes #1554
> ansible: add custom resource metrics

- doc/operator-scope.md
This commit fixes the out of place yaml indentation.
> docs: Fix the example indentation

- doc/migration/version-upgrade-guide.md
Add a doc that outlines the steps needed to upgrade an operator project to using a a particular version fo the SDK.
Closes #947 
Long overdue and it should help some users who are using older versions to step through the changes needed to upgrade to the later versions.
Note: the sections for `v0.8.0` and beyond will be added in a follow up PR since they involve the switch over to using Go modules.
> doc/migration: add version upgrade guide

- doc/dev/developer_guide.md
Just update the doc since `make dep` no longer exists
https://github.com/operator-framework/operator-sdk/issues/1775
> docs(user dev guide) : replace make dep since it no longer exists

- CHANGELOG.md
- doc/design/milestone-0.2.0/csv-generation.md
- doc/proposals/cli-ux-phase1.md
- doc/proposals/sdk-code-annotations.md
- doc/test-framework/scorecard.md
The Dir of docs in OLM was changed from Documentation to doc. This change is to fix the broken links. 
- https://github.com/operator-framework/operator-sdk/issues/1887
> Fix broken links - OLM Documentation was replaced by doc

- CHANGELOG.md
- cmd/operator-sdk/add/api.go
To skip to run k8s codegen and openapi-gen to generate deepcopy and validation spec for new CRD
Added new flag `--skip-generation` for `operator-sdk add api`
To skip to run k8s codegen and openapi-gen to generate deepcopy and validation spec for new CRD
> cmd: added new flag --skip-generation for operator-sdk add api

- doc/user/install-operator-sdk.md
Fix some minor issues in the documentation and remove the suggestion of using the `-J` flag with `curl`.
The operator installation instructions uses the `-J` flag when using `curl`. This is generally not a best practice, and more often than not should be avoided. 
See https://curl.haxx.se/docs/manpage.html#OPTIONS under the `-J` section
This also updates some minor nits found in the document.
> Remove usage of J flag

- CHANGELOG.md
- cmd/operator-sdk/add/api.go
- doc/sdk-cli-reference.md
Improves documentation and CHANGELOG for `operator-sdk add api --skip-generation` flag.
Add to SDK CLI Reference doc and improve wording.
> CHANGELOG.md,cmd,doc: update docs about --skip-generation flag

- pkg/metrics/metrics.go
createOrUpdateService should return latest service not the existing service.
log should use the INFO level log as like “Metrics Service object created”.
CreateMetricsService should return latest service, so createOrUpdateService should return latest service not the existing service.
log should use the INFO level log as like “Metrics Service object created”.
> pkg/metrics: CreateMetricsService should return latest service

- internal/olm/client.go
- internal/olm/client/client.go
**Description of the change:** copy `Client.GetInstalledVersion()`, `olmNamespace`, and `ErrOLMNotInstalled` from `internal/olm` to `internal/olm/client`.
**Motivation for the change:** Each of these pieces of code can be used by various parts of code interacting with OLM, in the present and future. They should therefore be accessible to code which leverages `internal/olm/client.Client`.
> internal/olm: move GetInstalledVersion() to internal/olm/client

- test/test-framework/deploy/olm-catalog/memcached-operator/0.0.2/memcached-operator.v0.0.2.clusterserviceversion.yaml
- test/test-framework/deploy/olm-catalog/memcached-operator/0.0.3/memcached-operator.v0.0.3.clusterserviceversion.yaml
- test/test-framework/deploy/olm-catalog/memcached-operator/memcached-operator.package.yaml
**Description of the change:** make names uniform, add package manifest
**Motivation for the change:** currently test framework CSV's do not pass registry/OLM validation, and don't have a package manifest that describes them.
> test/test-framework: update manifests to pass registry/OLM validation

- doc/ansible/dev/developer_guide.md
- doc/ansible/user-guide.md
- doc/dev/developer_guide.md
- doc/helm/user-guide.md
- doc/user-guide.md
Adds context to titles of user guides for easier searchability.
See issue #1905.
> Issue #1905: Add type of guide to user guide documentation.

- .travis.yml
- Makefile
- hack/image/build-helm-image.sh
- hack/image/push-image-tags.sh
- hack/image/push-manifest-list.sh
- hack/lib/image_lib.sh
build for ppc64le:
- the sdk cli
- the helm operator image
and create a "multi-arch" image for helm 
Signed-off-by: Christy Norman <christy@linux.vnet.ibm.com>
> ppc64le helm image build

- doc/dev/release.md
doc/dev/release.md:
- add samples repo update step after SDK release steps
- remove references to dep manager scaffold test files
- update what needs to change post-release
**Motivation for the change:** outdated release doc info, and we need a way to keep the samples repo in line with SDK releases.
> doc/dev/release.md: some cleanup and require samples repo update on a release

- cmd/operator-sdk/scorecard/cmd.go
- go.mod
- internal/pkg/scorecard/helpers/versions.go
- internal/pkg/scorecard/helpers/versions_test.go
- internal/pkg/scorecard/plugins/basic_tests.go
- internal/pkg/scorecard/plugins/resource_handler.go
- internal/pkg/scorecard/scorecard.go
This PR adds a version flag to the operator-sdk scorecard subcommand which will support
the ability of the end user to specify which version of the scorecard they want to run.
With this flag added, typical usage in code looks like:
if schelpers.IsV1alpha2() {
// v1alpha2 logic
}
The version command option is allowed on the scorecard CLI command line or
within the scorecard configuration file.
If not set, the version value is v1alpha1 which represents the current scorecard implementation.
This PR includes code to validate the version:  v1alpha1, v1alpha2 being the valid choices
When a user specifies an invalid version an error is reported as follows:
$ operator-sdk scorecard --version foomatic
Error: invalid scorecard version (foomatic); valid values: …
> Version flag

- CHANGELOG.md
- ci/dockerfiles/go-e2e.Dockerfile
- ci/dockerfiles/helm-e2e-hybrid.Dockerfile
- ci/dockerfiles/helm.Dockerfile
- ci/dockerfiles/scorecard-proxy.Dockerfile
- ci/tests/e2e-helm.sh
- hack/tests/e2e-helm.sh
- images/scorecard-proxy/Dockerfile
- internal/pkg/scaffold/build_dockerfile.go
- internal/pkg/scaffold/build_dockerfile_test.go
- internal/pkg/scaffold/helm/dockerfilehybrid.go
Update Go, Helm and scorecard proxy base images to use ubi8 instead of 7. 
https://jira.coreos.com/browse/OSDK-512
> Operator developers gets UBI8 based images (for all less Ansible)

- ci/dockerfiles/ansible-e2e-hybrid.Dockerfile
- ci/dockerfiles/ansible.Dockerfile
- ci/tests/e2e-ansible.sh
- internal/pkg/scaffold/ansible/dockerfilehybrid.go
**Description of the change:** ubi7 -> ubi8 for all ci files.
**Motivation for the change:** some missed image updates from #1952, which are required in prow CI.
> ci,internal: update ubi7 -> ubi8

- .travis.yml
- CHANGELOG.md
- ci/dockerfiles/ansible-e2e-hybrid.Dockerfile
- ci/dockerfiles/ansible.Dockerfile
- doc/ansible/dev/developer_guide.md
- hack/tests/e2e-ansible-molecule.sh
- internal/pkg/scaffold/ansible/build_test_framework_dockerfile.go
- internal/pkg/scaffold/ansible/dockerfilehybrid.go
- internal/pkg/scaffold/ansible/k8s_status.go
- internal/pkg/scaffold/ansible/molecule_default_prepare.go
- internal/pkg/scaffold/ansible/molecule_test_cluster_playbook.go
- internal/pkg/scaffold/ansible/molecule_test_local_playbook.go
- internal/pkg/scaffold/ansible/travis.go
- pkg/ansible/runner/internal/inputdir/inputdir.go
- test/ansible-inventory/inventory/hosts
- test/ansible-inventory/molecule/test-local/asserts.yml
- test/ansible-inventory/molecule/test-local/playbook.yml
- test/ansible-inventory/molecule/test-local/prepare.yml
- test/ansible-inventory/plugins/filter/test.py
- test/ansible-inventory/roles/inventory/tasks/main.yml
- Upgrade the python version 2 which is deprecated to 3.
- Upgrade ansible version and it deps/utilities too
- Use yum update
- https://github.com/operator-framework/operator-sdk/issues/1884
- https://jira.coreos.com/browse/OSDK-545
- Keep the images and versions updated ( solve technical debts )
- Address request made in : https://github.com/operator-framework/operator-sdk/pull/1979
> Upgrade Ansible Images 

- Makefile
Makefiles can sometimes be cumbersome to read. This little patch allows
you to run `make help` and see what targets do and what's available.
Right now I didn't document all the ones with / in them but we can certainly
add support for that. I hope I got the help messages right.
Closes: #1950
> Makefile: add help to major targets.

- CHANGELOG.md
- doc/dev/release.md
- As a follow-up to #1533, updates the developer release documentation to include the new support for the `ppc64le` binary and helm-operator base image.
- Add a line to the CHANGELOG for #1533.
To ensure that SDK developers are aware of the new support for `ppc64le`.
> doc/dev/release.md: add statement ppcle64 support

- CHANGELOG.md
- ci/dockerfiles/ansible-e2e-hybrid.Dockerfile
- ci/dockerfiles/ansible.Dockerfile
- ci/tests/e2e-ansible.sh
- doc/sdk-cli-reference.md
- internal/pkg/scaffold/ansible/build_test_framework_dockerfile.go
- internal/pkg/scaffold/ansible/dockerfilehybrid.go
- Upgrade ansible images to use ubi8 instead of 7 (for now it has the conditionals to pass in both)
**NOTE:**
To use ubi8 is required:
-to upgrade epel from 7 to 8 as well.
-python3-pip instead of python36-pip
**Motivation**
https://github.com/operator-framework/operator-sdk/issues/1656
> Ansible ubi upgrade

- CHANGELOG.md
- ci/dockerfiles/ansible-e2e-hybrid.Dockerfile
- ci/dockerfiles/ansible.Dockerfile
- internal/pkg/scaffold/ansible/ao_logs.go
- internal/pkg/scaffold/ansible/dockerfilehybrid.go
Ansible images using just ubi8
https://github.com/operator-framework/operator-sdk/issues/1656
> ansible images using just ubi8

- ci/tests/e2e-ansible.sh
- ci/tests/e2e-helm.sh
Remove `-t` flag, which unnecessarily enables a TTY for `kubectl run` commands that test metrics endpoints in ansible and helm e2e tests.
Following up from #1864, making similar changes to e2e scripts used in Travis, this should fix some flakes that happen periodically with helm and ansible e2e tests.
> hack/tests: remove tty setup in e2e usage of kubectl run

- CHANGELOG.md
- cmd/operator-sdk/olmcatalog/gen-csv.go
- internal/util/k8sutil/k8sutil.go
Relax `_crd.yaml` suffix check when copying over CRD manifests for `operator-sdk olm-catalog gen-csv --update-crds`
Fixes #1980
> *: fix gen-csv to copy CRD manifests with any name

- doc/proposals/openshift-4.3/operator-testing-tool.md
this is the proposal draft document for the operator-testing-tool, for openshift-4.3
not a breaking change or code fix, just the proposal for a new feature.
> initial draft of operator-testing-tool proposal for openshift-4.3

- go.mod
- go.sum
- internal/pkg/scaffold/ansible/go_mod.go
- internal/pkg/scaffold/go_mod.go
- internal/pkg/scaffold/helm/go_mod.go
**Description of the change:** use github.com/apache/thrift mirror instead of git.apache.org directly.
**Motivation for the change:** see #1873 for details.
Closes #1873
> go.mod,go.sum,internal/pkg/scaffold: use git.apache.org mirror

- CHANGELOG.md
- internal/pkg/scaffold/olm-catalog/csv_updaters.go
This PR fixes an issue in `olm-catalog gen-csv` where the CSV's owned CRDs are not properly populated from CRD manifests in `deploy/crds`.
The current code has two issues:
1. For new CSVs (when `--from-version` is not used), no CRDs are populated.
2. For CSV updates (when `--from-version` is used), only CRDs that are in the original version will be carried forward to the new version, even if there are new CRDs present in `deploy/crds`
These issues stem from the fact that the CSV updater iterates the existing set of CRDs to build the new set. In case 1, the existing set is empty, since nothing exists, which explains why no CRDs are populated.
Fixes the above described issue.
> internal/pkg/scaffold/olm-catalog/csv_updaters.go: fix applying owned CRDs

- CHANGELOG.md
Remove extra bugfix section from the CHANGELOG.
Fixing this from #2015
> CHANGELOG: remove extra bugfix section

- doc/test-framework/writing-e2e-tests.md
Adding one-liner information about `--namespace` flag.
I was under the impression that `operator-sdk test local ./test/e2e --up-local --namespace=memcached`  will create `namespece=memcached` and when I tried the command it was failing due to  `namespaces "memcached" not found` and for this, I raised an issue #2014. But later I got to know that it won't create any namespace but we need to specify the namespace that it should watch for changes in. So I thought it's a good piece of information and should have a place in the doc.
> Update writing-e2e-tests doc

- doc/proposals/TEMPLATE.md
- doc/proposals/ansible-operator-status.md
- doc/proposals/ansible-operator-testing.md
- doc/proposals/ansible-operator.md
- doc/proposals/cli-ux-phase1.md
- doc/proposals/helm-operator.md
- doc/proposals/improved-scorecard-config.md
- doc/proposals/leader-for-life.md
- doc/proposals/metering-operator-metrics.md
- doc/proposals/scorecard-plugin-system.md
- doc/proposals/sdk-code-annotations.md
- doc/proposals/tls-utilities.md
- Update the template in order to use the OCP one. 
- Update the status for the current one and add the ref links
Closes: https://github.com/operator-framework/operator-sdk/issues/1910
> same standard for all proposals

- CHANGELOG.md
- cmd/operator-sdk/olmcatalog/gen-csv.go
- internal/pkg/scaffold/olm-catalog/csv_updaters.go
- internal/util/k8sutil/k8sutil.go
Cherry pick of #2015 and #2017 bug fixes.
Needed for the `v0.10.1` release
> cherry-pick csv-gen bugfixes for #2015 #2017

- CHANGELOG.md
- internal/pkg/scaffold/ansible/travis.go
Add missing jmespath dependency to .travis.yml template for Ansible-based operators.
Closes #2023
> Fixes #2023: jmespath required to run default molecule tests in Travis CI environment.

- CHANGELOG.md
- cmd/operator-sdk/main.go
- cmd/operator-sdk/printdeps/cmd.go
- internal/util/projutil/project_util.go
- Be able to execute the commands operator-sdk generate k8s and openapi without relay in the existence of the Dockerfile and/or main.go one.
- Not relay in the Dockerfile in order to support other kinds of containers. 
Closes: https://github.com/operator-framework/operator-sdk/issues/1804 and https://github.com/operator-framework/operator-sdk/issues/1686
PS.: Helpful for https://github.com/operator-framework/operator-sdk/issues/1964
> Allow some commands to generate k8s, without requiring build files.

- CHANGELOG.md
- pkg/ansible/controller/reconcile.go
This PR fixes invalid usages of `logger.Info` in `pkg/ansible/controller/reconcile.go` that cause a panic due to an invalid number of arguments passed to the function.
`logger.Info` requires an odd number of arguments, consisting of a mandatory message and an optional list of `key1, value1, key2, value2, ..., keyN, valueN` pairs.
See https://github.com/operator-framework/operator-sdk/issues/2025
Closes #2025
> pkg/ansible/controller/reconcile.go: fix invalid logger.Info usage

- CHANGELOG.md
- doc/user/install-operator-sdk.md
- internal/pkg/scaffold/ansible/go_mod.go
- internal/pkg/scaffold/ansible/gopkgtoml.go
- internal/pkg/scaffold/go_mod.go
- internal/pkg/scaffold/gopkgtoml.go
- internal/pkg/scaffold/helm/go_mod.go
- internal/pkg/scaffold/helm/gopkgtoml.go
- version/version.go
Change versions to `v0.11.0`
Prepare for release `v0.11.0`
> *: release v0.11.0

- CHANGELOG.md
- doc/user/install-operator-sdk.md
- internal/pkg/scaffold/ansible/go_mod.go
- internal/pkg/scaffold/ansible/gopkgtoml.go
- internal/pkg/scaffold/go_mod.go
- internal/pkg/scaffold/gopkgtoml.go
- internal/pkg/scaffold/helm/go_mod.go
- internal/pkg/scaffold/helm/gopkgtoml.go
- version/version.go
Reverts operator-framework/operator-sdk#2034
There is a bug in `add crd` #1660  which causes it to fail outside `$GOPATH/src` for ansible projects:
```
$ operator-sdk add crd --kind=Foo --api-version=ansible.example.com/v1alpha1
FATA[0000] Project not in $GOPATH
```
This will currently cause the release tag to fail CI.
https://travis-ci.org/operator-framework/operator-sdk/jobs/596366754#L3017-L3020
> Revert "*: release v0.11.0"

- ci/tests/e2e-ansible.sh
- ci/tests/e2e-helm.sh
- cmd/operator-sdk/add/crd.go
- hack/image/build-ansible-image.sh
- hack/image/build-helm-image.sh
- hack/tests/e2e-ansible-molecule.sh
- hack/tests/e2e-ansible.sh
- hack/tests/e2e-helm.sh
- Allow `add crd` command to run outside `$GOPATH/src` for Helm/Ansible projects.
- Change `GOTMP="$(mktemp -d -p $GOPATH/src)"` ==> `GOTMP="$(mktemp -d)"` 
- Change the var name `GOTMP` to `TMPDIR` in the ansible/helm CI scripts
Fix the bug introduced to `add crd` in #1660 
The CI script var `GOTMP` name change is to avoid setting it as`GOTMP="$(mktemp -d -p $GOPATH/src)"` since those tests shouldn't need any Go related envs/paths. This is what caused the break in `add crd` to not be detected by the prow CI scripts in #1660
> *: allow add crd to run for ansible/helm projects outside $GOPATH

- doc/migration/version-upgrade-guide.md
- doc/user/unit-testing.md
**Description of the change:** add v0.10 and v0.11 SDK migration guides.
**Motivation for the change:** breaking changes occurred after v0.10, which need to be documented for migration purposes.
**Note:** we should probably hold off on merging this until we are ready to release, since this doc references the new release tag and might need to be updated following future changes pre-release.
> doc/migration/version-upgrade-guide.md: v0.10 and v0.11 upgrade guides

- ci/tests/e2e-ansible.sh
Add 60s timeout when deleting CRD's on the Ansible e2e tests
If the deletion fails, it can take up to 4 hours for CI to timeout itself
> ci/tests: add timeout to ansible e2e

- cmd/operator-sdk/new/cmd.go
- doc/sdk-cli-reference.md
I think `github.com/example-inc/my-opertor` is supposed to be `github.com/example-inc/my-operator`.
> cmd: fix typo

- CHANGELOG.md
- internal/pkg/scaffold/cmd.go
- internal/pkg/scaffold/cmd_test.go
The scaffold for Operator bootstrapping now includes the Operator's `version.Version`.
Currently an Operator built from scaffold does not print the Operator's `version.Version`
(This is my first PR; sorry if there is additional context you need, or if you're not looking for this type of PR)
> scaffold: printVersion includes operator's Version

- ci/tests/e2e-ansible.sh
Reorganize deletions so the operator can remove the finalizer on the CRs before the CRD is deleted
Frequent test failures
> Fix ansible-e2e CRD deletion timeouts

- doc/faq.md
Adds a question and the answer to the documentation for dealing with dependencies for ansible modules that aren't included in the ansible-operator image.
Adds a question and the answer to the documentation for dealing with dependencies for ansible modules that aren't included in the ansible-operator image.
I had to piece this together myself and thought it would be good to document for others (and when I forget).
> Documents Unsupported ansible modules Q/A

- internal/pkg/scorecard/helpers/helpers.go
- internal/pkg/scorecard/helpers/test_definitions.go
- internal/pkg/scorecard/plugins/basic_tests.go
- internal/pkg/scorecard/plugins/labels.go
- internal/pkg/scorecard/plugins/olm_tests.go
- pkg/apis/scorecard/v1alpha1/types.go
- pkg/apis/scorecard/v1v2conversions.go
part of the v1alpha2 implementation of the scorecard, this PR only adds the pre-defined labels to the basic and olm test definitions and adds the labels into the test results for displaying in JSON format (v1alpha2 only).
this PR sets up future work where label selectors will be added and used to determine
what tests get executed.
> Add labels to scorecard tests

- hack/tests/sanity-check.sh
- pkg/metrics/service-monitor.go
metrics: add an ability to create a ServiceMonitor with only a subset of ports, provided as a list of port names.
This change adds 2 additional calls for creating a ServiceMonitor: `CreateServiceMonitorWithPorts` and `GenerateServiceMonitorWithPorts`, they allow providing a list of ports to add as endpoints in the created ServiceMonitor object. The list is compared with the ports in the provided service and only adds the endpoints that already exist in the initial service.
Closes #1972 
Signed-off-by: Alex Lourie <djay.il@gmail.com>
> Allow using subset of endpoints when creating a ServiceMonitor

- .gitignore
**Description of the change:** clean up .gitignore
**Motivation for the change:** noticed that `cmd/operator-sdk/build` is also being ignored, and certain regexp's are not used.
> .gitignore: clean up, regexp on top-level artifact dirs

- CHANGELOG.md
- internal/olm/manager.go
func in `Do` declared a new local err, it will never be return to outer scope.
fix this bug
> bugfix: error in Do will never return to outer scope

- doc/ansible/project_layout.md
Add the `/` to make the directory name more clear that it is a directory. Escape the less than symbol so that it does not get eaten by markdown.
OCD?
> docs: make directories clear, escape less than

- .travis.yml
- Makefile
- ci/dockerfiles/ansible-e2e-hybrid.Dockerfile
- ci/dockerfiles/ansible.Dockerfile
- ci/dockerfiles/helm-e2e-hybrid.Dockerfile
- ci/dockerfiles/helm.Dockerfile
- ci/prow.Makefile
- doc/dev/developer_guide.md
- doc/dev/testing/running-the-tests.md
- doc/dev/testing/travis-build.md
Switch to using `-` instead of `/` for the targets. This came up in a comment of Issue #1950, kubebuilder uses `-` as well.
> Makefile: Use hyphen instead of slash

- CHANGELOG.md
- doc/ansible/dev/advanced_options.md
- pkg/ansible/flags/flag.go
- pkg/ansible/run.go
- pkg/ansible/runner/runner.go
- pkg/ansible/runner/runner_test.go
- pkg/ansible/watches/testdata/valid.yaml.tmpl
- pkg/ansible/watches/watches.go
- pkg/ansible/watches/watches_test.go
Make it possible to configure the verbosity of `ansible-runner` command
invocations via command line flags. The default value should be 2 to
avoid unexpected changes in behavior. Also, like `maxWorkers` the
`ansibleVerbosity` can be overridden per GVK with an environment
variable of the form `ANSIBLE_VERBOSITY_$KIND_$GROUP`.
This PR:
- Adds new command line flag `ansible-verbosity` for Ansible based
operators
- Add internal `cmdFuncType` to runner pkg for use when constructing
command functions
> feat(ansible): make ansible verbosity configurable

- hack/tests/scaffolding/scaffold-memcached.go
**Description of the change:** always use the local SDK repo path in `go.mod` replace lines.
**Motivation for the change:** the CI we use will always have a local copy of the SDK repo, one merged with master. e2e tests should always use this dir so they are (mostly) CI type-agnostic.
> hack/tests/scaffolding/scaffold-memcached.go: always use local SDK dir in CI

- CHANGELOG.md
- internal/scaffold/role.go
- internal/scaffold/role_test.go
Add default role required for the services.
```
- apiGroups:
- apps
resources:
- deployments
verbs:
- '*'
```
https://github.com/operator-framework/operator-sdk/issues/2088
**Steps to verify it**
Following the steps to make the review easier to be done. 
- Run `operator-sdk new memcached-operator --api-version=cache.test.com/v1alpha1 --kind=Memcached --type=helm --helm-chart=stable/memcached`
- Replace the `  AntiAffinity: "hard"` for ` AntiAffinity: "soft"` in the values and CR
- Rename the CRD for `cache.test.com_v1alpha1_memcached_crd.yaml`
- Use the following makefile to make its easier 
```
.DEFAULT_GOAL:=help
SHELL:=/bin/bash
NAMESPACE=fix
##@ Application
install: ## Install all resources (CR/CRD's, RBCA and Operator) …
```
> fix role for the metric services

- hack/tests/sanity-check.sh
Revert sanity test changes from #1949 
In order to migrate to Go 1.13, we needed to temporarily ignore `go.mod` and `go.sum` changes that were caused by Go tooling during the sanity tests. Now that openshift/releases#5443 is merged, we can revert that temporary change so that we require that PRs correctly update `go.mod` and `go.sum`.
> hack/tests/sanity-check.sh: fail on changed go.mod and go.sum

- CHANGELOG.md
- pkg/ansible/runner/runner.go
When the maxArtifacts annotation can not be converted to an integer, do
not use it.
> fix(ansible): invalid maxArtifacts annotation

- CHANGELOG.md
- internal/util/operator-registry/package_manifest.go
- internal/util/operator-registry/package_manifest_test.go
**Description of the change:** only return an error if package manifest has no default channel and more than one channel
**Motivation for the change:** see #2115
Closes #2115
> internal/util/operator-registry: fix default channel check

- CHANGELOG.md
- ci/tests/e2e-ansible.sh
- ci/tests/e2e-helm.sh
- ci/tests/subcommand.sh
- hack/ci/setup-k8s.sh
- internal/scaffold/ansible/molecule_default_molecule.go
- internal/scaffold/ansible/molecule_test_local_molecule.go
- test/ansible-inventory/molecule/test-local/molecule.yml
- test/ansible-memcached/molecule.yml
- test/e2e/_incluster-test-code/memcached_test.go
Update various docs and test scripts to use Kubernetes 1.15
Following up on comments from #2083
> *: updating k8s version references, follow-up from #2083

- hack/tests/e2e-ansible-molecule.sh
- hack/tests/e2e-ansible.sh
Updates the Travis Ansible e2e tests to match the OpenShift Ansible e2e tests.
Deleting the service account before deleting the CRD causes the e2e tests to fail because the operator no longer has the necessary permissions to complete the test.
> hack/tests/e2e-ansible*: fix travis ansible e2e tests

- Makefile
- README.md
- ci/dockerfiles/builder.Dockerfile
- ci/prow.Makefile
- ci/tests/scaffolding/e2e-ansible-scaffold-hybrid.sh
- ci/tests/scaffolding/e2e-helm-scaffold-hybrid.sh
- hack/tests/e2e-ansible.sh
- hack/tests/e2e-helm.sh
- hack/tests/scaffolding/scaffold-memcached.go
Removes use of GO111MODULE and GOPROXY environment variables in build and test scripts.
Now that we have updated SDK to support Go 1.13, these environment variables are no longer necessary.
- GO111MODULE semantics have changed, such that any project with a `go.mod` file is considered a go module unless GO111MODULE is explicitly set to `off`
- GOPROXY now defaults to `https://proxy.golang.org,direct`. Adding `direct` as an alternative also incidentally solves a problem with resolving branch names (e.g. `v0.12.x`) when used in `require` blocks.
This was cherry-picked from https://github.com/operator-framework/operator-sdk/pull/2128/commits/174e40ade11623bd21d3c3c362baab46a7ddde49
> *: remove broken and unnecessary Go env for master

- Makefile
- README.md
- ci/dockerfiles/builder.Dockerfile
- ci/prow.Makefile
- ci/tests/scaffolding/e2e-ansible-scaffold-hybrid.sh
- ci/tests/scaffolding/e2e-helm-scaffold-hybrid.sh
- hack/tests/e2e-ansible.sh
- hack/tests/e2e-helm.sh
- hack/tests/scaffolding/scaffold-memcached.go
Removes use of GO111MODULE and GOPROXY environment variables in build and test scripts.
Now that we have updated SDK to support Go 1.13, these environment variables are no longer necessary.
- GO111MODULE semantics have changed, such that any project with a `go.mod` file is considered a go module unless GO111MODULE is explicitly set to `off`
- GOPROXY now defaults to `https://proxy.golang.org,direct`. Adding `direct` as an alternative also incidentally solves a problem with resolving branch names (e.g. `v0.12.x`) when used in `require` blocks.
> *: remove broken and unnecessary Go env for v0.12.x

- CHANGELOG.md
- pkg/ansible/proxy/proxy.go
- pkg/helm/controller/controller.go
- pkg/internal/predicates/predicates.go
Event filtering will allow Ansible operator to skip reconciles that are not required
Closes #1968
Added support for event filtering using predicates
Address feature request #1968
> Ansible operator: Adding support for event filtering via predicates

- doc/user-guide.md
**Description of the change:** add notes on CRD validation annotations to user guide.
**Motivation for the change:** validation annotations are not documented in an obvious place in the SDK even though they're integral to CRD generation.
Relates to #2111 and #2042
> doc/user-guide.md: add CRD validation annotation notes

- doc/ansible/project_layout.md
**Description of the change:** fix Ansible Galaxy reference link
**Motivation for the change:** page seems to have been moved to https://docs.ansible.com/ansible/latest/reference_appendices/galaxy.html
> doc/ansible/project_layout.md: fix Ansible Galaxy link

- doc/migration/version-upgrade-guide.md
Add info to help users fix the validation issues which may be faced with the open API version used. 
https://github.com/operator-framework/operator-sdk/issues/2042#issuecomment-546274495
> add openAPI validation in migration doc

- internal/scaffold/crd_test.go
- test/test-framework/pkg/apis/cache/v1alpha1/memcached_types.go
- test/test-framework/pkg/apis/cache/v1alpha1/memcachedrs_types.go
- Fix type of node in the test-framework data according to API rule validations
Related to: #2114 and #2042
> Fix type of node in the test-framework data according to API rule validations

- doc/user-guide.md
- hack/tests/scaffolding/scaffold-memcached.go
- Add check in the tests to ensure that no issues related the API rule validations should be faced. 
- Fix type of spec for Memcached test data implementation. 
Closes #2114 
Related to: https://github.com/operator-framework/operator-sdk/issues/2042
> Add check for API rule validation and fix type for Memcached test data

- doc/ansible/dev/developer_guide.md
- doc/ansible/dev/retroactively-owned-resources.md
Update docs to use CR instead of CRD where appropriate
Doc implies that the CRD is included in extra vars, when its actually the CR.
> ansible: Update docs to use CR instead of CRD where appropriate

- cmd/operator-sdk/test/local.go
- internal/util/projutil/exec.go
- pkg/test/context.go
- pkg/test/framework.go
- pkg/test/main_entry.go
- pkg/test/resource_creator.go
This PR refactors the e2e framework to remove unnecessary global variables.
[Global Variables Are Bad](http://wiki.c2.com/?GlobalVariablesAreBad)
> Refactor e2e framework to remove globals

- internal/scorecard/helpers/helpers.go
- pkg/apis/scorecard/v1v2conversions.go
- test/test-framework/pkg/controller/memcached/memcached_controller.go
Remove TypeMeta.
When we do a new object{} the TypeMeta will be added into the initialization.  Then, is not a good practice to add it manually. 
PS: It was removed from other places in the past (operator-framework/operator-sdk-samples#64, #1462 ).
> Remove TypeMeta initializations

- internal/scorecard/helpers/helpers.go
- pkg/apis/scorecard/v1alpha1/types.go
- pkg/apis/scorecard/v1alpha2/types.go
- pkg/apis/scorecard/v1v2conversions.go
Add back TypeMeta which is mandatory for scorecard object because it is used to distinguish the versions (v1alpha1 and v1alpha2)
https://github.com/operator-framework/operator-sdk/pull/2153#discussion_r342882783
> Add back TypeMeta which is mandatory for scorecard object because it is used to distinguish the versions (v1alpha1 and v1alpha2)

- CHANGELOG.md
- doc/ansible/user-guide.md
- pkg/ansible/runner/runner.go
- pkg/ansible/runner/runner_test.go
- pkg/ansible/watches/testdata/valid.yaml.tmpl
- pkg/ansible/watches/watches.go
- pkg/ansible/watches/watches_test.go
Support for vars in the top level of ansible watches
Ability to use one playbook for multiple watches with different vars
Closes #2138
> ansible: Support vars in watches

- CHANGELOG.md
- doc/test-framework/scorecard.md
- hack/tests/subcommand-scorecard.sh
- internal/scorecard/scorecard.go
- internal/scorecard/scorecard_output.go
this PR adds return code logic into the scorecard subcommand, so that if any selected
test fails, a return code of 1 is produced.  If no tests fail, then the normal return code of 0 is produced.
adds return code logic, updates the scorecard docs to mention the new logic, and also adjusts the scorecard tests to allow for non-zero return codes.
this change is part of the scorecard v1alpha2 implementation and supports pipelines that run the scorecard in particular so that they can look for non-zero return codes instead of having to parse the scorecard output.
> scorecard - add return code logic

- doc/helm/user-guide.md
this PR corrects a few references to CR and CRD names that are now (v.0.12) generated with different names than what was mentioned in the helm user-guide.  
documentation update for helm user-guide to match what v.0.12 now generates.
> update helm user guide to correct cr and crd file names

- hack/go-linter.sh
- internal/scaffold/olm-catalog/csv_test.go
- internal/scorecard/plugins/olm_tests.go
> feat(linter) : add goconst check and fix issues

- CHANGELOG.md
- ci/dockerfiles/ansible-e2e-hybrid.Dockerfile
- ci/dockerfiles/ansible.Dockerfile
- internal/scaffold/ansible/dockerfilehybrid.go
- test/ansible-memcached/secret/tasks/main.yml
Fix issue faced when jmespath queries are used in in the ansible tasks. 
Closes #2237
> fix(ansible) : install jmespath in the contaner"

- CHANGELOG.md
- doc/ansible/dev/advanced_options.md
- doc/ansible/user-guide.md
- pkg/ansible/runner/runner.go
- pkg/ansible/runner/runner_test.go
This makes it possible to create a CR with an annotation, specifically
`"ansible.operator-sdk/verbosity"`, to override the verbosity of
`ansible-runner` commands for a given CR.
- Store the verbosity on `runner`
- Update `cmdFuncType` to take verbosity and `*exec.Cmd` to convert
integer value of verbosity to string
- In `Run()` get verbosity annotation from CR (if it exists) and use
that value when executing the `cmdFunc`
Closes #2091 
Checklist:
> feat(ansible): Configure verbosity via annotation

- hack/ci/setup-k8s.sh
- hack/lib/image_lib.sh
* hack/ci/setup-k8s.sh: update kindest/node to v1.6.3, kind to latest
**Motivation for the change:** `kind` has released a stable version `v0.6.0`, and has pushed a `v1.16.3` image built with this stable version. We can use this k8s version now that deps have been [bumped](#2145) to `kubernetes-1.16`.
> hack/ci/setup-k8s.sh: update kindest/node to v1.6.3, kind to latest

- CHANGELOG.md
- pkg/test/e2eutil/wait_util.go
Before waitForDeployment was waiting until the exact number of replicas
were available. Now, wait for at least that number of replicas to be
available.
scenario:
I'm using an operator with 3 replicas, but only 1 is needed for tests to
work. If all 3 replicas were available before waitForDeployment started
then it would wait until it timed out because 3 does not equal 1. Now,
since 3 replicas is greater than the 1 needed for tests waitForDeployment
successfully waits.
> pkg/test/e2eutil: wait for a deployment to have >= n replicas

- CHANGELOG.md
- ci/dockerfiles/ansible-e2e-hybrid.Dockerfile
- ci/dockerfiles/ansible.Dockerfile
- doc/ansible/dev/retroactively-owned-resources.md
- internal/scaffold/ansible/dockerfilehybrid.go
- internal/scaffold/ansible/molecule_default_asserts.go
- internal/scaffold/ansible/molecule_test_cluster_playbook.go
- internal/scaffold/ansible/molecule_test_local_playbook.go
- test/ansible-inventory/molecule/test-local/playbook.yml
- test/ansible-memcached/asserts.yml
Replaces uses of the deprecated `k8s_facts` module with `k8s_info`, which is the standard module for k8s information lookups in Ansible 2.9+.
Closes #2168
> Use k8s_info module instead of deprecated k8s_facts in molecule scaffold (#2168)

- .travis.yml
- Makefile
* Change unit test packages from whitelist to blacklist, so new root-level packages are automatically included in unit testing.
* Run `go test` in one run instead of three to simplify collection of code coverage stats.
Improve package selection for unit tests, simplify Makefile
> Makefile,.travis.yml: simplify unit test and code coverage make target

- hack/generate/gen-cli-doc.go
When generating CLI docs, delete and recreate the `doc/cli` directory.
We need to ensure that stale files (e.g. from renamed or removed CLI subcommands) are removed.
> hack/generate/gen-cli-doc.go: recreate doc/cli directory on every run

- CHANGELOG.md
- internal/scaffold/crd.go
- internal/scaffold/crd_test.go
This PR updates the CRD scaffolder for non-go projects to begin using valid structural schema.
Structural schemas are required in v1 CRDs. This change will make it simpler for project maintainers and users to migrate from v1beta1 CRDs to v1 CRDs in the future.
Since ansible and helm v2 do not provide schemas for their roles, playbooks, and charts, and we have no way to easily derive them, we need to continue preserving all CR fields.
> internal/scaffold/crd.go: use structural schema for non-go operator CRDs

- hack/common.sh
install golangci-lint via curl as recommended by its docs
@asmacdo find out that besides controller-runtime been installing it via go get as we are dong here it is not recommended. See: https://github.com/golangci/golangci-lint#go-get
> install  golangci-lint via curl as recommended by its docs

- doc/dev/testing/travis-build.md
- hack/generate/gen-test-framework.sh
- hack/tests/e2e-ansible-molecule.sh
- hack/tests/e2e-ansible.sh
- hack/tests/e2e-helm.sh
fix scripts to run in mac os x and/or Linux
Closes #2257
> fix scripts to run in mac os x and or linux

- ci/tests/e2e-ansible.sh
- ci/tests/e2e-helm.sh
- hack/common.sh
- hack/tests/e2e-ansible-molecule.sh
- hack/tests/e2e-ansible.sh
- hack/tests/e2e-helm.sh
- Replace comments for highlighted texts in the logs to be easier troubleshooting
- Make errors be outputted in red 
- Increase timeouts from 20s to 60s in order to avoid the errors faced in the CI because of it.
- Issues in CI that are solved be re-triggered it
- Be easier to check its issues faced with the changes
**NOTES:**
- See that it passed directly at the first without the need to re-triggered it. 
- See that now is easier to identify what step it is, errors and etc.
>  improve the ansible tests and its logs

- CHANGELOG.md
- doc/helm/dev/developer_guide.md
- doc/helm/user-guide.md
- internal/scaffold/helm/entrypoint.go
- internal/scaffold/helm/watches.go
* Changes the Helm operator to support relative paths to chart directories in the watches.yaml file. If a relative paths is found, a base path will be prepended. The prefered base path comes from the HELM_CHARTS_PATH environment variable. If that is empty or not set, the operator falls back to the HOME directory, which maintains backward compatibility with existing projects.
* Updates the Helm operator project's watches.yaml scaffold to use a relative path instead of an absolute path.
Allowing relative paths simplifies the experience of switching between `operator-sdk up local` and running in-cluster.
Now local filesystem changes do not have to be made for `up local` to work. Previously, developers had to copy their chart to …
> Helm: allow relative paths for helm charts in watches.yaml file

- CHANGELOG.md
- internal/scorecard/plugins/plugin_runner.go
- internal/scorecard/plugins/resource_handler.go
* read CSV when config.OLMDeployed is enabled
* filter listing pods based on deployment's namespace
Closes #2271
> scorecard: Fix basic tests run when 'olm-deployed: true'

- cmd/operator-sdk/test/local.go
- hack/go-linter.sh
- internal/scaffold/helm/chart.go
- internal/scaffold/olm-catalog/package_manifest.go
- Enable unparam check
- Fix linter issues
**Motivation**
Closes: #2212
> fix(linter) : Add unparam checks and fix issues

- cmd/operator-sdk/add/api.go
- cmd/operator-sdk/add/cmd.go
- cmd/operator-sdk/new/cmd.go
- cmd/operator-sdk/scorecard/cmd.go
- hack/tests/check-lint.sh
- internal/flags/watch/flags.go
- internal/scaffold/add_controller_test.go
- internal/scaffold/addtoscheme_test.go
- internal/scaffold/ansible/constants.go
- internal/scaffold/controller_kind_test.go
- internal/scaffold/cr_test.go
- internal/scaffold/crd_test.go
- internal/scaffold/doc_test.go
- internal/scaffold/helm/chart_test.go
- internal/scaffold/olm-catalog/csv.go
- internal/scaffold/olm-catalog/csv_updaters.go
- internal/scaffold/register_test.go
- internal/scaffold/test_setup.go
- internal/scaffold/types_test.go
- internal/scorecard/scorecard.go
- pkg/ansible/paramconv/paramconv.go
- pkg/ansible/runner/internal/inputdir/inputdir.go
- pkg/apis/scorecard/formatting.go
- pkg/k8sutil/k8sutil.go
- pkg/leader/leader.go
- pkg/test/context.go
> Fix linter golint

- CHANGELOG.md
- cmd/operator-sdk/olmcatalog/gen-csv.go
**Description of the change:** set `operatorName` from config after checking if set via CLI.
**Motivation for the change:** fixes #2266.
Closes #2266
> cmd/.../gen-csv.go: set operatorName from config after CLI if empty

- CHANGELOG.md
- internal/scaffold/olm-catalog/csv_updaters.go
**Description of the change:** set install strategy if empty in CSV updaters.
**Motivation for the change:** if a CSV does not have an install strategy when being updated, a CSV updater will error when it should instead set the strategy to `StrategyDetailsDeployment` (the only strategy available).
> internal/scaffold/olm-catalog/csv*.go: set install strategy if empty

- CHANGELOG.md
**Description of the change:** CHANGELOG.md update
**Motivation for the change:** missed in #1162
> CHANGELOG.md: add gen-csv Go API code annotations PR #1162

- doc/user/olm-catalog/generating-a-csv.md
Related to https://github.com/operator-framework/operator-sdk/issues/2292
Added `displayName` as required field in the document.
/cc @camilamacedo86
> Added `displayName` as required field.

- Makefile
- hack/image/build-helm-image.sh
Adds Makefile configuration and updates helm-operator's base image build script to always use GOOS=linux
Running the build script on non-linux hosts currently results in a helm operator base image that contains a binary with GOOS matching the non-linux host OS, which fails to run in Linux-based Kubernetes clusters.
The UBI base image used by the helm operator is based on Linux, so there should not be an OS compatibility problem with this change.
Closes: #2289
> Helm: always use GOOS=linux for operator base image

- README.md
To [avoid confusion for new user](https://github.com/operator-framework/operator-sdk/issues/1337) trying `operator-sdk`, Improve README and replace `example` with `<username>`. 
Also add step to login to public registry like quay.io. If user is not logged in through CLI, He will face following error
`quay unauthorized: access to the requested resource is not authorized`
After login push work seamlessly.
This will improve user experience for trying `operator-sdk` for the first time.
> doc: improve README to try operator-sdk

- hack/generate/gen-test-framework.sh
Update the test framework generator script to handle any branch name produced by `print-deps`
To ensure the sanity test passes on all branches.
This fix is already included in the `v0.13.x` post release PR (#2315)
> hack/generate/gen-test-framework.sh: fix for release branches

- CHANGELOG.md
- cmd/operator-sdk/build/cmd.go
- go.mod
- go.sum
- hack/tests/subcommand.sh
- test/test-framework/go.sum
Before when running `operator-sdk build` with an `--image-build-arg` of
something like `--label some.name="First Last"` then `operator-sdk`
would invoke the builder with ["--label", "some.name=First", "Last"],
when it was actually desired to be ["--label", "some.name=First Last"].
Using `shlex` handles all the appropriate parsing of spaces within quotes
unlike `strings.Fields` which just splits on any spaces regardless of
context like quotes.
Switching to `shlex` enables `operator-sdk build` to now properly handle
spaces within quotes.
> cmd/operator-sdk/build: fix handling of spaces within quotes

- CHANGELOG.md
- cmd/operator-sdk/olmcatalog/gen-csv.go
**Description of the change:** ensure gen-csv is run in the project root.
**Motivation for the change:** see #2081 
Closes #2081
> cmd/operator-sdk/olmcatalog: gen-csv must run in project root

- doc/proposals/tech-debt.md
Adds the OpenShift 4.4 proposal to handle some tech debt cleanup in SDK codebase. This proposal is primarily to document changes that have already been made for historical purposes, but it does include yet-to-be-merged changes that refactor the CRD generation.
To document the design and execution of reducing tech debt during the OpenShift 4.4 development cycle.
> doc/proposals/openshift-4.4/tech-debt.md: add proposal

- doc/proposals/openshift-4.4/ansible-operator-devex.md
Adds the OpenShift 4.4 proposal for improving the developer experience of using the operator-sdk with Ansible. Some of the changes mentioned in the proposal have already been implemented or merged.
To document the plan for improving the developer experience in OpenShift 4.4
> doc/proposals/openshift-4.4/ansible-operator-devex.md: Add proposal for Ansible Operator 4.4 features

- doc/proposals/openshift-4.4/kubebuilder-integration.md
Adds the Openshift 4.4 proposal for integrating the Kubebuilder CLI workflow into the Operator SDK.
Follows up on prior upstream discussions to outlines the high level user stories or steps needed in the SDK to achieve alignment with Kubebuilder.
> Add 4.4 proposal for Kubebuilder integration for Go operators

- doc/migration/version-upgrade-guide.md
I changed the go module information in the v0.11.0 upgrade guide to reflect was is generated by `operator-sdk new` for this version.
I tried to use the upgrade guide to move an operator from v0.10.0 to v0.11.0.  The project would not build because go could not resolve the modules correctly.  I had cut/paste a section of `go.mod` from the upgrade guide, and this was the section that was not correct.  The modules did not specify a valid version.  I am using go version 1.12.14.
> docs: correct the information in the v0.11.0 upgrade guide

- CHANGELOG.md
- doc/helm/user-guide.md
- pkg/helm/controller/controller.go
- pkg/helm/controller/reconcile.go
- pkg/helm/release/manager_factory.go
- pkg/helm/run.go
- pkg/helm/watches/watches.go
- pkg/helm/watches/watches_test.go
Adds `overrideValues` field to Helm operator's watches.yaml file, which allows an operator author to specify a values map that is merged with (and overrides) CR `spec` values.
The values defined in `overrideValues` can use environment variable expansion (e.g. `$MY_VAR` or `${MY_VAR}`) to use values from the environment.
In order to support disconnected scenarios and automated operand image rebuilds (e.g. to fix a CVE) it is necessary 
**To Do**
> pkg/helm: add overrideValues to watches.yaml (with env expansion)

- CHANGELOG.md
- internal/scaffold/cmd.go
- internal/scaffold/cmd_test.go
Skip service metrics when is running out o the cluster
Closes: #1702
**LOCAL TEST**
> fix error to create service metrics when run operator-sdk up local

- doc/user/olm-catalog/csv-annotations.md
- doc/user/olm-catalog/generating-a-csv.md
- internal/scaffold/olm-catalog/csv.go
* doc/user/olm-catalog: document that gen-csv and code annotations are only officially supported for Go Operators for now
* internal/scaffold/olm-catalog/csv.go: do not overwrite a CSV's `spec.customresourcedefinitions` for non-Go Operators
**Motivation for the change:** although `gen-csv` _may_ work with non-Go operators, it does not officially support them (for now). This constraint needs to be documented. Since it may work for Helm and Ansible operator projects as of now, this constraint should not be enforced and prior behavior reinstated.
> gen-csv: non-Go operators are not yet supported

- internal/scaffold/helm/role.go
- internal/scaffold/helm/role_test.go
This PR adds a new role rule during project scaffolding that allows the operator to create events.
This is a follow-up fix for #2325, which is required for the operator to be able to create events on CRs when override values are in use.
> internal/scaffold/helm: added role rule for creating events

- CHANGELOG.md
- pkg/helm/controller/reconcile.go
- pkg/helm/release/manager.go
When reconciling deleted Helm operator CRs, wait for the CR to be deleted from the cache before returning. Also improve the error handling to take advantage of Helm v3's new `ErrReleaseNotFound`
Closes #2342
> Helm: fix misleading "release not found" errors during CR deletion

- internal/util/projutil/exec.go
-mod=vendor is not needed if it's already set in GOFLAGS. So let's not
set it unless it's needed.
This is an issue for commands such as `go test` and `go vet` (
see https://github.com/golang/go/issues/32471 ). This avoids such an
issue.
With the enforcement of `GOFLAGS=-mod=vendor` in openshift, some projects got broken given that environment variable being set by default and operator-sdk setting that explicitly if the vendor directory exists..
> Only add explicit -mod=vendor if needed

- doc/helm/user-guide.md
Signed-off-by: dmesser <dmesser@redhat.com>
Add more context to the topic of `overrideValues` in the docs.
`overrideValues` is generally useful to use environment variables in helm charts. The prime example is making a helm Operator something that can be mirrored for offline/disconnected usage.
> more context on the doc on override values

- doc/proposals/improve-csv-cli.md
**Description of the change:** doc/proposals/improve-csv-cli.md: 'gen-csv --inputs' proposal
**Motivation for the change:** see https://github.com/operator-framework/operator-sdk/pull/2249#issuecomment-558757468.
> doc/proposals/improve-csv-cli.md: 'gen-csv --inputs' proposal

- cmd/operator-sdk/alpha/kubebuilder/cmd.go
- cmd/operator-sdk/alpha/kubebuilder/olmcatalog/cmd.go
- internal/util/projutil/exec.go
- Added a hidden subcommand `operator-sdk alpha kubebuilder ...` that calls out to the kubebuilder binary for Kubebuilder cmds, e.g:
- `operator-sdk alpha kubebuilder init` ==> `kubebuilder init`.
- SDK specific subcommands are not shimmed out to the kubebuilder binary and will be handled separately, e.g:
- `operator-sdk alpha kubebuilder olm-catalog gen-csv ...`
- Flags for Kubebuilder specific subcommands are passed in via the flag `--kb-flags`, e.g:
- `operator-sdk alpha kubebuilder create api --kb-flags="--group cache --version v1 --kind Memcached"`
- Updated `ExecCmd()` util to read from stdin for kubebuilder command prompts.
While the upstream [proposal for Kubebuilder CLI …
> Mock kubebuilder integration with 'operator-sdk alpha kubebuilder' cmd

- .travis.yml
Download goveralls outside of project directory.
Make sure downloading CI dependencies doesn't affect SDK go.mod contents.
> .travis.yml: goveralls download should not affect SDK go.mod contents

- CHANGELOG.md
- pkg/ansible/controller/reconcile.go
- pkg/ansible/controller/reconcile_test.go
Fix issue: https://github.com/operator-framework/operator-sdk/issues/2372
Errors in the event have not been re-trigging the reconcile. 
Closes #2372
**Notes**
Local tests to verify it can be done with the image: `quay.io/camilamacedo86/ansible-operator:dev`
The user POC in the #2372 was used to check.
> fix: (ansible) - Errors in the event have not been re-trigging the reconcile. 

- internal/generate/crd/crd.go
- internal/generate/crd/crd_test.go
* internal/generate/crd: fix controller-gen octal string bug
**Motivation for the change:** controller-gen's output rule for CRD generation disallows directory strings containing numbers starting with 0 that contain non-octal digits, ex. "012345678". This commit fixes a flaky unit test that occasionally triggers this bug. A more thorough fix will be implemented in the near future.
> internal/generate/crd: fix flaky unit test

- doc/helm/user-guide.md
Following up from #2404, this PR adds an anchor to the link so that users are directed to the section of the SDK CLI reference guide that contains the examples for creating a helm operator. 
Improve UX
> Link directly to Helm CLI examples from helm user guide

- CHANGELOG.md
- hack/tests/e2e-helm.sh
- pkg/helm/client/client.go
- pkg/helm/release/manager_factory.go
This PR fixes a bug that causes all release resources
to be created in the namespace that the helm-operator is deployed
in, not the namespace that the CR is deployed in.
Closes #2416
> pkg/helm: install resources in same namespace as CR

- CHANGELOG.md
- hack/tests/e2e-helm.sh
- pkg/helm/client/client.go
- pkg/helm/release/manager_factory.go
Backport #2414 to v0.14.x
See #2416
> [v0.14.x] pkg/helm: install resources in same namespace as CR

- CHANGELOG.md
- pkg/test/client.go
There are instances where the cluster could be temporarily unavailable.
e.g. when etcd is doing leader re-election.
https://search.svc.ci.openshift.org/?search=etcdserver%3A+leader+changed&maxAge=336h&context=2&type=all
While this is not a very normal scenario, it would be good to be lenient
on the cleanup side of things and retry if such a case happens.
This will be reflected as Timeout or Unavailable errors coming from etcd.
When using the e2e test framework to test an operator, if there are network issues, the cleanup functions might fail. This would present itself with the following logs:
```
client.go:75: resource type Deployment with namespace/name (openshift-compliance/compliance-operator) successfully deleted
client.go:75: resource type ClusterRoleBinding with namespace/name …
```
> pkg/test/client: retry cleanup function if cluster is temporarily unavailable

- Makefile
grep -P is not available on bad lucky os. grep -E do the same work in this case.
Can't make properly under osx
> grep -P is not available on osx

- CHANGELOG.md
- internal/scaffold/ansible/go_mod.go
- internal/scaffold/go_mod.go
- internal/scaffold/helm/go_mod.go
- test/test-framework/go.mod
- test/test-framework/go.sum
Add a `replace` line in `go.mod` scaffolds to fix broken dependency from OLM, which was caused by a tag that was removed from `openshift/api` in an effort to make that repo more Go module friendly.
Closes #2394
> internal/scaffold: fix go.mod scaffolds using openshift/api replacement

- .travis.yml
Update `.travis.yml` to resolve some of the validation warnings:
* root: deprecated key sudo (The key `sudo` has no effect anymore.)
* root: missing os, using default `linux`
* jobs.include.os: unknown value `linux-ppc64le`, using the default `linux`
Also update the other docker builds to have explicit settings for arch.
Reduce use of deprecated travis configs
See https://blog.travis-ci.com/2019-11-12-multi-cpu-architecture-ibm-power-ibm-z
> .travis.yml: reduce use of deprecated configs

- CHANGELOG.md
- cmd/operator-sdk/run/local.go
> cmd/operator-sdk: fix run local flags

- cmd/operator-sdk/add/controller.go
- doc/cli/operator-sdk_add_controller.md
- Improve the command controller help 
- Make clear how to use and what is the purpose of the flag `--custom-api-import flag`
Closes #2415
> doc: add better info and example over --custom-api-import flag

- CHANGELOG.md
- doc/user/logging.md
- pkg/log/zap/flags.go
- pkg/log/zap/logger.go
- pkg/log/zap/logger_test.go
Add an option to deactivate stack trace generation, similar to an existing option in Zap itself.
https://github.com/uber-go/zap/blob/v1.10.0/config.go#L202
For some of our public operators, we would like to keep logs clean and tidy to improve readability/investigations for our customers
> log: add option to deactivate zap stack trace generation

- internal/generate/olm-catalog/package_manifest_test.go
Shorten line so that golangci-lint lll test passes
Fix CI
> internal/generate/olm-catalog/package_manifest_test.go: fix sanity test

- hack/tests/subcommand-scorecard.sh
- internal/scorecard/helpers/helpers.go
- internal/scorecard/helpers/test_definitions.go
- internal/scorecard/plugins/basic_tests.go
- internal/scorecard/plugins/olm_tests.go
- internal/scorecard/plugins/plugin_runner.go
- pkg/apis/scorecard/v1alpha2/formatter.go
- pkg/apis/scorecard/v1alpha2/types.go
this PR removes the merge/cumulative concept in scorecard, instead it inserts the CR name into the test result (and scorecard output) to distiguish test results between multiple CRs if specified by the scorecard end user.
merge/cumulative code was removed as part of this change.
With this change, you end up with more test output than before, with each CR producing test results (per CR).
> scorecard - refactor - remove merging of results, add CR name to output

- CHANGELOG.md
- internal/scaffold/ansible/entrypoint.go
- internal/scaffold/ansible/usersetup.go
- internal/scaffold/entrypoint.go
- internal/scaffold/entrypoint_test.go
- internal/scaffold/helm/entrypoint.go
- internal/scaffold/helm/usersetup.go
- internal/scaffold/usersetup.go
- internal/scaffold/usersetup_test.go
This PR updates entrypoint and user_setup scaffolds to remove the steps that add the runtime user to `/etc/passwd` _at runtime_.
These steps are not actually required to support containers running with dynamic UIDs.
Instead, we statically add the user to the image _at build time_ and ensure its files are read/writeable by the gid=0. The container runtime can set the GID of the runtime user to 0 when the container is started.
> internal/scaffold: don't change /etc/passwd perms

- doc/ansible/dev/advanced_options.md
- doc/ansible/user-guide.md
- test/ansible/deploy/crds/test.example.com_v1alpha1_inventory_cr.yaml
Metadata annotations must be string.
Value of `ansible.operator-sdk/verbosity` become string.
If you use numeric value on `ansible.operator-sdk/verbosity` on CR, you face following error.
```
resource.metadataOnlyObject.ObjectMeta: v1.ObjectMeta.Name: Annotations: ReadString: expects " or n, but found 3,
```
I've tried string value on `ansible.operator-sdk/verbosity`, it works.
> doc: ansible.operator-sdk/verbosity become string.

- README.md
Signed-off-by: Eran Cohen <eranco@redhat.com>
Use env var for username during the quick start guide, so that the quick start guide will require less editing
> Updated README.md, so that the quick start guide will require less editing

- internal/flags/watch/flags.go
- pkg/ansible/flags/flag.go
- pkg/helm/flags/flag.go
- rename wachFlags for Flags
Was decide not to do this change in the same pr where the lint was introduced. Even though watch.WatchFlags is an internal type, it is embedded in exported types, which means that changing it to watch.Flags is a breaking change which will not affect users since it is not used/exported to them.
> rename wachFlags for Flags

- .travis.yml
- hack/ci/check-doc-only-update.sh
Fix ci for when just docs were updated by not calling the skip shell to deploy the images. 
We merged a doc and the CI-job in the master to build `Docker image for helm-operator (ppc64le)` did not work. So, the change could not cause it. ( The issue is timeout in the process which is not returning a exit in 10 min . - any command execution which takes more than 10 min will be killed by Travis in the default config )
Here: https://travis-ci.org/operator-framework/operator-sdk/jobs/647499366
```
travis-ci.orgtravis-ci.org
Travis CI - Test and Deploy Your Code with Confidence
Travis CI enables your team to test and ship your apps with confidence. Easily sync your projects with Travis CI and you'll be testing your code in minutes. …
```
> fix ci for when just docs were updated

- CHANGELOG.md
- internal/scaffold/cmd.go
- internal/scaffold/cmd_test.go
- pkg/ansible/run.go
- pkg/helm/run.go
- test/test-framework/cmd/manager/main.go
- Add native support to MultiNamespace. More Info: https://godoc.org/github.com/kubernetes-sigs/controller-runtime/pkg/cache#MultiNamespacedCacheBuilder
- Integration with OLM: See that OLM allows and config the MultiNamespace via the option  `targetNamespaces` via the OperatorGroup. We are also in the olm commands setting these values in the WATCH-NAMESPACE EnvVar. 
- Address the requirements requested in tasks such as https://github.com/operator-framework/operator-sdk/issues/2494, https://github.com/operator-framework/operator-sdk/pull/2078, (which are a very common scenario in the channels: I as an operator dev, would like to deploy the operator in the nsA and WATCH the resources in the nsB and do not all cluster ), 
Closes …
> Scaffold code in `cmd/manager/main.go` for Go operators and add logic to Ansible/Helm operators to handle [multinamespace caching]

- doc/dev/developer_guide.md
- doc/user/install-operator-sdk.md
this change updates the minimum required go lang version in one of the developer docs, and also changes the method for downloading the source code. it should produce fewer warnings for developers wishing to install operator-sdk from source. it also adds a note about needing GOPROXY set to its default.
Inspired by warning messages found while investigating issue #2573, the proposed changes here produce fewer warnings during installation for developers.
> update instructions for building operator-sdk

- CHANGELOG.md
- cmd/operator-sdk/test/local.go
- doc/cli/operator-sdk_test_local.md
- doc/test-framework/writing-e2e-tests.md
- pkg/test/context.go
- pkg/test/framework.go
This flag (which is `false` by default) tells the framework whether to
skip the clean up (or do it) if the test encountered errors.
With the current behavior, the framework will always clean up the
resources it created. This is fine in most cases, however, in CI,
whenever there's an error, we might not get the logs of the workloads
and operator after the cleanup. So this option enables those resources
to linger until the logs have been acquired.
> Add skip-cleanup-on-errors option to `test local` command

- CHANGELOG.md
- cmd/operator-sdk/run/local.go
On Windows, we need to add the .exe suffix to the executable that is
generated by the operator-sdk run --local command, otherwise it will
fail because the file doesn't have an executable extension.
Closes #2480
> cmd/operator-sdk/run: use Windows binary suffix with '--local'

- OWNERS
Add varshaprasad96 to OWNERS file.
<!--
Before making a PR, please read our contributing guidelines https://github.com/operator-framework/operator-sdk/blob/master/CONTRIBUTING.MD
> [OWNERS] add varsha prasad narsing

- CHANGELOG.md
- pkg/ansible/controller/reconcile.go
Add event stats output to the operator logs for Ansible based-operators.
**Motivation**
Allow we remove the ansible container ( Related to #2007 )
>  Add event stats output to the operator logs for Ansible based-operators.

- CHANGELOG.md
- cmd/operator-sdk/migrate/cmd.go
- doc/ansible/dev/developer_guide.md
- doc/ansible/user-guide.md
- doc/migration/version-upgrade-guide.md
- hack/image/ansible/scaffold-ansible-image.go
- hack/tests/e2e-ansible.sh
- internal/scaffold/ansible/ao_logs.go
- internal/scaffold/ansible/deploy_operator.go
- internal/scaffold/ansible/dockerfilehybrid.go
- internal/scaffold/ansible/molecule_templates_operator.go
- test/ansible-memcached/verify.yml
- test/ansible/deploy/operator.yaml
- test/ansible/molecule/templates/operator.yaml.j2
- Improve the log in the operator to add the event stats 
- Remove the ansible sidecar container used just to provide the Ansible logs. 
- deprecated the inotify-tools usage in order to be able to remove it before 1.0.0
Closes #2007
> Deprecated `inotify-tools` on Ansible based-operator images and remove Ansible sidecar container.

- doc/ansible/user-guide.md
Add info over how to gen others CR/CRDs for the Ansible operators
Make clear that users are able to use N CR/CRDS in the Ansible operators project as well.
> add info over how to gen others CR/CRDs for the Ansible operators

- doc/operator-scope.md
The example YAMLs were missing `metadata.namespace`.
As a new user you need a complete working example. The current documentation was missing a crucial piece of information.
> Update instructions for cluster wide resource watching

- CHANGELOG.md
- doc/ansible/dev/developer_guide.md
- doc/ansible/user-guide.md
- pkg/ansible/controller/controller.go
- pkg/ansible/controller/reconcile.go
- pkg/ansible/events/log_events.go
- pkg/ansible/run.go
- Add full Ansible result output to the operator logs for Ansible based-operators configurable by EnvVar.
Allow users to have the same full information that can be obtained until the version 0.15.x with the Ansible sidecar container in the operator logs. 
Note that we deprecated the inotify-tools and we will no longer scaffold the sidecar container. See https://github.com/operator-framework/operator-sdk/pull/2586. Also, we have been improving the operator logs in order to attend all needs. See: https://github.com/operator-framework/operator-sdk/pull/2580 and https://github.com/operator-framework/operator-sdk/pull/2321.
**Local Test**
Image: quay.io/camilamacedo86/ansible-operator:logs
See the output with the ENV VAR:
```
$ …
```
> Improve operator logs by adding the possibility to get the full Ansible logs on it

- CHANGELOG.md
- cmd/operator-sdk/scorecard/cmd.go
- doc/cli/operator-sdk_scorecard.md
- doc/test-framework/scorecard.md
- Deprecated other extensions for the scorecard config file. We will just support YAML. 
- Update flags, errors and docs to make clear that the SDK will be looking for scorecard.yaml file. 
Error now: 
Help:
> deprecate extensions for scorecard config file

- internal/scaffold/helm/role.go
- internal/scaffold/helm/role_test.go
- pkg/ansible/proxy/proxy.go
- pkg/k8sutil/k8sutil.go
- pkg/kube-metrics/uclient.go
- Replace the usage `ServerResource` by `ServerGroupsAndResources`
- Follow up it changes in the SDK internal API implemented to make easier the tests. (See @joelanford comment https://github.com/operator-framework/operator-sdk/pull/2541#pullrequestreview-356731570)
**Motivation**
- The `ServerResources` is deprecated and then is required to use instead of ServerGroupsAndResources instead.
- Solve technical debts in the project before 1.0.0
Note: deprecations occurred in client-go kubernetes-1.14.0.
> fix: kclient.Discovery() deprecations

- CHANGELOG.md
- doc/test-framework/scorecard.md
- internal/scorecard/plugins/plugin_runner.go
- internal/scorecard/plugins/resource_handler.go
make the scorecard cleanup use the init-timeout configuration setting when doing its cleanup, this will allow operators that specify a finalizer to have time to perform their cleanup based on a configurable value instead of the previous hard-coded value.
Closes #2094
> Scorecard finalizer fix

- CHANGELOG.md
- doc/test-framework/writing-e2e-tests.md
- pkg/test/context.go
- pkg/test/context_test.go
- pkg/test/framework.go
- pkg/test/resource_creator.go
- test/e2e/_incluster-test-code/memcached_test.go
- test/e2e/tls_util_test.go
- test/test-framework/test/e2e/memcached_test.go
- Deprecated `test.TestCtx` in order to rename test.TestCtx to test.Context
- Following the good practices since we should not have `test.Test`;
- Be able to rename the API before 1.0.0
- Solve tech-debts
> Deprecated test.TestCtx in order to rename test.TestCtx to test.Context

- doc/user/olm-catalog/operator-bundles.md
**Description of the change:** doc describing `bundle create` and `bundle validate`.
**Motivation for the change:** reason d'etre for these commands is undocumented.
Closes #2442 
> operator bundle docs

- cmd/operator-sdk/execentrypoint/ansible.go
- doc/ansible/dev/advanced_options.md
- doc/ansible/dev/finalizers.md
- doc/ansible/user-guide.md
- hack/tests/e2e-ansible-molecule.sh
- pkg/ansible/flags/flag.go
- pkg/ansible/watches/testdata/invalid_collection.yaml
- pkg/ansible/watches/testdata/valid.yaml.tmpl
- pkg/ansible/watches/watches.go
- pkg/ansible/watches/watches_test.go
- test/ansible-memcached/molecule.yml
- test/ansible/build/Dockerfile
- test/ansible/deploy/crds/test.example.com_collections_crd.yaml
- test/ansible/fixture_collection/galaxy.yml
- test/ansible/fixture_collection/roles/dummy/tasks/main.yml
- test/ansible/molecule/cluster/tasks/collections_test.yml
- test/ansible/molecule/cluster/verify.yml
- test/ansible/requirements.yml
- test/ansible/watches.yaml
~Just a POC at the moment, roles only, no playbooks.~ Note: Playbooks are not yet fully supported within collections.
Allow Ansible watches to use collection roles
Ansible-based operators can now specify roles in `watches.yaml` by their
fully qualified collection name, ie `myNamespace.myCollection.myRole`.
> Allow Ansible watches to use collection roles

- CHANGELOG.md
- doc/helm/user-guide.md
- pkg/helm/controller/controller.go
- pkg/helm/flags/flag.go
- pkg/helm/run.go
Adds --max-workers flag to the exec-entrypoint helm command
Currently the helm operator runs with just 1 worker. Reconciling helm releases can sometime take >1 second, using a single worker will not be able to keep up for more than 60 CRs of the same type.
> Adds --max-workers flag to the exec-entrypoint helm command

- doc/test-framework/writing-e2e-tests.md
Add docs text explaining why e2e operator tests *must* use the testing framework's MainEntry function.
e2e tests that do not use the framework MainEntry function cause confusing errors when attempting to run your test, the source of which is not obvious. See #1908.
Closes #1908
> Add docs about not running e2e testing m directly

- doc/user-guide.md
- internal/scaffold/cmd.go
- internal/scaffold/cmd_test.go
- test/test-framework/cmd/manager/main.go
- Update the docs and scaffold to make clear how works the metrics and what is required to do for third party API's. 
Closes #2577
Closes #1858
> Update the docs and scaffold to make clear how works the metrics and what is required to do for third party API's. 

- CHANGELOG.md
- internal/scaffold/cmd.go
- internal/scaffold/cmd_test.go
- pkg/ansible/run.go
- test/test-framework/cmd/manager/main.go
- Fix `ServiceMonitor` creation when the operator is cluster-scoped and the environment variable `WATCH_NAMESPACE` has not as value the namespace where the operator was deployed.
- Update mock data ( test-framework ) with the latest version of the main.go.  
Closes: #2602
See: https://github.com/operator-framework/operator-sdk/issues/2494#issuecomment-591600356
>  fix: creation of monitor service when operator is cluster-scoped

- doc/ansible/dev/advanced_options.md
Update doc with openAPI validations for Ansible based operators
Closes #2036
> doc: add info over openAPI validations for Ansible based operators

- doc/migration/version-upgrade-guide.md
- doc/sdk-cli-reference.md
- Remove `--watches-file` and its example for the command `run` from sdk cli doc since it is outdated. 
- Add further information in the migration doc over break changing in the run command. 
Closes #2615
> doc : update docs regards  break changing in the run command

- doc/migration/version-upgrade-guide.md
- Add info over changes in the default scaffold in the main.go file to address bug fixes and improvements. 
NOTE: It can just be merged after we merge: https://github.com/operator-framework/operator-sdk/pull/2606, https://github.com/operator-framework/operator-sdk/pull/2603, https://github.com/operator-framework/operator-sdk/pull/2601
> Add to migration doc steps regards changes over metrics to the scaffolded files.

- CHANGELOG.md
- doc/test-framework/scorecard.md
- images/scorecard-proxy/cmd/proxy/main.go
- internal/scorecard/interfaces.go
- internal/scorecard/plugins/config.go
- internal/scorecard/plugins/plugin_runner.go
- internal/scorecard/plugins/resource_handler.go
this change adds a proxy-port configuration setting for the scorecard
scorecard users can use a port other than the default, 8889, if they set the proxy-port configuration setting for the scorecard.
> Scorecard - add proxy port configuration setting

- cmd/operator-sdk/generate/csv.go
Modify error message by including the file path.
Currently, if there is error during unmarshalling of crds in the
deploy/crds folder, the error returned by generate-csv command
is unclear as it does not include any filename. This PR modifies
the error message to include the filepath.
> [fix]: include filename in the error returned by generate-csv command

- pkg/ansible/proxy/cache_response.go
- pkg/ansible/proxy/inject_owner.go
Some of the logging messages do not have any error context included, I added that in.
No change in the logic.
Related https://github.com/operator-framework/operator-sdk/issues/2623
In looking at the issue, I noticed that we were missing the error contexts for these log messages.
> Add error context to log messages

- doc/user/client.md
Update the patch examples in order to function as expected.
With current the patch examples provided, no changes would actually occur when patching because the patch was being applied to the modified object instead of a copy of the original.
> Update client.md incorrect patch examples

- CHANGELOG.md
- doc/ansible/dev/apb_migration_guide.md
- doc/ansible/dev/developer_guide.md
- doc/ansible/dev/retroactively-owned-resources.md
- doc/ansible/dev/testing_guide.md
- doc/ansible/user-guide.md
- internal/scaffold/ansible/dockerfilehybrid.go
- internal/scaffold/ansible/molecule_cluster_destroy.go
- internal/scaffold/ansible/molecule_cluster_playbook.go
- internal/scaffold/ansible/molecule_cluster_prepare.go
- internal/scaffold/ansible/molecule_cluster_verify.go
- internal/scaffold/ansible/molecule_test_local_playbook.go
- internal/scaffold/ansible/playbook.go
- internal/scaffold/ansible/roles_meta_main.go
- test/ansible-memcached/memfin/tasks/main.yml
- test/ansible-memcached/secret/tasks/main.yml
- test/ansible-memcached/tasks.yml
- test/ansible-memcached/verify.yml
- test/ansible/build/Dockerfile
- test/ansible/fixture_collection/roles/dummy/tasks/main.yml
- test/ansible/molecule/cluster/playbook.yml
- test/ansible/molecule/cluster/verify.yml
- test/ansible/molecule/test-local/playbook.yml
- test/ansible/roles/inventory/tasks/main.yml
Updates scaffolded code and tests to use the Kubernetes modules from the Kubernetes Ansible collection instead of Ansible core. Existing code should work for the time being, so no immediate steps are required for existing users, though it is recommended they switch to using the collection to continue getting new fixes and features.
Active module development has moved to the [Kubernetes Ansible collection](https://github.com/ansible-collections/kubernetes). At some point in the future, support for the Kubernetes modules in Ansible core may be removed.
> Use the Kubernetes Ansible collection

- doc/ansible/user-guide.md
- `reconcilePeriod` must have a time unit, added the same in the example
- `deploy/operator.yaml` - Fixed the sed commands to replace values of `image` and `imagePullPolicy`
- `roles/memcached/tasks/main.yml` - Replaced `community.kubernetes.k8s:` with `k8s:` as the former throws below error
```sh
ERROR! couldn't resolve module/action 'community.kubernetes.k8s'. This often indicates a misspelling, missing collection, or incorrect module path.                                                                                                      │
│ The error appears to be in '/opt/ansible/roles/memcached/tasks/main.yml': line 2, column 3, but may …
```
> docs: fixed a bunch of things in the docs

- CHANGELOG.md
- pkg/ansible/controller/reconcile.go
- pkg/ansible/controller/reconcile_test.go
The reconcile was not marking the CR status when no event status is returned.  
Closes #2565
**Local Test**
> fix: CR has not error faced in the task

- CHANGELOG.md
- pkg/ansible/runner/runner.go
- pkg/ansible/runner/runner_test.go
- test/ansible/deploy/crds/test.example.com_v1_inventorytest_cr.yaml
- test/ansible/deploy/crds/test.example.com_v1alpha1_inventory_cr.yaml
- Fix ansible verbosity annotation
Note: If this PR is fixing an issue make sure to add a note saying:
Closes #2627
> fix: ansible verbosity

- CHANGELOG.md
- doc/migration/version-upgrade-guide.md
- internal/scaffold/ansible/go_mod.go
- internal/scaffold/go_mod.go
- internal/scaffold/helm/go_mod.go
- version/version.go
updates the v0.16.x branch as part of post release steps
part of release process
> v0.16.x post release branch setup

- hack/check-doc-diffs.sh
- hack/tests/sanity-check.sh
Adds a sanity check to compare diffs between `./doc` and `./website`. If there are changes to `./doc`, we expect _something_ to change in `./website`.
While we're transitioning to a new docs site, we need to make sure that the docs stay in sync between the current GitHub-based docs in `./doc` and the new docs site docs in `./website`
> hack: add sanity check for doc diffs

- Makefile
Now that CI has been updated, we no longer need the slashed targets.
> remove the remaining slashes from targets

- CHANGELOG.md
- internal/scorecard/plugins/resource_handler.go
this PR fixes a situation where an operator being tested with scorecard, creates CRs in its implementation (seeded), this would cause scorecard to fail since it was trying to create the same CRs already seeded.  With this change, if a CR is already created, the scorecard will just print a message to the user to let them know when a CR already exists.
Closes #2677
> add already exists check in object creation

- CHANGELOG.md
- cmd/operator-sdk/new/cmd.go
- cmd/operator-sdk/olm/status.go
- doc/cli/operator-sdk_cleanup.md
- doc/cli/operator-sdk_new.md
- doc/cli/operator-sdk_olm_status.md
- doc/cli/operator-sdk_run.md
- internal/olm/client.go
- internal/olm/client/client.go
- internal/olm/manager.go
- internal/olm/operator/manager.go
- internal/olm/operator/operator.go
- test/integration/operator_olm_test.go
- website/content/en/docs/cli/operator-sdk_cleanup.md
- website/content/en/docs/cli/operator-sdk_new.md
- website/content/en/docs/cli/operator-sdk_olm_status.md
- website/content/en/docs/cli/operator-sdk_run.md
- Add `--olm-namespace` flag to to `operator-sdk run --olm` command
- Add `--olm-namespace` flag to `operator-sdk olm status` command
- Add `--olm-namespace` flag to `operator-sdk cleanup` command
This fixes the bug where running these commands against a openshift 4.x cluster would fail because in those clusters the OLM is installed in `namesapce: openshift-operator-lifecycle-manager` and the code always defaulted to default `namespace: olm`. Its now fixed by adding a new flag `--olm-namespace` that allows to override the default namespace(olm).
Closes: https://github.com/operator-framework/operator-sdk/issues/2595
**Example usage**
```
$ operator-sdk olm status --olm-namespace openshift-operator-lifecycle-manager
$ …
```
> Add `--olm-namespace` flag to OLM related subcommands

- doc/migration/version-upgrade-guide.md
- website/content/en/docs/migration/version-upgrade-guide.md
- Add missing info for 0.16 migration guide (breaking changes emerge before the agreement to started to update it with the prs + module)
> doc(migration guide) :add info regards 0.16 sdk version

- doc/test-framework/writing-e2e-tests.md
- website/content/en/docs/test-framework/writing-e2e-tests.md
Add docs about the needed permissions for running e2e operator tests.
As discussed in #1082 this is useful information for users in environments where they might not be running as cluster-admin by default.
Closes #1082
> Add docs about needed cluster roles for e2e operator tests

- website/config.toml
This PR does not solve https://github.com/operator-framework/operator-sdk/issues/2708, but does add a placeholder with value.
Master -> relative link, /docs
0.16 -> GitHub docs tree for 0.16.x branch
> Add releases tab, point to current gh docs

- CHANGELOG.md
- internal/scaffold/olm-catalog/descriptor/descriptor_test.go
- internal/scaffold/olm-catalog/descriptor/search.go
- test/test-framework/deploy/crds/cache.example.com_dummys_crd.yaml
- test/test-framework/pkg/apis/cache/v1alpha1/dummy_types.go
Add support for path detection of arrayFieldGroup spec descriptors during CSV generation
Closes #2700
> CSV Generation: support path detection for arrayFieldGroups

- CHANGELOG.md
- pkg/ansible/runner/runner.go
- pkg/ansible/runner/runner_test.go
Resources with '-' in the APIGroup now are properly formatted when
passed to Ansible. For example
```
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
```
will now result in a variabled called
`_cert_manager_io_certificaterequest`
instead of
`_cert-manager_io_certificaterequest`
Fixes #2486
> Properly handle resources with '-' in the group name

- CHANGELOG.md
- pkg/ansible/proxy/cache_response.go
- pkg/ansible/proxy/kubectl.go
- pkg/ansible/proxy/proxy.go
- test/ansible/deploy/crds/test.example.com_collectiontests_crd.yaml
- test/ansible/deploy/crds/test.example.com_exectests_crd.yaml
- test/ansible/deploy/crds/test.example.com_inventorytests_crd.yaml
- test/ansible/deploy/crds/test.example.com_v1alpha1_inventorytest_cr.yaml
- test/ansible/deploy/role.yaml
- test/ansible/molecule/cluster/tasks/collections_test.yml
- test/ansible/molecule/cluster/tasks/exec_test.yml
- test/ansible/molecule/cluster/tasks/inventory_test.yml
- test/ansible/molecule/templates/operator.yaml.j2
- test/ansible/molecule/test-local/playbook.yml
- test/ansible/playbooks/exec.yml
- test/ansible/watches.yaml
Allows exec requests to go through the proxy without error
It was impossible to make exec requests from Ansible code without circumventing the proxy
fixes #2204
> Fix exec in proxy

- pkg/ansible/proxy/cache_response.go
- pkg/ansible/proxy/inject_owner.go
- pkg/ansible/proxy/proxy.go
- website/content/en/docs/ansible/dev/webhooks.md
Adds documentation explaining how to use a webhook with an Ansible-based Operator.
Also fixes the proxy so that it can be used by sidecar containers
https://github.com/operator-framework/operator-sdk/issues/1658
> Add guide explaining how to use webhooks with Ansible-based Operators

- doc/user-guide.md
- website/content/en/docs/user-guide.md
**Description of the change:** fix typo and remove redundant section on metrics type filtering.
**Motivation for the change:** The two paragraphs discussing registering types for metrics are redundant and the first paragraph contains more specific information.
> doc/user-guide.md: fix typo and remove redundant section

- doc/migration/version-upgrade-guide.md
- website/content/en/docs/migration/version-upgrade-guide.md
Fixes a small typo in the `v0.16.x` upgrade guide.
While working through the upgrade to `v0.16.0` I encountered this issue and reported the bug.
Closes #2733
> doc: fix typo in v0.16.x upgrade guide

- CHANGELOG.md
- pkg/test/framework.go
- pkg/test/main_entry.go
- test/e2e/_incluster-test-code/main_test.go
* pkg/test: only register `--kubeconfig` if not registered, get value if already registered
**Motivation for the change:** controller-runtime currently adds the `--kubeconfig` flag if `pkg/client/config` is imported (set up in an `init()` function). The SDK's test framework also adds this flag, which will panic if both packages are imported and the test framework is initialized.
Closes: https://github.com/kubernetes-sigs/controller-runtime/issues/878
/cc @joelanford @camilamacedo86 @DirectXMan12 @akoserwal
/kind bug
> test framework: handle double-registered `--kubeconfig` flag

- cmd/operator-sdk/internal/genutil/k8s.go
If the user's `GOROOT` does not match the `GOROOT` used to build the binary, they would be required to explicitly set the `GOROOT` env variable:
```bash
export GOROOT=$(go env GOROOT)
```
To avoid this step for end-users we can explicitly pull the `GOROOT` from `go env` and explicitly set the `GOROOT` env variable prior to generation code executing.
Closes #2744
> cmd/operator-sdk/internal: explicitly set GOROOT

- CHANGELOG.md
- doc/ansible/dev/testing_guide.md
- internal/scaffold/ansible/molecule_default_molecule.go
- internal/scaffold/ansible/molecule_test_local_molecule.go
- test/ansible-memcached/molecule.yml
- test/ansible/molecule/test-local/molecule.yml
- website/content/en/docs/ansible/testing-guide.md
Upgrade Kind used for tests for Ansible based-operators from `1.16` to `1.17`.
Closes #2665
> Upgrade ansible kind from 1.16 to 1.17

- .travis.yml
**Description of the change:** organize all image build/push jobs under deploy stage
**Motivation for the change:** arm64 images should only be built/pushed from master merges
Follow-up from #2742
> .travis.yml: organize arm64 travis job under deploy stage

- cmd/operator-sdk/alpha/cmd.go
- cmd/operator-sdk/alpha/scorecard/cmd.go
- cmd/operator-sdk/alpha/scorecard2/cmd.go
Adds hidden skeleton command and needed flags for the updated scorecard system to the alpha commands group.
> Add Skeleton Command for Scorecard 2

- CHANGELOG.md
- pkg/status/conditions.go
- pkg/status/conditions_test.go
Convert conditions from a map to a slice.
Workaround CRD generation issue that caused the conditions validation section of the CRD to have incorrect fields.
Closes #2658
> pkg/status: use conditions slice instead of map

- Makefile
This PR changes the `TEST_PKGS` Makefile variable to only be evaluated when used.
I noticed that the Travis task for running the markdown checks was unnecessarily fetching the Go dependencies for the project, which takes several minutes.
This variable was being evaluated on every invocation of `make`. Now it is evaluated only when used so other make targets that don't require Go dependencies to be present will be much faster in CI
> Makefile: speed up make tasks that don't require Go deps

- internal/scorecard/alpha/config.go
this PR is for the alpha scorecard implementation, it contains the configuration Struct for the scorecard.  This configuration file defines the test configurations scorecard will process.  
Scorecard users will create a YAML configuration file that will map to this Struct and scorecard will
read this configuration file when executed.  Here is a sample snippet of the ScorecardConfig yaml text representation:
```
tests:
- image: quay.io/jemccorm/customtest1:v0.0.1
labels:
suite: custom
test: customtest1
description: an ISV custom test that does...
- image: quay.io/jemccorm/customtest2:v0.0.1
labels:
suite: custom
test: customtest2
description: an ISV custom test that does...
- image: quay.io/redhat/basictests:v0.0.1
entrypoint: basic-check-spec
labels:
suite: …
```
> added alpha scorecard config struct

- cmd/operator-sdk/bundle/create.go
- doc/cli/operator-sdk_bundle_create.md
- website/content/en/docs/cli/operator-sdk_bundle_create.md
Signed-off-by: dmesser <dmesser@redhat.com>
Bundle creation CLI docs are missing code format. Addresses #2772
> Bundle creation docs are missing code format

- cmd/operator-sdk/alpha/scorecard/cmd.go
- internal/scorecard/alpha/config.go
- internal/scorecard/alpha/config_test.go
- internal/scorecard/alpha/labels_test.go
- internal/scorecard/alpha/scorecard.go
this is the initial label processing of the alpha scorecard, it selects the tests to be run
by the selector flag value passed in.  At this point since the tests are not written, the 
test name and test labels are printed only instead of the actual test being run.
part of the larger alpha scorecard  implementation, this PR is focused on adding the
selector logic only.
> Scorecard2 label processing

- CHANGELOG.md
- go.mod
- go.sum
- pkg/helm/release/manager.go
- pkg/helm/release/manager_test.go
- test/test-framework/go.sum
This PR updates the jsonpatch library to fix an issue during reconciliation of arrays.
The old version had an incomplete implementation for json patches of arrays.
A diff between
```
containers:
- name: container1
- name: container2
```
and
```
containers:
- name: container1
```
created 3 patch operations:
- remove containers/0
- remove containers/1
- add containers/0
This causes an issue because we are ignoring all "remove" operations to allow manual modifications.
Helm tries to apply
```
containers:
- name: container1
- name: container2
- name: container1
```
```
invalid: spec.template.spec.containers[0].name: Duplicate value:
"container1"
```
The new jsonpatch version does only return a `remove containers/1`
operation (which we are still ignoring because it could be a manual
change, …
> [helm-operator] Fix reconciliation of resources with jsonpatch

- internal/util/projutil/project_util.go
Project type detection will now detect Ansible if one of `roles/`, `molecule/` or `requirements.yml` are present at the project root.
closes #2726
> Look for more than just roles when detecting project type for Ansible-based Operators

- CHANGELOG.md
Change links in CHANGELOG.md to point to new CLI location
To get PRs passing again in CI :)
> Fix CHANGELOG links pointing to ./doc/cli

- .travis.yml
**Description of the change:** use before_script as to not override test.before_install in .travis.yml
**Motivation for the change:** Go tests no longer respect docs-only check
> .travis.yml: use before_script as to not override test.before_install

- CHANGELOG.md
- doc/helm/user-guide.md
- pkg/helm/controller/reconcile.go
- pkg/helm/release/manager.go
- website/content/en/docs/helm/reference/advanced_features.md
This PR adds a new annotation to the CR for helm releases to use `helm
upgrade --force`.
> [helm-operator] Add annotation to use helm upgrade force 

- images/scorecard-proxy/bin/user_setup
- internal/scaffold/ansible/usersetup.go
- internal/scaffold/helm/usersetup.go
- internal/scaffold/usersetup.go
- internal/scaffold/usersetup_test.go
- test/test-framework/build/bin/user_setup
sh/bash best practice is to always use double quotes when interpolating
strings from variables.  This commit updates the user_setup scripts to
do this.  They now pass shellcheck linting
Add double quotes around interpolated arguments in user_setup shell scripts 
- Follow shell best practices
- Get a feel for this community and whether it's worth investing time helping out with things big and small in the future
- Something to do on a Saturday during a worldwide pandemic, while learning how to write operators
- Satisfy my OCD
> user_setup scripts: add double quotes

- pkg/predicate/predicate.go
- test/ansible/molecule/cluster/tasks/secrets_test.yml
- test/ansible/playbooks/secret.yml
- test/ansible/watches.yaml
Fixes #2108
If the `metadata.generation` is `0`, the event will now still trigger a
reconciliation.
> Resources without generation will not skip events

- doc/user/olm-catalog/olm-cli.md
- website/content/en/docs/golang/olm-integration/olm-cli.md
fixes a small type-o in an sdk olm run example.
small doc fix only.
> fix type-o in olm run command example

- Makefile
- hack/image/build-scorecard-test-image.sh
- images/scorecard-test/Dockerfile
- images/scorecard-test/bin/entrypoint
- images/scorecard-test/bin/user_setup
Create base image to support new scorecard system. Adds image build/push to Makefile (not enabled by default), a script to generate images and the base image dockerfile. Future additions will include building and executing the test binary as well as passing along test selection data to the test binary.
> Implement Scorecard 2 Base Image

- Makefile
Fix Makefile targets for generate scripts.
#2761 moved the ./hack/generate/ scripts down one level after introducing another main Go file
> Makefile: fix script paths for 'gen-*' make targets

- changelog/fragments/helm-rm-default-api-version.yaml
- internal/scaffold/helm/chart.go
Changed default API version for new Helm-based operators to `helm.operator-sdk/v1alpha1`. 
The `k8s.io` domain is reserved, so CRDs should not use it without explicit appproval.
> internal/scaffold/helm/chart.go: change default API version

- CHANGELOG.md
- changelog/fragments/fix-issue-2393.yaml
- pkg/ansible/paramconv/paramconv.go
- pkg/ansible/paramconv/paramconv_test.go
Fix snake conversion
Closes #2393
> Fix snake conversion 

- doc/user/unit-testing.md
- website/content/en/docs/golang/unit-testing.md
- website/content/en/docs/scorecard/_index.md
- remove index in order to keep all docs following the same standard
- fix broken links
**Example**
> remove index in order to keep all docs following the same standard

- changelog/fragments/fix-issue-bug-1701041.yaml
- pkg/ansible/proxy/cache_response.go
- pkg/ansible/proxy/proxy.go
Add timeout in the watch feature for Ansible based-operators proxy to avoid appears that the reconcile is stuck and hang when the operator has not the correct permissions to List and Watch the resources. 
- https://github.com/operator-framework/operator-sdk/pull/1638
- https://bugzilla.redhat.com/show_bug.cgi?id=1701041
**Note**
Also, solved by https://github.com/kubernetes-sigs/controller-runtime/pull/663. 
**Steps to test it locally**
- Build an ansible image with this PR
- Use the image in an ansible POC ( can be the Memchaced sample )
- Remove the required permission to perform some operations defined in the playbook/roles. E.g to create a resource. 
- After installing the CR which will call the playbook/role check in the …
> Adding context timeout for Ansible proxy

- website/content/en/docs/kubebuilder/migration/project_migration_guide.md
Add project migration doc for single api version operator. The guide explains the steps required to migrate an operator built using Operator-SDK to kubebuilder project layout.
> [doc] Add project migration doc for single api version operator

- changelog/fragments/2884-fix.yaml
- pkg/helm/controller/reconcile.go
- pkg/helm/controller/reconcile_test.go
helm: pass `force` to strconv.ParseBool() instead of `helmUpgradeForceAnnotation`
Fixes issue where helm.operator-sdk/upgrade-force annotation value is not being respected
Closes #2884
> bugfix: pass annotation value to strconv.ParseBool

- changelog/fragments/crd-default-v1.yaml
- internal/generate/crd/crd.go
- test/test-framework/deploy/crds/cache.example.com_memcachedrs_crd.yaml
- test/test-framework/deploy/crds/cache.example.com_memcacheds_crd.yaml
- website/content/en/docs/cli/operator-sdk_add_api.md
- website/content/en/docs/cli/operator-sdk_add_crd.md
- website/content/en/docs/cli/operator-sdk_generate_crds.md
- website/content/en/docs/cli/operator-sdk_new.md
Changed the default CRD version from `apiextensions.k8s.io/v1beta1` to `apiextensions.k8s.io/v1` for commands that create or generate CRDs.
`v1beta1` CRDs will be removed in Kubernetes v1.19, which is the next release. We need to help users start migrating from `v1beta1` to `v1` CRDs.
> internal/generate/crd: change default CRD to v1

- website/content/en/docs/kubebuilder/quickstart.md
Add docs for enabling status subresource in the kubebuilder quickstart guide.
Resolves the error I saw in https://github.com/operator-framework/operator-sdk/pull/2827#issuecomment-613846192 where the controller failed to update the status subresource with the status writer client.
https://github.com/operator-framework/operator-sdk/blob/master/example/kb-memcached-operator/memcached_controller.go.tmpl#L114
> kubebuilder/quickstart: add instruction for enabling status subresource

- hack/generate/changelog/util/fragment.go
- hack/generate/changelog/util/fragment_test.go
Use `sigs.k8s.io/yaml` instead of `gopkg.in/yaml.v2` in `./hack/generate/changelog`
Trying to make SDK use `sigs.k8s.io/yaml` consistently.
> hack/generate/changelog: use sigs.k8s.io/yaml

- website/content/en/docs/contribution-guidelines/backport-policy.md
- add backport policy
Discussion in Eng, Forum
> doc: add backport policy

- website/config.toml
Configure Hugo to ignore WIP kubebuilder docs
Keep Kubebuilder docs out of site until KB integration is ready.
> website: ignore kubebuilder docs

- .gitignore
- cmd/operator-sdk/alpha/scorecard/cmd.go
- hack/image/build-scorecard-test-image.sh
- images/scorecard-test/Dockerfile
- images/scorecard-test/cmd/test/main.go
- internal/scorecard/alpha/bundle.go
- internal/scorecard/alpha/config.go
- internal/scorecard/alpha/config_test.go
- internal/scorecard/alpha/formatting.go
- internal/scorecard/alpha/kubeclient.go
- internal/scorecard/alpha/labels_test.go
- internal/scorecard/alpha/scorecard.go
- internal/scorecard/alpha/tar.go
- internal/scorecard/alpha/testconfigmap.go
- internal/scorecard/alpha/testdata/config.yaml
- internal/scorecard/alpha/testdata/pod.yaml
- internal/scorecard/alpha/testpod.go
- internal/scorecard/alpha/tests/basic.go
- internal/scorecard/alpha/tests/bundle_test.go
- internal/scorecard/alpha/tests/crhelper.go
- internal/scorecard/alpha/tests/olm.go
- internal/scorecard/alpha/tests/test_bundle.go
this PR adds functionality to the alpha scorecard implementation, you can test
this PR out by running the following command as an example:
```
operator-sdk alpha scorecard \
--config=internal/scorecard/alpha/testdata/config.yaml \
--selector=suite=basic \
-o json \
--bundle=internal/scorecard/alpha/testdata/bundle/ \
--cleanup=true
```
this PR includes the following:
* creates a ConfigMap that holds the on-disk bundle contents, this ConfigMap is passed to test pods
* test pods are created by the scorecard for selected tests
* test pod logs are fetched and converted into Scorecard test output for viewing results
* output is formatted into json or text as the case with the current scorecard
* a cleanup flag is optional if you want to have access to the test …
> Scorecard2 pod execution

- go.mod
- go.sum
- internal/plugins/golang/config.go
- internal/plugins/golang/init.go
**Description of the change:** bump kubebuilder commit to https://github.com/kubernetes-sigs/kubebuilder/commit/d6e2b995831ce26228f2303e9d1b3a55acd3d225, merge commit for plugins into master.
**Motivation for the change:** plugins in kubebuilder master.
> go.mod: bump kubebuilder to a master commit for plugins

- changelog/fragments/2944-change.yaml
- cmd/operator-sdk/bundle/cmd.go
- cmd/operator-sdk/bundle/create.go
- cmd/operator-sdk/bundle/validate.go
- cmd/operator-sdk/generate/csv.go
- hack/lib/test_lib.sh
- hack/tests/subcommand-bundle.sh
- internal/generate/olm-catalog/package_manifest.go
- internal/generate/olm-catalog/package_manifest_test.go
- internal/generate/testdata/non-standard-layout/expected-catalog/olm-catalog/memcached-operator/memcached-operator.package.yaml
- website/content/en/docs/cli/operator-sdk.md
- website/content/en/docs/cli/operator-sdk_bundle.md
- website/content/en/docs/cli/operator-sdk_bundle_create.md
- website/content/en/docs/cli/operator-sdk_bundle_validate.md
- website/content/en/docs/cli/operator-sdk_generate_csv.md
- website/content/en/docs/olm-integration/generating-a-csv.md
- website/content/en/docs/olm-integration/user-guide.md
**Description of the change:** remove deprecation notices and comments for package manifests format generation
**Motivation for the change:** operator authors should be able to manage the operator-registry manifests format using the SDK, since it is still supported by operator-registry servers.
> generate csv: de-deprecate package manifests format

- cmd/operator-sdk/alpha/scorecard/cmd.go
- internal/scorecard/alpha/bundle.go
- internal/scorecard/alpha/config.go
- internal/scorecard/alpha/formatting.go
- internal/scorecard/alpha/labels_test.go
- internal/scorecard/alpha/scorecard.go
- internal/scorecard/alpha/testconfigmap.go
- internal/scorecard/alpha/testpod.go
pod execution refinement, this PR adds a --parallel flag and lets the user run tests in parallel if they choose to, the default is serial and NOT parallel.  This PR also cleans up a lot of the pod
execution code.
part of the overall scorecard2 work, this one deals with pod execution mostly.
> Scorecard2 pod exec3

- pkg/apis/scorecard/v1alpha2/formatter.go
Uniformly indents the log field when using the text output method
tests with long logs were difficult to parse visually because only the first line of the log would be indented
> Uniformly indent log in text output for readability

- internal/scorecard/alpha/testdata/bundle/manifests/memcached-operator.v0.0.1.clusterserviceversion.yaml
- internal/scorecard/alpha/tests/olm.go
Migrates the scorecard test for spec descriptor validation to the scorecard2 pattern
> Add Scorecard2 spec descriptor validation test

- internal/scorecard/alpha/testdata/bundle/manifests/memcached-operator.clusterserviceversion.yaml
- internal/scorecard/alpha/tests/bundle_test.go
- internal/scorecard/alpha/tests/olm.go
Migrate scorecard test for checking if CRDs have resources.
> [scorecard] add test to check if CRDs have resources

- changelog/fragments/2729-addition.yaml
- go.mod
- go.sum
- internal/generate/olm-catalog/csv.go
- internal/generate/olm-catalog/csv_updaters.go
- internal/generate/testdata/go/deploy/olm-catalog/memcached-operator/0.0.2/memcached-operator.v0.0.2.clusterserviceversion.yaml
- internal/generate/testdata/go/deploy/olm-catalog/memcached-operator/0.0.3/memcached-operator.v0.0.3.clusterserviceversion.yaml
- internal/generate/testdata/go/deploy/olm-catalog/memcached-operator/manifests/memcached-operator.clusterserviceversion.yaml
- internal/generate/testdata/go/deploy/olm-catalog/memcached-operator/noupdate/memcached-operator.v0.0.3.clusterserviceversion.yaml
- internal/generate/testdata/go/deploy/webhooks/cache-example-com-v1alpha1-memcached.webhook.yaml
**Description of the change:** `generate csv` adds validating and mutation webhooks to a CSV by reading their config manifests from a deploy dir.
**Motivation for the change:** OLM will support generating [admission webhooks](https://github.com/operator-framework/operator-lifecycle-manager/pull/1102) for operators soon. The CSV generator should support adding them to new and existing CSV's.
~Contains some changes that are nice-to-have from #2511 and necessary changes from #2730~
~Blocked by https://github.com/operator-framework/operator-lifecycle-manager/pull/1436~
/kind feature
> generate csv: support validating and mutating webhooks

- website/content/en/docs/kubebuilder/quickstart.md
**Description of the change:** add note on changing the default "runner" image from distroless to something else.
**Motivation for the change:** changing the default image is not obvious for the new SDK project layout like it is for the current layout.
> docs/kubebuilder/quickstart: note on changing base runner image

- website/content/en/docs/golang/quickstart.md
- website/content/en/docs/kubebuilder/advanced-topics.md
This is fix remove func inside Operator SDK documentation
func remove(...) could occurs slice bounds out of range exception even list contains more than one same entities
> Fix add and process finalizers implementation in docs

- changelog/fragments/2964-bugfix.yaml
- hack/tests/integration.sh
- internal/olm/operator/internal/configmap.go
- internal/olm/operator/internal/deployment.go
- internal/olm/operator/internal/registry.go
- internal/olm/operator/manager.go
- internal/util/k8sutil/k8sutil.go
- test/integration/integration_helpers.go
- test/integration/operator_olm_test.go
* internal/olm/operator: create one ConfigMap per package in a package manifests format, and deploy the registry with all ConfigMaps mounted
**Motivation for the change:** the package manifests format must be replicated in a pod's file system for consistent registry initialization.
Closes #2923 
/kind bug
> run --olm: create one ConfigMap per package

- changelog/fragments/2969-bugfix.yaml
- internal/olm/client/client.go
**Description of the change:** use indexed CSV in list instead of an iterator value in `internal/olm/client.Client.GetInstalledVersion`.
**Motivation for the change:** if more than one CSV is installed in OLM's namespace, as is the case in some k8s distros, the list operation in `GetInstalledVersion` will return multiple CSV's. The bug resulted in the last CSV in the returned list, not necessarily the packageserver's, to be inspected for OLM's version.
/kind bug
/cc @raffaelespazzoli
> OLM client: correctly get packageserver version

- website/layouts/index.html
This fixes various typos on the main page of the website which is
located at website/layouts/index.html
Fixes #2973
Fixing of typos in various \<p\> tags on the above mentioned HTML page.
Always better to not have typos!
> website: Fix typos on the main page

- changelog/fragments/interactive-csv-cmd.yaml
- cmd/operator-sdk/generate/csv.go
- hack/tests/subcommand-generate-csv.sh
- internal/generate/olm-catalog/csv.go
- internal/generate/olm-catalog/csv_cmd_prompt.go
- internal/generate/olm-catalog/csv_go_test.go
- internal/generate/testdata/go/deploy/olm-catalog/memcached-operator/manifests/memcached-operator.clusterserviceversion.yaml
- internal/util/projutil/interactive_promt_util.go
- internal/util/projutil/interactive_promt_util_test.go
- website/content/en/docs/cli/operator-sdk_generate_csv.md
This PR introduces the feature to provide interactive prompts
to the user to obtain csv metadata.
Add interactive prompts while generating csv.
> [gen-csv] Add interactive prompts to generate csv

- CONTRIBUTING.MD
This fixes the broken hyperlink to the developer docs in the
[CONTRIBUTING.md](https://github.com/operator-framework/operator-sdk/blob/master/CONTRIBUTING.MD) file, which points to a former docs directory
inside the repo. Since that no longer exists, and the docs
have been moved onto the website, this fixes the hyperlink to
point to the same docs on the new website.
Fixes #2974 
Substitute broken reference inside repo to a functional one on the doc website
I don't like broken links!
> CONTRIBUTING.md: fix broken hyperlink to the developer docs

- cmd/operator-sdk/cli/cli.go
Hide `operator-sdk test` cmd in the new Kubebuilder integrated CLI.
Replaces #2959 since it was decided that in the new layout [envtest](https://book.kubebuilder.io/reference/testing/envtest.html) would be the preferred way of writing operator integration tests instead of test-framework.
> remove test cmd in new CLI

- website/content/en/docs/olm-integration/generating-a-csv.md
* docs/olm-integration/generating-a-csv.md: revert changes from #2989, fix grammar
**Motivation for the change:** didn't get a review in before #2989 was merged (my fault). See the original PR for comments related to these changes.
> docs/olm-integration revert changes from #2989, fix grammar

- .travis.yml
* .travis.yml: merge test-markdown and test-links steps into one
**Motivation for the change:** runtime of sanity tests is the `check` stage's bottleneck; if we merge the markdown and website checks into one job, that job will still run in less time than sanity.
/cc @asmacdo
> .travis.yml: merge test-markdown and test-links steps into one

- website/assets/scss/_variables.scss
Updates the color variables to align with the colors in the graphic on the main SDK landing page.
Some colors were slightly off due to the 200 and 300 level color variables being duplicate.
An example of this is on the main page where two of the headers in the Go, Helm, and Ansible columns had the same color.
> website/assets/scss/_variables.scss: fix duplicate color

- changelog/fragments/csv-package-manifests-bugfix.yaml
- cmd/operator-sdk/generate/csv.go
* cmd/operator-sdk/generate: skip package manifest generation if `--make-manifests=true` (the default)
**Motivation for the change:** package manifests are not part of bundles
/kind bug
> generate csv: do not generate a package manifest for bundles

- changelog/fragments/get-csv-manifest-bugfix.yaml
- internal/generate/olm-catalog/csv_util.go
* internal/generate/olm-catalog: use correct variable when reading CSV manifests
**Motivation for the change:** bug
Closes #3002 
/kind bug
> internal/generate/olm-catalog: read only one manifest at a time

- website/content/en/docs/olm-integration/user-guide.md
Fix missing link to index image docs on olm-integration docs.
See: https://sdk.operatorframework.io/docs/olm-integration/user-guide/#production
```
OLM and Operator Registry consumes Operator bundles via an [index image][index-image]
```
> olm-integration: fix link to index image docs

- cmd/operator-sdk/test/local.go
- go.mod
- internal/generate/clusterserviceversion/bases/clusterserviceversion.go
- internal/generate/clusterserviceversion/bases/markers.go
- internal/generate/clusterserviceversion/bases/metadata.go
- internal/generate/clusterserviceversion/bases/metadata_test.go
- internal/generate/crd/crd.go
- internal/generate/olm-catalog/csv.go
- internal/generate/olm-catalog/csv_go_test.go
- internal/generate/olm-catalog/csv_updaters.go
- internal/generate/olm-catalog/csv_util.go
- internal/generate/olm-catalog/package_manifest.go
- internal/generate/testdata/go/deploy/olm-catalog/memcached-operator/noupdate/memcached-operator.v0.0.3.clusterserviceversion.yaml
- internal/generate/testdata/non-standard-layout/expected-catalog/olm-catalog/memcached-operator/0.0.1/memcached-operator.v0.0.1.clusterserviceversion.yaml
- internal/generate/testdata/non-standard-layout/expected-catalog/olm-catalog/memcached-operator/0.0.3/memcached-operator.v0.0.3.clusterserviceversion.yaml
- internal/generate/testdata/non-standard-layout/expected-catalog/olm-catalog/memcached-operator/0.0.4/memcached-operator.v0.0.4.clusterserviceversion.yaml
- internal/olm/operator/operator_manager.go
- internal/scorecard/plugins/resource_handler.go
- internal/util/k8sutil/api.go
- internal/util/k8sutil/scan.go
- pkg/test/resource_creator.go
* internal/generate/clusterserviceversion: future home of CSV generation code. For now this just holds the base CSV getter and interactive prompt code, moved from olm-catalog
* internal/generate/olm-catalog: update CSV generator to use base getter
* internal/generate/testdata: update CSVs with new UI metadata defaults
* internal/util/k8sutil: NewYAMLScanner now takes an `io.Reader` rather than `[]byte` directly
**Motivation for the change:** #2860 is a fairly big PR containing some changes that made sense to break into their own PR. Additionally the new base CSV getter works well with the current CSV generator, so that has been refactored here as well.
/cc @hasbro17 @varshaprasad96 @joelanford
> internal/generate: refactoring for new `generate` commands

- cmd/operator-sdk/generate/csv.go
- website/content/en/docs/cli/operator-sdk_generate_csv.md
cmd/operator-sdk/generate: remove deprecations on `--csv-channel` and `--default-channel`.
**Motivation for the change:** package manifests are not deprecated. See #2944.
> generate csv: un-deprecate --csv-channel and --default-channel

- netlify.toml
Configure netlify with `netlify.toml`
This pulls some of the configuration out of the netlify UI and allows it
to be managed with version control.
FYI: hugo version history
Original site used the default Hugo version (0.54) which had some problems rendering tables and lists. Bumping to latest (0.70.0) exposed a layout/content discrepancy, so we temporarily rolled back to 0.62.2. The discrepancy has been fixed, so we can now bump to latest version. The early version bumps were done by setting an environment variable in the netlify UI, but this value is overridden by `netlify.toml`, allowing us to keep the hugo version in version control (and leverage deploy previews to test a bumped version)
> Add netlify configuration, bump hugo version to 0.70.0

- hack/ci/setup-k8s.sh
* hack/ci/setup-k8s.sh: pin kind version 
**Motivation for the change:** `kind` is still a fairly young project and can break between minor versions, which is what happened between v0.7 and [v0.8](https://github.com/kubernetes-sigs/kind/releases/tag/v0.8.0). This breaking change is breaking patch releases of old SDK versions. Its version should be pinned and updated on each k8s dep bump if possible.
> ci: pin kind version

- changelog/fragments/helm-fix-finalizer.yaml
- pkg/helm/controller/controller.go
- pkg/helm/controller/reconcile.go
Helm operator now applies its uninstall finalizer only when a release is deployed.
This PR fixes a bug in the helm operator that caused the CR to be unable to be deleted without manually intervening to delete a prematurely added finalizer.
> pkg/helm/controller/reconcile.go: finalizer fix

- cmd/operator-sdk/cli/cli.go
Remove scorecard1 `scorecard` cmd from the new KB aligned CLI.
scorecard2 is the new iteration of scorecard and that cmd should be enabled when it moves out of alpha.
> cli: remove old scorecard cmd

- cmd/operator-sdk/cli/cli.go
- internal/scorecard/alpha/testpod.go
this PR replaces a hard-coded image path value with the image path
as found in the test config for scorecard2.  
bug, fixing this allows custom test images to work.
> replace hard-coded image with the test Image

- changelog/fragments/run-local.yaml
- cmd/operator-sdk/execentrypoint/ansible.go
- cmd/operator-sdk/execentrypoint/cmd.go
- cmd/operator-sdk/execentrypoint/helm.go
- cmd/operator-sdk/run/cmd.go
- cmd/operator-sdk/run/local/cmd.go
- cmd/operator-sdk/run/local/local.go
- cmd/operator-sdk/run/packagemanifests/packagemanifests.go
- hack/tests/subcommand.sh
- test/e2e/_incluster-test-code/memcached_test.go
- website/content/en/docs/ansible/development-tips.md
- website/content/en/docs/ansible/quickstart.md
- website/content/en/docs/cli/operator-sdk_run.md
- website/content/en/docs/cli/operator-sdk_run_local.md
- website/content/en/docs/contribution-guidelines/testing/travis-build.md
- website/content/en/docs/golang/quickstart.md
- website/content/en/docs/golang/references/logging.md
- website/content/en/docs/helm/quickstart.md
* cmd/operator-sdk/run: deprecate 'run --loca' and related flags, and move 'local' and 'packagemanifests' subcommand code into their own packages
* *: s/--local/local/g in docs
**Motivation for the change:** follows the pattern of [`run packagemanifests`](#3016) and [`run bundle](https://github.com/operator-framework/enhancements/pull/19).
/kind feature
> run: deprecate '--local' flag in favor of 'local' subcommand

- cmd/operator-sdk/cli/cli.go
- cmd/operator-sdk/cli/legacy.go
- cmd/operator-sdk/generate/bundle/bundle.go
- cmd/operator-sdk/generate/bundle/cmd.go
- cmd/operator-sdk/generate/cmd.go
- cmd/operator-sdk/generate/internal/genutil.go
- internal/generate/clusterserviceversion/clusterserviceversion.go
- internal/generate/clusterserviceversion/clusterserviceversion_suite_test.go
- internal/generate/clusterserviceversion/clusterserviceversion_test.go
- internal/generate/internal/genutil.go
- internal/generate/testdata/clusterserviceversions/bases/memcached-operator.clusterserviceversion.yaml
- internal/generate/testdata/clusterserviceversions/bases/with-ui-metadata.clusterserviceversion.yaml
- internal/generate/testdata/clusterserviceversions/newlayout/manifests/memcached-operator.clusterserviceversion.yaml
- internal/generate/testdata/non-standard-layout/PROJECT
- internal/util/kubebuilder/project.go
- website/content/en/docs/cli/operator-sdk_generate.md
* `operator-sdk generate bundle` with:
* `--kustomize`: creates `config/bundle/kustomization.yaml`, and creates or updates `config/bundle/bases` with UI metadata. The base contains no manifests. This command will read API type data to generate `customresourcedefinitions` metadata using GVK's in `PROJECT`.
* `--manifests`: reads either from stdin or on-disk files and applies them to a base to write CSV and CRD manifests to `config/bases/manifests`. This command emulates `kustomize build`.
* `--metadata`: calls the same generator as the current `bundle create --generate-only`.
**Motivation for the change:** See #2860.
~Depends on #3064.~
> generate: add `bundle` subcommand for new project layouts

- go.mod
- go.sum
**Description of the change:** bump kubebuilder version
**Motivation for the change:** k8s v1.17 -> v1.18 for new project layouts.
`init` is not public yet so it does not require a changelog fragment.
> deps: bump kubebuilder to commit that supports k8s v1.18.2

- cmd/operator-sdk/generate/bundle/bundle.go
- cmd/operator-sdk/generate/bundle/cmd.go
- cmd/operator-sdk/generate/internal/genutil.go
- internal/generate/clusterserviceversion/clusterserviceversion.go
- internal/generate/clusterserviceversion/clusterserviceversion_test.go
- internal/generate/clusterserviceversion/clusterserviceversion_updaters.go
* cmd/operator-sdk/generate/bundle: set default and allow interactive prompts
* internal/generate/clusterserviceversion: change Options to accept `projutil.InteractiveLevel` arguments
**Motivation for the change:** `--interactive` was not added in #3065 
This command is still "hidden" so I don't think a changelog fragment is needed.
/cc @hasbro17 @camilamacedo86 @jmrodri
> generate bundle: enable interactive mode, set metadata default

- test/integration/operator_olm_test.go
* test/integration: force registry cleanup and uncomment lines fixed in the latest api version
**Motivation for the change:** improve integration tests
> test/integration: force cleanup, uncomment previously broken code

- changelog/fragments/3088-addition.yaml
- cmd/operator-sdk/generate/bundle/bundle_legacy.go
- cmd/operator-sdk/generate/bundle/cmd.go
- cmd/operator-sdk/generate/cmd.go
- cmd/operator-sdk/generate/internal/genutil.go
- hack/tests/subcommand-generate-csv.sh
- internal/generate/clusterserviceversion/clusterserviceversion.go
- internal/generate/clusterserviceversion/clusterserviceversion_test.go
- website/content/en/docs/cli/operator-sdk_generate.md
- website/content/en/docs/cli/operator-sdk_generate_bundle.md
* cmd/operator-sdk/generate/bundle: add `NewCmdLegacy` that returns a `bundle` subcommand configured to generate bundles for current project layouts.
* internal/generate/clusterserviceversion: add `GenerateLegacy` and `LegacyOption` to generate CSVs for legacy projects.
**Motivation for the change:** current project layouts should have a `generate bundle` command to differentiate between bundle and package manifests formats.
/cc @hasbro17 @jmrodri @camilamacedo86 
/kind feature
> generate: add `bundle` subcommand for current project layouts

- changelog/fragments/3083.yaml
- cmd/operator-sdk/bundle/validate.go
- internal/registry/validate.go
- website/content/en/docs/cli/operator-sdk_bundle_validate.md
* cmd/operator-sdk/bundle: `validate` will print errors and warnings from validation.
* internal/registry: `ValidateBundleContent` validates a bundle with a given mediaType, returning the results of validation to be analysed/printed.
**Motivation for the change:** operator-sdk users should be aware of both required and optional aspects of a bundle when running `bundle validate`.
/kind feature
~Depends on #3081~
> bundle validate: include both warnings and errors

- website/content/en/docs/crds-scope.md
- website/content/en/docs/faq.md
- website/content/en/docs/kubebuilder/crds-scope.md
- website/content/en/docs/kubebuilder/operator-scope.md
- website/content/en/docs/operator-scope.md
- website/content/en/docs/versioning.md
- Add operator-scope kb layout
- Split CRD scope in its own doc 
- Just organize the menu for the CRD scope shows with Operator Scope
**Motivation**
KB integration
> doc: add operator-scope kb layout

- hack/check-links.sh
Previously, the hugo container built the html into website/public (owned
by root), which was not rebuilt cleanly.
> Cleanup built html after link checking

- cmd/operator-sdk/bundle/create.go
- internal/scorecard/alpha/config.go
- internal/util/projutil/project_util.go
- internal/util/projutil/projutil_test.go
Adds scorecard config to bundle image, by modying bundle.Dockerfile.
> [scorecard] inject scorecard config to bundle image

- Makefile
- changelog/fragments/scorecard2-add-image-push.yaml
this PR modifies the Makefile to add 'push' targets for the new scorecard-test image.
this allows us to push this new image like the other images we push.
> Scorecard2 test image push

- .gitmodules
- website/assets/scss/_footer.scss
- website/assets/scss/_functions.scss
- website/assets/scss/_global.scss
- website/assets/scss/_header.scss
- website/assets/scss/_homepage.scss
- website/assets/scss/_reset.scss
- website/assets/scss/_styles_project.scss
- website/assets/scss/_type.scss
- website/assets/scss/_variables.scss
- website/layouts/404.html
- website/layouts/build/baseof.html
- website/layouts/docs/baseof.html
- website/layouts/docs/list.html
- website/layouts/docs/single.html
- website/layouts/faq/baseof.html
- website/layouts/index.html
- website/layouts/partials/footer.html
- website/layouts/partials/navbar.html
> [v0.17.x] Updates submodule (#2873)

- website/content/en/docs/kubebuilder/quickstart.md
Document how to enable multi-group APIs without the use of `kubebuilder edit` command.
> Add note on multi-group for the new userguide

- changelog/fragments/bundle-default-channel.yaml
- cmd/operator-sdk/bundle/create.go
**Description of the change:** set default channel if only one channel is set
**Motivation for the change:** a default channel should always be set, and we can infer which one it is if there is only one channel.
See https://github.com/operator-framework/operator-sdk/pull/3106#issuecomment-634431106
/cc @hasbro17 @camilamacedo86
> bundle create: set default channel if only one channel is set

- website/content/en/docs/kubebuilder/advanced-topics.md
Update info in advanced topics doc.
> Update Advanced Topics Doc

- website/content/en/docs/faq.md
When following the Getting Started guide, not setting the ```GOROOT```
env variable can fail image builds of ```memcached``` operator. This
adds an FAQ in the docs, to allow users to troubleshoot the problem.
Making documentation more robust.
Fixes #3080
> docs: add FAQ regarding GOROOT env var

- .travis.yml
- Makefile
- hack/lib/common.sh
- hack/lib/image_lib.sh
- hack/tests/e2e-go-new.sh
- test/e2e-new/e2e_suite.go
- test/e2e-new/e2e_test.go
- test/e2e-new/utils/kubectl.go
- test/e2e-new/utils/test_context.go
- test/e2e-new/utils/util.go
- test/kind-config.yaml
* test/e2e-new: test suite and utils for running a simple e2e test on a project with the new layout (`operator-sdk init`'d)
* hack/tests/e2e-go-new.sh: run new project layout test suite
* .travis.yml: add new job
* Makefile: add `test-e2e-go-new` to run the test suite
**Motivation for the change:** we need a simple e2e test that ensures changes made to the underlying kubebuilder plugin result in a valid operator, without duplicating much code from upstream e2e tests.
Note: once https://github.com/kubernetes-sigs/kubebuilder/pull/1520 is merged, `/test/e2e-new/util` can be removed.
> test,hack: add e2e test for new project layout

- changelog/fragments/ansible-fail-if-cant-determine-vr.yaml
- pkg/ansible/proxy/inject_owner.go
Proxy will return 500 if it fails to get an API resource using the discovery client.
This seems to be caused by some kind of race condition, but the result is that resources that should have ownerReferences injected do not, preventing dependent watches from being properly established and preventing garbage collection from working properly.
This is not a fix for the root cause of #2623 , but it should at least prevent us from putting the user into a state we can't recover from.
> Ansible Operator proxy now fails requests when virtual resource can't be determined

- website/content/en/docs/ansible/reference/webhooks.md
Move the Ansible webhook doc to the reference section and fix formatting.
The webhook documentation doesn't currently show up on the website.
closes #1658
> Add ansible webhook doc to reference section, fix formatting

- changelog/fragments/3129.yaml
- cmd/operator-sdk/generate/internal/genutil.go
- internal/generate/internal/genutil.go
- internal/generate/olm-catalog/csv.go
- internal/generate/olm-catalog/package_manifest.go
**Description of the change:** permissions for generated bundle directories now have r/x permissions for all users (`0755`).
**Motivation for the change:** automation tooling should be able to read bundle files.
/cc @camilamacedo86 @hasbro17 @jmrodri 
/kind bug
> util: set r/x permissions for bundle dirs

- cmd/operator-sdk/generate/bundle/bundle.go
- cmd/operator-sdk/generate/bundle/bundle_legacy.go
- cmd/operator-sdk/generate/internal/genutil.go
- internal/generate/clusterserviceversion/clusterserviceversion.go
- internal/generate/clusterserviceversion/clusterserviceversion_updaters.go
- internal/generate/collector/collect.go
- internal/generate/collector/filter.go
- internal/generate/crd/crd.go
- internal/generate/crd/crd_test.go
- internal/generate/olm-catalog/csv.go
- internal/scorecard/plugins/olm_tests.go
- internal/util/k8sutil/api.go
- internal/util/k8sutil/manifest.go
- pkg/helm/release/manager.go
**Description of the change:** either use a v1 CRD directly or convert between v1beta1 and v1.
**Motivation for the change:** the SDK should support both v1 and v1beta1 CRDs anywhere relevant because `operator-sdk generate crds` generates both types. Instead of converting to v1 in all cases, which could be error prone ex. validation keys differ, these changes handle both explicitly.
Closes #3005
> *: handle both v1 and v1beta1 CRD versions

- CHANGELOG.md
**Description of the change:** add v0.17.1 section, remove duplicate entries, and fix PR references in CHANGELOG.md
**Motivation for the change:** patch release wasn't added to master's changelog. Also it looks like the changelog generator's PR lookup capabilities aren't foolproof and it linked the wrong PR's for v0.17.1 and v0.18.0.
> CHANGELOG.md: add v0.17.1 section and fix PR references

- changelog/fragments/3059-fixleader-election-message.yaml
- pkg/leader/leader.go
refresh configmap when existing leader gets killed
non-leaders would claim that the old leader is "waiting to get evicted"  when in fact the leader is healthy
reproduction:
- 1 leader, 1 follower
- kill leader
- new pod comes up ... claims leader spot
- old follower claims old leader is waiting for eviction
> leader: get most recent lock owner when attempting a claim

- cmd/operator-sdk/bundle/create.go
- cmd/operator-sdk/generate/bundle/bundle.go
- cmd/operator-sdk/generate/bundle/bundle_legacy.go
- cmd/operator-sdk/generate/bundle/cmd.go
* cmd/operator-sdk/generate/bundle: validate that default channel exists, and set it if only one channel is passed
**Motivation for the change:** `bundle validate` will error if a default channel is not set in a bundle. Follow-up from #3124.
/cc @hasbro17 @jmrodri @jmccormick2001 
/kind bug
> bundle generate: ensure default channel exists

- website/content/en/docs/ansible/reference/webhooks.md
**Description of the change:** fix doc links and indentation
**Motivation for the change:** the main docs website is on v1.18 now, prior link was broken.
> docs: fix v1.17 k8s doc links

- changelog/fragments/validation-bug-bump-api.yaml
- go.mod
- go.sum
See https://github.com/operator-framework/api/pull/39.
Closes #3146 
/kind bug
> deps: bump api library for CRD validation bugfix

- cmd/operator-sdk/generate/bundle/cmd.go
**Description of the change:** validate args before running `generate bundle` logic.
**Motivation for the change:** if your run
```sh
$ operator-sdk generate bundle --manifests --metadata --channel foo --default-channel bar
```
manifests will be generated but the metadata generator will error out. This change ensures all command args are valid before running any generator.
/cc @hasbro17 @camilamacedo86 @jmrodri
> cmd/operator-sdk/generate/bundle: validate args before running

- .travis.yml
> CI: move to send coveralls after success

- go.mod
- go.sum
- internal/generate/testdata/non-standard-layout/PROJECT
- internal/plugins/golang/plugin.go
- website/content/en/docs/kubebuilder/quickstart.md
*: remove references to minor and patch versions for plugins, add "alpha" stage
**Motivation for the change:** Plugin versions have been removed and replaced with kubebuilder's plugin.Version type, which only contains a "major" version integer and an optional stage string. The "alpha" suffix is to denote that this plugin version might change soon. We can remove this when the plugin is stable.
This is a follow-up from https://github.com/kubernetes-sigs/kubebuilder/pull/1547.
> internal/plugins: remove minor/patch version, add "-alpha"

- hack/generate/changelog/util/fragment.go
- hack/generate/changelog/util/fragment_test.go
- Generation of CHANGELOG from the fragments is causing some lines referencing incorrect PR links
- For the releases v0.17.1 and v0.18.1, CHANGELOG had some incorrect PR links which had to be manually fixed
- Bug is in getCommitMessage which uses `git log` command with some flags to find the pull request in which the fragment file was initially added. It uses `--find-renames `option for detecting renames for a commit. The threshold is currently set to 40% which sometimes results in incorrect PR. Setting it to 90% yields the correct PR link for all the cases I've tried
- Added a unit test for getCommitMessage and mock the exec.Command function to return a mock output which is the commit string
- Manually tested that CHANEGLOG …
> changelog generation: fix for incorrect PR links 

- changelog/fragments/3040-fix-loglevel.yaml
- pkg/log/zap/flags.go
- pkg/log/zap/flags_test.go
Delegate string parsing to zap, allowing any zap-supported level (for both `--zap-level` and `--zap-stacktrace-level`)
The `--zap-stacktrace-level` option (#2319) is currently not working for any level > error as the parsing will not allow it.
I also think it's cleaner to delegate this level parsing to zap itself, it allows anything supported upstream.
> log: fix "panic" loglevel parsing for --zap-stacktrace-level option

- pkg/test/framework.go
Building the main.go file directly does not work if the main package is
split into multiple files.
Resolves: https://github.com/operator-framework/operator-sdk/issues/3187
> Build the manager directory package, not the cmdFile directly

- website/content/en/docs/scorecard/custom-tests.md
This PR adds a few more custom test image details that pertain to scorecard alpha.  It adds
to the existing custom test image documentation.
a few more details specific to writing a custom test image that end users might find
useful if they write a test image themselves.
> scorecard2 update custom test documentation

- cmd/operator-sdk/bundle/cmd.go
- cmd/operator-sdk/cli/legacy.go
- cmd/operator-sdk/generate/bundle/bundle.go
- cmd/operator-sdk/generate/bundle/bundle_legacy.go
- cmd/operator-sdk/generate/bundle/cmd.go
- internal/generate/clusterserviceversion/bases/clusterserviceversion.go
- internal/generate/clusterserviceversion/clusterserviceversion_updaters.go
- internal/generate/olm-catalog/csv.go
- internal/plugins/golang/api.go
- internal/plugins/golang/init.go
- internal/scaffold/kustomize/kustomize.go
- test/e2e-new/e2e_suite.go
- website/content/en/docs/cli/operator-sdk_generate_bundle.md
Changes:
* `operator-sdk init` writes `config/bundle/kustomization.yaml` and adds `bundle` and `bundle-build` recipes that generate a bundle on disk and build a bundle image, respectively.
* `operator-sdk create api` manages `config/samples/kustomization.yaml` so `kustomize build config/bundle` retrieves custom resource samples.
Example workflow:
```console
$ operator-sdk init
$ operator-sdk create api --group ship --version v1beta1 --kind Frigate
```
Then invoke:
```console
$ make bundle 
/home/estroz/go/bin/controller-gen "crd:trivialVersions=true" rbac:roleName=manager-role webhook paths="./..." output:crd:artifacts:config=config/crd/bases
operator-sdk generate bundle -q --kustomize
kustomize build config/bundle | …
```
> plugin: write Makefile recipes for `generate bundle` subcommand

- CHANGELOG.md
- changelog/fragments/3059-fixleader-election-message.yaml
- changelog/fragments/validation-bug-bump-api.yaml
- internal/scaffold/ansible/go_mod.go
- internal/scaffold/go_mod.go
- internal/scaffold/helm/go_mod.go
- version/version.go
- website/content/en/docs/install-operator-sdk.md
- website/content/en/docs/migration/v0.18.1.md
With the release of 0.18.1, we need the `latest` branch (which is the production branch for sdk.operatorframework.io) to mirror v0.18.x branch.
> *: release v0.18.1 (#3179)

- hack/check-links.sh
- website/config.toml
- website/layouts/partials/navbar-version-selector.html
- website/layouts/partials/navbar.html
Adds a releases tab which points to versioned documentation. These changes should be cherry picked back to all live versions of the docs (0.17.x, 0.18.x)
> Versioned doc links

- CHANGELOG.md
- changelog/fragments/validation-bug-bump-api.yaml
**Description of the change:** update changelog and remove related fragments
**Motivation for the change:** changelog missing v0.18.1 entries.
There should be a step in the release doc to do this after every patch release, including removal of related fragments, so patched changes aren't duplicated in the following major/minor version release.
> changelog: update from v0.18.1 release

- .travis.yml
the scorecard-test image is new with the scorecard (alpha) version, so it needs to be built
and pushed like the other images by the Travis CI system.  This PR updates the .travis.yml file
to include scorecard-test image.
required to have scorecard-test image be built and pushed when doing releases.
> scorecard2 - update travis CI script to build and push the scorecard-test image

- website/content/en/docs/ansible/reference/advanced_options.md
- website/content/en/docs/ansible/reference/finalizers.md
- website/content/en/docs/golang/migrating-existing-apis.md
- website/content/en/docs/golang/quickstart.md
- website/content/en/docs/golang/references/client.md
- website/content/en/docs/operator-capabilities.md
Fixes broken links caused by kubernetes rename of a group of docs
Our CI is failing
> Fix links after kubernetes renamed access-kubernetes to extend-kuberntes-api

- internal/scaffold/version.go
- internal/scaffold/version_test.go
- website/content/en/docs/golang/references/project-layout.md
Add documentation for generated operator version.
Motivation is to add documentation on the operation version so users of the SDK know what this version is. Happy to change wording if needed.
> Add documentation for operator version

- hack/tests/e2e-ansible.sh
**Description of the change:** remove `-it` flags from the Ansible e2e test.
**Motivation for the change:** neither interactive mode nor a tty are needed.
> hack/tests/e2e-ansible.sh: remove `-it` flags

- changelog/fragments/3221-bugfix.yaml
- cmd/operator-sdk/bundle/validate.go
- go.mod
- go.sum
- internal/scorecard/alpha/tests/olm.go
* deps: bump operator-registry
* cmd/operator-sdk/bundle/validate,internal/scorecard/alpha/tests: the NewImageValidator API changed such that the command must create an image registry first before creating a validator.
**Motivation for the change:** This version of operator-registry contains a fix for a bug that causes validation errors when an existing `annotations.yaml` does not exactly match the default annotations generated by `operator-sdk bundle create`.
/cc @camilamacedo86 @jmrodri @hasbro17 @varshaprasad96 
/kind bug
> deps: bump operator-registry version

- internal/scorecard/interfaces.go
- pkg/apis/scorecard/v1alpha2/formatter.go
- pkg/apis/scorecard/v1alpha3/formatter.go
The change has fmt.Sprintf("...") removed from sb.WriteString(fmt.Sprintf("...")) and two other variable assignment in 3 files at various places.
This is because the latest version throws error stating that fmt.Sprintf() is doing an extra step of converting a string to a string. 
I have also done formatting of code in one of the section due to this error:
internal/plugins/golang/plugin.go:46: File is not `goimports`-ed (goimports)
after pretty print I am able to make the sdk.
I have installed the latest version of Go and a couple of features are throwing errors making it difficult to build.
> String error fix

- website/content/en/docs/operator-capabilities.md
> website: Fix misspelled 'PodDsruptionBudget' in the operator capabilities documentation.

- changelog/fragments/generate-packagemanifests.yaml
- cmd/operator-sdk/generate/cmd.go
- cmd/operator-sdk/generate/packagemanifests/cmd.go
- cmd/operator-sdk/generate/packagemanifests/packagemanifests.go
- internal/generate/clusterserviceversion/clusterserviceversion.go
- internal/generate/clusterserviceversion/clusterserviceversion_test.go
- internal/generate/clusterserviceversion/clusterserviceversion_updaters.go
- internal/generate/collector/collect.go
- internal/generate/packagemanifest/bases/packagemanifest.go
- internal/generate/packagemanifest/packagemanifest.go
- internal/generate/packagemanifest/packagemanifest_test.go
- internal/generate/testdata/memcached-operator.package.yaml
- test/e2e-new/e2e_suite.go
* `operator-sdk generate packagemanifests` with:
* `--kustomize`:
* creates or updates `config/packagemanifests/bases` with UI metadata. The base contains no manifests. This command will read API type data to generate `customresourcedefinitions` metadata using GVK's in `PROJECT`.
* creates `config/packagemanifests/kustomization.yaml` if it does not already exist.
* `--manifests`: reads either from stdin or on-disk files and applies them to a base to write CSV and CRD manifests to `config/packagemanifests/<version>`. This command emulates `kustomize build`.
**Motivation for the change:** See https://github.com/operator-framework/enhancements/pull/16.
TODO's:
> generate: add `packagemanifests` subcommand for new project layouts

- cmd/operator-sdk/generate/packagemanifests/packagemanifests.go
- website/content/en/docs/new-cli/operator-sdk_generate.md
- website/content/en/docs/new-cli/operator-sdk_generate_packagemanifests.md
**Description of the change:** fix spacing and regenerate CLI docs
**Motivation for the change:** no docs for `generate packagemanifests`.
/cc @hasbro17 
> cmd/operator-sdk/generate: fix spacing and regenerate CLI docs

- changelog/fragments/3234-arm64-tini-url.yaml
- internal/scaffold/ansible/dockerfilehybrid.go
This fixes the build of the ansible-operator base image to use the correct download URL for `tini` on ARM64. This fixes issue #3233 
The current ansible-operator base image for ARM64 doesn't work
> ansible: use correct download URL for tini on aarch64
