operator-framework/operator-sdk

pkg/generator/codegen_tmpls.go
pkg/generator/generator_test.go

Give docker access to GOPATH if SELinux is enforcing

---

CHANGELOG.md

CHANGELOG: added changelog

---

Makefile

refers to #239 
Add a basic Makefile for now

Makefile: Add Makefile for ease development

---

doc/dev/reporting_bugs.md

typo: no issue is too small

---

Makefile
README.md
doc/user-guide.md

@fanminshi What do you think about using `Makefile` command in README ? 
Also added `-v` flags when `make dep`.

doc/user_guide.md - README - Makefile: Use Makefile in documentation

---

pkg/generator/gen_version.go
pkg/generator/gen_version_test.go
pkg/generator/generator.go
pkg/generator/version_tmpl.go

Addressing @hasbro17 comment in PR #297

pkg/generator: Remove GitSHA from operator version file

---

pkg/generator/generator_test.go

pkg/generator: Generator unit testing

---

CONTRIBUTING.MD

Make documentation for major changes a requirement in the contributing guide
/cc @rithujohn191 @spahl

contributing.md: require documentation for new features

---

.travis.yml

Expanding e2e test to include the closing steps of the user guide

travis: Add memcached cr to travis

---

pkg/generator/util.go
pkg/generator/util_test.go

pkg/generator: Add support for ending in s

---

README.md
doc/user-guide.md

The directory for the checkout must be created before we can use it.

[docs] fix workflow example

---

test/e2e/main_test.go

This commit causes go test to exit on failure if a test fails

test/e2e/main_test.go: return correct exit code on failure

---

pkg/generator/generator_test.go
pkg/generator/templates.go

fix https://github.com/operator-framework/operator-sdk/issues/368

generator: support gcp auth

---

.travis.yml
Gopkg.lock
Gopkg.toml
pkg/generator/templates.go

This doesn't require any changes to the code and allows us to
experiment with the controller-runtime.

Gopkg.*,pkg/generator/templates.go: update to kubernetes 1.10.1

---

.gitignore

Adds vim and emacs, more complete vscode.

.gitignore: Use gitignore.io to generate more complete output

---

README.md

Fix issue #372 
Suggestions to improve this welcome!

Address issue #372, add Prerequisites section to README.md

---

.travis.yml
commands/operator-sdk/cmd/new.go
hack/check_error_case.sh
hack/check_license.sh
hack/lib/test_lib.sh
pkg/generator/generator_test.go
pkg/generator/templates.go
pkg/sdk/informer-sync.go
pkg/sdk/metrics.go
pkg/test/resource_creator.go
test/e2e/framework/context.go
test/e2e/framework/framework.go
test/e2e/framework/main_entry.go
test/e2e/framework/resource_creator.go
test/e2e/memcached_test.go

This adds a new bash test script in hack that checks the case of the first character of error messages to make sure they are not uppercase.
Resolves #380.

hack: add check_error_case.sh and test_lib.sh

---

doc/user-guide.md

doc: Use time.Duration in Documentation

---

pkg/sdk/action.go
pkg/sdk/informer-sync.go
pkg/util/k8sutil/k8sutil.go

pkg/{sdk,util}: don't panic on invalid cr.yaml

---

pkg/tlsutil/tls.go

pkg/tlsutil: remove unused keyAndCert

---

README.md

This adds a delete step for the CRD in the cleanup section

Cleanup steps should include step to delete CRD

---

commands/operator-sdk/cmd/new.go

commands: redefine/refactor the new command interface

---

pkg/scaffold/cmd.go
pkg/scaffold/render.go

pkg/scaffold: add codegen for cmd/manager/main.go

---

commands/operator-sdk/cmd/new.go
pkg/scaffold/cmd.go

commands: new generates cmd/manager/main.go

---

commands/operator-sdk/cmd/new.go
pkg/scaffold/controller.go

*: add codegen for pkg/controller/controller.go

---

commands/operator-sdk/cmd/new.go
pkg/scaffold/dockerfile.go

*: add codegen for pkg/build/Dockerfile

---

commands/operator-sdk/cmd/new.go
pkg/scaffold/build.go

*: add codegen for pkg/build/build.sh

---

Gopkg.lock
commands/operator-sdk/cmd/add.go
commands/operator-sdk/cmd/add/api.go
commands/operator-sdk/cmd/cmdutil/util.go
commands/operator-sdk/cmd/generate/k8s.go
pkg/scaffold/addtoscheme.go
pkg/scaffold/doc.go
pkg/scaffold/register.go
pkg/scaffold/resource.go
pkg/scaffold/types.go

Added the `operator-sdk add api --kind<kind> --apiversion=<apiversion>` command along with all the required templates and code-generators.

*: add operator-sdk add api command

---

commands/operator-sdk/cmd/new.go
pkg/scaffold/rolebinding.go

*: add codegen for deploy/role_bind.yaml

---

commands/operator-sdk/cmd/new.go
pkg/scaffold/role.go

*: add codgen for base deploy/role.yaml

---

commands/operator-sdk/cmd/new.go
pkg/scaffold/operator.go

*: add codegen for deploy/operator.yaml

---

commands/operator-sdk/cmd/new.go

*: add codegen for scripts/codegen/Boilerplate.go.txt and fix typos

---

commands/operator-sdk/cmd/new.go
pkg/scaffold/version.go

*: add codegen for version/version.go

---

doc/user-guide.md

Adding documentation for both operator-sdk and controller runtime on how to add a resource to the scheme.

doc/user-guide: Adding add to scheme documentation

---

README.md

to be consistent with all the README file

add missing mkdir

---

commands/operator-sdk/cmd/new.go
pkg/scaffold/gitignore.go

*: add codegen for .gitignore

---

commands/operator-sdk/cmd/new.go
pkg/scaffold/gopkgtoml.go

*: add codegen for Gopkg.toml

---

pkg/scaffold/role.go
pkg/scaffold/rolebinding.go

pkg/scaffold: use Role/Binding instead of ClusterRole/Binding

---

commands/operator-sdk/cmd/add/api.go

cmd/add: append role of new apiGroup and Resource to role.yaml

---

pkg/scaffold/add_controller_test.go
pkg/scaffold/addtoscheme_test.go
pkg/scaffold/test_constant.go

this is a part of efforts to write unit tests for all template generators. 
add tests for AddController and AddToScheme code generator.
cc/ @hasbro17

*: add add_controller_test and addtoscheme_test

---

pkg/scaffold/apis_test.go
pkg/scaffold/build_test.go
pkg/scaffold/cmd_test.go

*: add apis_test.go, build_test.go, and cmd_test.go

---

pkg/scaffold/controller_kind_test.go
pkg/scaffold/controller_test.go

pkg/refactor: add controller_kind_test.go and controller_test.go

---

commands/operator-sdk/cmd/add/api.go
pkg/scaffold/doc.go

*: remove unused projectPath from DocInput

---

test/e2e/memcached_test.go

test/e2e/memcached_test.go: use local memcached example handler

---

pkg/scaffold/cr_test.go
pkg/scaffold/doc_test.go
pkg/scaffold/dockerfile_test.go

pkg/scaffold: add cr_test.go doc_test.go dockerfile_test.go

---

pkg/scaffold/crd_test.go
pkg/scaffold/gitignore_test.go
pkg/scaffold/gopkgtoml_test.go

pkg/scaffold: add crd_test.go gitignore_test.go gopkgtoml_test.go

---

pkg/scaffold/operator_test.go
pkg/scaffold/register_test.go
pkg/scaffold/role_test.go

pkg/scaffold: add operator_test.go register_test.go role_test.go

---

pkg/scaffold/rolebinding_test.go
pkg/scaffold/types_test.go
pkg/scaffold/version_test.go

pkg/scaffold: add rolebinding_test.go types_test.go version_test.go

---

.gitignore
Makefile
doc/release-versioning.md
pkg/scaffold/gopkgtoml.go
pkg/scaffold/gopkgtoml_test.go
release.sh

Has useful annotations and makes the build workflow a bit easier.

cherry pick: Version and release documentation (#531)

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/feature-request.md
.github/ISSUE_TEMPLATE/support-question.md

Some formatting problems happened during my first PR, this should fix the issue problem. I edited it from the github UI. Was not aware that is possible before.

.github: Update issue templates

---

README.md

Fixed Ansible operator user guide link.
Broken link.

Fixed ansible_user_guide link

---

CHANGELOG.md

**Description of the change:** Update Changelogfor v0.1.0
**Motivation for the change:** Realease notes for v0.1.0

CHANGELOG.md: update for v0.1.0

---

pkg/scaffold/gopkgtoml.go
pkg/scaffold/gopkgtoml_test.go
version/version.go

pkg/scaffold,version: release to v0.1.0

---

pkg/scaffold/gopkgtoml.go
pkg/scaffold/gopkgtoml_test.go
version/version.go

pkg/scaffold,version: bump to v0.1.0-git

---

doc/release-versioning.md
pkg/scaffold/cmd.go
pkg/scaffold/cmd_test.go
pkg/scaffold/crd.go
pkg/scaffold/gopkgtoml.go
pkg/scaffold/gopkgtoml_test.go
release.sh
version/version.go

**Description of the change:** Cherry picked commits for v0.1.1 release
**Motivation for the change:** Important bug fixes

Cherry pick commits for v0.1.1 release

---

doc/migration/v0.1.0-migration-guide.md

Minor tweak to the Migration doc after running through it :-).

doc/migration: Tweak client examples, add unstructured

---

.github/PULL_REQUEST_TEMPLATE.md

Fix the comment closing tag.
Weirdly formatted markdown due to unclosed comment tag.

PR Template: fix comment tag

---

commands/operator-sdk/cmd/test/local.go

Empty deploy manifests or missing manifest files result in test failure
because of invalid yaml file parsing.
This change shows warning when a deploy manifest is missing, instead of
failing completely, and checks if the file is empty before appending the
content with other manifests.
#701 
Closes #701

cmd/test: do not append empty manifests

---

commands/operator-sdk/main.go
internal/util/projutil/project_util.go

Reverts operator-framework/operator-sdk#712

Revert "decompose GOPATH and set it according to the current working dir."

---

pkg/scaffold/controller_kind.go
pkg/scaffold/controller_kind_test.go

Fix inccorect initialization of logs in the generated controller.
Closes https://github.com/operator-framework/operator-sdk/issues/748

pkg/scaffold: Fix logging bug in controller

---

pkg/scaffold/controller_kind.go
pkg/scaffold/controller_kind_test.go

Fixes a typo in scaffolded controller logger
No typos > typos

pkg/scaffold: fixing typo in controller log

---

doc/user-guide.md

Document Core Kubernetes resources that are automatically registered and update 3rd Party Resource example to reflect a scheme that is not registered "out-of-the-box".

Update 3rd Party Resources User-Guide Info

---

CHANGELOG.md

**Description of the change:** Update the changelog
**Motivation for the change:** It was out of date and missing the latest user facing changes

CHANGELOG.md: update CHANGELOG

---

CHANGELOG.md

CHANGELOG.md: add print-deps line

---

doc/sdk-cli-reference.md

doc/sdk-cli-reference.md: add print-deps example

---

CHANGELOG.md
pkg/scaffold/gopkgtoml.go
pkg/scaffold/gopkgtoml_test.go
version/version.go

pkg/scaffold,version,changelog: bump to v0.2.0

---

CHANGELOG.md
pkg/scaffold/gopkgtoml.go
pkg/scaffold/gopkgtoml_test.go
version/version.go

Reverts operator-framework/operator-sdk#791

Revert "pkg/scaffold,version,changelog: bump to v0.2.0"

---

.travis.yml
test/e2e/memcached_test.go

Reverts operator-framework/operator-sdk#766

Revert "Adds travis support for push builds"

---

CHANGELOG.md
pkg/scaffold/gopkgtoml.go
pkg/scaffold/gopkgtoml_test.go
version/version.go

Release v0.2.0 (hopefully with working CI this time)

 pkg/scaffold,version,changelog: bump to v0.2.0 (again) (again)

---

CHANGELOG.md
pkg/scaffold/gopkgtoml.go
pkg/scaffold/gopkgtoml_test.go
version/version.go

pkg/scaffold,version,changelog: bump to v0.2.0+git

---

CHANGELOG.md

Backporting changelog addition from PR #822

changelog: add cluster-scope flag to changelog

---

pkg/ansible/proxy/proxy.go

**Description of the change:** Reduce level of a cache miss log from error to info
**Motivation for the change:** Better, clearer output for the proxy
/cc @dymurray @mhrivnak @shawn-hurley

pkg/ansible/proxy: change a cache miss log from error to info

---

CHANGELOG.md
pkg/scaffold/gopkgtoml.go
pkg/scaffold/gopkgtoml_test.go
version/version.go

**Description of the change:** Bump master branch to v0.2.1+git
**Motivation for the change:** v0.2.1 released

version,pkg/scaffold,changelog: bump to v0.2.1+git

---

.github/ISSUE_TEMPLATE/bug-report.md

Adding Helm as an operator type to the github issue template
We added support for the helm operator but didn't update the issue template.

.github/ISSUE_TEMPLATE/bug-report.md: add Helm

---

doc/proposals/README.md
doc/proposals/TEMPLATE.md

Adds a process for new proposals.

doc/proposals: Add proposal README and template

---

CHANGELOG.md

Updating CHANGELOG.md to document new location for base images.
To help users find the new base images.

CHANGELOG.md: Adding info about new locations for base images

---

pkg/test/client.go

e2e don't error if already gone

---

hack/check_error_log_msg_format.sh
pkg/k8sutil/k8sutil_test.go
pkg/ready/ready_test.go

**Description of the change:** fix log message check regexp and log messages not following that convention

Fix regexp in sanity check for log message case

---

CHANGELOG.md
pkg/ansible/proxy/proxy.go

Add the ability for the cache handler to respect list requests

pkg/ansible/proxy: Allow cache to handle list requests

---

doc/sdk-cli-reference.md

**Description of the change:** Update flags for commands in SDK CLI Reference doc
**Motivation for the change:** We should make sure the CLI reference doc matches the current state for the commands

doc/sdk-cli-reference: update cli ref

---

CHANGELOG.md
pkg/scaffold/ansible/gopkgtoml.go
pkg/scaffold/gopkgtoml.go
pkg/scaffold/gopkgtoml_test.go
pkg/scaffold/helm/gopkgtoml.go
version/version.go

Bump master branch to `v0.4.0+git`

*: bump to v0.4.0+git

---

commands/operator-sdk/cmd/migrate.go
hack/image/ansible/scaffold-ansible-image.go
pkg/scaffold/ansible/dockerfilehybrid.go
pkg/scaffold/ansible/k8s_status.go
pkg/scaffold/ansible/molecule_test_local_playbook.go
test/ansible-memcached/asserts.yml
test/ansible-memcached/tasks.yml

Add k8s_status Ansible module into the build for Ansible Operator
This Ansible module is needed for the managed status work in Ansible Operator

pkg/scaffold/ansible; Add k8s_status module

---

CHANGELOG.md

**Description of the change:** add CSV changes to `CHANGELOG.md`
**Motivation for the change:** record keeping

CHANGELOG.md: add CSV feature

---

doc/user/client.md

Fixes a typo
We don't like typos :)

doc/user/client.md: fix typo

---

pkg/ansible/controller/controller.go
pkg/ansible/controller/reconcile.go
pkg/ansible/controller/reconcile_test.go

after the ansible has finished.

pkg/ansible/controller: reconciler needs to get the resource

---

doc/test-framework/scorecard.md

**Description of the change:** Add documentation for scorecard config file
**Motivation for the change:** Document new feature

doc/test-framework/scorecard: add config file section

---

CHANGELOG.md
pkg/scaffold/ansible/gopkgtoml.go
pkg/scaffold/gopkgtoml.go
pkg/scaffold/gopkgtoml_test.go
pkg/scaffold/helm/gopkgtoml.go
version/version.go

**Description of the change:** Change master version to v0.4.1+git and sync changelog
**Motivation for the change:** v0.4.1 released

pkg,version,CHANGELOG: bump to v0.4.1+git

---

CHANGELOG.md
doc/proposals/ansible-operator.md
doc/proposals/helm-operator.md

- fix typo in CHANGELOG.md
- fix typo in doc/proposals/helm-operator.md
- fix typo in doc/proposals/ansible-operator.md

Fix few typos

---

CHANGELOG.md
pkg/scaffold/ansible/gopkgtoml.go
pkg/scaffold/gopkgtoml.go
pkg/scaffold/gopkgtoml_test.go
pkg/scaffold/helm/gopkgtoml.go
version/version.go

Release v0.5.0

---

CHANGELOG.md
pkg/scaffold/ansible/gopkgtoml.go
pkg/scaffold/gopkgtoml.go
pkg/scaffold/gopkgtoml_test.go
pkg/scaffold/helm/gopkgtoml.go
version/version.go

Cleaning up versioning post v0.5.0 release
Following release documentation

Post Release Clean-Up

---

doc/ansible/user-guide.md

Correct path in example

---

doc/dev/release.md

**Description of the change:** Fix some minor issues with the release doc
**Motivation for the change:** Make sure the release process is clear and up to date

doc/dev/release: make some minor corrections

---

doc/helm/dev/developer_guide.md
doc/sdk-cli-reference.md
pkg/scaffold/helm/chart.go
pkg/scaffold/scaffold.go

To avoid the confusion that a user would need to take action.
See https://github.com/operator-framework/operator-sdk/pull/949/files#r254343667

pkg/scaffold: Adjust log msg create -> created

---

doc/ansible/dev/developer_guide.md
doc/proposals/ansible-operator.md
pkg/ansible/controller/reconcile.go
pkg/ansible/proxy/proxy.go
pkg/ansible/runner/internal/inputdir/inputdir.go
pkg/k8sutil/constants.go
pkg/k8sutil/k8sutil_test.go
pkg/metrics/metrics.go
pkg/ready/ready.go
pkg/scaffold/ansible/molecule_test_cluster_playbook.go
pkg/scaffold/ansible/molecule_test_local_playbook.go
test/ansible-inventory/molecule/test-local/playbook.yml
test/ansible-memcached/asserts.yml
test/test-framework/deploy/olm-catalog/memcached-operator/0.0.2/memcached-operator.v0.0.2.clusterserviceversion.yaml

This PR fixes the misspelled words
Fix the misspelled words

misspell: Fix misspelled words

---

doc/ansible/dev/advanced_options.md
doc/ansible/dev/finalizers.md
doc/user-guide.md

Adds docs for finalizer field in watches.yaml
Docs are good

Add docs for finalizers

---

doc/ansible/dev/advanced_options.md
images/scorecard-proxy/cmd/proxy/main.go
pkg/ansible/flags/flag.go
pkg/ansible/proxy/proxy.go
pkg/ansible/run.go

* This will be used by an operator author by overriding the entrypoint
in there build/Dockerfile.

pkg/ansible: Adding ability to have a flag that turns off the owner ref.

---

doc/dev/developer_guide.md
doc/dev/release.md
doc/versioning.md

**Description of the change:** Fix broken links
**Motivation for the change:** Make CI pass on v0.4.x

doc/*: fix broken links (#1119)

---

pkg/ansible/controller/controller.go
pkg/ansible/flags/flag.go
pkg/ansible/operator/operator.go
pkg/ansible/operator/operator_test.go
pkg/internal/flags/flags.go

* add MaxWorkers option
* add support for environment variables
* add WORKER prefix
* add unit test for operator
* update help text
* favor env over cli
* Closes #915

pkg/ansible: support multiple workers

---

Gopkg.lock
hack/tests/e2e-ansible-molecule.sh
pkg/ansible/proxy/proxy.go
pkg/handler/enqueue_annotation.go
test/ansible-memcached/asserts.yml

* Ansible operator would create resources with owner references that were incorrect.
* This uses a new mechanism to dynamically watch resources that cross the namespace boundaries.
* This was a very bad assumption on our part and is causing issues.

Bugfix/update owner ref behavior 4.0

---

doc/helm/user-guide.md

fixed a typo in helm user guide.

Fix a minor typo

---

pkg/ansible/controller/reconcile.go
pkg/ansible/runner/eventapi/types.go

* Taking a pass through the error scenarios and adding context to them
* Adding more obvious errors for end users around the reconcile period
errors
* Adding ability to handle ignore_error key in ansible task
Better error messages and easier debugging when issues arise.
fixes #1174

pkg/ansible: Updating reconciler to make errors more obvious

---

CHANGELOG.md
pkg/scaffold/ansible/gopkgtoml.go
pkg/scaffold/gopkgtoml.go
pkg/scaffold/gopkgtoml_test.go
pkg/scaffold/helm/gopkgtoml.go
version/version.go

Post release versioning
Post release versioning

Post release versioning

---

CHANGELOG.md
doc/sdk-cli-reference.md

CHANGELOG.md: new --header-file flag for 'add api' and 'generate k8s'

---

CHANGELOG.md

**Description of the change:** Mention a bug fix in the changelog that was missing
**Motivation for the change:** Keep changelog up-to-date

CHANGELOG.md: add a missing bug fix to changelog

---

CHANGELOG.md
internal/util/yamlutil/scan.go

**Description of the change:** Backport bugfix from #1258
**Motivation for the change:** Fix bugs in latest stable release

Backport: internal/util/yamlutil: fix empty yaml bug (#1258)

---

Gopkg.lock
pkg/ansible/operator/operator.go
pkg/ansible/proxy/controllermap/controllermap.go
pkg/ansible/proxy/proxy.go
pkg/handler/enqueue_annotation.go

* Ansible operator would create resources with owner references that were incorrect.
* This uses a new mechanism to dynamically watch resources that cross the namespace boundaries.
* This was a very bad assumption on our part and is causing issues.

pkg/ansible - Bugfix/update owner ref behavior

---

test/e2e/memcached_test.go

**Description of the change:** bump e2e timeout.
**Motivation for the change:** tests have been flaking more recently. no more flakes plz

test/e2e: bump Go e2e timeout

---

CHANGELOG.md
internal/pkg/scaffold/ansible/gopkgtoml.go
internal/pkg/scaffold/gopkgtoml.go
internal/pkg/scaffold/gopkgtoml_test.go
internal/pkg/scaffold/helm/gopkgtoml.go
version/version.go

**Description of the change:** Set version to v0.7.0
**Motivation for the change:** Make new release

CHANGELOG,version,scaffold: release v0.7.0

---

CHANGELOG.md
internal/pkg/scaffold/ansible/gopkgtoml.go
internal/pkg/scaffold/gopkgtoml.go
internal/pkg/scaffold/gopkgtoml_test.go
internal/pkg/scaffold/helm/gopkgtoml.go
version/version.go

**Description of the change:** Bump versions to master and v0.7.0+git
**Motivation for the change:** Post-release versioning

CHANGELOG,version,scaffold: post-release version bump

---

CHANGELOG.md
internal/pkg/scaffold/ansible/gopkgtoml.go
internal/pkg/scaffold/gopkgtoml.go
internal/pkg/scaffold/gopkgtoml_test.go
internal/pkg/scaffold/helm/gopkgtoml.go
version/version.go

**Description of the change:** Bump version on v0.7.x branch
**Motivation for the change:** Post-release versioning

CHANGELOG,version,scaffold: post-release v0.7.x

---

doc/dev/release.md

Closes https://github.com/operator-framework/operator-sdk/issues/1249

doc/dev/release.md: Add brew formula upgrade guide

---

doc/ansible/user-guide.md

Simple PR to help users debugging Ansible errors
Help users debug issues

Useful debug help

---

doc/user-guide.md

* Add a note into the guide. See [here](https://github.com/operator-framework/operator-sdk/blob/39ff68960ed9e61a2f3d55bfd2ea6fed95f2a500/doc/user-guide.md#register-with-the-managers-scheme)
https://github.com/operator-framework/operator-sdk/issues/1365

Doc: add notes in the section ‘Register with the Manager's scheme’

---

test/e2e/memcached_test.go

**Description of the change:** rework some go e2e test logic for cleanliness, set local repo path in `memcached-operator` test project instead of always using a remote repo.
**Motivation for the change:** local commits are not respected by current `memcached_test.go` code when run locally. This PR sets a require directive in the scaffolded `go.mod` as follows:
```
module github.com/example-inc/memcached-operator
...
replace github.com/operator-framework/operator-sdk => /path/to/local/sdk
```
Modules can use local repo paths, but require a `go.mod` file be present. We must temporarily write a `/path/to/local/sdk/go.mod` file (removed after test finishes). This step can be removed once the SDK migrates to use modules itself.

test/e2e: use local path of SDK in go.mod for non-Travis CI environment

---

README.md
doc/ansible/user-guide.md
doc/dev/release.md
doc/helm/user-guide.md
doc/user-guide.md
doc/user/install-operator-sdk.md
release.sh

Users should install the latest release instead of compiling operator-sdk binary from master.

*: Point users to the latest release instead of

---

example/memcached-operator/memcached_controller.go.tmpl
internal/pkg/scaffold/controller_kind.go
internal/pkg/scaffold/controller_kind_test.go
pkg/helm/controller/reconcile.go
test/test-framework/pkg/controller/memcached/memcached_controller.go
test/test-framework/pkg/controller/memcachedrs/memcachedrs_controller.go

To make operator-sdk more accessible to newcomers we continue to improve code comments to explain generated constructs that may not be obvious.
Closes #1424

add comment to generated controller code to explain interface check

---

doc/design/milestone-0.2.0/csv-generation.md
doc/user/olm-catalog/generating-a-csv.md

Correct csv-config.yaml supported fields documentation

---

doc/user-guide.md

* Add an example of finalizer into the guide doc based on the Memcached Getting Started example.
* https://github.com/operator-framework/operator-sdk/issues/1397
* Help users know how it could be implemented

doc(finalizer) : Add an example based on Memcached Getting Started one

---

doc/proposals/cli-ux-phase1.md

This PR adds a proposal to update the SDK CLI with new commands to support running an operator with OLM.
To initiate design discussions and a proof of concept implementation for simplifying the process of deploying an operator to a cluster using OLM.

doc/proposals/cli-ux-phase1.md: adding first CLI UX proposal

---

pkg/ansible/proxy/cache_response.go
pkg/ansible/proxy/inject_owner.go
pkg/ansible/proxy/proxy.go

refactor the proxy.go file into three files to make it more clear what is doing what.
un-expose some functions to not leak internal details
proxy.go was too big and had too many things happening in it.

pkg/ansible/proxy: refactor proxy to remove public exposed functions

---

CHANGELOG.md

**Description of the change:** Add operator scorecard plugins addition to changelog
**Motivation for the change:** Keep changelog up to date

CHANGELOG.md: add scorecard changes

---

CHANGELOG.md
internal/pkg/scaffold/ansible/go_mod.go
internal/pkg/scaffold/ansible/gopkgtoml.go
internal/pkg/scaffold/go_mod.go
internal/pkg/scaffold/go_mod_test.go
internal/pkg/scaffold/gopkgtoml.go
internal/pkg/scaffold/gopkgtoml_test.go
internal/pkg/scaffold/helm/go_mod.go
internal/pkg/scaffold/helm/gopkgtoml.go
version/version.go

**Description of the change:** Bump to v0.8.0+git
**Motivation for the change:** Post-release bump

*: bump to v0.8.0+git

---

CHANGELOG.md
internal/pkg/scaffold/ansible/gopkgtoml.go
internal/pkg/scaffold/gopkgtoml.go
internal/pkg/scaffold/gopkgtoml_test.go
internal/pkg/scaffold/helm/gopkgtoml.go
version/version.go

**Description of the change:** Release v0.7.1
**Motivation for the change:** Make new v0.7.x release with bugfixes

*: release v0.7.1

---

CHANGELOG.md
internal/pkg/scaffold/ansible/go_mod.go
internal/pkg/scaffold/ansible/gopkgtoml.go
internal/pkg/scaffold/go_mod.go
internal/pkg/scaffold/go_mod_test.go
internal/pkg/scaffold/gopkgtoml.go
internal/pkg/scaffold/gopkgtoml_test.go
internal/pkg/scaffold/helm/go_mod.go
internal/pkg/scaffold/helm/gopkgtoml.go
version/version.go

**Description of the change:** Post-release branch bump for v0.8.x
**Motivation for the change:** Versioning

*: bump v0.8.x branch to v0.8.0+git

---

CHANGELOG.md
internal/pkg/scaffold/ansible/gopkgtoml.go
internal/pkg/scaffold/gopkgtoml.go
internal/pkg/scaffold/gopkgtoml_test.go
internal/pkg/scaffold/helm/gopkgtoml.go
version/version.go

**Description of the change:** Bump v0.7.x branch to `v0.7.1+git`
**Motivation for the change:** Versioning

*: bump to v0.7.1+git

---

CHANGELOG.md
doc/user/install-operator-sdk.md
internal/pkg/scaffold/ansible/go_mod.go
internal/pkg/scaffold/ansible/gopkgtoml.go
internal/pkg/scaffold/go_mod.go
internal/pkg/scaffold/go_mod_test.go
internal/pkg/scaffold/gopkgtoml.go
internal/pkg/scaffold/gopkgtoml_test.go
internal/pkg/scaffold/helm/go_mod.go
internal/pkg/scaffold/helm/gopkgtoml.go
version/version.go

Release v0.8.1
Make new v0.8.x release with bugfixes

*: release v0.8.1

---

CHANGELOG.md
internal/pkg/scaffold/ansible/go_mod.go
internal/pkg/scaffold/ansible/gopkgtoml.go
internal/pkg/scaffold/go_mod.go
internal/pkg/scaffold/go_mod_test.go
internal/pkg/scaffold/gopkgtoml.go
internal/pkg/scaffold/gopkgtoml_test.go
internal/pkg/scaffold/helm/go_mod.go
internal/pkg/scaffold/helm/gopkgtoml.go
version/version.go

Bump v0.8.x branch to v0.8.1+git
Versioning

*: bump to v0.8.1+git

---

cmd/operator-sdk/new/cmd.go
internal/pkg/scaffold/helm/role.go
internal/pkg/scaffold/helm/role_test.go

- Changes `helm.CreateRoleScaffold` signature to make testing easier
- Adds unit tests for `helm.CreateRoleScaffold`
Minimize future regressions

internal/pkg/scaffold/helm/role_test: add test for role scaffold

---

doc/user/install-operator-sdk.md

Updated the version number mentioned in installation guide.

Update install guide with 0.8.1 version

---

internal/pkg/scaffold/helm/chart_test.go

**Description of the change:** add license header to `internal/pkg/scaffold/helm/chart_test.go`
**Motivation for the change:** needs license header.

internal/pkg/scaffold/helm/chart_test.go: add license header

---

doc/design/milestone-0.0.2/query-api.md

Fixed minor typo I notice while copy-pasting code

Fix minor typo

---

doc/user-guide.md

Improve the finalizer example in the user guide
Helping a user out understanding finalizers, I realized that our finalizer example could be misleading in certain cases (failures during finalizer logic and handling multiple finalizers).

doc/user-guide.md: improve finalizer example

---

doc/user/logging.md

Update the Logging docs to include a runnable standalone example to demonstrate the `--zap-*` flags.
See #1527

doc/user/logging.md: update to include a runnable standalone example

---

doc/user/unit-testing.md

The field of the client in the reconcile is client not cl

Correct unit-test.md call to reconcile client

---

doc/user-guide.md

**Description of the change:** remove and change parts of doc/user-guide.md of documentation that reference Go module features supported by the SDK.
**Motivation for the change:** incorrect documentation.

doc/user-guide.md: update Go modules support section

---

CHANGELOG.md
internal/pkg/scaffold/ansible/go_mod.go
internal/pkg/scaffold/ansible/gopkgtoml.go
internal/pkg/scaffold/go_mod.go
internal/pkg/scaffold/go_mod_test.go
internal/pkg/scaffold/gopkgtoml.go
internal/pkg/scaffold/gopkgtoml_test.go
internal/pkg/scaffold/helm/go_mod.go
internal/pkg/scaffold/helm/gopkgtoml.go
version/version.go

**Description of the change:** revert `v0.9.0` to target `master`.
**Motivation for the change:** post-release PR.

*: bump to v0.9.0+git

---

doc/user/csv-annotations.md

**Description of the change:** fix broken link
**Motivation for the change:** fix link outside of #1689 so PR's pass

doc/usre/csv-annotations.md: fix link

---

doc/migration/v0.1.0-migration-guide.md
doc/proposals/ansible-operator-status.md
doc/proposals/metering-operator-metrics.md

**Description of the change:** see #1596 
**Motivation for the change:** broken links in v0.8.x

v0.8.x: fix broken links (#1596)

---

CHANGELOG.md
internal/pkg/scaffold/boilerplate_go_txt_test.go
internal/pkg/scaffold/scaffold.go

**Description of the change:** see #1544
**Motivation for the change:** for v0.8.2

v0.8.x: fix boilerplate check (#1544)

---

CHANGELOG.md
internal/pkg/scaffold/olm-catalog/csv_test.go
internal/pkg/scaffold/olm-catalog/csv_updaters.go
internal/pkg/scaffold/olm-catalog/testdata/deploy/olm-catalog/app-operator/0.1.0/app-operator.v0.1.0.clusterserviceversion.yaml
test/test-framework/deploy/olm-catalog/memcached-operator/0.0.2/memcached-operator.v0.0.2.clusterserviceversion.yaml
test/test-framework/deploy/olm-catalog/memcached-operator/0.0.3/memcached-operator.v0.0.3.clusterserviceversion.yaml

**Description of the change:** see #1396 
**Motivation for the change:** cherry-pick for v0.8.2

internal/pkg/scaffold/olm-catalog: use olm.targetNamespaces annotation in WATCH_NAMESPACE (#1396)

---

CHANGELOG.md
internal/pkg/scaffold/crd.go

**Description of the change:** see #1636 
**Motivation for the change:** deployed` (#1565)

internal/pkg/scaffold/crd.go: remove CRD cache (#1636)

---

CHANGELOG.md
doc/sdk-cli-reference.md

**Description of the change:** add `--operator-name` to docs
**Motivation for the change:** was not added in #1571 
Will update the v0.9.0 release notes and cherry pick this into v0.9.x once merged.

CHANGELOG.md,doc/sdk-cli-reference.md: add --operator-name addition

---

CHANGELOG.md
doc/sdk-cli-reference.md

**Description of the change:** see #1716
**Motivation for the change:** was missed in v0.9.0
Will update v0.9.0 release notes after merge.

CHANGELOG.md,doc/sdk-cli-reference.md: add --operator-name (#1716)

---

CHANGELOG.md
doc/user/install-operator-sdk.md
internal/pkg/scaffold/ansible/go_mod.go
internal/pkg/scaffold/ansible/gopkgtoml.go
internal/pkg/scaffold/go_mod.go
internal/pkg/scaffold/go_mod_test.go
internal/pkg/scaffold/gopkgtoml.go
internal/pkg/scaffold/gopkgtoml_test.go
internal/pkg/scaffold/helm/go_mod.go
internal/pkg/scaffold/helm/gopkgtoml.go
version/version.go

**Description of the change:** version bumps for v0.8.2
**Motivation for the change:** release v0.8.2

*: release v0.8.2

---

CHANGELOG.md
internal/pkg/scaffold/ansible/go_mod.go
internal/pkg/scaffold/ansible/gopkgtoml.go
internal/pkg/scaffold/go_mod.go
internal/pkg/scaffold/go_mod_test.go
internal/pkg/scaffold/gopkgtoml.go
internal/pkg/scaffold/gopkgtoml_test.go
internal/pkg/scaffold/helm/go_mod.go
internal/pkg/scaffold/helm/gopkgtoml.go
version/version.go

**Description of the change:** revert version from v0.8.2 to v0.8.x
**Motivation for the change:** post v0.8.2 release

*: revert version from v0.8.2 to v0.8.x

---

CHANGELOG.md

**Description of the change:** add v0.8.2 changelog entries
**Motivation for the change:** not present in `master`

CHANGELOG.md: add v0.8.2 bug fixes

---

hack/tests/e2e-ansible-molecule.sh
internal/pkg/scaffold/ansible/dockerfilehybrid.go
internal/pkg/scaffold/ansible/molecule_default_prepare.go
test/ansible-inventory/molecule/test-local/prepare.yml

ansible molecule e2e: pin pyasn1{-modules} version, better ready check, fix e2e user setup

---

cmd/operator-sdk/internal/genutil/openapi.go

**Description of the change:** use `kube-openapi` generator defaults.
**Motivation for the change:** `kube-openapi` generator defaults contain a build tag and using them allows future changes to the generator to be inherited by `operator-sdk generate openapi`.
Closes #1747 
cc @johananl

cmd/operator-sdk/internal/genutil/openapi.go: set ignore_autogenerated build tag in generated openapi code

---

Makefile
ci/dockerfiles/scorecard-proxy.Dockerfile
ci/tests/scorecard-proxy-scaffold.sh
ci/tests/scorecard-subcommand.sh
ci/tests/subcommand.sh
hack/tests/test-subcommand.sh
test/test-framework/.test-osdk-scorecard.yaml
test/test-framework/deploy/namespace-init.yaml

**Description of the change:** Add subcommand tests to openshift-ci
**Motivation for the change:** Migrate more tests from travis to openshift-ci

ci,test,hack/tests: add openshift-ci e2e support for subcommands

---

CHANGELOG.md
doc/user/install-operator-sdk.md
internal/pkg/scaffold/ansible/go_mod.go
internal/pkg/scaffold/ansible/gopkgtoml.go
internal/pkg/scaffold/go_mod.go
internal/pkg/scaffold/gopkgtoml.go
internal/pkg/scaffold/helm/go_mod.go
internal/pkg/scaffold/helm/gopkgtoml.go
release.sh
version/version.go

Description of the change: change versions to v0.10.0.
Motivation for the change: release v0.10.0.

*: release v0.10.0

---

CHANGELOG.md
internal/pkg/scaffold/ansible/go_mod.go
internal/pkg/scaffold/ansible/gopkgtoml.go
internal/pkg/scaffold/go_mod.go
internal/pkg/scaffold/gopkgtoml.go
internal/pkg/scaffold/helm/go_mod.go
internal/pkg/scaffold/helm/gopkgtoml.go
version/version.go

**Description of the change**: revert v0.10.0 to target master.
**Motivation for the change**: post-release PR.

*: bump to v0.10.0+git for master

---

README.md

- Add license and go report health status
- Add link for the Getting Started.

small readme improvements

---

OWNERS

add camila macedo

---

OWNERS

add jmccormick2001 github id to the OWNERS file

add jmccormick2001 to OWNERS file

---

doc/ansible/dev/testing_guide.md

Remove note about installing molecule from source

---

doc/proposals/ansible-operator-status.md
doc/proposals/ansible-operator-testing.md
doc/proposals/ansible-operator.md

Add relevant status and message with links to Ansible proposal implementation docs.
See Issue #1910.

Issue #1910: Add status to Ansible proposal docs with relevant docs links.

---

internal/pkg/scorecard/interfaces.go

cleanup code, make it more clean.

cleanup code in internal/pkg/scorecard/interfaces.go

---

doc/test-framework/scorecard.md

Some improvements in the scorecard 
Try to make easier its understanding. 
**To Review:**
Check its result here: https://github.com/operator-framework/operator-sdk/blob/5ab5232a623a852e4e54ff23832926192553cd94/doc/test-framework/scorecard.md

doc(test-features): improvements in the scorecard

---

cmd/operator-sdk/build/cmd.go

A small change in the desc of the operator-sdk build . 
- https://github.com/operator-framework/operator-sdk/issues/1930

small typo change to solve the issue 1930

---

README.md

Fix few typos.

---

ci/dockerfiles/ansible-e2e-hybrid.Dockerfile
ci/dockerfiles/ansible.Dockerfile
ci/tests/e2e-ansible.sh
internal/pkg/scaffold/ansible/dockerfilehybrid.go

This reverts commit e1c32a906dc57c2951d4e0845dae7efdf015c0ec.
Need to make sure ansible python3 bump happens at the same time as ubi8 bump.

Revert "ci,internal: update ubi7 -> ubi8 (#1986)"

---

doc/user/metrics/README.md

Update the readme to show an example of how to expose a custom metric.

doc: show how to expose custom metrics

---

doc/faq.md

Fix minor typo in faq.md

---

CHANGELOG.md
doc/design/milestone-0.2.0/csv-generation.md
doc/proposals/cli-ux-phase1.md
doc/proposals/sdk-code-annotations.md
doc/test-framework/scorecard.md
doc/user/csv-annotations.md

Cherry pick of 1cb0481ca94659b03dd90d3c4f367934c3865a85
Needed for the `v0.10.1` release

fix link doc olm (#1888)

---

CHANGELOG.md
internal/pkg/scaffold/ansible/travis.go
pkg/ansible/controller/reconcile.go

Pulling in patch #2031 for the upcoming release of v0.10.1
Have new bug fixes in release

Cherry pick PR #2031 to v0.10.x

---

CHANGELOG.md
internal/pkg/scaffold/ansible/go_mod.go
internal/pkg/scaffold/ansible/gopkgtoml.go
internal/pkg/scaffold/go_mod.go
internal/pkg/scaffold/gopkgtoml.go
internal/pkg/scaffold/helm/go_mod.go
internal/pkg/scaffold/helm/gopkgtoml.go
version/version.go

Post v0.11.0 release version bump for master
Versioning

*: bump to v0.11.0+git for master

---

internal/pkg/scaffold/helm/chart_test.go

t.Fatalf should be used in the same goroutine the testing run, this fix it.

fix t.Fataf using in goroutine

---

README.md

Add Operator capability level image in the README
**Motivation**
Closes: https://github.com/operator-framework/operator-sdk/issues/1797

Add Operator capability level image in the README

---

doc/ansible/dev/advanced_options.md

doc: Explain how to set maxWorkers

---

doc/operator-scope.md

Improvements with the purpose to make the understanding easier
- https://github.com/operator-framework/operator-sdk/issues/1933
- https://github.com/operator-framework/operator-sdk/issues/2009
**To Review**
See: https://github.com/operator-framework/operator-sdk/blob/0b1326fcaaccf271e7bebfa7e1d28f7467e4a1f9/doc/operator-scope.md

doc(operator and crds scope) : Improvements with the purpose to make the understanding easier

---

internal/scaffold/ansible/build_test_framework_dockerfile.go

Remove the conditional used to do the migration which should no longer be used now. 
Closes: #2105

fix Dockerfile ansible test image

---

doc/proposals/upstream-osdk-features-into-controller-runtime.md

Proposal for upstreaming SDK features into Kubebuilder and controller-runtime.
Outline all the specific features and changes that need to be upstreamed to facilitate SDK/Kubebuilder integration.
/cc @joelanford @dmesser

doc/proposals: proposal for upstreaming features into controller-runtime

---

CHANGELOG.md
internal/pkg/scaffold/ansible/go_mod.go
internal/pkg/scaffold/ansible/gopkgtoml.go
internal/pkg/scaffold/go_mod.go
internal/pkg/scaffold/gopkgtoml.go
internal/pkg/scaffold/helm/go_mod.go
internal/pkg/scaffold/helm/gopkgtoml.go
version/version.go

Post-release branch bump for v0.10.x
Versioning

*: bump to v0.11.0+git for v0.11.x

---

CHANGELOG.md
doc/user/install-operator-sdk.md
internal/scaffold/ansible/go_mod.go
internal/scaffold/go_mod.go
internal/scaffold/helm/go_mod.go
version/version.go

Change versions to v0.12.0
Prepare for release v0.12.0

*: release v0.12.0

---

CHANGELOG.md
internal/scaffold/ansible/go_mod.go
internal/scaffold/go_mod.go
internal/scaffold/helm/go_mod.go
version/version.go

Post v0.12.0 release version bump for master
Versioning

*: bump to v0.12.0+git for master

---

CHANGELOG.md
internal/scaffold/ansible/go_mod.go
internal/scaffold/go_mod.go
internal/scaffold/helm/go_mod.go
version/version.go

Post v0.12.0 release version bump for v0.12.x
Versioning

*: bump to v0.12.0+git for v0.12.x

---

doc/proposals/README.md
doc/proposals/hugo-doc-build.md

POC: https://operator-sdk.netlify.com/
POC Source: https://github.com/asmacdo/test-docs/

Docs Hosting with Hugo proposal

---

doc/proposals/openshift-4.3/operator-testing-tool.md

this is a docs change to the scorecard test tool proposal
the new changes include adding newly scoped goals to the proposal.  Stories for the new goals are included as well.

scorecard proposal - add new scope and associated stories

---

doc/ansible/dev/advanced_options.md
doc/ansible/information-flow-ansible-operator.md

Clarify doc on owner reference injection
It took me a while to understand how it worked, so I wanted to make the doc more obvious.
Ref: #1969

ansible: Clarify doc on owner reference injection

---

doc/helm/dev/developer_guide.md
doc/helm/project_layout.md
doc/helm/user-guide.md

fix broken links in the helm guide to fix CI

fix broken links in the helm guide

---

.travis.yml

Removal of certain conditional and repeated test in Travis CI, part of a larger effort to consolidate operator-sdk testing on a single CI platform.

Consolidate CI work to Single Provider

---

README.md

- Update the kube version in the requirements
https://github.com/operator-framework/getting-started/issues/60

update kube verison in requirements

---

.travis.yml
Makefile
hack/common.sh
hack/go-linter.sh

feat: add linter check

---

Makefile

- Organize Makefile by section to be easier to find where it any kind of target and know ts purpose. 
NOTE: Not merge this one before https://github.com/operator-framework/operator-sdk/pull/2205

Organize makefile

---

.travis.yml
Makefile
README.md

See the current coverage (52%) :https://coveralls.io/builds/27038706 . 
Closes #2197

Add coveralls

---

README.md

Remove the coveralls badge from the README

remove the badge

---

hack/go-linter.sh
internal/scorecard/scorecard_output.go
pkg/ansible/controller/status/types.go
pkg/ansible/controller/status/utils.go
pkg/ansible/controller/status/utils_test.go
pkg/apis/scorecard/v1alpha2/formatter.go
pkg/helm/run.go
pkg/tls/primitives.go
pkg/tls/tls.go
test/e2e/tls_util_test.go

feat(linter) : add check  for goimports and to do fixes

---

cmd/operator-sdk/internal/genutil/k8s.go
cmd/operator-sdk/internal/genutil/openapi.go
cmd/operator-sdk/scorecard/cmd.go
hack/go-linter.sh
internal/olm/client.go
internal/olm/client/client.go
internal/scaffold/crd_test.go
pkg/ansible/controller/reconcile.go
pkg/ansible/proxy/kubectl.go
pkg/ansible/proxy/proxy.go
pkg/kube-metrics/server.go
test/test-framework/pkg/controller/memcachedrs/memcachedrs_controller.go

- Enable errcheck check
- Fix linter issues
**Motivation**
Closes: #2219

feat(linter): add errcheck check an fix issues

---

hack/go-linter.sh
internal/scaffold/role.go
internal/scorecard/plugins/olm_tests.go

Add a linter to check code duplication and fix issues detected by the duplication linter.
Add [duplication linter](https://github.com/mibk/dupl) to `golangci-lint` to check for duplication of code and therefore reduce the code base.
Closes #2218

feat(linter): add dupl to linter and fix issues

---

doc/migration/version-upgrade-guide.md

Add steps to migrate the projects to use SDK 0.12
Closes #2161

add steps to migrate the projects to use the sdk version 0.12

---

doc/ansible/dev/developer_guide.md

add mapping name: test to roles/Foo/tasks/main.yml

add mapping to roles/Foo/tasks/main.yml

---

hack/go-linter.sh
internal/scorecard/plugins/plugin_runner.go
pkg/helm/controller/reconcile.go

- Enable interfacer check
- Fix linter issues
**Motivation**
Closes: #2217

feat(linter) : add interfacer check and solve issues

---

doc/sdk-cli-reference.md
doc/test-framework/writing-e2e-tests.md
doc/user/unit-testing.md

Update ref links for Memcached Go samples
**Motivation**
https://github.com/operator-framework/operator-sdk-samples/pull/97

update ref links

---

CHANGELOG.md
doc/dev/release.md
doc/user/install-operator-sdk.md
internal/scaffold/ansible/go_mod.go
internal/scaffold/go_mod.go
internal/scaffold/helm/go_mod.go
version/version.go

Change versions to v0.13.0
Prepare for release v0.13.0

*: release v0.13.0

---

CHANGELOG.md
internal/scaffold/ansible/go_mod.go
internal/scaffold/go_mod.go
internal/scaffold/helm/go_mod.go
version/version.go

Bump to `v0.13.0+git` for master
Post-release step for `v0.13.0` release.

*: bump to v0.13.0+git

---

CHANGELOG.md
cmd/operator-sdk/scorecard/cmd.go
doc/cli/operator-sdk_scorecard.md
doc/test-framework/scorecard.md
go.mod
go.sum
hack/tests/subcommand-scorecard.sh
internal/scorecard/helpers/helpers.go
internal/scorecard/helpers/test_definitions.go
internal/scorecard/plugins/config.go
internal/scorecard/plugins/olm_tests.go
internal/scorecard/plugins/plugin_runner.go
internal/scorecard/scorecard.go
pkg/apis/scorecard/v1alpha1/types.go
pkg/apis/scorecard/v1alpha2/formatter.go
pkg/apis/scorecard/v1alpha2/types.go
pkg/apis/scorecard/v1v2conversions.go
test/test-framework/.osdk-scorecard-bundle.yaml
test/test-framework/go.sum

add the scorecard bundle validation feature which includes calling a validation API, adding
a new bundle flag to the scorecard, plus adding a bundle validation test.
part of a set of changes to the scorecard.

add scorecard bundle validation feature

---

CHANGELOG.md

**Description of the change:** add leader election bugfix from #2210 to the changelog.
**Motivation for the change:** was not added in #2210
Will update release notes once this is added, and make a PR to `v0.13.x`.

CHANGELOG.md: add leader election bugfix (#2210)

---

doc/proposals/sdk-integration-with-olm.md

Signed-off-by: Chun Lin Yang <clyang@cn.ibm.com>
replace the individual commit with master

update the link in master

---

internal/scorecard/plugins/plugin_runner.go
internal/scorecard/plugins/runner_test.go

this PR is focused on organizing the function RunInternalPlugin() into a more easy
to understand and read function within the scorecard logic.  
The intention was NOT
to change the logic but just organize it better into manageable chucks/sub-functions
instead of the single large function.  More refactoring of this section of scorecard 
code is in upcoming work that will greatly change this code further.

Scorecard refactor run

---

code-of-conduct.md

Update outdated contact info in the Code of Conduct doc.
Fixes #2306

code-of-conduct: update contact info

---

doc/user-guide.md

* Explicitly mention example code location of `cmd/manager/main.go`
* Provide example of registration of 3rd party resource which does not
support `AddToScheme()` function
* Document working example of adding 3rd party resource which does not provide `AddToScheme()` function in its package
* That might be not the best way to do it so feedback is obviously welcome

Extend 3rd party resource management documentation

---

Makefile
hack/tests/check-lint.sh

- Add target to fix issues automatically
- Add target to check just the ci lint locally
Make easier check and do fix regards lint issues.

improvements in the make target for lint checks and automatically fixes

---

CHANGELOG.md
doc/user/install-operator-sdk.md
internal/scaffold/ansible/go_mod.go
internal/scaffold/go_mod.go
internal/scaffold/helm/go_mod.go
version/version.go

**Description of the change:** release v0.14.0
**Motivation for the change:** release v0.14.0

*: release v0.14.0

---

CHANGELOG.md
internal/scaffold/ansible/go_mod.go
internal/scaffold/go_mod.go
internal/scaffold/helm/go_mod.go
version/version.go

**Description of the change:** post v0.14.0 release
**Motivation for the change:** post v0.14.0 release

*: bump to v0.14.0+git

---

doc/faq.md

Check made to close the issue #1736

update doc: make clear the required permission for metrics regards the finalizers

---

CHANGELOG.md
doc/user/install-operator-sdk.md
internal/scaffold/ansible/go_mod.go
internal/scaffold/go_mod.go
internal/scaffold/helm/go_mod.go
version/version.go

Prepare for release of v0.14.1
Backport bug fixes

*: release v0.14.1

---

CHANGELOG.md
internal/scaffold/ansible/go_mod.go
internal/scaffold/go_mod.go
internal/scaffold/helm/go_mod.go
version/version.go

Post release version bumps for v0.14.1+
Complete the release

*: post-v0.14.1 bumps

---

CHANGELOG.md
doc/user/install-operator-sdk.md

Update CHANGELOG and install docs to include v0.14.1 info
Make sure docs are up-to-date

doc,CHANGELOG.md: update for v0.14.1 release

---

CHANGELOG.md
internal/scaffold/ansible/go_mod.go
internal/scaffold/go_mod.go
internal/scaffold/helm/go_mod.go
version/version.go

post v0.15.0 release updates
part of the release process.

post release v0.15.0 changes

---

CHANGELOG.md
internal/scaffold/ansible/go_mod.go
internal/scaffold/go_mod.go
internal/scaffold/helm/go_mod.go
version/version.go

updates the v0.15.x branch as part of post release steps.

v0.15.x post release branch setup

---

CHANGELOG.md
doc/user/install-operator-sdk.md
internal/scaffold/ansible/go_mod.go
internal/scaffold/go_mod.go
internal/scaffold/helm/go_mod.go
version/version.go

Prep v0.15.x branch for v0.15.1 release
Release bug fixes

*: prep for v0.15.1 release

---

CHANGELOG.md
internal/scaffold/ansible/go_mod.go
internal/scaffold/go_mod.go
internal/scaffold/helm/go_mod.go
version/version.go

Post-`v0.15.1` release updates
Complete the `v0.15.1` release

*: post release updates for v0.15.1

---

CHANGELOG.md
doc/user/install-operator-sdk.md

* Update CHANGELOG to include `v0.15.1`
* Update installation guide to point to `v0.15.1`
`master` should include references to latest patch release

CHANGELOG.md,doc/user: update for v0.15.1

---

ci/dockerfiles/ansible-e2e-hybrid.Dockerfile
ci/dockerfiles/ansible.Dockerfile
internal/scaffold/ansible/dockerfilehybrid.go

Bump openshift client to 0.9.2
Closes #2384

dockerfiles/ansible: bump openshift client to 0.9.2

---

pkg/helm/release/manager_factory.go

Add a mutex to ensure non-concurrent access to Helm's `kube.New()` function, which is not safe for concurrent use.
See https://github.com/helm/helm/pull/7249
This commit can be reverted after SDK's Helm dependendency is bumped to 3.1.0+
Closes #2476

pkg/helm/release/manager_factory.go: lock on kube.New()

---

internal/generate/olm-catalog/package_manifest_test.go

add unit tests for the Generator

add unit tests for the Generator

---

doc/user-guide.md

Add a link in the user guide to the new status conditions godoc
To make the status conditions helpers more discoverable

doc/user-guide.md: add godoc link for status conditions

---

doc/faq.md

Linking cache FAQ from controller runtime to the sdk docs.

doc: add controller runtime faq link to sdk FAQ

---

doc/proposals/kubernetes-1.17.md

fix broken link regards k8s 1.17 changelog

---

doc/proposals/kubernetes-1.17.md

Replace the link with joe's suggestion.

fix link k8s 1.17

---

doc/migration/version-upgrade-guide.md

upgrade guide with 0.13 changes

---

test/test-framework/cmd/manager/main.go
test/test-framework/deploy/crds/cache.example.com_dummys_crd.yaml
test/test-framework/deploy/crds/cache.example.com_otherdummies_crd.yaml
test/test-framework/go.sum

update test-framework mock data

update test-framework mock data

---

doc/proposals/kubernetes-1.17.md

fix broken link regards 1.17 changelog

fix broken link regards 1.17 changelog

---

CHANGELOG.md
internal/scaffold/ansible/entrypoint.go
internal/scaffold/ansible/usersetup.go
internal/scaffold/entrypoint.go
internal/scaffold/entrypoint_test.go
internal/scaffold/helm/entrypoint.go
internal/scaffold/helm/usersetup.go
internal/scaffold/usersetup.go
internal/scaffold/usersetup_test.go

internal/scaffold: don't change /etc/passwd perms (#2469)

---

CHANGELOG.md
cmd/operator-sdk/run/local.go

cmd/operator-sdk: fix run local flags (#2478)

---

internal/flags/watch/flags.go
pkg/ansible/flags/flag.go
pkg/helm/flags/flag.go

- revert the PR: https://github.com/operator-framework/operator-sdk/pull/2548
- And comment to remember us to do this change before 1.0.0
- https://github.com/operator-framework/operator-sdk/pull/2548#issuecomment-585298361

revert the PR: #2548

---

CHANGELOG.md
doc/user/install-operator-sdk.md
internal/scaffold/ansible/go_mod.go
internal/scaffold/go_mod.go
internal/scaffold/helm/go_mod.go
version/version.go

pre-release commit for the patch v0.15.2

pre-release commit for the patch v0.15.2 

---

.travis.yml
Makefile
doc/dev/release.md
hack/image/build-ansible-image.sh
hack/image/build-scorecard-proxy-image.sh
internal/scaffold/ansible/dockerfilehybrid.go

This replaces #2329 and should fix #2468.

Enable all images on ppc64le and s390x

---

doc/migration/version-upgrade-guide.md

add migration guide for sdk 0.14

add migration guide for sdk 0.14

---

CHANGELOG.md
doc/user/install-operator-sdk.md

changelog release 0.15.2

---

CHANGELOG.md
internal/scaffold/ansible/go_mod.go
internal/scaffold/go_mod.go
internal/scaffold/helm/go_mod.go
version/version.go

Post release 0.15.2

---

doc/migration/version-upgrade-guide.md

doc: add upgrade guide for 0.15+

doc: add upgrade guide for 0.15+

---

doc/dev/release.md

- add osx required notes and a missing step
- Issues/problems faced by doing the release

doc(release): add osx required notes and a missing step

---

doc/proposals/kubebuilder-integration.md

**Description of the change:** modify some wording, update status, update goals and related stories
**Motivation for the change:** a few requirements for the SDK side of the kubebuilder integration have changed, but nothing substantial (other than plugin proposal merge) since this proposal was submitted.

doc/proposals/kubebuilder-integration.md: update requirements

---

doc/user-guide.md

Signed-off-by: Brad Topol <btopol@us.ibm.com>
Adds a discussion of registry options for the image build
step in the user guide. Also provides clarity on the registry push
step in the guide.
Closes: #2592

add discussion of registry options for the image build

---

doc/user/logging.md

This PR updates logging.md with details explaining the use custom zap logger.
Addresses the issue - https://github.com/operator-framework/operator-sdk/issues/2449

Doc(logging.md): add notes for logging using custom zap logger

---

doc/user/logging.md

Update the console output from custom logger in logging.md guide.

[fix] correct console output in logging.md

---

doc/operator-capabilities.md

Signed-off-by: dmesser <dmesser@redhat.com>
Adding more information about Operator capability levels as well as guiding questions to help authors determine the current level of their Operators feature and aspire a higher level 😄
The capability graphic only provide minimal detail on what the different levels actually mean.

operator capability definitions

---

doc/proposals/ansible-helm-addapi.md

Proposal to  modify existing "add api" command to enable adding additional apis for ansible and helm based operators.

doc: Ansible/Helm add api command  Proposal for Operator SDK

---

doc/dev/developer_guide.md

- Add info to help new contributors know how to test their changes locally

adding steps over how to test the changes made locally

---

SECURITY.md

Add SECURITY.md.
To help users report security vulnerabilities responsibly.
Closes #2307

Add SECURITY.md for responsible disclosure instructions

---

CHANGELOG.md
doc/user/install-operator-sdk.md
internal/scaffold/ansible/go_mod.go
internal/scaffold/go_mod.go
internal/scaffold/helm/go_mod.go
version/version.go

Release bump PR for 0.16.0
Part of release process

Changes for release-v0.16.0

---

CHANGELOG.md
doc/migration/version-upgrade-guide.md
internal/scaffold/ansible/go_mod.go
internal/scaffold/go_mod.go
internal/scaffold/helm/go_mod.go
version/version.go

post v0.16.0 release updates
part of release process

Post v0.16.0 release updates

---

doc/user/olm-catalog/generating-a-csv.md

**Description of the change:** update outdated doc.
**Motivation for the change:** doc is outdated.

doc/.../generating-a-csv.md: update notes on CSV annotations

---

cmd/operator-sdk/bundle/validate.go
doc/cli/operator-sdk_bundle_validate.md

Fix typo in bundle validate help text

---

hack/check-doc-diffs.sh

add script change to exclude the proposals directory from the doc check
proposals are not being carried over to the website.

add fix to exclude the proposals directory in a docs check

---

doc/faq.md
website/content/en/docs/faq.md

Add in the FAQ info over the workaround solution for Schemas which has not the WATCH implemented. 
Closes #2649

doc: add faq scenario over Failed to watch

---

website/content/en/docs/test-framework/scorecard.md
website/content/en/docs/test-framework/writing-e2e-tests.md

update test-framework website docs to have frontmatter and make link changes that work on the website.
required for the website rendering

website - update test-framework pages

---

.travis.yml

.travis.yml: organize jobs into stages

---

doc/operator-capabilities.md
website/content/en/operator-capabilities.md

Adding additional context and questions to the operator capability levels based on additional changes I have made to https://docs.google.com/document/d/1xGRdDO04VjQSRMUHi1JfSakrpDSi-cosV5ppeWcay_A/edit# since this PR was created.
Provide a little bit more detail around each capability level.

Additional context and questions for operator capabilities

---

CHANGELOG.md

Add a line to the CHANGELOG for #2754 
Keep CHANGELOG up-to-date.

CHANGELOG.md: added line for #2754

---

internal/scaffold/go_mod_test.go
internal/scaffold/group_test.go
internal/scaffold/tools_test.go
pkg/ready/ready_test.go

Adding unit tests to increase code coverage.
Increase the code coverage

Add tests to increase code coverage

---

CHANGELOG.md

add changelog for issue 2742

---

website/content/en/docs/migration/v0.1.0-migration-guide.md
website/content/en/docs/migration/version-upgrade-guide.md

Description: Add migration docs to website.
Closes: #2694

Add migration docs to website

---

website/content/en/docs/contribution-guidelines/developer-guide.md
website/content/en/docs/contribution-guidelines/local-docs.md
website/content/en/docs/contribution-guidelines/release.md
website/content/en/docs/contribution-guidelines/reporting-issues.md
website/content/en/docs/contribution-guidelines/testing/_index.md
website/content/en/docs/contribution-guidelines/testing/running-the-tests.md
website/content/en/docs/contribution-guidelines/testing/travis-build.md

I found a few files in the contributor docs that were not included in the website.

Add frontmatter to contributor docs

---

website/content/en/docs/ansible/development-tips.md
website/content/en/docs/ansible/quickstart.md
website/content/en/docs/ansible/reference/advanced_options.md
website/content/en/docs/ansible/reference/retroactively-owned-resources.md
website/content/en/docs/golang/olm-integration/csv-annotations.md
website/content/en/docs/golang/olm-integration/generating-a-csv.md
website/content/en/docs/migration/v0.1.0-migration-guide.md
website/content/en/docs/migration/version-upgrade-guide.md
website/content/en/docs/test-framework/writing-e2e-tests.md

Fix broken internal links

---

doc/dev/developer_guide.md
website/content/en/docs/contribution-guidelines/developer-guide.md

doc: add doc over how to contribute and test the deploy of binaries #2747

---

CHANGELOG.md

**Description of the change:** update links
**Motivation for the change:** broken links

changelog: update links

---

CHANGELOG.md
doc/user/install-operator-sdk.md
internal/scaffold/ansible/go_mod.go
internal/scaffold/go_mod.go
internal/scaffold/helm/go_mod.go
version/version.go
website/content/en/docs/install-operator-sdk.md

**Description of the change:** bump operator-sdk version
**Motivation for the change:** release v0.17.0

Release v0.17.0

---

internal/scaffold/ansible/go_mod.go
internal/scaffold/go_mod.go
internal/scaffold/helm/go_mod.go
version/version.go

**Description of the change:** post-release version changes
**Motivation for the change:** post-release

Post-release v0.17.0

---

internal/scaffold/ansible/go_mod.go
internal/scaffold/go_mod.go
internal/scaffold/helm/go_mod.go
version/version.go

**Description of the change:** patch branch post-release version bump

Patch branch post-release v0.17.0

---

doc/migration/version-upgrade-guide.md
website/content/en/docs/migration/version-upgrade-guide.md

Just update the migration guide since the release was made. 
Release 0.17

upgrade guide for 0.17

---

doc/user-guide.md
website/content/en/docs/golang/quickstart.md

Adds descriptions and explanations of the various reconcile Result options
used by the memcached_controller example in the user guide.
Closes: #2593 

Add reconcile details

---

.gitmodules
website/assets/scss/_footer.scss
website/assets/scss/_functions.scss
website/assets/scss/_global.scss
website/assets/scss/_header.scss
website/assets/scss/_homepage.scss
website/assets/scss/_reset.scss
website/assets/scss/_styles_project.scss
website/assets/scss/_type.scss
website/assets/scss/_variables.scss
website/config.toml
website/layouts/404.html
website/layouts/build/baseof.html
website/layouts/docs/baseof.html
website/layouts/docs/list.html
website/layouts/docs/single.html
website/layouts/faq/baseof.html
website/layouts/index.html
website/layouts/partials/footer.html
website/layouts/partials/navbar.html

This is updating the .gitmodules to not use the submodule we had initially implemented. Now we have an override for the Hugo theme and custom layouts/scss added to the repo itself. 
@asmacdo please review

Updates submodule

---

website/assets/scss/_footer.scss
website/layouts/partials/footer.html

Added requested badge for Netlify

Adds badge to website footer for Netlify

---

website/assets/scss/_docs.scss
website/assets/scss/_global.scss
website/assets/scss/_homepage.scss
website/config.toml
website/content/en/build/_index.html
website/content/en/build/_index.md
website/layouts/_default/baseof.html
website/layouts/_default/single.html
website/layouts/build/single.html
website/layouts/docs/baseof.html
website/layouts/index.html
website/layouts/partials/footer.html

scoping the doc styling to just the content.

docs css fix

---

website/config.toml

Fix last mod on docs

---

hack/ci/check-doc-only-update.sh

**Description of the change:** add more doc ignore patterns

ci: ignore all docs

---

cmd/operator-sdk/main.go
internal/util/kubebuilder/project.go

- clean code: small nits in kbutils

clean code: small nits in kbutils

---

website/content/en/docs/kubebuilder/quickstart.md
website/content/en/docs/kubebuilder/webhooks.md

Adds documentation for implementing webhooks for Golang operators.

Add documentation for implementing webhooks in the example quickstart

---

images/scorecard-test/cmd/test/main.go
internal/scorecard/alpha/tests/bundle_test.go
internal/scorecard/alpha/tests/olm.go

Migrates the scorecard bundle tests to the scorecard2 format

Add BundleValidation test

---

website/content/en/docs/kubebuilder/references/logging.md

Description: Update the SDK logging doc to use the controller-runtime logger for Kubebuilder projects.
https://issues.redhat.com/browse/OSDK-1090

 Doc for controller-runtime logger based logging.

---

website/assets/scss/_global.scss

Fixes bugs in layout on large viewport

fix layout on website

---

internal/scorecard/alpha/scorecard.go
internal/scorecard/scorecard.go
internal/util/projutil/project_util.go
website/content/en/docs/ansible/reference/finalizers.md
website/content/en/docs/contribution-guidelines/testing/travis-build.md
website/content/en/docs/faq.md
website/content/en/docs/golang/e2e-tests.md
website/content/en/docs/golang/references/client.md
website/content/en/docs/golang/references/markers.md
website/content/en/docs/kubebuilder/migration/project_migration_guide.md
website/content/en/docs/migration/version-upgrade-guide.md
website/content/en/docs/olm-integration/generating-a-csv.md
website/content/en/docs/olm-integration/olm-deployment.md

**Description of the change:** update website doc links
**Motivation for the change:** broken links

*: update doc links

---

website/content/en/docs/olm-integration/generating-a-csv.md

Add doc for interactive prompts while generating CSV.

[doc] interactive prompts for gen-csv

---

hack/ci/setup-k8s.sh

[v0.17.x] ci: pin kind version (#3032)

---

hack/check-links.sh

link checker hugo version should match value in `netlify.toml`

Bump link checker Hugo version

---

changelog/fragments/2944-change.yaml
cmd/operator-sdk/bundle/cmd.go
cmd/operator-sdk/bundle/create.go
cmd/operator-sdk/bundle/validate.go
cmd/operator-sdk/generate/csv.go
hack/lib/test_lib.sh
hack/tests/subcommand-bundle.sh
internal/generate/olm-catalog/package_manifest.go
internal/generate/olm-catalog/package_manifest_test.go
internal/generate/testdata/non-standard-layout/expected-catalog/olm-catalog/memcached-operator/memcached-operator.package.yaml
website/content/en/docs/cli/operator-sdk.md
website/content/en/docs/cli/operator-sdk_bundle.md
website/content/en/docs/cli/operator-sdk_bundle_create.md
website/content/en/docs/cli/operator-sdk_bundle_validate.md
website/content/en/docs/cli/operator-sdk_generate_csv.md
website/content/en/docs/golang/olm-integration/generating-a-csv.md

[v0.17.x] generate csv: de-deprecate package manifests format (#2944)

---

changelog/fragments/2964-bugfix.yaml
hack/tests/integration.sh
internal/olm/operator/internal/configmap.go
internal/olm/operator/internal/deployment.go
internal/olm/operator/internal/registry.go
internal/olm/operator/manager.go
internal/util/k8sutil/k8sutil.go
test/integration/integration_helpers.go
test/integration/operator_olm_test.go

[v0.17.x] run --olm: create one ConfigMap per package (#2964)

---

changelog/fragments/csv-package-manifests-bugfix.yaml
cmd/operator-sdk/generate/csv.go

[v0.17.x] generate csv: do not generate a package manifest for bundles (#3014)

---

CHANGELOG.md

CHANGELOG.md: update links

---

changelog/fragments/3016-run-packagemanifests.yaml

Missing changelog fragment from #3016

changelog: missing from #3016

---

.github/PULL_REQUEST_TEMPLATE.md

I usually just `Cmd+A - delete` since there is too much noise ... so I'd like to try and reduce noise here.
- start each sentence with a unique verb to make it easy to scan
- add changelog template note
- remove redundant words like "please make sure to" etc
/cc @estroz

improve pull request template

---

README.md

This fixes a small nit in the [README.md](https://github.com/operator-framework/operator-sdk/blob/master/README.md) file.
Improving the documentation

README.md: fix a small nit

---

changelog/fragments/2727-helm-support-annotations.yaml
pkg/ansible/proxy/inject_owner.go
pkg/handler/enqueue_annotation.go
pkg/helm/client/client.go
pkg/helm/controller/controller.go
pkg/helm/release/manager_factory.go
pkg/k8sutil/k8sutil.go
pkg/k8sutil/k8sutil_test.go

Description: Enable resources to have Annotations, if they are cluster-scoped dependent resources.
Closes: #2727

 Enable resources to have Annotations set.

---

changelog/fragments/fix-issue-2914.yaml
pkg/kube-metrics/server.go

fix issue faced when the `healthz` endpoint is successfully called.

---

website/content/en/docs/scorecard/custom-tests.md

Update links in custom scorecard implementation doc
Co-authored-by: Jeff McCormick <jemccorm@redhat.com>

[doc] Update links in custom scorecard doc

---

internal/scaffold/ansible/go_mod.go
internal/scaffold/go_mod.go
internal/scaffold/helm/go_mod.go
version/version.go

Reverts operator-framework/operator-sdk#3056

Revert "*: post release v0.17.1"

---

CHANGELOG.md
changelog/fragments/2884-fix.yaml
changelog/fragments/2944-change.yaml
changelog/fragments/2964-bugfix.yaml
changelog/fragments/2969-bugfix.yaml
changelog/fragments/csv-package-manifests-bugfix.yaml
changelog/fragments/fix-issue-2393.yaml
changelog/fragments/fix-issue-bug-1701041.yaml
changelog/fragments/get-csv-manifest-bugfix.yaml
changelog/fragments/helm-fix-finalizer.yaml
internal/scaffold/ansible/go_mod.go
internal/scaffold/go_mod.go
internal/scaffold/helm/go_mod.go
version/version.go
website/content/en/docs/install-operator-sdk.md
website/content/en/docs/migration/v0.17.1.md

Reverts operator-framework/operator-sdk#3047

Revert "*: release v0.17.1"

---

cmd/operator-sdk/bundle/cmd.go
cmd/operator-sdk/bundle/create.go
cmd/operator-sdk/bundle/validate.go
website/content/en/docs/cli/operator-sdk_bundle.md
website/content/en/docs/cli/operator-sdk_bundle_create.md
website/content/en/docs/cli/operator-sdk_bundle_validate.md

replace  OCP enhancement #2880 links for sdk docs ones

---

internal/scaffold/ansible/go_mod.go
internal/scaffold/go_mod.go
internal/scaffold/helm/go_mod.go
version/version.go

*: post release v0.17.1 (#3056)

---

release.sh

**Description of the change:** updates to release.sh
**Motivation for the change:** release script had incorrect path and inconsistent precondition check formatting

release.sh: formatting consistency and one file path update

---

cmd/operator-sdk/bundle/validate.go
website/content/en/docs/cli/operator-sdk_bundle_validate.md

**Description of the change:** update `bundle validate` example
**Motivation for the change:** example will brake if copy/pasted
Closes #2963 

bundle validate: update example to force choosing a registry namespace

---

Makefile

**Description of the change:** reorganize recipes, update `install` to use `make build/operator-sdk`, remove extra `image-push-scorecard-test`
**Motivation for the change:** during the most recent release I noticed how cluttered the Makefile has gotten. This PR reorganizes image-related recipes into logical blocks and cleans up some other recipes

Makefile: reorganize, update recipes

---

go.mod
go.sum

Update operator-registry to the latest version that includes the fix: https://github.com/operator-framework/operator-registry/pull/334
Fixes https://github.com/operator-framework/operator-sdk/issues/2952

Update operator-registry to v1.12.4

---

Makefile

**Description of the change:** use naked `go install` in Makefile
**Motivation for the change:** Travis image builds seem to fail on some arches (?) because the current `make install` is breaking. This change reverts behavior back to before #3118.

Makefile: use `go install` with same args as `go build`

---

website/content/en/docs/scorecard/scorecard-alpha.md

Modify the scorecard-alpha doc
olm-crds-have-resources --> olm-crds-have-resources-test
olm-crds-have-validation  --> olm-crds-have-validation-test
The old doc miss the "-test"

Modify the scorecard-alpha doc

---

go.mod
go.sum

**Description of the change:** bump api repo
**Motivation for the change:** follow up from #3106.
/cc @hasbro17

deps: bump api to latest version to fix CRD conversion bug

---

internal/scaffold/ansible/go_mod.go
internal/scaffold/go_mod.go
internal/scaffold/helm/go_mod.go
version/version.go

*: post release v0.18.0

---

CONTRIBUTING.MD
website/content/en/docs/contribution-guidelines/release.md

**Description of the change:** update contribution guide/release guide in docs
**Motivation for the change:** incorrect formatting and a broken link

docs: update contribution guide formatting and a link

---

website/content/en/docs/golang/migrating-existing-apis.md

**Description of the change:** move API migration guide to golang docs section
**Motivation for the change:** it's a little confusing to have
```
Migrating Existing K8s APIs
Migration Reference
```
in the website sidebar. These docs are also only for Go operators as of now, so it makes the most sense to add them to `docs/golang`.

docs: move golang API migration doc to golang section

---

website/content/en/docs/kubebuilder/references/client.md

Update documentation for KB Client

Update KB Client Docs

---

internal/scaffold/ansible/go_mod.go
internal/scaffold/go_mod.go
internal/scaffold/helm/go_mod.go
version/version.go

*: post-release v0.18.0

---

OWNERS

Add rashmigottipati to reviewers and approvers sections in the OWNERS file.

OWNERS: Add rashmigottipati 

---

internal/plugins/helm/flags.go
internal/plugins/helm/init.go
internal/plugins/helm/plugin.go

Add the init helm plugin.
The call will be done in a follow-up.

Helm Plugin - New CMD

---

internal/plugins/helm/api.go
internal/plugins/helm/plugin.go

Add the helm plugin to scaffold new APIs.
The call will be done in a follow-up. 
blocked by #3239

Helm Plugin - Add API

---

website/config.toml
website/content/en/search.md

These values were erroneously nested under param.versions

Move config options to appropriate section

---

changelog/fragments/validation-bug-bump-api-2.yaml
go.mod
go.sum
internal/scorecard/alpha/tests/olm.go
internal/scorecard/plugins/olm_tests.go

**Description of the change:** bump api repo to v0.3.8
**Motivation for the change:** fix validation bug
/kind bug
/cc @hasbro17 @camilamacedo86 @jmccormick2001 @rashmigottipati

deps: bump api repo to v0.3.8

---

website/content/en/docs/ansible/reference/advanced_options.md
website/content/en/docs/ansible/reference/finalizers.md
website/content/en/docs/golang/quickstart.md
website/content/en/docs/golang/references/client.md
website/content/en/docs/migrating-existing-apis.md
website/content/en/docs/operator-capabilities.md

[v0.18.x] Fix links after kubernetes renamed access-kubernetes to extend-kubernes-api (#3219)

---

changelog/fragments/3221-bugfix.yaml
cmd/operator-sdk/bundle/validate.go
go.mod
go.sum
internal/scorecard/alpha/tests/olm.go

[v0.18.x] deps: bump operator-registry version (#3221)

---

changelog/fragments/validation-bug-bump-api-2.yaml
go.mod
go.sum
internal/scorecard/alpha/tests/olm.go
internal/scorecard/plugins/olm_tests.go

[v0.18.x] deps: bump api repo to v0.3.8 (#3282)

---

CHANGELOG.md
changelog/fragments/3221-bugfix.yaml
changelog/fragments/3234-arm64-tini-url.yaml
changelog/fragments/validation-bug-bump-api-2.yaml
internal/scaffold/ansible/go_mod.go
internal/scaffold/go_mod.go
internal/scaffold/helm/go_mod.go
version/version.go
website/content/en/docs/install-operator-sdk.md
website/content/en/docs/migration/v0.18.2.md

*: release v0.18.2

---

internal/scaffold/ansible/go_mod.go
internal/scaffold/go_mod.go
internal/scaffold/helm/go_mod.go
version/version.go

*: post-release v0.18.2

---

.github/PULL_REQUEST_TEMPLATE.md

Add checklist to .github/PULL_REQUEST_TEMPLATE.md for user-facing changes.
Help PR submitters and reviewers understand what extra docs
are required when making user-facing changes.

.github/PULL_REQUEST_TEMPLATE.md: add checklist

---

website/content/en/build/_index.html

Signed-off-by: dmesser <dmesser@redhat.com>
adding OLM packaging into build guide
increasing OLM awareness

plug OLM in build guide

---

website/content/en/docs/helm/reference/advanced_features.md

Small improvement to add more info to the helm upgrade release force annotation doc
**Motivation**
Clarifies better the option/feature for the helm based-Operators

doc: Add clarifications to the helm upgrade release force annotation option

---

cmd/operator-sdk/main.go

Fix Migration Link Issue
Signed-off-by: Deepak Sharma <deepshar@redhat.com>
BugFix: https://github.com/operator-framework/operator-sdk/issues/3394 
Quick Small Fix

Fix invalid migration link

---

website/content/en/docs/golang/project_migration_guide.md

fix command to create api for the new layout in the migration guide. 
**Motivation**
Closes: #3396

doc: fix command create api in the migration guide

---

website/content/en/docs/golang/project_migration_guide.md

Follow-up from #3403 
/cc @mhrivnak 

docs: add link in project migration guide

---

changelog/fragments/remove-test-framework.yaml

changelog: add test framework removal fragment

---

cmd/operator-sdk/olm/cmd_test.go
cmd/operator-sdk/olm/install_test.go
cmd/operator-sdk/olm/olm_suite_test.go
cmd/operator-sdk/olm/status_test.go
cmd/operator-sdk/olm/uninstall_test.go

Add unit tests for the cmd/olm commands
As part of ongoing work for #3246

Add unit tests for cmd/olm

---

internal/scorecard/alpha/examples/custom-scorecard-tests/go.mod
internal/scorecard/alpha/examples/custom-scorecard-tests/images/custom-scorecard-tests/cmd/test/main.go
internal/scorecard/alpha/examples/custom-scorecard-tests/internal/tests/tests.go

This commit updates scorecard example image with the latest version
of scorecard implementation.
**Checklist**

fix: Update scorecard example image

---

website/content/en/docs/golang/project_migration_guide.md
website/content/en/docs/golang/references/logging.md

Fix broken link
Docs hygiene
**Checklist**

website/content/en/docs/golang/project_migration_guide.md: fix broken link

---

website/content/en/docs/scorecard/custom-tests.md
website/content/en/docs/scorecard/scorecard.md

this PR updates a few links in the scorecard docs.
this PR is necessary to get the links correct to the source code which were moved in another preceding PR.
**Checklist**
- [x ] Add or update relevant sections of the docs website in [`website/content/en/docs`](https://github.com/operator-framework/operator-sdk/tree/master/website/content/en/docs)

update scorecard doc links

---

hack/generate/cli-doc/gen-cli-doc.go
website/content/en/docs/cli/ansible-helm/operator-sdk_add_api.md
website/content/en/docs/cli/ansible-helm/operator-sdk_build.md
website/content/en/docs/cli/ansible-helm/operator-sdk_new.md
website/content/en/docs/cli/golang/operator-sdk_build.md
website/content/en/docs/cli/golang/operator-sdk_cleanup_packagemanifests.md
website/content/en/docs/cli/golang/operator-sdk_new.md
website/content/en/docs/cli/golang/operator-sdk_run_packagemanifests.md

This fixes parsing of the 
This fixes issue #3004
This reflects properly for all the commands when the docs are generated.
**Checklist**

Added HTML entities to the < and > in markdown

---

internal/scaffold/role_test.go

Updates `internal/scaffold/role_test.go` so that the unit tests execute correctly.
The current `role_test.go` test `TestMergeRoleForResource` is passing, but it is a false positive. The test output shows errors executing the tests, but the test code does not raise assertion errors, causing the tests to incorrectly pass.
**Checklist**

internal/scaffold/role_test.go: make tests execute properly

---

internal/plugins/helm/v1/scaffolds/templates/role.go
internal/plugins/helm/v1/scaffolds/templates/role_test.go
internal/plugins/helm/v1/scaffolds/templates/testdata/testroles/valid_clusterrole/mergedRole.yaml
internal/plugins/helm/v1/scaffolds/templates/testdata/testroles/valid_role1/mergedRole.yaml
internal/plugins/helm/v1/scaffolds/templates/testdata/testroles/valid_role2/mergedRole.yaml
internal/plugins/helm/v1/scaffolds/templates/testdata/testroles/valid_role3/mergedRole.yaml
internal/plugins/helm/v1/scaffolds/templates/testdata/testroles/valid_role4/mergedRole.yaml
internal/plugins/helm/v1/scaffolds/templates/testdata/testroles/valid_role5/mergedRole.yaml
internal/plugins/helm/v1/scaffolds/templates/testdata/testroles/valid_role6/mergedRole.yaml

- Migrate relevant tests from roles to the new layout

helm: migrate tests for the new layout

---

website/content/en/docs/advanced-topics/scorecard/custom-tests.md
website/content/en/docs/advanced-topics/scorecard/scorecard.md

**Description of the change:** fix scorecard doc links
**Motivation for the change:** broken links
/cc @jmccormick2001 @jmrodri 
**Checklist**

website: fix scorecard links

---

website/content/en/docs/upgrading-sdk-version/v0.18.0.md

Fix link to that points to the work that implements liveness probe handling for Ansible-based operators that was done during the 0.18 release.
**Checklist**

website: Fix link to the pull requests that implements support for configuring a liveness probe for an Ansible operator.

---

website/content/en/docs/install-operator-sdk.md

Fix installation instructions
Docs fix
**Checklist**

[v0.19.x] website: fix install from source instructions

---

website/content/en/docs/installation/install-operator-sdk.md

Fix installation instructions
Docs fixes
I'll also backport this to v0.19
**Checklist**

website: fix install from source instructions

---

website/content/en/docs/building-operators/helm/migration.md

- Add info why use the domain ( request made by users )
- Add info regards the metrics changes 
- small improvements
See: https://deploy-preview-3554--operator-sdk.netlify.app/docs/building-operators/helm/migration/
#3327

doc: additionals and improvements on helm migration steps

---

version/version.go

*: post-release version reset

---

website/content/en/docs/building-operators/ansible/reference/scaffolding.md

Add some documentation about the deployment scaffolded.
There are some information not documented, but important for developers/users to know.

Add some documentation for Ansible operator scaffolding

---

CHANGELOG.md
changelog/fragments/ansible-operator-env.yaml
changelog/fragments/packagemanifests-from-version.yaml
internal/scaffold/ansible/go_mod.go
internal/scaffold/go_mod.go
internal/scaffold/helm/go_mod.go
version/version.go
website/content/en/docs/install-operator-sdk.md
website/content/en/docs/migration/v0.19.1.md

release v0.19.1

---

CHANGELOG.md

post release v0.19.1 update master changelog

post release v0.19.1 update master changelog

---

website/content/en/docs/building-operators/helm/reference/advanced_features/override_values.md

Fix typo
Fix typo
**Checklist**

website: fix typo in helm override_values.md

---

website/content/en/docs/building-operators/golang/operator-scope.md

The variable name is incorrect. Just fixed it.
**Checklist**

Fix variable watchNamespace name in operator-scope

---

internal/scaffold/ansible/go_mod.go
internal/scaffold/go_mod.go
internal/scaffold/helm/go_mod.go
version/version.go

/cc @joelanford @camilamacedo86 @jmrodri

*: post release v0.19.2

---

go.mod
go.sum

Bump operator-lib to v0.1.0
Use a release version of operator-lib.
**Checklist**

bump operator-lib to v0.1.0

---

internal/plugins/ansible/v1/api.go
internal/plugins/ansible/v1/init.go
internal/plugins/ansible/v1/scaffolds/internal/templates/config/crd/crd.go
internal/plugins/ansible/v1/scaffolds/internal/templates/config/rbac/leader_election_role.go
internal/plugins/ansible/v1/scaffolds/internal/templates/config/testing/debug_logs_patch.go
internal/plugins/ansible/v1/scaffolds/internal/templates/config/testing/kustomization.go
internal/plugins/ansible/v1/scaffolds/internal/templates/config/testing/manager_image.go
internal/plugins/ansible/v1/scaffolds/internal/templates/config/testing/pullpolicy/always_pull_patch.go
internal/plugins/ansible/v1/scaffolds/internal/templates/config/testing/pullpolicy/ifnotpresent_pull_patch.go
internal/plugins/ansible/v1/scaffolds/internal/templates/config/testing/pullpolicy/never_pull_patch.go
internal/plugins/helm/v1/scaffolds/init.go
internal/plugins/helm/v1/scaffolds/internal/templates/config/crd/crd.go
internal/plugins/helm/v1/scaffolds/internal/templates/config/crd/kustomization.go
internal/plugins/helm/v1/scaffolds/internal/templates/config/kdefault/kustomization.go
internal/plugins/helm/v1/scaffolds/internal/templates/config/samples/crd_sample.go
internal/plugins/helm/v1/scaffolds/internal/templates/dockerfile.go

fix the licenses of the plugins files
ensure that we are respecting the project license properly
ps: to do this pr i compare all files for we be sure over what is from sdk, modified from kb or fully kb

fix: fix licenses plugin licenses

---

CHANGELOG.md
website/content/en/docs/migration/v0.19.0.md
website/content/en/docs/scorecard/scorecard-alpha.md

Fix duplicate migration link
Docs quality is as important as software quality
**Checklist**

website/content/en/docs/migration/v0.19.0.md: fix migration link

---

internal/version/version.go
website/config.toml

post-release update
post-release update
**Checklist**

*: post-release version update

---

internal/version/version.go

Post-release version update
**Checklist**

[v1.0.x]: post-release version bump

---

.golangci.yml
internal/ansible/controller/reconcile.go
internal/ansible/proxy/requestfactory/requestinfo.go
internal/ansible/watches/watches_test.go
internal/helm/controller/reconcile.go

Signed-off-by: Ken Sipe <kensipe@gmail.com>
Add gocyclo to linter and ignoring the 4 violators.  We should limit or bring awareness of additional code that breaches gocyclo rules.
Cleaner, better, stronger code
**Checklist**

Adding  gocyclo to Linter

---

website/content/en/docs/contribution-guidelines/release.md

Update release guide so that ALL steps are numbered and co-located.
Some of the steps were hidden in paragraphs that are easily missed.
And others referenced other sections of the document which caused a
bunch of jumping back and forth during a release.
**Checklist**

Update release guide so that ALL steps are numbered and co-located.

---

changelog/fragments/3-alpha-config.yaml
internal/plugins/golang/v2/config.go
internal/plugins/golang/v2/init.go

[v0.19.x] internal/plugins: scaffold a vanilla `go.kubebuilder.io/v2` project when `--project-version=2` (#3697)

---

website/content/en/docs/building-operators/helm/quickstart.md
website/content/en/docs/building-operators/helm/tutorial.md

Just add missing pre-requirement.

doc: helm prequierements

---

website/content/en/docs/overview/_overview.md

website: fix a typo
Fix "Opearator" to "Operator" in the header
**Checklist**

Fix a typo in the header

---

netlify.toml
website/content/en/docs/advanced-topics/scorecard/custom-tests.md
website/content/en/docs/advanced-topics/scorecard/scorecard.md
website/content/en/docs/building-operators/ansible/reference/retroactively-owned-resources.md
website/content/en/docs/building-operators/golang/project_migration_guide.md
website/content/en/docs/building-operators/golang/references/envtest-setup.md
website/content/en/docs/contribution-guidelines/testing/travis-build.md
website/content/en/docs/upgrading-sdk-version/v1.0.0-alpha.1.md
website/content/en/docs/upgrading-sdk-version/v1.0.0.md

Fix broken links
CI is broken for v1.0.x branch
See #3866, #3808, and #3883
**Checklist**

[1.0.x] Fix broken links

---

internal/scaffold/ansible/go_mod.go
internal/scaffold/go_mod.go
internal/scaffold/helm/go_mod.go
version/version.go

Post-v0.19.4 version bump
Continuing the release process :)
**Checklist**

*: post release v0.19.4

---

internal/version/version.go

Post v1.0.1 version bump.
Complete the v1.0.1 release process.

internal/version/version.go: post release v1.0.1 version bump

---

.travis.yml
hack/tests/e2e-ansible-molecule.sh

molecule was probably pinned due to a dependency issue, but has since
been bumped by a major version.
**Checklist**

Pin to ansible 2.9

---

changelog/fragments/helm-json-patch-bug.yaml

**Description of the change:** see title
**Motivation for the change:** wasn't added in #3936 even though it is technically a bugfix
**Checklist**

changelog/fragments: add bugfix 3936 fragment

---

website/content/en/docs/building-operators/ansible/testing-guide.md

**Description of the change:** pin ansible module links to v2.9, the version the SDK uses
**Motivation for the change:** broken links
**Checklist**

docs/building-operators/ansible/testing-guide.md: pin links to v2.9

---

changelog/fragments/sdk-base-image.yaml
hack/image/build-sdk-image.sh
hack/image/sdk/Dockerfile

Additionally, install some additional requirements for scaffolding golang operators.
**Checklist**

Switch the base image from ubi8 to ubi8-minimal

---

proposals/automating-releases.md

**Description of the change:** added an enhancement that proposes modifying the release processes such that it is automated and simpler.
**Motivation for the change:** current release process is complex and occasionally buggy. The [goreleaser](https://goreleaser.com/) tool can encapsulate our process in a configuration file and allow one click releases.
**Checklist**

proposals/automating-releases.md: automate the release process

---

cmd/ansible-operator/main.go
cmd/helm-operator/main.go

Minor cleanup of #3974 
The comment is no longer relevant now that there are separate binaries.

cmd/ansible|helm-operator: minor nit improvements

---

.travis.yml
go.mod
release.sh
website/content/en/docs/contribution-guidelines/developer-guide.md
website/content/en/docs/installation/install-operator-sdk.md

Update go version in SDK to 1.15
In efforts to support Kubernetes 1.20
**Checklist**

Update go version in SDK

---

website/content/en/docs/building-operators/golang/advanced-topics.md

Update docs to refer to upstream implementation for Conditions.
Removed status package from operator-lib.
**Checklist**

Update docs on Conditions

---

hack/tests/subcommand-olm-install.sh

Change olm version to test in olm-subcommands.
Fixes olm-subcommand test in CI. 
**Checklist**

[v1.0.x]: Change olm version in test script

---

internal/olm/operator/registry/configmap/configmap.go
internal/olm/operator/registry/configmap/configmap_suite_test.go
internal/olm/operator/registry/configmap/configmap_test.go

Adding tests to runbundle
Testing all the files of configmap
**Checklist**

Configmap tests

---

website/config.toml

Post release 1.1

---

internal/olm/operator/registry/configmap/deployment_test.go

Added tests to deployments.go in run bundle
**Checklist**

Add tests for deployment.go

---

internal/olm/operator/registry/configmap/service_test.go

Added tests to Service.go
**Checklist**

Add tests for service.go

---

website/content/en/docs/building-operators/golang/advanced-topics.md

Revert doc on operator conditions
#3991 
**Checklist**

Revert doc on operator conditions

---

website/content/en/docs/building-operators/golang/advanced-topics.md
website/content/en/docs/building-operators/golang/project_migration_guide.md
website/content/en/docs/building-operators/golang/references/logging.md
website/content/en/docs/building-operators/golang/tutorial.md
website/content/en/docs/contribution-guidelines/testing/running-the-tests.md

Reverts operator-framework/operator-sdk#4008
See https://github.com/operator-framework/operator-sdk/pull/4008#issuecomment-718257995

Revert "[v1.0.x] Update docs on Conditions"

---

website/content/en/docs/building-operators/golang/advanced-topics.md

Revert "Update docs on Conditions" (#4008)

---

changelog/fragments/scorecard-status-descriptor-test.yaml
internal/scorecard/tests/bundle_test.go
internal/scorecard/tests/olm.go

Backport fix for #[3999](https://github.com/operator-framework/operator-sdk/issues/3999)
**Checklist**

[v1.0.x] fix: modify olm-status-descriptor-test in scorecard

---

website/content/en/docs/contribution-guidelines/releasing.md

During the last release, I forgot both of these steps because they weren't in the release guide :)

Add announcement and milestone steps to release guide

---

website/content/en/docs/olm-integration/generation.md

Add doc on validation of custom categories
Follow up of #4109 
**Checklist**

Add doc on validation of custom categories

---

website/content/en/docs/olm-integration/quickstart-package-manifests.md

**Description of the change:** update link
**Motivation for the change:** points to correct location
Closes #4113 
**Checklist**

docs/olm-integration/quickstart-package-manifests.md: fix Makefile target link

---

hack/generate/samples/internal/ansible/constants.go
hack/generate/samples/internal/ansible/molecule.go
test/e2e-ansible/e2e_ansible_cluster_test.go
test/e2e-ansible/e2e_ansible_olm_test.go
test/e2e-ansible/e2e_ansible_suite_test.go
testdata/ansible/memcached-operator/roles/memcached/tasks/main.yml

Use Memcached sample instead of re-generate the project.
operator-framework/enhancements#47

test-e2e/ansible : using samples

---

Makefile
testdata/ansible/memcached-operator/Dockerfile
testdata/ansible/memcached-operator/Makefile
testdata/ansible/memcached-operator/bundle/tests/scorecard/config.yaml
testdata/ansible/memcached-operator/config/scorecard/patches/basic.config.yaml
testdata/ansible/memcached-operator/config/scorecard/patches/olm.config.yaml
testdata/go/memcached-operator/bundle/tests/scorecard/config.yaml
testdata/go/memcached-operator/config/scorecard/patches/basic.config.yaml
testdata/go/memcached-operator/config/scorecard/patches/olm.config.yaml
testdata/helm/memcached-operator/Dockerfile
testdata/helm/memcached-operator/Makefile
testdata/helm/memcached-operator/bundle/tests/scorecard/config.yaml
testdata/helm/memcached-operator/config/scorecard/patches/basic.config.yaml
testdata/helm/memcached-operator/config/scorecard/patches/olm.config.yaml

- Makefile: bump IMAGE_VERSION to v1.2.0
- testdata: regenerate with v1.2.0 tag
**Motivation for the change:** for upcoming v1.2.0 release
**Checklist**

Makfile,testdata: bump IMAGE_VERSION to v1.2.0, regenerate samples

---

changelog/fragments/CVE-2018-1098.yaml
go.mod
go.sum

**Description of the change:** see title
**Motivation for the change:** see title
Closes #4198
**Checklist**

deps: exclude github.com/spf13/viper@v1.3.2 to fix CVE-2018-1098

---

internal/generate/clusterserviceversion/clusterserviceversion_updaters.go
internal/generate/clusterserviceversion/clusterserviceversion_updaters_test.go
internal/generate/testdata/clusterserviceversions/output/memcached-operator.clusterserviceversion.yaml
testdata/go/memcached-operator/bundle/manifests/memcached-operator.clusterserviceversion.yaml

Add targetPort while scaffolding csv
Closes: #4120 
**Checklist**

[webhook] Add targetPort while scaffolding csv

---

internal/olm/operator/registry/configmap_test.go

Added tests to configmap.go
**Checklist**

Add tests for registry/configmap.go

---

changelog/fragments/00-template.yaml

Doc the defined standard for the changelog

feat: doc standard for changelog

---

test/e2e-ansible/e2e_ansible_scorecard_test.go
test/e2e-go/e2e_go_scorecard_test.go
test/e2e-helm/e2e_helm_scorecard_test.go

Closes: https://github.com/operator-framework/operator-sdk/issues/4148

increase timeout for the scorecard tests

---

internal/olm/operator/registry/configmap/registry_test.go

Adding Ginkgo tests for Registry.go
**Checklist**

Add tests for registry.go

---

hack/generate/olm_bindata.sh
internal/bindata/olm/manifests.go

Use curl instead of wget
Closes: #4152 
Mac does not have wget pre installed
**Checklist**

fix: modify bindata script to use curl

---

internal/olm/operator/uninstall.go

Refactor cleanup to delete crds and csv instead of individually
deleting the resources referenced in install plan. OLM applies
an ownerref on every namespaced resource to the CSV, and an owner
label on cluster scoped resources. OLM and kube garbage collector
will delete the resources referenced in csv.
Rely on OLM to delete operator resources. 
**Checklist**

cleanup: refactor cleanup to let olm delete resources

---

website/content/en/docs/building-operators/golang/advanced-topics.md
website/content/en/docs/building-operators/golang/migration.md
website/content/en/docs/building-operators/golang/references/client.md
website/content/en/docs/building-operators/golang/references/logging.md
website/content/en/docs/building-operators/golang/tutorial.md
website/content/en/docs/faqs/_index.md

**Description of the change:** update old code and links in docs
**Motivation for the change:** outdated docs
**Checklist**

docs: update old links, FAQ, and Reconcile() code references

---

Makefile
testdata/ansible/memcached-operator/Dockerfile
testdata/ansible/memcached-operator/Makefile
testdata/ansible/memcached-operator/bundle/tests/scorecard/config.yaml
testdata/ansible/memcached-operator/config/scorecard/patches/basic.config.yaml
testdata/ansible/memcached-operator/config/scorecard/patches/olm.config.yaml
testdata/go/v2/memcached-operator/bundle/tests/scorecard/config.yaml
testdata/go/v2/memcached-operator/config/scorecard/patches/basic.config.yaml
testdata/go/v2/memcached-operator/config/scorecard/patches/olm.config.yaml
testdata/go/v3/memcached-operator/bundle/tests/scorecard/config.yaml
testdata/go/v3/memcached-operator/config/scorecard/patches/basic.config.yaml
testdata/go/v3/memcached-operator/config/scorecard/patches/olm.config.yaml
testdata/helm/memcached-operator/Dockerfile
testdata/helm/memcached-operator/Makefile
testdata/helm/memcached-operator/bundle/tests/scorecard/config.yaml
testdata/helm/memcached-operator/config/scorecard/patches/basic.config.yaml
testdata/helm/memcached-operator/config/scorecard/patches/olm.config.yaml
website/content/en/docs/contribution-guidelines/releasing.md

- Makefile: bump IMAGE_VERSION to v1.3.0
- docs: fix releasing.md formatting
**Motivation for the change:** pre-release step
**Checklist**

Makefile: bump IMAGE_VERSION to v1.3.0

---

internal/cmd/operator-sdk/bundle/validate/cmd.go
website/content/en/docs/cli/operator-sdk_bundle_validate.md

just add further details in the cmd doc to clarifies the same doubts that I had trying to understand it.
https://github.com/operator-framework/operator-sdk/issues/4375

Bundle validation desc

---

website/content/en/docs/building-operators/ansible/quickstart.md
website/content/en/docs/building-operators/golang/advanced-topics.md
website/content/en/docs/building-operators/golang/migration.md
website/content/en/docs/building-operators/golang/quickstart.md
website/content/en/docs/building-operators/golang/references/client.md
website/content/en/docs/building-operators/golang/references/event-filtering.md
website/content/en/docs/building-operators/golang/tutorial.md
website/content/en/docs/building-operators/helm/quickstart.md
website/content/en/docs/upgrading-sdk-version/v0.1.0-migration-guide.md

Align sample project in tutorial (go/ansible/helm) with testdata
Issue: #4381 
**Checklist**

Align tutorial imports with test samples

---

internal/testutils/utils.go

**Description of the change:** fix bad error check in testutils
**Motivation for the change:** bad error check
**Checklist**

internal/testutils: fix bad err check

---

internal/plugins/manifests/init.go
testdata/ansible/memcached-operator/Makefile
testdata/go/v2/memcached-operator/Makefile
testdata/go/v3/memcached-operator/Makefile
testdata/helm/memcached-operator/Makefile

Describe how to use the target and customize them to build the bundle and its image
closes: https://github.com/operator-framework/operator-sdk/issues/4377
**Checklist**

add a better doc/description over bundle options in the makefile

---

website/content/en/docs/building-operators/golang/advanced-topics.md

Update doc to point to upstream conditions.
`status` package from operator-lib has been removed.
closes: #4235 
Note: Need to be cherrypicked to 1.3
**Checklist**

Update doc with upstream conditions

---

README.md

Add the following useful links:
- Contribution guide
- Different communication channels like Slack, Email, Sig groups etc.
- Project meetings
This is very useful information to have available at finger tips when land on the repo. It is something that is very helpful for a new person to the project and encourages the person to contribute. It also helpful for more experienced person to be able to access easily.
**Checklist**

docs: Add useful links to the README

---

internal/plugins/scorecard/init.go

- internal/plugins/scorecard: refactor init plugin code for easier reading
**Motivation for the change:** the current `scorecard` plugin code is confusing. Template strings are easier to read and modify since the final file is more or less in front of you.
**Checklist**

internal/plugins/scorecard: refactor init plugin code for easier reading

---

website/content/en/docs/building-operators/golang/advanced-topics.md

Changes addFinalizer explicit code to controllerutil.AddFinalizer 
To stay consistent with the example (RemoveFinalizer called just above)
**Checklist**
- [-] Add a new changelog fragment in `changelog/fragments` (see [`changelog/fragments/00-template.yaml`](https://github.com/operator-framework/operator-sdk/tree/master/changelog/fragments/00-template.yaml))
- [+] Add or update relevant sections of the docs website in [`website/content/en/docs`](https://github.com/operator-framework/operator-sdk/tree/master/website/content/en/docs)

Use controllerutil.AddFinalizer

---

website/content/en/docs/building-operators/helm/tutorial.md

add line about deleting resources before uninstalling controller to helm tutorial

---

website/content/en/docs/building-operators/ansible/migration.md

fixed typo anisible->ansible

---

website/content/en/docs/building-operators/golang/tutorial.md

Definition was misspelled, I noticed while reading the website.
It is better if there is no misspelling
**Checklist**

Fix misspeling

---

code-of-conduct.md

Signed-off-by: jesus m. rodriguez <jmrodri@gmail.com>
Fix typo
Red Hat is always two words.
**Checklist**

Red Hat is two words.

---

Makefile
changelog/fragments/bugfix-3744.yaml
changelog/generated/v1.3.2.md
testdata/ansible/memcached-operator/Dockerfile
testdata/ansible/memcached-operator/Makefile
testdata/ansible/memcached-operator/bundle/tests/scorecard/config.yaml
testdata/ansible/memcached-operator/config/scorecard/patches/basic.config.yaml
testdata/ansible/memcached-operator/config/scorecard/patches/olm.config.yaml
testdata/go/v2/memcached-operator/bundle/tests/scorecard/config.yaml
testdata/go/v2/memcached-operator/config/scorecard/patches/basic.config.yaml
testdata/go/v2/memcached-operator/config/scorecard/patches/olm.config.yaml
testdata/go/v3/memcached-operator/bundle/tests/scorecard/config.yaml
testdata/go/v3/memcached-operator/config/scorecard/patches/basic.config.yaml
testdata/go/v3/memcached-operator/config/scorecard/patches/olm.config.yaml
testdata/helm/memcached-operator/Dockerfile
testdata/helm/memcached-operator/Makefile
testdata/helm/memcached-operator/bundle/tests/scorecard/config.yaml
testdata/helm/memcached-operator/config/scorecard/patches/basic.config.yaml
testdata/helm/memcached-operator/config/scorecard/patches/olm.config.yaml
website/content/en/docs/upgrading-sdk-version/v1.3.2.md

Release v1.3.2

---

Makefile
changelog/fragments/bugfix-3744.yaml
changelog/generated/v1.4.1.md
testdata/ansible/memcached-operator/Dockerfile
testdata/ansible/memcached-operator/Makefile
testdata/ansible/memcached-operator/bundle/tests/scorecard/config.yaml
testdata/ansible/memcached-operator/config/scorecard/patches/basic.config.yaml
testdata/ansible/memcached-operator/config/scorecard/patches/olm.config.yaml
testdata/go/v2/memcached-operator/bundle/tests/scorecard/config.yaml
testdata/go/v2/memcached-operator/config/scorecard/patches/basic.config.yaml
testdata/go/v2/memcached-operator/config/scorecard/patches/olm.config.yaml
testdata/go/v3/memcached-operator/bundle/tests/scorecard/config.yaml
testdata/go/v3/memcached-operator/config/scorecard/patches/basic.config.yaml
testdata/go/v3/memcached-operator/config/scorecard/patches/olm.config.yaml
testdata/helm/memcached-operator/Dockerfile
testdata/helm/memcached-operator/Makefile
testdata/helm/memcached-operator/bundle/tests/scorecard/config.yaml
testdata/helm/memcached-operator/config/scorecard/patches/basic.config.yaml
testdata/helm/memcached-operator/config/scorecard/patches/olm.config.yaml
website/content/en/docs/upgrading-sdk-version/v1.4.1.md

Release v1.4.1

---

changelog/fragments/bump-cryptography-dep.yaml
images/ansible-operator/Dockerfile

bump cryptography dep
**Checklist**

[v1.4.1] bump cryptography dep

---

Makefile
changelog/fragments/bugfix-3744.yaml
changelog/generated/v1.4.1.md
testdata/ansible/memcached-operator/Dockerfile
testdata/ansible/memcached-operator/Makefile
testdata/ansible/memcached-operator/bundle/tests/scorecard/config.yaml
testdata/ansible/memcached-operator/config/scorecard/patches/basic.config.yaml
testdata/ansible/memcached-operator/config/scorecard/patches/olm.config.yaml
testdata/go/v2/memcached-operator/bundle/tests/scorecard/config.yaml
testdata/go/v2/memcached-operator/config/scorecard/patches/basic.config.yaml
testdata/go/v2/memcached-operator/config/scorecard/patches/olm.config.yaml
testdata/go/v3/memcached-operator/bundle/tests/scorecard/config.yaml
testdata/go/v3/memcached-operator/config/scorecard/patches/basic.config.yaml
testdata/go/v3/memcached-operator/config/scorecard/patches/olm.config.yaml
testdata/helm/memcached-operator/Dockerfile
testdata/helm/memcached-operator/Makefile
testdata/helm/memcached-operator/bundle/tests/scorecard/config.yaml
testdata/helm/memcached-operator/config/scorecard/patches/basic.config.yaml
testdata/helm/memcached-operator/config/scorecard/patches/olm.config.yaml
website/content/en/docs/upgrading-sdk-version/v1.4.1.md

Reverts operator-framework/operator-sdk#4521

Revert "Release v1.4.1"

---

changelog/fragments/bump-cryptography-dep.yaml
images/ansible-operator/Dockerfile

bump cryptography dep (#4531)

---

changelog/fragments/align-kb.yaml

Closes: https://github.com/operator-framework/operator-sdk/issues/4364

supplement changelog with the fix #4364

---

internal/cmd/operator-sdk/bundle/validate/cmd.go
website/content/en/docs/cli/operator-sdk_bundle_validate.md

closes: https://github.com/operator-framework/operator-sdk/issues/4577

improve bundle output

---

website/content/en/docs/overview/_index.md

Document SDK's support to n-3 versions of OLM.
Closes: #4438 
**Checklist**

Document olm version support

---

Makefile
testdata/ansible/memcached-operator/Dockerfile
testdata/ansible/memcached-operator/Makefile
testdata/ansible/memcached-operator/bundle/tests/scorecard/config.yaml
testdata/ansible/memcached-operator/config/scorecard/patches/basic.config.yaml
testdata/ansible/memcached-operator/config/scorecard/patches/olm.config.yaml
testdata/go/v2/memcached-operator/bundle/tests/scorecard/config.yaml
testdata/go/v2/memcached-operator/config/scorecard/patches/basic.config.yaml
testdata/go/v2/memcached-operator/config/scorecard/patches/olm.config.yaml
testdata/go/v3/memcached-operator/bundle/tests/scorecard/config.yaml
testdata/go/v3/memcached-operator/config/scorecard/patches/basic.config.yaml
testdata/go/v3/memcached-operator/config/scorecard/patches/olm.config.yaml
testdata/helm/memcached-operator/Dockerfile
testdata/helm/memcached-operator/Makefile
testdata/helm/memcached-operator/bundle/tests/scorecard/config.yaml
testdata/helm/memcached-operator/config/scorecard/patches/basic.config.yaml
testdata/helm/memcached-operator/config/scorecard/patches/olm.config.yaml

release: update samples tag 1.5.0
**Checklist**

release: update samples tag 1.5.0

---

website/content/en/docs/contribution-guidelines/releasing.md
website/content/en/docs/overview/_index.md

- List the supported OLM versions in overview section of SDK docs.
- Add a step in release process to make sure the list is updated at the time of SDK release.
- Add steps in release guide on how to update bindata (since this is usually done at the time of SDK release)
**Checklist**

add doc on updating bindata in release guide

---

website/content/en/docs/faqs/_index.md

improve/fix the link only to point out for the sdk project layout doc.

doc: only point out for the project-layout

---

README.md
website/content/en/docs/contribution-guidelines/developer-guide.md
website/content/en/docs/olm-integration/generation.md

*.md: uncomment links, remove TODO's
**Motivation for the change:** leftover TODO's
**Checklist**

*.md: uncomment links, remove TODO's

---

website/content/en/docs/building-operators/golang/references/envtest-setup.md
website/content/en/docs/faqs/_index.md
website/content/en/docs/overview/cheat-sheet.md

doc: small nits fixes

---

images/ansible-operator/Dockerfile

- images/ansible-operator/Dockerfile: pin to ansible-operator-base:c6796de9b29ace4f4c737325c9037f6f715ce6d1
**Motivation for the change:** https://github.com/operator-framework/operator-sdk/runs/2098944365
**Checklist**

ansible-operator: pin to `ansible-operator-base:c6796de9b29ace4f4c737325c9037f6f715ce6d1`

---

internal/helm/controller/reconcile.go

Fix typo in helm reconciliation loop

---

internal/olm/operator/registry/index/registry_pod.go

- internal/olm/operator/registry/index: do not add secret if name is empty
**Motivation for the change:** `run bundle` will fail if `--secret-name` is not set. Follows up on #4694.
**Checklist**

internal/olm/operator/registry/index: do not add secret if name is empty

---

.github/workflows/deploy-manual.yml

- .github/workflows/deploy-manual.yml: tag using branch name
**Motivation for the change:** build from other branches aside from master
**Checklist**

workflows/deploy-manual: tag using branch name

---

.github/workflows/deploy-manual.yml

[v1.5.x] workflows/deploy-manual: tag using branch name (#4725)

---

changelog/fragments/add-declarative.yaml
internal/cmd/operator-sdk/cli/cli.go.orig
website/content/en/docs/cli/operator-sdk.md

- add the optional kb declarative plugin
**Motivation**
Add the custom option provide by KB to SDK. 
Add the custom options for we are able to check that working with
**Checklist**

plugins: add the optional kb declarative plugin

---

images/ansible-operator/Dockerfile

- images/ansible-operator/Dockerfile: bump ansible-operator to `ansible-operator-base:master-d31e4e800c0f159a2cd9f5ae375dbda00789f474`
**Motivation for the change:** see #4734 
**Checklist**

images/ansible-operator: bump ansible-operator to `ansible-operator-base:master-d31e4e800c0f159a2cd9f5ae375dbda00789f474`

---

Makefile
changelog/fragments/urllib3-1.26.4.yaml
changelog/generated/v1.5.1.md
testdata/ansible/memcached-operator/Dockerfile
testdata/ansible/memcached-operator/Makefile
testdata/ansible/memcached-operator/bundle/tests/scorecard/config.yaml
testdata/ansible/memcached-operator/config/scorecard/patches/basic.config.yaml
testdata/ansible/memcached-operator/config/scorecard/patches/olm.config.yaml
testdata/go/v2/memcached-operator/bundle/tests/scorecard/config.yaml
testdata/go/v2/memcached-operator/config/scorecard/patches/basic.config.yaml
testdata/go/v2/memcached-operator/config/scorecard/patches/olm.config.yaml
testdata/go/v3/memcached-operator/bundle/tests/scorecard/config.yaml
testdata/go/v3/memcached-operator/config/scorecard/patches/basic.config.yaml
testdata/go/v3/memcached-operator/config/scorecard/patches/olm.config.yaml
testdata/helm/memcached-operator/Dockerfile
testdata/helm/memcached-operator/Makefile
testdata/helm/memcached-operator/bundle/tests/scorecard/config.yaml
testdata/helm/memcached-operator/config/scorecard/patches/basic.config.yaml
testdata/helm/memcached-operator/config/scorecard/patches/olm.config.yaml
website/content/en/docs/installation/_index.md
website/content/en/docs/upgrading-sdk-version/v1.5.1.md

RELEASE PR v1.5.1
**Checklist**

Release v1.5.1

---

Makefile
changelog/generated/v1.6.1.md
testdata/ansible/memcached-operator/Dockerfile
testdata/ansible/memcached-operator/Makefile
testdata/ansible/memcached-operator/bundle/tests/scorecard/config.yaml
testdata/ansible/memcached-operator/config/scorecard/patches/basic.config.yaml
testdata/ansible/memcached-operator/config/scorecard/patches/olm.config.yaml
testdata/go/v2/memcached-operator/bundle/tests/scorecard/config.yaml
testdata/go/v2/memcached-operator/config/scorecard/patches/basic.config.yaml
testdata/go/v2/memcached-operator/config/scorecard/patches/olm.config.yaml
testdata/go/v3/memcached-operator/bundle/tests/scorecard/config.yaml
testdata/go/v3/memcached-operator/config/scorecard/patches/basic.config.yaml
testdata/go/v3/memcached-operator/config/scorecard/patches/olm.config.yaml
testdata/helm/memcached-operator/Dockerfile
testdata/helm/memcached-operator/Makefile
testdata/helm/memcached-operator/bundle/tests/scorecard/config.yaml
testdata/helm/memcached-operator/config/scorecard/patches/basic.config.yaml
testdata/helm/memcached-operator/config/scorecard/patches/olm.config.yaml
website/content/en/docs/installation/_index.md
website/content/en/docs/upgrading-sdk-version/v1.6.1.md

Release PR for 1.6.1
**Checklist**

Release v1.6.1

---

website/content/en/docs/installation/_index.md

[v1.5.x] Update _index.md (#4770)

---

.github/workflows/deploy-manual.yml

- .github/workflows/deploy-manual.yml: set branch name in auto-PR title and body
**Motivation for the change:** make PR title and commit descriptive.
**Checklist**

workflows/deploy-manual: set branch name in auto-PR title and body

---

website/content/en/docs/contribution-guidelines/plugins.md

After re-check the doc I noted that the suggestions made on the PR https://github.com/operator-framework/operator-sdk/pull/4732 change the meaning of the content of this section. Then, this PR has the goal of fix that.

fix the explanation

---

Makefile
changelog/generated/v1.5.2.md
testdata/ansible/memcached-operator/Dockerfile
testdata/ansible/memcached-operator/Makefile
testdata/ansible/memcached-operator/bundle/tests/scorecard/config.yaml
testdata/ansible/memcached-operator/config/scorecard/patches/basic.config.yaml
testdata/ansible/memcached-operator/config/scorecard/patches/olm.config.yaml
testdata/go/v2/memcached-operator/bundle/tests/scorecard/config.yaml
testdata/go/v2/memcached-operator/config/scorecard/patches/basic.config.yaml
testdata/go/v2/memcached-operator/config/scorecard/patches/olm.config.yaml
testdata/go/v3/memcached-operator/bundle/tests/scorecard/config.yaml
testdata/go/v3/memcached-operator/config/scorecard/patches/basic.config.yaml
testdata/go/v3/memcached-operator/config/scorecard/patches/olm.config.yaml
testdata/helm/memcached-operator/Dockerfile
testdata/helm/memcached-operator/Makefile
testdata/helm/memcached-operator/bundle/tests/scorecard/config.yaml
testdata/helm/memcached-operator/config/scorecard/patches/basic.config.yaml
testdata/helm/memcached-operator/config/scorecard/patches/olm.config.yaml
website/content/en/docs/installation/_index.md
website/content/en/docs/upgrading-sdk-version/v1.5.2.md

Release v1.5.2

---

changelog/fragments/add-pkgman-to-bundle-cmd.yaml

Add changelog on pkgman to bundle command.
**Checklist**

Add changelog for pkgman-to-bundle cmd

---

changelog/fragments/kubebuilder-v3.0.0.yaml
go.mod
go.sum
testdata/ansible/memcached-operator/bundle/manifests/memcached-operator.clusterserviceversion.yaml
testdata/ansible/memcached-operator/config/rbac/auth_proxy_client_clusterrole.yaml
testdata/ansible/memcached-operator/config/rbac/auth_proxy_role.yaml
testdata/ansible/memcached-operator/config/rbac/leader_election_role.yaml
testdata/go/v3/memcached-operator/Makefile
testdata/go/v3/memcached-operator/bundle/manifests/memcached-operator.clusterserviceversion.yaml
testdata/go/v3/memcached-operator/config/rbac/auth_proxy_client_clusterrole.yaml
testdata/go/v3/memcached-operator/config/rbac/auth_proxy_role.yaml
testdata/go/v3/memcached-operator/config/rbac/leader_election_role.yaml
testdata/helm/memcached-operator/bundle/manifests/memcached-operator.clusterserviceversion.yaml
testdata/helm/memcached-operator/config/rbac/auth_proxy_client_clusterrole.yaml
testdata/helm/memcached-operator/config/rbac/auth_proxy_role.yaml
testdata/helm/memcached-operator/config/rbac/leader_election_role.yaml

- go.mod,go.sum: bump kubebuilder to v3.0.0
**Motivation for the change:** new version
/area dependency 
**Checklist**

deps: bump kubebuilder to v3.0.0

---

Makefile
testdata/ansible/memcached-operator/Dockerfile
testdata/ansible/memcached-operator/Makefile
testdata/ansible/memcached-operator/bundle/tests/scorecard/config.yaml
testdata/ansible/memcached-operator/config/scorecard/patches/basic.config.yaml
testdata/ansible/memcached-operator/config/scorecard/patches/olm.config.yaml
testdata/go/v2/memcached-operator/bundle/tests/scorecard/config.yaml
testdata/go/v2/memcached-operator/config/scorecard/patches/basic.config.yaml
testdata/go/v2/memcached-operator/config/scorecard/patches/olm.config.yaml
testdata/go/v3/memcached-operator/bundle/tests/scorecard/config.yaml
testdata/go/v3/memcached-operator/config/scorecard/patches/basic.config.yaml
testdata/go/v3/memcached-operator/config/scorecard/patches/olm.config.yaml
testdata/helm/memcached-operator/Dockerfile
testdata/helm/memcached-operator/Makefile
testdata/helm/memcached-operator/bundle/tests/scorecard/config.yaml
testdata/helm/memcached-operator/config/scorecard/patches/basic.config.yaml
testdata/helm/memcached-operator/config/scorecard/patches/olm.config.yaml

Signed-off-by: Sujil02 <sujil.shah@gmail.com>
**Checklist**

Updating release version to v.1.7.0

---

website/content/en/docs/advanced-topics/operator-capabilities/operator-capabilities.md

**Description of the change:** fix a single typo
**Checklist**

Fix spelling

---

changelog/fragments/ubi-security.yaml
images/ansible-operator/base.Dockerfile
images/custom-scorecard-tests/Dockerfile
images/helm-operator/Dockerfile
images/operator-sdk/Dockerfile
images/scorecard-test/Dockerfile

**Description of the change:** bump image versions
**Motivation for the change:** bugfix
**Checklist**

images: bump ubi to 8.3-297.1618432833 and ubi-minimal to 8.3-298.1618432845

---

internal/olm/operator/registry/index/registry_pod.go
internal/olm/operator/registry/index/registry_pod_test.go

**Description of the change:** fix lint errors
**Motivation for the change:** somehow these snuck into master.
**Checklist**

internal/olm/operator/registry/index: fix lint errors

---

website/content/en/docs/olm-integration/quickstart-package-manifests.md

Add docs for pkgman to bundle
**Checklist**

doc: add docs for pkgman to bundle

---

website/content/en/docs/faqs/_index.md

Separate a sentence which incorrectly was rendered as part of bullet list.
**Checklist**

Fix markup

---

changelog/fragments/operator-lib-v0.4.1.yaml
go.mod
go.sum

[v1.7.x] deps: bump operator-lib to v0.4.1 (#4888)

---

Makefile
changelog/fragments/operator-lib-v0.4.1.yaml
changelog/fragments/pip3-21.1.yaml
changelog/fragments/ubi-security.yaml
changelog/generated/v1.7.2.md
testdata/ansible/memcached-operator/Dockerfile
testdata/ansible/memcached-operator/Makefile
testdata/ansible/memcached-operator/bundle/tests/scorecard/config.yaml
testdata/ansible/memcached-operator/config/scorecard/patches/basic.config.yaml
testdata/ansible/memcached-operator/config/scorecard/patches/olm.config.yaml
testdata/go/v2/memcached-operator/bundle/tests/scorecard/config.yaml
testdata/go/v2/memcached-operator/config/scorecard/patches/basic.config.yaml
testdata/go/v2/memcached-operator/config/scorecard/patches/olm.config.yaml
testdata/go/v3/memcached-operator/bundle/tests/scorecard/config.yaml
testdata/go/v3/memcached-operator/config/scorecard/patches/basic.config.yaml
testdata/go/v3/memcached-operator/config/scorecard/patches/olm.config.yaml
testdata/helm/memcached-operator/Dockerfile
testdata/helm/memcached-operator/Makefile
testdata/helm/memcached-operator/bundle/tests/scorecard/config.yaml
testdata/helm/memcached-operator/config/scorecard/patches/basic.config.yaml
testdata/helm/memcached-operator/config/scorecard/patches/olm.config.yaml
website/content/en/docs/installation/_index.md
website/content/en/docs/upgrading-sdk-version/v1.7.2.md

Release v1.7.2

---

Makefile
changelog/generated/v1.6.4.md
testdata/ansible/memcached-operator/Dockerfile
testdata/ansible/memcached-operator/Makefile
testdata/ansible/memcached-operator/bundle/tests/scorecard/config.yaml
testdata/ansible/memcached-operator/config/scorecard/patches/basic.config.yaml
testdata/ansible/memcached-operator/config/scorecard/patches/olm.config.yaml
testdata/go/v2/memcached-operator/bundle/tests/scorecard/config.yaml
testdata/go/v2/memcached-operator/config/scorecard/patches/basic.config.yaml
testdata/go/v2/memcached-operator/config/scorecard/patches/olm.config.yaml
testdata/go/v3/memcached-operator/bundle/tests/scorecard/config.yaml
testdata/go/v3/memcached-operator/config/scorecard/patches/basic.config.yaml
testdata/go/v3/memcached-operator/config/scorecard/patches/olm.config.yaml
testdata/helm/memcached-operator/Dockerfile
testdata/helm/memcached-operator/Makefile
testdata/helm/memcached-operator/bundle/tests/scorecard/config.yaml
testdata/helm/memcached-operator/config/scorecard/patches/basic.config.yaml
testdata/helm/memcached-operator/config/scorecard/patches/olm.config.yaml
website/content/en/docs/installation/_index.md
website/content/en/docs/upgrading-sdk-version/v1.6.4.md

Release v1.6.4

---

website/content/en/docs/building-operators/helm/installation.md

Fix missing link in helm overview guide
Fixes: #4938 
**Checklist**

fix: link to k8s version

---

README.md
go.sum
internal/ansible/runner/runner.go

Closes #4530
**Checklist**
Signed-off-by: rashmigottipati <chowdary.grashmi@gmail.com>

Bugfix for #4530: not able to test ansible operator locally

---

changelog/fragments/bugfix-ansible-runner.yaml

Add changelog fragment for the previously merged PR #4944
Signed-off-by: rashmigottipati chowdary.grashmi@gmail.com

Add changelog fragment for PR #4944

---

website/content/en/docs/contribution-guidelines/releasing.md
website/scripts/update_download_url.sh

Polish patch release documentation

---

changelog/fragments/community-validator.yaml
internal/cmd/operator-sdk/bundle/validate/cmd.go
internal/cmd/operator-sdk/bundle/validate/optional.go
website/content/en/docs/cli/operator-sdk_bundle_validate.md

- internal/cmd/operator-sdk/bundle/validate: remove incorrect wording, grammatical fixup
**Motivation for the change:** fixes some stuff from #4939 
**Checklist**

internal/cmd/operator-sdk/bundle/validate: remove incorrect wording, grammatical fixup

---

website/content/en/docs/building-operators/golang/operator-scope.md

website: Fix broken bundle quickstart link

---

internal/cmd/operator-sdk/pkgmantobundle/cmd.go
internal/cmd/operator-sdk/pkgmantobundle/pkgmantobundle_test.go
internal/plugins/manifests/v2/init.go
testdata/ansible/memcached-operator/Makefile
testdata/go/v2/memcached-operator/Makefile
testdata/go/v3/memcached-operator/Makefile
testdata/helm/memcached-operator/Makefile
website/content/en/docs/overview/cheat-sheet.md

Update the channel name in the e.g/comments to match with the Conv. 
**Motivation**
https://github.com/operator-framework/olm-docs/pull/162

Update the channel name in the e.g/comments to match with the Conv. 

---

Makefile
changelog/fragments/ansible-path-issue-fix.yaml
changelog/fragments/empty-patch-requests.yaml
changelog/generated/v1.9.0.md
testdata/ansible/memcached-operator/Dockerfile
testdata/ansible/memcached-operator/Makefile
testdata/ansible/memcached-operator/bundle/tests/scorecard/config.yaml
testdata/ansible/memcached-operator/config/scorecard/patches/basic.config.yaml
testdata/ansible/memcached-operator/config/scorecard/patches/olm.config.yaml
testdata/go/v2/memcached-operator/bundle/tests/scorecard/config.yaml
testdata/go/v2/memcached-operator/config/scorecard/patches/basic.config.yaml
testdata/go/v2/memcached-operator/config/scorecard/patches/olm.config.yaml
testdata/go/v3/memcached-operator/bundle/tests/scorecard/config.yaml
testdata/go/v3/memcached-operator/config/scorecard/patches/basic.config.yaml
testdata/go/v3/memcached-operator/config/scorecard/patches/olm.config.yaml
testdata/helm/memcached-operator/Dockerfile
testdata/helm/memcached-operator/Makefile
testdata/helm/memcached-operator/bundle/tests/scorecard/config.yaml
testdata/helm/memcached-operator/config/scorecard/patches/basic.config.yaml
testdata/helm/memcached-operator/config/scorecard/patches/olm.config.yaml
website/config.toml
website/content/en/docs/installation/_index.md
website/content/en/docs/upgrading-sdk-version/v1.9.0.md

This PR is for Release v1.9.0
Release v1.9.0

PR for Release v1.9.0

---

website/content/en/docs/building-operators/ansible/reference/internal_metrics.md

Added docs for the set of metrics that are internally collected by SDK for Ansible operators.
Close #3387.

Closes #3387: Docs for SDK Metrics on Ansible Operators

---

internal/annotations/metrics/metrics_suite_test.go
internal/annotations/metrics/metrics_test.go

As described in #5040
Fixes: #5040
**Checklist**

Add the missing test suite for the metrics

---

website/content/en/docs/contribution-guidelines/releasing.md

Modified Installations steps for make and gnu-sed.
helpful for new person.
**Checklist**

Modified release instructions for MacOS users

---

website/content/en/docs/olm-integration/cli-overview.md

Fix misspelling on the docs OLM Integration / CLI Overview page. 
Closes #5070
**Checklist**

docs/olm-integration: Fix misspelling

---

internal/cmd/ansible-operator/run/cmd.go
internal/cmd/helm-operator/run/cmd.go

Makes run command version details in sync with the version command
Fixes #5006 
Signed-off-by: sujil02 <sujil.shah@gmail.com>
**Checklist**

Makes run command version details in sync with the version command

---

go.mod
go.sum
internal/cmd/operator-sdk/scorecard/cmd.go
internal/scorecard/kubeclient.go
internal/scorecard/scorecard.go
internal/scorecard/storage.go
internal/scorecard/testpod.go
testdata/ansible/memcached-operator/bundle/tests/scorecard/config.yaml
testdata/go/v2/memcached-operator/bundle/tests/scorecard/config.yaml
testdata/go/v3/memcached-operator/bundle/tests/scorecard/config.yaml
testdata/helm/memcached-operator/bundle/tests/scorecard/config.yaml
website/content/en/docs/cli/operator-sdk_scorecard.md

depends on https://github.com/operator-framework/api/pull/135
**Checklist**

Add ability to configure storage to scorecard

---

CONTRIBUTING.MD
website/content/en/docs/contribution-guidelines/changelog.md

Signed-off-by: Ish Shah <ishah@redhat.com>
Addresses #3797

Add changelog info to docs and contribution guide

---

go.mod
go.sum

This PR bumps operator-lib to v0.6.0 which solves
a bug related to Operator conditions.
**Checklist**

bump operator-lib to v0.6.0

---

website/content/en/docs/building-operators/golang/webhook.md

Spelling error
Just fix of small spelling error
**Checklist**

Update webhook.md spelling error

---

internal/ansible/events/log_events.go
internal/ansible/flags/flag.go
internal/cmd/ansible-operator/run/cmd.go
website/content/en/docs/building-operators/ansible/reference/advanced_options.md

Added `--ansible-log-events` CLI Flag.
Allows more control over what logs are outputted. Also addresses #4446.

Added Ansible Log Events CLI Flag

---

Makefile
changelog/fragments/fix_order_of_generated_webhooks.yaml
changelog/fragments/uid-output.yaml
changelog/generated/v1.12.0.md
testdata/ansible/memcached-operator/Dockerfile
testdata/ansible/memcached-operator/Makefile
testdata/ansible/memcached-operator/bundle/tests/scorecard/config.yaml
testdata/ansible/memcached-operator/config/scorecard/patches/basic.config.yaml
testdata/ansible/memcached-operator/config/scorecard/patches/olm.config.yaml
testdata/go/v2/memcached-operator/bundle/tests/scorecard/config.yaml
testdata/go/v2/memcached-operator/config/scorecard/patches/basic.config.yaml
testdata/go/v2/memcached-operator/config/scorecard/patches/olm.config.yaml
testdata/go/v3/memcached-operator/bundle/tests/scorecard/config.yaml
testdata/go/v3/memcached-operator/config/scorecard/patches/basic.config.yaml
testdata/go/v3/memcached-operator/config/scorecard/patches/olm.config.yaml
testdata/helm/memcached-operator/Dockerfile
testdata/helm/memcached-operator/Makefile
testdata/helm/memcached-operator/bundle/tests/scorecard/config.yaml
testdata/helm/memcached-operator/config/scorecard/patches/basic.config.yaml
testdata/helm/memcached-operator/config/scorecard/patches/olm.config.yaml
website/config.toml
website/content/en/docs/installation/_index.md
website/content/en/docs/upgrading-sdk-version/v1.12.0.md

This is a release PR for v1.12.0
@jmrodri

Release v1.12.0

---

website/content/en/docs/building-operators/ansible/reference/proxy-vars.md
website/content/en/docs/building-operators/golang/references/proxy-vars.md
website/content/en/docs/building-operators/helm/reference/proxy-vars.md
website/content/en/docs/faqs/_index.md

No changelog is necessary, there are no new features, just docs.

Add docs for proxy-friendly operators

---

internal/scorecard/testpod.go

Signed-off-by: Ish Shah <ishah@redhat.com>
Change untar image from busybox to UBI image.
Remove dependency on dockerhub

Change Scorecard UnTar Image

---

.github/PULL_REQUEST_TEMPLATE.md

Add DCO info to PR template

---

website/content/en/docs/upgrading-sdk-version/_index.md

for #5032
It's been a while since we talked about this, so I hope this encapsulates everything we discussed about this.

Add blurb about backwards compatability to upgrading-sdk-version docs

---

website/content/en/docs/contribution-guidelines/releasing.md

Clarify Netlify docs for Major/minor releases

---

website/content/en/docs/building-operators/golang/tutorial.md

Signed-off-by: akihikokuroda <akuroda@us.ibm.com>
Adding "docker registry host" in the argument of `operator-sdk run bundle` 
Close https://github.com/operator-framework/operator-sdk/issues/4959
**Checklist**

update operator-sdk run bundle usage

---

website/content/en/docs/building-operators/golang/quickstart.md

Adding "docker registry host" in operator-sdk run bundle argument
Close https://github.com/operator-framework/operator-sdk/issues/4959
**Checklist**

update "operator-sdk run bundle" usage

---

website/content/en/docs/building-operators/golang/tutorial.md

Typo fix for definitons to definitions

---

website/content/en/docs/overview/cheat-sheet.md

Fix typo in operator

---

website/content/en/docs/building-operators/ansible/development-tips.md

Remove a blank line which caused a markdown paragraph break
Minor improvement to documentation presentation
**Checklist**

Remove extraneous blank line within paragraph

---

.github/workflows/deploy-manual.yml

follow-up of https://github.com/operator-framework/operator-sdk/pull/5354

fixup: other var

---

.github/workflows/deploy-manual.yml

fixup: copy/paste error led to empty commit in sha

---

.github/workflows/deploy-manual.yml

Fixup: copy paste error

---

website/content/en/docs/contribution-guidelines/faq.md

I've heard this question a few times now, so I started an FAQ for contributors.

start contributor faq

---

changelog/fragments/bump_kb.yaml
go.mod
go.sum
hack/generate/samples/internal/ansible/advanced_molecule.go
hack/generate/samples/internal/ansible/memcached.go
hack/generate/samples/internal/ansible/memcached_molecule.go
hack/generate/samples/internal/go/v2/memcached_with_webhooks.go
hack/generate/samples/internal/go/v3/memcached_with_webhooks.go
internal/generate/testdata/go/static/basic.multiversion.operator.yaml
internal/plugins/ansible/v1/init.go
internal/plugins/ansible/v1/scaffolds/internal/templates/makefile.go
internal/plugins/helm/v1/init.go
internal/plugins/helm/v1/scaffolds/internal/templates/config/samples/custom_resource.go
internal/plugins/helm/v1/scaffolds/internal/templates/makefile.go
test/e2e/ansible/suite_test.go
testdata/ansible/memcached-operator/Makefile
testdata/ansible/memcached-operator/bundle/manifests/memcached-operator.clusterserviceversion.yaml
testdata/ansible/memcached-operator/config/manager/manager.yaml
testdata/go/v2/memcached-operator/Makefile
testdata/go/v3/memcached-operator/Makefile
testdata/go/v3/memcached-operator/api/v1alpha1/memcached_webhook.go
testdata/go/v3/memcached-operator/api/v1alpha1/webhook_suite_test.go
testdata/go/v3/memcached-operator/bundle/manifests/memcached-operator.clusterserviceversion.yaml
testdata/go/v3/memcached-operator/config/manager/manager.yaml
testdata/helm/memcached-operator/Makefile
testdata/helm/memcached-operator/bundle/manifests/memcached-operator.clusterserviceversion.yaml
testdata/helm/memcached-operator/config/manager/manager.yaml
website/content/en/docs/building-operators/ansible/migration.md

Bump kb with the latest changes/fixes. See: https://github.com/kubernetes-sigs/kubebuilder/compare/87eb9d55ecdc...26a8982e5a73
**Motivations**
- Get the latest changes
- For Helm-bsed plugin, remove the no longer necessary customization in the resources limits

bump kb with the latest changes/fixes

---

website/content/en/docs/building-operators/helm/reference/advanced_features/override_values.md

Reorder sentence to make it easier to understand at least to a non-native-speaker.
I had to read it a few times to understand. I hope I got it right.
**Checklist**
N/A
/assign @joelanford

Reorder sentence

---

website/content/en/docs/best-practices/managing-resources.md
website/content/en/docs/best-practices/multi-tenancy.md

Fix broken link and nit layout

Fix broken link and nit layout

---

.cncf-maintainers

Remove inactive maintainer

---

internal/cmd/operator-sdk/scorecard/cmd.go

Added scorecard classname to xunit results

Add Classname to xUnit Result

---

website/content/en/docs/testing-operators/scorecard/custom-tests.md

Closes https://github.com/operator-framework/operator-sdk/issues/5432
See issue
**Checklist**

Fix example repo link in custom test

---

internal/cmd/operator-sdk/generate/bundle/bundle.go
internal/cmd/operator-sdk/generate/bundle/cmd.go
internal/plugins/manifests/v2/init.go

In flight PR for supporting SHA Digest based bundles based on the EP linked [here](https://github.com/operator-framework/enhancements/pull/107)
See also meta issue #5511 
cc: @ryantking

Adding SHA Digest based bundle options to Makefiles & CLI

---

website/content/en/docs/building-operators/ansible/reference/ansible-base-images.md

Document Ansible 2.11 base image usage

---

images/ansible-operator-2.11-preview/base.Dockerfile
images/ansible-operator/base.Dockerfile

bump pipenv in ansible base images

---

changelog/fragments/add-hybrid-helm-binary.yaml

Added changelog entry for addition of hybrid helm binary.
**Checklist**

[changelog] Add changelog for hybrid helm binary

---

hack/generate/samples/internal/ansible/constants.go
hack/generate/samples/internal/ansible/memcached_molecule.go
internal/plugins/ansible/v1/scaffolds/internal/templates/requirements.go
testdata/ansible/memcached-operator/requirements.yml
testdata/ansible/memcached-operator/roles/memcached/tasks/main.yml

Ansible metrics molecule

---

changelog/fragments/upgrades.yaml
internal/plugins/ansible/v1/scaffolds/internal/templates/requirements.go
testdata/ansible/memcached-operator/requirements.yml
website/content/en/docs/upgrading-sdk-version/version-upgrade-guide.md

Fixes #5478
add requirements `cloud.common` for ansible operator sdk
Closes #5478 
**Checklist**

add requirement cloud.common

---

website/content/en/docs/faqs/_index.md

add faq info about bundle size

add faq info about bundle size

---

website/content/en/docs/faqs/_index.md

[doc]: add info over how to keep the bundle smaller

[doc]: add info over how to keep the bundle smaller

---

images/ansible-operator-2.11-preview/Pipfile.lock
images/ansible-operator/Pipfile.lock

Closes #5550: Bumping oauthlib to 3.2.0

---

website/content/en/docs/building-operators/helm/quickstart.md

Signed-off-by: Venkat Ramaraju <vramaraj@redhat.com>
Changed "memcached" to "nginx" for helm quickstart guide.

helm quickstart run bundle command

---

website/content/en/docs/building-operators/golang/tutorial.md

Go Tutorial: Adding Note to further clarify instructions if the user receives an error
Made for Issue #5409
Adding Note to further clarify instructions if the user receives an error in tutorial.md
**Checklist**

Note to Clarify Go Operator Tutorial Manifests Error

---

website/content/en/docs/contribution-guidelines/documentation.md

Update Docsy link since the old one no longer exists.

Fixed Docsy Link

---

website/config.toml

archive 1.3 docs

---

website/config.toml

archive 1.5 docs

---

website/config.toml

archive 1.6 docs

---

website/config.toml

archive 1.7 docs

---

website/config.toml

archive 1.8 docs

---

website/config.toml

archive 1.9 docs

---

website/config.toml

archive 1.12 docs

---

website/config.toml

archive 1.13 docs

---

website/config.toml

archive 1.14 docs

---

website/config.toml

archive v1.15 docs

---

website/config.toml

archive 1.16 docs

---

website/content/en/_index.html

add newline, apparently empty commit doesn't trigger netlify

---

changelog/fragments/update-run-bundle-help.yaml
internal/cmd/operator-sdk/run/bundle/cmd.go
website/content/en/docs/cli/operator-sdk_run_bundle.md

Update the `operator-sdk run bundle` command help text to include more information regarding the intent of the command.
resolves #5721 
**Checklist**

Update run bundle help

---

internal/olm/fbcutil/util.go
internal/olm/operator/bundle/install.go
internal/olm/operator/bundleupgrade/upgrade.go
internal/olm/operator/registry/index_image.go

Refactor FBC-related functions and structs into a utility module

---

website/content/en/docs/building-operators/ansible/tutorial.md

Mention `kustomize` and RBAC in Ansible tutorial

---

website/content/en/docs/best-practices/best-practices.md

Reworded a sentence to be more clear.
Close #5732

Close #5732: Reworded sentence in best practices

---

website/content/en/docs/building-operators/golang/operator-scope.md

Signed-Off-By: Janki Chhatbar <jchhatba@redhat.com>
**Checklist**

Add a missing space

---

.github/workflows/deploy-manual.yml
.github/workflows/deploy.yml
.github/workflows/freshen-images.yml
.github/workflows/integration.yml
.github/workflows/rerun.yml
.github/workflows/test-ansible.yml
.github/workflows/test-go.yml
.github/workflows/test-helm.yml
.github/workflows/test-sanity.yml

Just update the versions used in the ci/GitHub actions
Closes: https://github.com/operator-framework/operator-sdk/issues/5839

ci: update python version from 3.6 to 3.8 and ubuntu image from ubuntu-18.04 to ubuntu-20.04

---

website/content/en/docs/best-practices/pod-security-standards.md

doc: add Pod Security Standards best practices

doc: add Pod Security Standards best practices

---

website/content/en/docs/best-practices/pod-security-standards.md

doc: (Pod Security Standards) fix nit format

doc: (Pod Security Standards) fix nit format

---

hack/generate/samples/internal/go/v3/memcached_with_webhooks.go
testdata/go/v3/memcached-operator/controllers/memcached_controller.go
website/content/en/docs/best-practices/pod-security-standards.md

doc/samples: update pod security standards to clarifies usage

doc/samples: update pod security standards to clarifies usage

---

images/custom-scorecard-tests/Dockerfile
images/helm-operator/Dockerfile
images/operator-sdk/Dockerfile
images/scorecard-test/Dockerfile

update ubi images registry.access.redhat.com/ubi8/ubi-minimal from 8.5 to 8.6
**Motivation**
Close the bot PR's
Solve tech-debt

update ubi images registry.access.redhat.com/ubi8/ubi-minimal from 8.5 to 8.6

---

.github/workflows/deploy-manual.yml
.github/workflows/deploy.yml

ci: update docker/build-push-action@v2 to docker/build-push-action@v3
**Motivation**
Close bots PRs
Solve tech - debts

ci: update docker/build-push-action@v2 to docker/build-push-action@v3

---

website/content/en/docs/best-practices/pod-security-standards.md

Better clarification on the doc

doc: best practices: pod security standards : improvements

---

website/content/en/docs/best-practices/pod-security-standards.md

**describe**
doc: fix statment

doc: fix statment

---

website/content/en/docs/best-practices/pod-security-standards.md

:doc: add improve instructions
**Motivation**
Help users to know how to install and use the tool

doc: Improve Pod Standards doc

---

changelog/fragments/add-muiltiarch.yaml
go.mod
go.sum
internal/cmd/operator-sdk/bundle/validate/cmd.go
internal/cmd/operator-sdk/bundle/validate/optional.go
website/content/en/docs/cli/operator-sdk_bundle_validate.md

Bump of the API + add the new validator

add multiarch optional validator

---

hack/generate/samples/internal/go/v3/memcached_with_webhooks.go
testdata/go/v3/memcached-operator/controllers/memcached_controller.go
website/content/en/docs/best-practices/pod-security-standards.md

doc/sample: nit clarifies the vendor caveats

doc/sample: nit clarifies the vendor caveats

---

website/content/en/docs/best-practices/pod-security-standards.md

doc: add recommendation to the best practices

doc: add recommendation to the best practices

---

hack/check-links.sh

docs-link: increase the timeout for the check
Closes: https://github.com/operator-framework/operator-sdk/issues/4172

docs-link: increase timeout for the check

---

changelog/fragments/support-arm64.yaml
internal/plugins/ansible/v1/scaffolds/internal/templates/makefile.go
internal/plugins/helm/v1/scaffolds/internal/templates/makefile.go
testdata/ansible/memcached-operator/Makefile
testdata/helm/memcached-operator/Makefile

* update Makefiles
* regenerate samples using the new update
**Checklist**

Bug 2037208: handle arm64

---

website/content/en/docs/upgrading-sdk-version/v1.23.0.md

Signed-off-by: Israel Blancas <iblancasa@gmail.com>
One step in the `upgrading to 1.23.0` section is duplicated.
Solves #6002.

Remove duplicated step for upgrading to 1.23.0

---

website/content/en/docs/building-operators/ansible/reference/internal_metrics.md

Adds appropriate metadata to Ansible's metrics doc to have it linked on
the website.
https://sdk.operatorframework.io/docs/building-operators/ansible/reference/internal_metrics/
Linking on navbar.
**Checklist**
- not required

docs: fix Ansible metrics reference

---

internal/plugins/manifests/v2/init.go
testdata/ansible/memcached-operator/Makefile
testdata/helm/memcached-operator/Makefile

Fixes #5987
Took a look at this and it looks like it should be fine.

change nongo bundle generation cruft to use updated flags

---

OWNERS_ALIASES

Update the owners to move camilamacedo86 to sdk-emeritus-approvers

Update the owners to move camilamacedo86 to sdk-emeritus-approvers

---

images/ansible-operator/Pipfile
images/ansible-operator/Pipfile.lock
images/ansible-operator/base.Dockerfile

updates to fix deploy-manual action

---

images/ansible-operator-2.11-preview/Pipfile
images/ansible-operator-2.11-preview/Pipfile.lock
images/ansible-operator-2.11-preview/base.Dockerfile

Bryce created it for ansible-operator and this one is for ansible-operator-2.11
**Checklist**

updated for ansible 2.11

---

website/content/en/docs/building-operators/golang/tutorial.md

fix default namespace description for ctrl.NewManager.
Signed-off-by: zhenpu.dong <dongzp97@163.com>

docs: update tutorial.md

---

.github/workflows/freshen-images/lib.sh

Add logging to freshen-images to determine get better insight into what's going on.
freshen-images is not updating the tagged images for some reason
**Checklist**

Fix fresh images

---

.ci/gpg/create-keyring.sh

- fix a gpg warning in actions
**Checklist**

(actions): add --mode 700 to gpg directory creation

---

website/content/en/docs/olm-integration/tutorial-package-manifests.md

Small type in the markdown
Makes the link cleaner
**Checklist**

docs: small typo update

---

.github/workflows/deploy-manual.yml
.github/workflows/freshen-images.yml
.github/workflows/test-sanity.yml

remove deprecated github actions from CI workflows

---

images/ansible-operator/Pipfile.lock

upgrading kubernetes dependency to pull fixes due to failures on FIPS enabled clusters (#5723)
https://github.com/operator-framework/operator-sdk/issues/6169
**Checklist**

update Pipfile.lock of ansible-operator

---

.cncf-maintainers
OWNERS_ALIASES

Signed-off-by: Bryce Palmer <bpalmer@redhat.com>

move everettraven from reviewer to approver

---

website/content/en/docs/best-practices/designing-lean-operators.md

Add documentation for best practices for designing lean operator.
#5382
**Checklist**

Add best practice for designing lean operator

---

.github/workflows/freshen-images/build.sh
.github/workflows/freshen-images/lib.sh

Fixes #6200 
Hopefully my bash-fu is strong.

Make refresh images github workflow push latest

---

website/content/en/docs/faqs/_index.md

Signed-off-by: Rahilsiddique <siddiquerahil19@gmail.com>
Documentation changed, example provided updated
adding modified example
changes in the reference to this issue https://github.com/operator-framework/operator-sdk/issues/6052
**Checklist**

fixed the faq documantation example

---

website/content/en/docs/building-operators/golang/tutorial.md

fix golang tutorial spec to match controller code

---

website/content/en/docs/contribution-guidelines/opening-pull-requests.md

Fixes #5685
Hopefully my markdown is right.

Add docs for PR process.

---

internal/scorecard/scorecard.go

Scorecard tests run in the `default` namespace, this change adds in all the necessary attributes in order to run in the default namespace on clusters that enforce PSA.
- Fixes: #6293 
To have scorecard work in new clusters that enforce PSA, and have any tooling that uses scorecard as a dependency also work in clusters that enforce PSA.
**Checklist**
Signed-off-by: Adam D. Cornett <adc@redhat.com>

updating PodSecurityContext and SecurityContext for scorecard pod

---

website/content/en/docs/building-operators/golang/tutorial.md

$subject
These fixes sync the examples with the code. 
Fixes parts of #6314.
**Checklist**

Fixes to golang tutorial

---

website/content/en/docs/building-operators/golang/tutorial.md

Signed-off-by: Dharmit Shah <shahdharmit@gmail.com>
$subject
To ensure that the reader doesn't get lost into trying to fix the errors reported by the IDE. GoLand reported 35 errors to me. I decided to see at the very first occurrence, which was in the `import` block. Luckily, for me, fixing that fixed all the subsequent errors.
**Checklist**

Adds note about repo flag

---

website/content/en/docs/building-operators/ansible/reference/advanced_options.md
website/content/en/docs/building-operators/ansible/reference/watches.md

state default reconcilePeriod value in ansible docs

---

hack/generate/samples/internal/go/memcached-with-customization/memcached_with_customization.go
internal/annotations/metrics/metrics.go
internal/cmd/ansible-operator/run/cmd.go

fix function name in comments

---

website/content/en/docs/best-practices/best-practices.md
website/content/en/docs/building-operators/golang/tutorial.md

Hi,
Please see individual commits for details
Kind regards

website: docs: add oxford comma + simplify example

---

go.mod
go.sum

Bump ansible operator plugin version to 1.34.1
Pulls in the fix for https://github.com/operator-framework/operator-sdk/issues/6644
**Checklist**

Bump ansible operator plugin version to 1.34.1

---

changelog/generated/v1.33.0.md
hack/generate/samples/internal/go/generate.go
hack/generate/samples/internal/go/memcached-with-customization/e2e_test_code.go
internal/helm/controller/reconcile.go
internal/helm/flags/flag.go
testdata/go/v4/memcached-operator/test/e2e/e2e_test.go
testdata/go/v4/monitoring/memcached-operator/test/e2e/e2e_test.go
website/content/en/docs/building-operators/golang/tutorial.md
website/content/en/docs/faqs/_index.md
website/content/en/docs/testing-operators/scorecard/_index.md
website/content/en/docs/upgrading-sdk-version/v1.0.0.md
website/content/en/docs/upgrading-sdk-version/version-upgrade-guide.md

chore: fix some comments

---

.cncf-maintainers

missed during #6735, this runs `make generate` to update .cncf_maintainers file.
**Checklist**

update .cncf-maintainers file

---

Makefile
changelog/generated/v1.34.2.md
testdata/go/v4/memcached-operator/Makefile
testdata/go/v4/memcached-operator/bundle/tests/scorecard/config.yaml
testdata/go/v4/memcached-operator/config/scorecard/patches/basic.config.yaml
testdata/go/v4/memcached-operator/config/scorecard/patches/olm.config.yaml
testdata/go/v4/monitoring/memcached-operator/Makefile
testdata/go/v4/monitoring/memcached-operator/bundle/tests/scorecard/config.yaml
testdata/go/v4/monitoring/memcached-operator/config/scorecard/patches/basic.config.yaml
testdata/go/v4/monitoring/memcached-operator/config/scorecard/patches/olm.config.yaml
testdata/helm/memcached-operator/Dockerfile
testdata/helm/memcached-operator/Makefile
testdata/helm/memcached-operator/bundle/tests/scorecard/config.yaml
testdata/helm/memcached-operator/config/scorecard/patches/basic.config.yaml
testdata/helm/memcached-operator/config/scorecard/patches/olm.config.yaml
website/content/en/docs/installation/_index.md
website/content/en/docs/upgrading-sdk-version/v1.34.2.md

Prep for the v1.34.2 release
Release v1.34.2 of the operator-sdk to update the version of the ansible-operator-plugin to v1.34.2, which uses go 1.21
**Checklist**

Release v1.34.2

---

go.mod
go.sum

- Updating `ansible-plugin` to the latest release version.
To get `operator-sdk` to a stable place to generate/run all plugin types.
**Checklist**

updating ansible plugin version to latest

---

testdata/go/v4/memcached-operator/Makefile
testdata/go/v4/monitoring/memcached-operator/Makefile
testdata/helm/memcached-operator/Makefile

Have `make test-sanity` pass.
**Checklist**

fixing test make files post release

---

website/content/en/docs/advanced-topics/multi-arch.md

So that docs CI passes.
CI was broken.
**Checklist**

fixing syslist.go link in website

---

Makefile
changelog/generated/v1.36.1.md
testdata/go/v4/memcached-operator/bundle/tests/scorecard/config.yaml
testdata/go/v4/memcached-operator/config/scorecard/patches/basic.config.yaml
testdata/go/v4/memcached-operator/config/scorecard/patches/olm.config.yaml
testdata/go/v4/monitoring/memcached-operator/bundle/tests/scorecard/config.yaml
testdata/go/v4/monitoring/memcached-operator/config/scorecard/patches/basic.config.yaml
testdata/go/v4/monitoring/memcached-operator/config/scorecard/patches/olm.config.yaml
testdata/helm/memcached-operator/Dockerfile
testdata/helm/memcached-operator/Makefile
testdata/helm/memcached-operator/bundle/tests/scorecard/config.yaml
testdata/helm/memcached-operator/config/scorecard/patches/basic.config.yaml
testdata/helm/memcached-operator/config/scorecard/patches/olm.config.yaml
website/content/en/docs/installation/_index.md
website/content/en/docs/upgrading-sdk-version/v1.36.1.md

Prep for the v1.36.1 release
To release:
- #6803  
**Checklist**

Release v1.36.1

---

website/content/en/docs/building-operators/golang/operator-scope.md

#6796 : Updated code snippets in documentation to definevnamespace scope in manager options
**Checklist**

Update code snippets

---

testdata/go/v4/memcached-operator/Makefile
testdata/go/v4/monitoring/memcached-operator/Makefile
testdata/helm/memcached-operator/Makefile

fix test data scaffolding

---

.github/workflows/deploy.yml
.github/workflows/freshen-images.yml
.github/workflows/integration.yml
.github/workflows/olm-check.yml
.github/workflows/test-go.yml
.github/workflows/test-helm.yml
.github/workflows/test-sample-go.yml
.github/workflows/test-sanity.yml
images/custom-scorecard-tests/Dockerfile
images/helm-operator/Dockerfile
images/operator-sdk/Dockerfile
images/scorecard-test-kuttl/Dockerfile
images/scorecard-test/Dockerfile

* Update actions to remove warnings of outdated node.

Update actions to latest

---

README.md

We need to try to communicate it as much as possible. Therefore, I am proposing we add this info as a WARNING in the README
**Checklist**

Update README.md - To add importance notice about legacy image

---

Makefile
go.mod
hack/generate/samples/internal/go/memcached-with-customization/memcached_with_customization.go
images/custom-scorecard-tests/Dockerfile
images/helm-operator/Dockerfile
images/operator-sdk/Dockerfile
images/scorecard-test-kuttl/Dockerfile
images/scorecard-test/Dockerfile
images/scorecard-untar/Dockerfile
internal/cmd/helm-operator/run/cmd.go
internal/cmd/helm-operator/version/cmd.go
internal/cmd/operator-sdk/alpha/config3alphato3/cmd.go
internal/cmd/operator-sdk/bundle/validate/cmd.go
internal/cmd/operator-sdk/olm/install.go
internal/cmd/operator-sdk/olm/status.go
internal/cmd/operator-sdk/olm/uninstall.go
internal/cmd/operator-sdk/pkgmantobundle/cmd.go
internal/cmd/operator-sdk/scorecard/cmd.go
internal/generate/packagemanifest/packagemanifest_test.go
internal/helm/controller/reconcile.go
internal/helm/flags/flag.go
internal/olm/client/status.go
internal/scorecard/kubeclient_test.go
internal/scorecard/tests/olm.go
internal/testutils/utils.go
website/content/en/docs/contribution-guidelines/developer-guide.md
website/content/en/docs/installation/_index.md

- Updating to support go 1.23
- Updating to UBI 9.5
- Updating linter version, and addressing lint failures
- Fixes: #6881 
**Checklist**

updating project to use go 1.23 and UBI 9.5

---

testdata/go/v4/memcached-operator/Makefile
testdata/go/v4/monitoring/memcached-operator/Makefile
testdata/helm/memcached-operator/Makefile

- fix scaffolding post release
**Checklist**

re-generate scaffolding post release

---

internal/helm/controller/reconcile.go

Save original status, and only update status, if there is a different between original status and the current status.
To prevent constant reconcilation of resources when there are no changes.
**Checklist**

fix constant reconcilation issue in helm controller

---

Makefile
changelog/generated/v1.39.1.md
testdata/go/v4/memcached-operator/bundle/tests/scorecard/config.yaml
testdata/go/v4/memcached-operator/config/scorecard/patches/basic.config.yaml
testdata/go/v4/memcached-operator/config/scorecard/patches/olm.config.yaml
testdata/go/v4/monitoring/memcached-operator/bundle/tests/scorecard/config.yaml
testdata/go/v4/monitoring/memcached-operator/config/scorecard/patches/basic.config.yaml
testdata/go/v4/monitoring/memcached-operator/config/scorecard/patches/olm.config.yaml
testdata/helm/memcached-operator/Dockerfile
testdata/helm/memcached-operator/Makefile
testdata/helm/memcached-operator/bundle/tests/scorecard/config.yaml
testdata/helm/memcached-operator/config/scorecard/patches/basic.config.yaml
testdata/helm/memcached-operator/config/scorecard/patches/olm.config.yaml
website/content/en/docs/installation/_index.md
website/content/en/docs/upgrading-sdk-version/v1.39.1.md

- creating a patch release for helm reconcliation logic fix
- to cut a release
**Checklist**

Release v1.39.1

---

.github/workflows/clean-unused-disk-space.sh
.github/workflows/integration.yml
.github/workflows/test-go.yml
.github/workflows/test-helm.yml
.github/workflows/test-sample-go.yml
.github/workflows/test-sanity.yml

adding logic to GHA's to remove unused diskspace

---

Makefile
changelog/generated/v1.39.2.md
testdata/go/v4/memcached-operator/bundle/tests/scorecard/config.yaml
testdata/go/v4/memcached-operator/config/scorecard/patches/basic.config.yaml
testdata/go/v4/memcached-operator/config/scorecard/patches/olm.config.yaml
testdata/go/v4/monitoring/memcached-operator/bundle/tests/scorecard/config.yaml
testdata/go/v4/monitoring/memcached-operator/config/scorecard/patches/basic.config.yaml
testdata/go/v4/monitoring/memcached-operator/config/scorecard/patches/olm.config.yaml
testdata/helm/memcached-operator/Dockerfile
testdata/helm/memcached-operator/Makefile
testdata/helm/memcached-operator/bundle/tests/scorecard/config.yaml
testdata/helm/memcached-operator/config/scorecard/patches/basic.config.yaml
testdata/helm/memcached-operator/config/scorecard/patches/olm.config.yaml
website/config.toml
website/content/en/docs/installation/_index.md
website/content/en/docs/upgrading-sdk-version/v1.39.2.md

- Creating a patch release with dependency updates
- to cut a release
**Checklist**

Release v1.39.2

---

.cncf-maintainers
OWNERS_ALIASES

🌱 OWNER-ALIAS: Update to ensure current state

---

testdata/go/v4/memcached-operator/Makefile
testdata/go/v4/monitoring/memcached-operator/Makefile
testdata/helm/memcached-operator/Makefile

fixing CI post 1.39.2 release

---

tools/scripts/fetch

To allow download upper versions
**Checklist**

🌱 fix: update kubectl fetch URL to official dl.k8s.io endpoint

---

Makefile

🌱 Upgrade k8s version used by SDK from 1.30.0 to 1.32.2

---

website/config.toml

moving 1.24 website from netlify to gh

---

Makefile
changelog/generated/v1.41.1.md
testdata/go/v4/memcached-operator/bundle/tests/scorecard/config.yaml
testdata/go/v4/memcached-operator/config/scorecard/patches/basic.config.yaml
testdata/go/v4/memcached-operator/config/scorecard/patches/olm.config.yaml
testdata/go/v4/monitoring/memcached-operator/bundle/tests/scorecard/config.yaml
testdata/go/v4/monitoring/memcached-operator/config/scorecard/patches/basic.config.yaml
testdata/go/v4/monitoring/memcached-operator/config/scorecard/patches/olm.config.yaml
testdata/helm/memcached-operator/Dockerfile
testdata/helm/memcached-operator/Makefile
testdata/helm/memcached-operator/bundle/tests/scorecard/config.yaml
testdata/helm/memcached-operator/config/scorecard/patches/basic.config.yaml
testdata/helm/memcached-operator/config/scorecard/patches/olm.config.yaml
website/content/en/docs/installation/_index.md
website/content/en/docs/upgrading-sdk-version/v1.41.1.md

Release v1.41.1
