- changelog/fragments/gitnit.yaml
- cmd/operator-sdk/new/cmd.go
- website/content/en/docs/cli/operator-sdk_new.md
- website/content/en/docs/new-cli/operator-sdk_new.md
deprecate git-init flag in the new cmd 
Has no need for we have a flag for it. Users are able to run git init when they wish.
> deprecate git-init flag

- cmd/operator-sdk/generate/bundle/bundle.go
- cmd/operator-sdk/generate/bundle/bundle_legacy.go
- cmd/operator-sdk/generate/bundle/cmd.go
- internal/plugins/golang/init.go
- website/content/en/docs/cli/operator-sdk_generate_bundle.md
* cmd/operator-sdk/generate/bundle/bundle.go: move `kustomization.yaml` template and write logic here
* internal/plugins/golang/init.go: remove the above logic
**Motivation for the change:** `generate bundle`, not `init`, now scaffolds `config/bundle/kustomization.yaml` if one does not exist. This is done so both `bundle` and `packagemanifests` subcommands can generate their own kustomize files.
> generate bundle (new CLI): write a `kustomization.yaml`

- website/content/en/docs/new-cli/operator-sdk_generate_bundle.md
Missing some CLI reference updates on the master branch.
Also not sure what's going on with the ` --project-version string` reshuffling the args.
/cc @estroz
> Update CLI reference doc

- changelog/fragments/generate-packagemanifests-legacy.yaml
- cmd/operator-sdk/generate/cmd.go
- cmd/operator-sdk/generate/packagemanifests/cmd.go
- cmd/operator-sdk/generate/packagemanifests/packagemanifests_legacy.go
- hack/tests/subcommand-generate-csv.sh
- internal/generate/clusterserviceversion/clusterserviceversion.go
- internal/generate/clusterserviceversion/clusterserviceversion_test.go
- website/content/en/docs/cli/operator-sdk_generate.md
- website/content/en/docs/cli/operator-sdk_generate_packagemanifests.md
**Description of the change:** `generate packagemanifests` subcommand for legacy project layouts. Similar implementation to the command in #3096 but no `--kustomize` or `--manifests` flags since only manifests are generated.
**Motivation for the change:** See #3096.
/kind feature
> generate: add `packagemanifests` subcommand for legacy project layouts

- cmd/operator-sdk/cli/cli.go
- go.mod
- go.sum
- internal/plugins/golang/v2/api.go
- internal/plugins/golang/v2/config.go
- internal/plugins/golang/v2/init.go
- internal/plugins/golang/v2/plugin.go
- website/content/en/docs/new-cli/operator-sdk_init.md
* cmd/operator-sdk/cli: update import path for Go plugin
* go.mod,go.sum: bump kubebuilder version
**Motivation for the change:** the `go.operator-sdk.io/v2-alpha` plugin is now in its own package. See https://github.com/kubernetes-sigs/kubebuilder/pull/1550 for a reference as to why this was done.
/cc @camilamacedo86 @hasbro17 @joelanford
> internal/plugins: move `go/v2-alpha` to its own package

- changelog/fragments/generate-kustomize.yaml
- cmd/operator-sdk/generate/cmd.go
- cmd/operator-sdk/generate/kustomize/cmd.go
- cmd/operator-sdk/generate/kustomize/manifests.go
- website/content/en/docs/new-cli/operator-sdk_generate.md
- website/content/en/docs/new-cli/operator-sdk_generate_kustomize.md
- website/content/en/docs/new-cli/operator-sdk_generate_kustomize_manifests.md
* cmd/operator-sdk/generate/kustomize: add `kustomize manifests` subcommand that generates kustomize bases and a `kustomization.yaml` in `config/manifests`. These files can be used by `generate <bundle|packagemanifests>`
**Motivation for the change:** Both `bundle` and `packagemanifests` generate the same set of kustomize files/bases, but in different directories. Instead of duplicating logic, `generate kustomize manifests` will now write operator-framework kustomize files to `config/manifests`.
Blocks #3257
/cc @hasbro17 @joelanford @jmrodri @bharathi-tenneti 
/kind feature
> generate (new CLI): add `kustomize` subcommand

- changelog/fragments/3190-add-new-cli-for-go-operators.yaml
- changelog/fragments/3190-deprecate-old-cli-for-go-operators.yaml
- changelog/fragments/3190-remove-new-cmd-for-go-operators.yaml
Add CHANGELOG fragments to document the changes for:
- removal of `--type=go` from `operator-sdk new` cmd.
- deprecation of the old CLI
- addition of the new CLI
Follow up to #3190
> Add CHANGELOG fragments for new CLI

- website/content/en/docs/golang/quickstart.md
Added the word "other" where it was missing in the golang Quickstart docs page in the reconcile reque section. 
Removing typos from the docs
> Added missing "other" in quickstart.md

- changelog/fragments/3222-none-tool.yaml
- cmd/operator-sdk/bundle/validate.go
- website/content/en/docs/cli/operator-sdk_bundle_validate.md
* cmd/operator-sdk/bundle/validate.go: add "none" option to available image builder tools
**Motivation for the change:** `ImageValidator` can now use a containerd image ("none") tool to unpack images, removing the need for an external image tool like docker/podman.
/cc @hasbro17 @jmccormick2001 @joelanford 
~Blocked by #3221~
/kind feature
> bundle validate: add tool-less image validation

- website/content/en/docs/new-cli/operator-sdk_bundle_validate.md
**Description of the change:** regenerate CLI docs.
**Motivation for the change:** missed in #3222 due to new CLI docs being made public before that PR was rebased.
> docs: regenerate 'bundle validate' cli docs

- changelog/fragments/modify-overwrite-flag.yaml
- cmd/operator-sdk/generate/bundle/cmd.go
- website/content/en/docs/cli/operator-sdk_generate_bundle.md
- website/content/en/docs/new-cli/operator-sdk_generate_bundle.md
With this PR, "generate bundle" command by default will overwrite
metadata files if already present.
> Modify default value of overwrite flag in generate-bundle cmd

- changelog/fragments/add-version-to-olm-subcommands.yaml
- cmd/operator-sdk/olm/status.go
- cmd/operator-sdk/olm/uninstall.go
- hack/tests/subcommand-olm-install.sh
- internal/olm/manager.go
- website/content/en/docs/cli/operator-sdk_olm_status.md
- website/content/en/docs/cli/operator-sdk_olm_uninstall.md
- website/content/en/docs/new-cli/operator-sdk_olm_status.md
- website/content/en/docs/new-cli/operator-sdk_olm_uninstall.md
- website/content/en/docs/olm-integration/user-guide.md
This PR adds "--version" flag to olm sub-commands, thereby enabling
users to specify the version of olm to uninstall or look up for
while fetching the status of its resources.
Allow users to override the version of OLM inferred from packageservers's CSV
Closes : #3095
> [olm-cmd] Add "version" flag to olm commands

- changelog/fragments/3234-arm64-tini-url.yaml
- internal/scaffold/ansible/dockerfilehybrid.go
> [v0.18.x] ansible: use correct download URL for tini on aarch64 (#3234)

- changelog/fragments/helm-conditional.yaml
- pkg/helm/controller/reconcile.go
- pkg/helm/internal/types/types.go
- helm: rename status conditional UpdateError to UpgradeError
- related to the changes done in the transition to using the new layout.
> helm: rename status conditional UpdateError to UpgradeError

- changelog/add-namespace-to-olm-sucommands.yaml
- cmd/operator-sdk/olm/install.go
- cmd/operator-sdk/olm/uninstall.go
- website/content/en/docs/cli/operator-sdk_olm_install.md
- website/content/en/docs/cli/operator-sdk_olm_uninstall.md
- website/content/en/docs/new-cli/operator-sdk_olm_install.md
- website/content/en/docs/new-cli/operator-sdk_olm_uninstall.md
This PR adds the "--olm-namespace" flag to OLM subcommands
(install, uninstall) to allow users to specify the
namespace where olm is to be installed or uninstalled.
Follow-up of : PR [3729](https://github.com/operator-framework/operator-sdk/pull/3279)
> [olm-cmd] Add option to specify namespace

- CHANGELOG.md
- changelog/fragments/3234-arm64-tini-url.yaml
- internal/scaffold/ansible/go_mod.go
- internal/scaffold/go_mod.go
- internal/scaffold/helm/go_mod.go
- version/version.go
- website/content/en/docs/install-operator-sdk.md
- website/content/en/docs/migration/v0.17.2.md
Needed because v0.17.1's tag returns go module errors.
> *: release v0.17.2

- cmd/operator-sdk/cli/cli.go
- cmd/operator-sdk/cli/legacy.go
- cmd/operator-sdk/run/cmd.go
- cmd/operator-sdk/run/packagemanifests/packagemanifests.go
- internal/olm/operator/packagemanifests.go
- test/e2e-new/e2e_suite.go
- test/internal/utils.go
- website/content/en/docs/cli/operator-sdk_run.md
- website/content/en/docs/new-cli/operator-sdk.md
- website/content/en/docs/new-cli/operator-sdk_run.md
- website/content/en/docs/new-cli/operator-sdk_run_packagemanifests.md
* cmd/operator-sdk: add `run packagemanifests` to new CLI, and set defaults for new project layouts
* test/e2e-new: test `run packagemanifests`
* test/utils: add utils to install/uninstall OLM
**Motivation for the change:** `run packagemanifests` should be available for new operator project layouts. This command must be used on operator projects with a package manifests format available.
/kind feature
> cli (new): add `run packagemanifests`

- website/content/en/docs/scorecard/kuttl-tests.md
this PR holds the scorecard2 'kuttl' documentation that would live on the website under the scorecard area.  This
doc describes to end users of the scorecard how the kuttl tests are set up within the scorecard config and provides
links to relevant kuttl website docs for reference.
part of the scorecard kuttl implementation that is on-going.
> initial scorecard2 kuttl user facing doc

- cmd/operator-sdk/alpha/scorecard/cmd.go
This refactors the alpha scorecard cmd to be more easily testable by making a command struct to contain the various fields, and moving the arg validation into a validate method, and the execution into a run method.
As per #3246 I'm going through the commands that will survive the KB integration and adding unit tests for the cmd layer. It is difficult to write unit tests for commands with global vars  and where the execution of the command is declared in-line in the cobra command declaration.
> refactor scorecard to be more testable

- website/content/en/docs/migration/v0.18.0.md
add the modules step to the migration guide for 0.18
**Motivation**
closes: https://github.com/operator-framework/operator-sdk/issues/3238
See: https://deploy-preview-3311--operator-sdk.netlify.app/docs/migration/v0.18.0/
> doc: add modules step for 0.18.0 migration guide

- changelog/fragments/helm-upgrade.yaml
- go.mod
- go.sum
Move helm version from `v3.2.0` to `v3.2.4`
To fix CVE-2020-4053
>In Helm greater than or equal to 3.0.0 and less than 3.2.4, a path traversal attack is possible when installing Helm plugins from a tar archive over HTTP. It is possible for a malicious plugin author to inject a relative path into a plugin archive, and copy a file outside of the intended directory. This has been fixed in 3.2.4.
https://nvd.nist.gov/vuln/detail/CVE-2020-4053
> move helm version from v3.2.0 to v3.2.4

- cmd/operator-sdk/bundle/bundle_suite_test.go
- cmd/operator-sdk/bundle/cmd_test.go
- cmd/operator-sdk/bundle/create_test.go
- cmd/operator-sdk/bundle/validate.go
- cmd/operator-sdk/bundle/validate_test.go
Add unit tests for the `bundle validate` and `bundle create` commands.
Golang unit tests are another layer of robust CI when paired with the e2e and script testing we currently have.
> add unit tests for cmd/bundle

- changelog/fragments/predicateChanges.yaml
- pkg/ansible/controller/controller.go
- pkg/ansible/run.go
- pkg/ansible/watches/watches.go
- pkg/predicate/predicate.go
- test/ansible/deploy/crds/test.example.com_selectortest_crd.yaml
- test/ansible/molecule/cluster/tasks/selector_test.yml
- test/ansible/playbooks/selector.yml
- test/ansible/watches.yaml
Added a predicate that will filter resources by labels based on the selectors that are specified in watches.yaml
**Motivation for the  #change:**
Avoid having to do an Ansible initialization before skipping an event.
Fixes the issue: https://github.com/operator-framework/operator-sdk/issues/2378
> Closes #2378: Filtering of watched resources

- cmd/operator-sdk/alpha/alpha_suite_test.go
- cmd/operator-sdk/alpha/cmd_test.go
- cmd/operator-sdk/alpha/scorecard/cmd_test.go
- cmd/operator-sdk/alpha/scorecard/scorecard_suite_test.go
Add unit tests for cmd/alpha/scorecard
Unit tests are cool. See #3246
> Add unit tests for alpha scorecard cmd

- cmd/operator-sdk/cleanup/cmd.go
- cmd/operator-sdk/cleanup/packagemanifests/packagemanifests.go
- cmd/operator-sdk/cli/cli.go
- cmd/operator-sdk/cli/legacy.go
- test/e2e-new/e2e_suite.go
- website/content/en/docs/cli/operator-sdk_cleanup.md
- website/content/en/docs/new-cli/operator-sdk.md
- website/content/en/docs/new-cli/operator-sdk_cleanup.md
- website/content/en/docs/new-cli/operator-sdk_cleanup_packagemanifests.md
* cmd/operator-sdk: enable `cleanup packagemanifests` subcommand for the new CLI.
* test/e2e-new: test `cleanup packagemanifests`
**Motivation for the change:** enable `cleanup packagemanifests` for the new CLI.
**Checklist**
- Not needed since the new CLI hasn't been released yet.
- Done in #3320.
/cc @joelanford @hasbro17 @camilamacedo86 @jmrodri
> cli (new): add `cleanup packagemanifests`

- changelog/fragments/helm-conditional-reason.yaml
- pkg/helm/controller/reconcile.go
- pkg/helm/internal/types/types.go
- Follow-up of : https://github.com/operator-framework/operator-sdk/pull/3269
- helm: rename status conditional UpdateSuccessful to UpgradeSuccessful
related to the changes done in the transition to using the new layout.
**Checklist**
> feat:  condition   status conditional UpdateSuccessful was renamed to UpgradeSuccessful

- hack/tests/check-lint.sh
- internal/plugins/golang/v2/plugin.go
- Upgrade lint version used to the latest one
- Fix go fmt check. See that we are just changing the fmt of 3 lines according to go rules which are valid for 1.13 and 1.14. See that Travis is using 1.13 and passed in the git diff test in the sanity check as well. (btw, done automatically when we run make lint-fix too).
**Motivation**
- Allow us to work across the projects without the need to delete/install diff versions of the lint
- Solve tech debts
> feat: upgrade lint version and fix gofmt

- changelog/fragments/generate-crds-non-go.yaml
- cmd/operator-sdk/generate/crds.go
Emit error message when using `operator-sdk generate crds` and `pkg/apis` directory does not exist.
`operator-sdk generate crds` is generally only supported for Go projects, which have a `pkg/apis` directory by default. Non-Go projects _could_ use this command, but only if they manually create `pkg/apis` and define Go types for their APIs.
> cmd/operator-sdk/generate/crds.go: check for existence of `pkg/apis`

- changelog/fragments/alias-run-packagemanifests.yaml
- cmd/operator-sdk/run/packagemanifests/packagemanifests.go
**Description of the change:** alias `run packagemanifests` as `run pm`.
**Motivation for the change:** the raw command name is long.
/cc @joelanford @hasbro17 
/kind feature
> `run packagemanifests`: alias as `run pm`

- cmd/operator-sdk/completion/bash_test.go
- cmd/operator-sdk/completion/cmd_test.go
- cmd/operator-sdk/completion/completion_suite_test.go
- cmd/operator-sdk/completion/zsh_test.go
Unit tests for cmd/completion. Super simple, I couldn't really think of a good way to test the actual completion bit without a text comparison.
See #3246
> add unit tests for cmd/completion

- hack/check-links.sh
- netlify.toml
- Upgrade hugo from 0.70 to 0.73
- Part of the changes made to try to solve intermittent timeout issues to check the docs which Hugo is shown not render the files with the default timeout. Such as:
```
- /target/404.html
*  External link https://gohugo.io/templates/404/ failed: response code 0 means something's wrong.
It's possible libcurl couldn't connect to the server or perhaps the request timed out.
Sometimes, making too many requests at once also breaks things.
Either way, the return message (if any) from the server is: Couldn't connect to server
- /target/docs/contribution-guidelines/local-docs/index.html
*  External link https://gohugo.io/ failed: response code 0 means something's wrong.
```
> Upgrade hugo from 0.70 to 0.73

- website/content/en/docs/helm/migration.md
- Add doc with the steps required that need be followed by the users migrate their project for the new layout. 
SDK is in a process to be integrated with KB which means that its project layouts will be aligned. More info : [Integrating Kubebuilder and Operator SDK](https://github.com/kubernetes-sigs/kubebuilder/blob/master/designs/integrating-kubebuilder-and-osdk.md). 
As part of this process, we are creating the Helm plugin. See PR https://github.com/operator-framework/operator-sdk/pull/3295. Also, we are updating the steps in the doc in the PR https://github.com/operator-framework/operator-sdk/pull/3326 and here we are adding a new doc which will help users to migrate their projects.
> doc: add migration guide for helm new layout

- cmd/operator-sdk/bundle/cmd.go
- website/content/en/docs/cli/operator-sdk_bundle.md
* cmd/operator-sdk/bundle/cmd.go: uncomment previously broken docs link
**Motivation for the change:** from #3320 
> cmd/operator-sdk/bundle/cmd.go: uncomment previously broken docs link

- Makefile
- changelog/fragments/release-helm-ansible-binaries.yaml
- hack/image/build-ansible-image.sh
- hack/image/build-helm-image.sh
- website/content/en/docs/install-operator-sdk.md
Add build targets and rules for the `ansible-operator` and `helm-operator` binaries
For 1.0, we want to remove the `operator-sdk run local` command. To continue supporting running helm and ansible operators locally, we will need these binaries to be released so that upcoming `make run` targets for those operator types can download and run the operator binaries locally.
**Checklist**
> Makefile,hack/image: build and release targets for helm and ansible binaries

- website/content/en/docs/migration/version-upgrade-guide.md
- 0.11.x: sigs.k8s.io/controller-tools@v0.2.0 no longer has the package sigs.k8s.io/controller-tools/pkg/crd/generator
- https://github.com/kubernetes-sigs/controller-tools/tree/v0.2.0/pkg/crd
- 0.14.x: add details about the new function addMetrics()
- 0.16.x: add details about multiple namespace support
Closes #3213
> docs: version upgrade guide: add more details for 0.11, 0.14, 0.16

- .travis.yml
this PR adds the scorecard-test-kuttl image to the travis configuration.  It will deploy the scorecard-test-kuttl (amd64) image to quay.io.  Other architectures will require kuttl base images to also support more than just amd64 architectures and will be added in follow on work if required.
a new scorecard-test-kuttl image is made available and meant to be released.
**Checklist**
> Scorecard kuttl image

- Makefile
Parse package name out of binary `build/%` target.
Simplify build target and don't stomp out `build/%.asc` target.
> Makefile: fix build/% rule

- website/content/en/docs/ansible/reference/watches.md
Selectors help clients/users can identify a set of objects based on their labels.
Added the selector feature to docs table with description, default, and link to Kubernetes API.
> docs: Added the selector feature to docs

- cmd/operator-sdk/generate/bundle/bundle.go
- cmd/operator-sdk/generate/internal/genutil.go
- cmd/operator-sdk/generate/kustomize/manifests.go
- cmd/operator-sdk/generate/packagemanifests/packagemanifests.go
- internal/util/projutil/project_util.go
- Make ProjectTypes helpers looking for the type in the PROJECT file when it exists. 
- To allow the SDK CLI commands works properly for the new layout 
- Follow up the same standard for all types shows very beneficial and increase the manutence ability
> feat: allow know the project type by the config file

- website/content/en/docs/golang/project_migration_guide.md
> Fix typos in migration guide

- website/content/en/docs/golang/installation.md
- website/content/en/docs/golang/project_migration_guide.md
**Description of the change:** fix go version in docs
**Motivation for the change:** go version is incorrect.
Closes #3400 
> docs: fix go version

- internal/plugins/golang/v2/api.go
- internal/plugins/golang/v2/init.go
- internal/util/plugins/makefile.go
- internal/util/plugins/samples.go
Just moving the SDK scaffolds for plugins to the sdk dir and allow it to be re-used. 
The SDK scaffolds will be required to other plugins. See for example https://github.com/operator-framework/operator-sdk/pull/3295
**Checklist**
> cleanup: keeping sdk scaffolds centralized

- website/content/en/docs/helm/reference/advanced_features.md
Nit : helm/doc:replace the word update to upgrade in the info log
Related to : https://github.com/operator-framework/operator-sdk/issues/3346
> helm/doc:replace the word update to upgrade in the info log

- changelog/fragments/helm-upgrade-rename.yaml
- pkg/helm/controller/reconcile.go
- pkg/helm/release/manager.go
- Follow up of: https://github.com/operator-framework/operator-sdk/pull/3345 and https://github.com/operator-framework/operator-sdk/pull/3269
- Renamed verb usage for Helm-based operators from "Update" to "Upgrade" 
- For https://github.com/operator-framework/operator-sdk/issues/3346
to better align with Helm nomenclature.
**Checklist**
- [Not applicable] Add or update relevant sections of the docs website in [`website/content/en/docs`](https://github.com/operator-framework/operator-sdk/tree/master/website/content/en/docs)
> helm-operator: use "Upgrade" instead of "Update" in var/fn names

- changelog/fragments/fix-find-metadata-dir.yaml
- internal/registry/labels.go
Bug fix for `regisry.FindMetadataDir`
Fewer bugs :)
**Checklist**
> internal/registry/labels.go: FindMetadataDir fix

- changelog/fragments/rm-legacy-go.yaml
- changelog/fragments/rm-legacy-run.yaml
Add missing fragment file for #3385, fix typo for #3406 
1.0 prep
**Checklist**
> changelog/fragments: add rm-legacy-go.yaml and rm-legacy-run.yaml

- internal/olm/operator/internal/registry_pod.go
- internal/olm/operator/internal/registry_pod_test.go
https://issues.redhat.com/browse/OSDK-1304
In this PR,
- Create a kubernetes clientset and using the client, create a registry pod using a registryImage and set the container command (entrypoint) to:
`{{/bin/bash -c ‘ \
/bin/mkdir -p /database && \
/bin/opm registry add -d /database/index.db -b {.BundleImage} && \
/bin/opm registry serve -d /database/index.db’}}`
- Before creation, verify if the registry pod already exists and return the existing pod if found
- After creation of the pod, verify that it was successfully created by polling and verifying that pod status is running
- Added functionality for capturing pod logs 
- Manual testing is done, unit testing is in progress
Note: Once the CLI code is ready, building the config and creating the client will …
> [run bundle]: Create bundle registry server

- Makefile
Removed the escape characters ( \ ) from the operator-sdk binary build, and added an -E flag to the sed command.
Allows better parsing of command, especially by OSX.
**Checklist**
> Removing escape characters in the operator-sdk binary build

- changelog/fragments/scorecard-label-perms.yaml
- internal/scorecard/alpha/tar.go
Fixed issue with generation of the bundle.tar.gz config map that caused permission errors when the test pod tried to load the bundle.
Fix a bug that causes the default test pods to fail.
**Checklist**
> scorecard: fix label permission bug

- pkg/ansible/watches/watches.go
Use defined consts rather than literals when referencing environment variables.
Avoid hard-coded strings in source code.
**Checklist**
No user facing changes introduced.
> Trivial - use consts rather than literals for env vars

- website/content/en/docs/contribution-guidelines/backport-policy.md
- website/content/en/docs/contribution-guidelines/release.md
* docs/contribution-guidelines/release.md: add info on website changes and ansible/helm operator release binaries
**Motivation for the change:** new release steps are necessary to document.
/cc @asmacdo @camilamacedo86 @varshaprasad96 
**Checklist**
> contrib: update release guide with helm/ansible operator and website info

- website/content/en/docs/ansible/development-tips.md
- website/content/en/docs/ansible/reference/watches.md
- add info over reconcilePeriod similar to the sync period attribute of [manager.Options](https://godoc.org/sigs.k8s.io/controller-runtime/pkg/manager#Options) to make clear that users should avoid small periods
- clarifies that users are able to create many CRD's and use the APIs to persuade the concepts such as single responsibility, cohesion and encapsulation which would bring more flexibility and optimization since they are able to do configurations per GKV via the watches file. 
https://github.com/operator-framework/operator-sdk/issues/3364
> doc: add extra info over ansible watches and reconcile period

- cmd/operator-sdk/cleanup/packagemanifests/packagemanifests.go
Refactor cmd/cleanup/packagemanifests to be more testable. This includes breaking up the functionality into validate and run method that can be individually tested.
Ongoing work for #3246
> refactor cmd/cleanup/packagemanifests to be more testable

- hack/lib/common.sh
Change `arch` call to `uname -m` since not all distros have `arch` (not present in Arch Linux, ironically enough)
Change `uname` call to `uname -s` to be specific
See above
**Checklist**
> hack/lib/common.sh: use uname instead of arch, use explicit flags

- changelog/fragments/ansible-operator-optional-case.yml
- pkg/ansible/runner/runner.go
- pkg/ansible/watches/watches.go
- pkg/ansible/watches/watches_test.go
- test/ansible/deploy/crds/test.example.com_casetest_crd.yaml
- test/ansible/molecule/cluster/tasks/case_test.yml
- test/ansible/playbooks/case.yml
- test/ansible/playbooks/secret.yml
- test/ansible/watches.yaml
- website/content/en/docs/ansible/quickstart.md
- website/content/en/docs/ansible/reference/watches.md
Adds the `snakeCaseParameters` (default true) parameter to the watches.yaml, which disables the camelCase -> snake_case conversion
For some users this causes more problems than it solves, and it definitely should be optional.
Closes #1770
> Make Ansible Operator parameter case conversion optional

- changelog/fragments/helm-metrics-addr.yaml
- cmd/helm-operator/main.go
- internal/plugins/helm/v1/scaffolds/templates/manager/config.go
- internal/plugins/helm/v1/scaffolds/templates/metricsauth/auth_proxy_patch.go
- pkg/helm/flags/flag.go
Add `--metrics-addr` flag for Helm operator
#2451 #3358 
**Checklist**
> cmd/helm-operator/main.go: add --metrics-addr flag

- changelog/fragments/enqueue-object-handler.yml
- pkg/ansible/controller/controller.go
- pkg/handler/instrumented_enqueue_object.go
- pkg/handler/internal/metrics/metrics.go
- pkg/helm/controller/controller.go
Description: Add new handler for metrics which can be registered with controller-runtime registry, and wraps existing `EnqueueResuestForObject`, for both Ansible and Helm controllers.
Motivation: This PR addresses current complexity around exposing primary resource metrics in SDK.
/kind feature
>  Add new handler for metrics

- changelog/fragments/modify-ansible-flags.yaml
- cmd/ansible-operator/main.go
- pkg/ansible/flags/flag.go
- pkg/ansible/watches/watches.go
- pkg/ansible/watches/watches_test.go
- website/content/en/docs/ansible/reference/advanced_options.md
This PR:
* Deprecates --max-workers flag
* Adds --max-concurrent-reconciles flag
* Adds MAX_CONCURRENT_RECONCILES_<group>_<kind> global variable
* Update relevant documentation
Effort to change ansible operator flags to match controller-runtime constructs.
**Checklist**
> ansible: rename cmd line flag and add global variable

- changelog/fragments/helm-leader-election.yaml
- cmd/helm-operator/main.go
- hack/tests/e2e-helm.sh
- internal/plugins/helm/v1/scaffolds/init.go
- internal/plugins/helm/v1/scaffolds/templates/makefile.go
- internal/plugins/helm/v1/scaffolds/templates/manager/config.go
- internal/plugins/helm/v1/scaffolds/templates/metricsauth/auth_proxy_patch.go
- pkg/helm/flags/flag.go
Helm operator: add leader election flags, use controller-runtime leader election
In general, the controller-runtime leader election method (lease-based) is preferable for most use cases. In the future, if there is a use case to support leader-for-life, we can add another flag to let operator developers choose their leader election mechanism.
**Checklist**
> Helm: add leader election flags, use lease-based election

- cmd/operator-sdk/run/cmd_test.go
- cmd/operator-sdk/run/packagemanifests/packagemanifests.go
- cmd/operator-sdk/run/packagemanifests/packagemanifests_suite_test.go
- cmd/operator-sdk/run/packagemanifests/packagemanifests_test.go
- cmd/operator-sdk/run/run_suite_test.go
Add unit tests for the stuff that's staying in cmd/run. Includes a minor refactor to put the arg parsing into a validate method so it's testable, but omitting a separate PR as no functionality changed. Hope that's OK?
Also added a dir with a dummy project file to test the behavior where it's supposed to automatically set the manifest dir if a project file is present. I opted to put a real file on disk and include it in the repo as opposed to writing something temp from the code. Let me know if the other way would be preferable.
As part of ongoing work for #3246
> add unit tests for cmd/run

- changelog/fragments/rm-helm-metrics.yml
- cmd/helm-operator/main.go
- hack/tests/e2e-helm.sh
- internal/plugins/helm/v1/scaffolds/templates/manager/config.go
Description: Remove kubemetrics package reference logic from `cmd/helm-operator/main.go`.
Motivation: Now that we have handler to setup metrics on primary resources using `handler.InstrumentedEnqueueRequestForObject{}`, we do not separate `KubeMetrics` to setup metrics.
Partially closes, #3354
> Remove metrics logic from cmd/helm-operator/main.go

- .gitignore
One-liner to fix gitignore path for scorecard example
Follow-up on moving alpha scorecard to scorecard.
> .gitignore: ignore scorecard example go.sum

- cmd/operator-sdk/version/cmd.go
- cmd/operator-sdk/version/cmd_test.go
- cmd/operator-sdk/version/version_suite_test.go
Add unit tests for cmd/version. Also includes a small refactor, putting the cmd logic into a run() method so it can be tested.
Ongoing work as part of #3246
> Add unit tests for cmd/version

- CHANGELOG.md
- website/content/en/docs/building-operators/helm/migration.md
- website/content/en/docs/building-operators/helm/quickstart.md
- website/content/en/docs/building-operators/helm/reference/advanced_features.md
- website/content/en/docs/building-operators/helm/reference/scaffolding.md
- website/content/en/docs/building-operators/helm/reference/watches.md
- website/content/en/docs/upgrading-sdk-version/v0.19.0.md
Provide the same documentation and steps using the helm plugin. See the PR #3421 which adds the plugin. 
- Update all related info in the Helm documentation  
- Create a new sub-directory called Legacy to keep the previous docs
**Motivation**
SDK is in a process to be integrated with KB which means that its project layouts will be aligned. More info : [Integrating Kubebuilder and Operator SDK](https://github.com/kubernetes-sigs/kubebuilder/blob/master/designs/integrating-kubebuilder-and-osdk.md) and [Extensible CLI and Scaffolding Plugins](https://github.com/kubernetes-sigs/kubebuilder/blob/master/designs/extensible-cli-and-scaffolding-plugins-phase-1.md).
> docs: update helm docs for the new layout

- cmd/ansible-operator/main.go
- pkg/ansible/flags/flag.go
Removes max-workers flag for ansible operators. They have been
replaced by --max-concurrent-reconciles.
Follow up of #3435 on changing an implementation. 
**Checklist**
> fix: remove max-workers flag for ansible

- changelog/fragments/rename-max-workers.yaml
- changelog/fragments/replace-max-workers.yaml
- cmd/ansible-operator/main.go
- cmd/helm-operator/main.go
- pkg/ansible/controller/controller.go
- pkg/ansible/watches/testdata/valid.yaml.tmpl
- pkg/ansible/watches/watches.go
- pkg/ansible/watches/watches_test.go
- pkg/helm/controller/controller.go
- pkg/helm/flags/flag.go
- website/content/en/docs/building-operators/helm/reference/advanced_features.md
This commit:
- Adds --max-concurrent-reconciles flag to helm binary
- Rename MaxWorkers to MaxConcurrentReconciles in ansible/helm
implementations.
Fixes: #3360 
Modify operator flags in ansible/helm operators to match controller-runtime constructs.
**Checklist**
> ansible/helm: Rename max-workers to max-concurrent-reconciles

- internal/plugins/helm/v1/scaffolds/templates/role.go
Remove operator RBAC rules that give it permission to manage services and service monitors.
Now that the helm-operator no longer creates its own metrics service and service monitor, it doesn't need permissions to do these things.
> internal/plugins/helm/v1/scaffolds/templates/role.go: remove metrics rules

- changelog/fragments/rm-ansible-metrics.yml
- cmd/ansible-operator/main.go
- hack/tests/e2e-ansible.sh
- internal/scaffold/role.go
- internal/scaffold/role_test.go
- test/ansible/molecule/cluster/tasks/servicemonitor_test.yml
Description: Remove kubemetrics package reference logic from cmd/ansible-operator/main.go.
Remove corresponding checks from hack/tests/e2e-ansible.sh
Motivation: Now that we have handler to setup metrics on primary resources using handler.InstrumentedEnqueueRequestForObject{}, we do not separate KubeMetrics to setup metrics.
> Remove metrics logic from cmd/anisble-operator/main.go

- changelog/fragments/scorecard-default-ns.yaml
- cmd/operator-sdk/scorecard/cmd.go
- cmd/operator-sdk/scorecard/cmd_test.go
- internal/scorecard/kubeclient.go
- internal/scorecard/kubeclient_test.go
- website/content/en/docs/cli/operator-sdk_scorecard.md
add logic in scorecard command to lookup the namespace, if not set on the command line, from the 
kubeconfig
Closes #3422 
**Checklist**
> scorecard - lookup namespace from kubeconfig

- internal/plugins/helm/v1/api.go
- internal/plugins/helm/v1/scaffolds/api.go
- internal/plugins/helm/v1/scaffolds/init.go
- internal/plugins/helm/v1/scaffolds/templates/role.go
- internal/plugins/helm/v1/scaffolds/templates/role_test.go
In the helm project scaffolding, move initial generation of `config/rbac/role.yaml` to the `init` plugin.
A project without an API should still have a valid base role.
> internal/plugins/helm: initialize manager role; other minor flag usage fixes

- hack/tests/e2e-helm.sh
- internal/plugins/helm/v1/scaffolds/templates/makefile.go
- test/e2e-helm/e2e_helm_cluster_test.go
- test/e2e-helm/e2e_helm_local_test.go
- test/e2e-helm/e2e_helm_olm_test.go
- test/e2e-helm/e2e_helm_suite_test.go
- test/e2e/e2e_suite.go
- test/internal/utils.go
- Replace the tests in the shell for Go
- Centralize ReplaceInFile in the utils 
**Motivation of the change:**
Replace the tests made to check the helm implementation in a shell script for golang
> helm:replace test in shell for go

- changelog/fragments/ansible-metrics-addr.yml
- cmd/ansible-operator/main.go
- pkg/ansible/flags/flag.go
Description of the change:
Add --metrics-addr flag for Ansible operator, and change to the port to 8080.
Closes partially: #3358
> Add Ansible metrics address flag

- changelog/fragments/ansible-leader-election.yaml
- cmd/ansible-operator/main.go
- internal/scaffold/ansible/deploy_operator.go
- pkg/ansible/flags/flag.go
Ansible operator: add leader election flags, use controller-runtime leader election
In general, the controller-runtime leader election method (lease-based) is preferable for most use cases. In the future, if there is a use case to support leader-for-life, we can add another flag to let operator developers choose their leader election mechanism.
**Checklist**
> Ansible: add leader election flags, use lease-based election

- go.mod
- go.sum
Pull in CVE-2020-14040 fixed by golang.org/x/text v0.3.3.
**Checklist**
> Update golang.org/x/text to v0.3.3

- changelog/fragments/modify-ansible-flags.yaml
Reword changelog fragment for removing --max-workers flag in ansible.
Follow up from #3456 
**Checklist**
> fix: reword changelog fragment for renaming flag

- website/content/en/docs/advanced-topics/scorecard/custom-tests.md
- website/content/en/docs/advanced-topics/scorecard/kuttl-tests.md
- website/content/en/docs/advanced-topics/scorecard/scorecard.md
this PR updates the scorecard website docs to have the same command format when 'operator-sdk scorecard' is referenced.
make things more clearer to the reader as to the fact that a bundle is a positional argument in all 'operator-sdk scorecard' command examples.
**Checklist**
> update scorecard docs to be consistent in command examples

- CHANGELOG.md
- website/content/en/docs/golang/quickstart.md
fix the broken link for controller example on 0.19
**Motivation**
Closes: https://github.com/operator-framework/operator-sdk/issues/3470
> Fix quick start link 0.19

- website/content/en/docs/golang/project_migration_guide.md
- website/content/en/docs/migration/v0.19.0.md
- We are applying here the typos and small fixes which were made on master related the migration guide
Closes: https://github.com/operator-framework/operator-sdk/issues/3396 
Closes: #3512
> doc: apply small fixes perform on master on to the migration guide (0.19)

- changelog/fragments/packagemanifests-from-version.yaml
- cmd/operator-sdk/generate/internal/genutil.go
- cmd/operator-sdk/generate/packagemanifests/cmd.go
- cmd/operator-sdk/generate/packagemanifests/packagemanifests.go
- website/content/en/docs/cli/operator-sdk_generate_packagemanifests.md
- website/content/en/docs/olm-integration/generation.md
**Description of the change:** add `generate packagemanifests --from-version`.
**Motivation for the change:** I'm not sure why this wasn't included in the original command, since it is still required to populate a CSV's `spec.replaces`.
**Checklist**
> cmd/operator-sdk/generate/packagemanifests: add `--from-version` flag

- website/content/en/docs/migration/v0.18.0.md
Fix link to that points to the work that implements liveness probe handling for Ansible-based operators that was done during the 0.18 release.
**Checklist**
> website: Fix link to the pull requests that implements support for configuring a liveness probe for an Ansible operator.

- cmd/operator-sdk/generate/packagemanifests/packagemanifests.go
change an error message so the suggested flag matches the actual flag for the command
It's helpful if the suggested flag is the actual flag of the command
> Fix flag name in error message for generate packagemanifests

- changelog/fragments/operator-name-config-file.yaml
- go.mod
- go.sum
- internal/plugins/helm/v1/chartutil/chart.go
- internal/plugins/helm/v1/init.go
- internal/plugins/helm/v1/plugin.go
- internal/plugins/helm/v1/scaffolds/internal/templates/config/kdefault/auth_proxy_patch.go
- internal/plugins/helm/v1/scaffolds/internal/templates/config/kdefault/kustomization.go
- internal/plugins/helm/v1/scaffolds/internal/templates/config/manager/manager.go
- internal/plugins/helm/v1/scaffolds/internal/templates/config/rbac/manager_role.go
- internal/util/projutil/project_util.go
* go.sum,go.mod: bump kubebuilder dep
* internal/plugins/helm: add `--project-name` flag, and use `Config.ProjectName` in scaffolds
**Motivation for the change:** This commit bumps sigs.k8s.io/kubebuilder to the latest commit so `Config.ProjectName` is available, and adds `--project-name` to Go (indirectly) and Helm (directly) to set this field on `init`. See https://github.com/kubernetes-sigs/kubebuilder/pull/1603 and https://github.com/kubernetes-sigs/kubebuilder/pull/1609 for details and changes to the Go plugin.
@asmacdo @fabianvf this might also be nice to have in an Ansible plugin too.
/cc @camilamacedo86 @joelanford
**Checklist**
> internal/plugins/helm: add `--project-name` and use `Config.ProjectName` in scaffold

- changelog/fragments/no-pod-left-behind.yaml
- internal/scorecard/run_test.go
- internal/scorecard/scorecard.go
- internal/scorecard/testpod.go
**Description of the change:** check timeout error in scorecard before cleaning up, and use a separate timeout for cleanup
**Motivation for the change:** fixes #3419 
/cc @jmccormick2001 
/kind bug
**Checklist**
> internal/scorecard: fix cleanup skip on timeout bug

- hack/generate/changelog/gen-changelog.go
* Use new location for migration files
* Allow pre-release versions in `-tag` flag.
Prep for 1.0.0-alpha1 release
> hack/generate/changelog: fixes in preparation for v1.0.0-alpha1 release

- internal/util/k8sutil/k8sutil.go
- internal/util/k8sutil/k8sutil_test.go
After we remove the metrics this funcs are no longer used. 
See that the fragment was not added because it has one for the users when the pkg was moved to internal. 
Closes: https://github.com/operator-framework/operator-sdk/issues/3354
> cleanup: remove the funcs from k8sutil which are no longer used

- changelog/fragments/packagemanifests-from-version.yaml
- cmd/operator-sdk/generate/internal/genutil.go
- cmd/operator-sdk/generate/packagemanifests/cmd.go
- cmd/operator-sdk/generate/packagemanifests/packagemanifests.go
- website/content/en/docs/cli/operator-sdk_generate_packagemanifests.md
- website/content/en/docs/new-cli/operator-sdk_generate_packagemanifests.md
- website/content/en/docs/olm-integration/generating-a-csv.md
> [v0.19.x] cmd/operator-sdk/generate/packagemanifests: add `--from-version` flag (#3509)

- changelog/fragments/consistent-domain.yaml
- internal/generate/testdata/non-standard-layout/PROJECT
- internal/plugins/plugins.go
- pkg/ansible/controller/reconcile.go
- pkg/ansible/runner/runner.go
- pkg/helm/controller/reconcile.go
- pkg/helm/controller/reconcile_test.go
- test/ansible/deploy/crds/test.example.com_v1_inventorytest_cr.yaml
- test/ansible/deploy/crds/test.example.com_v1alpha1_inventorytest_cr.yaml
- test/e2e-helm/e2e_helm_suite_test.go
- website/content/en/docs/building-operators/ansible/development-tips.md
- website/content/en/docs/building-operators/ansible/quickstart.md
- website/content/en/docs/building-operators/ansible/reference/advanced_options.md
- website/content/en/docs/building-operators/ansible/reference/watches.md
- website/content/en/docs/building-operators/helm/migration.md
- website/content/en/docs/building-operators/helm/quickstart.md
- website/content/en/docs/building-operators/helm/reference/advanced_features.md
- website/content/en/docs/building-operators/helm/reference/scaffolding.md
- website/content/en/docs/cli/operator-sdk_init.md
Use a consistent domain suffix for all SDK features (plugin names, annotations, etc.)
Consistency and to align with a domain we actually own.
**Checklist**
> *: consistently use *.sdk.operatorframework.io wherever we use domains

- changelog/fragments/crds-with-core-types.yaml
- internal/generate/clusterserviceversion/clusterserviceversion_test.go
- internal/generate/collector/collect.go
- internal/generate/collector/collect_test.go
- internal/generate/testdata/non-standard-layout/config/crds-with-core-types/foo.example.com_deployment_crd.yaml
- internal/generate/testdata/non-standard-layout/config/crds-with-core-types/foo.example.com_v1alpha1_deployment_cr.yaml
Comparing only "kind" of the resource might lead to conflict where two resources might have same kind but in different api groups.
For example an operator could provide a custom resource with name "Deployment" in it's own group. On generating csv for this operator might not consider the provided CR for filling 'alm-examples'
Observed this issue while integrating [PMEM-CSI operator](https://github.com/intel/pmem-csi) which provides `Deployment` CRD in `pmem-csi.intel.com` API group.
**Checklist**
> scorecard,generate-csv: consider api "group" while checking for known types

- website/content/en/docs/building-operators/golang/project_migration_guide.md
- website/content/en/docs/building-operators/golang/quickstart.md
- website/content/en/docs/building-operators/golang/references/env-test-setup.md
- Add info in the quick start over how to setup the env test. Otherwise. it will fail when users run `docker-build`
- Add new doc with its options and more detailed information in the references. 
- https://github.com/operator-framework/operator-sdk/issues/3461
> doc: steps and info to setup envtest

- test/e2e-helm/e2e_helm_suite_test.go
- website/content/en/docs/building-operators/helm/migration.md
- website/content/en/docs/building-operators/helm/quickstart.md
- website/content/en/docs/building-operators/helm/reference/scaffolding.md
Update documentations and tests to use `--plugins=helm` short name for plugin
It's a lot easier to type :)
**Checklist**
> test,website: use --plugins=helm when referencing the plugin name

- changelog/fragments/rename-meta-ansible-operator-meta.yaml
- internal/ansible/runner/runner.go
- test/ansible-memcached/tasks.yml
- test/ansible/watches.yaml
- website/content/en/docs/building-operators/ansible/development-tips.md
- website/content/en/docs/building-operators/ansible/quickstart.md
- website/content/en/docs/building-operators/ansible/reference/apb-migration-guide.md
- website/content/en/docs/building-operators/ansible/testing-guide.md
Rename the `meta` variable that is passed to the Ansible Operator to `ansible_operator_meta`
Closes #2692
This brings it in line with the typical naming scheme for implicit facts passed to roles/playbooks.
**Checklist**
> Meta ansible operator meta

- changelog/fragments/ansible-operator-env.yaml
- cmd/ansible-operator/main.go
The commit [`ed92d3668ca921270d01055d8d8e01f3fd5187d3`](https://github.com/operator-framework/operator-sdk/commit/ed92d3668ca921270d01055d8d8e01f3fd5187d3) removed the `setAnsibleEnvVars` function. However, that function is important to make sure the command line flags `ansible-roles-path` and `ansible-collections-path` work. These command line flags are set into environment variables that will be picked up later.
This PR fixes an issue introduced by a previous PR.
Not sure we need a change log for this kind of fix, because it is fixing a bug that is not yet released.
> Add back setting environment variable

- website/content/en/docs/golang/project_migration_guide.md
- website/content/en/docs/golang/quickstart.md
- website/content/en/docs/golang/references/env-test-setup.md
- Add steps to configure env test and allow users to follow up the common steps. (Applying to 0.19.x the same changes made in #3510)
Without this info, users are unable to run `docker-build`. They will face an issue because is missing the binaries that are shipped with kb. Related to: https://github.com/operator-framework/operator-sdk/pull/3510 and to close the issue #3461
**Checklist**
> doc: add envtest setup info  (0.19.x) 

- changelog/fragments/ansible-helm-log-fmt.yaml
- cmd/ansible-operator/main.go
- cmd/helm-operator/main.go
Use structured logging for version information for Ansible and Helm operators
Closes #2843
**Checklist**
> Ansible/Helm: use structured logging for version info

- changelog/fragments/ansible-operator-env.yaml
- pkg/ansible/run.go
Backport of #3549 
Fix bugs
**Checklist**
> pkg/ansible/run.go: add back setting environment variables (v0.19.x)

- website/content/en/docs/building-operators/ansible/development-tips.md
- website/content/en/docs/building-operators/ansible/quickstart.md
- website/content/en/docs/building-operators/ansible/testing-guide.md
- website/content/en/docs/building-operators/ansible/tutorial.md
- The quickstart was moved to tutorial
- Added new quickstart less verbose and with the concise steps. 
- Update the links and the order to show the docs 
See: https://deploy-preview-3555--operator-sdk.netlify.app/docs/building-operators/ansible/quickstart/
https://github.com/operator-framework/operator-sdk/issues/3327
Closes: #2774
> doc: quickstart for Ansible projects 

- internal/plugins/ansible/v1/scaffolds/internal/templates/config/kdefault/auth_proxy_patch.go
- internal/plugins/ansible/v1/scaffolds/internal/templates/config/manager/manager.go
- Remove scaffolding of POD_NAME and WATCH_NAMESPACE
- Use default --metrics-addr flag when auth proxy is not in use
Closes #3567 and #3569 
**Checklist**
> internal/plugins/ansible: manager scaffolding updates for --metrics-addr and envvars

- go.mod
- go.sum
- internal/cmd/operator-sdk/generate/bundle/bundle.go
- internal/cmd/operator-sdk/generate/bundle/cmd.go
- internal/cmd/operator-sdk/generate/internal/genutil.go
- internal/cmd/operator-sdk/generate/kustomize/manifests.go
- internal/cmd/operator-sdk/generate/packagemanifests/cmd.go
- internal/cmd/operator-sdk/generate/packagemanifests/packagemanifests.go
- internal/util/projutil/project_util.go
- test/e2e-helm/e2e_helm_olm_test.go
- test/internal/utils.go
- website/content/en/docs/cli/operator-sdk_init.md
- website/content/en/docs/olm-integration/generation.md
- fix OLM subcommands to be able to get the operator name via the project name in the project file or the current directory.  
- add e2e tests to ensure that the bundle subcommands are working for projects scaffolds with Helm plugin and the new layout. 
**Motivation**
SDK is in a process to be integrated with KB which means that its project layouts will be aligned. More info : [Integrating Kubebuilder and Operator SDK](https://github.com/kubernetes-sigs/kubebuilder/blob/master/designs/integrating-kubebuilder-and-osdk.md). 
#3327
> Allows OLM subcommands work for Helm/Ansible new layout

- internal/cmd/operator-sdk/bundle/bundle_suite_test.go
- internal/cmd/operator-sdk/completion/completion_suite_test.go
- internal/cmd/operator-sdk/olm/olm_suite_test.go
- internal/cmd/operator-sdk/run/packagemanifests/packagemanifests_suite_test.go
- internal/cmd/operator-sdk/run/run_suite_test.go
- internal/cmd/operator-sdk/scorecard/scorecard_suite_test.go
- internal/cmd/operator-sdk/version/version_suite_test.go
- internal/scorecard/scorecard_suite_test.go
- Update the go e2e test to have the suffix _test which has special meaning for the Go compiler.
- Rename test suites created for cmd. Otherwise, when it fails we are unable to know if is for example `Scorecard Suite` from cmd or from the internals one.   
Know what is the suite of test that fails and avoid duplications in the names.
> Cleanup CMD tests 

- internal/scaffold/ansible/go_mod.go
- internal/scaffold/go_mod.go
- internal/scaffold/helm/go_mod.go
- version/version.go
- website/content/en/docs/install-operator-sdk.md
> post-release v0.19.1

- release.sh
- website/content/en/docs/contribution-guidelines/release.md
- website/content/en/docs/installation/install-operator-sdk.md
- Update release.sh script to allow pre-releases, ignore `.gitignore`d files, and automatically verify binary signatures.
- Update release docs to remove file changes that are no longer relevant, and only push the one release tag
- Use `v1.0.0-alpha.1` in installation doc
Closes #3576 
**Checklist**
> release.sh, website: update release script and docs

- website/content/en/docs/building-operators/helm/migration.md
doc: fix the duplicated line in the migration guide
> doc: fix the duplicated line in the migration guide

- changelog/fragments/operator-name-config.yaml
- internal/cmd/operator-sdk/generate/bundle/bundle.go
- internal/cmd/operator-sdk/generate/bundle/cmd.go
- internal/cmd/operator-sdk/generate/kustomize/manifests.go
- internal/cmd/operator-sdk/generate/packagemanifests/cmd.go
- internal/cmd/operator-sdk/generate/packagemanifests/packagemanifests.go
- internal/generate/packagemanifest/packagemanifest.go
- website/content/en/docs/cli/operator-sdk_generate_bundle.md
- website/content/en/docs/cli/operator-sdk_generate_kustomize_manifests.md
- website/content/en/docs/cli/operator-sdk_generate_packagemanifests.md
- website/content/en/docs/olm-integration/generation.md
- website/content/en/docs/olm-integration/quickstart-package-manifests.md
**Description of the change:** remove `--operator-name` flag
**Motivation for the change:** `projectName` is now universal for plugins, so should be used instead of a flag value.
/cc @joelanford @camilamacedo86 @hasbro17 
**Checklist**
> generate: remove `--operator-name`

- changelog/fragments/run-packagemanifests-flags-2.yaml
- internal/olm/operator/operator_manager.go
- internal/olm/operator/packagemanifests_manager.go
- test/e2e/e2e_suite.go
- test/integration/operator_olm_test.go
- website/content/en/docs/cli/operator-sdk_cleanup_packagemanifests.md
- website/content/en/docs/cli/operator-sdk_run_packagemanifests.md
- website/content/en/docs/olm-integration/quickstart-bundle.md
- website/content/en/docs/olm-integration/testing-deployment.md
* internal/olm/operator: remove OLM namespace usage, OLM installation detection, create resources in provided operator namespace, and change operator namespace to namespace
* website: update docs
**Motivation for the change:** `<run|cleanup packagemanifests` flag `--olm-namespace` has been removed since it  is no longer used by the command, and `--operator-namespace` has been renamed to `--namespace`. OLM-adjacent resources (ex. registry deployment) are now created in the provided namespace, and OLM installation is no longer checked.
/cc @joelanford @jmrodri @rashmigottipati 
**Checklist**
> <run|cleanup> packagemanifests: remove `--olm-namespace`, change `--operator-namespace` to `--namespace`

- internal/plugins/ansible/v1/scaffolds/internal/templates/makefile.go
The kustomize target in the Makefile scaffolded by ansible plugin is missing use the realpath
To allow the test work without pre-install it. (PS. The need to use the real path was identified when we were porting the helm tests to go and we remove its setup from the script. we were looking for to test the makefile target in the tests as well )
**Checklist**
> fix: (ansible) - kustomize target is missing realpath

- website/content/en/docs/building-operators/helm/migration.md
- website/content/en/docs/building-operators/helm/quickstart.md
- website/content/en/docs/building-operators/helm/reference/_index.md
- website/content/en/docs/building-operators/helm/tutorial.md
- Fix header desc to make sense with info description of the guides in the navigation
- Remove $ from the commands which are without output to allow users copy/past them easily
- Fix the order that the docs should appear
- Typo issue
To check this one navigate in https://deploy-preview-3595--operator-sdk.netlify.app/docs/building-operators/helm/quickstart/
> doc: helm : tiny improvements and fixes

- .travis.yml
- internal/cmd/operator-sdk/generate/internal/genutil.go
- internal/generate/clusterserviceversion/clusterserviceversion_test.go
- internal/util/projutil/project_util.go
Follow-up of #3533
- Remove the support for the legacy layout
- #3327
Blocked by : #3433
> removal: cleanup over legacy support

- test/e2e/e2e_suite.go
Add basic and olm scorecard tests to e2e test suite.
> Scorecard e2e Testing

- CHANGELOG.md
**Description of the change:** update scorecard API links
**Motivation for the change:** scorecard API was moved to api repo
/cc @asmacdo @jmrodri 
**Checklist**
> CHANGELOG.md: update scorecard API links

- hack/tests/e2e-ansible-molecule.sh
- internal/plugins/ansible/v1/scaffolds/api.go
- internal/plugins/ansible/v1/scaffolds/init.go
- internal/plugins/ansible/v1/scaffolds/internal/templates/config/rbac/crd_editor_rbac.go
- internal/plugins/ansible/v1/scaffolds/internal/templates/config/rbac/crd_viewer_rbac.go
- internal/plugins/ansible/v1/scaffolds/internal/templates/config/rbac/kustomization.go
- internal/plugins/ansible/v1/scaffolds/internal/templates/config/rbac/role.go
Ansible was creating kustomize patches to the RBAC role, which was
different than the helm/go plugins. Now we simply update role.yaml more
like the other plugins.
> Modify rbac role, rather than patch with kustomize

- changelog/fragments/inject-operator-image-olm.yaml
- internal/plugins/manifests/init.go
- test/e2e-helm/e2e_helm_olm_test.go
- test/e2e/e2e_suite.go
- test/internal/utils.go
- website/content/en/docs/olm-integration/generation.md
* internal/plugins/manifests: add `IMG` variable injection to `bundle` recipe
* test/: update tests to use `IMG=<test image tag>`
* website/: update OLM integration docs with this change
**Motivation for the change:** This PR adds `cd config/manager && $(KUSTOMIZE) edit set image controller=$(IMG)` to the manifests phase 2 plugin's Makefile modifier, such that a user can specify operator image using `make bundle IMG=<tag>`. Our e2e tests were passing because `make deploy IMG=<tag>` was run beforehand; in a newly scaffolded project that only uses bundles/package manifests, that will likely not be the case.
/cc @joelanford @camilamacedo86 @asmacdo @fabianvf 
**Checklist**
> internal/plugins/manifests: inject operator image using `IMG=<tag>`

- Makefile
> Bug 1865808: Version informations populating error fix

- changelog/fragments/config-samples-kustomize-scaffold.yaml
- internal/plugins/ansible/v1/api.go
- internal/plugins/golang/v2/api.go
- internal/plugins/helm/v1/api.go
- internal/plugins/manifests/api.go
- internal/plugins/manifests/samples.go
* internal/plugins/manifests: add samples kustomization scaffold
* internal/plugins/{ansible,golang,helm}: update RunCreateAPI() call with the scaffolded resource
**Motivation for the change:** This commit adds a scaffold marker `+kubebuilder:scaffold:manifestskustomizesamples` to `config/samples/kustomization.yaml` so that this file can be updated with new CR files without being completely overwritten. Users should now be able to add multiple samples of their CRDs to their samples kustomization.
Closes #3370 
/cc @joelanford @asmacdo @fabianvf @camilamacedo86 
**Checklist**
> internal/plugins: update instead of overwrite samples kustomization

- website/content/en/docs/building-operators/ansible/tutorial.md
- website/content/en/docs/upgrading-sdk-version/v0.19.0.md
- website/content/en/docs/upgrading-sdk-version/v1.0.0-alpha.1.md
Fixup links that were pointing to `master.sdk.operatorframework.io`
No links should point to master in our docs.
**Checklist**
> website/content/en/docs/: fix links pointing to master docs site

- internal/plugins/ansible/v1/init.go
- internal/plugins/helm/v1/init.go
**Description of the change:** call the `createAPIPlugin.runPhase2()` on `Init.Run()` if API flags are set on `init`.
**Motivation for the change:** Currently if you run
```sh
$ operator-sdk init --plugins {ansible,helm} --group cache --version v1 --kind Memcached
```
You do not get the same behavior (no `config/samples/kustomization.yaml` is written) as running
```sh
$ operator-sdk init --plugins {ansible,helm}
$ operator-sdk create api --group cache --version v1 --kind Memcached
```
The changes in this PR replicate `create api` behavior in `init` when GVK flags are set exactly without actually running the `CreateAPI` plugin directly, as to keep changes minimally. However I do want to rethink separation of plugins going forward to avoid issues like this.
/cc @joelanford @camilamacedo86 …
> internal/plugins/{ansible,helm}: run `CreateAPI` phase 2 plugins in `Init`

- website/content/en/docs/contribution-guidelines/testing/travis-build.md
**Description of the change:** fix broken e2e test link
**Motivation for the change:** broken link
**Checklist**
> website: fix old e2e file link

- website/content/en/docs/building-operators/golang/project_migration_guide.md
Fix/Update the migration guide with the steps required to migrate the Memcached sample
See: https://deploy-preview-3543--operator-sdk.netlify.app/docs/building-operators/golang/project_migration_guide/
Closes: https://github.com/operator-framework/operator-sdk/issues/3460
Closes: https://github.com/operator-framework/operator-sdk/issues/3613
closes: #3613
> doc: Fix/Update the migration guide for Go projects

- website/content/en/docs/building-operators/ansible/development-tips.md
- website/content/en/docs/building-operators/ansible/migration.md
- website/content/en/docs/building-operators/ansible/quickstart.md
- website/content/en/docs/building-operators/ansible/testing-guide.md
- website/content/en/docs/building-operators/ansible/tutorial.md
- Add doc with the steps required to migrate the legacy projects to the new layout. (See: https://deploy-preview-3571--operator-sdk.netlify.app/docs/building-operators/ansible/migration/)
- Fix and align Quickstart to be similar to the other projects (See: https://deploy-preview-3571--operator-sdk.netlify.app/docs/building-operators/ansible/quickstart/)
- Rename file scaffolding to project_layout
Partial closes: #3542 https://github.com/operator-framework/operator-sdk/issues/3590
#3327
Follow-up of this one will be : https://github.com/operator-framework/operator-sdk/issues/3639 (to update the molecule docs)
PS.: PR to migrate the sample: https://github.com/operator-framework/operator-sdk-samples/pull/138
> doc: migration guide for Ansible and quickstart fixes

- website/content/en/docs/building-operators/golang/tutorial.md
Signed-off-by: Jose R. Gonzalez <josegonzalez89@gmail.com>
With v1.0, the scaffolding creates a manager with some default options using `"sigs.k8s.io/controller-runtime".NewManager()` (changed from `"sigs.k8s.io/controller-runtime/pkg/manager".New()`) This seems to be accounted for in other places in the docs.
Thought it might help with consistency across the documentation. Not sure if the Tutorial in its current form was going to stick around but figured I'd send this PR either way and we just close if it not.
**Checklist**
> update go tutorial docs to reflect call to NewManager func

- internal/plugins/ansible/v1/scaffolds/internal/templates/config/testing/kustomization.go
- internal/plugins/ansible/v1/scaffolds/internal/templates/molecule/mdefault/verify.go
- internal/plugins/ansible/v1/scaffolds/internal/templates/molecule/mkind/destroy.go
Motivation: scaffolded operators had some problems running molecule tests.
> Various molecule scaffolding tweaks

- test/integration/integration_helpers.go
**Description of the change:** use default service account for CSV perms in integration tests
**Motivation for the change:** follow up from #3610. Relates to #663.
/cc @joelanford 
**Checklist**
> test/integration: use default service account for CSV perms

- changelog/fragments/remove-olm-namespace-flag.yaml
- internal/cmd/operator-sdk/olm/install.go
- internal/cmd/operator-sdk/olm/install_test.go
- website/content/en/docs/cli/operator-sdk_olm_install.md
- website/content/en/docs/olm-integration/quickstart-bundle.md
Remove 'olm-namespace' flag from 'operator-sdk olm install' command.
The olm manifests published in github have a hardcoded
namespace value. Hence, the olm operators can only be installed in `olm`
namespace using `operator-sdk olm install` command.
**Checklist**
> [olm] Remove olm-namespace flag from install sub-command

- changelog/fragments/better-cleanup.yaml
- internal/cmd/operator-sdk/cleanup/cmd.go
- internal/operator/uninstall.go
- test/integration/operator_olm_test.go
Bug fixes for `operator-sdk cleanup`:
1. Actually wait for CRDs to be deleted
2. Check to see if subscription has install plan ref to avoid panic
3. Only delete resources created by install plan (avoids deleting things like `default` service account and other resources that existing before OLM installed the operator)
Better UX for `operator-sdk cleanup`
**Checklist**
> wait for CRD deletion; delete all objects created by install plan

- changelog/fragments/run-pkgman-allnamespaces.yaml
- hack/tests/integration.sh
- internal/olm/operator/operator_manager.go
- internal/olm/operator/packagemanifests_manager.go
- internal/olm/operator/tenancy.go
- test/integration/operator_olm_test.go
- website/content/en/docs/olm-integration/testing-deployment.md
The default install mode for the `run packagemanifests` command changed from `OwnNamespace` to `AllNamespaces`
In 1.0, operators are scaffolded to have cluster-scoped permissions and watch all namespaces, so it makes sense to align `run packagemanifests` with this default.
**Checklist**
> run packagemanifests: change default install mode to AllNamespaces

- changelog/fragments/3-alpha-config.yaml
- internal/plugins/golang/v2/api.go
- internal/plugins/golang/v2/config.go
- internal/plugins/golang/v2/init.go
- internal/plugins/manifests/api.go
- internal/plugins/manifests/init.go
- internal/plugins/scorecard/init.go
- website/content/en/docs/olm-integration/quickstart-bundle.md
- website/content/en/docs/olm-integration/quickstart-package-manifests.md
**Description of the change:** only run phase 2 plugins for project versions >= 3-alpha.
**Motivation for the change:** The SDK should be scaffolding the vanilla `go.kubebuilder.io/v2` plugin if `--project-version 2` is set, since the `go.sdk.operatorframework.io` phase 2 plugin requires a 3-alpha project.
Holding for discussion
/hold
**Checklist**
> internal/plugins: scaffold a vanilla `go.kubebuilder.io/v2` project when `--project-version=2`

- changelog/fragments/scorecard-kuttl-image-bump.yaml
- images/scorecard-test-kuttl/Dockerfile
this PR bumps the kuttl base image version to v0.5.2 that is used by the
scorecard-test-kuttl  image
this version has bug fixes and features we might make use of.
**Checklist**
> bump kuttl base image version

- internal/olm/operator/internal/registry_pod.go
- internal/olm/operator/internal/registry_pod_test.go
- Switch registry pod to use controller runtime client instead of kubernetes client-go 
- Across run bundle, we are using controller runtime client, and to avoid creating another client to create the registry pod, switching to use controller runtime client for creation of the pod
> [run bundle] Use controller runtime client to create registry pod

- website/content/en/docs/building-operators/golang/advanced-topics.md
Hello,
This PR Closes #3647
It changes the documentation to point to the new status location that is now `operator-framework/operator-lib`
see #3647. I've faced the same issue and it does not work with v1+ of operator-sdk.
**Checklist**
> Update `Advanced Topics` conditions with operator-framework/operator-lib

- internal/plugins/ansible/v1/api.go
Scaffolded operators without a role or playbook need manual
intervention, which can be avoided by including one of the optional
flags.
> Clarify that a role, playbook is necessary for a running operator

- internal/ansible/controller/reconcile.go
- internal/ansible/runner/eventapi/types.go
Added a check to determine whether or not a task has been rescued. 
Avoid adding rescued tasks to the list of failures during reconciliation. 
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1856714
> Adding checks for rescued tasks during reconciliation

- website/content/en/docs/building-operators/ansible/quickstart.md
Add a target for the markdown link in the ansible quickstart guide.
Links that work are cool.
**Checklist**
> fix broken link in ansible quickstart docs

- hack/ci/check-doc-only-update.sh
ci: skip test jobs when just the template used as an example is changed
We do not re-run all tests when the change is done for docs and in the template used by them only
> ci: skip test jobs when just the template used as an example is changed

- .golangci.yml
- images/scorecard-test-kuttl/cmd/test-kuttl/main.go
- internal/ansible/proxy/kubeconfig/kubeconfig.go
- internal/cmd/operator-sdk/scorecard/cmd.go
- internal/olm/operator/internal/registry_pod.go
- internal/registry/validate.go
Signed-off-by: Ken Sipe <kensipe@gmail.com>
Adding unconvert to Linter with Fixes.  This is simply unnecessary conversions in code.
💪 
**Checklist**
> Adding unconvert to Linter

- changelog/fragments/rescue-reconciliation.yaml
Added the fragment file for https://github.com/operator-framework/operator-sdk/pull/3650 (Missed in this PR).
> Adding fragment file for PR #3650 (Rescue tasks reconciliation)

- website/content/en/docs/building-operators/ansible/reference/retroactively-owned-resources.md
Fix ansible-operator link to CR sample	
Broken links cause CI to always fail
**Checklist**
> fix ansible-operator link to CR sample

- changelog/fragments/socket-cleanup.yaml
- internal/ansible/runner/eventapi/eventapi.go
Removed stale sockets during the closing of Ansible operators.
Removing of unused/stale sockets allows for smoother initialization of the operator during start-up.
> Removing stale sockets while running Ansible operators

- CHANGELOG.md
- changelog/fragments/00-template.yaml
- changelog/fragments/rescue-reconciliation.yaml
- cmd/operator-sdk/main.go
- hack/tests/e2e-ansible-molecule.sh
- internal/util/projutil/project_util.go
- pkg/ansible/controller/reconcile.go
- pkg/ansible/runner/eventapi/types.go
Added a check to determine whether or not a task has been rescued.
Avoid adding rescued tasks to the list of failures during reconciliation.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1856714
Backporting the PR https://github.com/operator-framework/operator-sdk/pull/3650
> Bug 1856714: Adding checks for rescued tasks during reconciliation

- website/content/en/docs/building-operators/golang/references/logging.md
Description: Tweak `logging.md` for minor fixes in `--zap-stacktrace-level` flag desc, and correct path for `main.go`.
> Fix main.go path, and desc for zap stacktrace level for logging.md

- changelog/fragments/fix-csv-role-names.yaml
- internal/generate/clusterserviceversion/clusterserviceversion_updaters.go
- internal/generate/collector/clusterserviceversion.go
- internal/generate/collector/clusterserviceversion_test.go
- internal/generate/collector/collect.go
- internal/generate/collector/collector_suite_test.go
> [v0.19.x] generate: consider service accounts when generating a CSV (#3610)

- website/content/en/docs/advanced-topics/scorecard/custom-tests.md
- website/content/en/docs/advanced-topics/scorecard/scorecard.md
update scorecard custom docs
updated the scorecard custom docs links to refer to the updated location of the custom image files.  Reworded some sections to make it clearer as to how to build the custom image.
**Checklist**
> update scorecard custom docs

- internal/operator/internal/index_image.go
- internal/operator/internal/registry_pod.go
- internal/operator/internal/registry_pod_test.go
- Create GRPC CatalogSource, pointing to the registry pod address (pointing to .:50051).
- Update catalog source with source type, address and annotations
- Verify that catalog source connection is ready
This is one of the building blocks for implementing run bundle and run bundle-upgrade commands. 
Links to enhancement proposals: 
https://github.com/operator-framework/enhancements/blob/master/enhancements/run-bundle.md
> [run bundle] Implement IndexImageCatalogCreator - create grpc catalog source 

- website/content/en/docs/building-operators/golang/references/markers.md
* docs/building-operators/golang/references/markers.md: fix marker xDesriptor example
**Motivation for the change:** marker format is incorrect
Closes #3742 
**Checklist**
> docs: fix Go API xDesriptor marker example

- website/content/en/docs/building-operators/ansible/tutorial.md
there are two mentions to 'memecached' instead of 'memcached'.
Fix #3756
> doc: fixing minor typos

- images/scorecard-test-kuttl/Dockerfile
update the scorecard-test-kuttl image to be based off of the kuttl v0.5.2 version 
this changes the scorecard-test-kuttl image from being based off of a SHA to the
semver tagged version of kuttl, this supports multi-arch images better.
**Checklist**
> use kuttl v0.5.2 as the base for scorecard-test-kuttl

- hack/tests/e2e-ansible.sh
- test/e2e-ansible/e2e_ansible_cluster_test.go
- test/e2e-ansible/e2e_ansible_local_test.go
- test/e2e-ansible/e2e_ansible_olm_test.go
- test/e2e-ansible/e2e_ansible_suite_test.go
- Port the ansible-e2e test to Go
- Add new tests to ensure that ansible projects have been covered
Note that:
- the mock Memcached example still the same but is generated (so we have no longer the need to keep static mock files to replace the content)
- its is adding tests to ensure OLM features and run local
- It ensures the metrics
- now we are creating the Memcached in an ns that is not the same as the operator to ensure that the cluster scope is working as should be. 
- Keep all tests following the same standard and increase the maintenance ability
- Ensure that the makefile targets are working since we are calling them
- Ensure that we are testing the changes performed since no longer static data is used. 
**Checklist** …
> feat: ansible e2e tests

- test/e2e-helm/e2e_helm_olm_test.go
4/5 OLM scorecard tests fail, which should be expected.
Also added some print statements to assist with debugging:
Does not indicate which scorecard test failed:
```
• Failure [23.285 seconds]
Integrating Helm Projects with OLM
/home/austin/devel/operator-sdk/test/e2e-helm/e2e_helm_olm_test.go:32
with operator-sdk
/home/austin/devel/operator-sdk/test/e2e-helm/e2e_helm_olm_test.go:33
should generate and run a valid OLM bundle and packagemanifests [It]
/home/austin/devel/operator-sdk/test/e2e-helm/e2e_helm_olm_test.go:50
Expected
<v1alpha3.State>: pass
to equal
<v1alpha3.State>: fail
```
Additional Output clearly shows which olm scorecard tests did not match
expectations:
```
- Name:  olm-crds-have-validation
Expected:  fail
Output:  fail
- Name:  olm-spec-descriptors
Expected:  fail …
```
> Run scorecard tests in helm e2e tests

- website/content/en/docs/building-operators/ansible/development-tips.md
- Replace 'k8s Ansible module' with 'Kubernetes Collection for Ansible' where appropriate
- Set code snippet to 'bash' or 'none' properly to avoid confusing highlights
- Update the output from `operator sdk new` to what we actually see today
- Revise the tutorial to create ConfigMap rather than Namespace which doesn't work out of the box for on cluster testing
- Fix the role name spelling, i.e. replace 'Foo' by 'foo' where needed
- Misc text tweaking for readability, e.g. 'inside of an Operator' -> 'inside an Operator'
- Rename "Ansible Operator annotations" to "Annotations for Curstom Resource" to avoid confusion
- Fixed the "Ansible Operator Conditions" section to reflect current status.
Fix outdated content and (hopefully) …
> Tweak development tips for Ansible operator

- changelog/fragments/operatorgroup-conflict.yaml
- internal/olm/operator/operator_suite_test.go
- internal/olm/operator/packagemanifests_manager.go
- internal/olm/operator/tenancy.go
- internal/olm/operator/tenancy_test.go
**Description of the change:** This PR prevents `run packagemanifests` from creating an OperatorGroup in a namespace if one already exists. If one does exist and its target namespaces match exactly those provided by the user, it will use the existing one; if those namespaces do not match, it will return an error with instructions on how to handle the namespace conflict.
* internal/olm/operator: wrap OperatorGroup creation in a method that handles conflict cases, and add unit tests
**Motivation for the change:** See #3681.
/cc @joelanford @jmrodri @rashmigottipati 
/kind bug
Closes #3681
**Checklist**
> internal/olm/operator: handle conflicting OperatorGroups

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/feature-request.md
- .github/ISSUE_TEMPLATE/support-question.md
**Description of the change:** update template comments and add language labels
**Motivation for the change:** all issues should now have a language label corresponding to operator type.
/cc @joelanford @camilamacedo86 @jmrodri 
**Checklist**
> .github/ISSUE_TEMPLATE: update template comments and add language labels

- website/content/en/docs/building-operators/ansible/tutorial.md
removing `memcached-operator` from documentation since user should be in the proper path as oriented at the beginning (`cd memcached-operator`)
> fix: use relative path in documentation

- changelog/fragments/helm-roles-permissions.yaml
- internal/plugins/ansible/v1/scaffolds/internal/templates/config/rbac/role.go
Users identified that the tool was not scaffolding RBAC permissions which are required for the Helm operator works successfully in OCP.
Closes: #3767
> Bugfix: Helm operator: add finalizers permission for created APIs

- website/content/en/docs/building-operators/golang/crds-scope.md
To eliminate confusion, remove definition of namespace scope from CRD scope section
Definition of cluster-scoped CRD was incorrect and caused confusion.
> remove definition of namespace scope from CRD scope section.

- changelog/fragments/bundle-validate-verbose.yaml
- internal/cmd/operator-sdk/bundle/validate.go
- internal/cmd/operator-sdk/bundle/validate_test.go
Make bundle validate subcommand respect verbosity
This makes the `bundle validate` subcommand respect the verbosity level
by setting it directly in the logger that's actually used, and not in
the global logger as was done previously.
Closes: #3793
> Make bundle validate subcommand respect verbosity

- changelog/fragments/bundle-validate-verbose.yaml
- cmd/operator-sdk/bundle/validate.go
- cmd/operator-sdk/bundle/validate_test.go
Cherry-picked from https://github.com/operator-framework/operator-sdk/pull/3795
* Make bundle validate subcommand respect verbosity
This makes the bundle validate subcommand respect the verbosity level
by setting it directly in the logger that's actually used, and not in
the global logger as was done previously.
Closes: #3793
* add unit test
Co-authored-by: Austin Macdonald <austin@redhat.com>
NOTE:
I cherry-picked manually because the bot couldn't handle an imports merge conflict.
> v0.19.x: Make bundle validate subcommand respect verbosity (#3795)

- changelog/fragments/helm-gitignore.yaml
- internal/plugins/helm/v1/scaffolds/internal/templates/gitignore.go
- For Helm-based Operators, cleanup the file `.gitignore` in order to not have invalid instructions for the type.
- keep standard across the project
- helm operator has no go files and should not have its instructions in the gitignore as well. 
**Checklist**
> cleanup: helm gitignore

- changelog/fragments/ansible-gitignore.yaml
- internal/plugins/ansible/v1/scaffolds/init.go
- internal/plugins/ansible/v1/scaffolds/internal/templates/gitignore.go
- For Ansible-based Operator, add `.gitignore` file which was missing.
- Following the good practices, users should not commit the binaries that are added to the bin/ dir. 
- Keep all projects/types following the same standard. 
**Checklist**
> For Ansible-based Operator, add .gitignore file which was missing.

- hack/image/ansible/Dockerfile
Using `--ignore-installed` with pip causes it to ignore the fact that
setuptools has already been installed by rpm. This results in the newest
version of setuptools (50.0.0) to be pulled in.
Setuptools 50 includes a backwards incompatible change to the way that
non-binary installs happen, which breaks the installation of
`ruamel.yaml.clib` on architectures that must install from source
because there is not a built wheel.
> Use rpm installed setuptools

- internal/scaffold/ansible/dockerfilehybrid.go
Using --ignore-installed with pip causes it to ignore the fact that
setuptools has already been installed by rpm. This results in the newest
version of setuptools (50.0.0) to be pulled in.
Setuptools 50 includes a backwards incompatible change to the way that
non-binary installs happen, which breaks the installation of
ruamel.yaml.clib on architectures that must install from source
because there is not a built wheel.
This is the same change as https://github.com/operator-framework/operator-sdk/pull/3827, but it didn't cherry pick.
>     Use rpm installed python-setuptools

- .golangci.yml
- internal/olm/operator/registry/configmap/configmap.go
This is a move away from MD5 which is known to be [broken](https://www.md5online.org/blog/why-md5-is-not-safe/).   This was discussed on a thread on [slack](https://kubernetes.slack.com/archives/C017UU45SHL/p1596812929074800), with this being the recommended solution.   Additionally the original [PR](https://github.com/operator-framework/operator-sdk/pull/3683)  was closed and could not be reopened after a rebase... that PR has several threads of conversation which I think have been resolved but should be considered as part of the reivew.
1. MD5 replaced with sha256
2. lint checker added to make sure md5 isn't used in the future
MD5 has been publicly reported as [broken](https://www.md5online.org/blog/why-md5-is-not-safe/) …
> MD5 out... in with SHA256

- CHANGELOG.md
All of the 0.19.x changes were cherry-picked, so the entries will be duplicates. 
Still, it's nice to have the complete changelog in a single file.
> Include 0.19.x stream in the changelog

- internal/cmd/operator-sdk/run/cmd.go
- internal/olm/operator/bundle/install.go
- internal/olm/operator/registry/catalog.go
- internal/olm/operator/registry/olm_resources.go
- internal/olm/operator/registry/operator_installer.go
- Change subscription approval to manual
- Verify install plan generation for the subscription
- Approve install plan for CSV generation
- We don't want the subscription approval to be automatic and would want to change the approval to manual and be able to  approve the install plan that's generated for that subscription which enables us to install and deploy the operator version we intend to run
/cc @joelanford @jmrodri @estroz @bharathi-tenneti
> [run bundle] Install plan generation and approval for subscription

- release.sh
Specifically, installing the docs locally generates files that trip up
this command.
I made this change to bring down a change from the 1.0+ [release script](https://github.com/operator-framework/operator-sdk/blob/master/release.sh#L20)
> Ignore some untracked files

- website/content/en/docs/building-operators/ansible/development-tips.md
Documentation Change
Fixes #3833
Incorrect snippet
**Checklist**
> Fixes annotations on Ansible development tips

- hack/image/build-custom-scorecard-tests-image.sh
- hack/image/build-scorecard-test-image.sh
- hack/image/build-scorecard-test-kuttl-image.sh
this PR removes the binary for custom-scorecard-test that was added by mistake into the repo.
**Checklist**
> removed customer-scorecard-tests binary that was inadvertly added

- changelog/fragments/ansible-helm-commit-info.yaml
- internal/cmd/ansible-operator/run/cmd.go
- internal/cmd/helm-operator/run/cmd.go
Add git commit logging to helm and ansible operator run commands
Better traceability for versioning
**Checklist**
> internal/cmd: add git commit logging in run subcommand

- changelog/fragments/v0-19-x-ansible-helm-commit-info.yaml
- pkg/ansible/run.go
- pkg/helm/run.go
Add git commit logging to helm and ansible operator run commands
Better traceability for versioning
**Checklist**
> Bug 1874736: pkg/{ansible,helm}: add git commit logging

- internal/olm/operator/registry/index/registry_pod.go
- internal/olm/operator/registry/index/registry_pod_test.go
- internal/olm/operator/registry/index_image.go
- internal/olm/operator/registry/operator_installer.go
- Few minor fixes to get catalog source create, wait and update working correctly for run bundle subcommand
- Tested these changes manually by running the command and it works correctly
- Leaving watiForCatalogSource() function commented out for now
> [run bundle] refactor catalog source and registry pod creation

- website/content/en/docs/building-operators/golang/project_migration_guide.md
- website/content/en/docs/upgrading-sdk-version/v1.0.0-alpha.1.md
- website/content/en/docs/upgrading-sdk-version/v1.0.0.md
The updates on the Writing tests docs in upstream were published in prod which causes the broken link in the CI.
> :book: fix broken links

- internal/olm/client/client.go
- internal/olm/client/client_suite_test.go
- internal/olm/client/client_test.go
Description: Add deployment status check in `DoCSVWait()` function, to determine further root cause on why operator has failed to run, and report back to operator developer.
> run bundle: Add deployment status check when verifying installed operator.

- changelog/fragments/scorecard_scaffolded_version.yaml
- internal/plugins/scorecard/init.go
- Scorecard manifests created using the image with tags. 
Closes: https://github.com/operator-framework/operator-sdk/issues/3840
**Checklist**
> bugfix: use the tags in the scorecard scaffolded manifests

- .travis.yml
- Makefile
- internal/cmd/operator-sdk/version/cmd.go
- internal/version/version.go
- website/content/en/docs/contribution-guidelines/release.md
Remove hard-coded version string in `internal/version/version.go`
This is an initial fully-backward compatible change for other code within the SDK that depends on this value (e.g. scaffolding image reference tags based on the SDK version). In a future PR, we could probably remove `internal/version.Version` entirely and depend only on `internal/version.GitVersion`
We can automatically inject the correct string based on reading the git tree when building from the Makefile. This reduces the number of steps and manual changes that are necessary as part of the release process.
**Checklist**
> Makefile,internal/version: inject version based on git tree

- website/content/en/docs/building-operators/golang/migration.md
Replace "memecached" with "memcached"
I like memes as much as anyone, but they probably don't belong in this particular documentation page.
**Checklist**
I don't think this issue warrants a changelog entry.
> Drop the use of memecached in Go migration docs

- .golangci.yml
- internal/cmd/operator-sdk/bundle/internal/result_test.go
- test/e2e-ansible/e2e_ansible_suite_test.go
- test/e2e-helm/e2e_helm_cluster_test.go
- test/e2e-helm/e2e_helm_local_test.go
- test/e2e-helm/e2e_helm_suite_test.go
- test/internal/utils.go
Use regex replacement to forcibly replace scaffolded Dockerfile base image strings
(Also ignore dot imports of ginkgo and gomega when linting)
Follow-up from #3854 to ensure latest changes are tested in e2e tests
**Checklist**
> e2e: use regex replace to forcibly replace scaffolded Dockerfile base image strings

- netlify.toml
Autoprefixer 10+ requires PostCSS 8+ which is not yet available.
Fixes #3882
> restrict autoprefixer version

- changelog/fragments/relax-csv-name-validation-v0.19.x.yaml
- go.mod
- go.sum
- netlify.toml
Bump to operator-framework/api v0.3.13
Resolved an issue that caused bundle validation to unnecessarily restrict CSV names to a specific format.
Now bundle validation applies the same CSV name validation as the kubernetes API server does (i.e. must be a DNS1123 subdomain)
**Checklist**
> [v0.19.x] Relax csv name validation

- website/content/en/docs/contribution-guidelines/testing/travis-build.md
Fix broken Go e2e link.
Broken link is blocking PRs from merging.
**Checklist**
> Fix broken Go e2e link

- changelog/fragments/relax-csv-name-validation.yaml
- go.mod
- go.sum
Bump to operator-framework/api v0.3.13
Resolved an issue that caused bundle validation to unnecessarily restrict CSV names to a specific format.
Now bundle validation applies the same CSV name validation as the kubernetes API server does (i.e. must be a DNS1123 subdomain)
**Checklist**
> Relax csv name validation

- changelog/fragments/relax-csv-name-validation-v1.0.x.yaml
- changelog/fragments/relax-csv-name-validation.yaml
- go.mod
- go.sum
Bump to operator-framework/api v0.3.13
Resolved an issue that caused bundle validation to unnecessarily restrict CSV names to a specific format.
Now bundle validation applies the same CSV name validation as the kubernetes API server does (i.e. must be a DNS1123 subdomain)
**Checklist**
> [v1.0.x]: Relax csv name validation

- test/e2e-ansible/e2e_ansible_cluster_test.go
- test/e2e-ansible/e2e_ansible_olm_test.go
- test/e2e-ansible/e2e_ansible_suite_test.go
- test/e2e-go/e2e_go_cluster_test.go
- test/e2e-go/e2e_go_olm_test.go
- test/e2e-go/e2e_go_suite_test.go
- test/e2e-helm/e2e_helm_cluster_test.go
- test/e2e-helm/e2e_helm_olm_test.go
- test/e2e-helm/e2e_helm_suite_test.go
Replace expect method `Expect(err).Should(Succeed())` with `Expect(err).NotTo(HaveOccurred())`
For better readability 
Fixes: #3896 
**Checklist**
> Replace method 'Should(Succeed())' with 'NotTo(HaveOccurred())'

- changelog/fragments/fix-migration-guide-link.yaml
- cmd/operator-sdk/main.go
Fixes #3862
**This Change fixes the Link to project migration guide**
**Project Migration Guide link is broken.:**
**Checklist**
> Fix Migration Guide link

- changelog/fragments/3761.yaml
- internal/generate/clusterserviceversion/clusterserviceversion_updaters.go
- internal/generate/clusterserviceversion/clusterserviceversion_updaters_test.go
- internal/generate/collector/manifests.go
- internal/generate/testdata/clusterserviceversions/output/memcached-operator.clusterserviceversion.yaml
- internal/generate/testdata/go/static/basic.operator.yaml
* internal/generate: set webhook deployment name by searching for deployments selected by webhook services
**Motivation for the change:** an element of a CSV's `spec.webhookDefinitions`'s deployment name was being inferred from the webhook config's service reference name, which often does not match the deployment's name. Instead, we can look up what service a webhook is using, then use the service's label selector to look up the deployment via labels on the pods for which the service will proxy.
/cc @varshaprasad96 
**Checklist**
> `generate`: correctly set CSV webhookDefinition deployment names

- internal/cmd/operator-sdk/generate/packagemanifests/packagemanifests.go
- website/content/en/docs/cli/operator-sdk_generate_packagemanifests.md
Signed-off-by: Jose R. Gonzalez <josegonzalez89@gmail.com>
Quick change to docs which makes reference to a flag `--manifests` which doesn't seem to exist in the `generate packagemanifests` action anymorew.
```
Flags:
--channel string         Channel name for the generated package
--crds-dir string        Root directory for CustomResoureDefinition manifests
--default-channel        Use the channel passed to --channel as the package manifest file's default channel
--deploy-dir string      Root directory for operator manifests such as Deployments and RBAC, ex. 'deploy'. This directory is different from that passed to --input-dir
--from-version string    Semantic version of the operator being upgraded from
-h, --help                   help for packagemanifests …
```
> remove references to --manifests command in generate packagemanifest docs

- Makefile
- hack/image/build-ansible-image.sh
- hack/image/build-custom-scorecard-tests-image.sh
- hack/image/build-helm-image.sh
- hack/image/build-scorecard-test-image.sh
- hack/image/build-scorecard-test-kuttl-image.sh
- hack/tests/e2e-go.sh
- test/e2e-ansible/e2e_ansible_suite_test.go
- test/e2e-go/e2e_go_suite_test.go
- test/e2e-helm/e2e_helm_suite_test.go
- test/internal/scorecard-custom-patch.go
Use CI-built scorecard images during e2e tests
Right now, we use either master or the latest release image during CI. However, this has 2 problems:
1. It doesn't test any changes to these images that may have happened in PRs
2. It fails during releases PRs because the release image is not yet built and pushed.
This is related to #3845.
> *: use CI-built scorecard images during e2e tests

- Makefile
- hack/image/build-ansible-image.sh
- hack/image/build-helm-image.sh
- hack/image/build-scorecard-test-image.sh
- hack/image/build-scorecard-test-kuttl-image.sh
- hack/tests/e2e-ansible.sh
- hack/tests/e2e-go.sh
- test/e2e-helm/e2e_helm_suite_test.go
- test/e2e/e2e_suite_test.go
- test/internal/utils.go
Backport of #3909 
Unblock release of v1.0.1
> [v1.0.x] *: use CI-built scorecard images during e2e tests

- changelog/fragments/csv-whdescs-defaults.yaml
- internal/generate/clusterserviceversion/clusterserviceversion_updaters.go
- internal/generate/testdata/clusterserviceversions/output/memcached-operator.clusterserviceversion.yaml
* internal/generate/clusterserviceversion: default admissionReviewVersions to "v1beta1" and sideEffects to "None"
**Motivation for the change:** a CSV is not valid if its webhook definitions do not contain admissionReviewVersions or sideEffects, each of which can be defaulted with reasonable values.
/kind feature
**Checklist**
> `generate`: default CSV `admissionReviewVersions` and `sideEffects`

- CHANGELOG.md
Update CHANGELOG.md for v0.19.4 and v1.0.1
Keep the master CHANGELOG up-to-date with all previous releases.
> CHANGELOG.md: add v0.19.4 and v1.0.1

- test/e2e-ansible/e2e_ansible_cluster_test.go
- test/e2e-ansible/e2e_ansible_olm_test.go
- test/e2e-go/e2e_go_cluster_test.go
- test/e2e-go/e2e_go_olm_test.go
- test/e2e-helm/e2e_helm_cluster_test.go
- test/e2e-helm/e2e_helm_olm_test.go
Added the ginkgo style checks for error messages rather then generating the error messages using fmt.Errorf()
Fixes #3771 
The changes was suggested in [#3499 (comment)](https://github.com/operator-framework/operator-sdk/pull/3499#discussion_r472553300) to better improve the readability of e2e tests.
> [e2e-test] Added the ginkgo style checks for e2e tests

- test/e2e-ansible/e2e_ansible_suite_test.go
- test/e2e-go/e2e_go_suite_test.go
- test/e2e-helm/e2e_helm_suite_test.go
- test/internal/scorecard.go
Added a centralization logic for replacing the dev images in scorecard config for e2e tests.
Closes #3912 
The dev image replace logic was replicated at 3 places in e2e tests. Hence moved it to the common function.
> Centralize the logic for scorecard dev image replacement

- changelog/fragments/olm-improve-logs.yaml
- internal/olm/installer/client.go
Notify user when olm tag is present in github but manifests cannot be located
while installing olm.
Provide better info to users when olm installation fails.
**Checklist**
> [olm] Improve error message in olm install cmd

- website/content/en/docs/building-operators/golang/operator-scope.md
- The examples were not with the full code generated by default which could lead to misunderstandings
- The examples were not the same as the code generated  for the new layout
- a few steps were missing and a few nits to make it easier to be follow up it. 
Since until 0.19 the projects are namespaced scope many users will need to change the scope of the operator in the migration. In this way, it was updated/fixed according to my experience trying to follow up it now. 
Closes: #3688
**Checklist**
> doc: operator-scope update examples with the new layout and clarifies steps. 

- changelog/fragments/disable_gather_facts.yaml
- internal/ansible/runner/runner.go
- internal/plugins/ansible/v1/scaffolds/internal/templates/config/manager/manager.go
- test/e2e-ansible/e2e_ansible_cluster_test.go
- website/content/en/docs/building-operators/ansible/reference/advanced_options.md
With the migration to kubebuilder style scaffolding, we dropped the `ANSIBLE_GATHERING='explicit'` environment variable on the operator's deployment. This causes a performance regression, as gathering facts can increase execution time by 30% for certain playbooks, and the gathered facts do not generally have any applicability to the operator use-case. 
This also makes it so that when running roles directly, we disable fact gathering if `ANSIBLE_GATHERING` is set to explicit. This allows the user to avoid the aforementioned performance penalty without needing to wrap their role in a playbook.
Fixes #2358 
Performance regression due to an oversight when migrating to kubebuilder.
**Checklist**
If the pull request includes …
> Disable fact gathering by default

- OWNERS
Hey there, applying for reviewership of Operator-SDK
Sponsor: @estroz 
Member for at least 3 months ✔️ 
Primary reviewer of 5 PRs:
#3096
#3668
#3879
#3708 (this is an issue but involved a substantial amount of investigation)
#2893
Reviewed/Merged 20 PRs:
#3096
#3668
#3879
#3708 (this is an issue but involved a substantial amount of investigation)
#2893
#3725
#3508
#3454 
#3413 
#3411 
#3375 
#3318 
#3296 
#3287 
#3247 
#2676
#2629
#3668
#3255
#3734
> OWNERS: add jberkhahn as reviewer

- OWNERS
- OWNERS_ALIASES
**Description of the change:** add an OWNERS_ALIASES file with appropriate labels for admins, approvers, and reviewers.
**Motivation for the change:** now that https://github.com/operator-framework/community/pull/12 has been merged, the OWNERS and OWNERS_ALIASES files should exist and hold the current set of approvers and reviewers at all times, each of which will have to follow community guidelines from the linked document.
Added @asmacdo to `sdk-approvers` since he meets the criteria and has been acting as an approver for a long time.
**Checklist**
> OWNERS: add OWNERS_ALIASES, add approvers/reviewers who already held roles

- changelog/fragments/bump-operator-registry.yaml
- go.mod
- go.sum
Bump `operator-framework/operator-registry` to v1.14.3.
Resolves an issue with default channel bundle validation. The default channel label is not required.
**Checklist**
> go.mod: bump operator-registry to v1.14.3 for bundle validation improvements

- changelog/fragments/scorecard-kuttl-image-bump-061.yaml
- images/scorecard-test-kuttl/Dockerfile
This PR bumps the kuttl version to v0.6.1 that is used within the scorecard-test-kuttl
image as its base.
This version has bug fixes and new features that we will make use of eventually.
**Checklist**
> bump kuttl version to 0.6.1 in scorecard-test-kuttl

- .travis.yml
- Makefile
- hack/image/build-sdk-image.sh
- hack/image/sdk/Dockerfile
The docker image builds, but we need to exercise the tag/push logic before merge 
/hold
This PR results in the creation of 4 new images published to quay: 
- quay.io/repository/operator-framework/operator-sdk-amd64
- quay.io/repository/operator-framework/operator-sdk-s390x
- quay.io/repository/operator-framework/operator-sdk-ppc64le
- quay.io/repository/operator-framework/operator-sdk-arm64
> Add sdk base image

- changelog/fragments/bump-operator-registry.yaml
- go.mod
- go.sum
Bump `operator-framework/operator-registry` to v1.14.3.
Resolves an issue with default channel bundle validation. The default channel label is not required.
Backport of #3953
**Checklist**
> [v0.19.x] *: bump operator-registry to v1.14.3

- website/content/en/docs/building-operators/golang/webhooks.md
fix typo for error link
Fix typo for error link in docs/building-operators/golang/webhooks.md
**Checklist**
> docs: fix typo in golang/webhooks.md

- changelog/fragments/fix-ansible-helm-auth-providers.yaml
- cmd/ansible-operator/main.go
- cmd/helm-operator/main.go
This PR adds the kubernetes auth clients to the ansible-operator and
helm-operator binaries.
Closes #3973
This PR adds the kubernetes auth clients to the ansible and helm operator binaries.
The change enables the ansible and helm operator binaries to run in local mode using gcp, azure, etc auth providers.
**Checklist**
> ansible-operator|helm-operator: add the kubernetes auth clients

- website/content/en/docs/building-operators/golang/advanced-topics.md
Update advance topic guide for golang developers
utilruntime.Must(routev1.AddToScheme(mgr.GetScheme())) to utilruntime.Must(clientgoscheme.AddToScheme(scheme))
Generated operator with operator-sdk has init function which already defines: utilruntime.Must(clientgoscheme.AddToScheme(scheme))
If want to add new schemes, we can follow the same pattern. instead of calledmgr.GetScheme()
- [X ] Add or update relevant sections of the docs website in [`website/content/en/docs`](https://github.com/operator-framework/operator-sdk/tree/master/website/content/en/docs)
> Update advance topics

- test/e2e-ansible/e2e_ansible_suite_test.go
- test/e2e-go/e2e_go_suite_test.go
- test/e2e-helm/e2e_helm_suite_test.go
- test/utils/olm.go
Install OLM version "0.15.1" for e2e tests as
install manifests are present in sdk locally.
To reduce calls to GitHub.
Issue: #3964 
Note: Latest version of OLM is still being tested in `subcommand-olm-install.sh` and `install_test.go` - this wouldn't eliminate requests to GitHub entirely.
**Checklist**
> Modify olm version in e2e test

- changelog/fragments/fix-ansible-helm-auth-providers.yaml
- cmd/ansible-operator/main.go
- cmd/helm-operator/main.go
This PR adds the kubernetes auth clients to the ansible-operator and
helm-operator binaries.
Backport of #3974
> [v0.19.x] ansible-operator|helm-operator: add the kubernetes auth clients

- test/e2e-ansible/e2e_ansible_olm_test.go
- test/e2e-ansible/e2e_ansible_scorecard_test.go
- test/e2e-ansible/e2e_ansible_suite_test.go
- test/e2e-go/e2e_go_olm_test.go
- test/e2e-go/e2e_go_scorecard_test.go
- test/e2e-go/e2e_go_suite_test.go
- test/e2e-helm/e2e_helm_olm_test.go
- test/e2e-helm/e2e_helm_scorecard_test.go
- test/e2e-helm/e2e_helm_suite_test.go
- only move the scorecard tests to e2e_<type>_scorecard_test
- (+) maintainable and readable.  
- https://github.com/operator-framework/operator-sdk/pull/3499#discussion_r488685751
**Checklist**
> cleanup: scorecard with its own test

- .travis.yml
- Makefile
- website/content/en/docs/contribution-guidelines/developer-guide.md
- website/content/en/docs/contribution-guidelines/releasing.md
- .travis.yml: consolidate test steps
- Makefile: remove old scaffold rules, rename generation rules, and reorganize scorecard test rules
- *.md: update dev docs
- Some old scaffold rules needed to be removed
- The `gen-` prefix on generation rules is unnecessary and stutters, ex. `make changelog` makes more sense than `make gen-changelog` since we're "making" the changelog
**Checklist**
> Makefile: rename, remove, and reorganize rules

- internal/cmd/operator-sdk/run/cmd.go
- internal/cmd/operator-sdk/run/cmd_test.go
- testdata/helm/memcached-operator/bundle/manifests/memcached-operator.clusterserviceversion.yaml
- website/content/en/docs/cli/operator-sdk_run.md
- website/content/en/docs/cli/operator-sdk_run_bundle.md
Enable the `run bundle` command. Depends on PR #3861 
**Checklist**
> run bundle: Enable run bundle

- website/content/en/docs/olm-integration/quickstart-bundle.md
This PR updates documentation, the OLM Integration/Bundle Quickstart section.
The bundle image build example was not specifying an image name that was different from the operator image name, this seemed confusing to me since these are different images.  I updated the example to include the '-bundle' in the bundle image name to distinguish the image purpose.
**Checklist**
- [] Add a new changelog fragment in `changelog/fragments` (see [`changelog/fragments/00-template.yaml`](https://github.com/operator-framework/operator-sdk/tree/master/changelog/fragments/00-template.yaml))
- [] Add or update relevant sections of the docs website in …
> update bundle image name in examples to denote this is a bundle image

- changelog/fragments/enable-run-bundle-cmd.yaml
Adding changelog fragment for PR #3877 
Forgot to add changelog fragment for PR #3877 
**Checklist**
> Add fragment for run-bundle.

- changelog/fragments/csv-whdescs-defaults.yaml
**Description of the change:** change fragment from addition to bugfix
**Motivation for the change:** CSVs are invalid if they don't have `admissionReviewVersion` or `sideEffects` set in webhook definitions, so #3903 should be treated as a bugfix
**Checklist**
> changelog/fragments/csv-whdescs-defaults.yaml: change to bugfixes, update descriptions

- website/content/en/docs/building-operators/ansible/reference/retroactively-owned-resources.md
- website/content/en/docs/contribution-guidelines/releasing.md
- website/content/en/docs/overview/_overview.md
- doc: update places to direct the users to check the samples in /testdata
- remove post-release process that is no longer required. 
operator-framework/enhancements#47
**Checklist**
> doc: update places to direct the users to check the samples in /testdata

- hack/tests/e2e-ansible-molecule.sh
- test/ansible/requirements.yml
Pin community-kubernetes to <1.0.0
To match ansible project scaffold and fix failing CI
**Checklist**
> Ansible: pin community-kubernetes to <1.0.0 in tests to match ansible project scaffold

- website/assets/scss/_homepage.scss
- website/layouts/index.html
> Add k8s black lives matter statement

- Makefile
- hack/generate/cli-doc/gen-cli-doc.sh
- hack/tests/sanity-check.sh
* Makefile: run gen-cli-doc.go directly
* hack/: remove unecessary gen-cli-doc wrapper script, run make targets where possible in sanity-check.sh
**Motivation for the change:** thin wrapper script is unnecessary, also fixes CI
**Checklist**
> Makefile: run cli-doc generator directly

- internal/testutils/utils.go
- test/e2e-ansible/e2e_ansible_olm_test.go
- test/e2e-ansible/e2e_ansible_suite_test.go
- test/e2e-go/e2e_go_olm_test.go
- test/e2e-go/e2e_go_suite_test.go
- test/e2e-helm/e2e_helm_olm_test.go
- test/e2e-helm/e2e_helm_suite_test.go
centralize the code to manage the prerequisites to install OLM and Prometheus which are equals for all e2e tests
- maintainability
- reusability 
- remove code duplications across the e2e tests
> cleanup e2e: centralize the code to manage the prerequisites

- website/content/en/docs/installation/install-operator-sdk.md
There is no `tidy` in mast branch, use `build` to replaced.
**Checklist**
> fix incorrect build command in installation doc

- Makefile
- release/Makefile
**Description of the change:** remove custom-scorecard-tests from image build/push from Makefile rules
**Motivation for the change:** custom-scorecard-tests don't exist remotely so shouldn't be built/pushed with other remote images
**Checklist**
> Makefile,release/Makefile: remove custom-scorecard-tests from image build/push

- website/content/en/docs/building-operators/golang/migration.md
Signed-off-by: Edmund Ochieng <ochienged@gmail.com>
A couple of sentences were re-written while maintaining the intended meaning
To clarify instructions in the instructions on migrating an existing operator to the new Operator SDK v1.
**Checklist**
> slight update to migration documentation

- changelog/fragments/scorecard-status-descriptor-test.yaml
- internal/scorecard/tests/bundle_test.go
- internal/scorecard/tests/olm.go
Modify `olm-status-descriptor-test` to not check the presence of
`status` field in CR, instead validate only if status-descriptors
are present in owned CRDs.
cc: @jmccormick2001 
Fixes: #3999 
**Checklist**
> fix: modify olm-status-descriptor-test in scorecard

- .cncf-maintainers
- Makefile
- hack/generate/cncf-maintainers/main.go
Automatically generate a flattened maintainers file from the `OWNERS` and `OWNERS_ALIASES` files in the SDK repo.
CNCF needs a single file listing individual maintainers to keep mailing lists updated. This requirement is incompatible with our existing `OWNERS` and `OWNERS_ALIASES` mappings.
See: https://github.com/operator-framework/operator-sdk/commit/575412115cd60452f0ee4d2abd04eab76f46741e#commitcomment-43450277
**Checklist**
> Auto-generate cncf maintainers file from OWNERS and OWNERS_ALIASES

- changelog/fragments/autogenerated-makefile-bundle-prerequisite-task.yaml
- hack/generate/samples/internal/ansible/memcached.go
- hack/generate/samples/internal/go/memcached_with_webhooks.go
- hack/generate/samples/internal/helm/memcached.go
- internal/plugins/manifests/init.go
- testdata/go/memcached-operator/Makefile
`bundle` target in the autogenerated Makefile for new golang based operator projects generated
by the operator-sdk make use of the `kustomize` CLI tool. This commit adds the `kustomize` Makefile
target as a prerequisite of the `bundle` target.
When running `make bundle` an error is returned if kustomize is not previously installed in `$PATH`.
Execution example:
```
msoriano@localhost:~/go/src/github.com/3scale/apicast-operator (update-operator-sdk-to-110)$ make bundle
which: no kustomize in (/home/msoriano/.rbenv/shims:/home/msoriano/.rbenv/bin:/home/msoriano/.nvm/versions/node/v10.21.0/bin:/usr/share/Modules/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/home/msoriano/.local/bin:/home/msoriano/bin:/usr/local/go/bin:/hom …
```
> internal/plugins: Add kustomize as a prerequisite of Makefile's bundle target

- changelog/fragments/fix-cleanup.yaml
- internal/cmd/operator-sdk/cleanup/cmd.go
- internal/olm/operator/bundle/install.go
- internal/olm/operator/helpers.go
- internal/olm/operator/packagemanifests/install.go
- internal/olm/operator/uninstall.go
Updates the `operator-sdk cleanup` subcommand to cleanup the catalog source and operator group even when a subscription for the operator does not exist.
In the event that a user runs `operator-sdk run` and an error occurs after the operator group and catalog source are created, but before a subscription is created, the operator group and catalog source must be manually cleaned up before retrying the `operator-sdk run` command.
In 1.1.0, the `operator-sdk cleanup` command will not cleanup the operator group and catalog source in this scenario.
This PR updates the `operator-sdk cleanup` command so that even when a subscription does not exist, it looks for the expected catalog source and operator group, and deletes them if they …
> cleanup: delete catsrc and operatorgroup even if subscription is not found

- internal/scorecard/tests/olm.go
Remove suggestions if status is not present in CR
Follow up: #4009 
**Checklist**
> Remove suggestions if status is not present in CR

- website/content/en/docs/advanced-topics/scorecard/custom-tests.md
- website/content/en/docs/advanced-topics/scorecard/scorecard.md
- website/content/en/docs/building-operators/golang/migration.md
- website/content/en/docs/building-operators/golang/references/client.md
- website/content/en/docs/building-operators/golang/references/logging.md
- website/content/en/docs/building-operators/golang/tutorial.md
- website/content/en/docs/contribution-guidelines/developer-guide.md
- website/content/en/docs/contribution-guidelines/releasing.md
- website/content/en/docs/contribution-guidelines/testing.md
- website/content/en/docs/olm-integration/testing-deployment.md
- website/content/en/docs/overview/_overview.md
- website/content/en/docs/upgrading-sdk-version/version-upgrade-guide.md
Change all links in the `v1.1.x` branch that refer to `master` to use `v1.1.x` instead.
We should not have links to `master` on release branches because they can break without notice.
**Checklist**
> website: re-point master links to v1.1.x

- internal/scorecard/run_test.go
Extend timers by an order of magnitude on scorecard parallelism test to reduce number of flakes.
CI flakes are a bummer :)
**Checklist**
> internal/scorecard/run_test.go: make parallel test more lenient on timing to reduce flakes

- README.md
updates the README to specify travis-ci.com instead of travis-ci.org 
to point to the right URL given the move to travis-ci.com
**Checklist**
- [] Add a new changelog fragment in `changelog/fragments` (see [`changelog/fragments/00-template.yaml`](https://github.com/operator-framework/operator-sdk/tree/master/changelog/fragments/00-template.yaml))
- [] Add or update relevant sections of the docs website in [`website/content/en/docs`](https://github.com/operator-framework/operator-sdk/tree/master/website/content/en/docs)
> update README link for travis from travis-ci.org to travis-ci.com

- Makefile
**Description of the change:** always build binaries destined for images with a linux target
**Motivation for the change:** no other OS targets can run in images
/cc @camilamacedo86 @joelanford 
**Checklist**
> Makefile: always build linux binaries when building for an image

- Makefile
- release/Makefile
Makefiles use fixed `BUILD_IMAGE_REPO` when building images. `release/Makefile` now uses overridable `IMAGE_REPO` just to set the repo to which images are pushed.
When testing the CI deploy phase in forks, contributors need to override `IMAGE_REPO` in their CI settings to push images to their own image repo.
However, we need to use a fixed image name when building the images because the e2e tests assume the fixed image name.
> ci: use fixed image name when building docker images

- changelog/fragments/upgrade-operator-framework-api.yaml
- go.mod
- go.sum
Bump operator-framework/api to v0.3.20
Closes: #4104  
**Checklist**
> Bump operator-framework/api to v0.3.20

- images/scorecard-test-kuttl/Dockerfile
this PR bumps up the kuttl version used within the scorecard-test-kuttl image to
version v.0.7.1.
kuttl version v0.7.1 contains the latest bug fixes plus features that might
be useful to future versions of scorecard-test-kuttl
**Checklist**
- [] Add a new changelog fragment in `changelog/fragments` (see [`changelog/fragments/00-template.yaml`](https://github.com/operator-framework/operator-sdk/tree/master/changelog/fragments/00-template.yaml))
- [] Add or update relevant sections of the docs website in [`website/content/en/docs`](https://github.com/operator-framework/operator-sdk/tree/master/website/content/en/docs)
> bump kuttl version to 0.7.1

- changelog/fragments/plugins-use-rbac-v1.yaml
- go.mod
- go.sum
- internal/generate/testdata/go/static/basic.operator.yaml
- internal/plugins/ansible/v1/scaffolds/internal/templates/config/rbac/auth_proxy_client_clusterrole.go
- internal/plugins/helm/v1/scaffolds/internal/templates/config/rbac/client_cluster_role.go
- testdata/ansible/memcached-operator/bundle/manifests/memcached-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- testdata/ansible/memcached-operator/config/rbac/auth_proxy_client_clusterrole.yaml
- testdata/go/memcached-operator/bundle/manifests/memcached-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- testdata/go/memcached-operator/config/rbac/auth_proxy_client_clusterrole.yaml
- testdata/helm/memcached-operator/bundle/manifests/memcached-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
- testdata/helm/memcached-operator/config/rbac/auth_proxy_client_clusterrole.yaml
In Go, Ansible, and Helm operators, updated the `metrics-reader` ClusterRole to use `rbac.authorization.k8s.io/v1` to be consistent with all other scaffolded RBAC resources.
Closes #4072
**Checklist**
> go/ansible/helm plugins: use rbac/v1 for metrics reader cluster role

- .gitignore
pycache is created when running Ansible Molecule tests locally.
> Add pycache to gitignore

- release.sh
Version information is automatically included, so this validation should be removed.
Had to make this change during the release process.
**Checklist**
> Remove outdated version validation

- hack/generate/samples/internal/ansible/constants.go
This task is broken and it is not working. To test that, add this task in the Ansible Memcached sample and deploy it to test the call. Then, you will see that it fails. More info:  https://github.com/operator-framework/operator-sdk/issues/4123
Cleanup the tests and remove unused/invalid code
> cleanup ansible molecule tests: remove invalid and not used task

- changelog/fragments/return-olm-install-error.yaml
- internal/olm/client/status.go
- internal/olm/installer/client.go
Returning the real errors occurred in installing the operator is useful
for debugging the failures.
**Motivation of the change:**
When the operator installation failed due to CRD parsing failures but the logs showed no clues of that error.
**Checklist**
> internal/olm/operator: do not suppress the real error

- website/config.toml
- website/layouts/docs/baseof.html
This PR
- Expands the left navigation menu
- Includes a TOC for individual docs on the right
- Includes breadcrumb links on top of the documents for
faster nav-back to the root folder/any folder
of the user's choice
The current contracted menu does not reveal anything about the content of the 
site to new/first time readers. Displaying a list of topics for the site and a 
table of content of each document will significantly improve the UX of the site 
from the perspective of readers who aren't already familiar with the contents of 
the site. 
**Checklist**
> [docs] Update doc site to improve navigation

- Makefile
- changelog/fragments/go-version-bug.yaml
- internal/cmd/ansible-operator/version/cmd.go
- internal/cmd/ansible-operator/version/cmd_test.go
- internal/cmd/helm-operator/version/cmd.go
- internal/cmd/helm-operator/version/cmd_test.go
- internal/cmd/operator-sdk/version/cmd.go
- internal/cmd/operator-sdk/version/cmd_test.go
- internal/plugins/ansible/v1/scaffolds/init.go
- internal/plugins/ansible/v1/scaffolds/internal/templates/dockerfile.go
- internal/plugins/ansible/v1/scaffolds/internal/templates/makefile.go
- internal/plugins/helm/v1/scaffolds/init.go
- internal/plugins/helm/v1/scaffolds/internal/templates/dockerfile.go
- internal/plugins/helm/v1/scaffolds/internal/templates/makefile.go
- internal/plugins/scorecard/init.go
- internal/version/version.go
- internal/*: define ImageVersion, which is set to the most recent of operator-sdk repo tag or release commit's future tag. This variable is consumed by ansible-operator, helm-operator, and scorecard plugins
- Makefile: set IMAGE_VERSION to v1.1.0, and set ImageVersion in ldflags
**Motivation for the change:** samples generated for a release commit will have incorrect versions, specifically the major+minor version preceding the soon-to-be-released version, in the current release setup because these versions depend on a release's git tag which has not been created yet. Setting this version explicitly in the Makefile breaks this cycle, allowing samples to be generated with a version that has not been released yet; these will still pass e2e tests because image …
> internal/*: define ImageVersion, which is set to the most recent

- internal/testutils/utils.go
- test/e2e-helm/e2e_helm_cluster_test.go
- test/e2e-helm/e2e_helm_suite_test.go
Discussed an alternate approach to #4028 with @camilamacedo86 to actually copy the generated helm sample from `testdata` into the test directory and use it as the base operator.
operator-framework/enhancements#47
> test/e2e-helm: use generated helm sample

- website/content/en/docs/building-operators/helm/tutorial.md
Updated the helm tutorial to match the unsupported status for 'operator-sdk run local' command.
Disambiguation and avoidance of errors.
> docs/building-operators/helm/tutorial: remove unsupported 'operator-sdk run local'

- website/content/en/docs/building-operators/helm/tutorial.md
Related to #4158 - Removing the choice to run it locally with operator-sdk run local that is not supported.
Cherry pick for v1.1.x branch
> docs/building-operators/helm/tutorial: Remove unsupported 'operator-sdk run local' (Cherry pick for v1.1.x )

- website/content/en/docs/building-operators/helm/tutorial.md
Related to #4158 - Removing the choice to run it locally with operator-sdk run local that is not supported.
Cherry pick of the edit made on master
> docs/building-operators/helm/tutorial: Remove unsupported 'operator-sdk run local' (Cherry pick for v1.0.x )

- website/content/en/docs/building-operators/ansible/migration.md
Update the ansible/migration.md documentation, adding the closing backtick to the missing watches.yaml mentions.
Minor documentation fix.
**Checklist**
> website: Fix the watches.yaml backticks in the Ansible migration guide

- website/config.toml
Without this feature, the left bar is far too long to be useful.
This is a partial revert of https://github.com/operator-framework/operator-sdk/pull/4002/files#r516232814
> Docs: Re-enable compact left-side bar

- changelog/fragments/fix-csv-generate-path-segments.yaml
- internal/generate/clusterserviceversion/bases/definitions/ast.go
- internal/generate/testdata/clusterserviceversions/bases/with-ui-metadata.clusterserviceversion.yaml
- internal/generate/testdata/clusterserviceversions/output/memcached-operator.clusterserviceversion.yaml
- internal/generate/testdata/go/api/v1alpha1/memcached_types.go
Fixes a bug that causes path segments to inadvertently re-use memory from other path segments, causing `specDescriptors` and `statusDescriptors` fields to end up with incorrect paths.
Fix bug = good :)
**Checklist**
> operator-sdk/internal/generate: fix CSV path segments for multi-field structs

- internal/testutils/utils.go
The InstallOLM is not used at all. So, we can remove it in order to keep the maintanability.
> testutils/cleanup: remove InstallOLM method that is no lonnger used

- changelog/fragments/olm-version-v.yaml
- internal/olm/installer/client.go
- internal/olm/installer/client_test.go
- internal/olm/installer/installer_suite_test.go
**Description of the change:** prepend `v` to semver strings passed to `olm` subcommands
**Motivation for the change:** OLM versions now have a `v` prefix.
**Checklist**
> internal/olm/installer: prepend 'v' to semvers >= 0.17.0

- hack/generate/samples/internal/go/memcached_with_webhooks.go
- testdata/go/memcached-operator/bundle/manifests/memcached-operator.clusterserviceversion.yaml
- testdata/go/memcached-operator/config/rbac/role.yaml
- testdata/go/memcached-operator/controllers/memcached_controller.go
- website/content/en/docs/building-operators/golang/quickstart.md
- website/content/en/docs/building-operators/golang/tutorial.md
- website/content/en/docs/faqs/faqs.md
- Add the RBAC finalizer permission to allow users to test the Go sample project on OCP
- See that for v3+ plugins this permission will be added by default 
- See that it was added as a NOTE to the quick start and by default in the tutorial in order to avoid the issue faced in https://github.com/operator-framework/operator-sdk/issues/3477
Closes : https://github.com/operator-framework/operator-sdk/issues/3477
**Checklist**
> add finalizer rbac permission to the go/sample and doc steps

- Makefile
**Description of the change:** checkout website submodules in `make test-links`
**Motivation for the change:** initializes website submodules if not already
Closes #4092
**Checklist**
> Makefile: add submodule checkout to 'test-links'

- changelog/fragments/ansible-helm-help-text.yaml
- cmd/ansible-operator/main.go
- cmd/helm-operator/main.go
> ansible-operator,helm-operator: improve executable help text

- hack/generate/samples/internal/ansible/memcached.go
- hack/generate/samples/internal/go/memcached_with_webhooks.go
- hack/generate/samples/internal/helm/memcached.go
- hack/generate/samples/internal/pkg/utils.go
- internal/testutils/olm.go
- test/e2e-go/e2e_go_olm_test.go
- test/e2e-go/e2e_go_suite_test.go
- testdata/ansible/memcached-operator/bundle.Dockerfile
- testdata/ansible/memcached-operator/bundle/manifests/memcached-operator.clusterserviceversion.yaml
- testdata/ansible/memcached-operator/bundle/metadata/annotations.yaml
- testdata/ansible/memcached-operator/config/manifests/bases/memcached-operator.clusterserviceversion.yaml
- testdata/go/memcached-operator/bundle.Dockerfile
- testdata/go/memcached-operator/bundle/manifests/memcached-operator.clusterserviceversion.yaml
- testdata/go/memcached-operator/bundle/metadata/annotations.yaml
- testdata/go/memcached-operator/config/manifests/bases/memcached-operator.clusterserviceversion.yaml
- testdata/helm/memcached-operator/bundle.Dockerfile
- testdata/helm/memcached-operator/bundle/manifests/memcached-operator.clusterserviceversion.yaml
- testdata/helm/memcached-operator/bundle/metadata/annotations.yaml
- testdata/helm/memcached-operator/config/manifests/bases/memcached-operator.clusterserviceversion.yaml
- hack/generate/samples: added `SampleContext.StripBundleAnnotations()` which removes all operator-sdk metrics labels from metadata and manifests in a bundle
- *: renamed exported testutils to align with their functionality
**Motivation for the change:** This PR removes metrics annotations from samples in testdata/, which are inherently versioned by git. Removing these annotations permits proper release tagging of samples.
**Checklist**
> hack/generate/samples: strip operator-sdk metrics annotations

- website/content/en/docs/building-operators/golang/tutorial.md
Adds instructions on how to set up a target to undeploy the operator.
Modifies the deployment namespace so that it does not match an existing namespace.
The previous instructions were not deleting all the resources created during the tutorial. See #4146 
Also modified the deployment namespace to a namespace that does not exist per default in a kubernetes cluster to avoid unintended resources being deleted with the namespace during cleanup.
> Closes #4146 - provides instructions on how to set up a target to undeploy the operator

- release/Makefile
Use `GOARGS` when building release binaries.
`GOARGS` is used to configure `GOOS` and `GOARCH` when building release binaries. This fix ensures that the correct OS and architecture settings are used during the release.
Closes #4216
> release/Makefile: honor GOOS and GOARCH when building release binaries

- website/content/en/docs/installation/_index.md
Remove install steps about downloading and verifying `ansible-operator` and `helm-operator` binaries.
The `operator-sdk` binary will automatically download and install the `ansible-operator` and `helm-operator` binaries as needed via `make run`.
**Checklist**
> website: remove confusing/unnecessary install helm/ansible instructions

- changelog/fragments/helm-ansible-version-metric.yaml
- internal/ansible/metrics/metrics.go
- internal/cmd/ansible-operator/run/cmd.go
- internal/cmd/helm-operator/run/cmd.go
- internal/helm/metrics/metrics.go
Added the `ansible_operator_build_info` and `helm_operator_build_info` metrics to instrument commit and version information for the Ansible and Helm operators, respectively.
Expose runtime version information to augment stamp versions in bundle and CSV metadata.
**Checklist**
> internal/cmd: add build info metric in helm/ansible operators

- hack/generate/samples/internal/helm/memcached.go
- hack/generate/samples/internal/pkg/utils.go
1. Hardcode the helm chart path for the helm sample generation
2. Don't run `make bundle-build` during sample generation
1. The previous method of building the full helm chart path fails when "operator-sdk" appears multiple times in the path, which can happen on developer machines and in CI systems that clone the repo in a subdirectory of a path containing the project name.
2. `make bundle-build` does not change a project, so it is not needed during sample generation.
> sample generation fixes

- website/content/en/docs/building-operators/golang/operator-scope.md
The used `Infof` method isn't defined for the `setupLog` logger, so that we have to use `Info` in combination with `fmt.Sprintf` to get the desired log line.
The error for the current example looks as follows:
```
go fmt ./...
go vet ./...
vet: ./main.go:75:12: setupLog.Infof undefined (type logr.Logger has no field or method Infof)
make: *** [vet] Error 2
```
Fix the given example in the documentation.
**Checklist**
> doc: fix log statement in multi namespace example

- website/content/en/docs/building-operators/golang/tutorial.md
I added an import statement to the Go building operators tutorial.
It would be more user-friendly if we have the import statement since `appsv1 "k8s.io/api/apps/v1"` statement is not specified by default. 
**Checklist**
> Add an import statement to the Go building operators tutorial

- website/content/en/docs/building-operators/golang/tutorial.md
There is a missing url for operator_install in [Golang tutorial page](https://sdk.operatorframework.io/docs/building-operators/golang/tutorial/). Then I add a link for it.
> Fix missing url for operator_install

- changelog/fragments/csv-order.yaml
- internal/generate/clusterserviceversion/bases/definitions/crd.go
- internal/generate/clusterserviceversion/bases/definitions/crd_test.go
- internal/generate/clusterserviceversion/bases/definitions/definitions.go
- internal/generate/clusterserviceversion/bases/definitions/definitions_suite_test.go
- internal/generate/clusterserviceversion/bases/definitions/definitions_test.go
- internal/generate/clusterserviceversion/bases/definitions/markers.go
- internal/generate/clusterserviceversion/bases/definitions/zz_generated.markerhelp.go
- website/content/en/docs/building-operators/golang/references/markers.md
- internal/generate/clusterserviceversion/bases/definitions: add Order to Description and Descriptor marker types, which are considered when adding elements to .spec.customresourcedefinitions
**Motivation for the change:** This PR adds the 'order=<int>' field to the set of CSV marker definitions on both types and fields, which will order that type or field with all others of the same order in a descending manner. The order of `.spec.customresourcedefinition` elements and their descriptors matters in a CSV, as this order is pushed to consoles.
/kind feature
**Checklist**
> generate: add `order=<int>` CSV marker fields

- changelog/fragments/refactor-generate-subcommands.yaml
- hack/generate/samples/internal/pkg/utils.go
- internal/annotations/metrics/metrics.go
- internal/cmd/operator-sdk/generate/bundle/bundle.go
- internal/cmd/operator-sdk/generate/bundle/cmd.go
- internal/cmd/operator-sdk/generate/internal/genutil.go
- internal/cmd/operator-sdk/generate/kustomize/manifests.go
- internal/cmd/operator-sdk/generate/packagemanifests/cmd.go
- internal/cmd/operator-sdk/generate/packagemanifests/packagemanifests.go
- internal/generate/clusterserviceversion/bases/clusterserviceversion.go
- internal/generate/clusterserviceversion/clusterserviceversion.go
- internal/generate/clusterserviceversion/clusterserviceversion_test.go
- internal/generate/collector/manifests.go
- internal/generate/testdata/clusterserviceversions/bases/memcached-operator.clusterserviceversion.yaml
- internal/generate/testdata/clusterserviceversions/output/with-ui-metadata.clusterserviceversion.yaml
- internal/util/projutil/project_util.go
- website/content/en/docs/cli/operator-sdk_generate_bundle.md
- website/content/en/docs/cli/operator-sdk_generate_kustomize_manifests.md
- website/content/en/docs/cli/operator-sdk_generate_packagemanifests.md
Pre-Extract operator details to successfully run `operator-sdk generate  <bundle|packagemanifests>`
Operators created using older SDK versions (<v0.19) have a different project layout than the current [Kubebuilder project layout](https://book.kubebuilder.io/cronjob-tutorial/basic-project.html), which restricts them from generating bundles or package manifests, using the latest versions of Operator SDK.
> Refactoring generate subcommands for to support older layouts

- changelog/fragments/csv-base-name-bugfix.yaml
- internal/cmd/operator-sdk/generate/bundle/bundle.go
- internal/cmd/operator-sdk/generate/bundle/cmd.go
- internal/cmd/operator-sdk/generate/kustomize/manifests.go
- internal/cmd/operator-sdk/generate/packagemanifests/packagemanifests.go
- internal/generate/clusterserviceversion/bases/clusterserviceversion.go
- internal/generate/clusterserviceversion/bases/metadata_test.go
- internal/generate/clusterserviceversion/clusterserviceversion.go
- internal/generate/clusterserviceversion/clusterserviceversion_test.go
- internal/generate/testdata/clusterserviceversions/bases/memcached-operator.clusterserviceversion.yaml
- internal/generate/testdata/clusterserviceversions/bases/with-ui-metadata.clusterserviceversion.yaml
- testdata/ansible/memcached-operator/config/manifests/bases/memcached-operator.clusterserviceversion.yaml
- testdata/go/memcached-operator/config/manifests/bases/memcached-operator.clusterserviceversion.yaml
- testdata/helm/memcached-operator/config/manifests/bases/memcached-operator.clusterserviceversion.yaml
- website/content/en/docs/olm-integration/generation.md
- internal/generate/clusterserviceversion: use an empty base if no CSVs are in the collector
- internal/generate/clusterserviceversion/bases: auto-migrate base name
- docs/olm-integration: document updated behavior
**Motivation for the change:** This commit fixes a bug caused by an invalid CSV name being generated. `operator-sdk generate kustomize manifests` will auto-migrate a base CSV's name to `<package name>.v<version>` if it ends in `.vX.Y.Z`. `operator-sdk generate <bundle|packagemanifests` will always persist base CSV metadata unless `--version` or `--from-version` are set.
/kind bug
**Checklist**
> generate: fix "invalid CSV name" bug

- hack/tests/integration.sh
Downgrade the OLM version used ONLY for the integration tests. Note that the tests were not updated to use the OLM bindata 0.16 when it was added and after the merge of https://github.com/operator-framework/operator-sdk/pull/4242, besides it pass in the tests (https://github.com/operator-framework/operator-sdk/runs/1501864624), we could identify that all follow-up prs starts to fail in the integration tests. Then, since 
- ALL tests have not really been done with the latest version ( 0.16 previously )
- On master, all other tests work with 0.17.0
Shows fine we just downgrade this one to unblock the CI until we are able to identify the root cause and fix it which indeed can be in the OLM side. See the:  https://github.com/operator-framework/operator-sdk/issues/4284
> e2e-intgration-tests: keep using OLM version 0.15.1

- internal/helm/controller/reconcile.go
- internal/helm/release/manager.go
It's possible to run into a nil pointer error during a helm uninstall
Prevent the nil pointer error from happening.
**Checklist**
_its not a user-facing changes._
_no doc updates required._
> fix: (helm) - prevent a possible nil pointer in the helm uninstall

- hack/generate/samples/internal/go/v2/memcached_with_webhooks.go
- hack/generate/samples/internal/go/v3/memcached_with_webhooks.go
- test/e2e-go/e2e_go_cluster_test.go
- test/e2e-go/e2e_go_olm_test.go
- test/e2e-go/e2e_go_scorecard_test.go
- test/e2e-go/e2e_go_suite_test.go
- testdata/go/v2/memcached-operator/api/v1alpha1/memcached_webhook.go
- testdata/go/v2/memcached-operator/bundle/manifests/memcached-operator.clusterserviceversion.yaml
- testdata/go/v2/memcached-operator/config/samples/cache_v1alpha1_memcached.yaml
- testdata/go/v3/memcached-operator/bundle/manifests/memcached-operator.clusterserviceversion.yaml
- testdata/go/v3/memcached-operator/config/samples/cache_v1alpha1_memcached.yaml
- Use Memcached sample instead of re-generate the project.
- Fix/Adjust the e2e tests to work with the sample. 
operator-framework/enhancements#47
> test-e2e/go : using samples 

- test/e2e-go/e2e_go_cluster_test.go
- test/e2e-go/e2e_go_olm_test.go
- test/e2e-go/e2e_go_scorecard_test.go
- test/e2e-go/e2e_go_suite_test.go
**Description of the change:** fix go-e2e test
**Motivation for the change:** reconciliation count is a flaky check, while the sample reconciler will update `status.nodes` on successful reconcile
/area testing
**Checklist**
> test/e2e-go: fix reconcile check

- internal/olm/client/client.go
Sometimes OLM installation fails with the below error:
```
INFO[0028] Waiting for deployment/packageserver rollout to complete
FATA[0028] Failed to install OLM version "latest": deployment/packageserver failed to rollout: deployments.apps "packageserver" not found
```
The reason might be that the deployment object we are waiting for is not
yet registered with the API server. So, do not treat this as an error
and continue the polling.
FIXES: #4293
Observed OLM installation failed occasionally.
**Checklist**
> OLM client: Wait till the deployment appear

- Makefile
- internal/olm/operator/uninstall.go
- test/integration/operator_olm_test.go
- Makefile: remove atypical KUBECONFIG
- internal/olm/operator/uninstall.go: set CatalogSource GVK before deleting
- test/integration/operator_olm_test.go: ensure cleanup after each run
**Motivation for the change:** flaky test
**Checklist**
> e2e/integration: fix flaky OLM integration test

- hack/ci/check-doc-only-update.sh
- netlify.toml
- website/assets/scss/_styles_project.scss
- website/package-lock.json
**Description of the change:** pin the website's postcss dependency to ^8.0.0, and recursively update submodules in website/
**Motivation for the change:** website builds broken
**Checklist**
> netlify.toml: pin postcss dependency to ^8.0.0, recursive submodule update

- internal/testutils/utils.go
- test/e2e-ansible/e2e_ansible_cluster_test.go
- test/e2e-go/e2e_go_cluster_test.go
- test/e2e-helm/e2e_helm_cluster_test.go
**Description of the change:** clean up some e2e setup code
**Motivation for the change:** fix some potential panics and warn on error instead of not checking error at all
**Checklist**
> test/: clean up some e2e setup code

- internal/olm/operator/registry/operator_installer.go
Randomly `run packagemanifests` fails with the below error:
```
Failed to run packagemanifests: error approving install plan: Operation cannot be fulfilled on installplans.operators.coreos.com \"install-jp28s\": the object has been modified; please apply your changes to the latest version and try again
```
The reason is the way error wrapping while calling the
`retry.RetryOnConflict()`. Using '%w' for formatting the error keeps the
original error type unlike '%v'.
FIXES #4308
**Checklist**
> olm/operator: fix issue in wrapping error

- changelog/fragments/pin-ansible-2.9.yaml
- images/ansible-operator/Dockerfile
This rolls back the version of Ansible installed in the Ansible base
image, fixing a syntax error in the Dockerfile. ansible~=2.9 resolves to
Ansible 2.10, but should have been < 2.10.
This does not solve the related concern of helping users set up a local environment, which will be addressed in a followup PR.
**Checklist**
> Pin top level Python dependencies

- hack/generate/samples/internal/ansible/memcached.go
- hack/generate/samples/internal/go/v2/memcached_with_webhooks.go
- hack/generate/samples/internal/go/v3/memcached_with_webhooks.go
- hack/generate/samples/internal/helm/memcached.go
- hack/generate/samples/internal/pkg/utils.go
- internal/testutils/olm.go
- test/e2e-ansible/e2e_ansible_olm_test.go
- test/e2e-ansible/e2e_ansible_suite_test.go
- test/e2e-go/e2e_go_suite_test.go
- test/e2e-helm/e2e_helm_olm_test.go
- test/e2e-helm/e2e_helm_suite_test.go
- Move the olm helpers in the `hack/generate/samples/internal/pkg/utils.go` to `internal/testutils/olm.go`. Reason: allow samples and tests to use the same helper and keep it in a more appropriate place. 
- Remove the duplicates calls made in the e2e tests which are already done in the samples in the e2e tests
- Use the e2e test the helper instead of duplicate the code. 
- Maintainability
- Reduce CI effort by not calling make bundle twice. 
- Centralize the steps to integrate the projects with OLM and keep samples and e2e tests using the same func
- Reduce the duplication of code as of the calls made
> test-e2e/samples/cleanup: centralize code to integrate the project with OLM

- .gitignore
- changelog/fragments/go-v3-default.yaml
- go.mod
- go.sum
- hack/generate/samples/internal/go/v3/memcached_with_webhooks.go
- internal/cmd/operator-sdk/cli/cli.go
- internal/generate/testdata/go/PROJECT
- test/e2e-go/e2e_go_cluster_test.go
- test/e2e-go/e2e_go_suite_test.go
- testdata/go/v3/memcached-operator/PROJECT
- testdata/go/v3/memcached-operator/bundle/manifests/memcached-operator.clusterserviceversion.yaml
- testdata/go/v3/memcached-operator/config/manager/manager.yaml
- website/content/en/docs/building-operators/golang/tutorial.md
- website/content/en/docs/cli/operator-sdk_init.md
- hack/generate/samples: update webhook marker and a few other nits
- internal/cmd/operator-sdk/cli: make go/v3 the default
**Motivation for the change:** now that go/v3 is stable, it can be the default plugin. This is not a breaking change because go/v2 is still supported.
**Checklist**
> *: make go/v3 the default plugin

- website/content/en/docs/building-operators/ansible/_index.md
- website/content/en/docs/building-operators/ansible/installation.md
- website/content/en/docs/building-operators/ansible/migration.md
- website/content/en/docs/building-operators/ansible/quickstart.md
- website/content/en/docs/building-operators/ansible/tutorial.md
- website/content/en/docs/building-operators/golang/migration.md
- website/content/en/docs/building-operators/golang/quickstart.md
- website/content/en/docs/building-operators/golang/tutorial.md
- website/content/en/docs/building-operators/helm/installation.md
- website/content/en/docs/building-operators/helm/migration.md
- website/content/en/docs/building-operators/helm/quickstart.md
- website/content/en/docs/building-operators/helm/tutorial.md
**Description of the change:** unify all quickstarts 
**Motivation for the change:** the quickstarts have drifted when they should be closely aligned
**Checklist**
> docs/building-operators: clean up and align quickstarts

- internal/cmd/operator-sdk/generate/bundle/bundle.go
- website/content/en/docs/building-operators/ansible/migration.md
- website/content/en/docs/building-operators/ansible/tutorial.md
- website/content/en/docs/building-operators/golang/quickstart.md
- website/content/en/docs/building-operators/golang/tutorial.md
- website/content/en/docs/building-operators/helm/migration.md
- website/content/en/docs/building-operators/helm/tutorial.md
- website/content/en/docs/cli/operator-sdk_generate_bundle.md
**Description of the change:** unify all tutorials 
**Motivation for the change:** the tutorials have drifted when they should be closely aligned
**Checklist**
> docs/building-operators: update and align tutorials

- changelog/fragments/liveness_readiness_probe_for_operator.yaml
- internal/ansible/flags/flag.go
- internal/cmd/ansible-operator/run/cmd.go
- internal/cmd/helm-operator/run/cmd.go
- internal/helm/flags/flag.go
- internal/plugins/ansible/v1/scaffolds/internal/templates/config/manager/manager.go
- internal/plugins/helm/v1/scaffolds/internal/templates/config/manager/manager.go
- testdata/ansible/memcached-operator/bundle/manifests/memcached-operator.clusterserviceversion.yaml
- testdata/ansible/memcached-operator/config/manager/manager.yaml
- testdata/helm/memcached-operator/bundle/manifests/memcached-operator.clusterserviceversion.yaml
- testdata/helm/memcached-operator/config/manager/manager.yaml
- Add the probes for Helm/Ansible by default as it was done for Golang go/v3 in upstream. 
- For Ansible/Helm-based operators, added new flag `--health-probe-bind-address` to allow customize the probe port used.
- For Ansible-based operators, deprecated the ping endpoint
- https://github.com/operator-framework/operator-sdk/issues/1234
**Checklist**
> For Ansible/Helm-based operators, add Liveness and Readiness probe

- hack/generate/samples/internal/helm/memcached.go
- testdata/helm/memcached-operator/bundle/manifests/memcached-operator.clusterserviceversion.yaml
- testdata/helm/memcached-operator/config/samples/cache_v1alpha1_memcached.yaml
Disable `securityContext` config for Helm sample 
**Motivation**
Allow sample runs in OCP without: 
```
Warning  FailedCreate  2m (x18 over 10m)  statefulset-controller  create Pod memcached-sample-0 in StatefulSet memcached-sample failed error: pods "memcached-sample-0" is forbidden: unable to validate against any security context constraint: [provider restricted: .spec.securityContext.fsGroup: Invalid value: []int64{1001}: 1001 is not an allowed group spec.containers[0].securityContext.runAsUser: Invalid value: 1001: must be in the ranges: [1000630000, 1000639999]]
```
- Make easier the downstream process by addressing the same fix done in https://github.com/openshift/ocp-release-operator-sdk/pull/84/files#diff-62df55fca2d17f047db431766e3962fa139afff08331dedf0863ec9d86dd7 …
> helm/samples: customize config/sample to allow it runs in OCP with default config

- changelog/fragments/fix-bundle-validate-panic.yaml
- internal/cmd/operator-sdk/bundle/validate/validate.go
I faced an issue with `operator-sdk bundle validate` that is quite easy to reproduce, see the command/result below:
```shell
operator-sdk bundle validate --image-builder docker quay.io/blaqkube/mysql-operator:0.4.0
INFO[0000] Unpacking image layers
INFO[0000] running /usr/bin/docker pull quay.io/blaqkube/mysql-operator:0.4.0
INFO[0001] running docker create
INFO[0001] running docker cp
INFO[0001] running docker rm
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x13b0f86]
goroutine 1 [running]:
github.com/operator-framework/operator-sdk/internal/cmd/operator-sdk/bundle/validate/internal.(*Result).prepare(0x0, 0x15, 0x7fff15fead90) …
```
> Fix panic with "operator-sdk bundle validate" and OCI

- README.md
- website/content/en/_index.html
- website/content/en/docs/overview/_index.md
**Description of the change:** remove old link
**Motivation for the change:** use upstream docs
Closes #3801
**Checklist**
> *: replace defunct coreos.com/operators/ with kubernetes.io link

- website/content/en/docs/building-operators/golang/tutorial.md
**Description of the change:** fix link
**Motivation for the change:** broken link is blocking patches
**Checklist**
> docs: fix broken link

- Makefile
**Description of the change:** upgrade envtest in dev Makefile
**Motivation for the change:** align dev Makefile with controller-runtime dep version
/area testing
**Checklist**
> Makefile: bump envtest version to v0.7.0

- changelog/fragments/kuttl-v0.8.0.yaml
- images/scorecard-test-kuttl/Dockerfile
**Description of the change:** upgrade the `kudobuilder/kuttl` base image version in the `scorecard-test-kuttl` image to v0.8.0
**Motivation for the change:** new kuttl release has features/changes required for #4329 
**Checklist**
> images/scorecard-test-kuttl: upgrade kuttl to v0.8.0

- changelog/fragments/helm_operator_fix_helm_keep_annotated_delete.yaml
- internal/helm/client/client.go
- internal/helm/client/client_test.go
Helm operator: updated the ownerRefInjectingClient to not inject the owner references if it contains the annotation: 
```
annotations:
"helm.sh/resource-policy": keep
```
see https://helm.sh/docs/howto/charts_tips_and_tricks/ for more details about the `keep` annotation.
For the Helm operator delete CR, namespace scope resources with the Helm keep annotation are being GC'ed by Kubernetes.
This change is to make sure those resources are not owned by the CR so they won't get GC'ed.
Closes: https://github.com/operator-framework/operator-sdk/issues/4378
After this change, I can no longer reproduces the issue described in https://github.com/operator-framework/operator-sdk/issues/4378 …
> fix: (helm) - do not add owner references to resources that contain the Helm keep resource-policy annotation

- .github/workflows/rerun.yml
**Description of the change:** rerun failed actions with `/test <action name>` or all failed actions with `/retest` (same commands as prow)
**Motivation for the change:** closes #3712 
See [test PR](https://github.com/estroz/operator-sdk/pull/14) and corresponding [actions runs](https://github.com/estroz/operator-sdk/runs/1581202133?check_suite_focus=true).
**Checklist**
> .github/workflows: add rerun-actions action to rerun other actions by comment

- hack/ci/check-doc-only-update.sh
- hack/ci: remove workflows dir from docs-only check
**Motivation for the change:** workflow changes should be fully tested
**Checklist**
> hack/ci: remove workflows dir from docs-only check

- internal/olm/operator/registry/index_image.go
- internal/olm/operator/registry/operator_installer.go
Handle operator bundle upgrade from traditional operator installation without executing `run bundle` command to deploy the operator bundle.
Supporting a use-case where an operator bundle was deployed onto the cluster without executing `run bundle`, and still being able to perform upgrades to it thereafter, through `run bundle-upgrade` command.
/cc @joelanford @estroz @jmrodri
> Handle operator bundle upgrade from traditional operator installation

- website/content/en/docs/building-operators/ansible/tutorial.md
Fixes a tiny typo I found while reading through the Ansible Operator SDK tutorial.
I don't like typos.
**Checklist**
> Fix a tiny typo in Ansible tutorial.

- website/content/en/docs/upgrading-sdk-version/v0.19.0.md
- docs/upgrading-sdk-version/v0.19.0.md: add link to and note about v0.19.x migration guide
**Motivation for the change:** it is confusing to see two different migration guides when migrating a Go project to v0.19.0, one of which is specifically for v0.19.0 and the other for v1.x (latest).
**Checklist**
> docs/upgrading-sdk-version: note v0.19.0 migration guide as well as latest

- website/content/en/docs/building-operators/ansible/quickstart.md
- website/content/en/docs/building-operators/ansible/tutorial.md
- website/content/en/docs/building-operators/golang/quickstart.md
- website/content/en/docs/building-operators/golang/tutorial.md
While using the operator-sdk docs, I encountered the following issues:
- Link in https://sdk.operatorframework.io/docs/building-operators/golang/tutorial/#prerequisites for install is incorrect. It should be https://sdk.operatorframework.io/docs/building-operators/golang/installation/
- Error when run: `make docker-build IMG=hub.docker.com/$USERNAME/memcached-operator:v0.0.1` in https://sdk.operatorframework.io/docs/building-operators/golang/tutorial/#build-and-push-the-image:
```
[...]
Failure [0.005 seconds]
[BeforeSuite] BeforeSuite 
/home/marty/projects/memcached-operator/controllers/suite_test.go:52
Unexpected error:
<*fmt.wrapError | 0xc0003d0ac0>: {
msg: "failed to start the controlplane. retried 5 times: fork/exec /usr/local/kubebuilder/bin/etcd: no …
```
> Updates to the tutorial docs

- changelog/fragments/helm-ansible-download-makefile.yaml
- internal/plugins/ansible/v1/scaffolds/internal/templates/makefile.go
- internal/plugins/helm/v1/scaffolds/internal/templates/makefile.go
- testdata/ansible/memcached-operator/Makefile
- testdata/helm/memcached-operator/Makefile
- internal/plugins/{ansible,helm}: fix download URLs and order of binary checks checks for all downloaded binaries
**Motivation for the change:** v1.3.0 changed the download URL for release artifacts so Makefiles must be updated (this needs to be backported). While fixing this I noticed that the downloaded binary is being re-downloaded if a global `helm-operator` or `ansible-operator` binary are present.
/kind bug
**Checklist**
> (helm/v1,ansible/v1) fix download URLs and order of binary checks

- website/content/en/docs/advanced-topics/operator-capabilities/operator-capabilities.md
This change removes three trailing double-asterisks in headers on the Operator Capabilities documentation. 
Closes #4397
Clarity and style consistency
**Checklist**
> Removed trailing double-asterisks on a several headers 

- website/content/en/docs/contribution-guidelines/releasing.md
- website/content/en/docs/installation/_index.md
- docs: add ubuntu keyserver to installation instructions, remove gpg requirement from release guide
**Motivation for the change:** the default gpg server does not work.
Closes #4435 
**Checklist**
> docs: add ubuntu keyserver to installation instructions, remove gpg requirement from release guide

- changelog/fragments/bugfix-generate-no-project-name.yaml
- internal/cmd/operator-sdk/generate/bundle/bundle.go
- internal/cmd/operator-sdk/generate/internal/genutil.go
- internal/cmd/operator-sdk/generate/packagemanifests/packagemanifests.go
- internal/cmd/operator-sdk/generate: respect project version when getting package name
**Motivation for the change:** project version determines how package name is retrieved for a project (dir name vs. config's `projectName` field).
/kind bug
**Checklist**
> generate: respect project version when getting package name

- changelog/fragments/bugfix-generate-no-project-name.yaml
- internal/cmd/operator-sdk/generate/bundle/bundle.go
- internal/cmd/operator-sdk/generate/internal/genutil.go
- internal/cmd/operator-sdk/generate/packagemanifests/packagemanifests.go
> generate: respect project version when getting package name (#4431)

- website/content/en/docs/faqs/_index.md
> add kubebuilder/operator-sdk FAQ

- website/content/en/docs/building-operators/golang/tutorial.md
Operator-SDK v1.3.0 introduced kubebuilder Go [CLI plugin](https://master.book.kubebuilder.io/reference/cli-plugins.html) v3.  This uses new controller logic in `controller-runtime v0.7.0`. The Go tutorial therefore needs to point to the new version of the memcached example implementation so it will build as the `Reconcile()` definition changed.
Fix usability of the Go tutorial.
**Checklist**
> docs: Update memcached example implementation in Go tutorial

- website/content/en/docs/building-operators/ansible/tutorial.md
- website/content/en/docs/building-operators/golang/references/openapi-validation.md
- website/content/en/docs/building-operators/golang/tutorial.md
- website/content/en/docs/building-operators/helm/tutorial.md
- remove webhooks statements from tutorial since it does not use webhooks might bring confusion
- add as next step integrate the project with OLM instead of use webhooks which shows that is more aligned with the goal
- move the open API validation and multigroup support to reference since both are not features used in the example
- add clarifications over the reconcile and APIs to make clear how it works and address common questions such as https://github.com/operator-framework/operator-sdk/issues/4013, https://github.com/operator-framework/operator-sdk/issues/4030, #4077
- add an overview to clarifies the goal of the tutorial. 
- add a note to make clear that k8s recommends use conditionals for the status definitions
> doc: improve/fix memcached go tutorial

- changelog/fragments/bugfix-run-bundle-upgrade.yaml
- internal/olm/operator/registry/operator_installer.go
`run bundle-upgrade` command handles error instead of throwing a panic, when a previous version of the operator bundle doesn't exist in the cluster 
```
Without installing etcd operator, 
Result:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1978d29]
```
Expected behavior: The command should check that the etcd operator doesn't exist in the cluster and handle the error gracefully instead of throwing a panic.
**Checklist**
> Bug 1921458: `run bundle-upgrade` should handle error gracefully when a previous operator version doesn't exist

- changelog/fragments/fix-bundle-validate-failure-on-warnings.yaml
- go.mod
- go.sum
Bumped to operator-framework/api.
Bundle validate with optional validators would fail if there was a warning during the validation instead of passing but listing out the warning.
```
$ build/operator-sdk bundle validate --select-optional name=operatorhub registry-proxy.engineering.redhat.com/rh-osbs/openshift-ose-clusterresourceoverride-operator-bundle:v4.6.0.202101230113.p0-1
...
ERRO[0001] Error: Value : (clusterresourceoverride-operator.4.6.0-202101230113.p0) Warning: Value : csv.Spec.Icon not specified 
```
**Checklist**
> Bug 1921727: Bundle validate should not fail because of warnings.

- internal/olm/operator/registry/operator_installer.go
If subscription doesn't match any existing package name, then return error instead of panic. 
Improve error handling for `run bundle-upgrade` command
**Checklist**
> bugfix for `run bundle-upgrade`: handle subscription that matches package name not being found

- .github/ISSUE_TEMPLATE/doc-report.md
Add new issue type for documentation. Add its as the type to use from "Create documentation issue" link on the sdk docs.
Fixes #4129 
Fixes #4349 
**Checklist**
> Add issues template for documentation

- changelog/fragments/helm-uninstall-fix.yaml
- internal/helm/release/manager.go
The Helm `History()` function already returns a ErrReleaseNotFound error if no such release name exists.
see https://github.com/helm/helm/blob/v3.2.4/pkg/storage/storage.go#L148-L154
The current additional check of `if len(h) == 0 ` might cause an issue where the release might actually exist but during decoding of the release, it ran into an error and not append it to the list of return result.
see https://github.com/helm/helm/blob/v3.2.4/pkg/storage/driver/secrets.go#L125-L138
Which leads to the Helm operator incorrectly determines that the release doesn't exist and skips the actual helm uninstall call.
In some cases, the Helm-operator doesn't call the equivalent of the `helm uninstall` …
> Bug fix: helm operator uninstall is not properly checking for existing release

- changelog/fragments/fix-bundle-validate-failure-on-warnings.yaml
- go.mod
- go.sum
Cherry-pick of #4449
Signed-off-by: Eric Stroczynski <estroczy@redhat.com>
> [v1.3.x]  Bug 1921727: Bundle validate should not fail because of warnings. (#4449)

- changelog/fragments/bugfix-validate-add-mode.yaml
- internal/olm/operator/bundle/install.go
- internal/olm/operator/bundleupgrade/upgrade.go
- internal/olm/operator/registry/index/bundle_add_mode.go
- internal/olm/operator/registry/index/registry_pod.go
- internal/olm/operator/registry/index/registry_pod_test.go
- internal/olm/operator: validate BundleAddMode before running a bundle image
**Motivation for the change:** values should be validated before the heavy lifting of these commands occurs (pulling/unpacking a bundle)
/kind bug
**Checklist**
> `run bundle{-upgrade}`: validate `--mode` before running a bundle

- changelog/fragments/phase-2-plugin-keys.yaml
- internal/plugins/ansible/v1/api.go
- internal/plugins/ansible/v1/init.go
- internal/plugins/golang/v2/api.go
- internal/plugins/golang/v2/config.go
- internal/plugins/golang/v2/init.go
- internal/plugins/helm/v1/api.go
- internal/plugins/helm/v1/init.go
- internal/plugins/manifests/v2/plugin.go
- testdata/ansible/memcached-operator/PROJECT
- testdata/go/v2/memcached-operator/PROJECT
- testdata/helm/memcached-operator/PROJECT
- internal/plugins: add `manifests` and `scorecard` plugin keys to ansible/v1, helm/v1, and go/v2 projects on init, and consider these keys when running `create api`
**Motivation for the change:** All phase 2 plugins should have keys in the `plugins` config field. This (backwards-compatible) change makes it so.
**Checklist**
> internal/plugins: add `manifests` and `scorecard` plugin keys to all projects

- changelog/fragments/csv-gen-package-aware.yaml
- internal/generate/clusterserviceversion/bases/definitions/ast.go
- internal/generate/clusterserviceversion/bases/definitions/crd.go
- internal/generate/clusterserviceversion/bases/definitions/definitions.go
- internal/generate/clusterserviceversion/bases/definitions/definitions_test.go
- internal/generate/clusterserviceversion/bases/definitions/markers.go
- internal/generate/clusterserviceversion/clusterserviceversion_updaters.go
- internal/generate/testdata/go/api/shared/doc.go
- internal/generate/testdata/go/api/shared/memcached_types.go
- internal/generate/testdata/go/api/v1alpha1/memcached_types.go
- internal/generate/testdata/go/api/v1alpha2/dummy_types.go
- internal/generate/testdata/go/api/v1alpha2/memcached_types.go
- internal/generatel/clusterserviceversion/bases/definitions: make the owned CRD generator package- and type-aware so multiple packages containing the same type names can be used.
**Motivation for the change:** currently the CSV generator indexes types in the struct-field hierarchy by type name only, which is potentially not unique between packages. This PR makes the generator package-aware.
Closes #4409
Closes #3744 
/kind bug
**Checklist**
> generate: make CSV generator for Go GVKs package-aware

- website/content/en/docs/building-operators/golang/advanced-topics.md
- docs/building-operators/golang/advanced-topics.md: fix file path reference
**Motivation for the change:** old file path
**Checklist**
> docs: fix incorrect file path

- internal/ansible/controller/reconcile.go
- internal/helm/controller/reconcile.go
- internal/{helm,ansible}/controller: use `Reconcile()`'s ctx argument in Client method calls
**Motivation for the change:** this should have happened when upgrading controller-runtime to v0.7.0
**Checklist**
> internal/{helm,ansible}/controller: use correct context in client.Client calls

- website/content/en/docs/building-operators/golang/migration.md
- website/content/en/docs/building-operators/golang/references/client.md
- website/content/en/docs/building-operators/golang/references/event-filtering.md
- website/content/en/docs/building-operators/golang/tutorial.md
- docs/building-operators/golang: fix `context.Context` usage, imports, and general formatting
**Motivation for the change:** docs weren't using the correct `context.Context` value (see #4474), imports weren't formatted correctly, and different GVKs were used which is confusing.
**Checklist**
> docs/building-operators/golang: fix context.Context usage, imports, general formatting

- changelog/fragments/upgrade-python-on-ansible-operator.yaml
- images/ansible-operator/Dockerfile
- website/content/en/docs/building-operators/ansible/installation.md
Upgrade Python to version 3.8 to facilitate local development (i.e. without having to resort to deadsnakes repos and suchlikes) and benefit from performance enhancements in more recent versions of Python (with 3.6 functionally mothballed now)
The Ansible operator uses an outdated version of Python that hampers local development and reproducible builds as it requires you to keep around an old version of Python. Since many recent distros don't ship Python 3.6 in their standard packaging repositories anymore, this requires a manual install, or alternate package repositories.
*Note*: this is a first pull request to start addressing the issues mentioned in #4237 
**Checklist**
If the pull request includes user-facing changes, extra …
> upgrade Python to v 3.8

- changelog/fragments/change-finalizer-format.yaml
- hack/generate/samples/internal/ansible/constants.go
- internal/ansible/controller/reconcile.go
- internal/ansible/controller/reconcile_test.go
- internal/ansible/runner/runner_test.go
- internal/ansible/watches/testdata/duplicate_gvk.yaml
- internal/ansible/watches/testdata/invalid.yaml
- internal/ansible/watches/testdata/invalid_finalizer_no_vars.yaml
- internal/ansible/watches/testdata/invalid_finalizer_playbook_path.yaml
- internal/ansible/watches/testdata/invalid_finalizer_role_path.yaml
- internal/ansible/watches/testdata/invalid_playbook_path.yaml
- internal/ansible/watches/testdata/invalid_role_path.yaml
- internal/ansible/watches/testdata/valid.yaml.tmpl
- internal/ansible/watches/watches_test.go
- internal/helm/controller/reconcile.go
- test/e2e-ansible/e2e_ansible_suite_test.go
- website/content/en/docs/building-operators/ansible/reference/finalizers.md
- website/content/en/docs/building-operators/ansible/reference/watches.md
- website/content/en/docs/building-operators/golang/advanced-topics.md
**Description of the change:** change all references to the old finalizer name format to the format suggested [upstream](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#finalizers).
**Motivation for the change:** This PR modifies the suggested format for finalizers from `<finalizer-name>.<qualified-group>` to `<qualified-group>/<finalizer-name>`, which is the recommended format in k8s docs. This change is not breaking because technically any name format is allowed
**Checklist**
> *: format finalizers correctly

- changelog/fragments/fix-trim-format-dns1123-functions.yaml
- internal/olm/operator/registry/configmap/deployment_test.go
- internal/util/k8sutil/k8sutil.go
- internal/util/k8sutil/k8sutil_test.go
* TrimDNS1123Label would trim strings but end up creating invalid DNS1123
strings.
* FormatOperatorNameDNS1123 would return strings that were invalid if
they begin or end with non-alphanumeric or hyphens.
Fixes #4470
Signed-off-by: jesus m. rodriguez <jmrodri@gmail.com>
**Checklist**
> Fixed invalid object names generated for long package names 

- changelog/fragments/reorder-docker-args.yaml
- internal/plugins/ansible/v1/scaffolds/internal/templates/makefile.go
- internal/plugins/helm/v1/scaffolds/internal/templates/makefile.go
- testdata/ansible/memcached-operator/Makefile
- testdata/helm/memcached-operator/Makefile
Because folks may have `docker` aliased to `podman`, and Podman prefers options before positional arguments:
```console
$ podman build --help | grep CONTEXT-DIRECTORY
podman build [command options] CONTEXT-DIRECTORY | URL
```
Supersedes PR #4226 
Co-authored-by: W. Trevor King <wking@tremily.us>
Signed-off-by: jesus m. rodriguez <jmrodri@gmail.com>
**Checklist**
> *: Replace 'docker build . -t ${IMG}' with '-t ${IMG} .'

- Makefile
- testdata/ansible/memcached-operator/Dockerfile
- testdata/ansible/memcached-operator/Makefile
- testdata/ansible/memcached-operator/bundle/tests/scorecard/config.yaml
- testdata/ansible/memcached-operator/config/scorecard/patches/basic.config.yaml
- testdata/ansible/memcached-operator/config/scorecard/patches/olm.config.yaml
- testdata/go/v2/memcached-operator/bundle/tests/scorecard/config.yaml
- testdata/go/v2/memcached-operator/config/scorecard/patches/basic.config.yaml
- testdata/go/v2/memcached-operator/config/scorecard/patches/olm.config.yaml
- testdata/go/v3/memcached-operator/bundle/tests/scorecard/config.yaml
- testdata/go/v3/memcached-operator/config/scorecard/patches/basic.config.yaml
- testdata/go/v3/memcached-operator/config/scorecard/patches/olm.config.yaml
- testdata/helm/memcached-operator/Dockerfile
- testdata/helm/memcached-operator/Makefile
- testdata/helm/memcached-operator/bundle/tests/scorecard/config.yaml
- testdata/helm/memcached-operator/config/scorecard/patches/basic.config.yaml
- testdata/helm/memcached-operator/config/scorecard/patches/olm.config.yaml
- bump IMAGE_VERSION to v1.3.1
**Motivation for the change:** get ready for v1.3.1
**Checklist**
> [v1.3.x] bump IMAGE_VERSION to v1.3.1

- Makefile
- testdata/ansible/memcached-operator/Dockerfile
- testdata/ansible/memcached-operator/Makefile
- testdata/ansible/memcached-operator/bundle/tests/scorecard/config.yaml
- testdata/ansible/memcached-operator/config/scorecard/patches/basic.config.yaml
- testdata/ansible/memcached-operator/config/scorecard/patches/olm.config.yaml
- testdata/go/v2/memcached-operator/bundle/tests/scorecard/config.yaml
- testdata/go/v2/memcached-operator/config/scorecard/patches/basic.config.yaml
- testdata/go/v2/memcached-operator/config/scorecard/patches/olm.config.yaml
- testdata/go/v3/memcached-operator/bundle/tests/scorecard/config.yaml
- testdata/go/v3/memcached-operator/config/scorecard/patches/basic.config.yaml
- testdata/go/v3/memcached-operator/config/scorecard/patches/olm.config.yaml
- testdata/helm/memcached-operator/Dockerfile
- testdata/helm/memcached-operator/Makefile
- testdata/helm/memcached-operator/bundle/tests/scorecard/config.yaml
- testdata/helm/memcached-operator/config/scorecard/patches/basic.config.yaml
- testdata/helm/memcached-operator/config/scorecard/patches/olm.config.yaml
- bump IMAGE_VERSION to v1.4.0
**Motivation for the change:** get ready for v1.4.0
**Checklist**
> update IMAGE_VERSION to v1.4.0

- internal/ansible/controller/reconcile.go
- internal/ansible/events/log_events.go
Log GVK, namespace and CR name as part of the ansible output
If our ansible operator allows multiple workers to run reconcile on multiple namespaces with different CR type, then the concurrency of multiple reconcile is very hard to know which CR that the output tie to, so we need to put more info in the output
**Checklist**
> ansible output should log with GVK info, namespace as the CR name

- changelog/fragments/kube-rbac-proxy.yaml
- internal/generate/testdata/clusterserviceversions/output/memcached-operator.clusterserviceversion.yaml
- internal/generate/testdata/clusterserviceversions/output/with-ui-metadata.clusterserviceversion.yaml
- internal/generate/testdata/go/static/basic.operator.yaml
- internal/plugins/ansible/v1/scaffolds/internal/templates/config/kdefault/auth_proxy_patch.go
- internal/plugins/helm/v1/scaffolds/internal/templates/config/kdefault/auth_proxy_patch.go
- testdata/ansible/memcached-operator/bundle/manifests/memcached-operator.clusterserviceversion.yaml
- testdata/ansible/memcached-operator/config/default/manager_auth_proxy_patch.yaml
- testdata/helm/memcached-operator/bundle/manifests/memcached-operator.clusterserviceversion.yaml
- testdata/helm/memcached-operator/config/default/manager_auth_proxy_patch.yaml
- website/content/en/docs/building-operators/golang/references/logging.md
-   For Ansible/Helm based-operators, upgrade the `kube-rbac-proxy` image version from `0.5.0` to `0.8.0` to address security concerns. More info [#kubernetes-sigs/kubebuilder#1955](https://github.com/kubernetes-sigs/kubebuilder/pull/1955).
- Closes: #3925
**Checklist**
- [x ] Add a new changelog fragment in `changelog/fragments` (see [`changelog/fragments/00-template.yaml`](https://github.com/operator-framework/operator-sdk/tree/master/changelog/fragments/00-template.yaml))
> Fix kube rbac proxy

- images/ansible-operator/Dockerfile
- images/ansible-operator/Dockerfile: pin cryptography python package t…o version that does not require the rust compiler to set up
**Motivation for the change:** ansible-operator image build is broken:
```console
$ git checkout v1.3.x
$ make image/ansible-operator
...
Collecting cryptography (from ansible==2.9.15)
Downloading https://files.pythonhosted.org/packages/27/5a/007acee0243186123a55423d49cbb5c15cb02d76dd1b6a27659a894b13a2/cryptography-3.4.4.tar.gz (545kB)
Complete output from command python setup.py egg_info:
...
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/tmp/pip-build-7t2f19qr/cryptography/setup.py", line 14, in <module>
from setuptools_rust import RustExtension
ModuleNotFoundError: No module named …
```
> [v1.3.x] images/ansible-operator/Dockerfile: pin cryptography python package

- website/content/en/docs/upgrading-sdk-version/v1.3.0.md
- docs/upgrade-sdk-version/v1.3.0.md: correct link to migration guide
**Motivation for the change:** broken link. Note that this may have to be updated again once book-v3 is realeased. For now this fixes the link check.
**Checklist**
> docs/upgrade-sdk-version/v1.3.0.md: correct link to migration guide

- .github/workflows/test-sanity.yml
- .travis.yml
- Makefile
- website/content/en/docs/contribution-guidelines/documentation.md
- Makefile: rename test-links to test-docs, move changelog validator here
- *: update docs/tests with test-docs target
**Motivation for the change:** docs-only PR's always run code-checking tests in the sanity action, which are not required and use action minutes unnecessarily.
**Checklist**
> Makefile: `test-docs` target tests docs only

- internal/olm/operator/registry/operator_installer.go
- internal/olm/operator/registry/operator_installer_test.go
Fixes `no supported install modes` error when installing Operators
in install mode MultiNamespace via
`operator-sdk run bundle --install-mode MultiNamespace=x,y`
Closes #4512
> fix bundle run install mode MultiNamespace

- website/content/en/docs/building-operators/golang/migration.md
- website/content/en/docs/faqs/_index.md
Improve/Upgrade the migration guide to address the need of the users to move from pre-1.0.0 to latest
- Closes: https://github.com/operator-framework/operator-sdk/issues/4392
Preview: https://deploy-preview-4536--operator-sdk.netlify.app/docs/building-operators/golang/migration/
> Improve/Upgrade the migration guide to address the need of the users to move from pre-1.0.0 to latest

- internal/olm/operator/registry/configmap.go
- internal/olm/operator/registry/operator_installer.go
- internal/olm/operator/registry/operator_installer_test.go
Updated `getInstalledCSV` to accept an `Option` type to allow passing in an OLM client.
`getInstalledCSV` was not testable because there was no way to fake out the OLM client which was created directly in the code. Running unit tests locally without a running cluster would cause the test to fail. Because of this there were no unit tests for it.
Fixes #4173
**Checklist**
Signed-off-by: jesus m. rodriguez <jmrodri@gmail.com>
> Make getInstalledCSV testable

- website/content/en/docs/upgrading-sdk-version/v1.4.0.md
Signed-off-by: Florin Hillebrand <flozzone@gmail.com>
Fix the paths to the manager resource file in the docs upgrade docs for version 1.4.2.
Paths to the resource file were wrong.
**Checklist**
> docs: fix wrong paths in 1.4.2 upgrade guide. (#4541)

- website/content/en/docs/contribution-guidelines/releasing.md
Add doc on reverting changes made in release PR
in case there is a build failure.
**Checklist**
> [release] add doc on reverting release changes

- internal/plugins/ansible/v1/scaffolds/internal/templates/makefile.go
- internal/plugins/helm/v1/scaffolds/internal/templates/makefile.go
- testdata/ansible/memcached-operator/Makefile
- testdata/helm/memcached-operator/Makefile
Remove the shell specification in ansible
and helm makefiles.
Currently, we are hardcoding `SHELL` to point to `/bin/sh`.  Its not necessary that  `/bin/sh` invokes sh or points to bash, it can be a symbolic link invoking any other shell which may give errors. Instead, if required we could add a documentation similar to as we have for [Golang](https://sdk.operatorframework.io/docs/building-operators/golang/tutorial/#build-and-push-the-image) operators, suggesting to use bash. 
Closes: #4403 
**Checklist**
> Remove `shell` specification in Makefile for Ansible and Helm

- changelog/fragments/swap-readiness-liveness-paths-4541.yaml
- internal/plugins/ansible/v1/scaffolds/internal/templates/config/manager/manager.go
- internal/plugins/helm/v1/scaffolds/internal/templates/config/manager/manager.go
- testdata/ansible/memcached-operator/bundle/manifests/memcached-operator.clusterserviceversion.yaml
- testdata/ansible/memcached-operator/config/manager/manager.yaml
- testdata/helm/memcached-operator/bundle/manifests/memcached-operator.clusterserviceversion.yaml
- testdata/helm/memcached-operator/config/manager/manager.yaml
* created changelog fragment
* fixed scaffold template for the manager resource (ansible/helm)
* fixed testdata (ansible/helm)
Signed-off-by: Florin Hillebrand <flozzone@gmail.com>
Fix wrong HTTP paths of the livenessProbe and readinessProbe in the scaffold templates and testdata.
livenessProbe and readinessProbe were swapped in templates but are correctly documented in upgrade guide.
**Checklist**
> fix swapped liveness/readiness http paths. (#4541)

- website/content/en/docs/building-operators/golang/installation.md
- website/content/en/docs/installation/_index.md
Remove `mercurial` from the prerequisites list for current docs.
Fixes #4559 
**Checklist**
> docs: Remove mercurial from current install guide.

- website/content/en/docs/building-operators/golang/installation.md
- website/content/en/docs/building-operators/golang/migration.md
- website/content/en/docs/contribution-guidelines/developer-guide.md
- website/content/en/docs/installation/_index.md
**Description of the change:** specify go 1.15 must be used
**Motivation for the change:** some upstream deps might fail to build with newer or older versions of go, so only the version tested with the binary/latest Go plugin should be used.
Closes #4556 
**Checklist**
> docs/: specify go 1.15 must be used

- hack/generate/samples/internal/go/v3/memcached_with_webhooks.go
- testdata/go/v3/memcached-operator/bundle/manifests/memcached-operator.clusterserviceversion.yaml
- testdata/go/v3/memcached-operator/config/rbac/role.yaml
- testdata/go/v3/memcached-operator/controllers/memcached_controller.go
- hack/generate/samples/internal/go/v3/memcached_with_webhooks.go: add `watch` verb to RBAC marker
**Motivation for the change:** see https://github.com/operator-framework/operator-sdk/issues/4059#issuecomment-712858011
Closes #4433 
**Checklist**
> samples(go/v3): add watch verb to RBAC marker

- website/content/en/docs/building-operators/ansible/installation.md
- website/content/en/docs/building-operators/golang/installation.md
- website/content/en/docs/building-operators/golang/tutorial.md
- website/content/en/docs/building-operators/helm/installation.md
- website/content/en/docs/contribution-guidelines/testing.md
- website/content/en/docs/overview/_index.md
- docs/overview/_index.md: document k8s version compatibility and platform support
- docs/building-operators: update all cluster version references
**Motivation for the change:** k8s versions required are not actually correct. This PR adds instructions to correctly deduce whether a project/binary is compatible with a particular k8s version.
Closes #4385 
**Checklist**
> docs: document k8s version compatibility and platform support

- README.md
- README.md: update support info with links to SDK docs website
**Motivation for the change:** relevant link updates from #4574 
**Checklist**
> README.md: update support info with links to SDK docs website

- hack/generate/samples/internal/go/v2/memcached_with_webhooks.go
- hack/generate/samples/internal/go/v3/memcached_with_webhooks.go
- testdata/go/v2/memcached-operator/controllers/memcached_controller.go
- testdata/go/v3/memcached-operator/controllers/memcached_controller.go
fix/sample/go: use recon after x time to ensure that the pod names were created
**Motivation**
Clarifies why the requeue is made and provide a better example.
> fix/sample/go: use recon after x time to ensure that the pod names were created 

- hack/tests/e2e-ansible-molecule.sh
- hack/tests/e2e-ansible-molecule.sh: run tests in venv, pin versions
**Motivation for the change:** ansible-molecule tests seem to be [broken](https://github.com/operator-framework/operator-sdk/runs/1983461382?check_suite_focus=true) (appears to be caused by version 12.0.0 of the `openshift` dependency, which was released a few hours ago). This PR changes ansible-molecule tests to run in a venv as to not pollute host environment, and pins the `openshift` dependency to the prior version.
/area testing
**Checklist**
> tests: fix ansible-molecule tests, install deps in venv, pin versions

- changelog/fragments/bugfix-4575.yaml
- hack/generate/samples/internal/helm/memcached.go
- internal/plugins/helm/v1/api.go
- internal/plugins/helm/v1/chartutil/chart.go
- internal/plugins/helm/v1/chartutil/chart_test.go
- internal/plugins/helm/v1/init.go
- internal/plugins/helm/v1/scaffolds/api.go
- internal/plugins/helm/v1/scaffolds/init.go
- internal/plugins/helm/v1/chartutil: have CreateChart() return a resource.Resource instead of golang.Options
- internal/plugins/helm/v1: refactor to run createAPISubcommand after initSubcommand finishes execution
This PR fixes samples kustomization.yaml generation when running `operator-sdk init --plugins=helm --helm-chart=<chart>`, an error caused by out-of-order operations in plugin code.
Closes #4575 
/kind bug
**Checklist**
> (helm/v1) run `create api` plugin only after `init` plugin finishes execution

- test/common/scorecard.go
- test/e2e/ansible/cluster_test.go
- test/e2e/ansible/scorecard_test.go
- test/e2e/ansible/suite_test.go
- test/e2e/go/cluster_test.go
- test/e2e/go/scorecard_test.go
- test/e2e/go/suite_test.go
- test/e2e/helm/cluster_test.go
- test/e2e/helm/scorecard_test.go
- test/e2e/helm/suite_test.go
- test/: refactor scorecard tests into a spec function in common, remove 'By()' calls in poll function
**Motivation for the change:** scorecard test code is repeated across all e2e test types. This PR refactors that code into a spec-running function.
/area testing
**Checklist**
> test/: refactor scorecard e2e test, clean up existing test poll funcs

- .github/workflows/deploy-manual.yml
- images/ansible-operator/Dockerfile
- images/ansible-operator/base.Dockerfile
- images/ansible-operator/base.Dockerfile: Dockerfile for the ansible-operator-base image
- .github/workflows/deploy-manual.yml: start workflows manually, namely the ansible-operator-base image deployment job
**Motivation for the change:** the ansible-operator image takes awhile to build, so it would be nice to build a base image containing the long-running dependency installation steps every so often, ex. when dependencies are updated.
**Checklist**
> ci: add ansible-operator-base image and manual build workflow

- internal/plugins/ansible/v1/api.go
- internal/plugins/ansible/v1/init.go
- internal/plugins/ansible/v1/scaffolds/api.go
- internal/plugins/ansible/v1/scaffolds/init.go
- internal/plugins/ansible/v1: refactor to run createAPISubcommand after initSubcommand finishes execution
**Motivation for the change:** This PR refactors `init --plugins=ansible` with GVK flags to run the `create api` plugin only after the `init` plugin completes, much like running `operator-sdk init && operator-sdk create api`.
Follows up on #4584
**Checklist**
> (ansible/v1) run `create api` plugin only after `init` plugin finishes execution

- .github/workflows/deploy-manual.yml
- .github/workflows/deploy-manual.yml: checkout before tag creation for git data
**Motivation for the change:** `git describe` needs all git history
**Checklist**
> actions/deploy-manual: checkout before tag creation for git data

- internal/generate/clusterserviceversion/clusterserviceversion_updaters_test.go
**Description of the change:** add unit tests
**Motivation for the change:** wrote these as part of triaging #4041, might as well merge them.
**Checklist**
> internal/generate/clusterserviceversion: add tests for apply{Cluster}Roles()

- images/ansible-operator/base.Dockerfile
- images/ansible-operator/base.Dockerfile: move some setup out of base image, fix ansible.cfg setup
**Motivation for the change:** `tini` should be invoked as an entrypoint, and user setup should be, in the final ansible-operator image.
**Checklist**
> images/ansible-operator/base.Dockerfile: move some setup out of base image

- images/ansible-operator/Dockerfile
- images/ansible-operator/Dockerfile: use ansible-operator-base image as ansible-operator final base image @[v1.4.0-45-g65af4898a1cbeb032954979c68bba0d422454b6d](https://github.com/operator-framework/operator-sdk/runs/2034778959).
**Motivation for the change:** newly built ansible-operator-base image.
Follows up on #4555
**Checklist**
> images/ansible-operator/Dockerfile: use ansible-operator-base image

- .github/workflows/deploy.yml
- .github/workflows/deploy.yml: check if docs-only before running
**Motivation for the change:** image builds do not need to run on docs-only PRs
**Checklist**
> actions/deploy: check if docs-only before running

- internal/testutils/utils.go
- testdata/ansible/memcached-operator/config/default/kustomization.yaml
- testdata/go/v2/memcached-operator/config/default/kustomization.yaml
- testdata/go/v3/memcached-operator/config/default/kustomization.yaml
- testdata/helm/memcached-operator/config/default/kustomization.yaml
- internal/testutils: rewrite UncommentCode() to only append newlines if line is not the last in target
**Motivation for the change:** unnecessary newlines.
**Checklist**
> testdata: remove unnecessary newlines

- changelog/fragments/kubebuilder-dd3942c.yaml
- go.mod
- go.sum
- internal/plugins/ansible/v1/api.go
- internal/plugins/helm/v1/api.go
- test/e2e/go/cluster_test.go
- test/e2e/go/suite_test.go
- testdata/go/v2/memcached-operator/go.mod
- testdata/go/v3/memcached-operator/Makefile
- testdata/go/v3/memcached-operator/bundle/manifests/memcached-operator-controller-manager_v1_serviceaccount.yaml
- testdata/go/v3/memcached-operator/bundle/manifests/memcached-operator.clusterserviceversion.yaml
- testdata/go/v3/memcached-operator/config/manager/manager.yaml
- testdata/go/v3/memcached-operator/config/rbac/auth_proxy_role_binding.yaml
- testdata/go/v3/memcached-operator/config/rbac/kustomization.yaml
- testdata/go/v3/memcached-operator/config/rbac/leader_election_role_binding.yaml
- testdata/go/v3/memcached-operator/config/rbac/role_binding.yaml
- testdata/go/v3/memcached-operator/config/rbac/service_account.yaml
- testdata/go/v3/memcached-operator/controllers/memcached_controller.go
- testdata/go/v3/memcached-operator/go.mod
- testdata/go/v3/memcached-operator/go.sum
- website/content/en/docs/advanced-topics/scorecard/custom-tests.md
- website/content/en/docs/advanced-topics/scorecard/kuttl-tests.md
- website/content/en/docs/building-operators/golang/migration.md
- deps: bump kubebuilder to https://github.com/kubernetes-sigs/kubebuilder/commit/dd3942c97cf5ade5e686a4531712297a9deb1cc9, update where necessary
- docs/: document service account featrue
**Motivation for the change:** recent changes in kubebuilder
Closes #4468 
**Checklist**
> deps: bump kubebuilder to dd3942c

- website/content/en/_index.html
- website/content/en/docs/overview/_index.md
- website/content: update coreos.com blogpost link to openshift.com
**Motivation for the change:** old coreos.com link no longer exists
**Checklist**
> website/content: update non-existent coreos.com blogpost link to openshift.com

- .github/workflows/deploy-manual.yml
- .github/workflows/deploy.yml
- .github/workflows: use 'github.repository_owner' context in image tags for easier testing in fork repos
**Motivation for the change:** easier testing in forks
/area testing
**Checklist**
> .github/workflows: use 'github.repository_owner' in image tags

- hack/tests/e2e-ansible-molecule.sh
**Description of the change:** see #4588
**Motivation for the change:** latest openshift version breaks molecule tests
/area testing
**Checklist**
> [v1.4.x] hack/tests/e2e-ansible-molecule.sh: pin openshift and cryptography (#4588)

- CONTRIBUTING.MD
- internal/plugins/ansible/v1/api.go
- internal/plugins/helm/v1/chartutil/chart.go
- website/content/en/docs/building-operators/ansible/development-tips.md
- website/content/en/docs/building-operators/golang/_index.md
- website/content/en/docs/building-operators/golang/references/_index.md
- website/content/en/docs/building-operators/golang/tutorial.md
- website/content/en/docs/overview/_index.md
- website/content/en/docs/upgrading-sdk-version/v1.2.0.md
This PR renames most of the `Golang` occurrences to `Go`. The only exception are the proposals, which, are historical archives, so,  I believe that there's no need for a change.
The main motivation is to keep consistency with the naming across the project. Some sections mention Go and others  Golang. Also, [according](https://tip.golang.org/doc/faq#go_or_golang) to the official website, `Go` is the proper name to use.
**Checklist**
> Rename golang occurrences to go

- changelog/fragments/confg-3-alpha-removed.yaml
- go.mod
- internal/cmd/operator-sdk/alpha/cmd.go
- internal/cmd/operator-sdk/alpha/config3alphato3/cmd.go
- internal/cmd/operator-sdk/alpha/config3alphato3/convert_config_3-alpha_to_3.go
- internal/cmd/operator-sdk/alpha/config3alphato3/convert_config_3-alpha_to_3_test.go
- internal/cmd/operator-sdk/alpha/config3alphato3/suite_test.go
- internal/cmd/operator-sdk/cli/cli.go
- website/content/en/docs/cli/operator-sdk.md
- website/content/en/docs/cli/operator-sdk_alpha.md
- website/content/en/docs/cli/operator-sdk_alpha_config-3alpha-to-3.md
- internal/cmd/operator-sdk/alpha/config3alphato3: convert config version 3-alpha to 3, and exit after conversion
- internal/cmd/operator-sdk/cli: add PersistentPreRun to root cmd for helpful error message
**Motivation for the change:** Version 3-alpha has been removed after version 3 was released. While this change is not technically breaking because the spec at that version was alpha, it was used by default in `operator-sdk` commands so should be marked as breaking and have a convenient migration path. The `alpha config3alphato3` command will convert most of a PROJECT file from version 3-alpha to 3, and leave comments with directions where automatic conversion is not possible.
/kind feature
**Checklist**
If the pull request includes user-facing changes, …
> config3alphato3: convert config version 3-alpha to 3

- website/content/en/docs/building-operators/golang/migration.md
- website/content/en/docs/building-operators/golang/operator-scope.md
- docs/building-operators/golang: remove redundant info in migration guide, discuss service account in scope guide
**Motivation for the change:** non-default service account support was added in #4626. This PR adds follow-up docs and corrects docs added in that PR
**Checklist**
> docs: remove redundancy in Go migration, discuss service account in scope doc

- changelog/fragments/make-catalog-build.yaml
- internal/plugins/manifests/api.go
- internal/plugins/manifests/init.go
- testdata/ansible/memcached-operator/Makefile
- testdata/go/v2/memcached-operator/Makefile
- testdata/go/v3/memcached-operator/Makefile
- testdata/helm/memcached-operator/Makefile
- website/content/en/docs/olm-integration/quickstart-bundle.md
* internal/plugins/manifests: added `catalog-build`, `catalog-push`, and `opm` targets to Makefile, and improve variables/comments for ease of use.
**Motivation for the change:** this addition to the Makefile allows users to create catalog images with `opm index add`. They can string together `make` rules like so:
```sh
make bundle-build bundle-push catalog-build catalog-push BUNDLE_IMG=${SOME_BUNDLE_IMG} CATALOG_IMG=${SOME_CATALOG_IMG}
```
or if `IMAGE_TAG_BASE` is set to an existing repo:
```sh
export IMAGE_TAG_BASE=quay.io/example/my-operator
make bundle-build bundle-push catalog-build catalog-push
```
which will build and push `quay.io/example/my-operator-bundle:v0.0.1` and `quay.io/example/my-operator-catalog:v0.0.1`.
Enhancement: …
> (manifests/v2) add catalog targets to Makefile

- .github/workflows/deploy.yml
- .github/workflows/get_image_tags.sh
- .github/workflows/integration.yml
- .github/workflows/test-ansible.yml
- .github/workflows/test-go.yml
- .github/workflows/test-helm.yml
- .github/workflows/test-sanity.yml
- images/scorecard-test-kuttl/main.go
- release/Makefile
- website/content/en/docs/contribution-guidelines/releasing.md
- .github/workflows: release scorecard-test-kuttl images on `scorecard-kuttl/v*` tags, and only run image deploy jobs for code changes and appropriate tag patterns
**Motivation for the change:** breaking changes to kuttl happen, and the accepted solution is to version the scorecard-test-kuttl version independently, starting at v2.0.0 (see #4557 for details). Releases will be tagged with `scorecard-kuttl/vX.Y.Z`. operator-sdk releases will still have tags like `vA.B.C`, but will not cause scorecard-test-kuttl images to be published.
**Checklist**
> release: push scorecard-test-kuttl images on `scorecard-kuttl/v*` tags

- images/scorecard-test-kuttl/Dockerfile
Upgrade kuttl to version [0.9.0](https://github.com/kudobuilder/kuttl/releases/tag/v0.9.0) 
New version contains the [capability](https://github.com/kudobuilder/kuttl/pull/272) to run assertion based on commands/scripts, that enable more complete testing of the objects being managed
> Upgrade kuttl testing image to 0.9.0 version

- changelog/fragments/use-pipenv-for-python-package-installation.yaml
- images/ansible-operator/Pipfile
- images/ansible-operator/Pipfile.lock
- images/ansible-operator/base.Dockerfile
retry of #4538 and #4494
Signed-off-by: reinvantveer <reinvantveer@gmail.com>
Retry of previous attempt on using Pipenv as dependency management solution for Ansible operator
Previous build failed on missing gcc, which went unnoticed until checking the Travis builds on [arm64](https://travis-ci.com/github/operator-framework/operator-sdk/jobs/482845168), [ppc64le](https://travis-ci.com/github/operator-framework/operator-sdk/jobs/482845170), and [s390x](https://travis-ci.com/github/operator-framework/operator-sdk/jobs/482845171)
**Checklist**
> Use pipenv for python dependency management

- changelog/fragments/mark-variables-unsafe.yaml
- internal/ansible/runner/runner.go
- internal/ansible/runner/runner_test.go
- internal/ansible/watches/testdata/valid.yaml.tmpl
- internal/ansible/watches/watches.go
- internal/ansible/watches/watches_test.go
User provided values from the custom resource are tagged
unsafe by default.
Closes: #4169 
**Checklist**
> [ansible]: mark variables from custom resources as unsafe

- website/content/en/docs/building-operators/ansible/migration.md
- website/content/en/docs/building-operators/ansible/testing-guide.md
- website/content/en/docs/building-operators/golang/migration.md
- website/content/en/docs/building-operators/helm/migration.md
Align/Fix the Helm/Asible migration guides 
Follow up of #4392 and https://github.com/operator-framework/operator-sdk/pull/4536
**Checklist**
> doc: align ansible/helm migration guides with go

- changelog/fragments/ansible-helm-ssc.yaml
- internal/plugins/ansible/v1/scaffolds/internal/templates/config/manager/manager.go
- internal/plugins/helm/v1/scaffolds/internal/templates/config/manager/manager.go
- testdata/ansible/memcached-operator/bundle/manifests/memcached-operator.clusterserviceversion.yaml
- testdata/ansible/memcached-operator/config/manager/manager.yaml
- testdata/helm/memcached-operator/bundle/manifests/memcached-operator.clusterserviceversion.yaml
- testdata/helm/memcached-operator/config/manager/manager.yaml
Signed-off-by: Camila Macedo <cmacedo@redhat.com>
- (ansible/v1)(helm/v1) Add SecurityContext to now allow root privileges and align project languages with Golang.
- Reduce the complexities for we address https://github.com/kubernetes-sigs/kubebuilder/issues/2015
- Keep Ansible/Helm/Go aligned (Align Helm/Ansible plugins with the changes made for Golang ( go/v3 )) https://github.com/operator-framework/operator-sdk/issues/4542
- Closes: https://github.com/operator-framework/operator-sdk/issues/4656
**Checklist**
> ansible/helm: add ssc to not allow root previleges

- .github/workflows/check-docs-only.sh
- .github/workflows/deploy.yml
- .github/workflows/integration.yml
- .github/workflows/test-ansible.yml
- .github/workflows/test-go.yml
- .github/workflows/test-helm.yml
- .github/workflows/test-sanity.yml
- .github/workflows: move docs only check script here, make all calls reference the same outputs
**Motivation for the change:** patterns were incorrect, output name in workflows was incorrect
/kind bug
**Checklist**
> ci: fix docs only check patterns and workflow output names

- changelog/fragments/ansible-helm-makefile-help.yaml
- internal/plugins/ansible/v1/scaffolds/internal/templates/makefile.go
- internal/plugins/helm/v1/scaffolds/internal/templates/makefile.go
- testdata/ansible/memcached-operator/Makefile
- testdata/helm/memcached-operator/Makefile
Signed-off-by: Camila Macedo <cmacedo@redhat.com>
add makefile helper for ansible/helm
provide for ansible/helm the same nice features that we have for Go
Closes: https://github.com/operator-framework/operator-sdk/issues/4628
**Checklist**
> ansible/helm: add makefile helper

- changelog/fragments/make-catalog-build.yaml
- internal/plugins/manifests/init.go
- testdata/ansible/memcached-operator/Makefile
- testdata/go/v2/memcached-operator/Makefile
- testdata/go/v3/memcached-operator/Makefile
- testdata/helm/memcached-operator/Makefile
- internal/plugins/manifests: use docker in `catalog-build` target to align with others
**Motivation for the change:** all other make targets use `docker` for building/pushing but `opm index add` defaults to non-docker builders/pullers. A nice side effect of making the build/pull tool explicit is that it makes this choice obvious for those who want to change it.
**Checklist**
> (manifests/v2) use docker in 'catalog-build' target to align with others

- website/content/en/docs/building-operators/golang/references/event-filtering.md
The documentation for the event filtering was using `MetaOld` and `MetaNew`
for filtering update events. In the latest version of the event package
this should be `ObjectOld` and `ObjectNew`.
Ref: https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/event#UpdateEvent
Fix the documentation.
**Checklist**
> Fix typo in the event filtering docs

- website/content/en/docs/overview/cheat-sheet.md
add doc with sdk cheat sheet.
Closes: https://github.com/operator-framework/operator-sdk/issues/4658
**Checklist**
> doc: add sdk cheat-sheet

- changelog/fragments/kubebuilder-646f742.yaml
- go.mod
- go.sum
- internal/cmd/operator-sdk/generate/kustomize/manifests.go
- internal/plugins/ansible/v1/init.go
- internal/plugins/ansible/v1/scaffolds/internal/templates/config/prometheus/monitor.go
- internal/plugins/helm/v1/init.go
- internal/plugins/helm/v1/scaffolds/internal/templates/config/prometheus/monitor.go
- internal/plugins/manifests/init.go
- internal/testutils/olm.go
- internal/util/projutil/project_util.go
- testdata/ansible/memcached-operator/PROJECT
- testdata/ansible/memcached-operator/bundle/manifests/memcached-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
- testdata/ansible/memcached-operator/config/prometheus/monitor.yaml
- testdata/go/v2/memcached-operator/PROJECT
- testdata/go/v2/memcached-operator/bundle/manifests/memcached-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
- testdata/go/v2/memcached-operator/config/prometheus/monitor.yaml
- testdata/go/v3/memcached-operator/PROJECT
- testdata/go/v3/memcached-operator/bundle/manifests/memcached-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
- testdata/go/v3/memcached-operator/config/prometheus/monitor.yaml
- testdata/helm/memcached-operator/PROJECT
- testdata/helm/memcached-operator/bundle/manifests/memcached-operator-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
- testdata/helm/memcached-operator/config/prometheus/monitor.yaml
**Description of the change:** bump kubebuilder to https://github.com/kubernetes-sigs/kubebuilder/commit/646f742d9407f253aff90b7f6930a0aea94cffeb, and make plugin API changes.
**Motivation for the change:** dep bump, and has a change needed by #4670.
**Checklist**
> deps: bump kubebuilder to 646f742

- changelog/fragments/helm-handle-list-kind.yaml
- internal/helm/controller/controller.go
The Kubernetes `kind: List` is not actually a resource and therefore cannot have a watch set on it. This PR iterates on the `List` items instead and sets the watch on those Kubernetes kinds. 
Helm operator controller errors out when a Helm chart has a `kind: List` declared.
Closes #4636 
**Checklist**
> fix(Helm.controller.watch): Process watch for List kind

- changelog/fragments/alpha-config-gen.yaml
- internal/cmd/operator-sdk/cli/cli.go
- website/content/en/docs/cli/operator-sdk_alpha.md
- website/content/en/docs/cli/operator-sdk_alpha_config-gen.md
- website/content/en/docs/cli/operator-sdk_alpha_config-gen_install-as-plugin.md
- internal/cmd/operator-sdk/cli: un-hide `alpha config-gen`
**Motivation for the change:** users should be able to use and give feedback on alpha commands. See https://github.com/operator-framework/operator-sdk/pull/4667#discussion_r595122390 for discussion.
/kind feature
**Checklist**
> enable 'alpha config-gen' command

- website/content/en/docs/building-operators/ansible/migration.md
- website/content/en/docs/building-operators/golang/migration.md
- website/content/en/docs/building-operators/helm/migration.md
- docs/building-operators/*/migration.md: make sure these are aligned and have prerequisites
**Motivation for the change:** migration guides should all have prerequisites. Follows up on #4665.
**Checklist**
> docs/migration: add prereqs, align guides for all languages

- changelog/fragments/bugfix-csv-webhooks.yaml
- hack/generate/samples/internal/go/v2/memcached_with_webhooks.go
- hack/generate/samples/internal/go/v3/memcached_with_webhooks.go
- internal/cmd/operator-sdk/generate/kustomize/manifests.go
- internal/plugins/ansible/v1/init.go
- internal/plugins/golang/v2/init.go
- internal/plugins/golang/v3/init.go
- internal/plugins/helm/v1/init.go
- internal/plugins/manifests/v2/init.go
- internal/plugins/manifests/v2/kustomization.go
- internal/plugins/manifests/v2/plugin.go
- testdata/ansible/memcached-operator/config/manifests/kustomization.yaml
- testdata/go/v2/memcached-operator/bundle/manifests/memcached-operator.clusterserviceversion.yaml
- testdata/go/v2/memcached-operator/config/manifests/kustomization.yaml
- testdata/go/v3/memcached-operator/bundle/manifests/memcached-operator.clusterserviceversion.yaml
- testdata/go/v3/memcached-operator/config/manifests/kustomization.yaml
- testdata/helm/memcached-operator/config/manifests/kustomization.yaml
- website/content/en/docs/olm-integration/generation.md
- internal/plugins/manifests/v2: initialize project with a `config/manifests/kustomization.yaml` that contains a patch to remove the [`cert` volume and mount](https://github.com/operator-framework/operator-sdk/blob/a07364f06aa14934ce52257f3af1aaf0da587401/testdata/go/v3/memcached-operator/config/default/manager_webhook_patch.yaml) from the default manager configuration.
- internal/cmd/operator-sdk/generate/kustomize: use the manifests/v2 kustomization.yaml for backwards-compatibility.
**Motivation for the change:** no kustomize helpers are created to enable webhooks by default. This is considered a bug since the CSV generator supports webhooks (see #4244).
Closes #4240 
Closes #4244
Closes #4439 
/kind bug
**Checklist**
If the pull request includes …
> (manifests/v2) add support for webhooks by default and docs

- release/Makefile
- website/content/en/docs/installation/_index.md
- website/scripts/update_download_url.sh
- docs/installation: use version in download URL
- release/Makefile,website/scripts: include script to update download URL as a part of prerelease steps
**Motivation for the change:** following up on #4661, which addresses a broken download link for operator-sdk, I discovered that it would actually make more sense to pin the download link to a particular operator-sdk version so that older docs do not point to newer operator-sdk binaries.
This reverts part of #4034.
Closes #4661 
**Checklist**
> docs/installation: use version in download URL

- website/content/en/docs/building-operators/ansible/migration.md
- website/content/en/docs/building-operators/ansible/reference/watches.md
Properly documents the format for `reconcilePeriod` in the Ansible watches.yaml
We were missing docs and migration instructions for the new behavior of the `reconcilePeriod` parameter.
**Checklist**
> Properly document that reconcilePeriod is a time.Duration

- website/content/en/docs/best-practices/_index.md
- website/content/en/docs/best-practices/common-recommendation.md
- website/content/en/docs/contribution-guidelines/_index.md
- website/content/en/docs/faqs/_index.md
Add a doc to centralize the common recommendations and suggestions
**Motivation**
Closes: https://github.com/operator-framework/operator-sdk/issues/4674
**Preview**
https://deploy-preview-4675--operator-sdk.netlify.app/docs/best-practices/common-recommendation/
> doc: add common recommendations and suggestions

- website/content/en/docs/building-operators/ansible/migration.md
- website/content/en/docs/building-operators/golang/migration.md
- website/content/en/docs/building-operators/helm/migration.md
- website/content/en/docs/faqs/_index.md
- add faq question about kb docs usage
- link that where is required
Closes https://github.com/operator-framework/operator-sdk/issues/4526 without we need to duplicate the KB docs info and have the effort to keep both maintained. 
**Checklist**
> doc: add faq question about kb docs usage + clarifications

- internal/cmd/operator-sdk/bundle/validate/validate.go
- website/content/en/docs/cli/operator-sdk_bundle_validate.md
closes: https://github.com/operator-framework/operator-sdk/issues/4562
> allow we see the alpha option output the bundle validation in another format

- website/content/en/docs/building-operators/ansible/tutorial.md
Cleanup Ansible tutorial docs.
- use correct status for the example memcached object
- add blurb saying that you should fill out the CRD with the Spec and Status fields
- change references to kube "v1alpha1" versions to "v1" 
#4663 
#4664
> cleanup ansible tutorial docs

- changelog/fragments/pin-ansible-galaxy-collections.yaml
- internal/plugins/ansible/v1/scaffolds/internal/templates/requirements.go
- testdata/ansible/memcached-operator/requirements.yml
This PR is part of #4237 to work towards a more user-friendly way of doing reproducible local builds
This PR pins versions of Ansible collections installed through ansible-galaxy
Answers https://github.com/operator-framework/operator-sdk/issues/4237#issuecomment-770829132
**Checklist**
> Pin ansible galaxy installs

- website/content/en/docs/building-operators/ansible/development-tips.md
- docs/building/operators/ansible: use memcached in dev tips, clean up code blocks, add prerequisites
**Motivation for the change:** dev tips should match tutorial GVK and code block style. Prerequisites should be linked too.
Closes #4237 
**Checklist**
> docs: use memcached in ansible dev tips, clean up code blocks, add prerequisites

- hack/check-links.sh
- internal/olm/operator/bundle/install.go
- internal/olm/operator/bundleupgrade/upgrade.go
- internal/olm/operator/registry/index/registry_pod.go
- internal/olm/operator/registry/index/registry_pod_test.go
- internal/olm/operator/registry/index_image.go
- internal/scorecard/testpod.go
- *: pin internally used images to specific versions, add TODO(v2.0.0)'s for public images
**Motivation for the change:** all images should be pinned for reproducibility and backwards-compatibility.
**Checklist**
> *: pin internally used images to specific versions, add TODO's for others

- changelog/fragments/optional-flags-cleanup.yaml
- internal/cmd/operator-sdk/cleanup/cmd.go
- internal/olm/operator/uninstall.go
- website/content/en/docs/cli/operator-sdk_cleanup.md
- website/content/en/docs/olm-integration/testing-deployment.md
operator-sdk cleanup command has optional additional flags (`--delete-all` and `--delete-crds`) to handle deletion of CRDs. 
To preserve the current behavior, both these flags will be set to true by default. 
If a user intends to not cleanup CRDs, then the user will have to set the flags as below:
`operator-sdk cleanup <operatorPackageName> --delete-all=false --delete-crds=false` to prevent deletion of CRDs
The existing operator-sdk cleanup command currently deletes the CRDs and all other resources owned by the operator, without an option to disable this behavior. Ideally, the cleanup command should have certain flags that prevent deletion of CRDs, for feature parity with the kubectl operator plugin and also so that eventually …
> cleanup command has additional flags to handle deletion of CRDs

- changelog/fragments/run-bundle-with-secret.yaml
- go.mod
- go.sum
- internal/cmd/operator-sdk/cleanup/cmd.go
- internal/cmd/operator-sdk/run/bundle/cmd.go
- internal/cmd/operator-sdk/run/bundleupgrade/cmd.go
- internal/cmd/operator-sdk/run/packagemanifests/packagemanifests.go
- internal/olm/operator/bundle/install.go
- internal/olm/operator/bundleupgrade/upgrade.go
- internal/olm/operator/config.go
- internal/olm/operator/registry/index/registry_pod.go
- internal/olm/operator/registry/index/registry_pod_test.go
- internal/olm/operator/registry/index_image.go
- internal/olm/operator/registry/olm_resources.go
- website/content/en/docs/building-operators/ansible/quickstart.md
- website/content/en/docs/building-operators/ansible/tutorial.md
- website/content/en/docs/building-operators/golang/quickstart.md
- website/content/en/docs/building-operators/golang/tutorial.md
- website/content/en/docs/building-operators/helm/quickstart.md
- website/content/en/docs/building-operators/helm/tutorial.md
- website/content/en/docs/cli/operator-sdk_cleanup.md
- website/content/en/docs/cli/operator-sdk_run_bundle-upgrade.md
- website/content/en/docs/cli/operator-sdk_run_bundle.md
- website/content/en/docs/cli/operator-sdk_run_packagemanifests.md
- website/content/en/docs/olm-integration/quickstart-bundle.md
- website/content/en/docs/olm-integration/testing-deployment.md
- website/content/en/docs/overview/cheat-sheet.md
**Description of the change:** This PR adds `--service-account` to `run bundle` and `run bundle-upgrade` to bind registry objects to a non-default service account. It also adds `--secret-name` to `run bundle` and `run bundle-upgrade` to configure the registry Pod with an in-cluster docker config Secret to pull bundle images from private registries.
**Motivation for the change:** private registries containing bundles should be accessible by `opm` within the ephemeral registry pod. The service account can be used to configure image pull secrets for private index images.
Relates to #4650
/kind feature
**Checklist**
> `run bundle(-upgrade)`: configure service account and secret

- website/content/en/docs/installation/_index.md
Updated the `arch` command with `uname` for more accurate architecture identification. 
The `arch` command in macOS due to [legacy reasons](https://stackoverflow.com/a/12763379) reports whether the Intel arches are capable of 32-bit.
For example, in my MBP 16" (Intel):
```
$ arch
i386
$ uname -m
x86_64
```
Consequently, the snippet for downloading `operator-sdk` manually. That's why I chose `uname -m` as a replacement.
**Checklist**
PTAL
> Changed arch with uname for finding the architecture in macOS

- internal/plugins/ansible/v1/init.go
- internal/plugins/envtest/v1/init.go
- internal/plugins/envtest/v1/plugin.go
- internal/plugins/helm/v1/api.go
- internal/plugins/helm/v1/init.go
- internal/plugins/manifests/v2/api.go
- internal/plugins/manifests/v2/plugin.go
- internal/plugins/util/legacy_keys.go
- testdata/go/v2/memcached-operator/PROJECT
- internal/plugins/envtest/v1: remove plugin key, since this plugin should only be used internally as a go/v2 patch.
- internal/plugins/manifests/v2: remove resources from plugin config, and run if a legacy PROJECT configuration is found.
**Motivation for the change:** following up on comments in #4581 
**Checklist**
> internal/plugins: follow-up updates from #4581

- .github/workflows/deploy-manual.yml
- .github/workflows/deploy-manual.yml: specify ansible_operator_base_tag as input, use only HEAD commit hash as default tag
**Motivation for the change:** Now that the operator-sdk is a monorepo with multiple tags, ex. `scorecard-kuttl/vX.Y.Z`, ansible-operator-base tags containing git tag data don't make sense. Instead, a commit should be used.
**Checklist**
> actions(deploy-manual): use commit as ansible-operator-base tag

- internal/olm/operator/registry/operator_installer.go
PR #4309 does not fully fix the issue #4308 and `run packagemanifests`
randomly fails with below error:
```
Failed to run packagemanifests: error approving install plan: Operation cannot be fulfilled on installplans.operators.coreos.com \"install-jp28s\": the object has been modified; please apply your changes to the latest version and try again
```
`retry.RetryOnConflict()` uses `k8serrors.IsConflict()` to determine if
the error occurred was a conflict error. IsConflict() checks if the
'type' of the error is `StatusError`. Wrapping the error returned by the
Update() call will changed the 'type' to 'wrapError'. Hence do not wrap
the error return from Update().
FIXES #4308
**Checklist**
If the pull request includes user-facing …
> olm/operator: do not tamper error type returned by the apiserver

- changelog/fragments/urllib3-1.26.4.yaml
- images/ansible-operator/Dockerfile
- images/ansible-operator/Dockerfile: bump base image to `ansible-operator-base:b187f86157fbdc115da60d275628b3dd633e55c2`
**Motivation for the change:** [security fix](https://github.com/urllib3/urllib3/releases/tag/1.26.4)
**Checklist**
> ansible-operator: bump base image to `ansible-operator-base:b187f86157fbdc115da60d275628b3dd633e55c2`

- changelog/fragments/urllib3-1.26.4.yaml
- images/ansible-operator/base.Dockerfile
> [v1.5.x] images/ansible-operator: pin urllib3 to 1.26.4

- images/ansible-operator/Dockerfile
-  images/ansible-operator/Dockerfile: bump base image to `ansible-operator-base:v1.5.0-2-g052de7c858de99f224d26b80959c0cc6805e53a3`
**Motivation for the change:** see #4723
**Checklist**
> [v1.5.x] ansible-operator: bump base image to `ansible-operator-base:v1.5.0-2-g052de7c858de99f224d26b80959c0cc6805e53a3`

- changelog/fragments/add-plugins.yaml
- internal/cmd/operator-sdk/cli/cli.go
- website/content/en/docs/cli/operator-sdk.md
Add kustomize plugin
**Motivation**
Allow using the SDK tool to only scaffold the default common base. 
**Checklist**
> feat: add kustomize plugin

- changelog/fragments/ansible-dep-bump.yaml
- images/ansible-operator/Pipfile
- images/ansible-operator/Pipfile.lock
- internal/plugins/ansible/v1/scaffolds/internal/templates/requirements.go
- testdata/ansible/memcached-operator/requirements.yml
Bring python and Ansible dependencies up to date
Lots of work going on in the kubernetes and operator_sdk collection, want to make sure we keep up with those dependencies.
**Checklist**
> Ansible bump deps

- changelog/fragments/ca-secret-name-run-bundle.yaml
- changelog/fragments/run-bundle-with-secret.yaml
- internal/olm/operator/registry/index/registry_pod.go
- internal/olm/operator/registry/index/registry_pod_test.go
- internal/olm/operator/registry/index_image.go
- website/content/en/docs/building-operators/ansible/migration.md
- website/content/en/docs/building-operators/ansible/quickstart.md
- website/content/en/docs/building-operators/ansible/tutorial.md
- website/content/en/docs/building-operators/golang/migration.md
- website/content/en/docs/building-operators/golang/quickstart.md
- website/content/en/docs/building-operators/golang/tutorial.md
- website/content/en/docs/building-operators/helm/migration.md
- website/content/en/docs/building-operators/helm/quickstart.md
- website/content/en/docs/building-operators/helm/tutorial.md
- website/content/en/docs/cli/operator-sdk_run_bundle-upgrade.md
- website/content/en/docs/cli/operator-sdk_run_bundle.md
- website/content/en/docs/olm-integration/cli-overview.md
- website/content/en/docs/olm-integration/quickstart-bundle.md
- website/content/en/docs/olm-integration/testing-deployment.md
- website/content/en/docs/overview/cheat-sheet.md
- internal/olm/operator/registry: add `--ca-secret-name` to accept the name of a secret containing a root certificate file.
**Motivation for the change:** This PR adds `--ca-secret-name` so users attempting to run bundles hosted by a registry using a custom CA can configure the registry Pod's `opm registry add` command with the root cert file.
Closes #4650 
/kind feature
**Checklist**
> `run bundle(-upgrade)`: configure registry pod with root certificate secret

- go.mod
- go.sum
**Description of the change:** bump kubebuilder to https://github.com/kubernetes-sigs/kubebuilder/commit/c7525d74815300c4d5b8c6e6fa6cf4cd80a9dbd2
**Motivation for the change:** fix regressions
Closes #4716
**Checklist**
> deps: bump kubebuilder to c7525d74815300c4d5b8c6e6fa6cf4cd80a9dbd2

- go.mod
- go.sum
- internal/cmd/operator-sdk/generate/kustomize/manifests.go
- internal/generate/internal/genutil.go
bump github.com/operator-framework/api from 0.5.3 to 0.8.0
More info: https://github.com/operator-framework/api/compare/v0.5.3...v0.8.0
**Motivation**
- Solve tech debts
- Unblock https://github.com/operator-framework/operator-sdk/pull/4693
> bump github.com/operator-framework/api from 0.5.3 to 0.8.0

- .github/workflows/deploy-manual.yml
- .github/workflows/deploy-manual.yml: patch ansible-operator Dockerfile with new base image tag and create a PR on successful base image build
**Motivation for the change:** automates a step that needs doing on each ansible-operator-base image build.
**Checklist**
> workflows/deploy-manual: automate ansible-operator base image bump PR creation

- website/content/en/docs/contribution-guidelines/plugins.md
- website/content/en/docs/contribution-guidelines/releasing.md
- website/content/en/docs/contribution-guidelines/reporting-issues.md
- website/content/en/docs/contribution-guidelines/testing.md
Add doc which describes how the SDK plugins work and provide the required info for who would like to create your own plugins following the same standards as for its maintainers. 
Preview: https://deploy-preview-4732--operator-sdk.netlify.app/docs/contribution-guidelines/plugins/
> doc: add plugins contribution doc

- changelog/fragments/change-scImagePolicy.yaml
- internal/scorecard/testdata/pod.yaml
Signed-off-by: Ish Shah <ishah@redhat.com>
Change default Image Pull Policy in scorecard.
**Checklist**
> Change default Image Pull Policy for Scorecard

- website/content/en/docs/upgrading-sdk-version/version-upgrade-guide.md
The v1.16.2 k8s tag was missing a trailing code bracket, which resulted in it rendering incorrectly in the migration guide.
Going through the migration guide to upgrading the marketplace operator to a suitable operator-sdk version.
**Checklist**
> website/content: Add trailing code bracket to the sdk v0.13.x migration guide

- changelog/fragments/add-componentconfig-flag.yaml
- internal/ansible/flags/flag.go
- internal/ansible/flags/flag_test.go
- internal/ansible/flags/suite_test.go
- internal/cmd/ansible-operator/run/cmd.go
- internal/cmd/helm-operator/run/cmd.go
- internal/helm/flags/flag.go
- internal/helm/flags/flag_test.go
- internal/helm/flags/suite_test.go
- internal/plugins/ansible/v1/init.go
- internal/plugins/helm/v1/init.go
- internal/{ansible,helm}: add --config flag, and configure flags to be applied on top of manager Options
- internal/cmd/{ansible,helm}: apply config file data prior to flag data
**Motivation for the change:** This PR fixes manager component configuration for ansible-operator and helm-operator by adding the underlying reading and Manager option updating functionality. This was missing when the config file was originally added to both ansible/v1 and helm/v1 plugins. --config accepts a path to this config file.
/kind bug
**Checklist**
> `{ansible,helm}-operator run`: add component config flag `--config`

- .github/dependabot.yml
This configures Dependabot (Github feature) to automatically create PRs whenever a newer base image is available.
This simplifies the process of switching to a new base image after security patches are released.
Relates to #4763
> deps: enable Dependabot to upgrade base images

- website/content/en/docs/contribution-guidelines/documentation.md
- website/content/en/docs/upgrading-sdk-version/version-upgrade-guide.md
Update the migration guide for the v0.2.x to v0.17.x versions and prefix
any of the **revision for tag "kubernetes-1.*.*"** with a comment so
it's easier to copy-and-paste when working with operator-sdk based
projects that haven't migrated from dep to go modules yet.
**Checklist**
> website/content: Update migration guide to allow copy-pasting Gopkg.toml updates

- hack/generate/samples/generate_testdata.go
- hack/generate/samples/internal/ansible/advanced_molecule.go
- hack/generate/samples/internal/ansible/generate.go
- hack/generate/samples/internal/ansible/memcached.go
- hack/generate/samples/internal/ansible/memcached_molecule.go
- hack/generate/samples/internal/go/generate.go
- hack/generate/samples/internal/go/v2/memcached_with_webhooks.go
- hack/generate/samples/internal/go/v3/memcached_with_webhooks.go
- hack/generate/samples/internal/helm/generate.go
- hack/generate/samples/internal/helm/memcached.go
- hack/generate/samples/molecule/generate.go
- hack/generate/samples: clean up samples code by renaming stuff, making sure binary path flag works, and moving exported constructors to the tops of files.
**Motivation for the change:** general cleanup of internal samples generator code.
**Checklist**
> hack/generate/samples: clean up samples code

- internal/cmd/operator-sdk/generate/bundle/bundle.go
Sorting the OtherLabels in bundle command.
OtherLabels stem from a map and will have random order between
executions causing the generated bundle Dockerfile to potentially
result in a dirty git state.
> fix: ensure labels are ordered in generated bundle

- hack/check-links.sh
- hack/check-links.sh: pin klakegg/html-proofer image to 3.18.8 to fix dep issue
**Motivation for the change:** latest image is broken
**Checklist**
> [v1.5.x] hack/check-links.sh: pin klakegg/html-proofer image to 3.18.8 to fix dep issue

- release/Makefile
- release/Makefile: bump goreleaser to 0.156.0
**Motivation for the change:** necessary to use go1.16 (eventually)
Closes #4773 
**Checklist**
> release: bump goreleaser to 0.156.0

- website/content/en/docs/best-practices/best-practices.md
- website/content/en/docs/best-practices/common-recommendation.md
Add the content from [community-operators](https://github.com/operator-framework/community-operators/blob/master/docs/best-practices.md) to SDK docs. Note that this comment will be removed from there and we will link the SDK docs instead of. 
See the preview : https://deploy-preview-4717--operator-sdk.netlify.app/docs/best-practices/best-practices/
**Motivation**
Centralize here the docs as requested by @dmesser
> doc: add operator best practices

- images/ansible-operator/Dockerfile
- images/ansible-operator: bumped base to ansible-operator-base:v1.6.x-ce34186d53201446db17dc8c3498f035130498d8
**Motivation for the change:** see #4797
**Checklist**
> [v1.6.x]  images/ansible-operator: bumped base to ansible-operator-base:v1.6.x-ce34186d53201446db17dc8c3498f035130498d8

- images/ansible-operator/Dockerfile
- images/ansible-operator: bumped base to ansible-operator-base:v1.5.x-61a9e03de149f6b9d3c7f192e1f303ce97a42420
**Motivation for the change:** see #4799 
**Checklist**
> [v1.5.x]  images/ansible-operator: bumped base to ansible-operator-base:v1.5.x-61a9e03de149f6b9d3c7f192e1f303ce97a42420

- changelog/fragments/new-option-validate.yaml
- go.mod
- go.sum
- internal/cmd/operator-sdk/bundle/validate/optional.go
- internal/cmd/operator-sdk/bundle/validate/optional_test.go
- internal/cmd/operator-sdk/bundle/validate/validate.go
- website/content/en/docs/cli/operator-sdk_bundle_validate.md
- website/content/en/docs/olm-integration/generation.md
- Add a new optional flag to pass optional values to the validators.  For more info see the EP: https://github.com/operator-framework/enhancements/blob/master/enhancements/operator-hub-check.md
Allow SDK to use the new checks added for OperatorHub.io
**NOTE** This PR is using my fork. We need to get merged first: https://github.com/operator-framework/api/pull/103 and follow-up: https://github.com/operator-framework/api/pull/111
**Checklist**
> add new optional for bundle validate

- internal/cmd/operator-sdk/generate/bundle/bundle.go
- internal/cmd/operator-sdk/generate/packagemanifests/packagemanifests.go
- internal/cmd/operator-sdk/generate: print 'without an existing base' only if no base was provided
**Motivation for the change:** message was printed even when a base was provided.
**Checklist**
> internal/cmd/operator-sdk/generate: print warning correctly

- .github/workflows/deploy-manual.yml
- workflows/deploy-manual: set branch suffix to valid enum
**Motivation for the change:** apparently `branch-suffix` is an enum not an arbitrary string, whoops.
**Checklist**
> workflows/deploy-manual: set branch suffix to valid enum

- changelog/fragments/ansible_log_events.yaml
- go.mod
- internal/ansible/controller/controller.go
- internal/ansible/handler/handler_suite_test.go
- internal/ansible/handler/logging_enqueue_annotation.go
- internal/ansible/handler/logging_enqueue_annotation_test.go
- internal/ansible/handler/logging_enqueue_object.go
- internal/ansible/handler/logging_enqueue_object_test.go
- internal/ansible/handler/logging_enqueue_owner.go
- internal/ansible/handler/logging_enqueue_owner_test.go
- internal/ansible/proxy/proxy.go
Adds event handlers that emit a log signaling what events are coming in and what primary resource it will map to.
This is currently just for the ansible-operator specifically, it may be that these changes are better suited to `operator-lib` or `controller-runtime`, but I wanted people to be able to work with a basic implementation before I started working on a more complete solution.
For Ansible-based Operators specifically, we've frequently had issues with infinite reconciliation loops caused by controllers wrestling over a resource, but what resource is causing the issue is completely opaque to the user. This should make debugging those kinds of issues significantly easier.
Fixes #3945
**Checklist**
If the pull request …
> Add logs that allow users to see what events the controller is receiving

- internal/testutils/utils.go
- test/e2e/ansible/suite_test.go
- test/e2e/go/suite_test.go
- test/e2e/helm/suite_test.go
- test/integration/packagemanifests_test.go
- test/integration/suite_test.go
**Description of the change:** bump OLM version tested, remove code.
**Motivation for the change:** This PR bumps the tested OLM version to 0.18.0 and removes integration test code necessary for project to work with prior OLM versions following #4832
/area testing
**Checklist**
> test/integration: bump tested OLM version to 0.18.0, remove old test code

- changelog/fragments/fmt-info-logs.yaml
- internal/cmd/ansible-operator/run/cmd.go
- internal/cmd/helm-operator/run/cmd.go
- internal/cmd: format log.Info messages correctly
**Motivation for the change:** panic caused by odd number of keys
/kind bug 
Closes #4841 
**Checklist**
> internal/cmd: format log.Info messages correctly

- changelog/fragments/skip-adding-deprecard-crds.yaml
- internal/generate/clusterserviceversion/clusterserviceversion_updaters_test.go
- internal/util/k8sutil/api.go
Currently CSV generator adds the unserved crd versions
to the `ownedCRD` section of CSV. This PR fixes the same.
Closes: #4722 
**Checklist**
> fix: skip adding unserved CRDs to CSV

- test/integration/packagemanifests_test.go
- test/integration/suite_test.go
- test/integration: avoid OLM cache inconsistency by updating InstallModes in BeforeSuite()
**Motivation for the change:** flaky test caused by OLM package caching in newer versions.
/area testing
**Checklist**
> test/integration: fix flaky test

- changelog/fragments/ansible-fix-cluster-annotations.yaml
- hack/generate/samples/internal/ansible/advanced_molecule.go
- hack/generate/samples/internal/ansible/testdata/tasks/clusterannotationtest_test.yml
- hack/generate/samples/internal/ansible/testdata/watches.yaml
- internal/ansible/proxy/inject_owner.go
Dependent object creation passing through the proxy failed to add an
owner annotation, causing the objects not to be watched.
Closes https://github.com/operator-framework/operator-sdk/issues/4647
**Checklist**
> Fix bug in cluster scoped ansible operators

- website/content/en/docs/building-operators/golang/tutorial.md
Fix link for brace markers in tutorial.
Closes: #4847 
**Checklist**
> fix: link to rbac markers in doc

- changelog/fragments/run-bundle-from-insecure-registry.yaml
- internal/cmd/operator-sdk/scorecard/cmd.go
- internal/olm/operator/bundle/install.go
- internal/olm/operator/bundleupgrade/upgrade.go
- internal/olm/operator/helpers.go
- internal/olm/operator/registry/index/registry_pod.go
- internal/olm/operator/registry/index/registry_pod_test.go
- internal/olm/operator/registry/index_image.go
- internal/registry/image.go
- website/content/en/docs/cli/operator-sdk_run_bundle-upgrade.md
- website/content/en/docs/cli/operator-sdk_run_bundle.md
Supporting insecure registry is useful for testing operator installation
from a bundle image stored at the local registry.
Closes #4815
Add a new boolean command-line option(defaults to false) named `--allow-insecure` for both `operator-sdk run bundle` and `operator-sdk run bundle-upgrade`. When enabled this argument the commands ignores the SSL errors that occurred while communicating the docker registry. This allows pulling the bundle images from insecure(usually local) docker registries.
Using a local insecure registry is a possible case for storing the generated bundle image, and test the operator installation.
**Checklist**
> operator-sdk: run bundle{-upgrade} support insecure registry server

- changelog/fragments/pip3-21.1.yaml
- images/ansible-operator/base.Dockerfile
- images/ansible-operator/base.Dockerfile: pin pip3~=21.1
**Motivation for the change:** fix unicode split vuln that `pipenv check` complains about
**Checklist**
> images/ansible-operator/base.Dockerfile: pin `pip3~=21.1`

- .github/workflows/deploy-manual.yml
**Description of the change:** signoff on automatic PR commits
**Motivation for the change:** DCO is not happy with automatically created PRs without sigoffs on commits
**Checklist**
> workflows/deploy-manual: add commit signoff to automatically created PRs

- changelog/fragments/operator-lib-v0.4.1.yaml
- go.mod
- go.sum
**Description of the change:** bump operator-lib
**Motivation for the change:** bugfixes to ansible-operator and helm-operator
**Checklist**
> deps: bump operator-lib to v0.4.1

- images/ansible-operator/Dockerfile
New ansible-operator-base image built by https://github.com/operator-framework/operator-sdk/actions/runs/814389245
>  [v1.6.x] image(ansible-operator): bump base to quay.io/operator-framework/ansible-operator-base:v1.6.x-891ff1b580520bec52b5ecda1ab837a89b583b64

- changelog/fragments/api-v0.8.1.yaml
- go.mod
- go.sum
**Description of the change:** bump api to v0.8.1
**Motivation for the change:** see https://github.com/operator-framework/api/pull/118
**Checklist**
> deps: bump operator-framework/api to v0.8.1

- internal/olm/installer/manager.go
Return actual error returned by olm client
Error installing OLM resulted in `nil` error:
```
Failed to install OLM version "latest": failed to create manager client: <nil>
```
**Checklist**
> Return actual olm client error

- website/content/en/docs/advanced-topics/scorecard/custom-tests.md
The path for the custom test configuration file should be located in the patches directory as indicated later in the patchesJson6902.
**Checklist**
> docs: fix scorecard patches path.

- go.mod
- go.sum
- testdata/go/v3/memcached-operator/config/crd/patches/webhook_in_memcacheds.yaml
This PR bumps kb to the latest commit which has a patch to scaffold
default conversion review versions in the crd.
This is required for #4346 
**Checklist**
> bump kb to latest commit (53b7bf2fc477)

- internal/cmd/operator-sdk/generate/internal/genutil.go
- internal/cmd/operator-sdk/generate/packagemanifests/packagemanifests_test.go
Fix tthe error message when generating a bundle. It should mention `--package` instead of `--package-name` since `--package-name` is not a valid parameter.
> generate: correct error message when package name is missing

- .github/workflows/deploy-manual.yml
- .github/workflows/freshen-images.yml
- .github/workflows/freshen-images/build.sh
- .github/workflows/freshen-images/lib.sh
- .github/workflows/freshen-images/tags.sh
- changelog/fragments/freshen-images.yaml
- images/ansible-operator/base.Dockerfile
- images/custom-scorecard-tests/Dockerfile
- images/helm-operator/Dockerfile
- images/operator-sdk/Dockerfile
- images/scorecard-test/Dockerfile
- images/: remove patch info from base images in Dockerfiles, add git_commit label to ansible-operator-base for getting git info in freshen-images job.
- .github/workflows: add freshen-images job and scripts, and update ansible-operator-base build with GIT_COMMIT build arg
**Motivation for the change:** This PR adds the freshen-images workflow, which checks for newer base images used by any Dockerfile in images/ and rebuilds them if found. These Dockerfiles now specify patch-less base image tags so newer base images can be pulled if they exist.
**Checklist**
> workflows: add freshen-images cronjob to rebuild tagged images

- internal/generate/clusterserviceversion/clusterserviceversion_test.go
- internal/generate/clusterserviceversion/clusterserviceversion_updaters.go
- internal/generate/clusterserviceversion/clusterserviceversion_updaters_test.go
- internal/generate/testdata/clusterserviceversions/bases/memcached-operator-multiVersion.yaml
- internal/generate/testdata/clusterserviceversions/output/memcached-operator-multiVersion.yaml
- internal/generate/testdata/clusterserviceversions/output/memcached-operator.clusterserviceversion.yaml
- internal/generate/testdata/clusterserviceversions/output/with-ui-metadata.clusterserviceversion.yaml
- internal/generate/testdata/go/static/basic.multiversion.operator.yaml
- internal/generate/testdata/go/static/basic.operator.yaml
This PR adds support to scaffold conversion webhook in CSV,
when CRDs include conversion webhookClientConfig.
Follow-up from: #3762 
Co-authored-by: Eric Stroczynski <ericstroczynski@gmail.com>
Support conversion webhook scaffold in SDK
**Checklist**
> Add conversion webhook support

- go.mod
- go.sum
Bump the java plugin so that it picks up the recent `Makefile` changes.
The java plugin now has a `Makefile` which we'd like to include in the first release of the plugin with the SDK.
**Checklist**
> bump java plugins

- go.mod
- go.sum
Pickup stutter fix from java-plugin.
`operator-sdk init --plugins quarkus ... --project-name memcached-quarkus-operator` would result in incorrectly generated operator main file. The filename would be `MemcachedQuarkusOperator.java` but the class inside would be `MemcachedQuarkusOperatorOperator`. This scenario is invalid in Java as the file needs to match the class. 
**Checklist**
> Bump java plugin to pickup stutter fix.

- changelog/fragments/helm-randalphanum.yaml
- internal/helm/release/manager.go
- internal/helm/release/manager_test.go
- internal/helm/release/testdata/simple/.helmignore
- internal/helm/release/testdata/simple/Chart.yaml
- internal/helm/release/testdata/simple/templates/NOTES.txt
- internal/helm/release/testdata/simple/templates/_helpers.tpl
- internal/helm/release/testdata/simple/templates/secrets.yaml
- internal/helm/release/testdata/simple/values.yaml
- internal/helm/release/testdata/simpledf/.helmignore
- internal/helm/release/testdata/simpledf/Chart.yaml
- internal/helm/release/testdata/simpledf/templates/NOTES.txt
- internal/helm/release/testdata/simpledf/templates/_helpers.tpl
- internal/helm/release/testdata/simpledf/templates/secrets.yaml
- internal/helm/release/testdata/simpledf/values.yaml
Signed-off-by: cndoit18 <cndoit18@outlook.com>
Fix when using the randAlphaNum in Helm, the chart release is constantly upgraded
fixes: #4936 
**Checklist**
> fix(helm): properly compare existing and candidate releases

- changelog/fragments/community-validator.yaml
- go.mod
- go.sum
- internal/cmd/operator-sdk/bundle/validate/cmd.go
- internal/cmd/operator-sdk/bundle/validate/optional.go
- website/content/en/docs/cli/operator-sdk_bundle_validate.md
- website/content/en/docs/olm-integration/generation.md
Add a new community-validator which implemented in the API (https://github.com/operator-framework/api/pull/120)
**Checklist**
**Note**
- https://github.com/operator-framework/olm-docs/pull/155
-
> add: new community validator to check bundles

- changelog/fragments/extra-service-accounts.yaml
- internal/cmd/operator-sdk/generate/bundle/bundle.go
- internal/cmd/operator-sdk/generate/bundle/cmd.go
- internal/cmd/operator-sdk/generate/internal/manifests.go
- internal/cmd/operator-sdk/generate/internal/manifests_test.go
- internal/cmd/operator-sdk/generate/packagemanifests/packagemanifests.go
- internal/generate/clusterserviceversion/clusterserviceversion.go
- internal/generate/clusterserviceversion/clusterserviceversion_updaters.go
- internal/generate/clusterserviceversion/clusterserviceversion_updaters_test.go
- internal/generate/collector/clusterserviceversion.go
- internal/generate/collector/clusterserviceversion_test.go
- website/content/en/docs/cli/operator-sdk_generate_bundle.md
- generate bundle: add --extra-service-accounts flag to consider extra-Deployment SAsFeature/extra service accounts
- generate bundle: include both Roles and ClusterRoles in `.spec.permissions`, if ClusterRoles are bound by RoleBindings
**Motivation for the change:** see https://github.com/operator-framework/operator-sdk/issues/4751#issuecomment-821574461
/kind feature
Closes #4751 
**Checklist**
Signed-off-by: Eric Stroczynski <ericstroczynski@gmail.com>Signed-off-by: Eric Stroczynski <ericstroczynski@gmail.com>
> generate bundle: add --extra-service-accounts flag to consider extra-Deployment SAs

- website/content/en/docs/contribution-guidelines/releasing.md
- release.md: add branch names to tag
**Motivation for the change:** clarify which branch gets tagged during release.
**Checklist**
> docs(release): add branch information so the correct commit is tagged

- website/content/en/docs/olm-integration/testing-deployment.md
Update documentation for `run bundle-upgrade` to clarify assumptions of the command.
**Checklist**
Signed-off-by: rashmigottipati <chowdary.grashmi@gmail.com>
> Doc update for `run bundle-upgrade`

- changelog/fragments/empty-patch-requests.yaml
- internal/helm/release/manager.go
- internal/helm/release/manager_test.go
This change is in the helm operator when generating patch requests during each reconcile cycle.  The change filters out empty patches generated from the 3-way merge, which could be in the form of the "{}" byte array that represents an empty map.  This byte array is neither nil or zero-length, so the release reconciler sees it as non-empty and sends out a patch request to the kube apiserver.
This addresses https://github.com/operator-framework/operator-sdk/issues/4956.
We have a deployment scenario with hundreds of helm operators, each generating ~60 empty patch requests even there are no changes.  That caused heavy traffic onto the kube apiserver.
**Testing done:**
- Built the operator with this change and confirmed no more …
> fix(helm-operator): do not send empty patch requests to kube apiserver

- internal/cmd/operator-sdk/pkgmantobundle/cmd.go
- internal/cmd/operator-sdk/pkgmantobundle/pkgmantobundle_test.go
- internal/util/bundleutil/bundleutil.go
- website/content/en/docs/cli/operator-sdk_pkgman-to-bundle.md
- website/content/en/docs/olm-integration/quickstart-package-manifests.md
The custom build command in pkgman-to-bundle accepts the input and
executes it using [`exec.Command()`](https://github.com/operator-framework/operator-sdk/blob/d3bd87c6900f70b7df618340e1d63329c7cd651e/internal/util/bundleutil/bundleutil.go#L203). However, `exec.Command()` requires that the
first argument is the name or path of the command. This change separates
the user input and considers first argument as the path and then appends the rest of the args to execute the command in all the sub directories. 
Example:
```
/Users/vnarsing/go/bin/operator-sdk pkgman-to-bundle packagemanifests --image-tag-base quay.io/example/memcached --build-cmd "docker build -f bundle.Dockerfile . -t"
INFO[0001] Packagemanifests will be migrated to bundles in bundles directory
INFO[0001] Creating …
```
> fix: build-cmd arg in pkgman-to-bundle

- website/content/en/docs/building-operators/golang/tutorial.md
Fix the link to memcached_controller.go to point to master.
Fixes: #4966
**Checklist**
> fix: link to memcached_controller.go

- internal/ansible/events/log_events.go
Printed log events to stdout, based on verbosity set in CR.
To no longer ignore the verbosity at stdout while running Ansible-based operators, as mentioned in #4446.
> Closes #4446: Logging to Stdout based on verbosity

- website/content/en/docs/building-operators/golang/references/client.md
Update the client.md documentation and change the function signature
documented from client.UpdateOption to client.PatchOption for the patch
method header.
**Checklist**
> website/context: Fix the Patch function signature in the Go client documentation

- website/content/en/docs/building-operators/helm/tutorial.md
[Tutorial for building helm-based operator](https://sdk.operatorframework.io/docs/building-operators/helm/tutorial/) has instructions to build a Nginx operator bundle. However, when running the `operator-sdk run bundle` command, it shows the `memcached-operator-bundle` instead of `nginx-operator-bundle`.
Incorrect documentation
**Checklist**
> update image name in "operator-sdk run bundle" cmd

- internal/plugins/helm/v1/init.go
The comment is in the helm plugin but only mentions ansible which
is confusing. I used the helm/ansible term to be consistent
with the rest of the comments in the file.
Signed-off-by: Brad Topol <btopol@us.ibm.com>
**Checklist**
> Update comment to mention that webhooks are not supported by helm

- changelog/fragments/generate-bundle-fix.yaml
- internal/util/bundleutil/bundleutil.go
Specify the right path of metadata in bundle.Dockerfile when `output-dir` is specified.
closes #5021 
**Checklist**
> fix: specify the right path of metadata in bundle.Dockerfile

- changelog/fragments/java-operator-bump.yaml
- go.mod
- go.sum
Bumping java-operator-plugins
To pick up fixes from the operator-plugins repo.
**Checklist**
> Bump java-operator-plugins.

- changelog/fragments/helm-deepequals.yaml
- internal/helm/release/manager.go
- internal/helm/release/manager_test.go
Signed-off-by: cndoit18 <cndoit18@outlook.com>
fix #5041 
**Checklist**
> fix: issue-5041

- website/content/en/docs/olm-integration/testing-deployment.md
Add markdown reference link for image registry config page in olm-integration/testing-deployment docs page.
The reference link is based on the link in golang/quickstart page https://github.com/operator-framework/operator-sdk/blob/f298f7c92ee154a0e8123fb13398a7f21720cf0e/website/content/en/docs/building-operators/golang/quickstart.md#L59 .
Broken markdown link.
**Checklist**
> docs/olm-integration: Add image registry config reference link

- internal/cmd/operator-sdk/alpha/config3alphato3/convert_config_3-alpha_to_3.go
- internal/cmd/operator-sdk/alpha/config3alphato3/convert_config_3-alpha_to_3_test.go
Update `convertConfig3AlphaTo3()` to use an empty string as a domain name
when the read config has no domain information.
Check the existence of "domain" field in the config before attempting a
type assertion. This helps avoid panic:
```
panic: interface conversion: interface {} is nil, not string
```
I've an old project which was created with `3-alpha` PROJECT version a few months ago. It is based on an old operator-sdk project, before operator-sdk started using kubebuilder for project scaffold. The project's api version is of the format `group/v1`. All the new projects based on kubebuilder seem to use a domain name, resulting in the api version of the format `group.domain/v1`. Setting the domain to an empty string seems to …
> config3alphato3: Default domain to empty string

- changelog/fragments/modify-default-channel.yaml
- internal/cmd/operator-sdk/pkgmantobundle/cmd.go
- internal/cmd/operator-sdk/pkgmantobundle/pkgmantobundle_test.go
Previously, the versions of manifests other than the latest version,
used to have the channel as `candidate`. This caused errors
while running the bundle. With this commit, the channels for those
manifests would be the defaultchannel specified in package.yaml.
Previous versions of pkgman bundles used to error.
**Checklist**
> Modify channels for previous versions of manifests

- changelog/fragments/modify-default-channel.yaml
- internal/cmd/operator-sdk/pkgmantobundle/cmd.go
- internal/cmd/operator-sdk/pkgmantobundle/pkgmantobundle_test.go
This is a cherry-pick of #5062 
Previously, the versions of manifests other than the latest version,
used to have channel specified as `candidate`. This caused errors
while running the bundle. With this commit, the channels for those
manifests would be the `defaultchannel` specified in package.yaml.
**Checklist**
> [1.8.x] modify default channels for previous versions of manifests

- .github/ISSUE_TEMPLATE/bug-report.md
docs: fix comment for "what did you see instead"
The original seems to have been a blind copy-paste.
**Checklist**
GH metadata change only, no additional documentation changes needed.
> docs: fix comment for "what did you see instead"

- website/content/en/docs/olm-integration/generation.md
- docs/olm-integration/generation.md: fix example Go code to get webhooks working with OLM < 0.17
**Motivation for the change:** see https://github.com/kubernetes-sigs/controller-runtime/pull/1500
**Checklist**
> docs/olm-integration: fix example Go code for OLM < 0.17

- changelog/fragments/helm-labelselector.yaml
- internal/cmd/helm-operator/run/cmd.go
- internal/helm/controller/controller.go
- internal/helm/controller/controller_test.go
- internal/helm/watches/watches.go
- website/content/en/docs/building-operators/helm/reference/watches.md
Added a predicate to filter events based on labels.
Allow Helm operators to only watch CRs with specific labels defined in `watches.yaml`, as mentioned in #4949.
> Closes #4949: Label-based filtering for Helm via predicates

- website/content/en/docs/faqs/_index.md
- website/content/en/docs/upgrading-sdk-version/v1.0.0.md
Update the v1.0.0.md migration guide and ensure the link to the envtest
documentation is correctly formatted.
**Checklist**
> docs: Fix link to the envtest documentation in the v1.0.0 migration guide

- website/content/en/docs/faqs/_index.md
In later versions of Operator SDK, the docs have been moved. Rather than
backporting the docs move as well, we can simply link to the full url
including version.
> Link to scorecard docs of version 1.8

- website/content/en/docs/faqs/_index.md
In later versions of Operator SDK, the docs have been moved. Rather than
backporting the docs move as well, we can simply link to the full url
including version.
> Versioned sc link 1 9

- website/content/en/docs/faqs/_index.md
In later versions of Operator SDK, the docs have been moved. Rather than
backporting the docs move as well, we can simply link to the full url
including version.
> Link to scorecard docs of version 1.10

- changelog/fragments/helm-overrides-template.yaml
- go.mod
- go.sum
- internal/helm/watches/watches.go
- internal/helm/watches/watches_test.go
- website/content/en/docs/building-operators/helm/reference/advanced_features/override_values.md
Support text/template expansion of helm-operator overrideValues.
In some cases, environment variables need to be parsed to be used in helm charts, especially in dependent charts that helm-operator authors have less (or zero) control over.
For example, with this change it is possible to split a fully qualified image repo:tag into separate repo and tag values to pass to helm as values:
Environment:
```sh
export MY_IMAGE="quay.io/operator-framework/helm-operator:latest"
```
Input values:
```yaml
overrideValues:
repo: '{{ ("$MY_IMAGE" | split ":")._0 }}'
tag: '{{ ("$MY_IMAGE" | split ":")._1 }}'
```
Expanded values:
```yaml
overrideValues:
repo: "quay.io/operator-framework/helm-operator"
tag: "latest"
```
/cc @madorn 
**Checklist** …
> helm-operator: support go text/template evaluation in override values

- changelog/fragments/ansible-set-local-rolespath.yaml
- internal/plugins/ansible/v1/scaffolds/internal/templates/makefile.go
- testdata/ansible/memcached-operator/Makefile
closes: https://github.com/operator-framework/operator-sdk/issues/4071
When running locally, we set the ANSIBLE_ROLES_PATH to include the local
roles path, preventing users from needing to manually setting this
environment variable for normal development.
**Checklist**
> prepend local roles path to ANSIBLE_ROLES_PATH

- changelog/fragments/bump-kb.yaml
- go.mod
- go.sum
- internal/plugins/ansible/v1/init.go
- internal/plugins/helm/v1/init.go
- testdata/ansible/memcached-operator/bundle/manifests/memcached-operator-controller-manager-metrics-service_v1_service.yaml
- testdata/ansible/memcached-operator/bundle/manifests/memcached-operator.clusterserviceversion.yaml
- testdata/ansible/memcached-operator/config/default/manager_auth_proxy_patch.yaml
- testdata/ansible/memcached-operator/config/rbac/auth_proxy_service.yaml
- testdata/go/v3/memcached-operator/Makefile
- testdata/go/v3/memcached-operator/bundle/manifests/memcached-operator-controller-manager-metrics-service_v1_service.yaml
- testdata/go/v3/memcached-operator/bundle/manifests/memcached-operator-webhook-service_v1_service.yaml
- testdata/go/v3/memcached-operator/bundle/manifests/memcached-operator.clusterserviceversion.yaml
- testdata/go/v3/memcached-operator/config/default/manager_auth_proxy_patch.yaml
- testdata/go/v3/memcached-operator/config/manager/manager.yaml
- testdata/go/v3/memcached-operator/config/rbac/auth_proxy_service.yaml
- testdata/go/v3/memcached-operator/config/webhook/service.yaml
- testdata/helm/memcached-operator/bundle/manifests/memcached-operator-controller-manager-metrics-service_v1_service.yaml
- testdata/helm/memcached-operator/bundle/manifests/memcached-operator.clusterserviceversion.yaml
- testdata/helm/memcached-operator/config/default/manager_auth_proxy_patch.yaml
- testdata/helm/memcached-operator/config/manager/manager.yaml
- testdata/helm/memcached-operator/config/rbac/auth_proxy_service.yaml
bump kubebuilder commit in Operator SDK
**Checklist**
> bump kubebuilder commit in Operator SDK

- changelog/fragments/fix-bundle-service-accounts.yaml
- internal/cmd/operator-sdk/generate/internal/manifests.go
- internal/generate/clusterserviceversion/clusterserviceversion_updaters_test.go
- internal/generate/collector/clusterserviceversion.go
- internal/generate/collector/clusterserviceversion_test.go
- testdata/ansible/memcached-operator/bundle/manifests/memcached-operator-controller-manager_v1_serviceaccount.yaml
- testdata/go/v3/memcached-operator/bundle/manifests/memcached-operator-controller-manager_v1_serviceaccount.yaml
- testdata/helm/memcached-operator/bundle/manifests/memcached-operator-controller-manager_v1_serviceaccount.yaml
> [v1.8.x] fix(generate): exclude ServiceAccounts in the CSV from generated bundle

- changelog/fragments/fix-bundle-service-accounts.yaml
- internal/cmd/operator-sdk/generate/internal/manifests.go
- internal/generate/clusterserviceversion/clusterserviceversion_updaters_test.go
- internal/generate/collector/clusterserviceversion.go
- internal/generate/collector/clusterserviceversion_test.go
- testdata/ansible/memcached-operator/bundle/manifests/memcached-operator-controller-manager_v1_serviceaccount.yaml
- testdata/go/v3/memcached-operator/bundle/manifests/memcached-operator-controller-manager_v1_serviceaccount.yaml
- testdata/helm/memcached-operator/bundle/manifests/memcached-operator-controller-manager_v1_serviceaccount.yaml
> [v1.9.x] fix(generate): exclude ServiceAccounts in the CSV from generated bundle

- changelog/fragments/bump-of-api-0.10.5.yaml
- go.mod
- go.sum
Update the vendored api ref to the latest z to pull in new validation changes
Related pr: https://github.com/operator-framework/api/pull/144
> Bump operator-framework api to 0.10.5

- test/common/scorecard.go
The scorecard storage feature has merged and now needs automated testing within our repo. Opening as a draft in order to test/sample various testing strategies.
> Add Testing for Scorecard Storage Output Feature

- website/content/en/docs/building-operators/ansible/installation.md
- Add version range for `ansible-runner` to the document
To prevent other readers from spending time debugging the failure caused by an unsupported version of ansible-runner. also mentioned in https://github.com/operator-framework/operator-sdk/issues/5043
**Checklist**
> docs: Add version range for `ansible-runner` in installation.md

- website/content/en/docs/building-operators/ansible/reference/advanced_options.md
Signed-off-by: Venkat Ramaraju <venky2063@gmail.com>
Password files for `ansible-args` need to be specified in their absolute path. Added this change to docs.
More specific.
> Ansible-Vault password docs change

- Makefile
This commit adds an additional variable in Makefile to print K8s version
in SDK binary.
**Checklist**
> Add additional variable to print k8s version

- changelog/fragments/uid-output.yaml
- internal/cmd/operator-sdk/scorecard/cmd.go
Signed-off-by: Ish Shah <ishah@redhat.com>
Include optional Unique ID in XML output, change was withheld earlier as an API update was necessary
> Add UniqueID to XML Output

- release/Makefile
Bump goreleaser to latest release.
The goreleaser install script no longer works on older versions of goreleaser because it has been updated to handle the new location of the release checksum files.
**Checklist**
> bump goreleaser to 0.177.0 to address broken goreleaser install script

- website/content/en/docs/contribution-guidelines/reporting-issues.md
Update the link to use https.
Documentation has a link to a url that has moved permanently (301).  This 301 error causes the link checker to fail. Investigated and found the new link, using that in our docs instead.
**Checklist**
> docs: fix link that moved permanently

- website/content/en/docs/faqs/_index.md
Signed-off-by: Masato Naka <masatonaka1989@gmail.com>
Fix the link to controller-runtime FAQ (`[controller-runtime_faq]` was removed in #4411 but the link wasn't updated.)
Enable to jump to the FAQ
**Checklist**
> docs: fix missing link to controller-runtime FAQ

- changelog/fragments/fix_order_of_generated_webhooks.yaml
- internal/generate/clusterserviceversion/clusterserviceversion_updaters.go
- internal/generate/testdata/clusterserviceversions/output/memcached-operator-multiVersion.yaml
- internal/generate/testdata/clusterserviceversions/output/memcached-operator.clusterserviceversion.yaml
- internal/generate/testdata/clusterserviceversions/output/with-ui-metadata.clusterserviceversion.yaml
- testdata/go/v2/memcached-operator/bundle/manifests/memcached-operator.clusterserviceversion.yaml
- testdata/go/v3/memcached-operator/bundle/manifests/memcached-operator.clusterserviceversion.yaml
Adding sort to reorder webhookDescription based on webhookType
https://issues.redhat.com/browse/OSDK-1916
#5022 
Signed-off-by: sujil02 <sujil.shah@gmail.com>
**Checklist**
> Adding sort to reorder webhookDescription based on webhookType

- changelog/fragments/01-bump-java.yaml
- go.mod
- go.sum
Bump java-operator-plugins to a specific release.
java-operator-plugins was released as v0.1.0 so we want to use that tag instead of master.
**Checklist**
> plugins: bump java-operator-plugins to v0.1.0

- changelog/fragments/default-opm-image.yaml
- internal/olm/operator/registry/index/registry_pod.go
- internal/olm/operator/registry/index/registry_pod_test.go
- internal/olm/operator/registry/index_image.go
- website/content/en/docs/cli/operator-sdk_run_bundle.md
- website/content/en/docs/olm-integration/testing-deployment.md
Signed-off-by: Joe Lanford <joe.lanford@gmail.com>
Update default base image used in `run bundle` and `run bundle-upgrade` to the multi-arch `quay.io/operator-framework/opm:latest` image.
To support non-amd64 clusters and to avoid using the latest `master` build of `opm` (which is what `quay.io/operator-framework/upstream-opm-builder:latest` points to). The `quay.io/operator-framework/opm:latest` image is the latest tagged release of `opm`
See also: https://github.com/operator-framework/operator-registry/pull/762
**Checklist**
> update default opm index image for run bundle(-upgrade)

- website/content/en/docs/faqs/_index.md
Modified faqs to fix preserveUnknownFields issue from make bundle.
preserveUnknownFields missed after **make bundle** Added script which will add **preserveUnknownFields** back to the yaml file.
**Checklist**
> Modified faqs to fix preserveUnknownFields issue from make bundle

- internal/cmd/operator-sdk/generate/kustomize/manifests.go
If the outputDir is set then the kustomization manifest generation needs to
know otherwise the defaults set a new path of config/manifests and creates
a default kustomization.yaml, which can differ from custom yaml files that
may be in use.
#5143
Signed-off-by: phantomjinx <p.g.richardson@phantomjinx.co.uk>
**Checklist**
> manifests.go: Adds outputDir to Path config of kustomization

- go.mod
- go.sum
- internal/cmd/operator-sdk/scorecard/cmd.go
This enables selecting the service account for the scorecard using the config.yaml in addition to the existing method of changing it at runtime in the CLI. 
This blocked on an API release which should occur shortly.
> Scorecard optional Config.yaml Service Account selection

- website/content/en/docs/contribution-guidelines/releasing.md
> Document ansible-operator-base image update

- website/content/en/docs/testing-operators/scorecard/kuttl-tests.md
Signed-off-by: Masato Naka <masatonaka1989@gmail.com>
Change `quay.io/operator-framework/scorecard-test-kuttl:dev` -> `quay.io/operator-framework/scorecard-test-kuttl:v2.0.0` in https://sdk.operatorframework.io/docs/testing-operators/scorecard/kuttl-tests/#configuring-kuttl-tests-in-the-scorecard-configuration
To save readers' time to investigate where is the failure coming from.
`quay.io/operator-framework/scorecard-test-kuttl:dev` doesn't work with the recent version.
The version I tested:
- operator-sdk version: `operator-sdk version: "v1.11.0", commit: "28dcd12a776d8a8ff597e1d8527b08792e7312fd", kubernetes version: "v1.20.2", go version: "go1.16.6", GOOS: "darwin", GOARCH: "amd64"`
- kubectl-kuttl version: `kubectl-kuttl …
> docs: fix scorecard-test-kuttl version in "Writing Kuttl Scorecard Tests"

- website/content/en/docs/testing-operators/scorecard/custom-tests.md
Updates the code sample in the custom scorecard test documentation replacing the `github.com/operator-framework/operator-registry/pkg/registry`  import for `apimanifests "github.com/operator-framework/api/pkg/manifests"` and  making the required fixes. Also changes the function signature to take a pointer to a bundle.
Was going through the documentation and noticed that it wasn't working. Then checked against sample code from the repo, e.g. https://github.com/operator-framework/operator-sdk/blob/master/internal/scorecard/tests/basic.go#L19
> docs: fix custom scorecard test code sample

- website/content/en/docs/testing-operators/scorecard/kuttl-tests.md
- Clarify where is the root of the `tree` command.
- Fix file paths in https://sdk.operatorframework.io/docs/testing-operators/scorecard/kuttl-tests/
`tests/kuttl` -> `bundle/tests/scorecard/kuttl`
To make it easier and clear for readers to know where to put `kuttl` files.
**Checklist**
> [docs] Fix kuttl file paths in Writing Kuttle Scorecard Tests

- changelog/fragments/msg_scorecard.yaml
- internal/scorecard/tests/basic.go
Add information to the errors raised by scorecard basic tests to allow easily identify the scenarios
**Motivation**
I check these needs when I was troubleshooting the errors faced in the tests/ci of this repo or in the CVP pipeline trying to help Operator authors. Without the error message and the cr name is very hard to identify why the scenario is failing.
> Add information to the errors raised by scorecard basic tests to allow easily identify the scenarios

- changelog/fragments/api-sa-bugfix.yaml
- go.mod
- go.sum
**Description of the change:** bump api to v0.10.7
**Motivation for the change:** bugfix (https://github.com/operator-framework/api/pull/161)
**Checklist**
> chore(deps): bump api to v0.10.7

- changelog/fragments/reformat-xml.yaml
- internal/cmd/operator-sdk/scorecard/xunit/xunit.go
This is a PR to change the XML output to support attribute tags instead of nested attributes in the result. This will allow users of existing test parsing tools to use the scorecard xml results without post run pruning.
> Add Attribute Tags to XML output

- changelog/fragments/03-scorecard-error.yaml
- internal/scorecard/tests/basic.go
Print out the failed CRD in the Suggestions.
When the basic test fails the error is just "spec is missing" but doesn't tell you where.
**Checklist**
> fix: scorecard: output the failed CR  from basic test

- Makefile
Remove exporting of KB assets during envtest setup
Remove exporting of KB assets so that those are not downloaded and
propagated to sub-shells while building kb binary.
**Checklist**
> Remove exporting of KB assets during envtest setup

- website/content/en/docs/best-practices/resource-pruning.md
add into the SDK web site docs, under Best Practices, a section on Resource Pruning to assist operator authors
regarding how to and why to implement resource pruning within their operators.
documentation for operator authors as to how to use operator-lib's prune package.
**Checklist**
> add resource pruning docs to best practices section

- website/content/en/docs/building-operators/golang/installation.md
**Description of the change:** specify go 1.16 must be used
**Motivation for the change:** `operator-sdk init --domain example.com --repo github.com/example/memcached-operator` fails with older or newer versions of go.
```bash
>> operator-sdk init --domain example.com --repo github.com/example/memcached-operator
Writing kustomize manifests for you to edit...
Writing scaffold for you to edit...
Get controller runtime:
$ go get sigs.k8s.io/controller-runtime@v0.9.2
Update dependencies:
$ go mod tidy
go mod tidy: go.mod file indicates go 1.16, but maximum supported version is 1.15
Error: failed to initialize project: unable to run post-scaffold tasks of "base.go.kubebuilder.io/v3": exit status 1
``` 
**Checklist**
If the pull request includes user-facing changes, extra …
> docs: specify go 1.16 must be used

- .github/workflows/deploy-manual.yml
This action (AFAICT) can't be tested locally or with PRs. A previous
commit mixed up 2 variable scopes.
> Fixup syntax for deploy-manual.

- website/content/en/docs/building-operators/golang/tutorial.md
Fix a typo
**Checklist**
- ~~Add a new changelog fragment in `changelog/fragments` (see [`changelog/fragments/00-template.yaml`](https://github.com/operator-framework/operator-sdk/tree/master/changelog/fragments/00-template.yaml))~~
- ~~Add or update relevant sections of the docs website in [`website/content/en/docs`](https://github.com/operator-framework/operator-sdk/tree/master/website/content/en/docs)~~
> Fix typo from the Go operation building tutorial

- internal/cmd/operator-sdk/generate/packagemanifests/cmd.go
- internal/cmd/operator-sdk/run/packagemanifests/packagemanifests.go
A spelling mistake "packagemanifes" has been fixed in two places
The spelling was incorrect
> Fix: Spelling mistake in packagemanifests deprecation message

- website/content/en/docs/olm-integration/generation.md
The link to "JSON patch" was added to remove the volume containing TLS cert data by Cert manager is broken.
Broken markdown link.
**Checklist**
> docs/olm-integration: fix broken link for cm-patch

- website/content/en/docs/building-operators/ansible/development-tips.md
Signed-off-by: Nick Piper <nick.piper@cgi.com>
**Checklist**
> Correction to example console output to match playbook

- .github/workflows/deploy-manual.yml
https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions?query=%22id%22#outputsoutput_id
> Fixup: action syntax id must start with a letter

- website/content/en/docs/building-operators/golang/references/proxy-vars.md
It was pointed out that the doc doesnt mention the import path :(
> add import to go proxy docs

- images/ansible-operator-2.11-preview/base.Dockerfile
- images/ansible-operator/base.Dockerfile
Dockerfiles based on ubi8.4 recently started failing on `RUN yum update -y` step.
I was able to replicate this outside of SDK. Locally, I created a new Dockerfile:
```
FROM registry.access.redhat.com/ubi8/ubi:8.4
RUN yum update -y
```
Error: 
```
Problem 1: cannot install the best update candidate for package python3-subscription-manager-rhsm-1.28.13-4.el8_4.x86_64
- nothing provides python3-cloud-what = 1.28.21-3.el8 needed by python3-subscription-manager-rhsm-1.28.21-3.el8.x86_64
Problem 2: cannot install the best update candidate for package subscription-manager-1.28.13-4.el8_4.x86_64
- nothing provides python3-cloud-what = 1.28.21-3.el8 needed by subscription-manager-1.28.21-3.el8.x86_64
Problem 3: package subscription-manager-1.28.13-4.el8_4.x86_64 requires …
```
> Bump ubi 8.4 to 8.5 for ansible-operator images

- Makefile
- website/content/en/docs/contribution-guidelines/releasing.md
`make generate` is now run before `make prerelease`, and the documentation is updated to match.
This is a necessary step in the release process.
**Checklist**
> Run generate before prerelease

- website/content/en/docs/olm-integration/tutorial-bundle.md
Added the caveat that ``olm status`` does not work with non-standard olm installations to the enabling-olm docs.
Short term solution for #4714, as mentioned in [this](https://github.com/operator-framework/operator-sdk/issues/4714#issuecomment-963493281) comment.
> Docs: olm status when installed via non-standard installations

- Makefile
- testdata/ansible/memcached-operator/Dockerfile
- testdata/ansible/memcached-operator/Makefile
- testdata/ansible/memcached-operator/bundle/tests/scorecard/config.yaml
- testdata/ansible/memcached-operator/config/scorecard/patches/basic.config.yaml
- testdata/ansible/memcached-operator/config/scorecard/patches/olm.config.yaml
- testdata/go/v2/memcached-operator/bundle/tests/scorecard/config.yaml
- testdata/go/v2/memcached-operator/config/scorecard/patches/basic.config.yaml
- testdata/go/v2/memcached-operator/config/scorecard/patches/olm.config.yaml
- testdata/go/v3/memcached-operator/bundle/tests/scorecard/config.yaml
- testdata/go/v3/memcached-operator/config/scorecard/patches/basic.config.yaml
- testdata/go/v3/memcached-operator/config/scorecard/patches/olm.config.yaml
- testdata/helm/memcached-operator/Dockerfile
- testdata/helm/memcached-operator/Makefile
- testdata/helm/memcached-operator/bundle/tests/scorecard/config.yaml
- testdata/helm/memcached-operator/config/scorecard/patches/basic.config.yaml
- testdata/helm/memcached-operator/config/scorecard/patches/olm.config.yaml
bumps makefile version to 1.15.0
1.15.0 is about to be released
**Checklist**
> Bump Makefile version to 1.15.0

- changelog/fragments/bump-operator-frameworkapi.yaml
- go.mod
- go.sum
Description
bump operator-frawork-api to get its latest changes and fixes (https://github.com/operator-framework/api/compare/v0.10.7...f579141ce61d8bb7c4dc7c06169bc436ac4b9703)
> bump operator-frawork-api

- changelog/fragments/deprecation.yaml
- internal/cmd/operator-sdk/bundle/validate/cmd.go
- website/content/en/docs/cli/operator-sdk_bundle_validate.md
Deprecation the Optional(stage: alpha) Community Operator bundle validation. Its checks were moved to the [external validator](https://github.com/redhat-openshift-ecosystem/ocp-olm-catalog-validator/).
We reach the consensus that this check is more vendor-like and specific and should not be shipped with SDK.
**Checklist**
> deprecation:Optional(stage: alpha) Community Operator bundle validator

- changelog/fragments/suite.yaml
- internal/cmd/operator-sdk/bundle/validate/optional.go
Add the deprecated APIs optional checker to the suite operator
**Motivation**
We can have many validators shipped and implemented.
The suite was designed to ensure that we can aggregate all checks to validate the bundle against the upstream/operator framework criteria
> feat: add the deprecated APIs optional checker to the suite operator

- changelog/fragments/good-practices.yaml
- go.mod
- go.sum
- internal/cmd/operator-sdk/bundle/validate/cmd.go
- internal/cmd/operator-sdk/bundle/validate/optional.go
- website/content/en/docs/cli/operator-sdk_bundle_validate.md
add new good practices validator (https://github.com/operator-framework/api/pull/197)
This new validator will raise warnings with nice suggestions over good practices when are able to check the nit by looking at the bundles. 
**Checklist**
> add new good practices validator

- website/content/en/docs/building-operators/ansible/reference/webhooks.md
Old link hardcodes to k8s 1.17 docs, which is no longer available https://kubernetes.io/docs/home/supported-doc-versions/
> Update k8s docs link to 1.21

- changelog/fragments/00-template.yaml
- changelog/fragments/01-upgrade-opm-version.yaml
- internal/plugins/manifests/v2/init.go
- testdata/ansible/memcached-operator/Makefile
- testdata/go/v2/memcached-operator/Makefile
- testdata/go/v3/memcached-operator/Makefile
- testdata/helm/memcached-operator/Makefile
- website/content/en/docs/upgrading-sdk-version/v1.6.0.md
- website/content/en/docs/upgrading-sdk-version/v1.6.1.md
The generated `Makefile` uses a more recent version of `opm`
On OSX, using the version `v1.15.1` of `opm` leads to the following error:
```
Error: Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work.
```
when doing a `make catalog-build`. Using the latest version of `opm` (`v1.19.1` at the time of this PR) solves the issue.
**Checklist**
> Upgrade OPM version used

- changelog/fragments/bump-sdk-util.yaml
- internal/plugins/ansible/v1/scaffolds/internal/templates/requirements.go
- testdata/ansible/memcached-operator/requirements.yml
> bump: bump operator-sdk.util to 0.3.1

- go.mod
- go.sum
Just to get the update in the msg:
More about the diffs: https://github.com/operator-framework/api/compare/6897e9ad3883..ff6b5ebe3c25
> bump of/api

- changelog/fragments/add-check-to-ensure-examples.yaml
- go.mod
- go.sum
Now operator-sdk bundle validate also ensures that the `alm-examples` annotation has a valid JSON ([More info](https://github.com/operator-framework/api/pull/207)), see:
PS: Introduction done by upgrading operator-framework/api from the commit `54878ea280f7c7402549dae568916dfb330b9262` to the release `v0.11.1`
> Now operator-sdk bundle validate also ensures that the  annotation has a valid JSON

- website/content/en/docs/faqs/_index.md
> add blurb about how to wait for a certain state to FAQ

- OWNERS_ALIASES
Per the discussion at the meeting today, here's my application for approver. I'm apparently already a maintainer on the CNCF side of things so I think(?) this is the only thing to do, as the lists in operator-framework/community don't seem like they need to change.
Also I sorted the lists because I couldn't stand them not being in alphabetical order, sorry.
@asmacdo
> jberkhahn for operator-sdk approver

- website/content/en/docs/olm-integration/quickstart-bundle.md
Update the reference link to the Go building-operators quickstart link.
Signed-off-by: timflannagan <timflannagan@gmail.com>
**Checklist**
> website: Fix typo in reference link in quickstart-bundle.md

- changelog/fragments/trim-quotes-input.yaml
- internal/util/projutil/interactive_promt_util.go
- internal/util/projutil/interactive_promt_util_test.go
Fixes #5499 
Signed-off-by: Ryo Imai <iryo@jp.ibm.com>
This PR changes the handling of interactive input string to trim quotes (double quotes, single quotes, back quotes) to fix #5499 . The functions depending on the changed function are only used for generating bundle CSV base manifests first time. So, I assume the impact by this change is limited. 
**Checklist**
> fix: trim quotes in interactive input

- changelog/fragments/01-bump-java-operator-plugins.yaml
- go.mod
- go.sum
java-operator-plugins release: https://github.com/operator-framework/java-operator-plugins/releases/tag/v0.2.0
Additions:
- chore: bump go 1.17, k8s 1.23, and kubebuilder 3.3
- chore(deps): update to Quarkus SDK extension 3.0.2 and Quarkus 2.6.3
- chore(deps): update to use Quarkus JOSDK extension 3.0.1
- Remove useless file
- chore: bump k8s 1.22.2 and kubebuilder 3.2
- exposed exnpoints for micrometer metrics
- modified the Quarkus operator SDK version and tutorial too
- chore: bump fabric8 5.8.0 & quarkus 2.4.0
- modified the doc file and removed file after generation
- release: fix release script to understand release branches
Bug Fixes:
- Fix for wrongly generated file name
**Motivation for the …
> chore: bump java-operator-plugins to v0.2.0

- go.mod
- go.sum
bump api to get the fix in the bundle size check
See: https://github.com/operator-framework/api/pull/227
PS.: Not added to changelog because this check was not shipped yet. It is part of the next release 1.18.0. See: https://github.com/operator-framework/operator-sdk/pull/5552
> bump api to get fix in the bundle size check

- website/content/en/docs/building-operators/golang/tutorial.md
Changes a link to Kubebuilder's webhook docs to point to the local docs instead.
While reading I was slightly surprised that the link sent me straight to the Kubebuilder documentation because I was aware that a local webhook page existed.
The internal webhook page provides additional context on top of the Kubebuilder documentation, but links to the Kubebuilder documentation as well.
**Checklist**
> docs: update webhook link in go tutorial

- changelog/fragments/image-digests.yaml
- internal/cmd/operator-sdk/generate/bundle/bundle.go
- internal/cmd/operator-sdk/generate/bundle/cmd.go
- internal/generate/clusterserviceversion/clusterserviceversion.go
- internal/plugins/manifests/v2/init.go
- testdata/ansible/memcached-operator/Makefile
- testdata/go/v2/memcached-operator/Makefile
- testdata/go/v3/memcached-operator/Makefile
- testdata/helm/memcached-operator/Makefile
- website/content/en/docs/cli/operator-sdk_generate_bundle.md
Adds the ability to create operators that use image digests instead of tags for operator images as well as related images. 
https://github.com/operator-framework/enhancements/blob/master/enhancements/sha-bundle-digest.md
**Checklist**
- [x ] Add a new changelog fragment in `changelog/fragments` (see [`changelog/fragments/00-template.yaml`](https://github.com/operator-framework/operator-sdk/tree/master/changelog/fragments/00-template.yaml))
> Add support for using image digests instead of tags

- go.mod
- go.sum
Closes: https://github.com/operator-framework/operator-sdk/issues/5568
Changes : https://github.com/operator-framework/api/compare/bbe9c3235aff..v0.14.0
> bump api v0.14 release

- changelog/fragments/respect-deployment-labels.yaml
- internal/generate/clusterserviceversion/clusterserviceversion_updaters.go
- internal/generate/clusterserviceversion/clusterserviceversion_updaters_test.go
- internal/generate/testdata/clusterserviceversions/output/memcached-operator-multiVersion.yaml
- internal/generate/testdata/clusterserviceversions/output/memcached-operator.clusterserviceversion.yaml
- internal/generate/testdata/clusterserviceversions/output/with-ui-metadata.clusterserviceversion.yaml
- testdata/ansible/memcached-operator/bundle/manifests/memcached-operator.clusterserviceversion.yaml
- testdata/go/v2/memcached-operator/bundle/manifests/memcached-operator.clusterserviceversion.yaml
- testdata/go/v3/memcached-operator/bundle/manifests/memcached-operator.clusterserviceversion.yaml
- testdata/helm/memcached-operator/bundle/manifests/memcached-operator.clusterserviceversion.yaml
This change adds the labels of the deployment to the ClusterServiceVersions [`DeploymentSpecs`](https://github.com/operator-framework/api/blob/8e593f1c42b91ec75bf0787a28100a5f31690898/pkg/operators/v1alpha1/clusterserviceversion_types.go#L78). So the labels defined for the deployment (and defined in its manifest) will be applied too, if the operator gets bundled and  installed via OLM.
Currently the CSV does not contain the labels of the deployment in the deployment spec, even there is a field for it ([clusterserviceversion_types.go#L71](https://github.com/operator-framework/api/blob/8e593f1c42b91ec75bf0787a28100a5f31690898/pkg/operators/v1alpha1/clusterserviceversion_types.go#L71)). 
This leads to missing labels of the …
> Respect deployment labels in the CSV

- website/content/en/docs/testing-operators/scorecard/custom-tests.md
> fix link to new kustomize docs

- hack/generate/samples/internal/ansible/constants.go
- hack/generate/samples/internal/ansible/memcached_molecule.go
Fixes #5547
Signed-off-by: Ryo Imai <iryo@jp.ibm.com>
`memcached-molecule-operator` used in e2e molecule test watches k8s core resources (`Secret`). Thus running the operator in cluster-scope causes watching all Secrets in the cluster, which causes high load of the operator and leads to resource creation timeout in the test case.
I locally verified that configuring the operator to watch own namespace workarounds the issue.
Make running e2e test on local machine, where available computational resources could be limited compared to CI environment, more stable.
**Checklist**
> chore(e2e-molecule): Watch own namespace only

- changelog/fragments/01-bump-java-operator-plugins.yaml
- go.mod
- go.sum
java-operator-plugins release: https://github.com/operator-framework/java-operator-plugins/releases/tag/v0.3.0
Bug Fixes
- Fixes issue 74 - chore: update to JOSDK extension 3.0.4 and Quarkus 2.7.3 (PR 76)
Update to latest java-operator-plugins to pickup a blocker bug fix.
**Checklist**
> chore: bump java-operator-plugins to v0.3.0

- changelog/fragments/helm-annotations-reconcile-period.yaml
- internal/cmd/helm-operator/run/cmd.go
- internal/helm/controller/reconcile.go
- internal/helm/controller/reconcile_test.go
- internal/helm/watches/watches.go
- website/content/en/docs/building-operators/helm/reference/advanced_features/reconcile-period.md
1. Added the parsing of the `helm.sdk.operatorframework.io/reconcile-period` key in the custom resource's annotations. 
2. Added the option to specify the reconcile-period through the `watches.yaml` file.
The value obtained from either of these two is set to the `RequeueAfter` field of the reconciler for Helm. If both are specified, then the CR annotations takes precedence.
Close #5565 
**Checklist**
**Note:**
As mentioned in my [comment](https://github.com/operator-framework/operator-sdk/issues/5565#issuecomment-1049421940) on the issue: this functionality already exists via a command line flag. This PR is to provide the user with the option of doing the same in the CR annotations or `watches.yaml`, which there seems to be a …
> Closes #5565: Helm reconcile period from CR annotations or watches.yaml

- website/content/en/docs/building-operators/golang/advanced-topics.md
- website/content/en/docs/building-operators/golang/crds-scope.md
- website/content/en/docs/building-operators/golang/migration.md
I noticed a few links within the Golang section had their references broken whilst browsing them.
This corrects the reference name within the CRD and Advanced Topics pages. For the migration page I've made a best-guess as to the ComponentConfig proposal that should've been linked - I'm assuming it's that design Markdown doc?
**Checklist**
> docs: fix broken reference links within the Golang section

- Makefile
Set the `K8S_VERSION` to 1.23.
Allow `K8S_VERSION` to match the actual K8S version we're using. 
**Checklist**
> fix: K8S_VERSION in Makefile

- .goreleaser.yml
- changelog/fragments/darwin-arm64.yaml
- website/content/en/docs/overview/_index.md
Signed-off-by: Joe Lanford <joe.lanford@gmail.com>
Add binary builds for `darwin/arm64`
I have a Mac M1 machine :)
**Checklist**
> add darwin-arm64 build to goreleaser config

- changelog/fragments/log-error-url-verification.yaml
- internal/cmd/ansible-operator/run/cmd.go
Simply logs the already generated error prior to exiting
Prevent silent exit of ansible-operator when URL fails verification.
**Checklist**
Apologies if I haven't followed the process correctly.
> log error for url verification failure

- website/content/en/docs/best-practices/resource-pruning.md
The log field could not be set as it was unexported. The log strategy also needed to be aligned with the rest of the library.
[operator-lib PR #100](https://github.com/operator-framework/operator-lib/pull/100)
It was not usable as it was and the documentation needs to reflect the implementation change
**Checklist**
> Documents operator-lib PR #100.

- website/layouts/index.html
Drop the BLM banner.
The banner was originally put in place as a response to current events at the time. Those events have past and I believe keeping the banner up will dilute the message. This change does not mean we are changing our policy, just simply cleaning up the documentation site.
**Checklist**
> Drop the BLM banner.

- website/content/en/docs/upgrading-sdk-version/v1.18.0.md
This wasn't actually a typo, seems @jmrodri forgot to fill in his changelog fragment?
fixes #5576
> fix java bump changelog in v1.18.0 docs

- hack/generate/samples/internal/ansible/testdata/watches.yaml
This significantly lowers the load on the test-operator, which was
getting restarted due to resource limits.
Re #5547
> Restrict secrets to watch with label selector

- internal/ansible/watches/watches.go
- internal/ansible/watches/watches_test.go
- internal/cmd/ansible-operator/run/cmd.go
Signed-off-by: Venkat Ramaraju <vramaraj@redhat.com>
Added the usage of the reconcile-period CLI flag in Ansible
Close #5594
> Close #5594: Ansible reconcile-period CLI flag

- website/content/en/docs/faqs/_index.md
There is a known controller-tools issue where rbac markers are not
parsed correctly if they are not followed by a newline.
Fixes: Bugzilla 2061611
Fixes: #5627 
Add an FAQ to notify users about a known issue in `controller-tools`.
There is a known controller-tools issue where rbac markers are not
parsed correctly if they are not followed by a newline.
**Checklist**
> Notify users of rbac marker parsing error

- changelog/fragments/scorecard-deadline.yaml
- internal/cmd/operator-sdk/scorecard/cmd.go
Handle `DeadlineExceeded` errors by allowing test output to be printed even during context timeouts
context timeouts hide all test results
Fixes: #5415 
**Checklist**
> fix: printout errors even if we have a timeout

- go.mod
- go.sum
Co-authored-by: Prashant Arya <prary2@gmail.com>
Present Operator framework image has CVE, this PR mitgated the CVEs in it.
```
✗ Medium severity vulnerability found in github.com/prometheus/client_golang/prometheus/promhttp
Description: Denial of Service (DoS)
Info: https://snyk.io/vuln/SNYK-GOLANG-GITHUBCOMPROMETHEUSCLIENTGOLANGPROMETHEUSPROMHTTP-2401819
Introduced through: github.com/prometheus/client_golang/prometheus/promhttp@1.11.0
From: github.com/prometheus/client_golang/prometheus/promhttp@1.11.0
Fixed in: 1.11.1
```
Upgrading go dependencies fixes the CVE's.
**Checklist**
> bump: update prometheus to fix medium vulnerability

- website/content/en/docs/faqs/_index.md
For images that are no longer supported, users can still update
dependencies and use their own versions of these images. Add this
information to the FAQ.
> Document how to update your own OSDK images

- website/layouts/partials/footer.html
- website/layouts/partials/head.html
This PR removes a RedHat specific script and the RedHat
Privacy statement link from the documentation site.
**Checklist**
> (docs) Remove Red Hat links

- website/content/en/docs/building-operators/golang/quickstart.md
Removed a repetitive word `in`.
Removed a repetitive word `in` in the quickstart documentation.
To correct the quickstart guide for improving the interpretation.
> Removed Repetitive word

- website/content/en/docs/building-operators/golang/quickstart.md
- website/content/en/docs/contribution-guidelines/documentation.md
Include steps for running the operator locally in the Go operator quickstart
Add a section to the Go operator Quickstart guide that details how to run a Go operator locally (outside of the cluster)
The steps for running a Go operator locally already exists in the detailed Go operator tutorial. Going through the docs it felt like it might be nice for someone who just wants to go through the Go operator Quickstart guide and not the in-depth tutorial to know that there is a way to run the operator locally.
**Checklist**
> update Go operator quickstart docs

- internal/cmd/operator-sdk/scorecard/cmd.go
- internal/cmd/operator-sdk/scorecard/xunit/xunit.go
Currently, scorecard's XUnit output does not conform to any XUnit
schema. This makes the scorecard XUnit output conform with the XUnit
schema defined by the Jenkins XUnit plugin.
This is sample output from running scorecard against the sample Go v3
Memcached operator:
```xml
<testsuites name="scorecard">
<testsuite name="olm-bundle-validation-test" tests="1" skipped="0" failures="0" errors="0">
<properties>
<property name="spec.image" value="quay.io/operator-framework/scorecard-test:v1.19.0"></property>
<property name="spec.entrypoint" value="scorecard-test olm-bundle-validation"></property>
<property name="labels.test" value="olm-bundle-validation-test"></property>
</properties>
<testcase name="olm-bundle-validation" time="0001-01-01T00:00:00Z"> …
```
> Fix scorecard XUnit output

- changelog/fragments/fix-make-bundle.yaml
- internal/cmd/operator-sdk/generate/bundle/bundle.go
- internal/cmd/operator-sdk/generate/internal/relatedimages.go
- internal/cmd/operator-sdk/generate/internal/relatedimages_test.go
- internal/generate/clusterserviceversion/clusterserviceversion.go
The related image discovery feature currently only reads environment
variables from the manager container. This was causing an error when the
deployment labels or container name that was expected were not present.
This fixes that by collecting related images from all containers across
all deployments.
This change also enables users to use related images in other containers
since related images from everywhere will be considered.
Signed-off-by: Ryan King <ryking@redhat.com>
> Fix related image environment variable discovery

- Makefile
- hack/tests/e2e-ansible-molecule.sh
This updates the `Makefile` so only one kind cluster is used for running
tests instead of two.
Signed-off-by: Ryan King <ryking@redhat.com>
> Make it so tests share one kind cluster

- changelog/fragments/proxy-port-flag.yaml
- internal/ansible/flags/flag.go
- internal/cmd/ansible-operator/run/cmd.go
> Added proxy server port customization for Ansible

- changelog/fragments/bump-api.yaml
- go.mod
- go.sum
bump operator-framework api
Check the differences here: https://github.com/operator-framework/api/compare/v0.14.0...33310d6154f344da5494c788451bd34cdf54711c
**Motivations**
Closes: https://github.com/operator-framework/operator-sdk/issues/5586
> :sparkles: bump operator-framework api

- website/content/en/docs/building-operators/golang/crds-scope.md
CRD scope either `Namespaced` or `Cluster`, right marker should be 
`//+kubebuilder:resource:scope=Namespaced` , Not 
`//+kubebuilder:resource:scope=Namespace` .
> Fix marker for kubebuilder

- proposals/ansible-operator-status.md
The Previous URL is outdated and results in a 404 - Update the docs to point to the correct page
Update the URL of doc for implemented status management proposal with the correct URL 
Inability to find the correct doc for days :smiling_face_with_tear: 
**Checklist**
> Update URL for Docs

- website/content/en/docs/olm-integration/tutorial-bundle.md
Added a clarification to docs about the use of `--index-image` flag while invoking run bundle.
More precise. If an author runs an upgrade on a bundle that was installed with an index image, the default bundle add mode is "replaces" instead of "semver". This means that the upgraded CSV must have a replaces field that points to an older version of the operator, otherwise the upgrade process will timeout.
> Docs: Clarification about the use of index image in run bundle(-upgrade)

- .github/workflows/olm-check.yml
- hack/check-olm.sh
Add a check to CI that will check for the OLM versions to be up to date with the 3 latest minor releases.
The check is implemented as a shell script so that the check can also be run locally outside of CI. 
The script will check the following files for the most up to date OLM versions:
- Makefile
- internal/bindata/olm/versions.go
- internal/testutils/olm.go
- website/content/en/docs/overview/_index.md
The check assumes that if you change the `OLM_VERSIONS` variable in the Makefile that you also have run `make bindata` to update the OLM bindata and therefore does not directly check the bindata.
The CI check will also only run on PRs from a branch prefixed with `release-` as to prevent the check from running on every PR.  …
> ci: add check for up-to-date olm versions

- Makefile
Changed Makefile command to include lightweight tags so that the correct SDK version is used in annotations. 
Close #5612
> Include lightweight tags in version annotation

- website/content/en/docs/building-operators/golang/installation.md
go1.16 not work for [go-quickstart](https://sdk.operatorframework.io/docs/building-operators/golang/quickstart/) anymore ,must update to go1.17
When i try to run ```operator-sdk init --domain example.com --repo github.com/example/memcached-operator``` ,failed at go1.16 and go1.18 ,only work at go1.17
Run error some as [https://github.com/kubernetes-sigs/controller-tools/issues/643](https://github.com/kubernetes-sigs/controller-tools/issues/643)
update installation.md go version
> Docs: update installation.md go version

- website/content/en/docs/testing-operators/scorecard/_index.md
Add xunit output example to docs website
New functionality added to SDK, needs docs
**Checklist**
> Add xunit sample to Scorecard Docs

- go.mod
- internal/olm/operator/bundle/install.go
- internal/olm/operator/registry/fbcindex/fbc_registry_pod.go
- internal/olm/operator/registry/index/registry_pod.go
- internal/olm/operator/registry/index/registry_pod_test.go
- internal/olm/operator/registry/index_image.go
- Create a file-based catalog (FBC) on the fly by generating the bundle, package and channel blobs, if an index image is not provided by the user (i.e. for a default index image `quay.io/operator-framework/opm:latest`) and serve it over a gRPC port.
- If an index image is provided through the flag, then bundle image will be inserted to the index by appending the bundle contents (rendered bundle image) to the index that's converted to a declarative config and this index containing the bundle will be served over a gRPC port.
- If bundle already exists in the index, then we will error out and not proceed with serving the index image.
- Generated FBC will be validated (equivalent to the `opm validate` command) and converted to a string format and sent down to …
> Implement file-based catalog (FBC) support for run bundle

- changelog/fragments/bump-helm-operator-plugins.yaml
- go.mod
- go.sum
Signed-off-by: Bryce Palmer <bpalmer@redhat.com>
Bump helm-operator-plugins to v0.0.10
resolves #5771 
**Checklist**
> bump helm-operator-plugins version

- tools/scripts/fetch
This change updates the goreleaser installation in the tools/scripts/fetch script to download the tar.gz file from the goreleaser github releases page (https://github.com/goreleaser/goreleaser/releases) based on the version tag given.
When attempting to make a patch release for v1.20.1 the deploy action was failing due to curl not being able to resolve the hostname `install.goreleaser.com`. When attempting to reach that same hostname locally it fails to resolve it as well. 
We can see this in the following action results: https://github.com/operator-framework/operator-sdk/runs/6512280746?check_suite_focus=true
<details>
<summary>Error output from action</summary>
```
make -f release/Makefile release
make[1]: Entering directory …
```
> update goreleaser install method

- internal/ansible/flags/flag.go
Changed default reconcile period (from the `--reconcile-period` command-line flag) to 10 hours.
More reasonable reconcile interval.
> Changed the default reconcile period for Ansible-based operators to 10 hours

- changelog/fragments/bundle-scorecard.yaml
- internal/cmd/operator-sdk/generate/bundle/bundle.go
Scorecard details got generated for the bundle even if no details were present for the scorecard in the java plugin
Updated the flag which will check for the scorecard path.
It will verify the path of the scorecard and if present then only it generates its artifacts in `bundle.Dockerfile`
**Checklist**
Before:
```
FROM scratch
LABEL operators.operatorframework.io.bundle.mediatype.v1=registry+v1
LABEL operators.operatorframework.io.bundle.manifests.v1=manifests/
LABEL operators.operatorframework.io.bundle.metadata.v1=metadata/
LABEL operators.operatorframework.io.bundle.package.v1=memcached-quarkus-operator
LABEL …
```
> Scorecard details gets generated for java plugin in bundle.Dockerfile

- changelog/fragments/hide-skip-tls.yaml
- internal/olm/operator/registry/index_image.go
Hide `--skip-tls` flag as it is deprecated
As per the discussion, we must keep this field hidden.
The user will not see deprecated command.
**Checklist**
> deprecated skip-tls flag marked as hidden

- website/content/en/docs/advanced-topics/multi-sa.md
Document how to use the `--extra-service-accounts` flag as it isn't documented well.
Needed to use the `--extra-service-accounts` flag to add multiple service accounts but wasn't clear how to use it.
**Checklist**
Fixes #5435
> Document how to use the `--extra-service-accounts` flag

- changelog/fragments/deprecate-crdversionflag.yaml
- internal/plugins/ansible/v1/api.go
- internal/plugins/helm/v1/api.go
- internal/plugins/util/message.go
deprecate the flag  since  APIs is not longer offered from k8s 1.22 and this flag is deprecated for Golang
NOTE: Users should no longer be using this option since if they scaffold projects with v1beta1 it will no longer work on Kubernetes versions >= 1.22. By using v1 for CRDs they can create projects which can work since Kubernetes 1.16
> (ansible/v1, helm/v1): deprecate the flag  since  APIs is not longer offered from k8s 1.22 and this flag is deprecated for Golang

- changelog/fragments/sdk-fbc-run-bundle(-upgrade).yaml
- go.mod
- internal/cmd/operator-sdk/run/bundle/cmd.go
- internal/olm/fbcutil/util.go
- internal/olm/operator/bundle/install.go
- internal/olm/operator/bundleupgrade/upgrade.go
- internal/olm/operator/registry/catalog.go
- internal/olm/operator/registry/fbcindex/fbc_registry_pod.go
- internal/olm/operator/registry/index/registry_pod.go
- internal/olm/operator/registry/index/registry_pod_test.go
- internal/olm/operator/registry/index_image.go
- internal/olm/operator/registry/operator_installer.go
- website/content/en/docs/cli/operator-sdk_run_bundle.md
Closes #5593
- Add FBC support to `run bundle` and `run bundle-upgrade` commands by create a file-based catalog (FBC) on the fly by generating the bundle, package and channel blobs, if an index image is not provided by the user (i.e. for a default index image `quay.io/operator-framework/opm:latest`) and serve it over a gRPC port.
- For run bundle: If an index image is provided through the flag, then bundle image will be inserted to the index by appending the bundle contents (rendered bundle image) to the index that's converted to a declarative config and this index containing the bundle will be served over a gRPC port.
- If bundle already exists in the index, then we error out and not serve the index image (which is consistent with the existing SQLite …
> Merge feature/run-bundle into master: Add FBC support to `run bundle` and `run bundle-upgrade` commands

- website/content/en/docs/building-operators/ansible/reference/advanced_options.md
Added documentation for reconcile-period to Ansible docs. This is a copy of the [existing](https://sdk.operatorframework.io/docs/building-operators/helm/reference/advanced_features/annotations/#helmsdkoperatorframeworkioreconcile-period) Helm docs. 
Close #5837
> Close #5837: Document reconcile period for Ansible in advanced options

- hack/generate/samples/internal/ansible/constants.go
- testdata/ansible/memcached-operator/roles/memcached/tasks/main.yml
Update Ansible sample to comply with Pod Security Standards
https://github.com/operator-framework/operator-sdk/pull/5852
> Update Ansible sample to comply with Pod Security Standards

- website/content/en/docs/best-practices/pod-security-standards.md
In the documentation about pod security standards was a dead link to the memcache example CSV yaml. This PR addresses it and uses the correct link to the example CSV.
Fixing deadlink in docu.
> Fix link to CSV in pod-security-standards docu

- internal/olm/operator/bundle/install.go
- internal/olm/operator/registry/index_image.go
Propagate correct error message when an invalid index image is provider by the user that does not exist. 
With this fix, the error below would be as below:
▶ ./build/operator-sdk run bundle quay.io/olmqe/k8sstatus-bundle:v4.10 --index-image quay.io/kakatest/kkkkk:test
FATA[0005] Failed to run bundle: error determining whether index "quay.io/kakatest/kkkkk:test" is FBC or SQLite based: get index image labels: error pulling image quay.io/kakatest/kkkkk:test: error resolving name : unexpected status code [manifests test]: 401 UNAUTHORIZED
**Checklist**
> Bug 2090135: Propagate correct error message for an invalid index

- internal/olm/operator/registry/fbcindex/fbc_registry_pod.go
- internal/olm/operator/registry/index_image.go
The registry pod index directory now includes the CatalogSource name to prevent conflicts between indexes in the same directory
Signed-off-by: Bryce Palmer <bpalmer@redhat.com>
Update the registry pod index directory to include the `CatalogSource` name.
Potential fix for #5870 
`run bundle-upgrade` was not working properly when upgrading a traditionally (OLM) installed  operator for FBC indexes. It seems this issue is due to multiple indexes being in the same directory that have repeating package definitions.
This change makes it so that the directory indexes are stored in correlate to the `CatalogSource` that is created/used for the upgrade. This seems to have resolved the issue.
(This change also affects `run bundle` as it …
> (bugfix): `run bundle` and `run bundle-upgrade` - update registry pod index directory

- .gitmodules
- website/content/en/docs/advanced-topics/custom-bundle-validation.md
Covers the `--alpha-select-external` usage, writing a custom validator
from scratch, and how to use validations in `operator-framework/api` at
arbitrary versions.
> Add custom validator tutoral

- changelog/fragments/rbu-ip-approval-bugfix.yaml
- internal/olm/operator/registry/operator_installer.go
- internal/olm/operator/registry/operator_installer_test.go
Modify the `internal/olm/operator/registry/operator_installer.go` `waitForInstallPlan` function to now wait for the `InstallPlan` to be different than the previous `InstallPlan` before attempting to approve it.
Update the tests as well.
resolves #5897 
The previous logic would approve the `InstallPlan` based on the `InstallPlanRef` in a `Subcription`s status not being empty. This caused an issue when running `operator-sdk run bundle-upgrade` as it would occasionally approve the previous CSV's `InstallPlan` because the `Subscription`'s `InstallPlanRef` had not yet been updated to reflect new changes. This lead to having to manually approve the new `InstallPlan`s so that the rest of the `operator-sdk run bundle-upgrade` command …
> (bugfix): approve `InstallPlan` only if it is a new `InstallPlan`

- hack/generate/samples/internal/go/v3/memcached_with_webhooks.go
- test/e2e/go/cluster_test.go
- testdata/go/v3/memcached-operator/controllers/memcached_controller.go
- website/content/en/docs/best-practices/pod-security-standards.md
- Update the `SecurityContext` to contain the `RunAsUser` field with the UID set to `1000`.
- Update Go e2e tests to make sure all pods that contain the substring `memcached` are in the "Running" state
- Update https://sdk.operatorframework.io/docs/best-practices/pod-security-standards/ to include information about this change.
resolves #5902
**Checklist**
> (bugfix): fix SecurityContext in Go memcached sample

- website/content/en/docs/upgrading-sdk-version/v1.22.0.md
Correct the version in the docs to match the one in the [requirement.yaml](https://github.com/operator-framework/operator-sdk/blob/master/testdata/ansible/memcached-operator/requirements.yml#L10) for ansible operator. 
Reference PR https://github.com/operator-framework/operator-sdk/pull/5846 which delivered the incorrect version
**Checklist**
> Correct cloud.common version to match the requirements.yaml

- changelog/generated/v1.22.0.md
- website/content/en/docs/upgrading-sdk-version/v1.22.0.md
Signed-off-by: Mitulsharma123 <sharmamitul72@gmail.com>
Added missing url for https://github.com/kubernetes-sigs/kubebuilder/pull/2596 in v1.22.0.md 
To make documentation readable and precise 
**Checklist**
> [Doc] Added git url release note v1.22.0.md 

- Makefile
- make lint -> to run only the lint checks ( many times we just want to check the lint and the sanity takes too long )
- make fix -> calling option used in Kubebuilder to fix small issues like when having unused imports which are very unproductive be required to be fixed manually. 
**Motivation**
Face scenarios like on the CI:
> dx: add option to run only the lint checks as fix small issues automatically i.e. unused imports

- go.mod
- internal/olm/operator/registry/fbcindex/fbc_registry_pod.go
- internal/olm/operator/registry/index/registry_pod.go
Closes https://github.com/operator-framework/operator-sdk/issues/5932
Registry pod doesn't have "securityContext.runAsNonRoot=true" config which should be generated by `run bundle(-upgrade)`. Additionally, also set the `ServiceAccount` from the pod configuration.
Steps to Reproduce:
1. operator-sdk run bundle quay.io/example/bundle:v4.10
2. oc get pods
Actual results:
3. oc get pod quay-io-example-bundle-v4-10 -o yaml | grep "securityContext" -A1. 4. 
`securityContext: {}`
`serviceAccount: default`
Expected results:
5. oc get pod quay-io-example-bundle-v4-10 -o yaml | grep "securityContext" -A1.6. 
`securityContext:`
`runAsNonRoot: true`
`serviceAccount: default`
Set the security context for the registry pod by including the …
> Add securityContext config to Registry pod spec for run bundle(-upgrade)

- changelog/fragments/export-scorecard-storage.yaml
- internal/scorecard/storage.go
Signed-off-by: Andrej Podhradsky <apodhrad@redhat.com>
**Checklist**
> OSDK-2345: Export scorecard storage as an env variable in a test pod

- changelog/fragments/fix-scorecard-mountpath.yaml
- internal/scorecard/storage.go
Signed-off-by: Andrej Podhradsky <apodhrad@redhat.com>
**Checklist**
> OSDK-2303: Scorecard testOutput is tightly coupled with storage mountPath

- website/content/en/docs/overview/operator-capabilities.md
Signed-off-by: Shirly Radco <sradco@redhat.com>
Since metering is a deprecated feature, removed it from the Deep Insights capability level requirements.
Links to deprecation notice: 
- https://github.com/kube-reporting/metering-operator
- https://docs.openshift.com/container-platform/4.8/metering/metering-about-metering.html
Incorrect requirements for Deep Insights capability level creates confusion.
**Checklist**
> Remove metering from deep insights capability

- changelog/fragments/fix.yaml
- internal/plugins/manifests/v2/templates/config/manifests/kustomization.go
- website/content/en/docs/faqs/_index.md
Signed-off-by: Camila Macedo <cmacedo@redhat.com>
fix operator-sdk generate kustomize manifests to respect changes made by users in the config/manifests
If we change the target value on the command to solve the breaking change faced with Kustomize v4 it still not working
because the SDK subcommand call the Helper plugin to generate the CSV and it was not configured to Skip the file when it is scaffolded already.  
**Checklist**
Motivation: https://github.com/operator-framework/operator-sdk/issues/5898
> :bug: fix operator-sdk generate kustomize manifests to respect changes made by users in the config/manifests

- hack/generate/samples/internal/go/v3/memcached_with_webhooks.go
- website/content/en/docs/best-practices/pod-security-standards.md
Improve the documentation to let the users know how they can sort out the error scenarios that they might face.
> doc/samples: better clarification about runAsNonRoot and RunAsUser regards pod standards

- changelog/fragments/fix-run-upgrade-bundle.yaml
- internal/olm/operator/registry/fbcindex/fbc_registry_pod.go
- internal/olm/operator/registry/index/registry_pod.go
Fix operator-sdk run bundle and upgrade bundle subCommands to allow they to work against Kubernetes versions < 1.19 and vendors like Openshift
> fix: run and upgrade bundle subcommands to they work well with vendors

- website/content/en/docs/overview/operator-capabilities.md
- doc: improve capability doc by providing a better explanation over the  deep insight level
- Add k8s api convention links/info to let the authors follow the good practices
- Add the links for the metrics documentation and for let them be aware of the helpers provided to them
> doc: improve capability doc by providing a better explanation over the  deep insight level

- changelog/fragments/fix-plugin.yaml
- internal/cmd/operator-sdk/cli/cli.go
fix deploy-image for sdk to generate the bundle with the apis created by it
In SDK we need to update the manifests with the APIs created so that we can generate the bundle.
> fix: deploy-image for sdk to generate the bundle with the apis created by it

- hack/generate/samples/internal/go/memcached-with-webhooks/memcached_with_webhooks.go
- testdata/go/v3/memcached-operator/Dockerfile
- testdata/go/v3/memcached-operator/controllers/memcached_controller.go
- testdata/go/v3/memcached-operator/go.mod
- testdata/go/v3/memcached-operator/main.go
- testdata/go/v3/memcached-operator/monitoring/metrics.go
- testdata/go/v4-alpha/memcached-operator/Dockerfile
- testdata/go/v4-alpha/memcached-operator/controllers/memcached_controller.go
- testdata/go/v4-alpha/memcached-operator/go.mod
- testdata/go/v4-alpha/memcached-operator/main.go
- testdata/go/v4-alpha/memcached-operator/monitoring/metrics.go
This PR adds to the sample `memcached-operator` (`testdata/go/v3/memcached-operator` & `testdata/go/v4-alpha/memcached-operator`) a metric named `memcached_deployment_size_undesired_count_total` as part of a new `monitoring` directory. 
This metric counts how many times it was required to perform the operation to ensure that the number of Memcached replicas on the cluster is the same as the quantity desired and specified via the custom resource size spec.
This PR includes scaffolding for this changes, within the existing sample `memcached-operator` scaffolding (i.e. `make generate` generates this functionally). 
We would like to implement observability concepts for the `memcahced-operator`, in order to have the operator in …
> Add a metric to the sample memcached-operator

- changelog/fragments/bump-java-operator-plugins.yaml
- go.mod
- go.sum
Bring in latest java-operator-plugins v0.6.0
Released of java-operator-plugins.
**Checklist**
> Bump java-operator-plugins to v0.6.0

- internal/testutils/olm.go
- internal/testutils/utils.go
Fix methods references in testutils comments
Prevent discrepancy between method naming and references in comments
**Checklist**
> testutils: fix method references in comments

- changelog/fragments/kuttl-selector.yaml
- images/scorecard-test-kuttl/Dockerfile
- images/scorecard-test-kuttl/entrypoint
Update the `entrypoint` to use the test name passed in from the test config. 
Fixes #5743 
**Checklist**
> Support test selection in scorecard-kuttl integration

- hack/generate/samples/internal/go/memcached-with-webhooks/memcached_with_webhooks.go
- testdata/go/v3/memcached-operator/controllers/memcached_controller.go
- testdata/go/v3/memcached-operator/main.go
- testdata/go/v4-alpha/memcached-operator/controllers/memcached_controller.go
- testdata/go/v4-alpha/memcached-operator/main.go
Signed-off-by: assafad <aadmi@redhat.com>
This PR changes the monitoring imports in the sample memcached-operator code to be comments by default. Users who want to use custom metrics for the operator, will uncomment these lines. Another separate PR will add a custom metric tutorial for the operator-SDK documentation, and there the users will be instructed to uncomment these lines. 
https://github.com/operator-framework/operator-sdk/issues/6008
**Checklist**
> Comment monitoring imports in the sample memcached-operator

- changelog/fragments/rbu-stall-fix.yaml
- internal/olm/fbcutil/util.go
- internal/olm/operator/bundle/install.go
- Updates the process of creating a new containerdregistry during the `operator-sdk run bundle(-upgrade)` process to no longer stall due a file lock clash. Instead, we now create a temporary registry directory based on the image references being used in the `fbcutil.RenderRefs()` function
- fixes #6039 
**Checklist**
> fix run bundle(-upgrade) to no longer stall

- .cncf-maintainers
- OWNERS_ALIASES
* removed camila and marc from cncf-maintainers
* removed marc from OWNERS_ALIASES
* added everettraven to OWNERS_ALIASES as reviewer
Failing `test-sanity` task.
**Checklist**
> Update .cncf-maintainers & OWNERS_ALIASES

- website/content/en/docs/building-operators/golang/tutorial.md
> Add API groups explanation to golang tutorial

- website/content/en/docs/overview/_index.md
someone forgot to do this when they bumped the olm bindata versions.
hmmmm @jmrodri
> bump supported OLM versions in docs

- website/content/en/docs/contribution-guidelines/releasing.md
`sed` command in MAC is used as `gsed`. Updated release doc.
**Checklist**
> Updated release doc for MAC users

- changelog/fragments/enable-seccompprofile-run-bundle.yaml
- internal/olm/operator/registry/fbcindex/fbc_registry_pod.go
- internal/olm/operator/registry/index/registry_pod.go
- internal/olm/operator/registry/index_image.go
- internal/olm/operator/registry/index_image_test.go
- website/content/en/docs/cli/operator-sdk_run_bundle-upgrade.md
- website/content/en/docs/cli/operator-sdk_run_bundle.md
Added --security-context-config flag to enable seccompprofile. It defaults to enabled to support k8s 1.25. You can disable it with --security-context-config=legacy
In k8s 1.25 PodSecurityAdmission is enabled. https://kubernetes.io/blog/2022/08/04/upcoming-changes-in-kubernetes-1-25/#podsecuritypolicy-removal
Fixes a few issues found downstream but affect upstream as well:
* https://issues.redhat.com/browse/OSDK-2481
* https://issues.redhat.com/browse/OCPBUGS-1666
**Checklist**
> OCPBUGS-1666: Expose flag to enable/disable PodSecurity

- website/content/en/docs/contribution-guidelines/releasing.md
- make locking the master branch it's own step like it is in the patch release section
- move the IMAGE_VERSION bump to section on creating the release commit. It can't be merged before the release commit is created because it causes test suites to fail. (Or is there some other way to do this? Jesus and I couldn't figure out a way to do it correctly).
> reformat release docs

- internal/util/bundleutil/bundleutil.go
Fix a type-o in the output.
I've also fixed a few other type-o's and spelling mistakes.
#6078
**Checklist**
> Fix type-o in output.

- website/content/en/docs/olm-integration/generation.md
- Updates the documentation for generating manifests
- fixes #6028
**Checklist**
> Update documentation for generating manifests

- changelog/fragments/multi-arch-changes.yaml
- internal/plugins/ansible/v1/scaffolds/internal/templates/makefile.go
- internal/plugins/helm/v1/scaffolds/internal/templates/makefile.go
- testdata/ansible/memcached-operator/Makefile
- testdata/helm/memcached-operator/Makefile
Similar to the go plugin, adding support for building multi-arch images from the project `Makefile`.
Make it easier to build multi-arch operator images.
**Checklist**
> Fixes #6037: Add multi-arch builder to ansible and helm plugins

- changelog/fragments/docs-bump-go-version.yaml
- website/content/en/docs/contribution-guidelines/developer-guide.md
The version of go has been bumped, but the docs haven't been updated.  The commit updates the developer guide with the correct version.
#6087 
**Checklist**
Closes #6087
> Docs: Update the minimum version of go from 1.17 to 1.18

- website/content/en/docs/building-operators/ansible/tutorial.md
Previously, if you ran the suggested command `kustomize build config/default | kubectl apply -f -`, that would render an incorrect manifest. That is because when the user changed the value of `IMAGE_TAG_BASE` and `IMG` in the Makefile during a previous step, that change has not yet been applied to kustomize manifests at the time of running the suggested command. So the wrong image reference ends up being rendered, and the manifests get applies to the cluster. `make deploy` must be run first, which updates the kustomize manifest.
This change clarifies that running `kustomize build config/default` is part of explaining to the reader how things work, is not a required step that should apply anything to the cluster, AND importantly should not be run until after …
> docs: re-orders deploy steps and clarifies instructions

- changelog/fragments/01-ansible-fix-make-run.yaml
- internal/plugins/ansible/v1/scaffolds/internal/templates/makefile.go
- website/content/en/docs/building-operators/ansible/tutorial.md
Previously, an ansible operator would be scaffolded with a Makefile whose "run" target had incorrect syntax. It would run this command:
`ANSIBLE_ROLES_PATH="$(ANSIBLE_ROLES_PATH):$(shell pwd)/roles" $(ANSIBLE_OPERATOR) run`
That command failed to set the `ANSIBLE_ROLES_PATH` variable correctly because it was using Makefile syntax in a target's recipe, which gets interpreted as shell script.
This commit moves the variable setting statement, which uses Makefile syntax, out of the recipe. It also uses the standard `?=` operator to only set the variable if it is unset.
Signed-off-by: Michael Hrivnak <mhrivnak@redhat.com>
fix the bug
**Checklist**
> fixes broken "make run" for ansible operators

- changelog/fragments/02-api-bump-k8s-125-validation.yaml
- go.mod
- go.sum
- Bumps operator-framework/api to commit https://github.com/operator-framework/api/commit/b611f6cef49cb8c6d621145c4e31d8ddfd4c59f4
- Add to `operator-sdk bundle validate` the updated k8s 1.25.x deprecated API validation logic
**Checklist**
> bump operator-framework/api 

- website/content/en/docs/building-operators/ansible/development-tips.md
collection community.kubernetes is now deprecated in favor of kubernetes.core
use collection kubernetes.core instead of community.kubernetes
collection community.kubernetes is now deprecated in favor of kubernetes.core
**Checklist**
> Point kubernetes collection to kubernetes/core instead of community.kubernetes

- website/content/en/docs/best-practices/pod-security-standards.md
Signed-off-by: Vladimir Belousov <vbelouso@redhat.com>
Fixed typo in namespace labeling command. Сolon sign replaced with an equal sign.
```sh
kubectl label --overwrite ns mytest \
pod-security.kubernetes.io/enforce=restricted \
pod-security.kubernetes.io/enforce-version=v1.24 \
pod-security.kubernetes.io/audit: restricted
```
The current command does not execute correctly and ends with an error
```sh
error: all resources must be specified before label changes: pod-security.kubernetes.io/audit:restricted
```
**Checklist**
> docs: fix typo in namespace labeling command

- changelog/fragments/03-ubi-image-bump.yaml
- images/ansible-operator-2.11-preview/base.Dockerfile
- images/ansible-operator/base.Dockerfile
- images/custom-scorecard-tests/Dockerfile
- images/helm-operator/Dockerfile
- images/operator-sdk/Dockerfile
- images/scorecard-test/Dockerfile
- Bumps `ubi(-minimal)` image version to `8.7`
- Our images depend on `ubi(-minimal)` and are currently on version `8.6`. Version `8.7` was released ~6 days ago. We need to update the version to ensure we are always pulling in the latest updates.
**Checklist**
> (chore): bump ubi(-minimal) to 8.7

- website/content/en/docs/overview/operator-capabilities.md
- CHANGED accumulating for independent levels on cap description
Signed-off-by: acmenezes <adcmenezes@gmail.com>
On this PR I propose to change the capability description found at https://sdk.operatorframework.io/docs/overview/operator-capabilities/ where the word accumulating leads to the understanding that capability levels are technically dependent on lower level ones. We know that we can include level 4 capabilities without having level 3 or 2 for example. We can have a broader discussion about how to grant badges for the operator hubs on this. This is not the intention here. It's just to eliminate the confusion for the users reading this doc.
Multiple partners, operator-sdk users, have asked questions about this …
> CHANGE capability level description to independent levels

- images/operator-sdk/Dockerfile
Closes 6171
Added GCC to dependencies
operator-sdk cli is not fully functional without it with default settings if run through docker image
For more details see #6171 
**Checklist**
> add gcc to image dependencies, so it can be used to fully run operator-sdk cli

- hack/generate/samples/internal/ansible/memcached.go
- hack/generate/samples/internal/go/memcached-with-webhooks/memcached_with_webhooks.go
- hack/generate/samples/internal/helm/memcached.go
- internal/generate/clusterserviceversion/clusterserviceversion_test.go
- internal/generate/clusterserviceversion/clusterserviceversion_updaters.go
- internal/generate/testdata/clusterserviceversions/bases/memcached-operator.clusterserviceversion.yaml
- internal/generate/testdata/clusterserviceversions/output/memcached-operator-multiVersion.yaml
- internal/generate/testdata/clusterserviceversions/output/with-ui-metadata.clusterserviceversion.yaml
- testdata/ansible/memcached-operator/bundle/manifests/memcached-operator.clusterserviceversion.yaml
- testdata/go/v3/memcached-operator/bundle/manifests/memcached-operator.clusterserviceversion.yaml
- testdata/go/v3/monitoring/memcached-operator/bundle/manifests/memcached-operator.clusterserviceversion.yaml
- testdata/go/v4-alpha/memcached-operator/bundle/manifests/memcached-operator.clusterserviceversion.yaml
- testdata/go/v4-alpha/monitoring/memcached-operator/bundle/manifests/memcached-operator.clusterserviceversion.yaml
- testdata/helm/memcached-operator/bundle/manifests/memcached-operator.clusterserviceversion.yaml
Signed-off-by: Gabe Alford <redhatrises@gmail.com>
The createdAt field should be updated when `make bundle` is run.
Per discussion with the operator-sdk team at KubeCon, having createdAt updated on a `make bundle` is one less thing that has to be manually updated.
**Checklist**
> Update createdAt when `make bundle` is run

- release/Makefile
- website/config.toml
- website/content/en/docs/overview/_index.md
- website/layouts/shortcodes/client-go-version.html
- website/layouts/shortcodes/kube-version.html
- website/scripts/update_branch_mappings.sh
- website/scripts/update_latest_release_compat.sh
- In the docs, update the Kubernetes compatibility matrix table to include the Kubernetes version that the binaries were tested against for a given version and the client-go version that the binary was built with.
- Fixes #6072 
**Checklist**
> update kubernetes compatibility matrix

- changelog/fragments/04-rbu-large-fbc.yaml
- internal/olm/operator/registry/fbcindex/fbc_registry_pod.go
- internal/olm/operator/registry/fbcindex/fbc_registry_pod_test.go
Updates the logic of `operator-sdk run bundle(-upgrade)` to:
- Partition FBCs into multiple ConfigMaps and mount them as Volumes to the registry pod as needed
- It will only partition into multiple ConfigMaps if the FBC contents are too large to fit into a single ConfigMap
- Use the `CatalogSource` name as part of the `ConfigMap` name so that its contents aren't overwritten every time `operator-sdk run bundle(-upgrade)` is used in the same namespace.
- Fixes #6144 
**Checklist**
> (bugfix): update run bundle(-upgrade) logic

- website/content/en/docs/faqs/_index.md
- website/content/en/docs/olm-integration/tutorial-bundle.md
- Add a note in the bundle tutorial about specifying the index image used for handling SQLite bundles in versions of `operator-sdk` < `v1.22.0` as FBC support wasn't enabled until `v1.22.0`
- Add a FAQ section for the error that may be encountered when using `operator-sdk run bundle` with `operator-sdk` versions < `v1.22.0`
- closes #6049 
**Checklist**
> update docs for operator-sdk run bundle with SQLite

- website/content/en/docs/building-operators/golang/tutorial.md
Signed-off-by: Chirayu Kapoor <dev.csociety@gmail.com>
>To begin, we will represent our API by defining the `Memcached` type, which will have a `MemcachedSpec.Size` field to set the quantity of memcached instances (CRs) to be deployed, and a `MemcachedStatus.Nodes` field to store a CR's Pod names.
>
>**Note** The Node field is just to illustrate an example of a Status field. In real cases, it would be recommended to use [Conditions][conditionals].
Updated the content to be coherent with the code snippet
> To begin, we will represent our API by defining the `Memcached` type, which will have a `MemcachedSpec.Size` field to set the quantity of memcached instances (CRs) to be deployed, and a `MemcachedStatus.Nodes` field to store a CR's …
> Updated the content to be coherent with the code snippet

- changelog/fragments/01-fix-ansible-image.yaml
- images/ansible-operator-2.11-preview/Dockerfile
- images/ansible-operator/Dockerfile
- Updates the `ansible-operator` and `ansible-operator-2.11-preview` Dockerfiles to now use the base image with tag `master-aa0243440429e60568c27df5c7c22976f2b23a16`. This tag was built with the UBI 8.7 image as a base.
- patch the v1.25.x branch in preparation to create a v1.25.3 patch release that updates the ansible-operator images to use the proper ansible-operator base image that is built with UBI 8.7 instead of UBI 8.6. Creating this patch release would help in fixing #6183 
**Checklist**
> update ansible operator images to use the base image that uses UBI 8.7

- changelog/fragments/05-rbu-psa.yaml
- internal/olm/operator/bundle/install.go
- internal/olm/operator/registry/fbcindex/fbc_registry_pod.go
- internal/olm/operator/registry/index/registry_pod.go
- internal/olm/operator/registry/index/registry_pod_test.go
- internal/olm/operator/registry/index_image.go
- internal/olm/operator/registry/olm_resources.go
- website/content/en/docs/advanced-topics/custom-bundle-validation.md
- website/content/en/docs/advanced-topics/multi-arch.md
- website/content/en/docs/cli/operator-sdk_run_bundle-upgrade.md
- website/content/en/docs/cli/operator-sdk_run_bundle.md
- website/content/en/docs/contribution-guidelines/releasing.md
- website/content/en/docs/overview/cheat-sheet.md
- website/content/en/docs/upgrading-sdk-version/v1.5.0.md
- Update default channel name selection to be different based on using FBC vs SQLite image.
- Update the `SecurityContext` from the registry pod containers created by `operator-sdk run bundle(-upgrade)` to only be added to the containers when `--security-context-config=restricted`
- Change default of `--security-context-config` flag to be `legacy` in anticipation of some OpenShift PSA changes.
- Set the `CatalogSource.grpcPodConfig.securityContextConfig` to the same value of the `--security-context-config` flag.
- Fixes a bug where SQLite bundle images couldn't be properly run due to setting the default channel name to `operator-sdk-run-bundle`.
- This became a problem because we can manipulate FBCs to utilize this default …
> (bugfix): OCPBUGS-3072 - fix `operator-sdk run bundle(-upgrade)` PSA related issues

- changelog/fragments/01-validate-bugfix.yaml
- go.mod
- go.sum
- Bumps operator-framework/api dependency to https://github.com/operator-framework/api/commit/f1b729684854a053f229464eb327527222188fd1
- Fixes a bug in the k8s 1.25 validation logic when running `operator-sdk bundle validate ...` that was caused by the validation logic not checking both the group and the resource when validating permissions in the CSV. This bug would cause a warning to be issued to all resources with the same name regardless of what group they are in.
**Checklist**
> (bugfix): bump operator-framework/api dependency version

- changelog/fragments/6225-print-kuttl-logs.yaml
- images/scorecard-test-kuttl/main.go
Print kuttl logs if kuttl tests cannot be started  (for example when specifying an inaccessible path in `crdDir`).
The `empty kuttl test suite was found` error message is not helpful in case kuttl cannot be started.
**Checklist**
> Print kuttl logs if kuttl tests cannot be started

- internal/cmd/helm-operator/run/cmd.go
- internal/helm/client/actionconfig.go
- internal/helm/client/client.go
- internal/helm/client/restclientgetter.go
- internal/helm/release/manager_factory.go
See https://github.com/operator-framework/helm-operator-plugins/pull/198 for a detailed description of the issue. This commit ports over the relevant changes.
I assume that eventually, the generic `helm-operator` code in this repo should depend on github.com/operator-framework/helm-operator-plugins. However, because the latter repo is still marked as experimental, and importing it would result in a large number of accidental dependency changes, I have decided to merely copy code over.
I've tried to minimize changes to both the copied code as well as the existing code in this repo. Because the bulk of the code is copied, I don't think replicating tests would be useful, but I can see if I can copy them over if it turns out to be not too much effort.
**Description of the change:** Fix a …
> helm: fix a memory leak resulting from too many k8s client instantiations

- website/content/en/docs/installation/_index.md
- website/content/en/docs/upgrading-sdk-version/v1.25.0.md
Fixing some formatting issues in the 1.25.0 upgrade code and change the instillation prereq to be go 1.19
When following the upgrade from 1.22 to 1.26 I noticed some formating issues in the 1.25.0 doc that caused them to not copy properly, and also missing the need to change from go 1.18 to go 1.19.
**Checklist**
Signed-off-by: Adam D. Cornett <adc@redhat.com>
> fixing formatting in 1.25.0 doc and updating install prereq

- changelog/fragments/05-rbu-psa.yaml
- internal/olm/operator/bundle/install.go
- internal/olm/operator/registry/fbcindex/fbc_registry_pod.go
- internal/olm/operator/registry/index/registry_pod.go
- internal/olm/operator/registry/index/registry_pod_test.go
- internal/olm/operator/registry/index_image.go
- internal/olm/operator/registry/olm_resources.go
- website/content/en/docs/advanced-topics/custom-bundle-validation.md
- website/content/en/docs/advanced-topics/multi-arch.md
- website/content/en/docs/cli/operator-sdk_run_bundle-upgrade.md
- website/content/en/docs/cli/operator-sdk_run_bundle.md
- website/content/en/docs/contribution-guidelines/releasing.md
- website/content/en/docs/overview/cheat-sheet.md
- website/content/en/docs/upgrading-sdk-version/v1.5.0.md
Creating a cherry-pick of PR https://github.com/operator-framework/operator-sdk/pull/6210 to backport this fix onto 1.25.x branch
> [v1.25.x] (bugfix): OCPBUGS-3072 - fix operator-sdk run bundle(-upgrade) PSA related issues

- changelog/fragments/01-validate-bugfix.yaml
- go.mod
- go.sum
Cherry-pick of https://github.com/operator-framework/operator-sdk/pull/6227
> [v1.25.x] (bugfix): bump operator-framework/api dependency version (#6227)

- changelog/fragments/spec-scoreacrd-fix.yaml
- internal/scorecard/tests/basic.go
- internal/scorecard/tests/bundle_test.go
Cherry-pick of PR https://github.com/operator-framework/operator-sdk/pull/6245
> [v1.25.x] updated code and made state as pass and throw suggestion instead of error for missing spec in CR

- images/ansible-operator-2.11-preview/Pipfile
- images/ansible-operator-2.11-preview/Pipfile.lock
- images/ansible-operator/Pipfile
- images/ansible-operator/Pipfile.lock
Unpins the `cryptography` dependency for the ansible-operator base images by:
- Updating the `Pipfile` files
- Updating the `Pipfile.lock` files
- resolves #5739 
**Checklist**
> unpin cryptography dependency for ansible-operator base images

- changelog/fragments/6247-bundle-validate-exit-code.yaml
- internal/cmd/operator-sdk/bundle/validate/cmd.go
Updates the `operator-sdk bundle validate` command to properly issue a non-zero exit code if there are validation test failures.
- fixes #6247 
**Checklist**
> (bugfix): `operator-sdk bundle validate` returns exit code 0 despite test failures

- .github/workflows/deploy-manual.yml
- .github/workflows/deploy.yml
- .github/workflows/freshen-images.yml
- .github/workflows/integration.yml
- .github/workflows/rerun.yml
- .github/workflows/test-ansible.yml
- .github/workflows/test-go.yml
- .github/workflows/test-helm.yml
- .github/workflows/test-sample-go.yml
- .github/workflows/test-sanity.yml
New Ubuntu 22.04 runner image has been released
Upgrade[ Ubuntu runner image](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#choosing-github-hosted-runners) in Github Actions- `ubuntu-20.04`->`ubuntu-22.04`
Use the latest Ubuntu runner image for CI.
**Checklist**
> Upgrade Ubuntu runner image in github actions

- .github/workflows/deploy-manual.yml
- .github/workflows/deploy.yml
- .github/workflows/freshen-images.yml
- .github/workflows/integration.yml
- .github/workflows/test-ansible.yml
- .github/workflows/test-go.yml
- .github/workflows/test-helm.yml
- .github/workflows/test-sample-go.yml
- .github/workflows/test-sanity.yml
Upgrade Five GitHub Action Versions
There are newer versions for five GitHub Actions : 
- [actions/checkout](https://github.com/actions/checkout/releases)
- [actions/setup-go](https://github.com/actions/setup-go/releases)
- [docker/setup-qemu-action](https://github.com/docker/setup-qemu-action/releases)
- [docker/setup-buildx-action](https://github.com/docker/setup-buildx-action/releases)
- [docker/login-action](https://github.com/docker/login-action/releases)
**Checklist**
> Upgrade Five GitHub Action Versions

- hack/tests/e2e-ansible-molecule.sh
- internal/plugins/ansible/v1/scaffolds/internal/templates/requirements.go
- testdata/ansible/memcached-operator/requirements.yml
- Update molecule version in CI and the default ansible scaffolds to support a newer molecule version.
- Fix the ansible CI failures
**Checklist**
> Fix Ansible CI

- changelog/fragments/01-ansible-image-fixes.yaml
- images/ansible-operator-2.11-preview/base.Dockerfile
- images/ansible-operator/base.Dockerfile
Updates the ansible operator images base.Dockerfile to multi-stage builds so that we can ensure all packages are always included in the images we deliver by installing/building all packages in a build stage and copying them over to the final build stage.
fixes #6302
**Checklist**
> (ansible): update ansible base images to use multi-stage builds

- changelog/fragments/02-update-kubernetes-core.yaml
- internal/plugins/ansible/v1/scaffolds/internal/templates/requirements.go
- testdata/ansible/memcached-operator/requirements.yml
Updates the default kubernetes.core collection version included in the scaffolded `requirements.yaml` file to be v2.4.0.
- fixes #6258 
**Checklist**
> (ansible): update kubernetes.core collection default to v2.4.0

- go.mod
- go.sum
- internal/cmd/operator-sdk/generate/bundle/bundle.go
- generate bundle now specifies default auth when pulling images
this means operator-sdk will default to whatever auth docker is using on the system already (i.e. if the user has run `docker login`, it will use those creds).
Closes #6027
Closes #6095
> Bump operator-manifest-tools dependency

- .golangci.yml
- Makefile
- internal/ansible/runner/runner_test.go
- Bumps `K8S_VERSION` in Makefile to 1.26.0 so that our testing environment uses k8s 1.26
- Bumps `kind` version in Makefile to `0.17.0` so that it is up to date with the latest release
- Bumps `golangci-lint` version in Makefile to `1.51.2` to fix a problem I had locally where running `make lint` resulted in my terminal or editor crashing.
- K8s 1.26 bump
**Checklist**
> (testing): Bump K8S_VERSION for testing to 1.26.0

- internal/bindata/olm/versions.go
- internal/testutils/olm.go
Updates OLM version in places missed by `make bindata` target.
**Checklist**
> Update OLM version to 0.24.0

- website/content/en/docs/building-operators/golang/webhook.md
This commit adds documentation on not needing to use Cert-manager with OLM while using webhooks as OLM uses self-signed certs and is not compatible with any third-party cert management solution.
Closes #6257 
**Checklist**
> [Doc] Add documentation on using cert-manager with OLM

- internal/cmd/operator-sdk/scorecard/cmd.go
- internal/cmd/operator-sdk/scorecard/cmd_test.go
- website/content/en/docs/cli/operator-sdk_scorecard.md
The use of tags breaks disconnected environments when using mirrored images.
Reintroduces the use of Digest in the scorecard images instead of tags.
Bring back default support to disconnected environments using scorecard.
**Checklist**
- [ x] Add or update relevant sections of the docs website in [`website/content/en/docs`](https://github.com/operator-framework/operator-sdk/tree/master/website/content/en/docs)
Fixes: #6392
> Use digest instead of tags in scorecard images

- internal/cmd/operator-sdk/scorecard/cmd.go
- internal/cmd/operator-sdk/scorecard/cmd_test.go
- website/content/en/docs/cli/operator-sdk_scorecard.md
Cherry-pick of https://github.com/operator-framework/operator-sdk/pull/6393
> [v1.28.x] Use digest instead of tags in scorecard images (#6393)

- .github/workflows/deploy.yml
- Makefile
Remove "scorecard-storage", "scorecard-untar" from being built during the release process. I think this is the only place to change, though I am unsure if this is all the places.
In order for scorecard tests to work in DCI and disconnected environments, images need to be referenced by `sha` and not a `tag`, this would stop these two testing images from getting rebuilt on release, since the rarely change.
- Relates: #6417 
**Checklist**
> stop building "scorecard-storage", "scorecard-untar" images

- website/content/en/docs/best-practices/common-recommendation.md
- website/content/en/docs/building-operators/ansible/migration.md
- website/content/en/docs/building-operators/ansible/testing-guide.md
- website/content/en/docs/building-operators/golang/testing.md
- website/content/en/docs/overview/project-layout.md
- website/content/en/docs/upgrading-sdk-version/version-upgrade-guide.md
[Issue](https://github.com/operator-framework/operator-sdk/issues/6413)
Currently, molecule document links are deprecated, making the docs link checker fail. This PR addresses that. 
Currently, molecule document links are deprecated, making the docs link checker fail. This PR addresses that. 
**Checklist**
> updating molecule links #6413

- .golangci.yml
- internal/ansible/handler/logging_enqueue_annotation_test.go
- internal/ansible/handler/logging_enqueue_object_test.go
- internal/ansible/proxy/inject_owner_test.go
- internal/cmd/ansible-operator/version/cmd_test.go
- internal/cmd/helm-operator/version/cmd_test.go
- internal/cmd/operator-sdk/bundle/cmd_test.go
- internal/cmd/operator-sdk/bundle/validate/optional_test.go
- internal/cmd/operator-sdk/olm/cmd_test.go
- internal/cmd/operator-sdk/run/cmd_test.go
- internal/cmd/operator-sdk/run/packagemanifests/packagemanifests_test.go
- internal/generate/clusterserviceversion/bases/definitions/crd_test.go
- internal/generate/clusterserviceversion/clusterserviceversion_test.go
- internal/generate/clusterserviceversion/clusterserviceversion_updaters_test.go
- internal/generate/collector/clusterserviceversion_test.go
- internal/generate/packagemanifest/packagemanifest_test.go
- internal/olm/operator/registry/configmap/configmap_test.go
- internal/olm/operator/registry/configmap/registry_test.go
- internal/olm/operator/registry/configmap_test.go
- internal/olm/operator/registry/fbcindex/fbc_registry_pod_test.go
- internal/olm/operator/registry/index/registry_pod_test.go
- internal/olm/operator/registry/operator_installer_test.go
- internal/registry/labels_test.go
- internal/scorecard/bundle_test.go
- internal/scorecard/tests/bundle_test.go
- internal/validate/external_test.go
- test/e2e/ansible/cluster_test.go
- test/e2e/go/cluster_test.go
- test/e2e/helm/cluster_test.go
enable [ginkgolinter](https://github.com/nunnatsa/ginkgolinter) and fix findings.
Improve test code quality and prevent some bug, when using ginkgo and gomega.
> enable ginkgolinter and fix findings

- changelog/fragments/support_configmap_compression.yaml
- internal/olm/operator/registry/fbcindex/configMapWriter.go
- internal/olm/operator/registry/fbcindex/fbc_registry_pod.go
- internal/olm/operator/registry/fbcindex/fbc_registry_pod_test.go
Add the `--gzip-configmap=true` CLI parameter in order to compress the configMap, if it exeeds the max length.
Fix #6323 
It is currently not possible to run bundles with files larger than 1MB (the configMap limit). In these cases, the existing partitioning mechanism is not enough, and the action fails.
OLM solved this issue by compressing the configMap content. This PR motivation is to implement compression mechanism in operator-sdk as well.
By adding the `--gzip-configmap=true` parameter, operator-sdk now will compress the content of the config map. The commad of the pod is also modified in this case. It is not possible to extract the files in the configMap itself. The command now extracts the files to `/var/tmp` which is writable, and then run the opm server form this directory. …
> Fix 6323: compress the bundle configMap

- hack/check-links.sh
> ignore github access URI in htmlproofer

- changelog/fragments/01-update-kuttl.yaml
- images/scorecard-test-kuttl/Dockerfile
- images/scorecard-test-kuttl/main.go
Update kuttl to v0.15.0 in the scorecard-test-kuttl image
Fixes cleanup of created resources in kuttl (created resources of a kuttl test will be deleted after the test is run).
This change is especially relevant when using a single namespace for testing (default with this image).
See https://github.com/kudobuilder/kuttl/releases/tag/v0.14.0
**Checklist**
> Update kuttl to v0.15.0 in the scorecard-test-kuttl image

- go.mod
- go.sum
> OCPBUGS-11569: Update ubi to ubi-micro:8.7

- changelog/fragments/image-ansible-operator-go-version.yaml
- images/ansible-operator-2.11-preview/Dockerfile
- images/ansible-operator/Dockerfile
Project uses 1.19 when building locally but still use 1.18 for images pushed to Quay
Resolves https://github.com/operator-framework/operator-sdk/issues/6397
Bumps the golang base image from 1.18 to 1.19 to align with local builds
https://github.com/operator-framework/operator-sdk/issues/6397
**Checklist**
> Bump Golang version in ansible-operator images to 1.19

- changelog/fragments/docs-bump-go-version.yaml
- website/content/en/docs/contribution-guidelines/developer-guide.md
Go.mod is using golang 1.19 and pre-requisite is using 1.18. So Incrementing the developer guide to meet the golang version.
Bumped the Golang version.
#6385 
**Checklist**
Closes #6385
> Bumped the Golang version to 1.19 in pre-requisite documentation

- hack/generate/samples/internal/go/memcached-with-customization/memcached_with_customization.go
- testdata/go/v3/memcached-operator/main.go
- testdata/go/v3/monitoring/memcached-operator/main.go
- testdata/go/v4-alpha/memcached-operator/cmd/main.go
- testdata/go/v4-alpha/monitoring/memcached-operator/cmd/main.go
- website/content/en/docs/building-operators/golang/tutorial.md
Fixes #6314
Not 100% confident in the testdata edit, we'll see if this works.
> add blurb about recorder to golang tutorial and sample

- changelog/fragments/01-ubi-image-bump.yaml
- images/ansible-operator-2.11-preview/base.Dockerfile
- images/ansible-operator/base.Dockerfile
- images/custom-scorecard-tests/Dockerfile
- images/helm-operator/Dockerfile
- images/operator-sdk/Dockerfile
- images/scorecard-test/Dockerfile
- website/content/en/docs/building-operators/ansible/reference/proxy-vars.md
Bump ubi(-minimal) to 8.8.
Some Telco partners use helm-operator and ansible-operator as base images for their operators. Since they are interested in RH-certifying their images, they need to be based on the latest ubi(-minimal)8 in order to pass the [OpenSCAP](https://www.redhat.com/sysadmin/container-vulnerabilities-openscap) vulnerability checks. 
Related issue: https://github.com/operator-framework/operator-sdk/issues/6118 
**Checklist**
> Bump ubi(-minimal) to 8.8

- hack/check-links.sh
- Seems that the `make test-docs` is failing randomly. This updates the config and container version to reduce random failures.
Have passing CI for link url checking.
**Checklist**
> fix: update test-docs to fail less randomly

- changelog/fragments/01-operator-sdk-binary-variable.yaml
- internal/plugins/manifests/v2/init.go
- internal/testutils/olm.go
- testdata/ansible/memcached-operator/Makefile
- testdata/go/v3/memcached-operator/Makefile
- testdata/go/v3/monitoring/memcached-operator/Makefile
- testdata/go/v4-alpha/memcached-operator/Makefile
- testdata/go/v4-alpha/monitoring/memcached-operator/Makefile
- testdata/helm/memcached-operator/Makefile
This allows the operator-sdk install to customizable via Makefile. If necessary, a specific version can be downloaded and used.
Useful for users to be able to customize their environment and usage of the operator-sdk binary in their project or project(s) e.g. a user works on multiple different projects that aren't on the same version, CI systems that might require a specific version, etc.
**Checklist**
> feat: allow operator-sdk install to be customizable

- images/ansible-operator-2.11-preview/base.Dockerfile
- images/ansible-operator/base.Dockerfile
- Ignores more recent CVEs that have presented when attempting to build the ansible base images. This is meant to be temporary until we can properly resolve them by bumping the ansible version used in the base images. This will allow us to continue building base images for new releases in the meantime.
- Fix base image build failures so that we can continue building new base images for new releases of the Operator-SDK
**Checklist**
> (fix): (ansible): temporarily ignore CVEs

- changelog/fragments/01-hash-cache-directory-name.yaml
- internal/olm/fbcutil/util.go
- internal/olm/fbcutil/util_test.go
Fix #6476 
In `run bundle-upgrade`, hash the cache directory name to avoid error of too long file name.
`run bundle-upgrade` is failing if the bundle image names are long. See #6476 
**Checklist**
> Fix RFE-4185: run bundle-upgrade with long image names

- website/content/en/docs/building-operators/ansible/development-tips.md
- website/content/en/docs/building-operators/ansible/testing-guide.md
Update docs to remove deprecated references and replace with the correct references.
> Update docs to remove deprecated references

- changelog/fragments/02-olm-install-retry.yaml
- internal/olm/client/client.go
- internal/olm/client/client_test.go
When installing OLM, retry creating resources, if the CRD is not ready yet.
Fixes: #6489
On olm install command, if the creation of a resource fails with "no-match" error, retry creating it, assuming the CRD is not ready yet, but is going to be ready very soon.
Bug fix. See #6489 
##Checklist
> Fix a bug in olm install

- go.mod
- go.sum
- hack/generate/cncf-maintainers/main.go
- internal/ansible/proxy/cache_response.go
- internal/ansible/proxy/inject_owner.go
- internal/ansible/proxy/requestfactory/requestinfo.go
- internal/cmd/operator-sdk/generate/internal/relatedimages.go
- internal/olm/client/status.go
- internal/olm/operator/install_mode.go
- internal/olm/operator/registry/operator_installer.go
- internal/olm/operator/registry/operator_installer_test.go
Use the `k8s.io/utils` implemention of `set` rather than the `apimachinery` `sets`.
Following https://github.com/kubernetes/utils/pull/243 it's likely that the k8s.io/utils version will end up being the canonical one.
**Checklist**
> Use k8s.io/utils set instead of apimachinery sets

- changelog/fragments/doc info.yaml
- website/content/en/docs/building-operators/ansible/reference/retroactively-owned-resources.md
Description of the change:
Updated Reference from " to_be_owned.namespace "
to " to_be_owned.metadata.namespace " at line 186.
Signed-off-by: wasup-yash trooper0018080@gmail.com
Motivation for the change:
Closes #6318
> updated owner reference

- website/content/en/docs/building-operators/golang/installation.md
- website/layouts/partials/head.html
- website/layouts/partials/navbar.html
* Delete `_internal/google_news.html` since its deprecated.
* Update '.URL' to '.Permalink' since it can’t evaluate field URL in type *hugolib.pageState.
* Update Go version from '1.18' tp '1.19' in `building-operator` section.
**Checklist**
> Documentation fix

- changelog/fragments/05-template.yaml
- internal/helm/client/actionconfig.go
- internal/helm/client/secrets_watch.go
Helm stores its state in secrets inside the cluster.
Instead of listing these secrets before every reconciliation of every release, we use an informer to query a local secrets list.
Whats the current status of the [helm-operator-plugins](https://github.com/operator-framework/helm-operator-plugins) repo, should I also create a MR there?
We are running 2 helm-operators with 50 CRs each in a namespace with over 1000 secrets.
Listing these secrets, even with a filter, takes more than 1 second.
Running multiple of these list queries in parallel generates a high load on the kubernetes apiserver and etcd.
Combined with the default reconcile period of 1m this results in a constant high load.
Before and After metrics (after installing …
> Helm: Use informer to list helm secrets to improve performance

- internal/scorecard/tests/olm.go
Resources with no status produce the following warning:
> ... does not have status spec. Note thatAll objects that represent a
> physical resource ...
This adds the missing space between "that" and "All", and lower-cases the "a" in "all".
This makes the suggestions easier to read.
**Checklist**
> scorecard: add missing space to suggestion

- .github/workflows/deploy.yml
- Don't run the gpg and quay login steps for the jobs in https://github.com/operator-framework/operator-sdk/blob/master/.github/workflows/deploy.yml when Dependabot has created the PR. This makes it so CI can run properly on Dependabot PRs without Dependabot having access to secret values.
- Make it possible for Dependabot PRs to pass CI so we can truly start taking advantage of the benefits of Dependabot
**Checklist**
> (actions): fix some dependabot actions issues

- go.mod
- go.sum
Updating logrus to latest version.
- Closes: #6502 
**Checklist**
> updating logrus dependency to latest to resolve CVE

- changelog/fragments/03-run-bundle-cmd.yaml
- internal/olm/operator/bundle/install.go
During the creation of a new catalog image using the operator-sdk, a critical bug was identified where existing FBC (File-Based Configuration) files were not being copied to the new location of the catalog image. Consequently, the generated catalog image was missing essential FBC files, leading to incorrect behavior and potential issues for end-users.
This bug fix addresses the root cause of the problem by ensuring that both the old and new FBC files are correctly included in the catalog image creation process. With this fix, the resulting catalog image will contain all the necessary FBC files, thereby resolving the issue of missing configurations and ensuring the operator functions as expected. Users can now rely on the updated catalog image to access and …
> fix: merge existing and extra fbc while rendering the index image

- images/ansible-operator/base.Dockerfile
- Sets the environment variable `CARGO_NET_GIT_FETCH_WITH_CLI=true` for rust cross compilation
- Fix the error that occurred in https://github.com/operator-framework/operator-sdk/actions/runs/5661692798/job/15340134785 
**Checklist**
> (ci): fix cross compilation

- images/ansible-operator/base.Dockerfile
- Copies binaries from the builder stage by adding `COPY --from=builder /usr/local/bin /usr/local/bin` to the steps in the final stage
- Ansible binaries were missing in the base image as can be seen by https://github.com/operator-framework/operator-sdk/actions/runs/5672628145/job/15372988930?pr=6518#step:5:545
**Checklist**
> (bugfix): Copy ansible binaries from builder stage when building the base image

- changelog/fragments/helm-operator-rollback.yaml
- internal/helm/controller/reconcile.go
- internal/helm/controller/reconcile_test.go
- internal/helm/release/manager.go
- testdata/ansible/memcached-operator/Makefile
- testdata/go/v3/memcached-operator/Makefile
- testdata/go/v3/monitoring/memcached-operator/Makefile
- testdata/go/v4-alpha/memcached-operator/Makefile
- testdata/go/v4-alpha/monitoring/memcached-operator/Makefile
- testdata/helm/memcached-operator/Makefile
- website/content/en/docs/building-operators/helm/reference/advanced_features/annotations.md
Whenever a helm-based operator encounters an error during reconcilliation, by default, it would attempt to perform a rollback with the `--force` option. While this works as expected in most scenarios, there are a few edge cases where performing a rollback with `--force` could have undesired side effects.
Adding annotation to the custom resource, `helm.sdk.operatorframework.io/rollback-force: false` therefore allows a user, to change the default behavior of the helm-based operator whereby, rollbacks will be performed without the `--force` option whenever an error is encountered.%                                                                                                         
This change was motivated by the issue #6494 …
> Allow users to add annotation to set configure rollback

- website/content/en/docs/upgrading-sdk-version/v1.25.0.md
Fixes https://github.com/operator-framework/operator-sdk/issues/6525.
> Add missing "controller-tools" update instructions to the v1.25.0 migration guide

- .github/ISSUE_TEMPLATE.md
- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/feature-request.md
- .github/ISSUE_TEMPLATE/support-question.md
- .github/PULL_REQUEST_TEMPLATE.md
- Updates the issue and PR templates to point towards the new ansible repo at https://github.com/operator-framework/ansible-operator-plugins for filing issues and creating PRs
- Drive ansible related requests towards the new https://github.com/operator-framework/ansible-operator-plugins repository
**Checklist**
> (repo): update issue+PR templates to point to new ansible repo

- website/config.toml
- website/content/en/docs/building-operators/ansible/tutorial.md
- website/content/en/docs/building-operators/golang/migration.md
- website/content/en/docs/building-operators/golang/references/markers.md
- website/content/en/docs/building-operators/golang/tutorial.md
- website/content/en/docs/building-operators/helm/tutorial.md
- website/content/en/docs/upgrading-sdk-version/v0.1.0-migration-guide.md
- website/content/en/docs/upgrading-sdk-version/v0.19.0.md
- website/content/en/docs/upgrading-sdk-version/version-upgrade-guide.md
- Updates broken links due to the Netlify branch changes that were made
- Fix the links that are causing the sanity link checker to fail in CI
**Checklist**
> (docs): update broken links

- .github/workflows/deploy.yml
- .github/workflows/integration.yml
- .github/workflows/test-go.yml
- .github/workflows/test-helm.yml
- .github/workflows/test-sample-go.yml
- .github/workflows/test-sanity.yml
- go.mod
- go.sum
- images/custom-scorecard-tests/Dockerfile
- images/helm-operator/Dockerfile
- images/operator-sdk/Dockerfile
- images/scorecard-test-kuttl/Dockerfile
- images/scorecard-test/Dockerfile
- testdata/go/v3/memcached-operator/Makefile
- testdata/go/v3/monitoring/memcached-operator/Makefile
- testdata/go/v4-alpha/memcached-operator/Makefile
- testdata/go/v4-alpha/monitoring/memcached-operator/Makefile
- testdata/helm/memcached-operator/Makefile
- website/content/en/docs/building-operators/golang/installation.md
- website/content/en/docs/contribution-guidelines/developer-guide.md
- website/content/en/docs/installation/_index.md
- Bumps Go version in `go.mod` to 1.21
- Updates GitHub actions to pull Go version from `go.mod` file
- Regenerates testdata
- Update to latest Go version to pick up any fixes
- fixes #6603 
**Checklist**
> (chore): Bump Go version to 1.21 + regenerate testdata

- internal/olm/fbcutil/util.go
- internal/olm/operator/bundle/install.go
- internal/olm/operator/registry/fbcindex/fbc_registry_pod.go
- internal/olm/operator/registry/index_image.go
- website/content/en/docs/cli/operator-sdk_run_bundle.md
The  `--init-image` argument  has been added to the `run bundle` command. This argument will override the docker.io/library/busybox image, used when creating a registry pod. Not including the argument will cause the same behavior as before this change.
The forced use of the image docker.io/library/busybox causes issues for users making use of operator-sdk run bundle. Dockerhub rate limits container image pulls. The rate limiting will cause operator-sdk run bundle to fail once `run bundle` has been used too many times within a time period.
**Checklist**
Closes #6578
> Make `run bundle` init image choosable

- Makefile
Add checking for set GOBIN on `make install`
With this change we catch situation where GOBIN isn't defined and `make install` silently fails.
```
$ unset GOBIN
$ make install
Error: GOBIN is not set
make: *** [Makefile:75: install] Error 1
$ source ~/.bash_profile
$ echo $GOBIN/
/usr/local/go/bin/
$ make install
go install -gcflags "all=-trimpath=/home/user1" -asmflags "all=-trimpath=/home/user1" -ldflags " -X 'github.com/operator-framework/operator-sdk/internal/version.Version=v1.32.0+git' -X 'github.com/operator-framework/operator-sdk/internal/version.GitVersion=v1.32.0-6-g034aef67-dirty' -X 'github.com/operator-framework/operator-sdk/internal/version.GitCommit=034aef6779729a30ac3d716f93a01824ed8dd3c7' -X …
```
> Check GOBIN on make install

- internal/bindata/olm/manifests.go
> chore: remove refs to deprecated io/ioutil

- go.mod
- go.sum
- internal/cmd/operator-sdk/bundle/validate/optional.go
- internal/cmd/operator-sdk/bundle/validate/optional_test.go
This pull request updates the operator-framework api dependency to 0.20.0.
As part of that consumption, this updates the `operator-sdk bundle validate` command to consume the new hierarchy of optional validators, given the deprecation of the optional `operatorhub` validator. See https://github.com/operator-framework/api/pull/304 for more info.
> Consume 0.20.0 version of operator framework api

- internal/cmd/operator-sdk/alpha/config3alphato3/convert_config_3-alpha_to_3.go
- internal/cmd/operator-sdk/generate/kustomize/manifests.go
- testdata/go/v3/memcached-operator/Makefile
- testdata/go/v3/monitoring/memcached-operator/Makefile
- testdata/go/v4/memcached-operator/Makefile
- testdata/go/v4/monitoring/memcached-operator/Makefile
- testdata/helm/memcached-operator/Makefile
- When multigroup is true, the api directory (which is considered the project layout standard) is now used instead of apis. See https://kubebuilder.io/migration/manually_migration_guide_gov3_to_gov4
This appears to have been missed in the latest release which uses go/v4.
> fix: migrate apis directory to api per standard

- changelog/fragments/helm-fix-docker-buildx.yaml
- internal/plugins/helm/v1/scaffolds/internal/templates/makefile.go
- testdata/helm/memcached-operator/Makefile
Closes #6660 
This is the first time for me to send PR to this repository. Please let me know if I'm on the wrong way.
I wasn't sure if a changelog was necessary, but I wrote one anyway.
Thanks in advance 😃 
Fix an issue that multi-arch images cannot be built from the project Makefile, by following two changes:
- Remove `test` target from `docker-buildx` target
- Remove `sed` command that adds `--platform=${BUILDPLATFORM}` so that `${TARGETPLATFORM}` is specified as `--platform` according to BuildKit defaults
**Checklist**
> fix: fix an issue that multi-arch images cannot be built from the project makefile

- website/content/en/docs/building-operators/golang/testing.md
Add note about chainsaw in the docs.
If you need more infos :point_down:
- GitHub: https://github.com/kyverno/chainsaw
- Docs: https://kyverno.github.io/chainsaw
- Slack: https://kubernetes.slack.com/archives/C067LUFL43U
We presented chainsaw to the community meeting last week and received good feedback.
It would be awesome to have it listed in the docs.
**Checklist**
> docs: add note about chainsaw

- OWNERS_ALIASES
> add acornett21 to sdk-approves list

- OWNERS_ALIASES
Add @OchiengEd  to operator sdk approvers
**Checklist**
> Add OchiengEd to sdk-approvers

- website/content/en/docs/building-operators/golang/operator-scope.md
- correct spelling
- fix Markdown syntax
**Checklist**
> docs: correct spelling of Operator scope

- internal/olm/fbcutil/util.go
- website/content/en/docs/cli/operator-sdk_run_bundle.md
Change untar image from busybox to UBI image as #5191
Remove dependency on dockerhub
**Checklist**
> Change DefaultIndexImage to UBI

- changelog/fragments/01-ansible-operator-plugin-upgrade.yaml
- go.mod
- go.sum
Update version of `github.com/operator-framework/ansible-operator-plugins` to v1.34.2
Updating the version of `github.com/operator-framework/ansible-operator-plugins` ensures that the ansible operator plugin is on go 1.21
**Checklist**
> Bump ansible operator plugin to v1.34.2

- images/custom-scorecard-tests/Dockerfile
- images/helm-operator/Dockerfile
- images/operator-sdk/Dockerfile
- images/scorecard-test/Dockerfile
Current base container image ubi-minimal tag version 8.9 contains [several security vulnerabilities](https://catalog.redhat.com/software/containers/ubi8/ubi-minimal/5c359a62bed8bd75a2c3fba8?architecture=amd64&image=6639e6e904a1a78fa9e8e6c4&container-tabs=security) that are [not present](https://catalog.redhat.com/software/containers/ubi8/ubi-minimal/5c359a62bed8bd75a2c3fba8?architecture=amd64&image=664fbe740cc7edbe34c4d059) in the 8.10 version. This PR updates the references in all Dockerfiles to point to 8.10
@everettraven PTAL.
> Change base image ubi-minimal from 8.9 to 8.10 in all Dockerfiles

- website/content/en/docs/upgrading-sdk-version/v1.36.0.md
Fix formatting - bad rendering of the first codeblock and other codeblocks should be nested
Hard to read!
**Checklist**
Skipped changelog - formatting only.
> Fix formatting

- website/content/en/docs/upgrading-sdk-version/v1.36.0.md
> Fix formatting (#6797)

- go.mod
- go.sum
Update java-operator-plugins to v0.11.1.
https://github.com/operator-framework/operator-sdk/issues/6645
Fixed #6645
> Bump java-operator-plugins to v0.11.1

- go.mod
- go.sum
> updating docker dependencies to address GHSA-v23v-6jw2-98fq

- changelog/fragments/01-template.yaml
- go.mod
- go.sum
- internal/cmd/operator-sdk/cli/cli.go
- website/content/en/docs/cli/operator-sdk.md
Fixes #6819 
Removing java-operator-plugins and the plugin quarkus so the command `operator-sdk init --plugins quarkus` will no longer work. This is a breaking change.
The team behind the Quarkus plugin no longer want to support this integration and users should instead use the Quarkus provided API to generate projects (https://github.com/quarkiverse/quarkus-operator-sdk?tab=readme-ov-file#bootstrapping-a-project)
**Checklist**
> Remove java-operator-plugins

- website/content/en/docs/building-operators/ansible/reference/webhooks.md
Pointing to main doc site, instead of version specific site.
The site no longer exists at the version URL.
**Checklist**
> updating both webhook links to reference main docs url

- changelog/fragments/02-remove-helm-hybrid-plugin.yaml
- go.mod
- go.sum
- internal/cmd/operator-sdk/cli/cli.go
- internal/util/projutil/project_util.go
- website/content/en/docs/cli/operator-sdk.md
Removing the `helm-operators-plugin` dependency, so that we no longer support the `hybrid.helm` type.
This plugin saw low adoption, so to make development/maintenance/support easier for `operator-sdk` it makes sense to remove this plugin.
**Checklist**
> removing helm hybrid operator plugin

- website/content/en/docs/building-operators/golang/tutorial.md
Removes v4-alpha from the tutorial.
This PR addresses the issue mentioned https://github.com/operator-framework/operator-sdk/issues/6778
Closes: https://github.com/operator-framework/operator-sdk/issues/6778
**Checklist**
> docs: Update go tutorial

- changelog/fragments/fix-run-bundle-yaml-split.yaml
- internal/olm/operator/registry/fbcindex/fbc_registry_pod.go
- internal/olm/operator/registry/fbcindex/fbc_registry_pod_test.go
> fix: make `run bundle` use proper YAML library to split documents

- go.mod
- go.sum
Updating ansible-operator-plugin to v1.36.1 that has the proper metrics rbac scaffolding inplace
To have all operator types have the proper scaffolding, now that `kube-rbac-proxy` scaffolding is removed.
- Relates:#6730
**Checklist**
> updating ansible plugin to 1.36.1

- website/content/en/docs/building-operators/ansible/development-tips.md
- website/content/en/docs/building-operators/golang/operator-scope.md
- website/content/en/docs/building-operators/golang/references/logging.md
- website/content/en/docs/building-operators/helm/reference/advanced_features/max_concurrent_reconciles.md
Remove references to `kube-rbac-proxy` from the main parts of the website. References in the migration docs can remain.
To accuratly reflect the the state of scaffolding.
- Relates: #6730 
**Checklist**
> removing kube-rbac-proxy from website docs

- testdata/go/v4/memcached-operator/Makefile
- testdata/go/v4/monitoring/memcached-operator/Makefile
- testdata/helm/memcached-operator/Makefile
To fix tests
so pr's pass
**Checklist**
> fix test data scaffolding...again

- go.mod
- go.sum
- Updates `golang.org/x/net` to latest
- Fix CVE-2024-45338
- Fixes: #6882
**Checklist**
> fixing CVE-2024-45338 in golang.org/x/net

- website/content/en/docs/upgrading-sdk-version/v1.38.0.md
Fix very small typo in 1.38.0 migration documentation on line 196 of file`operator-sdk/website/content/en/docs/upgrading-sdk-version/v1.38.0.md`.
Changed `monitor/yaml` to `monitor.yaml`
Full original line: '13) [go/v4, helm/v1, ansible/v1] Update your `/config/prometheus/monitor/yaml` file with the below changes:'
Full new line: '13) [go/v4, helm/v1, ansible/v1] Update your `/config/prometheus/monitor.yaml` file with the below changes:'
Simply fixing a small typo that would prevent a user from doing a direct copy and paste of this file name without causing an error.
> fix small typo in filename referenced in documentation

- website/config.toml
- move v1.21 from netlify to gh like in toml file
- to be able to add a new netlify route for a new release
**Checklist**
> move v1.22 from netlify to gh like in toml file

- internal/helm/client/client.go
This PR fixes the issue where the primary custom resource would randomly get assigned "operator-sdk/primary-resource" and "operator-sdk/primary-resource-type" annotations when helm-operator is used.
We use helm operator to deploy our software in OpenShift environment.  However, our primary custom resource would get random annotations assigned , e.g.,
```
apiVersion: apm.neuvector.com/v1alpha1
kind: Neuvector
metadata:
annotations:
operator-sdk/primary-resource: /neuvector-binding-nvvulnerabilityprofiles
operator-sdk/primary-resource-type: ClusterRoleBinding.rbac.authorization.k8s.io
```
The resource name and resource type would change randomly after each deployment. 
After some debugging, it looks like …
> fix: primary-resouce is created in wrong place.

- website/content/en/docs/upgrading-sdk-version/v1.39.0.md
The update instructions for v1.39.0 have a template that contains the "memcached-operator" name but I do believe that this should be replaced by the user with their operator name. I replaced it with "<operator-name>" as in the other update instructions.
Make the upgrade path better.
> docs: Replace memcached-operator in v1.39.0 update instructions

- internal/olm/operator/registry/fbcindex/fbc_registry_pod.go
- internal/olm/operator/registry/index/registry_pod.go
- internal/olm/operator/registry/index_image.go
- website/content/en/docs/cli/operator-sdk_run_bundle-upgrade.md
- website/content/en/docs/cli/operator-sdk_run_bundle.md
```diff
❯ go run cmd/operator-sdk/main.go run bundle 
Error: accepts 1 arg(s), received 0
Usage:
operator-sdk run bundle <bundle-image> [flags]
Flags:
--ca-secret-name string                     Name of a generic secret containing a PEM root certificate file required to pull bundle images. This secret *must* be in the namespace that this command is configured to run in, and the file *must* be encoded under the key "cert.pem"
--decompression-image string                image used in an init container in the registry pod to decompress the compressed catalog contents. cat and gzip binaries are expected to exist in the PATH (default "registry.access.redhat.com/ubi8:8.9")
-h, --help                                      help for bundle
+     --image-pull-policy …
```
> Fix Allow IfNotPresent policy when `operator-sdk run bundle` #6795

- Makefile
Without this change we are unable to run make install on mac os envs:
```
$ make install
Error: GOBIN is not set
make: *** [install] Error 1
```
> 🌱 (fix) fis GOBIN to allow run make install in Mac Os

- Makefile
- internal/helm/release/manager.go
Upgrade golangci from 1.63.4 to 1.64.8
Otherwise, with golang 1.24 installed locally is not possible to run ` make test-sanity`
> 🌱 Upgrade golangci from 1.63.4 to 1.64.8

- changelog/fragments/generalize-container-tool.yaml
- internal/plugins/helm/v1/scaffolds/internal/templates/makefile.go
- internal/plugins/manifests/v2/init.go
- testdata/go/v4/memcached-operator/Makefile
- testdata/go/v4/monitoring/memcached-operator/Makefile
- testdata/helm/memcached-operator/Makefile
This PR generalizes the container tool usage in the bundle build target to respect the `CONTAINER_TOOL` variable. The change replaces the hardcoded `docker` command with `$(CONTAINER_TOOL)` in the `bundle-build` target of the Makefile template, making it consistent with other container-related targets in the operator-sdk.
Currently, the bundle build target hardcodes the use of `docker` as the container tool, which is inconsistent with other parts of the operator-sdk that respect the `CONTAINER_TOOL` variable. This change:
1. Makes the bundle build process more flexible by allowing users to use alternative container tools like podman
2. Maintains consistency with the rest of the operator-sdk tooling
3. Follows the existing …
> feat: generalize container tool usage in Makefile template

- go.mod
- go.sum
updating ansible operator plugin to v1.38.1.
to have the proper version of the plugin so scaffolding works properly.
**Checklist**
> updating ansible-operator-plugin to v1.38.1

- website/content/en/docs/building-operators/helm/reference/watches.md
In the helm watches reference mention the dryRunOption  that was added in https://github.com/operator-framework/operator-sdk/pull/6691
> Document helm operator dryrunOption

- website/content/en/docs/upgrading-sdk-version/v1.40.0.md
Fixing broken link
- passing ci.
- correct links loading.
**Checklist**
> fix broken link in 1.40.0 docs

- website/content/en/docs/upgrading-sdk-version/v1.40.0.md
Thank you team for your work and attention to this.
I simply fixed a single character typo.  Documentation referred to the file `kutomization.yaml`. I corrected it by adding an `s` so that it now reads `kustomization.yaml`.
Although this is a very trivial typo, I noticed it when my command failed as I had copy/pasted the incorrect file name. Fixing this will hopefully benefit others who copy/paste command names like this.
**Checklist**
> fix typo in filename `kustomization.yaml`

- images/operator-sdk/Dockerfile
- Updating the operator-sdk Dockerfile to copy go from the builder images, instead of downloading.
- to speed up build time.
- to lessen burden of remembering to update the `GO_VERSION` for every update.
**Checklist**
> use go version from builder image, instead of downloading in Dockerfile

- website/content/en/docs/best-practices/observability-best-practices.md
To have consistent documentation with external documentation.
- Fixes: #6992
**Checklist**
> update observability docs to align with prometheus's docs

- internal/plugins/helm/v1/api.go
- internal/plugins/helm/v1/chartutil/chart.go
- Add support for OCI helm registries client to helm's download manager.
- Updating flag arguments for clarification
- Added an example for clarification
- Fixes: #610
**Testing**
- Example in the PR now works
-  The follow where `oci://` is passed is also supported `operator-sdk create api --group demo --version v1alpha1 --kind Nginx --helm-chart oci://registry-1.docker.io/bitnamicharts/nginx:21.1.21`
**Checklist**
> add support to scaffold oci helm registry charts
